10073 reduced quarkus image size
keycloak/keycloak pull request #10074
Opened 2022-02-08 16:15 UTC by sschu

Implements https://github.com/keycloak/keycloak/issues/10073

2022-02-08 16:51 UTC, andreaTP approved these changes, later dismissed
LGTM

2022-02-09 07:20 UTC, sschu commented
The test run failure might be related to my change, I will have a look...

2022-02-09 08:31 UTC, sschu commented
Alright, looks like COPY always uses root as owner unless you tell it to do otherwise. Permissions are taken over. Fixed that.

2022-02-09 09:55 UTC, andreaTP commented
Happy to see that the Quarkus integration tests on Docker are effective! 🎉

2022-02-09 12:56 UTC, sschu commented
I highly doubt the last build failure has to do with my changes. Is there any way I can trigger another build?

2022-02-09 14:10 UTC, DGuhr submitted a review, later dismissed

2022-02-09 14:13 UTC, stianst requested changes
Just tested this out here with podman and getting the following error:
`
Error: error building at STEP "COPY --from=build-env --chown 1000:0 /opt/keycloak /opt/keycloak": COPY only supports the --chmod=<permissions> --chown=<uid:gid> and the --from=<image|stage> flags
`

2022-02-09 14:20 UTC, stianst commented on quarkus/container/Dockerfile
> +COPY --from=build-env --chown 1000:0 /opt/keycloak /opt/keycloak
```suggestion
COPY --from=build-env --chown=1000:0 /opt/keycloak /opt/keycloak
```

2022-02-09 15:18 UTC, stianst approved these changes

2022-02-09 15:44 UTC, DGuhr approved these changes

2022-02-09 17:09 UTC, pedroigor approved these changes

2022-02-09 18:06 UTC, sschu commented
Strange, its always the same error in the build:
`Could not transfer artifact org.picketbox:picketbox:pom:5.0.3.Final-redhat-00008 from/to jboss-enterprise-maven-repository (https://maven.repository.redhat.com/ga/): transfer failed for https://maven.repository.redhat.com/ga/org/picketbox/picketbox/5.0.3.Final-redhat-00008/picketbox-5.0.3.Final-redhat-00008.pom, status: 500 Internal Server Error` looks like the repository has a problem.

2022-02-10 07:01 UTC, merged