Revising content of outgoing HTTP requests guide
keycloak/keycloak pull request #10078
Opened 2022-02-08 22:26 UTC by andymunro

Reworded content and formatted to make it easier to skim

Closes #110075

One more PR for review, @stianst

2022-02-11 11:01 UTC, DGuhr requested changes

2022-02-11 16:58 UTC, andymunro commented on docs/guides/src/main/server/outgoinghttp.adoc
> +.Example of proxy mappings and environment variables
Okay, @DGuhr let me know.

2022-02-24 08:02 UTC, DGuhr requested changes

2022-02-24 08:02 UTC, DGuhr commented on docs/guides/src/main/server/outgoinghttp.adoc
> +.Example of proxy mappings and environment variables
Then I'd say change back to third level headline would be great, thank you.

2022-02-24 16:50 UTC, andymunro commented
Thanks, @DGuhr. Updated now.

2022-02-25 08:23 UTC, DGuhr approved these changes

2022-02-25 08:29 UTC, stianst approved these changes

2022-02-25 08:30 UTC, merged