docs(keycloak-js): add README
keycloak/keycloak pull request #10085
Opened 2022-02-09 11:19 UTC by bmacher

The current package of the javascript adapter (also known as keycloak-js) lacks a README and thus any documentation. This can be found elsewhere. However, it would be nice if it was at least linked. Since this is only a small effort, I thought I can skip the issue and create a pull request directly.

2022-03-01 10:34 UTC, jonkoops requested changes
In order for this file to be included into the NPM package you will have to add some additional code so that it is included in the distribution.

If you search the project for `**/*.mjs` you will find all locations where this should be added. Please add an equivalent for matching all `.md` files there.

2022-03-02 15:22 UTC, bmacher commented
Thanks for your response. I will cover that in a few days.

2022-03-15 13:25 UTC, bmacher commented
I cannot fine any files ending with `.mjs`, when running `find .  -name "*.mjs"`.

2022-03-15 13:37 UTC, jonkoops commented
@bmacher I am referring to the contents of the files, you'll find several entries in XML files.

2022-03-15 13:42 UTC, jonkoops requested changes

2022-03-15 13:42 UTC, jonkoops commented on adapters/oidc/js/README.md
> +The documentation can be found here: http://www.keycloak.org/docs/latest/securing_apps/index.html#_javascript_adapter
```suggestion
The documentation can be found here: https://www.keycloak.org/docs/latest/securing_apps/index.html#_javascript_adapter
```

2022-03-15 13:47 UTC, edewit submitted a review, later dismissed

2022-04-07 07:52 UTC, bmacher commented
Hi @jonkoops I included the files. Hope, everything is fine now. :-)

2022-04-07 11:15 UTC, jonkoops commented
@bmacher I am looking to push some changes to your branch, could you give me access to your fork?

2022-04-08 06:10 UTC, bmacher commented
@jonkoops I invited you into the repo. Is there a way to only grant permissions on the fork?

2022-04-08 07:31 UTC, jonkoops approved these changes

2022-04-08 07:32 UTC, edewit approved these changes

2022-04-08 07:32 UTC, jonkoops commented
@ssilvert could you review and merge this PR?

2022-04-08 16:43 UTC, ssilvert approved these changes

2022-04-08 16:43 UTC, merged