Add extensions as init container
keycloak/keycloak pull request #10306
Opened 2022-02-17 18:53 UTC by andreaTP

This is a stop-gap solution for #9785 , I open it in draft since we need to discuss more.

Resolves: #9785

2022-02-21 13:37 UTC, pedroigor submitted a review, later dismissed

2022-02-22 10:58 UTC, vmuzikar requested changes
Thanks @andreaTP, added a few comments.

Before merging this, we need to align with @stianst on the container that will be used. In the operator code, we're using [existing init container](https://quay.io/repository/keycloak/keycloak-init-container) what was originally meant for WF dist. But in the CI, we're using a [new init container](https://github.com/keycloak/keycloak/tree/26df1b007d8ac66796961af2d17c2f59914949c0/quarkus/init-container). This needs to be aligned. I see 3-4 options.
1. Rely only on the [`legacy` tag](https://quay.io/repository/keycloak/keycloak-init-container?tab=tags) (effectively it is latest) of init container both in operator and the tests. We don't plan any changes in it anyway, so it should be ok-ish. It is an stop-gap solution in any case, before we switch to some `kc.sh` command.
2. Rely only on the `legacy` tag but checkout the [keycloak-containers repo](https://github.com/keycloak/keycloak-containers) and build it in the CI for tests. It's not ideal but we'd still catch potential issues sooner.
3. Rely on the[ new init container](https://github.com/keycloak/keycloak/tree/26df1b007d8ac66796961af2d17c2f59914949c0/quarkus/init-container) both in operator and the CI.
4. Per @stianst suggestion, we could go ahead and really implement it as a simple `kc.sh extensions` command without using an init container at all.

2022-02-22 11:51 UTC, andreaTP commented on operator/src/main/java/org/keycloak/operator/v2alpha1/KeycloakDeployment.java
> +import static org.keycloak.operator.Constants.*;
done

2022-02-22 11:52 UTC, andreaTP commented on operator/src/main/java/org/keycloak/operator/v2alpha1/KeycloakDeployment.java
> +        var initContainers = baseDeployment.getSpec().getTemplate().getSpec().getInitContainers();
removed

2022-02-22 11:52 UTC, andreaTP commented on operator/src/main/java/org/keycloak/operator/v2alpha1/KeycloakDeployment.java
> +        baseDeployment.getSpec().getTemplate().getSpec().setInitContainers(initContainers);
I think this is good practice ... but not fussy, fixed

2022-02-22 11:53 UTC, andreaTP commented on operator/src/main/resources/application.properties
> +operator.keycloak.init-container-image=quay.io/keycloak/keycloak-init-container:latest
done

2022-02-22 11:54 UTC, andreaTP commented on operator/src/test/java/org/keycloak/operator/KeycloakDeploymentE2EIT.java
> +                            "https://github.com/aerogear/keycloak-metrics-spi/releases/download/2.5.3/keycloak-metrics-spi-2.5.3.jar"));
make sense 👍

2022-02-22 12:04 UTC, andreaTP commented
@vmuzikar thanks for the review, I believe I addressed all the outstanding comments.

Regarding alignment on which init container to use, I think that the best option is to use the new init container(3) in operator and CI. Happy to complete this PR automating the new container publishing (even if I would need some help for doing it :-) ).

> implement it as a simple `kc.sh extensions` command without using an init container at all.

We already discussed and agreed, as a team, that this is not the right time to go in this direction(keeping the door open for it in the future).

2022-02-23 14:21 UTC, abstractj reviewed
@andreaTP could you please rebase?

2022-02-23 15:22 UTC, andreaTP commented
@abstractj done, ready for review again 🙂

2022-02-24 10:49 UTC, andreaTP commented
@vmuzikar this should be ready for a final review.

2022-02-24 17:43 UTC, vmuzikar approved these changes
LGTM, thanks @andreaTP! This is ready to be merged.

2022-02-24 18:17 UTC, pedroigor approved these changes

2022-02-24 18:17 UTC, merged