hide scopes from scopes_supported in discovery endpoint
keycloak/keycloak pull request #10409
Opened 2022-02-23 11:45 UTC by cgeorgilakis

closes #10388

2024-06-19 12:21 UTC, cgeorgilakis commented
I have updated to latest main.
Could you review it in order to be able to hide a scope from scopes_supported in discovery endpoint?

2024-06-19 12:55 UTC, ahus1 commented
The linting in the admin UI complains, please check the logs. I'm switching this PR to "draft" in the meantime. Please switch it back to "ready-for-review" when you want to have it reviewed again.

Unfortunately the Admin UI tests are currently unstable, see #30492 - if those tests fail again, it might be worth waiting for that issue to be closed first and then rebase, or asking a maintainer to re-run the tests.

2025-06-25 07:26 UTC, dalbani commented
@cgeorgilakis: would you mind refreshing your PR, should you have the time to do so? If not, I'm willing to have a try, so that we can have hopefully have this feature added to Keycloak.
Thanks!

2025-06-25 08:08 UTC, cgeorgilakis commented
> @cgeorgilakis: would you mind refreshing your PR, should you have the time to do so? If not, I'm willing to have a try, so that we can have hopefully have this feature added to Keycloak. Thanks!

Unfortunatelly no this period. Feel free to rebase it and proceed with PR.

2025-10-24 06:42 UTC, cgeorgilakis commented
> The linting in the admin UI complains, please check the logs. I'm switching this PR to "draft" in the meantime. Please switch it back to "ready-for-review" when you want to have it reviewed again.
> 
> Unfortunately the Admin UI tests are currently unstable, see #30492 - if those tests fail again, it might be worth waiting for that issue to be closed first and then rebase, or asking a maintainer to re-run the tests.

@ahus1 @dalbani I have rebased my PR, making all needed changes. It is ready for review.

2025-10-26 17:30 UTC, ahus1 requested changes
Thank you for the updated PR. See below for two changes I ask for before this PR can be merged.

2025-10-26 17:30 UTC, ahus1 commented on js/apps/admin-ui/src/client-scopes/details/ScopeForm.tsx
> +        />
I see that this is visible also for SAML scope. IMHO this should only be visible for OIDC scopes given its name. If there be an equivalent setting for SAML, it should be renamed to something generic.

2025-10-26 17:30 UTC, ahus1 commented on js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
> +hideFromOpenIdProviderMetadataHelp=If on, this client scope will be hidden from OpenID Provider Metadata.
There is an existing option in the same dialog with the "Include in token scope", and this new option is inverting it by stating "Hide from..."

Please rework this new option to also be name "Include in ...". When doing this, this needs to be inverted to be true by default both in the back end and in the front end.

2025-10-29 10:53 UTC, cgeorgilakis commented on js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
> +hideFromOpenIdProviderMetadataHelp=If on, this client scope will be hidden from OpenID Provider Metadata.
The main problem with this logic is the migration process from older version.
As I understand, this will need a migration method for making all scopes _include.in.openid.provider.metadata_ to _true_ . 
Do we want it? That's why I named it _hide.from.openid.provider.metadata_.

2025-11-01 10:01 UTC, ahus1 commented on js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
> +hideFromOpenIdProviderMetadataHelp=If on, this client scope will be hidden from OpenID Provider Metadata.
@cgeorgilakis - thank you for reaching out. I agree a migration method would not be ideal. Instead of a migration, I would suggest to have a default of "true" both in the backend and the frontend. WDYT?

2025-11-03 09:45 UTC, cgeorgilakis commented on js/apps/admin-ui/src/client-scopes/details/ScopeForm.tsx
> +        />
I check if it is not _SAML_. As I have understood, there is also _OID4VC_PROTOCOL_ scopes now.

2025-11-03 13:02 UTC, cgeorgilakis commented
@ahus1 I have made the requested changes.
The failed test is not PR fault, it is due to `Could not resolve dependencies for project org.keycloak:keycloak-quarkus-integration-tests:jar:999.0.0-SNAPSHOT`.

2025-11-03 14:32 UTC, ahus1 commented
@cgeorgilakis - thank you, looks great. Some small changes here: https://github.com/eosc-kc/keycloak/pull/1028

As I wasn't allowed push the changes directly (no permission), so I created a PR on top of this PR. 

Please merge my PR, and then this PR is ready to be merged.

Best,
Alexander

2025-11-03 15:26 UTC, ahus1 approved these changes

2025-11-03 16:26 UTC, merged