Fix operator CI
keycloak/keycloak pull request #10481
Opened 2022-02-25 14:49 UTC by andreaTP

The operator CI is currently broken due to two events happened at the same time:
 - merging a breaking change
 - changed the CI in a "concurrent" PR
 
 this fix it.

2022-02-25 14:50 UTC, andreaTP commented
The CI is green already here:
https://github.com/andreaTP/keycloak/runs/5334866653

2022-02-25 16:41 UTC, vmuzikar requested changes
@andreaTP Can you please create and link an issue for this?

Funny that the issue was really caused by a multi-line parameter. :D

2022-02-25 17:17 UTC, DGuhr commented
@andreaTP seems that was really the issue... weird. would be nice if someone here can elaborate why. I first thought i was blind or andrea forgot to push the fix accidentally 😄

2022-02-25 17:45 UTC, andreaTP commented
@vmuzikar opened the issue and linked it.

@DGuhr detailed explanation:

 - in [this PR](https://github.com/keycloak/keycloak/pull/10306/files#diff-e3946c0d4cebe6233f6aa4079b21ddcd0e24e61fa7b46fb8e6a813c40a482a32R68) I "broke" the operator CI without noticing, since the tests where passing using both the locally built image and the default `latest`
 - in [this PR](https://github.com/keycloak/keycloak/pull/10396) I introduced a breaking change that was affecting the operator CI tests
 
__Result:__
 after merging both the PR (without rebasing one on top of the other) the CI started to fail for good reasons.
 
__Considerations:__
this kind of issues can be avoided by setting the default Docker image tag to something that doesn't exists by default in the tests, but this means that we would need to always override this parameter when running the CI locally that is a little inconvenient.
I don't expect those kind of issue to happen really often, but we can discuss about the tradeoff.

2022-02-28 08:44 UTC, DGuhr approved these changes
LGTM

2022-02-28 09:02 UTC, vmuzikar approved these changes
Just to summarize – a TL;DR explanation. Per my understanding, the issue here was that we did not correctly override the default KC image coordinates in the operator when  running remote tests.

There's no simple solution to this to avoid such test bugs in the future – we really can't use non-existing image by default as it'd affect the whole operator, not just tests.

Fix LGTM, thanks @andreaTP. We can merge.

2022-02-28 12:06 UTC, stianst approved these changes

2022-02-28 12:06 UTC, merged