Convert authentication session entities into interface
keycloak/keycloak pull request #10507
Opened 2022-03-01 07:39 UTC by martin-kanis

Closes #9738.

2022-03-03 16:06 UTC, mhajas requested changes
Thank for the PR @martin-kanis, I added two comments into code

2022-03-04 07:56 UTC, mhajas approved these changes
Thanks @martin-kanis

2022-03-04 07:56 UTC, martin-kanis commented on model/map/src/main/java/org/keycloak/models/map/authSession/MapAuthenticationSessionEntity.java
> +        public void addExecutionStatus(String authenticator, AuthenticationSessionModel.ExecutionStatus status) {
Thank you for the suggestion. I included it.

2022-03-04 07:56 UTC, mhajas commented on model/map/src/main/java/org/keycloak/models/map/authSession/MapAuthenticationSessionEntity.java
> +        public void addExecutionStatus(String authenticator, AuthenticationSessionModel.ExecutionStatus status) {
Done

2022-03-04 07:57 UTC, mhajas commented on model/map/src/main/java/org/keycloak/models/map/authSession/MapRootAuthenticationSessionEntity.java
> +        public MapAuthenticationSessionEntity removeAuthenticationSession(String tabId) {
Done

2022-03-04 07:57 UTC, martin-kanis commented on model/map/src/main/java/org/keycloak/models/map/authSession/MapRootAuthenticationSessionEntity.java
> +        public MapAuthenticationSessionEntity removeAuthenticationSession(String tabId) {
Changed.

2022-03-04 09:49 UTC, hmlnarik approved these changes
Approving per @mhajas 's approval

2022-03-04 09:50 UTC, merged