Append the legacy CRD using a Json patch
keycloak/keycloak pull request #10525
Opened 2022-03-01 17:55 UTC by andreaTP

Resolves: #9826 

Notes:
 - the CRD is copy pasted from [current `main`](https://github.com/keycloak/keycloak-operator/blob/main/deploy/crds/keycloak.org_keycloaks_crd.yaml)
 - extracted only the `/spec/versions/v1alpha1`
 - `served: false`
 - `storage: false`
 
We can automate the process of "downloading the old CRD and injecting it", but we need first some more clarity about how we want to release "kubernetes resources".

2022-03-03 12:12 UTC, vmuzikar requested changes
Thanks @andreaTP.

What is the expected result from this change? I tried the following:
1. `kubectl apply -f keycloak.org_keycloaks_crd.yaml` in the [old operator repo](https://github.com/keycloak/keycloak-operator/blob/main/deploy/crds/keycloak.org_keycloaks_crd.yaml).
2. `kubectl delete -f keycloak.org_keycloaks_crd.yaml`. This has no effect on the result.
3. `kubectl apply -k target` in the [new operator module](https://github.com/keycloak/keycloak/tree/main/operator).
4. `kubectl get keycloaks` resulting in this error:
```
Error from server (NotFound): Unable to list "keycloak.org/v1alpha1, Resource=keycloaks": the server could not find the requested resource (get keycloaks.keycloak.org)
```

2022-03-03 12:43 UTC, andreaTP commented on operator/src/main/kubernetes/kustomization.yml
> +patchesJson6902:
Used `patches` but documentation is terribly scattered and added a comment to be able to use the old keywords.

2022-03-03 12:47 UTC, andreaTP commented
@vmuzikar to test this change you miss to run a `mvn clean package` command, e.g:

1. kubectl apply -f keycloak.org_keycloaks_crd.yaml in the [old operator repo](https://github.com/keycloak/keycloak-operator/blob/main/deploy/crds/keycloak.org_keycloaks_crd.yaml).
2. mvn clean package in the [new operator module](https://github.com/keycloak/keycloak/tree/main/operator).
3. kubectl apply -k target in the [new operator module](https://github.com/keycloak/keycloak/tree/main/operator).

and the fact that it works shows that we fixed the issue 🙂 

Ready for a new round!

2022-03-14 10:32 UTC, andreaTP commented
@vmuzikar any feedback on this one?

2022-03-14 18:30 UTC, vmuzikar approved these changes

2022-03-14 21:09 UTC, abstractj approved these changes

2022-03-14 21:09 UTC, merged