Add section on how to add the initial admin user
keycloak/keycloak pull request #10532
Opened 2022-03-02 11:53 UTC by ahus1

Closes #10531

2022-03-02 11:59 UTC, DGuhr commented on docs/guides/src/main/server/configuration.adoc
> +To add the initial admin user via scripting, set the environment variables `KEYCLOAK_ADMIN` and `KEYCLOAK_ADMIN_PASSWORD` for username and password of the user.
```suggestion
To add the initial admin user, set the following environment variables: `KEYCLOAK_ADMIN` for the initial admin username and `KEYCLOAK_ADMIN_PASSWORD` for the initial admin password..
```

2022-03-02 12:02 UTC, ahus1 commented
@DGuhr - thank you for the suggestions, I accepted and squashed them into my commit.

2022-03-02 13:08 UTC, jonkoops approved these changes, later dismissed

2022-03-04 13:42 UTC, DGuhr requested changes

2022-03-04 13:42 UTC, DGuhr commented on docs/guides/src/main/server/configuration.adoc
> +To add the initial admin user using environment variables, set `KEYCLOAK_ADMIN` for the initial admin username and `KEYCLOAK_ADMIN_PASSWORD` for the initial admin password..
```suggestion
To add the initial admin user using environment variables, set `KEYCLOAK_ADMIN` for the initial admin username and `KEYCLOAK_ADMIN_PASSWORD` for the initial admin password.
```

2022-03-04 13:42 UTC, DGuhr commented on docs/guides/src/main/server/configuration.adoc
> +Once the first user with administrative rights exists, use the command line tool `kcadm.[sh|bat]` to create additional users.
```suggestion
Once the first user with administrative rights exists, you can use the UI or the command line tool `kcadm.[sh|bat]` to create additional users.
```

2022-03-04 13:44 UTC, DGuhr approved these changes, later dismissed

2022-03-04 14:00 UTC, DGuhr approved these changes

2022-03-04 14:03 UTC, abstractj approved these changes

2022-03-04 14:04 UTC, abstractj commented
@ahus1 I will wait for the checks to complete, so we can get it merged.

2022-03-04 16:25 UTC, merged