SSL config in the operator
keycloak/keycloak pull request #10605
Opened 2022-03-04 18:07 UTC by andreaTP

Resolves #9780

2022-03-04 18:08 UTC, andreaTP commented on operator/src/main/resources/base-keycloak-deployment.yaml
> -          httpGet:
`httpGet` doesn't support the "insecure" option

2022-03-04 18:31 UTC, andreaTP commented on operator/src/test/java/org/keycloak/operator/ClusteringE2EIT.java
> +                        .portForward(8443, 8443)) {
unfortunately we cannot get rid of the port-forwarding thing, it still doesn't work even with strict hostname.

2022-03-04 21:13 UTC, pedroigor approved these changes, later dismissed

2022-03-07 17:16 UTC, vmuzikar requested changes

2022-03-07 17:20 UTC, andreaTP commented on operator/src/test/java/org/keycloak/operator/ClusterOperatorTest.java
> +    Awaitility.setDefaultTimeout(Duration.ofSeconds(360));
yes, at least seems like.

2022-03-07 17:21 UTC, andreaTP commented on operator/src/test/java/org/keycloak/operator/utils/K8sUtils.java
> +                    }
not a leftover, I intentionally left it here for easier debugging.

> the stacktrace is printed if awaitility fails

no, it doesn't maybe we are missing a configuration or something?

2022-03-07 17:22 UTC, vmuzikar commented on operator/src/test/java/org/keycloak/operator/ClusterOperatorTest.java
> +    Awaitility.setDefaultTimeout(Duration.ofSeconds(360));
Do you know why? Kinda seems like a red flag.

2022-03-07 17:24 UTC, andreaTP commented on operator/src/test/java/org/keycloak/operator/utils/K8sUtils.java
> +                    }
anyhow, the underlying problem is the stability, I remove it for now.

2022-03-07 17:52 UTC, andreaTP commented
@vmuzikar ready for next round I believe.

2022-03-07 17:53 UTC, andreaTP commented on operator/src/test/java/org/keycloak/operator/KeycloakDeploymentE2EIT.java
> +    public void testTlsDisabled() {
here you go:
https://github.com/keycloak/keycloak/pull/10605/files#diff-6c9bb3849a00b8bf0ad94a582971f6335e9cefadd546187ac395cace155b2ecaR167

2022-03-08 10:02 UTC, vmuzikar approved these changes
LGTM, thanks @andreaTP.

JFTR. The only missing thing is watching the TLS Secret for changes to restart the Deployment. I'll sneak it in as part of #9726.

We can merge.

2022-03-08 10:04 UTC, vmuzikar requested changes
Oh, one last thing. Please correctly refer to #9782 so it's closed with this PR. Multiple issues can be linked to a single PR.

2022-03-08 10:12 UTC, andreaTP commented
@vmuzikar done

2022-03-08 10:14 UTC, andreaTP commented
force pushed only to re-trigger the CI, @vmuzikar do you mind to re-approve?

2022-03-08 11:40 UTC, vmuzikar commented
Operator tests failed. Not sure if related to this change.

2022-03-08 15:06 UTC, pedroigor approved these changes

2022-03-08 15:13 UTC, vmuzikar approved these changes
LGTM, assuming the tests pass.

2022-03-08 17:52 UTC, vmuzikar commented
All green! Can you please merge @abstractj?

2022-03-08 18:21 UTC, merged