#10443 start-dev: parsing command lines parameters
keycloak/keycloak pull request #10665
Opened 2022-03-09 13:53 UTC by JPA2015

kc.bat called "shift" twice after parsing "start-dev". But "start-dev" is only one parameter so that "shift" should be called only once or else further command line parameters won't be parsed correctly.

2022-03-10 09:12 UTC, DGuhr requested changes
hey @JPA2015 Tried it locally, and with one shift it works :) thanks for the contribution. Could you please add a `Closes #10443` in a new line in the commit message? (see e.g. https://github.com/keycloak/keycloak/blob/main/CONTRIBUTING.md#commit-messages-and-issue-linking ) This links the PR to the issue and helps us later on to keep track. would be great!

2022-03-10 09:20 UTC, JPA2015 commented
> Could you please add a `Closes #10443` in a new line in the commit message?
done

2022-03-10 09:23 UTC, JPA2015 commented
Or may be not. Apparently I can just change it in the conversation. I don't see any possibility in github to change the commit message.

2022-03-10 09:26 UTC, DGuhr commented
@JPA2015 using the command line git tools, e.g. go to your branch -> `git commit --amend` -> editor (vi or similar) should open with the current commit message -> add "Closes ..." there -> save & close editor -> `git push -f`

2022-03-11 15:41 UTC, JPA2015 commented
Thanks for the explanation. It may takes some time until I get to do it, as I didn't get the source code on my computer just to change one line in a batch file (I've done it completely online in github). Sorry I won't be able to do it this week.
Actually I'm wondering if it might be easier for me to cancel this pull request and start a new one with the correct commit message, but I'll see next week.

2022-03-17 15:44 UTC, closed without merging