Hot Rod map storage: Authentication session no-downtime store
keycloak/keycloak pull request #10709
Opened 2022-03-11 11:34 UTC by martin-kanis

Closes #9674

2022-03-16 09:28 UTC, mhajas requested changes
Thank you for the changes @martin-kanis. I added a few comments.

2022-03-16 09:28 UTC, mhajas commented on model/map-hot-rod/src/main/java/org/keycloak/models/map/storage/hotRod/authSession/HotRodAuthenticationSessionEntity.java
> +            return executionStatuses.stream().collect(Collectors.toMap(k -> k.getKey(),
```suggestion
            return executionStatuses.stream().collect(Collectors.toMap(HotRodPair::getKey,
```

2022-03-16 09:28 UTC, mhajas commented on model/map-hot-rod/src/main/java/org/keycloak/models/map/storage/hotRod/authSession/HotRodRootAuthenticationSessionEntity.java
> +        abstract public <V> V deepClone(V obj);
This seems to be unused

2022-03-16 09:28 UTC, mhajas commented on model/map-hot-rod/src/main/java/org/keycloak/models/map/storage/hotRod/clientscope/HotRodClientScopeEntity.java
> -import java.util.LinkedHashSet;
This change seems to be unnecessary.

2022-03-16 09:28 UTC, mhajas commented on model/map-hot-rod/src/main/java/org/keycloak/models/map/storage/hotRod/common/HotRodTypesUtils.java
> +    public static HotRodAuthenticationSessionEntity createHotRodAuthenticationSessionEntityFromMapEntry(Map.Entry<String, MapAuthenticationSessionEntity> entry) {
This is unused after the change in MapAuthenticationSessionInterface (`Map` -> `Set`).

2022-03-16 14:24 UTC, mhajas submitted a review, later dismissed
Thanks @martin-kanis

2022-03-16 16:03 UTC, hmlnarik commented
@martin-kanis Is `ConcurrentLoginTest.concurrentLoginSingleUserSingleClient` from
[Base testsuite (undertow-map-hot-rod, group2)](https://github.com/keycloak/keycloak/runs/5571803540?check_suite_focus=true#logs) supposed to fail?

2022-03-21 20:27 UTC, hmlnarik approved these changes
Approving per @mhajas 's approval

2022-03-22 07:19 UTC, martin-kanis commented
Model tests failure not related to this PR:
```
2022-03-21T19:47:40.9454832Z ##[error]| jpa-federation+infinispan | Tests run: 8, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 66.379 s <<< FAILURE! - in org.keycloak.testsuite.model.session.OfflineSessionPersistenceTest
2022-03-21T19:47:40.9466131Z ##[error]| jpa-federation+infinispan | org.keycloak.testsuite.model.session.OfflineSessionPersistenceTest.testPersistenceMultipleNodesClientSessionsAtRandomNode  Time elapsed: 10.953 s  <<< FAILURE!
2022-03-21T19:47:40.9468491Z ##[error]| jpa-federation+infinispan | java.lang.AssertionError: Execution didn't complete: java.lang.RuntimeException: org.infinispan.commons.CacheException: java.lang.IllegalStateException: Read commands must ignore leavers
```

2022-03-22 08:05 UTC, merged