Add HotRod no downtime store for Realms
keycloak/keycloak pull request #10825
Opened 2022-03-18 16:08 UTC by mhajas

Closes #9670

2022-03-28 09:05 UTC, martin-kanis requested changes
Thanks @mhajas! The PR looks good. Could you just reindex `realms` cache in testsuite/integration-arquillian/tests/base/src/test/resources/META-INF/keycloak-server.json?

2022-03-30 15:03 UTC, mhajas commented on model/map-hot-rod/src/main/java/org/keycloak/models/map/storage/hotRod/realm/HotRodRealmEntity.java
> +    @ProtoDoc("@Field(index = Index.YES, store = Store.YES)")
Looking at the `SearchableFields` for the `RealmModel`, I would say we should leave the index as is. Currently, we don't use `ID` in any MCB, however, we cannot ensure it won't happen in the future version. WDYT?

2022-03-30 15:09 UTC, mhajas commented
Thanks for the review @martin-kanis, added&rebased

2022-04-06 09:18 UTC, mhajas commented on model/map-hot-rod/src/main/java/org/keycloak/models/map/storage/hotRod/realm/HotRodRealmEntity.java
> +    @ProtoDoc("@Field(index = Index.YES, store = Store.YES)")
Let's have it without the index now. At least we can try the index migration if we decide to add MCB with ID later.

2022-04-07 06:45 UTC, martin-kanis commented
@mhajas Can you please check failing `RoleModelTest` with `map-ldap` profile?

2022-04-07 13:41 UTC, mhajas commented
@martin-kanis the failures in the model tests are caused by this issue: https://github.com/keycloak/keycloak/issues/11171

2022-04-07 14:52 UTC, martin-kanis approved these changes
Thanks @mhajas. The failure in CrossDC tests doesn't seem related. Here is similar failure from `main` https://github.com/keycloak/keycloak/runs/5823731955?check_suite_focus=true

2022-04-08 07:35 UTC, hmlnarik approved these changes
Approving per @martin-kanis 's approval

2022-04-08 07:36 UTC, merged