Enhance Map authz entities with REALM_ID (ResourceServer with CLIENT_…
keycloak/keycloak pull request #10889
Opened 2022-03-23 11:18 UTC by vramik

…ID) searchable field

Closes #10883

2022-03-28 13:47 UTC, vramik commented
https://github.com/keycloak/keycloak/discussions/10965

2022-05-02 08:38 UTC, mhajas reviewed
Thanks for the PR @vramik! I added two comments

2022-05-02 12:45 UTC, vramik commented on model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/authorization/PermissionTicketAdapter.java
> +            ResourceServer resourceServer = cacheSession.getResourceServerStoreDelegate().findById(null, cached.getResourceServerId());
Thanks, discussed offline and agreed it will be part of the follow-up PR.

2022-05-02 13:17 UTC, mhajas approved these changes
Thanks @vramik

2022-05-02 13:25 UTC, hmlnarik submitted a review, later dismissed
Approving per @mhajas' approval

2022-05-02 13:43 UTC, mhajas requested changes
I am just looking at the model test results and it seems the failures are relevant, could you have a look @vramik

2022-05-03 09:37 UTC, mhajas approved these changes
Thanks for the fix. That was my fault

2022-05-03 10:19 UTC, vramik commented
@mhajas np at all! Thank you.

2022-05-03 10:55 UTC, hmlnarik approved these changes
Reapproving

2022-05-03 10:56 UTC, merged

2022-05-05 07:03 UTC, vramik commented on model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/authorization/PermissionTicketAdapter.java
> +            ResourceServer resourceServer = cacheSession.getResourceServerStoreDelegate().findById(null, cached.getResourceServerId());
https://github.com/keycloak/keycloak/pull/11831