SLO and ACS Binding are linked with AuthnRequest Binding in SAML Identity Broker Metadata
keycloak/keycloak pull request #11080
Opened 2022-04-02 05:38 UTC by i7a7467

#11079

2023-03-08 11:30 UTC, mposolda commented
@rmartinc Could you please review this one?
@i7a7467 Are you please able to rebase your PR to latest Keycloak main to fix the conflicts?

2023-03-09 10:26 UTC, rmartinc requested changes
Thanks for the PR @i7a7467!

It's almost OK, but I think we should maintain `isPostBindingAuthnRequest` in favor of `isPostBindingResponse`.

2023-03-09 10:26 UTC, rmartinc commented on services/src/main/java/org/keycloak/broker/saml/SAMLIdentityProvider.java
> +            if (getConfig().isPostBindingResponse()) {
I think we should maintain using `isPostBindingAuthnRequest` here. In theory both values should be the same but the one that really is forcing to use the post binding is the `isPostBindingAuthnRequest` (see [here](https://github.com/keycloak/keycloak/blob/21.0.1/services/src/main/java/org/keycloak/broker/saml/SAMLIdentityProvider.java#L170) and then [here](https://github.com/keycloak/keycloak/blob/21.0.1/services/src/main/java/org/keycloak/broker/saml/SAMLIdentityProvider.java#L196-L200)). The ` isPostBindingResponse` is only used to set the attribute in the request ([here](https://github.com/keycloak/keycloak/blob/21.0.1/services/src/main/java/org/keycloak/broker/saml/SAMLIdentityProvider.java#L135-L137)).

Modify the tests accordingly please.

2023-03-26 22:42 UTC, i7a7467 commented
@rmartinc 
Sorry for the delay in replying to you. I am checking the link you gave me codes.
`(see here and then here).` Could you please give me a few days?

2023-03-27 06:28 UTC, rmartinc commented
@i7a7467 Yes, no problem at all, just wanted to know if you were working on it. Thanks!

2023-04-09 09:22 UTC, i7a7467 commented
@rmartinc 
Thanks reply.
Sorry for the late reply.
I read comments and code you provided.

The setting of `HTTP-POST binding for AuthnRequest` does not affect SAML Service Provider metadata.
There I don't know the background behind your idea of changing this code.
Could you give me some more details?

My opinion is as follows.

### HTTP-POST binding response
- Off
  - The value of `AssertionConsumerService Binding` in metadata
    - `urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect`
  - The value of `ProtocolBinding` in authentication request assertion to IdP
    - `urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect`
- On
  - The value of `AssertionConsumerService Binding` in metadata
    - `urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST`
  - The value of `ProtocolBinding` in authentication request assertion to IdP
    - `urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST`

<img width="1336" alt="metadata" src="https://user-images.githubusercontent.com/61368544/230764938-fc192c93-c23e-44e9-8adb-ea088d7d853a.png">

<img width="725" alt="authentication request assertion " src="https://user-images.githubusercontent.com/61368544/230764934-43a294b9-24ae-40c4-a624-32968e226128.png">

### HTTP-POST binding for AuthnRequest
- Off
  - Use GET HTTP method in authentication request to IdP
- On
  - Use POST HTTP method in authentication request to IdP

![image](https://user-images.githubusercontent.com/61368544/230764986-09be912c-ebe6-4e83-a38f-80c33a420c45.png)

2023-04-10 07:53 UTC, rmartinc commented
@i7a7467 There are three different options you are managing here:

* HTTP-POST binding response (isPostBindingResponse): This one is just used to indicate the binding type in the XML payload.
* HTTP-POST binding for AuthnRequest (isPostBindingAuthnRequest): This one is used to really send a POST or GET/REDIRECT request for the authn. If true a POST is used, if false REDIRECT is used. Check the links I presented before.
* HTTP-POST binding logout (isPostBindingLogout): This one is clear, true use POST for logout, false use REDIRECT.

As you see no option is directly involved with the descriptor. They are used to choose what BINDING to use when doing the different requests. The option that is really used to send the POST binding for the authn request  is the second one (isPostBindingAuthnRequest). The first one (isPostBindingResponse) is only used to add the XML binding in the XML payload. If you configure one with true and the other with false, you can be sending a POST (using POST binding) but assigning to the XML payload that it is a REDIRECT binding (so a nonsense). IMHO both options ("HTTP-POST binding response" and "HTTP-POST binding for AuthnRequest") should be always the same and one can even be removed. I would always use same value in the tests for those two options.

But, as you say, the three options are not directly involved with the descriptor. My request is to maintain `isPostBindingAuthnRequest` as it was done before just for backwards compatibility. I'm OK with changing the logout as you are doing but I prefer to maintain `isPostBindingAuthnRequest` as before.

2023-05-05 06:04 UTC, i7a7467 commented
@rmartinc 
Thanks for the details.
I understand about maintaining backward compatibility. 
And I also understood about wanting to keep the behavior the same as it is today.
I will modify codes for backward compatibility.

> IMHO both options ("HTTP-POST binding response" and "HTTP-POST binding for AuthnRequest") should be always the same and one can even be removed. I would always use same value in the tests for those two options.

However, I do not understand the opinion that `isPostBindingResponse` and `isPostBindingAuthnRequest` should also have the same settings.
HTTP-Redirect or HTTP-POST is often used for authenrequest , while HTTP-POST is generally used for authenresponse.(e.g., Google Workspace and box).
I think it is necessary to allow separate Binding for authenrequest  and autheresponse.

2023-05-22 07:31 UTC, rmartinc approved these changes
Thanks for the change @i7a7467 ! LGTM.

2023-05-22 08:04 UTC, mposolda commented
@i7a7467 @rmartinc Thanks for the work and review!

2023-05-22 08:04 UTC, mposolda approved these changes

2023-05-22 08:05 UTC, merged