JPA spi example added
keycloak/keycloak pull request #11110
Opened 2022-04-05 08:50 UTC by psytester

Added: how to configure JPA migration

2022-04-22 12:38 UTC, stianst requested changes
We should rather document this in the configuring the database guide. I thought it was already covered somewhere, but probably mistaken

2022-04-25 16:48 UTC, psytester commented
@stianst what do you expect here? Should I rebuild the PR and add the extension into database guide or do you wait for a review of @DGuhr / @pedroigor?

2022-04-26 11:02 UTC, stianst commented
@psytester if you update the PR to add a section to https://github.com/keycloak/keycloak/blob/main/docs/guides/src/main/server/db.adoc instead of the provider config guide that'd be great.

2022-04-26 17:59 UTC, pedroigor commented
@psytester Thanks. Can you please update the database guide as suggested by Stian?

I'm also wondering if it makes sense to provide some configuration options instead of using the SPI configuration? Not sure because of the upcoming changes to storage though.

2022-04-27 07:28 UTC, DGuhr requested changes
- I also think the right place would be a `setting the migration strategy for JPA` section in the db guide instead. 
- I also think it makes sense to have the config exposed in a more convenient way, e.g. `db-migration-strategy`, but i would suggest to handle this as a follow up. Created #11678 to discuss this further

2022-04-27 12:54 UTC, psytester commented
Change is done.

Which magic does add the chapter "Relevant options" to the page to show config parameter and they possible values in a table? https://www.keycloak.org/server/db

2022-04-27 12:56 UTC, pedroigor approved these changes

2022-06-14 21:08 UTC, pedroigor approved these changes, later dismissed

2022-06-15 06:10 UTC, DGuhr commented
@psytester Sorry for reaching back late. The magic is in the first lines: 

```
... includedOptions="db db-* transaction-xa-enabled"
```

but this magic does not work for SPI-settings so-far, as they are not wrapped in the new configuration layer (it only works for configuration we have a [mapper](https://github.com/keycloak/keycloak/tree/main/quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers) for, and as the SPIs are loaded differently (not "wrapped" by this layer), they can't be rendered in the section atm. That said, there's https://github.com/keycloak/keycloak/issues/11678 to change this, but I have not gotten an answer there so-far from the store team and at the moment we are restructuring the config into its own package in https://github.com/keycloak/keycloak/pull/12435 so I hesitate to change sth before this is done. 

@pedroigor this opens up a kind-of interesting question, that is, can and should we include the spi options into the docs "relevant options" table another way?

Apart from that i'll also approve here for now, as it should help ppl nevertheless :) thanks.

2022-06-15 06:11 UTC, DGuhr approved these changes, later dismissed

2022-08-26 08:37 UTC, stianst commented on docs/guides/src/main/server/configuration-provider.adoc
> +
Please remove as this is an irrelevant change

```suggestion
```

2022-08-26 08:38 UTC, stianst approved these changes

2022-08-26 08:38 UTC, merged

2022-08-26 11:14 UTC, pedroigor commented
@stianst The example is now wrong after the new store integration. The options should use `legacy` instead of `quarkus` as the provider ir.

2022-08-26 12:06 UTC, psytester commented
> use `legacy` instead of `quarkus` as the provider.

Was my first thought too

2022-08-26 12:16 UTC, pedroigor commented
@psytester https://github.com/keycloak/keycloak/pull/14038