Fixing NPE when querying resources by type
keycloak/keycloak pull request #11142
Opened 2022-04-06 10:38 UTC by pedroigor

Closes #11137

2022-04-06 10:50 UTC, jonkoops approved these changes, later dismissed

2022-04-06 14:41 UTC, mhajas approved these changes

2022-04-06 14:43 UTC, mhajas requested changes
thank you for the fix. It seems the test is failing on wildlfy, could you have a look?

2022-04-07 12:40 UTC, stianst approved these changes

2022-04-07 13:43 UTC, mhajas approved these changes
thanks for the fix @pedroigor!

2022-04-07 18:10 UTC, merged

2022-04-07 18:10 UTC, pedroigor commented
@mhajas Thank you.