Event has incorrect error=invalid_logout_response for login response …
keycloak/keycloak pull request #11179
Opened 2022-04-07 21:41 UTC by chrisdolphy

…for brokered error MISSING_REQUIRED_DESTINATION

Changed to error=invalid_saml_response for MISSING_REQUIRED_DESTINATION

Closes #11178

2022-04-12 10:28 UTC, mhajas requested changes
Thank you @chrisdolphy. The change looks good, however, we should have also some tests for this. I came up with something like [this](https://gist.github.com/mhajas/fdff673aefef8199d01e96f427a31915). Could you have a look, please? 

It should be added here: https://github.com/keycloak/keycloak/tree/main/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker

2023-04-18 13:23 UTC, mposolda commented
@mhajas Does it makes sense to close this one and send new PR including your test?

2024-01-30 20:38 UTC, thomasdarimont commented
I just stumbled upon this, rebased the current code and added the recommended test.

As I couldn't add commits to this PR I created a new PR with @mhajas and @chrisdolphy as coauthors here: https://github.com/keycloak/keycloak/pull/26615

If the new PR is accepted we can close this.

2024-01-31 08:32 UTC, ahus1 commented
Other PR has been merged, closing this one

2024-01-31 08:32 UTC, closed without merging