Add environment variable expansion to keycloak.conf
keycloak/keycloak pull request #11285
Opened 2022-04-13 15:16 UTC by pedroigor

Closes #11283

2022-04-13 15:26 UTC, pedroigor commented
@DGuhr You should be fine by just running the tests I just added.

2022-04-13 18:08 UTC, DGuhr requested changes
Code LGTM, thanks 👍 

but could you please add sth to the configuration docs about the expression expansion? I think its a pretty neat feature and should be mentioned (like they do e.g. here in quarkus: https://quarkus.io/guides/config-reference#property-expressions )

tried locally, tests run, but what now also works is e.g.:

Nested expansion of env vars:
#log-level=${ROOT_LVL:${FALLBACK_LVL}} -> uses ROOT_LVL if defined and FALLBACK_LVL is not.

ENV VAR-Concatenation (I added IN / FO in these two and server started with log lvl info)
log-level=$IN_VAR$FO_VAR

Partial use of env vars in strings:
log-level=WA${RN_VAR} -> returned log lvl WARN. cold e.g. come in handy for db-url, where the hostname changes per environment, but port etc stays the same.

If you want I can provide a separate PR for the docs later on, just tell me and I approve this one instead. :)

2022-04-13 20:03 UTC, pedroigor commented
@DGuhr Please, let me know if the doc change works for you.

2022-04-13 21:37 UTC, DGuhr commented
@pedroigor for me yes, but not for the build ;)

2022-04-14 11:03 UTC, DGuhr commented on docs/guides/src/main/server/configuration.adoc
> +db-url-host="${r"${MY_DB_HOST}"}"
these quotes are duplicated during merge, no? shouldn't it be `$r{"${MY_DB_HOST}"}`? Looking at the html output it now looks like this:
![Screenshot 2022-04-14 at 12 59 27](https://user-images.githubusercontent.com/89905860/163378584-055c2378-cdd7-411b-89a2-6f50dbfc0f93.png)
which is wrongly double-quoted (or do I miss sth?)

2022-04-14 11:04 UTC, DGuhr commented on docs/guides/src/main/server/configuration.adoc
> +db-url-host="${r"${MY_DB_HOST:mydb}"}"
see comment above

2022-04-14 11:40 UTC, DGuhr approved these changes
LGTM :)

2022-04-19 07:11 UTC, stianst approved these changes

2022-04-19 07:11 UTC, merged

2022-04-19 08:15 UTC, danielFesenmeyer commented
That's very helpful, thanks for implementing this enhancement :thumbsup: