Add duplicate parameters check process in Device Authz Endpoint.
keycloak/keycloak pull request #11295
Opened 2022-04-14 01:11 UTC by m-takai

Similar to the past [PR](https://github.com/keycloak/keycloak/pull/7544), AuthorizationEndpointRequest class already checks duplicated parameters but DeviceEndpoint class has not checked its error. Thus a check process is added in handleDeviceRequest().

Closes #11294

2022-04-14 05:15 UTC, tnorimat requested changes
@m-takai I added some review comments. Could you check them?
And did you run arquillian integration tests on your PC and confirm that no regression error was found?

2022-04-14 05:15 UTC, tnorimat commented on services/src/main/java/org/keycloak/protocol/oidc/grants/device/endpoints/DeviceEndpoint.java
> +        if(request.getInvalidRequestMessage() != null) {
It might be better to insert a blank between `if` and `(request.` like:
`if (request.`

2022-04-14 05:15 UTC, tnorimat commented on services/src/main/java/org/keycloak/protocol/oidc/grants/device/endpoints/DeviceEndpoint.java
> +                request.getInvalidRequestMessage(), Response.Status.BAD_REQUEST);
How about adding `event.error(Errors.INVALID_REQUEST);` the same as:
https://github.com/keycloak/keycloak/blob/820ab52dce148eae0d51ba194ba9248bf83a69c6/services/src/main/java/org/keycloak/protocol/oidc/endpoints/AuthorizationEndpointChecker.java#L201-L203

2022-04-14 05:15 UTC, tnorimat commented on testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/OAuth2DeviceAuthorizationGrantTest.java
> +    private OAuthClient.DeviceAuthorizationResponse doDeviceAuthorizationWithDulicateParams(String clientId, String clientSecret) throws Exception {
It might be typos:
`doDeviceAuthorizationWithDuplicatedParams`

2022-04-15 00:27 UTC, tnorimat approved these changes
LGTM

2022-04-15 00:28 UTC, m-takai commented
Thank you for your valuable comments and LGTM!

2022-04-19 08:51 UTC, mposolda approved these changes
@m-takai  tnorimat Thanks for the fix and review! I've approved as well. I hope to merge this once tests pass.

2022-04-19 12:20 UTC, merged