Properly enable/disable metrics and health endpoints
keycloak/keycloak pull request #11507
Opened 2022-04-19 15:39 UTC by pedroigor

Closes #11506

2022-07-21 10:20 UTC, DGuhr requested changes
All i

2022-07-21 15:16 UTC, pedroigor commented on quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/KeycloakProcessor.java
> +        filters.produce(new FilterBuildItem(recorder.createRequestFilter(isHealthEnabled() || isMetricsEnabled()),FilterBuildItem.AUTHORIZATION - 10));
It is always called before "functional" routes. The order there is for routes behaving as filters, basically non-functional routes dealing with some cross-cutting concerns like authentication, cord, and authz.

2022-07-21 15:16 UTC, pedroigor commented on quarkus/runtime/src/main/resources/application.properties
> +quarkus.http.non-application-root-path=${quarkus.http.root-path}
Do we need to disable it at all?

2022-07-21 15:17 UTC, pedroigor commented on quarkus/tests/integration/src/main/java/org/keycloak/it/utils/RawKeycloakDistribution.java
> +        keycloak = null;
Concurrency, async read can happen after keycloak is set to null.

2022-07-21 15:29 UTC, DGuhr approved these changes, later dismissed
LGTM, thanks :)

2022-07-21 15:50 UTC, abstractj submitted a review, later dismissed

2022-07-21 16:13 UTC, DGuhr commented on quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/KeycloakProcessor.java
> +        filters.produce(new FilterBuildItem(recorder.createRequestFilter(isHealthEnabled() || isMetricsEnabled()),FilterBuildItem.AUTHORIZATION - 10));
thx, so basically same concept :)

2022-07-22 06:04 UTC, DGuhr approved these changes
LGTM

2022-07-22 12:41 UTC, merged