Build operator dependencies first before testing it
keycloak/keycloak pull request #11642
Opened 2022-04-25 07:52 UTC by ahus1

Closes #11641

2022-04-26 08:24 UTC, andreaTP commented
Hi @ahus1 ! And thanks a lot for opening this issue and proposing a fix!

Other than explicitly building the `common` module I would suggest that we change the `mvn clean verify` command to use the `-am` option, something like:
```bash
mvn -P operator -pl operator -am clean verify \
    ....
```

This way we do not need to track dependencies in the future.

2022-04-26 11:15 UTC, ahus1 commented
@andreaTP - I wasn't sure how much time test tests of keycloak-common would take; testing it locally it is 1 sec. Looking at that result, your solution is a lot more robust. I pushed a change, let's see how the builds run with that change. I'll ask you for a review once the build completed.

2022-04-26 13:38 UTC, ahus1 commented
@andreaTP - the builds are all-green (except the quickstarts). Ready for a review!

2022-04-26 14:08 UTC, andreaTP requested changes
LGTM after removing the old implementation of it 🙂 
Thanks a ton!

2022-04-26 14:15 UTC, ahus1 commented on .github/workflows/operator-ci.yml
> +      - name: Build operator dependencies
Sorry, you're right. Pushed the update.

2022-04-26 14:45 UTC, andreaTP approved these changes

2022-05-24 12:40 UTC, andreaTP commented
I'm extremely sad that we haven't merged this simple and effective PR for so long.

Unfortunately, we are now at the point where another PR ( #11929 ) is touching almost the same bits.

@ahus1 would you mind verifying? And we can probably close this one 😞

2022-05-24 13:03 UTC, ahus1 commented
@andreaTP - I see that the other PR is touch quite some bits and pieces, and I would need to build it locally to see if it tackes the same issues.

Once that other PR has been merged, I'm happy to check if this PR is still necessary and will then either rebase or close it.

2022-05-24 15:54 UTC, pedroigor approved these changes

2022-05-25 19:40 UTC, merged