Fix running operator image tests with prebuilt image
keycloak/keycloak pull request #11751
Opened 2022-04-28 14:54 UTC by DGuhr

Tested locally using the example I added to the readme (using operator nightly build).

plus a few minor improvements to testsetup to make sonarlint happier.

Closes #9898

2022-04-28 18:47 UTC, vmuzikar submitted a review, later dismissed
LGTM, thanks @DGuhr!

2022-04-29 13:46 UTC, vmuzikar requested changes

2022-04-29 13:46 UTC, vmuzikar commented on .github/workflows/operator-ci.yml
> +              -Dquarkus.kubernetes.deployment-target=minikube \
Thinking about this more, I'm not sure using `minikube.yaml` is the correct solution for our main environment where we need to run the tests with pre-built operator image – QE pipelines with OpenShift.

I think we should not tie the capability of testing a pre-built image to a YAML specific to given environment. In other words, the previous solution was correct, IMHO.

CC: @andreaTP

2022-04-29 15:33 UTC, andreaTP commented on .github/workflows/operator-ci.yml
> +              -Dquarkus.kubernetes.deployment-target=minikube \
> I think we should not tie the capability of testing a pre-built image to a YAML specific to given environment.

We are doing it(and we need this ability) anyhow, or in code with the previous `map` or using a different file.
I do very much prefer this encoding since it gives us the opportunity to switch the environment without code changes.

All in all, here we are not tieing the test-suite to a specific environment, on the contrary, we are exploiting its configurability, and, since we test on `minikube` that's the correct file to use.

But happy to discuss if needed 🙂

2022-04-29 15:34 UTC, andreaTP approved these changes, later dismissed

2022-05-02 07:15 UTC, DGuhr commented on .github/workflows/operator-ci.yml
> +              -Dquarkus.kubernetes.deployment-target=minikube \
Would it be a way to go for you both to declare a specific testing yaml instead of using minikube.yaml? I understand the point that we want to decouple the tests from YAMLs specific to environments, nevertheless it is always like this, as an operator is kind of a convenience wrapper(+ generator) around YAMLs, so I also see the point of andrea. I think having a test-deployment.yaml or sth around this would provide decoupling and more flexibility w.r.t. test setup, but at the cost of double maintenance. Not sure how to proceed.

2022-05-02 09:01 UTC, andreaTP commented on .github/workflows/operator-ci.yml
> +              -Dquarkus.kubernetes.deployment-target=minikube \
Let @vmuzikar confirm, but I think that this PR contains the agreed path forward:
https://github.com/DGuhr/keycloak/pull/9/files

2022-05-02 10:15 UTC, vmuzikar commented on .github/workflows/operator-ci.yml
> +              -Dquarkus.kubernetes.deployment-target=minikube \
+1 for merging https://github.com/DGuhr/keycloak/pull/9.

2022-05-02 10:17 UTC, vmuzikar requested changes
Proposed approach:
* Merge https://github.com/DGuhr/keycloak/pull/9
* Update remote testing instructions in README.md to include `-Dquarkus.kubernetes.image-pull-policy=IfNotPresent` instead of `-Dquarkus.kubernetes.deployment-target=kubernetes`.

2022-05-04 13:43 UTC, DGuhr commented
@vmuzikar @andreaTP updated the branch to include andreas changes and the changes to README, also rebased on latest main. Pls re-review.

2022-05-04 18:09 UTC, andreaTP submitted a review, later dismissed
LGTM thanks!

2022-05-04 21:45 UTC, DGuhr commented
seems the CI does not say LGTM. will have a look tomorrow. :/

2022-05-19 09:29 UTC, vmuzikar reviewed
@DGuhr I'm sorry for the late reply, I somehow managed to miss the update. :)

LGTM, just found a small typo.

2022-05-19 09:29 UTC, vmuzikar commented on operator/README.md
> +:you want to use by setting `quarkus.container-image.image=<your-image>:<your-tag>`
Just spotted a tiny typo:
```suggestion
you want to use by setting `quarkus.container-image.image=<your-image>:<your-tag>`
```

2022-05-19 09:54 UTC, DGuhr commented
@vmuzikar added the typofix from your suggestion, thx.

2022-05-19 09:58 UTC, vmuzikar approved these changes, later dismissed

2022-05-19 13:00 UTC, DGuhr commented
@ahus1 @hmlnarik are the model tests flaky again? Asking bc of this workflow run ⏫ 

Experienced them being pretty stable in the last days and weeks, so wanted to ping you on this. Should be unrelated to these changes, though.

2022-05-25 19:33 UTC, abstractj commented
@DGuhr @vmuzikar @andreaTP added Hynek and Alexander to review based on @DGuhr comments. If that's not necessary, please let me know. I noticed that the model tests are failing, but I'm not sure if it's related with the current changes.

2022-05-26 07:41 UTC, andreaTP commented
@abstractj this PR doesn't require any additional reviewer IMHO, as it is self-contained to `operator`.
Comments regarding tests are a week old now and unrelated to this PR.

2022-05-26 07:42 UTC, andreaTP submitted a review, later dismissed

2022-05-27 16:40 UTC, ahus1 commented
@DGuhr the changes you did can't make the model test fail, so this was a rare and unfortunate glitch, some test ran into a timeout when writing things into H2 and Infinispan.

On main, this usually runs with out problems (see https://github.com/keycloak/keycloak/pull/12217 for an example), please run again (ideally after a rebase on main).

2022-06-09 08:55 UTC, andreaTP approved these changes
LGTM

2022-06-09 12:03 UTC, abstractj approved these changes

2022-06-09 12:04 UTC, andreaTP approved these changes

2022-06-09 12:55 UTC, merged