Fix the ClassCastException when running the expiry
keycloak/keycloak pull request #11776
Opened 2022-04-29 15:13 UTC by ahus1

Closes #11775

2022-04-29 18:09 UTC, hmlnarik commented on model/map/src/main/java/org/keycloak/models/map/storage/chm/CriteriaOperator.java
>                  return false;
I agree, either the caller needs to fix it or some sort of type conversion needs to happen. Either way, throwing an exception suits better

2022-05-05 13:12 UTC, hmlnarik requested changes
LGTM, only update the imports please

2022-05-05 13:12 UTC, hmlnarik commented on model/map/src/test/java/org/keycloak/models/map/storage/chm/CriteriaOperatorTest.java
> +import static org.junit.Assert.*;
Please avoid star imports

2022-05-06 05:53 UTC, ahus1 commented on model/map/src/test/java/org/keycloak/models/map/storage/chm/CriteriaOperatorTest.java
> +import static org.junit.Assert.*;
Sorry, fixed this.

2022-05-06 06:10 UTC, ahus1 commented
Test failures seem unrelated to this change, ready for a review.

2022-05-11 07:18 UTC, hmlnarik approved these changes

2022-05-11 07:19 UTC, merged