Cascade removal of client sessions on parent user session removal
keycloak/keycloak pull request #12185
Opened 2022-05-25 13:45 UTC by mhajas

2022-05-26 13:43 UTC, mhajas commented
Currently, I am not able to say whether the failure in Model Tests is caused by these changes. However, I tried to run more iterations (6) and all of them passed: https://github.com/mhajas/keycloak/actions/runs/2390100196

2022-05-27 09:38 UTC, martin-kanis requested changes
Thank @mhajas for the PR. I have one comment.

2022-05-27 10:26 UTC, mhajas commented on model/map-hot-rod/src/main/java/org/keycloak/models/map/storage/hotRod/HotRodMapStorageProviderFactory.java
> +            HotRodEntityDescriptor<HotRodUserSessionEntity, HotRodUserSessionEntityDelegate> entityDescriptor = (HotRodEntityDescriptor<HotRodUserSessionEntity, HotRodUserSessionEntityDelegate>) getE
Fixed

2022-05-27 10:47 UTC, vramik approved these changes
I have checked non-HotRod part of the PR and it LGTM, thanks @mhajas

2022-05-27 14:25 UTC, martin-kanis approved these changes

2022-05-30 07:58 UTC, hmlnarik approved these changes
Approving per @vramik and @martin-kanis 's approvals

2022-05-30 07:58 UTC, merged