Use base64 url decoded for client secret when authenticating with Basic Auth
keycloak/keycloak pull request #12486
Opened 2022-06-13 17:39 UTC by lexcao

https://github.com/keycloak/keycloak/issues/11908

2022-07-06 19:40 UTC, frankjkelly commented
Any update on this - can we get some 👁️ on this so we can get this merged eventually? Thanks!

2022-07-14 18:07 UTC, mposolda requested changes
@lexcao Thanks for the PR! Added one minor inline comment.

Will be also good to rebase this PR on top of latest keycloak main (maybe it will help to make sure that GH actions test will properly run with this PR as it seems they were not executed before for some reason).

2022-07-15 15:57 UTC, lexcao commented on core/src/main/java/org/keycloak/util/BasicAuthHelper.java
> +    public static String[] parseHeader(String header) {
It could replace the entire method, I think.
Let me do that.

2022-07-15 16:58 UTC, lexcao commented
Hi, @mposolda 
I have updated the PR.
Could you please help trigger the CI?

2022-07-16 07:38 UTC, mposolda approved these changes
@lexcao Thanks!

2022-07-16 07:38 UTC, merged