Continue client browser flow after User login from Identity Provider
keycloak/keycloak pull request #12891
Opened 2022-07-04 10:36 UTC by cgeorgilakis

Closes #10250

Our implementation saves in AuthNotes of AuthenticationSessionModel all needed information for Client Browser Flow ( AuthenticationProcessor.CURRENT_AUTHENTICATION_EXECUTION of Client Browser Flow, flowid) before redirecting to Identity Provider login. After Identity Provider login has successfully finished, Keycloak can retrieve all needed information for Client Browser Flow from AuthNotes of AuthenticationSessionModel and proceed with Client Browser Flow. 

Browser flows execution are now continuing after Identiy Provider Login. That's why some tests need to be changed. Some changes indicate that Browser flow with Identity Provider login, is working well. I do not know if we need extra tests.
More tests failures are related with SamlClientBuilder and its related code.  I do not know well test implementation of SamlClientBuilder in order to make appropriate changes in it or found possible errors in my code. Finnaly KcOidcBrokerTest/KcSamlBrokerTest test method testPostBrokerLoginFlowWithOTP failure is strange.

2022-07-04 13:26 UTC, cgeorgilakis commented
I have added a check for CLIENT_AUTHENTICATION_EXECUTION and CLIENT_FLOW_ID not being null in method finishBrokerAuthentication of IdentityBrokerService for overcome errors and test failures. A warn is logged if at least one of  CLIENT_AUTHENTICATION_EXECUTION and CLIENT_FLOW_ID is null. However, I do not understand why these variables are null in some cases.

2022-10-04 08:52 UTC, cgeorgilakis commented
After rebasing some test methods( `AbstractAdvancedBrokerTest.testPostBrokerLoginFlowWithOTP_bruteForceEnabled`, `KcOidcFirstBrokerLoginNewAuthTest.testReAuthenticateWithPasswordAndConditionalOTP_otpRequested`, `KcOidcFirstBrokerLoginNewAuthTest.testReAuthenticateWithPasswordOrOTP_otpConfigured_otpUsed`) are failing. The problem is that otp is failed - added by `loginTotpPage.login(totp.generateTOTP(totpSecret));`. This happens when otp check is passed during IdP flow and Client flow requires otp again after successful IdP login. Why this happen? How can I fix it?

Moreover, SAML tests ( methods `BrokerTest.testInResponseToSetCorrectly`, `BrokerTest.testLogoutPropagatesToSamlIdentityProvider`) are not failing only for quarkus! Why? How can I fix it?

2024-03-13 13:45 UTC, mposolda commented
Thanks a lot for the PR and sorry for it not yet being reviewed. We will try to review this once we have some time...

2024-04-01 23:37 UTC, trixpan commented
@mposolda any luck with this review?

2024-04-22 22:54 UTC, JSmith-Aura commented
Any news on this? Just discovered this bug myself and am very keen to get it fixed....

2024-04-26 12:48 UTC, thereiam commented
Same here. It would be amazing if this bug could be fixed! Thank you for all your great work.

2024-04-30 07:29 UTC, NicolasLiampotis commented
Looking forward to the review whenever the team has a chance.

2024-05-02 17:25 UTC, tulequ commented
Looking for this feature!!!

2024-06-05 11:38 UTC, piaoyunbo commented
Any updates on this?Looking for this feature!!!

2024-06-18 10:37 UTC, mixman68 commented
I need this feature too during my transition phase

2024-07-03 15:50 UTC, jirutka requested changes
Fix code-style

2024-07-03 15:50 UTC, jirutka commented on services/src/main/java/org/keycloak/authentication/AuthenticationProcessor.java
> +            authSession.setAuthNote(AuthenticationProcessor.CLIENT_FLOW_ID,client_flow);
```suggestion
        String clientExecution = authSession.getAuthNote(AuthenticationProcessor.CLIENT_AUTHENTICATION_EXECUTION);
        String clientFlow = authSession.getAuthNote(AuthenticationProcessor.CLIENT_FLOW_ID);
        authSession.clearAuthNotes();
        // Keep CLIENT_AUTHENTICATION_EXECUTION and CLIENT_FLOW_ID if they exist
        if (client_execution != null) {
            authSession.setAuthNote(AuthenticationProcessor.CLIENT_AUTHENTICATION_EXECUTION, clientExecution);
        }
        if (client_flow != null) {
            authSession.setAuthNote(AuthenticationProcessor.CLIENT_FLOW_ID, clientFlow);
        }
```

2024-07-03 15:50 UTC, jirutka commented on services/src/main/java/org/keycloak/authentication/DefaultAuthenticationFlow.java
> +        } else return response;
```suggestion
        } else {
            return response;
        }
```

2024-07-03 15:50 UTC, jirutka commented on services/src/main/java/org/keycloak/authentication/authenticators/browser/IdentityProviderAuthenticator.java
> +       Optional<IdentityProviderModel> idp = context.getRealm().getIdentityProvidersStream()
```suggestion
        Optional<IdentityProviderModel> idp = context.getRealm().getIdentityProvidersStream()
```

2024-07-03 15:50 UTC, jirutka commented on services/src/main/java/org/keycloak/authentication/authenticators/browser/IdentityProviderAuthenticator.java
> +            context.success();
```suggestion
        // If IDENTITY_PROVIDER_USERNAME is not null, then user has logged in via IdP -> return success
        if (context.getAuthenticationSession().getUserSessionNotes().get(Details.IDENTITY_PROVIDER_USERNAME) != null) {
            context.success();
        }
```

2024-07-03 15:50 UTC, jirutka commented on services/src/main/java/org/keycloak/authentication/authenticators/browser/UsernamePasswordForm.java
> +        //BROKER_USER_ID not null user have been login with Idp -> return success
```suggestion
        // If IDENTITY_PROVIDER_USERNAME is not null, user has logged in via IdP -> return success
```

2024-07-03 15:50 UTC, jirutka commented on services/src/main/java/org/keycloak/services/resources/IdentityBrokerService.java
> +        if (execution != null && flowId!=null) {
```suggestion
        if (execution != null && flowId != null) {
```

2024-07-03 15:50 UTC, jirutka commented on services/src/main/java/org/keycloak/services/resources/IdentityBrokerService.java
> +            if (challenge != null) return challenge;
```suggestion
            if (challenge != null) {
                return challenge;
            }
```

2024-07-03 15:50 UTC, jirutka commented on testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/AbstractAdvancedBrokerTest.java
> +             AccountHelper.logout(adminClient.realm(bc.consumerRealmName()), bc.getUserLogin());
```suggestion
            AccountHelper.logout(adminClient.realm(bc.consumerRealmName()), bc.getUserLogin());
```

2024-07-04 12:35 UTC, cgeorgilakis commented
> Fix code-style

@jirutka I have make code-style changes suggested and I have rebased it. Thanks.
@jirutka @mposolda could we proceed with reviewing this important bug fix for supporting client authentication flows with broker users?

2024-07-04 12:54 UTC, jirutka requested changes

2024-07-04 12:54 UTC, jirutka commented on services/src/main/java/org/keycloak/authentication/authenticators/browser/IdentityProviderAuthenticator.java
> +            context.success();
```suggestion
        if (context.getAuthenticationSession().getUserSessionNotes().get(Details.IDENTITY_PROVIDER_USERNAME) != null) {
            context.success();
        }
```

2024-10-22 04:00 UTC, igor-nikiforov commented
@mposolda just a friendly ping here.

2024-12-18 10:20 UTC, mposolda commented
@cgeorgilakis Sorry for the late review. Thanks for the PR. Unfortunately I think it makes sense even more complex and fragile (authentication flows are already quite fragile in general). And the test failures are also problematic...

I believe we can address your use-case (and hopefully most other use-cases as well) by some easier way. I've commented on the issue https://github.com/keycloak/keycloak/issues/10250#issuecomment-2550923386 ).

2026-04-29 06:39 UTC, closed without merging

2026-04-29 06:39 UTC, stianst commented
Closing this as it's been open a long time without consensus.

2026-04-29 09:14 UTC, jirutka commented
Are you kidding us? It’s not a lack of consensus, but a lack of care from the Keycloak devs. The problem is still present and unresolved.