Showing consent screen text instead of scope name in consent part of …
keycloak/keycloak pull request #13160
Opened 2022-07-18 07:56 UTC by cgeorgilakis

…Application page in Account console

Closes #13109

![correctConsent_ApplicationPage](https://user-images.githubusercontent.com/55974447/179467817-2ffeeebf-3574-4a38-8a8f-ab284ec1bb46.PNG)
Correct consent in Application Page of Account Console

2022-07-27 13:39 UTC, mposolda requested changes
@cgeorgilakis Looks like a good change, Thanks for this!

The only thing is failing `AccountRestServiceTest` in the quarkus distribution, which looks like a regression of this PR. It is strange that it is just for the quarkus dist. Could you please doublecheck in your environment and possibly fix the failing test? The steps to run the test with quarkus distribution is likely something like:
```
mvn clean install -DskipTests=true -Pdistribution,quarkus
cd testuite/integration-arquillian
mvn clean install -Dtest=AccountRestServiceTest -Pauth-server-quarkus
```

2022-08-05 12:29 UTC, cgeorgilakis commented
Strange. AccountRestServiceTest is successful locally and in github actions of branch.
I have rebased branch and all tests have passed.

2022-08-23 09:22 UTC, mposolda commented
@cgeorgilakis Thanks!

2022-08-23 09:22 UTC, mposolda approved these changes

2022-08-23 09:22 UTC, merged