Add support for explicit user search by username and email in Admin UI
keycloak/keycloak pull request #13185
Opened 2022-07-18 13:58 UTC by thomasdarimont

This adds support for the `username:$USERNAME` `email:$EMAIL` in the vein of `id:$USERID`.

Add support for user lookup by username
- Add ability for direct user lookups by username and email to UsersResource and BruteForceUsersResource
- Document user search by selected fields
- Extract SEARCH_ID_PARAMETER to SearchQueryUtils

Fixes https://github.com/keycloak/keycloak/issues/26602

Discussion: #13184

Signed-off-by: Thomas Darimont <thomas.darimont@googlemail.com>

2022-07-25 09:14 UTC, Nowheresly commented
really useful feature
+1

2024-02-01 10:21 UTC, thomasdarimont commented
The tests work fine on my side. It seems as if the keycloak-documentation build has some issues at the moment.

2024-02-07 15:08 UTC, pedroigor submitted a review, later dismissed

2024-02-08 20:36 UTC, pedroigor commented
@mposolda @ssilvert Wdyt?

2024-02-08 21:22 UTC, pedroigor commented
I don't see why we can't have e-mail in this PR?

2024-02-08 22:51 UTC, thomasdarimont commented
Okay then I'll add email too for completeness

2024-02-09 12:54 UTC, ssilvert commented
@thomasdarimont We already added user attribute searches to the UI.  I take it that you are saying these searches are too inefficient?

2024-02-14 21:39 UTC, thomasdarimont commented
@ssilvert thanks for having a look. I think you are referring to this regarding attribute search: https://github.com/keycloak/keycloak/blob/main/rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/BruteForceUsersResource.java#L97C24-L97C37
This method will internally call https://github.com/keycloak/keycloak/blob/main/model/jpa/src/main/java/org/keycloak/models/jpa/JpaUserProvider.java#L733. This in turn will generate a generic search predicate: https://github.com/keycloak/keycloak/blob/main/model/jpa/src/main/java/org/keycloak/models/jpa/JpaUserProvider.java#L900
This method generates something like `... username = ? OR email = ? OR lower(firstname) = ? OR lower(lastname) = ? ....`.

This of course does the job but is not very efficient. I think the proposed shortcuts for very common search operations speed up user search via admin-ui and rest API significantly.

2026-04-29 09:52 UTC, thomasdarimont commented
I rebased my branch on current main and reimplemented the support for explicit user and email lookups via `username:...` and `email:...` prefixes. 
I also aligned the lookup used by UsersResource and BruteForceProtected users.

2026-04-29 10:21 UTC, pedroigor requested changes
Thanks, @thomasdarimont.

Can you please update the PR:

* Add `email` to `getCount`
* Add tests to cover `count` within the test methods you are adding

Once we have that, LGTM.

2026-04-29 10:23 UTC, thomasdarimont commented
Just pushed a rebased version

2026-04-29 10:33 UTC, thomasdarimont commented
@pedroigor I think searches for prefixes like id:, email: and username: are covered now. I added some additional checks for count(..) as you requested.

2026-04-29 18:09 UTC, pedroigor approved these changes

2026-04-29 18:12 UTC, merged