Abort CodeQL runs on new pushes for the branch
keycloak/keycloak pull request #13241
Opened 2022-07-21 05:28 UTC by ahus1

Closes #13231

2022-07-21 05:30 UTC, ahus1 commented
Hi @abstractj - this limits the concurrency of the CodeQL actions for pull requests; I noticed they are not cancelled. 

WDYT? Keeping it as a draft while the actions are still running.

2022-07-22 07:09 UTC, vmuzikar requested changes
@ahus1 Thanks for the PR!

>This also prevents that a push to a branch cancels an already running action on the same branch in those cases where the job is not running for a pull request.

Wanted to discuss this a bit. What is the use-case for keeping the workflows running when you push new changes to your branch? Even during development on my fork, I'm interested in test results only for the latest commit, am I not? And it might happen that I deplete all the GHA resources even on my fork in certain scenarios.

2022-07-22 09:06 UTC, ahus1 commented
@vmuzikar - there is always an exception to the rules is seems. See https://github.com/keycloak/keycloak/branches, especially `token-exchange-fix`. 

On the other hand, on cloned repositories there are branches that are supposed to be pushed at, and contributors might want to run those actions on their branches. 

I pushed some changes, and the GHAs look good, please have a look when you have the time. 

It applies some refactoring that it includes the name as a variable; this way the code can be copied across GitHub actions without changing the prefix. See https://docs.github.com/en/actions/using-jobs/using-concurrency#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow for the source.

2022-07-22 10:44 UTC, vmuzikar approved these changes
@ahus1 LGTM, thank you!

2022-07-28 18:29 UTC, abstractj approved these changes

2022-07-28 18:30 UTC, merged