Add missing Slovak translation
keycloak/keycloak pull request #13325
Opened 2022-07-26 09:20 UTC by diaboy96

Closes #13324

2022-07-26 12:42 UTC, martin-kanis requested changes
@diaboy96 Thank you for the PR. For consistency reasons with the rest of the translation, I think, it would be better to use adjective "autentifikovaný" as noun "autentifikácia" is often used in the rest and also noun "administrátora".

2022-07-26 12:42 UTC, martin-kanis commented on themes/src/main/resources-community/theme/base/login/messages/messages_sk.properties
> +federatedIdentityUnavailableMessage=Používateľ {0} overený poskytovateľom identity {1} neexistuje. Kontaktujte svojho správcu.
```suggestion
federatedIdentityUnavailableMessage=Používateľ {0} autentifikovaný poskytovateľom identity {1} neexistuje. Kontaktujte svojho administrátora.
```

2022-07-26 18:32 UTC, martin-kanis submitted a review, later dismissed
Thanks @diaboy96.

2022-07-27 05:04 UTC, hmlnarik requested changes
@diaboy96 Could you please squash the two commits into a single one?

2022-07-27 08:49 UTC, diaboy96 commented
> @diaboy96 Could you please squash the two commits into a single one?

Of course

2022-07-27 08:59 UTC, hmlnarik approved these changes
Thank you!

2022-07-27 12:03 UTC, merged