Print response from http call to keycloak server
keycloak/keycloak pull request #13558
Opened 2022-08-05 02:42 UTC by kyao233

Closes #13557

2022-08-05 04:38 UTC, kyao233 commented
@DGuhr Can you help to check this one? thanks.

2022-08-24 12:41 UTC, stianst requested changes
Including the response in the stack trace is not ideal for a few reasons. It can have a performance impact, but more importantly there's a risk of leaking sensitive information in logs.

I would say we should have a separate log category for response logging, at debug or even tracing level that can be enabled explicitly.

2022-08-24 12:54 UTC, pedroigor commented on authz/client/src/main/java/org/keycloak/authorization/client/util/HttpMethod.java
> +                throw new HttpResponseException("Unexpected response from server: " + statusCode + " / " + statusLine.getReasonPhrase()  + " Response : " + new String(bytes), statusCode, statusLine.g
For debugging purposes, we can use Java Logging and log the response accordingly when level `FINE` is set.

2022-08-26 12:58 UTC, pedroigor commented
@kyao233 Thanks for the contribution. I'm closing it for now but if you have time for applying the suggested changes, feel free to re-open it.

2022-08-26 12:58 UTC, closed without merging