Allow dependencies from keycloak-admin-ui
keycloak/keycloak pull request #13924
Opened 2022-08-22 16:45 UTC by ahus1

This prevents exceptions due to missing classes like kotlin/jvm/internal/Intrinsics.

Closes #13918

2022-08-22 20:47 UTC, jonkoops approved these changes

2022-08-23 06:22 UTC, martin-kanis approved these changes

2022-08-23 07:29 UTC, edewit approved these changes

2022-08-23 08:02 UTC, stianst requested changes
There's not much value add here in adding Kotlin for the custom endpoints introduced by the admin-ui. These should really just be changed to be plain Java.

2022-08-23 08:10 UTC, ahus1 commented
The core of this PR is about whether the keycloak-admin-ui can add dependencies to Keycloak itself. 

Which dependencies the keycloak-admin-ui introduces is then about the keycloak-admin-ui and not part of this PR.

Still, as it is now, the keycloak-admin-ui can't introduce any dependencies, which serves as a trip-wire (but only in the the cases, not sure if quarkus packages those dependencies as default)

2022-08-24 09:31 UTC, stianst approved these changes

2022-08-24 09:31 UTC, merged