Allow updating authz settings via default client registration provider
keycloak/keycloak pull request #14124
Opened 2022-08-31 20:48 UTC by pedroigor

Closes #9008

2022-12-13 08:11 UTC, vmuzikar requested changes
Thanks, @pedroigor! Changes LGTM but I wonder whether we should be consistent and import the AuthZ settings also upon Client creation, not just when updating it.

2022-12-13 10:33 UTC, pedroigor commented
The reason why it is only on the update is to keep it consistent with how you create a client and enable authz. First, you create and enable authz, then you manage settings.

2022-12-13 10:59 UTC, mposolda approved these changes, later dismissed
@pedroigor LGTM, I am approving. Will be good to wait for @vmuzikar if he approves as well, but your explanation for create/update is fine to me.

Sorry for late review.

2022-12-13 11:00 UTC, vmuzikar reviewed
@pedroigor Thanks for the clarification! LGTM then, all we need now is just a rebase. :)

2022-12-14 12:35 UTC, vmuzikar submitted a review, later dismissed

2022-12-15 19:43 UTC, vmuzikar approved these changes

2022-12-15 19:43 UTC, merged