CryptoIntegration initialization using the same classloader
keycloak/keycloak pull request #14467
Opened 2022-09-16 22:07 UTC by rgala

Initialize CryptoIntegration using the same classloader that was used to load CertificateUtils and PemUtils classes

Closes #13803

2022-09-26 07:54 UTC, mposolda approved these changes
@rgola Thanks!

2022-09-26 07:57 UTC, mposolda requested changes
@rgala One note: Is it possible that you sent this PR to the "main" branch instead of the "19.0" branch?

The most important branch for the future development is always the "main" . Adding this to the "19.0" will mean that this issue will happen again in the future.

2022-09-26 08:00 UTC, rgala commented
@mposolda I could but this issue does not exist in main, it exists only in 19.0

2022-09-27 07:20 UTC, mposolda commented
@rgala Ah, ok. So if the issue does not exists in latest Keycloak main, then we can just close this PR and also close #13803 issue. Is it correct? Until the Keycloak 20 is released, you can use the Keycloak built from Keycloak main or the Keycloak nightly build - https://github.com/keycloak/keycloak/releases/tag/nightly

2022-09-27 07:23 UTC, rgala commented
Of course, but if you plan to release another 19.x version then I would recommend to merge this PR into 19 branch.

2022-09-27 09:34 UTC, mposolda approved these changes
@rgala Ok, Thanks. I am not sure if we are going to have 19.0.3. If yes, you can expect this to be present there.

2022-09-27 09:35 UTC, merged