Cleanup MapUserSessionAdapter.getAuthenticatedClientSessions()
keycloak/keycloak pull request #14744
Opened 2022-10-05 15:04 UTC by ahus1

Closes #14743

2022-10-06 07:49 UTC, ahus1 commented
/rerun

2022-10-06 20:28 UTC, ahus1 commented
Those changes are supposed to be small and local. If they lead t a lot of questions, I'd rather revert them.

2022-10-07 07:48 UTC, hmlnarik requested changes
Thank you for the PR! Up to the changes in the `MapUserSessionProvider` looks good to me, please see inline.

2022-10-07 07:48 UTC, hmlnarik commented on model/map/src/main/java/org/keycloak/models/map/userSession/MapUserSessionProvider.java
> +                // only check expiry for transient entities, as the physical map store will not return expired entities on any query
Unfortunately, this assumption is not correct. The expiration check for persistent entities has to remain here, see the following javadoc.
https://github.com/keycloak/keycloak/blob/148c7695ff5b32f46f05a5f341ca5456da144987/model/map/src/main/java/org/keycloak/models/map/common/ExpirableEntity.java#L24-L27

2022-10-07 09:32 UTC, hmlnarik approved these changes
Approving (conditioned on green builds). Thank you for the PR!

2022-10-07 11:38 UTC, sguilhen reviewed
Operator CI seems to be failing not only on this PR. Got the same error in the remote tests in a completely unrelated PR

2022-10-07 12:09 UTC, ahus1 commented
Builds are green, operator failure is not related as I see it - thank for Stefan confirming it.

2022-10-10 11:00 UTC, mhajas approved these changes
Thanks @ahus1, LGTM

2022-10-10 11:01 UTC, merged