Add possibility to limit field length in legacy event store
keycloak/keycloak pull request #14891
Opened 2022-10-14 10:17 UTC by vramik

Closes #14888

2022-10-14 13:11 UTC, stianst commented
I'm not all that convinced about this. 

The main reason a admin event would be too big to store in the database is due to including the realm representation. By limiting the length of the field the important information in the realm representation may or may not be included in the stored event. 

For example if an admin is updating a realm, and is changing one of the last fields in the representation, that will not be visible in the stored event, as that has been removed completely.

In addition it seems this is storing invalid JSON in the event, which can't be parsed by any JSON libraries.

2022-10-14 13:24 UTC, vramik commented
Thanks @stianst

> I'm not at all that convinced about this.
> 
> The main reason a admin event would be too big to store in the database is due to including the realm representation. By limiting the length of the field the important information in the realm representation may or may not be included in the stored event.
> 
> For example if an admin is updating a realm, and is changing one of the last fields in the representation, that will not be visible in the stored event, as that has been removed completely.

So you're not convinced that we should introduce the configuration option to limit the representation at all or that the approach in this PR is correct?

> In addition it seems this is storing invalid JSON in the event, which can't be parsed by any JSON libraries.

true, but this issue is there already, right? This PR doesn't change anything about that. Am I missing something?

2022-10-14 14:14 UTC, stianst commented
PR itself looks okay, it's rather the general solution to the problem I don't think is good.

2022-10-14 14:47 UTC, vramik commented
> PR itself looks okay, it's rather the general solution to the problem I don't think is good.

I agree it's not ideal to throw away part of the data. By default there is not trimming at all. It has to be actively configured by admin to make it work. I can see it as option to get unstuck in case the representation became too long. Would you rather suggest something else instead?

2022-10-17 08:05 UTC, stianst commented
See https://github.com/keycloak/keycloak/issues/14851#issuecomment-1280449942 for more details thoughts around this from me.

2022-10-18 13:44 UTC, hmlnarik requested changes

2022-10-18 13:44 UTC, hmlnarik commented on model/jpa/src/main/java/org/keycloak/events/jpa/JpaEventStoreProvider.java
> +            logger.warnf("Detail '%s' will be truncated." + detail);
```suggestion
            logger.warnf("Detail '%s' will be truncated.", detail);
```

2022-10-18 13:44 UTC, hmlnarik commented on model/jpa/src/main/java/org/keycloak/events/jpa/JpaEventStoreProvider.java
> +            logger.warn("Field '%s' will be truncated." + field);
```suggestion
            logger.warn("Field '%s' will be truncated.", field);
```

2022-10-18 13:44 UTC, hmlnarik commented on model/jpa/src/main/java/org/keycloak/events/jpa/JpaEventStoreProviderFactory.java
> +        maxFieldLength = config.getInt("max-field-length", -1);
These should be checked to be greater than 3 (otherwise they can lead to an exception later)

2022-10-21 13:13 UTC, hmlnarik approved these changes

2022-10-21 13:16 UTC, merged