fix(sec): upgrade org.apache.tomcat:tomcat-catalina to 8.5.76
keycloak/keycloak pull request #14950
Opened 2022-10-18 02:50 UTC by Super-Sky

### What happened？
There are 8 security vulnerabilities found in org.apache.tomcat:tomcat-catalina 8.5.38
- [CVE-2019-17563](https://www.oscs1024.com/hd/CVE-2019-17563)
- [CVE-2019-0232](https://www.oscs1024.com/hd/CVE-2019-0232)
- [CVE-2019-0221](https://www.oscs1024.com/hd/CVE-2019-0221)
- [CVE-2020-9484](https://www.oscs1024.com/hd/CVE-2020-9484)
- [CVE-2021-30640](https://www.oscs1024.com/hd/CVE-2021-30640)
- [CVE-2021-24122](https://www.oscs1024.com/hd/CVE-2021-24122)
- [CVE-2021-25329](https://www.oscs1024.com/hd/CVE-2021-25329)
- [CVE-2022-25762](https://www.oscs1024.com/hd/CVE-2022-25762)

### What did I do？
Upgrade org.apache.tomcat:tomcat-catalina from 8.5.38 to 8.5.76 for vulnerability fix

### What did you expect to happen？
Ideally, no insecure libs should be used.

### The specification of the pull request
[PR Specification](https://www.oscs1024.com/docs/pr-specification/) from OSCS

2022-10-21 20:03 UTC, abstractj commented
@stianst would be possible to include this change into 20.0.0?

2022-10-21 20:03 UTC, abstractj approved these changes, later dismissed

2022-10-24 07:49 UTC, martin-kanis requested changes
I don't see a problem with upgrade of the version. However, there is one override of Tomcat version in the testsuite that can be removed with the PR. https://github.com/keycloak/keycloak/blob/main/testsuite/integration-arquillian/servers/pom.xml#L52

2022-10-24 11:56 UTC, abstractj commented
@Super-Sky could you please incorporate the changes requested by @martin-kanis ?

2022-10-25 05:38 UTC, stianst commented
Follow-up PR with the override in the testsuite removed:
https://github.com/keycloak/keycloak/pull/15133

2022-10-25 05:40 UTC, stianst approved these changes

2022-10-25 05:42 UTC, stianst commented
Removed the override in the testsuite pom

2022-10-25 08:39 UTC, martin-kanis approved these changes
Thanks @stianst for the update.

2022-10-25 12:30 UTC, merged