Rename free-form field from 'serverConfiguration' to 'additionalOptions' in Keycloak CR.
keycloak/keycloak pull request #14978
Opened 2022-10-18 15:25 UTC by andre-nascimento-rh

- The "serverConfiguration" field at "KeycloakSpec.java" class was renamed to "additionalOptions";

- All the references and mentions were refactored;

- Some .adoc files and Test files were changed also.

Known Issues:

- The Operator's Test Suites ran successfully via Maven command line. However, some weird errors happened when running such tests in IDE (IntelliJ Idea).

Closes #14410

2022-10-19 16:15 UTC, vmuzikar requested changes
@andre-nascimento-rh Can you please rebase? There are some unrelated commits.

2022-10-20 10:55 UTC, andre-nascimento-rh commented
> 

Rebase done. Please review again. Thanks.

2022-10-20 11:05 UTC, vmuzikar approved these changes
@andre-nascimento-rh Thank you! Changes LGTM, let's wait for the tests.

2022-10-20 19:25 UTC, vmuzikar requested changes
@andre-nascimento-rh Can I ask for one more rebase? Some conflicts were introduced by https://github.com/keycloak/keycloak/pull/14989.

2022-10-21 10:06 UTC, mabartos reviewed
@andre-nascimento-rh Thanks for the PR! LGTM, once the rebase is completed, I'll approve that.

2022-10-21 10:37 UTC, andre-nascimento-rh commented
> @andre-nascimento-rh Can I ask for one more rebase? Some conflicts were introduced by #14989.

Rebase done. Please, re-review.

2022-10-21 12:40 UTC, vmuzikar approved these changes
@andre-nascimento-rh Thank you, LGTM!

2022-10-21 12:41 UTC, merged