Allow simulated redirects
keycloak/keycloak pull request #15074
Opened 2022-10-20 23:41 UTC by Mstrodl

Requests with `simulate_redirect=true` won't generate a 301. This is very useful for themes that want to submit forms in javascript with XHR.

2022-10-24 11:34 UTC, stianst requested changes
Forms should not be submitted with XHR, and this is not something we will want to support.

2022-10-24 17:58 UTC, Mstrodl commented
> Forms should not be submitted with XHR, and this is not something we will want to support.

Why? My usecase is to allow allow a single-page login flow similar to https://access.redhat.com/login

2022-11-01 14:38 UTC, WillNilges commented
This would be really cool to have. It's a huge pain the way that it works now (on my system, at least), and implementing something like this would really streamline the login.

2022-11-01 14:52 UTC, stianst commented
This stuff makes no sense to me, but if someone can explain how this is useful perhaps we can figure something out.

2022-11-01 18:41 UTC, Mstrodl commented
> Well, that's not a spa. It's the regular Keycloak login pages with a little bit of js and custom rest endpoints added on the top.

I'd like to avoid adding custom endpoints to keycloak if possible. Is it possible to get webauthn challenges through the admin API or something? It's one thing to check that a user exists, but determining which flow to use seems like it's better left up to keycloak. Right now, my login flow has a username form, followed by either a password form or a passwordless webauthn prompt. This isn't ideal, because password managers can't fill both the username and password fields because the page reloads. It's also not great, because webauthn prompts need user interaction (like a click) to work, which the browser loses when keycloak sends us to the next form page.

2022-11-02 07:55 UTC, stianst commented
We do plan to eventually turn the login pages completely into a SPA, but that will take some time.

It would be great if you open discussion or a issue to discuss further how the issues you are mentioning around identity-first, and webauthn, could be resolved. I'd love to see a solution to that built-in if we can figure out a decent way to do it.

This approach though is honestly just messy and a complete work-around, which is not something we'll want to incorporate.

2022-11-02 07:55 UTC, closed without merging