Fix race condition while updating Secrets labels in Operator
keycloak/keycloak pull request #15351
Opened 2022-11-04 18:50 UTC by vmuzikar

Closes #12942

There was occasionally a race condition in the Operator on watched Secrets when Operator overwrote a Secret that user (or test) just modified. That was due to incorrect handling of Secrets editing.

I did not add a new test for this as it is a bit hard to reliably reproduce. But the change is pretty simple as it is basically just alignment with [best practices](https://github.com/fabric8io/kubernetes-client/blob/f3e776b1557aa54c02b078f2b75382d932489e10/doc/CHEATSHEET.md#secret) in Fabric8.

I also sneaked in a log improvement for tests.

2022-11-04 18:51 UTC, vmuzikar commented
10 test runs (which were unstable previously): https://github.com/vmuzikar/keycloak/actions/runs/3396274587

2022-11-07 10:22 UTC, andre-nascimento-rh approved these changes
LGTM.
Good Job!

2022-11-07 11:03 UTC, mabartos requested changes
@vmuzikar Thanks for the PR! Could you please check the comment below? Thanks!

2022-11-07 11:03 UTC, mabartos commented on operator/src/main/java/org/keycloak/operator/controllers/WatchedSecretsStore.java
> +                client.secrets().inNamespace(secret.getMetadata().getNamespace()).withName(secret.getMetadata().getName())
I'm afraid the `secret.getMetadata().getNamespace()` can throw NPE. As the code is executed even when the metadata are null for the secret.

2022-11-07 11:48 UTC, mabartos commented on operator/src/main/java/org/keycloak/operator/controllers/WatchedSecretsStore.java
> +                client.secrets().inNamespace(secret.getMetadata().getNamespace()).withName(secret.getMetadata().getName())
Yep, you're right. I've been thinking about it in a more fault-tolerant way as after some invalid secret creation in a cluster, the whole process could be canceled. I was thinking about some warning dump and ignoring the secret, but it's probably better not to continue and solve the issue with that. Moreover, without a name, the secret wouldn't even be fetched, so the metadata are always there.

IMHO, the PR is ready to go. Thanks!

2022-11-07 11:56 UTC, pedroigor approved these changes

2022-11-07 12:07 UTC, merged