Fix (keycloak#15493): make nginx certificate-lookup thread safe
keycloak/keycloak pull request #15480
Opened 2022-11-13 20:28 UTC by Bukarim

The Keycloak leads to a ConcurrentModificationException under load-tests:

# Load-test with Gatling (before the fix):
 + description: During 1 minute, 3 users try to get an access token at the same time (X.509 authentication)
 + KeycloakVersion: 9.0.3, 16.1.1 & 19.0.3
 + reverse proxy: nginx  
 ```
/* load cert */
  private def getKeyStore(jksFile : File): KeyManagerFactory = {
    val clientKeystore: KeyStore = KeyStore.getInstance("JKS")
    val clientFis: FileInputStream = new FileInputStream(jksFile)
    clientKeystore.load(clientFis, PHRASE.toCharArray)
    clientFis.close()

    val kmf: KeyManagerFactory = KeyManagerFactory.getInstance(KeyManagerFactory.getDefaultAlgorithm)
    kmf.init(clientKeystore, PHRASE.toCharArray)
    kmf
  }
/* setup request */
exec(http("getAccessToken")
      .post("/auth/realms/LAB/protocol/openid-connect/token")
      .header("content-type", "application/x-www-form-urlencoded")
      .formParam("client_id", "xxxxxxxxx")
      .formParam("client_secret", "xxxxxxxxxxx")
      .formParam("username", "xxxxxxxxx")
      .formParam("grant_type", "password")
      .check(jmesPath("access_token").saveAs("accessToken"))

/* setup simulation */
  setUp(logonScenario.inject(rampUsers(3) during (1 seconds)).protocols(httpProtocolLab)
  ).maxDuration(1 minutes)
```
 # Result:
> request count                                  3403 (OK=3270   KO=133)
> failed                                               133 (  4%)

# logs: 
> ERROR [org.keycloak.services.error.KeycloakErrorHandler] (default task-574) Uncaught server error: java.util.ConcurrentModificationException 
> at java.base/java.util.HashMap$HashIterator.nextNode (HashMap.java:1493)
> at java.base/java.util.HashMap$KeyIterator.next(HashMap.java:1516)
> at org.bouncycastle//org.bouncycastle.jce.provider. CertStoreCollectionSpi.engineGetCertificates (Unknown Source)
> at java.base/java.security.cert.CertStore.getCertificates (CertStore.java:152)
> at org.bouncycastle//org.bouncycastle.jcajce.PKIXCertStoreSelector.getCertificates (Unknown Source)
> at org.bouncycastle//org.bouncycastle.jce.provider.CertPathValidatorUtilities.findCertificates (Unknown Source)
> at org.bouncycastle//org.bouncycastle.jce.provider.CertPathValidatorUtilities.findIssuerCerts (Unknown Source)
> at org.bouncycastle//org.bouncycastle.jce.provider.PKIXCertPathBuilderSpi.build(Unknown Source)
> at org.bouncycastle//org.bouncycastle.jce.provider.PKIXCertPathBuilderSpi.engineBuild(Unknown Source)
> at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
> at org.keycloak.keycloak-services@19.0.3//org.keycloak.services.x509. NginxProxySslClientCertificateLookup.buildChain (NginxProxySslClientCertificateLookup.java:193) 
> at org.keycloak.keycloak-services@19.0.3//org.keycloak.services.x509. NginxProxySslClientCertificateLookup.getCertificateChain (NginxProxySslClientCertificateLookup.java:131)
> at org.keycloak.keycloak-services@19.0.3//org.keycloak.authentication.DefaultAuthenticationFlow.processSingleFlowExecutionModel(DefaultAuthenticationFlow.java:438)
> at org.keycloak.keycloak-services@19.0.3//org.keycloak.authentication.DefaultAuthenticationFlow.processFlow (DefaultAuthenticationFlow.java:247)
> at org.keycloak.keycloak-services@19.0.3//org.keycloak.authentication. AuthenticationProcessor.authenticateOnly (AuthenticationProcessor.java:976)
> at org.keycloak.keycloak-services@19.0.3//org.keycloak.protocol.oidc.endpoints.TokenEndpoint.resourceOwner PasswordCredentialsGrant(TokenEndpoint.java:591) 
> at org.keycloak.keycloak-services@19.0.3//org.keycloak.protocol.oidc.endpoints. TokenEndpoint.processGrantRequest(TokenEndpoint.java:190)

# Load-test with Gatling (after the fix):
> request count                                    3008 (OK=3008   KO=0)
> failed                                                 0 (  0%)
# logs:
No Exception

2022-12-14 07:19 UTC, Bukarim commented
Hi @stianst , @patriot1burke we are still blocked. Who can help? Could you please review the pull request?

2022-12-14 07:59 UTC, stianst requested changes
Thanks for the PR, Provider instances themselves should be thread-safe, and should not contain static variables like what's used here. This should really be refactored so the ProviderFactory initializes the sets and passes it to the Provider.

To be honest this whole NginxProxySslClientCertificateLookup is a bit messy.

2022-12-14 09:44 UTC, mposolda commented
Yes, so maybe this PR is the opportunity to improve things and remove static variables.

Usually it can be good to use the initialization at factory level as factory (in this case NginxProxySslClientCertificateLookupFactory) is kind of "singleton". This means that variables can be declared in the factory and they can be declared as normal variables (non static variables) due to this. And they can be simply passed to the provider to the constructor. Also it is good to practice to either do this at "postInit" method or "lazy load" at factory level - for example see `DefaultJpaConnectionProviderFactory` for the inspiration. Especially methods `create` and `lazyInit` on that class.

2022-12-29 12:51 UTC, Bukarim commented
Hi @stianst & @mposolda , i refactored and formatted the two classes. There are no static variables any more: the factory initializes the required provider variables.

2023-01-03 07:18 UTC, mposolda requested changes
@Bukarim Few points:

- You changed the formatting of the classes and used indentation of 2 characters. In Keycloak, we try to stick with the indentation of 4 characters and that's what was used in those classes before. Is it possible if you changed the indentation back to 4 characters? This will simplify review as it will remove all the irrelevant formatting changes from your PR

- I think that the initialization you used is not correct. In the constructor of `NginxProxySslClientCertificateLookup`, you are sending the certificates as empty sets and the variable `isTruststoreLoaded` is sent always with `false`. This means that truststore needs to be loaded by the `NginxProxySslClientCertificateLookup` at every request, which is very bad for performance. I suggest that you change this as I've pointed in the previous comment - the initialization of certificates and the `isTruststoreLoaded` is done by the factory itself and then you always send the initialized values to the constructor of `NginxProxySslClientCertificateLookup`. See my previous comment for the details.

2023-01-03 08:00 UTC, Bukarim commented
@mposolda thx for the feedback, i will change it :)

2023-01-03 18:02 UTC, Bukarim commented
@mposolda pls re-review the PR. The load test passed and there were no exceptions

2023-01-05 16:13 UTC, mposolda requested changes
Looks much better, Thanks!

One last thing - it can happen that 2 threads are trying to call `NginxProxySslClientCertificateLookupFactory.create` at the same time and hence it would be possible that it is accidentally initialized 2 times (note the fact that `this.trustedRootCerts` and `this.internediateCerts` are concurrent maps is not necessarily enough as the certificates might be added 2 times into the map during the concurrent call).

So is it possible to use the protection against multiple initialization? I believe that method `loadKeycloakTruststore` can be changed like this to prevent this:
```
if (isTruststoreLoaded){
    return;
}

synchronized (this) {
     // Checking this again inside synchronized block to avoid multiple initializations
     if (isTruststoreLoaded){
         return;
     }
     ... Here the lines 78-90 from your PR
}
```

Also the variable `isTruststoreLoaded` may be needed to be changed to be `volatile`.

For the inspiration, see for example `DefaultJpaConnectionProviderFactory.lazyInit` or this article for some background about this pattern: https://www.baeldung.com/java-singleton-double-checked-locking

2023-01-06 10:27 UTC, Bukarim commented
@mposolda , loadKeycloakTruststore is now protected against multiple initialization, thx for the hint

2023-01-06 12:50 UTC, mposolda approved these changes, later dismissed
@Bukarim Thanks!

2023-01-06 12:56 UTC, Bukarim commented
Hi@mposolda, when can we expect the fixed release and which version?

2023-01-10 10:54 UTC, mposolda approved these changes
@Bukarim Thanks

2023-01-10 10:56 UTC, merged

2023-01-10 10:58 UTC, mposolda commented
@Bukarim It will be in Keycloak 21 release. This release will be probably in February 2023 (no promise).