update-email: email change does not affect the username when "Email as username" option is checked
keycloak/keycloak pull request #15583
Opened 2022-11-19 20:25 UTC by reda-alaoui

Fixes #13988

2022-12-10 09:53 UTC, reda-alaoui commented
@mposolda could somebody take a look at this? :)

2023-01-02 14:06 UTC, mposolda requested changes
@reda-alaoui Thanks for this fix!

I've added 2 minor comments inline. Could you please check them?

2023-01-02 14:06 UTC, mposolda commented on testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/AbstractAppInitiatedActionUpdateEmailTest.java
> +		setRegistrationEmailAsUsername(testRealm(), false);
Nitpick: Is it possible to remove the change on line  61 and instead call `setRegistrationEmailAsUsername(false);` at the end of the `updateWithEmailAsUsernameEnabled()` test? This is just to make sure that test is not affected if default settings for the realm are changed (For example if emailAsUsername is ever changed to true in the realm).

2023-01-02 14:06 UTC, mposolda commented on testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/AbstractRequiredActionUpdateEmailTest.java
> +		setRegistrationEmailAsUsername(testRealm(), false);
Nitpick: Is it possible to move this to the end of new test method instead? See similar comment for `AbstractAppInitiatedActionUpdateEmailTest`.

2023-01-05 14:32 UTC, reda-alaoui commented
> @reda-alaoui Thanks for this fix!
> 
> I've added 2 minor comments inline. Could you please check them?

Done :+1:

2023-01-05 20:46 UTC, pedroigor approved these changes

2023-01-06 13:03 UTC, mposolda approved these changes
@reda-alaoui @pedroigor Thanks for the update and review!

2023-01-06 13:04 UTC, merged