Update to Quarkus 2.14.1.Final
keycloak/keycloak pull request #15601
Opened 2022-11-21 15:54 UTC by abstractj

Closes #15329

Supersedes #15531

2022-11-21 15:55 UTC, abstractj commented
Follow up of https://github.com/keycloak/keycloak/pull/15552

2022-11-23 11:24 UTC, vmuzikar requested changes
@abstractj Thanks for the PR!

I can see a few issues here:
* We're actually not upgrading Quarkus. :) `quarkus.version` is not bumped.
* We're re-introducing `javax.annotation-api.version` that was removed [here](https://github.com/keycloak/keycloak/commit/5e891951f5edadb5ad7a595e4e34203e175668c5#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8L86).

I believe we need to review `set-quarkus-version.sh` a bit. Some issues we've faced with this upgrade are AFAICT caused by `mvn versions:revert`. Created https://github.com/keycloak/keycloak/issues/15644 for it.

Also opened https://github.com/abstractj/keycloak/pull/1 to fix the issues I found in this PR. Feel free to review/reject/merge them. ;)

2022-11-23 14:13 UTC, pedroigor approved these changes

2022-11-23 14:14 UTC, vmuzikar approved these changes

2022-11-23 15:00 UTC, merged