Enable all test methods in ConcurrentLoginTest for JPA Map Storage
keycloak/keycloak pull request #15609
Opened 2022-11-22 00:46 UTC by sguilhen

- Tests still disabled for Hotrod and CHM
- Fixes concurrent login issues with CRDB. Verified with both PostgreSQL and CockroachDB.

Closes #12707
Closes #13210

2022-11-22 13:14 UTC, ahus1 requested changes
Hi @sguilhen - looks good to me, one some change suggested, see below.

2022-11-22 13:21 UTC, sguilhen commented on services/src/main/java/org/keycloak/authentication/AuthenticationProcessor.java
> +            throw (RuntimeException) failure;
> IMHO one can't be sure that `failure` is a `RuntimeException`, although the current implementation suggests this.

Well, currently a retriable exception must be a SQLException whose state is 40001, and that is a RuntimeException. So if `isExceptionRetriable()` returns true we know the exception is a runtime one.

2022-11-22 13:22 UTC, sguilhen commented on services/src/main/java/org/keycloak/authentication/AuthenticationProcessor.java
> +            throw (RuntimeException) failure;
EDIT: actually it is not a RuntimeException, it is often encapsulated as one though. I'll change the code to follow your suggestion.

2022-11-22 13:23 UTC, ahus1 commented on services/src/main/java/org/keycloak/authentication/AuthenticationProcessor.java
> +            throw (RuntimeException) failure;
Hm, it is actually testing that the root exception is a `SQLException`. The wrapping exception can be anything, although its wrappers will most likely be a runtime exception as well.

2022-11-22 13:24 UTC, ahus1 commented on services/src/main/java/org/keycloak/authentication/AuthenticationProcessor.java
> +            throw (RuntimeException) failure;
Ah, now I see the edit; agreed. Please disregard my previous comment.

2022-11-22 13:41 UTC, ahus1 approved these changes
Thank you for this PR - this is a huge step forward on the road to CockroachDB support!

2022-11-23 11:51 UTC, vramik approved these changes

2022-11-24 12:36 UTC, hmlnarik approved these changes
Approving per @vramik 's and @ahus1 's reviews

2022-11-24 12:36 UTC, merged