Replace old HotRod index annotation with new one
keycloak/keycloak pull request #15676
Opened 2022-11-24 15:33 UTC by martin-kanis

Closes #12493

2022-12-01 09:59 UTC, martin-kanis commented
/rerun

2022-12-01 14:08 UTC, mhajas requested changes
Thank you for the PR @martin-kanis. I added two comments that I would say are worth attention. Could you please have a look?

Also, were you able to play with no-downtime upgrades for these new annotations? For example, from sortable to non-sortable, or projectable and so on?

2022-12-12 11:51 UTC, martin-kanis commented on model/map-hot-rod/src/main/java/org/keycloak/models/map/storage/hotRod/authSession/HotRodRootAuthenticationSessionEntity.java
> +    @Basic(sortable = true)
Changed to `projectable` after the performance analyses.

2022-12-12 11:55 UTC, martin-kanis commented on model/map-hot-rod/src/main/java/org/keycloak/models/map/storage/hotRod/IckleQueryOperators.java
> +                .combine(modelFieldName, new String[] {sanitizedValue.toLowerCase()}, parameters);
I added those checks and removed `toLowerCase()` by simplifying `ilike()` and `like()` methods into an one method.

2022-12-16 12:11 UTC, mhajas approved these changes
Thanks @martin-kanis! The changes LGTM, I added just one question that should not block merging. There are some failures in the GHA (probably not caused by this), could you please rebase?

2022-12-20 17:13 UTC, mhajas requested changes
@martin-kanis Can you please rebase to have GHA running with hotrod?

2022-12-21 10:18 UTC, martin-kanis commented on model/map-hot-rod/src/main/java/org/keycloak/models/map/storage/hotRod/authSession/HotRodRootAuthenticationSessionEntity.java
>      public String id;
Yes, it is possible. I tried it in my [PR](https://github.com/infinispan/infinispan/pull/10545) but I didn't commit it.

Also it is possible to project fields that are indexed, but not `projectable`. https://github.com/infinispan/infinispan/pull/10545/files#diff-a3580c88f69f3adefb7c2580e2aa7abcb0fe6e4f56d9058e7fd4ec35274af7c5R458

2022-12-21 11:19 UTC, mhajas commented on model/map-hot-rod/src/main/java/org/keycloak/models/map/storage/hotRod/authSession/HotRodRootAuthenticationSessionEntity.java
>      public String id;
ok, thanks for the confirmation @martin-kanis!

2022-12-21 11:20 UTC, martin-kanis commented
@mhajas All good after rebase.

2022-12-21 11:24 UTC, mhajas commented
> @mhajas All good after rebase.

I will just test locally, to be 100% sure the integration tests are running with the new annotations and if it is ok, I will merge.

2022-12-21 11:49 UTC, mhajas approved these changes
Thanks @martin-kanis, this works correctly. I am merging.

2022-12-21 11:50 UTC, merged