Fix certificate username conflict
keycloak/keycloak pull request #16499
Opened 2023-01-17 13:03 UTC by Bukarim

Closes #16490

2023-01-18 13:37 UTC, mposolda requested changes
@Bukarim I think that KeycloakErrorHandler is not proper place where to handle this case. It should be handled at the place where this error actually happened. Also it is needed to have a test for this.

2023-01-27 08:04 UTC, Bukarim commented
@mposolda thx for your feedback, i will change that :)

2023-02-07 13:57 UTC, Bukarim commented
@mposolda, I've moved the handling to the TokenEndpoint, I hope it's the right place.

In our company we use certificate-based authentication, we tested the fix and it conforms the expectations.
The subject "testing" is ambiguous/complicated: a certificate that is not outdated is required!! hence my question: is it possible to mock the test? Which package does this test belong to?

2023-02-14 08:39 UTC, mposolda commented
@Bukarim Thanks for the changes.

We try to avoid mocks. The "real test" can be nice. There is `X509DirectGrantTest`, which tests X.509 authentication for direct grant login (OAuth2 resource owner password credentials) and hence looks like good place to test this. I think you can relatively easily add new test method to this class. It seems to me that you don't need to generate new certificate or something like that (which is a bit pain, so good that you don't need this) as you can just use `username` parameter for some different user than the user present in the certificate and that's sufficient to reproduce the issue if I understand correctly?

2023-02-24 16:00 UTC, Bukarim commented
Hi @mposolda,
your tip was very helpful, thank you!
yes, you understood the situation very well.
I wrote a test for the use case, but surprisingly it failed: a token is always generated and the username doesn't matter, only the clientSecret has to be right.
I wrote a temporary method (org.keycloak.testsuite.util.OAuthClient#doAccessTokenRequestTemp) hoping to get the expected result, but it doesn't help.
is my test set wrong?
Any idea why the method (oauth.doGrantAccessTokenRequest) always returns a token even if the username is wrong?

2023-03-13 18:18 UTC, vilmosnagy requested changes

2023-03-14 08:49 UTC, Bukarim commented on services/src/main/java/org/keycloak/protocol/oidc/endpoints/TokenEndpoint.java
> +        }catch (AuthenticationFlowException exception){
i adjusted the try catch block 👍

2023-04-05 07:53 UTC, Bukarim commented
Hi @mposolda @vilmosnagy @stianst @rmartinc, could someone answer reply to my [comment](https://github.com/keycloak/keycloak/pull/16499#issuecomment-1443898247)
i need help to fix the test: (org.keycloak.testsuite.x509.X509DirectGrantTest#loginFailedOnCertificateCNIsNotTheSameAsClientUsername).

the method (org.keycloak.testsuite.util.OAuthClient#doGrantAccessTokenRequest(java.lang.String, java.lang.String, java.lang.String)) always returns a token, even if the username doesn't match the CN in the used certificate.

2023-04-05 10:46 UTC, jonkoops commented
@Bukarim could you rebase your work on `main`? There are a ton of unrelated commits in this PR at the moment which makes it hard to understand what changed.

2023-04-05 12:07 UTC, rmartinc commented
@Bukarim I think that the test works because the direct grant flow configuration for the test just contains the "X509/Validate Username" step (and not "Username Validation"). In my tests I just got your exception if the flow contains both steps (first "Username Validation" and then "X509/Validate Username", both required). Note that "Username Validation" is not needed for the X509 login, the user is obtained from the X509 certificate following the cx509 configuration. Is your direct grant flow containing the "Username Validation" step too?

2023-04-12 11:12 UTC, Bukarim commented
we've adjusted our flow and it's working as expected 🥇

2023-04-12 11:12 UTC, closed without merging