Make LockAcquiringTimeoutException a RuntimeException
keycloak/keycloak pull request #16700
Opened 2023-01-30 12:48 UTC by ahus1

Closes #16690

2023-01-30 13:49 UTC, ahus1 commented
@mhajas - this is now ready for review; the code with `RuntimeException` is now shorter than before. Thanks!

2023-01-30 14:47 UTC, mhajas requested changes

2023-01-30 14:47 UTC, mhajas commented on server-spi-private/src/main/java/org/keycloak/models/locking/LockAcquiringTimeoutException.java
> +public final class LockAcquiringTimeoutException extends RuntimeException {
Should we return the non-parametric constructor? This is to make sure the values `String lockName, String keycloakInstanceIdentifier, Instant timeWhenAcquired` are always set

2023-01-31 07:20 UTC, mhajas commented on server-spi-private/src/main/java/org/keycloak/models/locking/LockAcquiringTimeoutException.java
> +public final class LockAcquiringTimeoutException extends RuntimeException {
You are right. Sorry, it turned out I forgot how the no-argument constructor behaves when there is some parameteric added :man_facepalming:

2023-01-31 07:21 UTC, mhajas approved these changes
LGTM thanks!

2023-01-31 07:21 UTC, merged