Add Attribute to Group Mapper for SAML IDP
keycloak/keycloak pull request #16771
Opened 2023-02-01 17:15 UTC by bernard-denis

Add feature to map attribute to a group with saml IDP Provider 

Tested with Azure AD Saml IDP locally 

Closes #12950

2023-02-01 22:53 UTC, pedroigor requested changes
Thanks, @bernard-denis.

Do you mind looking at this [guide](https://github.com/keycloak/keycloak/blob/main/CONTRIBUTING.md) and following the first steps there to contribute to the project?

Basically, you should create an issue and link it to this PR as per the guide above.

The mapper you are proposing should enable and make it easier to assign federated users to groups dynamically. It should be a common use case.

We also need an integration test for it. It can be done similarly to `https://github.com/keycloak/keycloak/blob/f80a8fbed0940f28e8a23ebcdc5469c7299c0457/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcSamlAdvancedAttributeToRoleMapperTest.java#L21`. The same mapper that grants roles based on attributes is being tested by that test class.

2023-02-01 22:53 UTC, pedroigor commented on services/src/main/java/org/keycloak/broker/saml/mappers/AbstractAttributeToGroupMapper.java
> + * attribute into a {@code Keycloak} role.
The comment is still the same from `AbstractAttributeToRoleMapper`.

2023-02-01 22:53 UTC, pedroigor commented on services/src/main/java/org/keycloak/broker/saml/mappers/AbstractAttributeToRoleMapper.java
> -     * @return the {@link RoleModel} that corresponds to the mapper model role or {@code null}, if the role could not be
Could you please remove this change?

2023-02-01 22:56 UTC, pedroigor requested changes

2023-02-01 22:56 UTC, pedroigor commented on services/src/main/java/org/keycloak/broker/saml/mappers/AdvancedAttributeToGroupMapper.java
> + * @author <a href="mailto:denis.bernard@avanade.com">Denis Bernard</a>
Not here?

2023-02-02 08:10 UTC, bernard-denis commented
Thank @pedroigor for your review. 

I followed the contributing guide as well I understand it. 
I tagged my branch the issue number like explain,
I tagged the commit with the issue already created by community 
I didn't see how to link more my commit to the issue #12950 that I did. 

Sorry for the mistake test. 

As you can see, I build this function based on the current SAML Role mapper and the OIDC Group Mapper. 
and I didn't see this kind of test in the OIDC pull request (maybe I have miss read it). My bad to forget it
I'm not a developer, but I need this feature for my current customer, so I did my best for the contribution :) 

Thank for checking my work. I'll make the correction early.

2023-02-02 11:54 UTC, pedroigor commented on services/src/main/java/org/keycloak/broker/saml/mappers/AdvancedAttributeToGroupMapper.java
> + * @author <a href="mailto:denis.bernard@avanade.com">Denis Bernard</a>
Sorry, just like other classes you are adding, the `@author` should be right above the class declaration.

2023-02-02 11:56 UTC, pedroigor commented
@bernard-denis No worries, we appreciate your time on this. It is a useful mapper.

If you need help with the test, please let me know. That should be the last missing bit.

2023-02-03 01:11 UTC, bernard-denis commented
@pedroigor It seems good now. 
I build the test based on the SAML and OIDC existing test and made the correction asked
the CI task ran successfully (on my self hosted runner) the build and test (some part failed for missing dependency in my runner :) ).

2023-02-03 13:56 UTC, pedroigor reviewed
@bernard-denis Did some suggestions in order to make your test method to pass.

I think it will fail because you are not configuring the mapper to point to a valid group (`MAPPER_TEST_GROUP_PATH`)

To run the test, run the following command:

```
 mvn -f testsuite/integration-arquillian/pom.xml -Pauth-server-quarkus clean install -Dtest=KcCustomOidcBrokerTest
```

After that, you can run from your IDE too by enabling the `auth-server-quarkus-embedded` maven profile and then running the test class.

2023-02-03 13:56 UTC, pedroigor commented on testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcSamlAdvancedAttributeToGroupMapperTest.java
> +                .put(ConfigConstants.GROUP, groupValue)
```suggestion
                .put(ConfigConstants.GROUP, MAPPER_TEST_GROUP_PATH)
```

2023-02-03 13:56 UTC, pedroigor commented on testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcSamlAdvancedAttributeToGroupMapperTest.java
> +        assertThatUserHasBeenAssignedToGroup(user, KcOidcBrokerConfiguration.ATTRIBUTE_TO_MAP_NAME_2);
```suggestion
        assertThatUserHasBeenAssignedToGroup(user, MAPPER_TEST_GROUP_PATH);
```

2023-02-03 14:06 UTC, pedroigor commented
@bernard-denis Here is the changes I did https://github.com/pedroigor/keycloak/tree/tmp-broker.

We also need to remove the mapper after running the test otherwise it will mess up other test methods.

Not so good, but this area is a bit odd and we need to refactor some brokering tests ...

2023-02-03 19:33 UTC, pedroigor commented
@bernard-denis In order to be able to implement the test, I had to make some changes completely out of the scope. To avoid spending more of your time, I've sent https://github.com/keycloak/keycloak/pull/16840 with your changes plus those to the test.

I'm closing this one in favor of https://github.com/keycloak/keycloak/pull/16840.

2023-02-03 19:33 UTC, closed without merging

2024-05-09 22:00 UTC, obscuredByCloud commented
Hello, I am trying to map group idp attribuite to a group, this seems to work but it doesn't join the group.  
keycloak is managing the group and the saml IDP authenicates and sends back the name and group and I see the user attribte group is mapped, but when I look at the user, it only gives option to click on join, it doesn't auto-join the group. I'm probably missing something, or do I have to add code to do this?