Operator: use TLS Edge termination when back-end protocol is HTTP
keycloak/keycloak pull request #16813
Opened 2023-02-02 22:43 UTC by MikeEdgar

Keycloak Operator - Use TLS `edge` termination for ingress when the Keycloak back-end protocol is plain HTTP.

Fixes #16807

Signed-off-by: Michael Edgar <michael@xlate.io>

2023-02-08 09:08 UTC, vmuzikar requested changes
@MikeEdgar Thank you for the contribution!

Added a few minor comments, mainly to clean up the tests a bit.

2023-02-08 09:08 UTC, vmuzikar commented on operator/src/test/java/org/keycloak/operator/testsuite/unit/IngressLogicTest.java
> +        }
I think we should overload properly here:
```java
public static MockKeycloakIngress build(Boolean defaultIngressEnabled, boolean ingressExists, boolean ingressSpecDefined) {
            return build(defaultIngressEnabled, ingressExists, ingressSpecDefined, true);
        }
```

2023-02-08 09:08 UTC, vmuzikar commented on operator/src/test/java/org/keycloak/operator/testsuite/unit/IngressLogicTest.java
> +                    .ifPresent(http -> http.setTlsSecret(null));
I think we can (and actually should) assume here the `httpSpec` is present as we expect TLS to be configured in the example KC.
```suggestion
                kc.getSpec().getHttpSpec().setTlsSecret(null);
```

2023-02-08 15:07 UTC, vmuzikar approved these changes
@MikeEdgar Thanks for the update!

2023-02-08 15:07 UTC, merged

2023-02-08 17:25 UTC, MikeEdgar commented
Thanks for the review @vmuzikar. In which release milestone do you think this will be included?

2023-02-09 09:39 UTC, vmuzikar commented
@MikeEdgar Keycloak 21