Support to enforce LoA in authentication flow (Step-up)
keycloak/keycloak pull request #16897
Opened 2023-02-07 17:34 UTC by sventorben

Please see #16884 for details.

Closes #16884

2023-02-13 21:22 UTC, pedroigor reviewed
@sventorben Nice one :)

Test failures are related and seem related to changes in the number of built-in providers.

2023-02-15 19:22 UTC, pedroigor commented
@sventorben Thanks. We need to provide a test for it.

@mposolda May I ask you to continue reviewing and help with tests?

2023-02-16 11:53 UTC, mposolda requested changes
@sventorben Thanks for the PR. I've added one minor note inline. Besides that:

- I vote against `ConditionalClientIdAuthenticator`. It doesn't scale as realms can have thousands of clients. We already discussed (and rejected) this idea some time ago during the work on "client policies". The idea is to instead use some other ways to make sure that particular client matches the condition. For example it can be "marker" client role added to client or some kind of "marker" client scope.
 
This also allows that "client administrator" is not forced to contact "global realm administrator" to update authentication flow always when client wants to "enforce loa".

- Regarding `ForceLoAAuthenticator`, I would also prefer this to be rather "client policy executor" instead of "Authenticator". This will allow to re-use all existing conditions provided by current client policies instead of add new dedicated condition implementation to the authentication flow.
 
I see the possible issue that authenticationSession is not available when `AUTHORIZATION_REQUEST` client policy is triggered (on `AuthorizationEndpoint` - line 202). However hopefully this can be mitigated by either:
1) rewrite `claims` parameter and add enforced level to "essential" claims (if bigger than already provided in `claims` parameter)
2) add some `contextData<String, Object>` map to `AuthorizationEndpointRequest` . Client policy executor can set some attribute to it like MIN_ENFORCED_LOA_LEVEL. Then AuthorizationEndpoint (part of the codebase where Loa is parsed) can consume this.
3) add dedicated client policy event type like POST_AUTHORIZATION_REQUEST, which can be triggered after authenticationSession is parsed and available.

I think (2) is my favourite right now, but any of those works (whatever you find easiest).

- Tests are possible in `LevelOfAssuranceFlowTest` to test step-up. Tests for client policies are in package `org.keycloak.testsuite.client.policies` - for inspiration how to setup client policies (if we go this path).

2023-02-17 23:00 UTC, sventorben commented on services/src/main/java/org/keycloak/authentication/authenticators/browser/ForceLoAAuthenticator.java
> +            if (acrToLoaMap.containsKey(configuredAcr)) {
Yes, sure. Will do.

2023-02-17 23:22 UTC, sventorben commented
@mposolda
Using a client policy executor instead of an authenticator will not work for SAML clients, right?
At least I cannot find any client policy checks in the SamlEndpoint. Am I missing something?

Regarding the usage of  a "marker" client role or "marker" client scope, there is a `ClientScopesCondition` and `ClientRolesCondition` for use with client policies. But is there any condition supported within flows (like an authenticator)?

2023-02-20 08:37 UTC, mposolda commented
> @mposolda Using a client policy executor instead of an authenticator will not work for SAML clients, right? At least I cannot find any client policy checks in the SamlEndpoint. Am I missing something?
> 
> Regarding the usage of a "marker" client role or "marker" client scope, there is a `ClientScopesCondition` and `ClientRolesCondition` for use with client policies. But is there any condition supported within flows (like an authenticator)?

@sventorben Nope, it is not right now. That's also one of the reasons why I am more towards the "Client Policies" path, because the conditions are already available here. So only new thing needed here is the implementation of the executor though.

2023-03-07 21:28 UTC, mrpatrickpilch commented
@mposolda I have a use case in which this being an authenticator came in handy. I wanted to force an LoA after the "selected user" was determined (such as after a username/password form being completed) in an authentication flow. Not sure if I have access to user attributes/metadata in a client policy.

2023-03-14 15:31 UTC, sventorben commented
@mposolda Thanks for your reply. I added commit 75689bfd30091b465956234a2e54cebde36d9aba to this PR.
Would you mind taking a quick look at this just to check if I am going into the right direction here?

2024-10-21 12:07 UTC, mposolda commented
@sventorben Thanks for the PR and sorry for the late feedback.

In the end, we ended with the approach of https://github.com/keycloak/keycloak/pull/33205 . If it doesn't met your needs, feel free to create a follow-up issue if needed.

2024-10-21 12:07 UTC, closed without merging