Make lockTimeout more friendly for JPA map storage
keycloak/keycloak pull request #16990
Opened 2023-02-10 10:09 UTC by mhajas

Closes #16616

2023-02-10 11:29 UTC, ahus1 requested changes
Thank you for this PR, @mhajas.

I see that it don't show the warning all the time any more, and only once on the initialization of the factory. The documentation for the property has also been generated in the server guide. The CLI option works as expected when running Quarkus 

When testing this with PostgreSQL and Quarkus, I saw that this worked. Still, the code `createEntityManagerFactory()` is overwritten in Quarkus and will never be called. Due to that, the warning is never shown. This is a bit more complex to handle AFAIK, so I suggest to create a new issue for that if you think this should be fixed. As there are no other databases as PostgreSQL and CockroachDB for the JPA map storage, this is not something we would need to fix now.

Find below some small comments that IMHO should be changed before this issue can be merged. Thanks!

2023-02-10 11:29 UTC, ahus1 commented on testsuite/model/src/test/java/org/keycloak/testsuite/model/transaction/StorageTransactionTest.java
> +        reinitializeKeycloakSessionFactory();
When the test fails, the system property might not be cleaned up. 

Therefore wrap it in a try/finally, so it is cleaned up in all cases. 

In addition: the if/else should be wrapped with curly braces as best practice.

2023-02-10 11:47 UTC, mhajas commented
thank you for the review @ahus1. 
> When testing this with PostgreSQL and Quarkus, I saw that this worked. Still, the code createEntityManagerFactory() is overwritten in Quarkus and will never be called. Due to that, the warning is never shown. This is a bit more complex to handle AFAIK, so I suggest to create a new issue for that if you think this should be fixed. As there are no other databases as PostgreSQL and CockroachDB for the JPA map storage, this is not something we would need to fix now.

How are other options configured with Quarkus? For example `datasource`, `user`, etc.
https://github.com/keycloak/keycloak/blob/main/model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/JpaMapStorageProviderFactory.java#L380-L392

If there is some custom config, is it possible to configure `javax.persistence.lock.timeout` there?

2023-02-10 11:48 UTC, mhajas commented on testsuite/model/src/test/java/org/keycloak/testsuite/model/parameters/JpaMapStorageCockroachdb.java
> +                .config("lockTimeout", "${" + LOCK_TIMEOUT_SYSTEM_PROPERTY + ":}");
I added the comment to the property so it is accessible everywhere the property is used. Is it ok?

2023-02-10 12:16 UTC, ahus1 submitted a review, later dismissed
Thank you for updating this PR, ready to be merged!

2023-02-10 12:24 UTC, ahus1 commented
> How are other options configured with Quarkus

I suppose the settings would need to be picked from the configuration here https://github.com/keycloak/keycloak/blob/17bf092da638d03645c80725196284ffd91bffa5/quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/KeycloakProcessor.java#L248 or here https://github.com/keycloak/keycloak/blob/17bf092da638d03645c80725196284ffd91bffa5/quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/KeycloakProcessor.java#L297

From what I understand this is all done before the provider is instantiated, so needs to be duplicated somehow.

2023-02-14 10:21 UTC, ahus1 submitted a review, later dismissed
Hi @mhajas - those changes look good, and the additional option  now ends up in Quarkus as expected. 

As you pushed a second commit for this PR, either squash those commits now, on when merging this PR. Thanks.

2023-02-14 16:38 UTC, vmuzikar approved these changes

2023-02-14 16:38 UTC, vmuzikar commented on quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/KeycloakProcessor.java
> +
Reviewed just the Quarkus side and LGTM.

2023-02-15 08:49 UTC, ahus1 approved these changes
LGTM!

2023-02-15 08:51 UTC, ahus1 commented
@hmlnarik - reviewed, ready to be merged. Thanks!

2023-02-15 09:38 UTC, merged