Set working directory in Dockerfile
keycloak/keycloak pull request #17061
Opened 2023-02-13 20:25 UTC by sbrajchuk

This PR adds the `WORKDIR /opt/keycloak` instruction into the Dockerfile. Without this instruction, Keycloak would run in the root directory (`/`). 
This modification is essential for starting Keycloak container with the `QUARKUS_TRANSACTION_MANAGER_ENABLE_RECOVERY=true` environment variable. #15255

2023-02-13 20:33 UTC, pedroigor requested changes
@sbrajchuk We can also remove the `/opt/keycloak` path from the entrypoint, right?

@vmuzikar FYI.

2023-02-13 20:36 UTC, sbrajchuk commented
@pedroigor right.

2023-02-13 20:51 UTC, sbrajchuk commented
Ok. But either way, I think it is more appropriate to run Keycloak in `/opt/keycloak` rather than in the root directory (`/`)

2023-02-13 20:53 UTC, pedroigor approved these changes, later dismissed

2023-02-14 09:06 UTC, vmuzikar reviewed
Doesn't this add additional layer to the container image? Is this really required?

2023-02-14 13:23 UTC, sbrajchuk commented
#15255
Keycloak is currently unable to start inside a container because it tries to create an `ObjectStore` directory at the root directory `/`. If the working directory was intentionally set to the root directory to prevent any directory creation, then there is no need to make any changes.

2023-02-15 11:15 UTC, pedroigor commented
@vmuzikar IMO, this is a bad behavior as we don't want the server creating anything at the root directory (from where `kc.sh` is invoked`).

Not sure but perhaps we can also fix this in `kc.sh|bat` so that we make sure the server is executed from `kc.home.dir`? That could help to avoid the additional layer.

@sbrajchuk wdyt?

2023-02-15 15:00 UTC, vmuzikar commented
Fixing `kc.sh|bat` sounds like more robust solution to me, considering e.g. bare metal installations as well.

2023-02-15 15:36 UTC, sbrajchuk commented
We can set `QUARKUS_TRANSACTION_MANAGER_OBJECT_STORE_DIRECTORY` environment variable in `kc.sh|bat` to point to `kc.home.dir` or below.

2023-02-15 17:05 UTC, sbrajchuk commented
Or do not chage anything. If someone needs to use the transaction manager, they must configure the [quarkus.transaction-manager.enable-recovery](https://quarkus.io/guides/all-config#quarkus-narayana-jta_quarkus.transaction-manager.enable-recovery) **and** [quarkus.transaction-manager.object-store-directory](https://quarkus.io/guides/all-config#quarkus-narayana-jta_quarkus.transaction-manager.object-store-directory) via either a configuration file or environment variables.

2023-02-15 19:02 UTC, pedroigor commented
@sbrajchuk I think the issue you reported shows a problem and we need to fix it. We could easily map that property from Quarkus in our configuration layer and force it to a directory within `data` but we do need to run the server relative to `kc.home.dir`. If someday we want to support transaction recovery, we should also make life easier by not forcing users to set the option.

@vmuzikar Good point about making it also work for standalone deployments. Need to think more if we can not fix this issue within the server itself somehow so that we don't need duplicates in our script files.

2023-02-17 16:51 UTC, sschu commented
On a related note, when I start KC 20.0.3 `bin/kc.sh start-dev` I get: 2023-02-17 16:29:00,401 WARN  [io.quarkus.agroal.runtime.DataSources] (main) Datasource <default> enables XA but transaction recovery is not enabled. Please enable transaction recovery by setting quarkus.transaction-manager.enable-recovery=true, otherwise data may be lost if the application is terminated abruptly
I am not sure if this is due to h2 not supporting XA or because this setting is never enabled (it probably should be if the datasource supports it).

2023-03-27 15:15 UTC, pedroigor commented
Closed in favor of https://github.com/keycloak/keycloak/pull/17061.

2023-03-27 15:15 UTC, closed without merging