Apply to Keycloak documentation style to the Getting Started guides
keycloak/keycloak pull request #17173
Opened 2023-02-17 16:05 UTC by andymunro

Closes #17133

@stianst, @ahus1, @pedroigor, @DGuhr Please check these updates to conform the Getting Started guides to the Keycloak style guide: https://github.com/keycloak/keycloak-documentation/blob/main/internal_resources/styleguide.adoc

These changes make these guides match the other guides more closely. If you prefer, we could meet first to discuss some changes as part of a decision-driven documentation effort.

2023-02-17 16:35 UTC, ahus1 requested changes
Hi @andymunro - thank you for bringing this guide into shape!

See below for minor formatting issues. I also reviewed all the wording changes and they look valid from my Keycloak knowledge.

2023-02-17 16:35 UTC, ahus1 commented on docs/guides/src/main/getting-started/getting-started-openshift.adoc
>  [source,bash,subs="attributes+"]
The bash script should relate to the enumeration item, therefore add a "+" to keep them together.

```suggestion
. Create a project called `keycloak` by entering the following command:
+
[source,bash,subs="attributes+"]
```

2023-02-17 16:35 UTC, ahus1 commented on docs/guides/src/main/getting-started/getting-started-openshift.adoc
>  [source,bash,subs="attributes+"]
The bash script should relate to the enumeration item, therefore add a "+" to keep them together.

```suggestion
. Once the server is provisioned, enter the following command to find out the Keycloak URLs:
+
[source,bash,subs="attributes+"]
```

2023-02-17 16:35 UTC, ahus1 commented on docs/guides/src/main/getting-started/templates/first-app.adoc
> +* Set *Web origins* to `https://www.keycloak.org`
Those links are data that should be entered, and not clicked on. Therefore I added a passthrough so they are rendered as text and not as links. This was this way in the original docs, still it should be changed.

```suggestion
* Set *Valid redirect URIs* to `+https://www.keycloak.org/app/*+`
* Set *Web origins* to `+https://www.keycloak.org+`
```

2023-02-17 18:22 UTC, andymunro commented
Thanks @ahus1 for the fast response. I have made these corrections.

2023-02-17 18:26 UTC, ahus1 approved these changes
Thanks for these edits, approving it.

2023-02-20 09:09 UTC, ahus1 commented
@stianst - as you suggested, I had a look how the updated guides will be rendered on the upstream website, and it looks good. 

![image](https://user-images.githubusercontent.com/3957921/220061725-b4273db9-84f5-4c9a-90f7-28afbafcddf0.png)

2023-02-20 12:58 UTC, stianst approved these changes

2023-02-20 12:58 UTC, merged