Applying documentation style to the Operator Guide
keycloak/keycloak pull request #17205
Opened 2023-02-20 20:40 UTC by andymunro

Closes #17177
@ahus1, @stianst, @DGuhr, @pedroigor Please review

I had to change some Freemarker links to sections of the Server guide to be HTTPS links so they would work in RHBK.  However, they would still need to be converted to RHBK guidename links.  So I could revert those changes for now if you prefer.

2023-02-21 07:35 UTC, stianst requested changes
Please don't change the links. They are templated to use the correct links when publishing either to keycloak.org or to Pantheon.

2023-02-21 10:11 UTC, ahus1 requested changes
Thank you Andy for reviewing these docs! I reviewed them from the contents perspective and they look good. 

+1 for Stian's comment about the links: Please keep the `<link...>` elements as is. I'll fix the links for the downstream docs by replacing them with appropriate downstream URL. 

See below for some minor comments. I also dared to suggest a comma: As I'm a non-native speaker, that's just a a suggestion and I leave the final decision to you.

2023-02-21 10:11 UTC, ahus1 commented on docs/guides/src/main/operator/basic-deployment.adoc
> +The Keycloak Operator does not manage the database and you need to provision it yourself. Consider verifying your cloud provider offering or use a database operator such as https://access.crunchydata
```suggestion
The Keycloak Operator does not manage the database and you need to provision it yourself. Consider verifying your cloud provider offering or using a database operator such as https://access.crunchydata.com/documentation/postgres-operator/latest/[Crunchy].
```

2023-02-21 10:11 UTC, ahus1 commented on docs/guides/src/main/operator/realm-import.adoc
> +* If a Realm with the same name already exists in Keycloak it will not be overwritten.
```suggestion
* If a Realm with the same name already exists in Keycloak, it will not be overwritten.
```

2023-02-21 10:11 UTC, ahus1 commented on docs/guides/src/main/operator/realm-import.adoc
> +* The Realm Import CR only supports creation of new realms and doesn't update or delete those. Changes to the realm performed directly on Keycloak are not synced back in the CR.
```suggestion
* The Realm Import CR only supports creation of new realms and does not update or delete those. Changes to the realm performed directly on Keycloak are not synced back in the CR.
```

2023-02-21 16:40 UTC, andymunro commented
Thanks for the comments, including the comma, @ahus1, which I have addressed. I have also reverted the links to Freemarker format.

2023-02-21 18:08 UTC, ahus1 requested changes
Hi @andymunro - thanks for reverting back the `<link...>` elements.

I noticed that one of them switch its ID. Please update it with the old ID. 

The other missing `.` where probably missing before anyway, and I might have missed them in the previous review.

Thanks!

2023-02-21 18:08 UTC, ahus1 commented on docs/guides/src/main/operator/basic-deployment.adoc
> +See <@links.server id="db"/> for the available configurations.
```suggestion
See <@links.server id="hostname"/> for the available configurations.
```

2023-02-21 18:08 UTC, ahus1 commented on docs/guides/src/main/operator/customizing-keycloak.adoc
> +For instructions on how to build such an image, see <@links.server id="containers"/>
```suggestion
For instructions on how to build such an image, see <@links.server id="containers"/>.
```

2023-02-21 18:08 UTC, ahus1 commented on docs/guides/src/main/operator/realm-import.adoc
> +The recommended way to obtain a `RealmRepresentation` is by leveraging the export functionality <@links.server id="importExport"/>
```suggestion
The recommended way to obtain a `RealmRepresentation` is by leveraging the export functionality <@links.server id="importExport"/>.
```

2023-02-21 19:21 UTC, andymunro commented
Thanks, @ahus1.  Corrections made plus a couple of other minor improvements.

2023-02-22 09:43 UTC, ahus1 submitted a review, later dismissed
Thank you for those changes, they look good to me!

2023-02-22 09:44 UTC, ahus1 commented
@stianst - this is IMHO now ready to be merged. Thanks!

2023-02-27 14:05 UTC, stianst reviewed
LGTM, but @vmuzikar should probably take a look as well before we merge

2023-02-27 16:38 UTC, vmuzikar requested changes
@andymunro Added a few comments, thank you.

2023-02-27 16:38 UTC, vmuzikar commented on docs/guides/src/main/operator/advanced-configuration.adoc
> +* Fields that apply to a Kubernetes environment
```suggestion
* Fields that do not apply to a Kubernetes environment
```

Or maybe even something like:
```
Fields that are not relevant to a Kubernetes environment
```

2023-02-27 16:38 UTC, vmuzikar commented on docs/guides/src/main/operator/customizing-keycloak.adoc
> +=== Custom image and build configuration
I would like to suggest the users what we consider a best practice. Without this heading, I thing the empasis on building a custom image is not as strong as it was.

2023-02-28 07:49 UTC, vmuzikar approved these changes
LGTM, thanks @andymunro.

2023-03-01 15:24 UTC, merged