Adds Portuguese translations
keycloak/keycloak pull request #17531
Opened 2023-03-09 11:02 UTC by froque

Closes #17530

2023-03-13 22:20 UTC, trixpan requested changes
you seem to be mixing unicode and non-unicode messages.

IMNSHO you should stick to using the unicode notation across all files.

2023-03-13 22:20 UTC, trixpan commented on themes/src/main/resources-community/theme/keycloak.v2/account/messages/messages_pt.properties
> +unknownUser=Anónimo
use unicode across the board

2023-03-13 22:20 UTC, trixpan commented on themes/src/main/resources-community/theme/keycloak.v2/account/messages/messages_pt.properties
> +needAccessRights=Não tem as permissões de acesso para esta solicitação. Entre em contato com um administrador.
use unicode across the board

2023-03-14 00:06 UTC, froque commented
@trixpan I thought I was using UTF-8 already. 

```shell
❯ find themes/src/ -name messages_pt.properties| xargs file -i 
themes/src/main/resources-community/theme/keycloak.v2/account/messages/messages_pt.properties: text/plain; charset=utf-8
themes/src/main/resources-community/theme/base/admin/messages/messages_pt.properties:          text/plain; charset=utf-8
themes/src/main/resources-community/theme/base/account/messages/messages_pt.properties:        text/plain; charset=utf-8
themes/src/main/resources-community/theme/base/email/messages/messages_pt.properties:          text/html; charset=utf-8
themes/src/main/resources-community/theme/base/login/messages/messages_pt.properties:          text/plain; charset=utf-8
❯ find themes/src/ -name messages_pt.properties| xargs isutf8
```

This seems to be similar to latest Arabic translation addition https://github.com/keycloak/keycloak/pull/17090
```
❯ find themes/src/ -name messages_ar.properties| xargs file -i 
themes/src/main/resources-community/theme/keycloak.v2/account/messages/messages_ar.properties: text/plain; charset=utf-8
themes/src/main/resources-community/theme/base/admin/messages/messages_ar.properties:          text/plain; charset=utf-8
themes/src/main/resources-community/theme/base/account/messages/messages_ar.properties:        text/plain; charset=utf-8
themes/src/main/resources-community/theme/base/email/messages/messages_ar.properties:          text/html; charset=utf-8
themes/src/main/resources-community/theme/base/login/messages/messages_ar.properties:          text/plain; charset=utf-8
❯ find themes/src/ -name messages_ar.properties| xargs isutf8
```

Am I missing something ?

2024-02-17 22:12 UTC, codespearhead commented
@froque 

Unlike all the other edited files in your commit, [this file](https://github.com/keycloak/keycloak/blob/5190a02ace37dfc5737ba2f5bd2f85cf1606d532/themes/src/main/resources-community/theme/keycloak.v2/account/messages/messages_pt.properties) isn't using Unicode escape sequences.

- OK
https://github.com/keycloak/keycloak/blob/5190a02ace37dfc5737ba2f5bd2f85cf1606d532/themes/src/main/resources-community/theme/base/login/messages/messages_pt_BR.properties#L7

- Not OK
https://github.com/keycloak/keycloak/blob/5190a02ace37dfc5737ba2f5bd2f85cf1606d532/themes/src/main/resources-community/theme/keycloak.v2/account/messages/messages_pt.properties#L18

The Arabic translation is an exception since everything would have to be represented as Unicode escape sequences.

I'm willing to collaborate on this PR btw (I'm Brazilian).

2024-02-28 13:14 UTC, jonkoops commented
Closing this as it has massive conflicts that are not likely to be resolved. All our property files are read as UTF-8 now, so there is no need to use any escape sequences.

2024-02-28 13:14 UTC, closed without merging