[WIP] Remove AccountTotpPage from the testsuite #15201
keycloak/keycloak pull request #17657
Opened 2023-03-14 14:55 UTC by lhanusov

fix #15201

2023-04-05 15:30 UTC, mposolda requested changes
@lhanusov Thanks!

This PR will require some rebase due the conflict with other PR for consents https://github.com/keycloak/keycloak/pull/17651 .

Besides that, I've added some inline comments (basically I suggested to use something like `fooPage.assertCurrent()` instead of `assertTrue(fooPage.isCurrent())` (See method `assertCurrent()` for the details).

2023-04-05 15:30 UTC, mposolda commented on testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/storage/BackwardsCompatibilityUserStorageTest.java
> +        assertTrue(loginTotpPage.isCurrent());
`loginTotpPage.assertCurrent()` is slightly better?

2023-04-05 15:30 UTC, mposolda commented on testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/storage/BackwardsCompatibilityUserStorageTest.java
> +        assertTrue(appPage.isCurrent());
`appPage.assertCurrent()` is slightly better

2023-04-05 15:30 UTC, mposolda commented on testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/storage/BackwardsCompatibilityUserStorageTest.java
> +        assertTrue(appPage.isCurrent());
Same as above

2023-04-05 15:30 UTC, mposolda commented on testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/ResetCredentialsAlternativeFlowsTest.java
> +            Assert.assertTrue(totpPage.isCurrent());
totpPage.assertCurrent

2023-04-06 08:44 UTC, lhanusov commented
@mposolda Hello Marek, thank you for the review, suggestions resolved and applied.

2023-04-06 09:48 UTC, mposolda approved these changes

2023-04-06 09:49 UTC, merged