Incorrect documentation around password policies
keycloak/keycloak pull request #19364
Opened 2023-03-27 18:48 UTC by pedro-hos

closes #19363

2023-03-27 19:13 UTC, mposolda approved these changes, later dismissed
@pedro-hos Thanks! This looks good to me assuming that we go in a way of handling this in the documentation. Will discuss this within the team as well.

2023-03-28 21:42 UTC, andymunro commented on docs/documentation/server_admin/topics/authentication/password-policies.adoc
> +The new policy will not be effective for existing users. So, Make sure that you set the password policy from the beginning of the realm creation and/or add "Update password" to existing users and/or
```suggestion
The new policy will not be effective for existing users. Therefore, make sure that you set the password policy from the beginning of the realm creation or add "Update password" to existing users  or use "Expire password" to make sure that users update their passwords in next "N" days, which will actually adjust to new password policies.
```

2023-03-28 21:42 UTC, andymunro requested changes
@mposolda  A few suggestions.

2023-03-29 06:56 UTC, mposolda commented
@andymunro Thanks!

2023-03-29 06:57 UTC, mposolda approved these changes

2023-03-29 08:09 UTC, merged

2023-03-29 14:37 UTC, pedro-hos commented
Thank you @andymunro and @mposolda