Remove legacy Promise APIs from Keycloak JS
keycloak/keycloak pull request #19389
Opened 2023-03-28 14:10 UTC by jonkoops

Closes #19388

2023-03-28 15:10 UTC, mhajas requested changes
To me, it makes sense to add this change to release notes.

I see the base test suite was skipped for this PR, we should run at least [this class](https://github.com/keycloak/keycloak/blob/main/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/javascript/JavascriptAdapterTest.java) for this. I assume this test method will fail:
https://github.com/keycloak/keycloak/blob/08829835ea51dcf5bc3d240b08c4c4bb1d40c148/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/javascript/JavascriptAdapterTest.java#L815-L829

2023-03-28 15:57 UTC, jonkoops commented
@mhajas updated the test you mentioned, that should also kick off the CI.

> To me, it makes sense to add this change to release notes.

Agreed. Do we have a process in place for that? How can I contribute this?

2023-03-28 16:23 UTC, mhajas requested changes
Thank you for the update @jonkoops. I added one more comment to the code.

Release notes are here: 
https://github.com/keycloak/keycloak/tree/main/docs/documentation/release_notes

You need to create a new file `22_0_0.adoc` (interesting it is not there already) and add it to [index.adoc](https://github.com/keycloak/keycloak/blob/main/docs/documentation/release_notes/index.adoc). You can just follow how it is done for [21_0_0.adoc](https://github.com/keycloak/keycloak/blob/main/docs/documentation/release_notes/topics/21_0_0.adoc).

2023-03-28 23:09 UTC, jonkoops commented on testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/javascript/JavascriptAdapterTest.java
>      public void testRefreshTokenWithDeprecatedPromiseHandles() {
Ahh, yeah agreed. I went ahead and removed this test entirely.

2023-03-28 23:10 UTC, jonkoops commented
@mhajas I've removed the test for the legacy methods and added some documentation the docs. Can I ask you to take another look?

2023-03-29 06:40 UTC, mhajas requested changes
Thanks for the update @jonkoops. I added two more comments. 

Also, I just realized you don't have `Closes #19388` in your commit message, can you [add it there as well](https://github.com/keycloak/keycloak/blob/main/CONTRIBUTING.md#commit-messages-and-issue-linking)?

2023-03-29 06:40 UTC, mhajas commented on docs/documentation/release_notes/topics/22_0_0.adoc
> +*Before:*
Sorry, I should have told you before. Release notes should contain only a brief description of what was changed. Details on what migration steps are needed should be mentioned in [upgrading docs](https://github.com/keycloak/keycloak/blob/main/docs/documentation/upgrading/topics/keycloak/changes-22_0_0.adoc).

See, for example, this PR to the old docs repository: https://github.com/keycloak/keycloak-documentation/pull/1760/files

2023-03-29 07:58 UTC, jonkoops commented
> Also, I just realized you don't have `Closes #19388` in your commit message, can you [add it there as well](https://github.com/keycloak/keycloak/blob/main/CONTRIBUTING.md#commit-messages-and-issue-linking)?

This will get added when we merge the PR through GitHub's UI.

2023-03-29 08:09 UTC, jonkoops commented on docs/documentation/release_notes/topics/22_0_0.adoc
> += Legacy Promise API removed from Keycloak JS
Changed this everywhere 'Keycloak JS' is mentioned.

2023-03-29 08:10 UTC, jonkoops commented
@mhajas I updated the docs with your suggestions, can you take another look?

2023-03-29 13:26 UTC, mhajas approved these changes, later dismissed
Thank you for the update. The PR looks good to me now.

> > Also, I just realized you don't have `Closes #19388` in your commit message, can you [add it there as well](https://github.com/keycloak/keycloak/blob/main/CONTRIBUTING.md#commit-messages-and-issue-linking)?
> 
> This will get added when we merge the PR through GitHub's UI.

The issue number is not added to the commit message on merge.

I am approving this PR because code-wise it looks good to me, however, regarding the commit message I think we should either follow the rules from the [CONTRIBUTING.md](https://github.com/keycloak/keycloak/blob/main/CONTRIBUTING.md) guide or start a discussion for changing it so we can all agree on one process.

2023-03-29 13:34 UTC, stianst approved these changes, later dismissed
LGTM haven't done a review of the code though, so rely on others to do that.

2023-03-29 14:59 UTC, jonkoops commented
> I am approving this PR because code-wise it looks good to me, however, regarding the commit message I think we should either follow the rules from the [CONTRIBUTING.md](https://github.com/keycloak/keycloak/blob/main/CONTRIBUTING.md) guide or start a discussion for changing it so we can all agree on one process.

Yeah, I started a discussion on the mailing list about this but it ended up dying out. My peeve is that issue numbers in commits were a thing when we were still using JIRA. Now that we've got everything on GitHub it will automatically put the PR number in the commit title when merging to `main`, making this procedure less relevant.

2023-03-29 15:04 UTC, agagancarczyk approved these changes

2023-03-29 15:06 UTC, vmuzikar reviewed
Does this have any impact on quickstarts?

2023-03-29 15:12 UTC, pedroigor approved these changes

2023-03-29 15:17 UTC, vmuzikar approved these changes

2023-03-29 16:29 UTC, merged