Set default object store directory via application.properties
keycloak/keycloak pull request #19384
Opened 2023-03-28 13:34 UTC by sbrajchuk

Set default directory name for the location of the transaction logs

Can be overriden by setting the [quarkus.transaction-manager.object-store-directory](https://quarkus.io/guides/all-config#quarkus-narayana-jta_quarkus.transaction-manager.object-store-directory) property in the quarkus.properties file or by setting the environment variable QUARKUS_TRANSACTION_MANAGER_OBJECT_STORE_DIRECTORY

Closes #15255

2023-03-28 14:17 UTC, pedroigor submitted a review, later dismissed
@sbrajchuk @vmuzikar LGTM.

Perhaps the directory name is not so meaningful and `data/transaction/object-store` is better. But I'm not sure.

2023-03-29 08:52 UTC, vmuzikar commented on quarkus/runtime/src/main/resources/application.properties
> +quarkus.transaction-manager.object-store-directory=${kc.home.dir}/data/transaction-logs
@pedroigor Is that a correct format? ^^

2023-03-29 09:14 UTC, sbrajchuk commented on quarkus/runtime/src/main/resources/application.properties
> +quarkus.transaction-manager.object-store-directory=${kc.home.dir}/data/transaction-logs
Tested on Windows and confirmed that the Linux separator functions properly. Your approach also works, but I believe your method appears to be more accurate.

2023-03-29 09:29 UTC, vmuzikar approved these changes
@sbrajchuk Thanks, LGTM.
Let's wait for an approval from @pedroigor before merging this.

2023-03-29 09:30 UTC, vmuzikar requested changes
@sbrajchuk Actually, one more thing. Could you please create and link a GH Issue to this, see our [contribution guide](https://github.com/keycloak/keycloak/blob/main/CONTRIBUTING.md#contributing-to-keycloak).

2023-03-30 15:07 UTC, pedroigor approved these changes

2023-03-30 15:23 UTC, vmuzikar approved these changes

2023-03-30 15:24 UTC, merged

2023-03-30 19:51 UTC, pedroigor commented
@sbrajchuk Thanks.