Include Account Console version 3 as a theme
keycloak/keycloak pull request #19641
Opened 2023-04-11 13:47 UTC by jonkoops

Includes the new Account Console (v3) theme behind an 'experimental' feature.

Closes #19524

2023-04-12 10:53 UTC, edewit approved these changes, later dismissed

2023-04-12 12:30 UTC, edewit submitted a review, later dismissed
what it still needed is a way to disable / enable groups and resources in the console

2023-04-12 13:11 UTC, ssilvert submitted a review, later dismissed
LGTM

2023-04-12 14:14 UTC, edewit submitted a review, later dismissed

2023-04-12 15:03 UTC, edewit approved these changes, later dismissed

2023-04-13 01:17 UTC, ssilvert requested changes

2023-04-13 08:03 UTC, edewit approved these changes

2023-04-13 08:29 UTC, agagancarczyk approved these changes

2023-04-13 10:10 UTC, stianst approved these changes
LGTM

2023-04-13 13:41 UTC, ssilvert approved these changes

2023-04-13 13:41 UTC, merged