new link for "edit this section" button
keycloak/keycloak pull request #19680
Opened 2023-04-12 20:55 UTC by buti1021

The link for the edit this section was still pointing to the old location. This PR fixes this

2023-04-13 13:26 UTC, jonkoops requested changes
If I do a quick search for `keycloak/keycloak-documentation` I can find quite a lot of other documents that have to be updated.

@buti1021 would you mind fixing these issues as well in this PR?

2023-04-15 23:51 UTC, buti1021 commented
Hey @jonkoops, yes that would kinda make sense, however I'm not really sure how to update the other occurences:

This is what I found:
![image](https://user-images.githubusercontent.com/49496963/232258671-4dd025a9-28f2-4c58-b337-cd2dc33878fe.png)

Leaving us with 4 files including `keycloak/keycloak-documentation`:
1. keycloak/keycloak/docs/documentation/internal_resources/contributing.adoc
2. keycloak/keycloak/docs/documentation/release_notes/topics/21_1_0.adoc
3. keycloak/keycloak/docs/documentation/tests/src/test/resources/ignored-links
4. keycloak/keycloak/docs/documentation/topics/templates/header.adoc

My understanding of the usage:
1. Seems to me like a super outdated file, not sure how much just replacing links here makes sense, I'm not even sure where this file is used.
2. This file just includes the info, that the repos have been consolidated, the old link should be used here
3. Not sure how the testing works, might just be possible to remove the old link here, might also need to replace it.
4. This is the occurence I changed with my first commit.

2023-04-17 10:11 UTC, jonkoops commented
Hmmm, yes. Looking at the contributing document I am not entirely sure why it exists. Especially as we already have a similar document in [the repository](https://github.com/keycloak/keycloak/blob/main/CONTRIBUTING.md). 

Let's get this merged as-is, it's already an improvement. @andymunro can you let me know if we can perhaps get rid of the contribution guide? I'd like to avoid duplicating documentation.

2023-04-17 10:11 UTC, jonkoops approved these changes

2023-04-17 12:31 UTC, ssilvert commented
This is for @andymunro.  He should be the one to work on it.

2023-04-17 18:33 UTC, andymunro commented
@jonkoops 

[This file ](https://github.com/keycloak/keycloak/blob/main/CONTRIBUTING.md) is focused on contributing to Keyloak.  It includes a link (in the Documentation section) to a Readme which links to the Contributing.adoc file,  which is focused on contributing to documentation. So we don't want to remove it.

It seems we may have some duplication of content, but we don't want to break any links.

@ahus1 rearranged the documentation file structure, so he might know more.

2023-04-17 20:43 UTC, ahus1 commented
Yes, I've been the one leading the move of keycloak-documentation. Having those links to the repository were off my radar, sorry for that. 

Let's merge this PR as is to fix the `header.adoc`. I'll review the remaining files in another issue/pull request (probably next week).

2023-04-17 20:43 UTC, ahus1 approved these changes
Thanks for changing this link.

2023-04-18 06:42 UTC, stianst approved these changes

2023-04-18 06:42 UTC, merged