Adding a list of translated texts, to check the right path
keycloak/keycloak pull request #19747
Opened 2023-04-17 06:39 UTC by sharifrezvani

I just translated a couple of sentences and texts to see if I'm on the right path or not. 

This is related to https://github.com/keycloak/keycloak/issues/19604

Thank you guys.

2023-04-17 10:26 UTC, jonkoops commented
Please also refrain from updating the PR with `main` through the GitHub interface. This is not needed for a merge and results in unnecessary merge commits and notifications.

2023-04-26 12:08 UTC, jonkoops requested changes
This is a good change, but to add a locale properly it also needs to be added [under the base theme](https://github.com/keycloak/keycloak/tree/main/themes/src/main/resources-community/theme/base/admin/messages). Create a file there that contains the same labels as the [English version](https://github.com/keycloak/keycloak/blob/main/themes/src/main/resources/theme/base/admin/messages/messages_en.properties).

This will allow Keycloak to pick up the locale as expected.

2023-05-01 08:22 UTC, sharifrezvani commented
@jonkoops Thank you for your guidance. I believe that in my latest commit I have created all the necessary files and all of the needed translations. Let me know if there's anything that I would need to change.

2023-05-08 08:24 UTC, sharifrezvani commented
@jonkoops Just as a reminder, is there anything else that I need to do or are the requested changes satisfied now?

2023-05-15 15:05 UTC, jonkoops commented
@sharifrezvani Sorry for the late reply, I was busy with some other tasks. In order for Keycloak to pick up these new labels you'll have to add the locale code to the following files to make this work:

- `themes/src/main/resources-community/theme/base/account/theme.properties`
- `themes/src/main/resources-community/theme/base/admin/theme.properties`
- `themes/src/main/resources-community/theme/base/email/theme.properties`
- `themes/src/main/resources-community/theme/base/login/theme.properties`

2023-05-25 11:51 UTC, jonkoops commented
@sharifrezvani just checking, are you still interested in landing this?

2023-05-27 13:03 UTC, sharifrezvani commented
@jonkoops I'm terribly sorry for replying this late. I got caught up with work as well. Yes, I will give this the final touches that you mentioned ASAP. thank you for your patience

2023-06-05 18:32 UTC, ssilvert commented
@sharifrezvani Please do finish this up.  We are trying to get rid of our older PRs.  If you are unable to finish it in the next couple of days we can close the PR and reopen when you are ready.

Also, I'm wondering why some messages were left untranslated?

2023-06-07 06:36 UTC, sharifrezvani commented
@ssilvert sorry again for the late reply,I hope that didn't come across as rude.

I made the changes which @jonkoops asked for.

As for the messages which are not translated, please show me some examples. I did find 4 messages which I had missed during the translation and I changed them to Farsi in my latest commit.
But if you are talking about some acronyms like "URL", the thing is, even though these words have translations in Farsi, common (even pro) users aren't aware of their translations. for example, the word "URL" would be "مکان‌یاب منبع یکسان" in Farsi, but no one knows what this means. However, almost everyone knows the meaning of URL.
You might also be talking about other messages like "Google Authenticator" or "Recaptcha", again, these are specific services by well-known companies which if they are translated, they won't sound familiar to Farsi users anymore.

However, I would gladly change the translations if you want me to. I just believe that these will be more useful to Farsi users. But if you guys have any sort of conventions, I will change them.

Still, do show me some examples so that I can fix the issues or explain them.

2023-06-07 09:43 UTC, jonkoops commented
@sharifrezvani can you add `locale_fa` to `themes/src/main/resources/theme/base/account/messages/messages_X.properties` (X being each language) as well? That way it will show up in the list of languages when logging in, right now it's not displayed:

![image](https://github.com/keycloak/keycloak/assets/695720/ef2bffe4-b1d9-492e-b512-1782ccf967ae)

2023-06-07 09:45 UTC, jonkoops commented
Also, the files for the Admin UI are not yet translated. Do you intend to pick that up separately?

2023-06-07 10:33 UTC, sharifrezvani commented
@jonkoops I added the locale_fa in other language files in the commit that I just made.

And yes I'll do the Admin UI later separately. I'll open up another PR in the coming days for that.

2023-06-07 10:37 UTC, jonkoops commented
@sharifrezvani why are those strings encoded in unicode? Doesn't UTF-8 natively support the Persian alphabet ?

2023-06-07 10:42 UTC, sharifrezvani commented
@jonkoops it does, but the other languages aren't utf-8 so i thought that would cause a problem

2023-06-07 10:57 UTC, jonkoops commented
Hmmm, yeah I see that it's not the case for all languages. We should fix that, so I've logged #20848 for it.

2023-06-07 10:58 UTC, jonkoops submitted a review, later dismissed
The changes here look good, but I would like a native speaker to review this as well.

2023-06-07 10:59 UTC, jonkoops commented
@kasir-barati would you be willing to review this pull request?

2023-06-07 17:25 UTC, ssilvert commented on js/apps/account-ui/public/locales/fa/translation.json
> +    "infoMessage": "By clicking Remove Access, you will remove granted permissions of this application. This application will no longer use your information.",
Not translated?

2023-06-07 17:25 UTC, ssilvert commented on js/apps/account-ui/public/locales/fa/translation.json
> +    "removeModalMessage": "This will remove the currently granted access permission for {{0}}. You will need to grant access again if you want to use this app.",
Not translated?

2023-06-07 17:25 UTC, ssilvert commented on js/apps/account-ui/public/locales/fa/translation.json
> +    "removeModalTitle": "Remove access",
Not translated?

2023-06-07 17:27 UTC, ssilvert commented on js/apps/account-ui/public/locales/fa/translation.json
> +    "signOutAllDevicesWarning": "This action will sign out all the devices that have signed in to your account, including the current device you are using.",
Not translated?

2023-06-07 17:27 UTC, ssilvert commented on js/apps/account-ui/public/locales/fa/translation.json
> +    "signingInDescription": "Configure ways to sign in.",
Not translated?

2023-06-07 17:27 UTC, ssilvert commented on js/apps/account-ui/public/locales/fa/translation.json
> +    "signedInDevicesExplanation": "Sign out of any unfamiliar devices.",
Not translated?

2023-06-07 17:27 UTC, ssilvert commented on js/apps/account-ui/public/locales/fa/translation.json
> +    "shareUser": "Add users to share your resource with",
Not translated?

2023-06-07 17:28 UTC, ssilvert commented on js/apps/account-ui/public/locales/fa/translation.json
> +    "setUpNew": "Set up {{0}}",
Not translated?

2023-06-07 17:34 UTC, ssilvert commented
> @ssilvert sorry again for the late reply,I hope that didn't come across as rude.
> 
No problem at all.  On the UI team, we try to keep older, open PRs to a minimum.   And it's not a problem if we need to close a PR and revisit later.

> As for the messages which are not translated, please show me some examples.
> 
I commented on the messages that are untranslated.  If there is some reason for leaving it untranslated then that's OK.

2023-06-10 07:25 UTC, sharifrezvani commented
@ssilvert My mistake, I had completely forgotten about these. Thank you for pointing these out. If you'll allow me, I'll translate these in the next couple of hours. but if not, I'll do them in the next PR which I will open up for the admin-ui files. I'm asking because I don't know if it's OK for me to make any further changes at this stage.

2023-06-12 17:04 UTC, ssilvert commented
> @ssilvert My mistake, I had completely forgotten about these. Thank you for pointing these out. If you'll allow me, I'll translate these in the next couple of hours. but if not, I'll do them in the next PR which I will open up for the admin-ui files. I'm asking because I don't know if it's OK for me to make any further changes at this stage.

@sharifrezvani If you can do it in the next couple of days then go ahead and do them in this PR.

2023-06-13 06:26 UTC, sharifrezvani commented
@ssilvert I added the missing translations in my latest commit. thank you again for pointing them out

2023-06-13 15:01 UTC, jonkoops commented
@kasir-barati do you have time to review the latest changes on this PR?

2023-06-14 18:49 UTC, ssilvert commented
@sharifrezvani @kasir-barati @jonkoops I think this PR has lived long enough and a good effort has been made to get everything right.  

@kasir-barati if you want to review and make suggested changes, please go ahead.  Otherwise, I'm going to merge this as-is in 24 hours.

2023-06-15 09:15 UTC, jonkoops commented
> But if they are busy I can suggest some other users who might be interested in reviewing this PR as a native Farsi speaker

@sharifrezvani Yes, feel free to ping anyone you might know who's interested.

2023-06-15 18:15 UTC, kasir-barati requested changes
Hi dear reader

I just found some typoes and also inconsistencies.
And my apologize to @jonkoops @sharifrezvani for late reply :sweat:

2023-06-15 18:15 UTC, kasir-barati commented on themes/src/main/resources-community/theme/keycloak.v2/account/messages/messages_fa.properties
> +removeModalMessage=این عمل مجوز دسترسی اعطاشده فعلی برای {0} را حذف می‌کند. اگر می‌خواهید از این اپ دوباره استفاده کنید باید مجدد دسترسی را اعطا کنید.
```suggestion
removeModalMessage=با این کار مجوز دسترسی اعطا شده در حال حاضر برای {0} حذف خواهد شد. اگر می خواهید از این اپلیکیشن استفاده کنید، باید دوباره مجوز دسترسی بدهید.
```

Using the same translated message here as we had in this file: [js/apps/account-ui/public/locales/fa/translation.json](https://github.com/keycloak/keycloak/pull/19747/files#diff-572c71ad3aafccaceadd91c102a082fe63becb83163d878ee158dc11837c8b64)

2023-06-15 20:25 UTC, merged

2023-06-15 20:29 UTC, ssilvert commented
@kasir-barati I'm sorry.  I merged this without seeing your suggested changes.  If you feel they are important enough, please submit a new PR.