better default avatar if none is set
keycloak/keycloak pull request #19804
Opened 2023-04-19 11:10 UTC by edewit

fixes: #19681

2023-04-19 15:59 UTC, jonkoops commented
@ssilvert Normally I would back-port high impact issues. But since this is an experimental feature do we want to skip this one?

2023-04-19 16:02 UTC, jonkoops requested changes

2023-04-19 16:02 UTC, jonkoops commented on js/libs/keycloak-masthead/package.json
> +    "vite-plugin-svgr": "^2.4.0"
Do we really need to add a plugin to do SVGs? I'd rather we use one of the pre-defined components from PatternFly.

2023-04-19 17:27 UTC, ssilvert commented
> @ssilvert Normally I would back-port high impact issues. But since this is an experimental feature do we want to skip this one?

@jonkoops Right.  No need to backport.

2023-05-02 09:57 UTC, jonkoops approved these changes

2023-05-02 09:57 UTC, merged