Fix for Email settings erased after any change on realm settings
keycloak/keycloak pull request #19810
Opened 2023-04-19 14:32 UTC by kaustubh-rh

Added RealmRepresentation save instead of custom save function in Emailtab.tsx

Closes #19746

2023-04-19 15:55 UTC, jonkoops requested changes

2023-04-19 15:55 UTC, jonkoops commented on js/apps/admin-ui/src/realm-settings/EmailTab.tsx
> -      setRealm(savedRealm);
Looks like this is the only place `setRealm` was called, so it's no longer needed to keep it in a separate state. CAn you remove the `setState()` call that this originates from?

2023-05-15 15:16 UTC, jonkoops requested changes

2023-05-15 15:16 UTC, jonkoops commented on js/apps/admin-ui/src/realm-settings/EmailTab.tsx
>    realm: initialRealm,
Since this is the only place we're getting the realm from there is no longer a need to keep calling it `initialRealm`.
```suggestion
  realm,
```

2023-05-15 15:16 UTC, jonkoops commented on js/apps/admin-ui/src/realm-settings/EmailTab.tsx
> +  const [realm] = useState(initialRealm);
Since this value is always passed from higher up there is no need to keep it in a state any longer.
```suggestion
```

2023-05-15 15:16 UTC, jonkoops commented on js/apps/admin-ui/src/realm-settings/EmailTab.tsx
> +      if (savedRealm.smtpServer?.port === "") savedRealm.smtpServer.port = null;
Instead of handling this here, perhaps we can handle this in the `save` function of the `RealmSettingsTabs` component?

2023-05-25 11:52 UTC, jonkoops commented
@kaustubh-rh could you take a look at the review comments and address them?

2023-06-06 11:39 UTC, jonkoops commented
@kaustubh-rh are you still interested in landing this?

2023-06-07 08:20 UTC, kaustubh-rh commented
@jonkoops ack , will update it soon

2023-06-12 10:40 UTC, jonkoops commented
@kaustubh-rh are you still interested in landing this?

2023-06-12 10:41 UTC, jonkoops commented
@kaustubh-rh can you update the PR? We don't like keeping them open for extended periods of time for team process reasons. If you don't have time to work on this now we can close the PR and a new one can be submitted later.

2023-06-13 01:36 UTC, closed without merging