Update documentation on user storage provider in Quarkus
keycloak/keycloak pull request #19898
Opened 2023-04-24 10:25 UTC by martin-kanis

Closes #17394

2023-05-04 05:58 UTC, vramik approved these changes, later dismissed
Thank you @martin-kanis!

2023-05-05 09:30 UTC, andymunro commented on docs/documentation/server_development/topics/user-storage/configuration.adoc
> +In the `validateConfiguration()` method we get the configuration variable from the `ComponentModel` and we check to see if that file exists on disk.
```suggestion
The `validateConfiguration()` method provides the configuration variable from the `ComponentModel` to verify if that file exists on disk.
```

2023-05-05 09:37 UTC, andymunro commented on docs/documentation/server_development/topics/user-storage/configuration.adoc
> +The `${jboss.server.config.dir}` string corresponds to the `conf/` directory of our server and is really useful for this example.
```suggestion
Notice that the use of the `org.keycloak.common.util.EnvUtil.replace()` method. With this method any string that includes`${}` will replace that value with a system property value.
The `${jboss.server.config.dir}` string corresponds to the `conf/` directory of our server and is really useful for this example.
```

2023-05-05 09:42 UTC, andymunro commented on docs/documentation/server_development/topics/user-storage/registration-query.adoc
> +The method iterates over the key set of the property file, delegating to `getUserByUsername()` to load a user.
```suggestion
The first declaration of `searchForUserStream()` takes a `String` parameter. In this example, the parameter represents a username that you want to search by. This string can be a substring, which explains the choice of the `String.contains()`
method when doing the search. Notice the use of `*` to indicate to request a list all users.
The method iterates over the key set of the property file, delegating to `getUserByUsername()` to load a user.
```

2023-05-05 09:47 UTC, andymunro commented on docs/documentation/server_development/topics/user-storage/registration-query.adoc
> +in which case we return all users. We delegate to `searchForUserStream(realm, search, firstResult, maxResults)` for this.
```suggestion
Only usernames are stored, so the search is based only on usernames except when the `Map` parameter does not contain the `username` attribute. In this case, all users are returned. In that situation,  use `searchForUserStream(realm, search, firstResult, maxResults)` .
```

2023-05-05 09:47 UTC, andymunro commented on docs/documentation/server_development/topics/user-storage/registration-query.adoc
> +We do not store groups or attributes, so the other methods return an empty stream.
```suggestion
Groups or attributes are not stored, so the other methods return an empty stream.
```

2023-05-05 09:48 UTC, andymunro requested changes
@mhajas Just a few suggestions. Thanks.

2023-05-09 08:48 UTC, martin-kanis commented
I updated the PR according Andy's suggestions. @vramik @andymunro  Can you please re-review?

2023-05-15 13:25 UTC, andymunro approved these changes

2023-05-16 09:02 UTC, vramik approved these changes

2023-05-16 09:57 UTC, mhajas approved these changes
Approving per @vramik 's and @andymunro 's approvals

2023-05-16 09:57 UTC, merged