ChineseLocalization
keycloak/keycloak pull request #19927
Opened 2023-04-25 04:16 UTC by xianli123

As a Chinese native speaker, I reviewed all Chinese localization files and optimized the wordings. This branch includes the original localization and some updates.

2023-04-25 10:27 UTC, jonkoops commented
@xianli123 do we have another native mandarin speaker that could review this change?

2023-04-25 11:29 UTC, xianli123 commented
Hi @jonkoops I can ask our UXD team members if anyone has time to help check it. Once all things are done, I will let you know.

2023-04-26 07:48 UTC, xianli123 commented on js/apps/admin-ui/public/resources/zh-CN/authentication-help.json
> +  "topLevelFlowType": "流程有什么样的类型？“客户端”类型用于客户端（应用程序）的认证，而通用的类型是用于用户和其他的认证",
```suggestion
  "topLevelFlowType": "顶层流程有什么样的类型？“客户端”类型用于客户端（应用程序）的认证，而通用的类型是用于用户和其他的认证",
```

2023-05-10 08:24 UTC, edewit approved these changes, later dismissed

2023-05-10 08:41 UTC, xianli123 commented
@edewit Thanks for approving it. I have invited Haley to help review the translations and wording. Once all things are done, I will let you know.

2023-05-25 11:53 UTC, jonkoops commented
@xianli123 any progress on this PR?

2023-05-25 13:31 UTC, xianli123 commented
Hi @jonkoops I invited Haley to help with the review. Today, we had a meeting and talked about this pr. She will finish reviewing it as soon as possible (it could be by the end of next week). Once all things are done, I will let you know. Thanks.

2023-05-31 03:32 UTC, xianli123 commented on js/apps/admin-ui/public/resources/zh-CN/authentication-help.json
> +  "authDefaultActionTooltip": "如果启用，任何新用户都将获得分配给它的此项必需操作。",
```suggestion
  "authDefaultActionTooltip": "如果启用，此项操作对于任何新用户都将是必需的操作。",
```

2023-05-31 08:49 UTC, jonkoops commented
@xianli123 could you do a rebase of this branch on `main`? It seems some conflicts have started to appear.

2023-05-31 14:11 UTC, jonkoops commented
@xianli123 what I mean is that new changes have landed on the `main` branch, that are in conflict with the changes you have here. So in that case you will have to get the latest from `main` and resolve the conflicts. Probably the easiest way to do this is to use the [GitHub desktop app](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/keeping-your-local-repository-in-sync-with-github/syncing-your-branch-in-github-desktop#rebasing-your-project-branch-onto-another-branch).

Feel free to let me know if you need some help, we can hop on a call together.

2023-06-01 04:40 UTC, xianli123 commented
@jonkoops I see. I will try to solve the conflict. If there is any problem, I will ask for your help. Thanks.🙏

2023-06-01 08:00 UTC, yih-wang requested changes

2023-06-01 08:00 UTC, yih-wang commented on js/apps/admin-ui/public/resources/zh-CN/realm-settings.json
> +  "requiredFor": "被应用于",
```suggestion
  "requiredFor": "针对何人为必填项",
```

2023-06-01 08:00 UTC, yih-wang commented on js/apps/admin-ui/public/resources/zh-CN/realm-settings.json
> +  "validatorDeletedSuccess": "用户用户资料配置已保存。",
```suggestion
  "validatorDeletedSuccess": "用户资料配置已保存。",
```

2023-06-01 08:00 UTC, yih-wang commented on js/apps/admin-ui/public/resources/zh-CN/realm-settings.json
> +  "scopesAsRequested": "请求范围",
```suggestion
  "scopesAsRequested": "在此范围内生效",
```

2023-06-01 08:00 UTC, yih-wang commented on js/apps/admin-ui/public/resources/zh-CN/realm-settings.json
> +  "eventType": "被保存事件的类型",
```suggestion
  "eventType": "被保存的事件类型",
```

2023-06-01 08:00 UTC, yih-wang commented on js/apps/admin-ui/public/resources/zh-CN/realm-settings.json
> +      "name": "模拟错误",
```suggestion
      "name": "角色扮演错误",
```

2023-06-01 08:00 UTC, yih-wang commented on js/apps/admin-ui/public/resources/zh-CN/realm-settings.json
> +      "name": "模拟",
```suggestion
      "name": "角色扮演",
```

2023-06-01 08:00 UTC, yih-wang commented on js/apps/admin-ui/public/resources/zh-CN/realm-settings.json
> +      "description": "模拟"
```suggestion
      "description": "角色扮演"
```

2023-06-01 08:00 UTC, yih-wang commented on js/apps/admin-ui/public/resources/zh-CN/realm-settings.json
> +      "name": "客户发起的账户关联",
```suggestion
      "name": "客户端发起的账号关联",
```

2023-06-01 08:00 UTC, yih-wang commented on js/apps/admin-ui/public/resources/zh-CN/realm-settings.json
> +      "description": "客户发起的账户链接"
```suggestion
      "description": "客户端发起的账号关联"
```

2023-06-01 08:00 UTC, yih-wang commented on js/apps/admin-ui/public/resources/zh-CN/realm-settings.json
> +      "name": "身份提供者链接账户",
```suggestion
      "name": "身份提供商关联账号",
```

2023-06-01 08:00 UTC, yih-wang commented on js/apps/admin-ui/public/resources/zh-CN/realm-settings.json
> +      "description": "身份提供者链接账户"
```suggestion
      "description": "身份提供商关联账号"
```

2023-06-01 08:00 UTC, yih-wang commented on js/apps/admin-ui/public/resources/zh-CN/realm-settings.json
> +      "description": "身份供应者链接账号错误"
```suggestion
      "description": "身份提供商关联账号错误"
```

2023-06-01 08:00 UTC, yih-wang commented on js/apps/admin-ui/public/resources/zh-CN/realm-settings.json
> +      "description": "注销错误"
```suggestion
      "description": "登出错误"
```

2023-06-01 08:00 UTC, yih-wang commented on js/apps/admin-ui/public/resources/zh-CN/realm-settings.json
> +      "name": "Oauth2设备代码令牌",
```suggestion
      "name": "Oauth2设备用于交换令牌的代码",
```

2023-06-01 08:00 UTC, yih-wang commented on js/apps/admin-ui/public/resources/zh-CN/realm-settings.json
> +      "name": "Oauth2设备代码令牌错误",
```suggestion
      "name": "Oauth2设备用于交换令牌的代码错误",
```

2023-06-01 08:00 UTC, yih-wang commented on js/apps/admin-ui/public/resources/zh-CN/realm-settings.json
> +      "description": "Oauth2设备代码令牌错误"
```suggestion
      "description": "Oauth2设备用于交换令牌的代码错误"
```

2023-06-01 08:00 UTC, yih-wang commented on js/apps/admin-ui/public/resources/zh-CN/realm-settings.json
> +      "name": "Oauth2设备验证用户密码错误",
```suggestion
      "name": "Oauth2设备验证用户代码错误",
```

2023-06-01 08:00 UTC, yih-wang commented on js/apps/admin-ui/public/resources/zh-CN/realm-settings.json
> +  "importOverwritten_zero": "没有记录被覆盖。",
```suggestion
  "importOverwritten_zero": "没有记录被覆写。",
```

2023-06-02 05:26 UTC, xianli123 commented on js/apps/admin-ui/public/resources/zh-CN/client-scopes-help.json
> +  "displayOnConsentScreen": "如果启用，并且此客户端作用域被添加到需要许可的某些客户端，则“许可页面的显示文本”指定的文本将显示在许可申请的页面上。如果禁用，此客户端作用域将不会显示在许可申请的页面上",
```suggestion
  "displayOnConsentScreen": "如果启用，并且此客户端作用域被添加到需要许可的某些客户端，则“许可页面的展示文本”指定的文本将展示在许可申请的页面上。如果禁用，此客户端作用域将不会展示在许可申请的页面上",
```

2023-06-02 07:51 UTC, xianli123 commented on js/apps/admin-ui/public/resources/zh-CN/realm-settings.json
> +  "noDefaultGroupsInstructions": "默认组允许您在整个<1>身份代理</1>过程中创建或导入任何新用户时自动分配组成员。添加默认组以开始使用。",
```suggestion
  "noDefaultGroupsInstructions": "设置默认组将允许您在<1>identity brokering</1>过程中创建或导入新用户时自动分配群组。添加默认组以开始使用这一功能。",
```

2023-06-02 09:02 UTC, closed without merging

2023-06-02 09:13 UTC, xianli123 commented
Hi @jonkoops @ssilvert I closed this pr due to some conflicts and pull a new PR https://github.com/keycloak/keycloak/pull/20740. The main files have been reviewed by Haley and I updated them according to her suggestions. Please take a look and merge it if there is no error. Thanks!