New messages are added in Spanish
keycloak/keycloak pull request #19956
Opened 2023-04-25 23:03 UTC by jorozcof

- sessionLimitExceeded=Hay demasiadas sesiones.
- federatedIdentityExistsMessage=El usuario con {0} {1} ya existe. Inicie sesi\u00F3n en la administraci\u00F3n de cuentas para vincular la cuenta. 
- federatedIdentityUnavailableMessage=El usuario {0} autenticado con el proveedor de identidad {1} no existe. P\u00F3ngase en contacto con su administrador. 
- identityProviderInvalidResponseMessage=Respuesta no v\u00E1lida del proveedor de identidad.
- identityProviderMissingStateMessage=Falta el par\u00E1metro de estado en respuesta del proveedor de identidad.
- alreadyLoggedIn=Ya se ha autentificado.
- identity-provider-redirector=Con\u00E9ctese con otro proveedor de identidad 
- identity-provider-login-label=O inicia sesi\u00F3n con 
- idp-email-verification-display-name=Verificacion de email 
- idp-email-verification-help-text=Vincula tu cuenta validando tu correo electr\u00F3nico. 
- idp-username-password-form-display-name=Usuario y contrase\u00F1a 
- idp-username-password-form-help-text=Vincula tu cuenta iniciando sesi\u00F3n.

- access-denied=Acceso denegado

- logoutConfirmTitle=Saliendo de tu cuenta
- logoutConfirmHeader=¿Quieres cerrar sesi\u00F3n?
- doLogout=Cerrar sesi\u00F3n

#19945

2023-04-26 09:15 UTC, rmartinc requested changes
Thanks for the PR  @jorozcof!

Just some minor comments because the messages mix second and third person, better use third person in all of them.

2023-04-26 15:39 UTC, jorozcof commented on themes/src/main/resources-community/theme/base/login/messages/messages_es.properties
> +identity-provider-redirector=Con\u00E9ctese con otro proveedor de identidad
Yes, It sounds weird. I think is better `Inicie sesi\u00F3n con otro proveedor de identidad`. What do you thing @rmartinc ?

2023-04-26 16:06 UTC, rmartinc commented on themes/src/main/resources-community/theme/base/login/messages/messages_es.properties
> +identity-provider-redirector=Con\u00E9ctese con otro proveedor de identidad
Yep, it sounds good to me.

2023-04-27 07:09 UTC, rmartinc approved these changes
Thanks @jorozcof! LGTM.

2023-04-27 14:28 UTC, rmartinc commented
Yes, no problem, you can add them in this PR. I'm going to set it to `request changes` to not merge it by mistake.

2023-04-27 14:28 UTC, rmartinc requested changes
@jorozcof wants to add some more missing messages in Spanish.

2023-04-27 18:28 UTC, jorozcof commented
> @jorozcof wants to add some more missing messages in Spanish.

@rmartinc Yes, I added new messages in Spanish. If you like, you can review in my last commit.

2023-05-03 06:36 UTC, rmartinc approved these changes
Thanks @jorozcof ! LGTM!

2023-05-03 08:23 UTC, mposolda approved these changes
@jorozcof @rmartinc Thanks for the PR and review! Merging based on @rmartinc review

2023-05-03 08:23 UTC, merged