Update auth.ts
keycloak/keycloak pull request #20000
Opened 2023-04-27 14:51 UTC by hmica

Correct getToken error

This fix a regression on migration from Axios To FetchAPI Credential header must be encoded not decoded.

This fix #19879

2023-04-27 16:07 UTC, jonkoops requested changes
Perhaps it would be good to add some tests for this as well to prevent regressions in the future.

2023-04-27 16:07 UTC, jonkoops commented on js/libs/keycloak-admin-client/src/utils/auth.ts
> +      "Basic " + btoa(credentials.clientId + ":" + credentials.clientSecret)
Can we use a template literal here?
```suggestion
      `Basic ${btoa(`${credentials.clientId}:${credentials.clientSecret}`)`
```

2023-05-08 08:21 UTC, hmica commented on js/libs/keycloak-admin-client/src/utils/auth.ts
> +      "Basic " + btoa(credentials.clientId + ":" + credentials.clientSecret)
yes, done !

2023-05-08 08:24 UTC, hmica commented
Hi, I agree that's a good idea to have more test but I, not familiar with the project architecture, I try to run current test but they all failled, I suppose I need to have a Keycloak instance running.

2023-05-09 10:29 UTC, jonkoops requested changes

2023-05-09 10:29 UTC, jonkoops commented on js/libs/keycloak-admin-client/src/utils/auth.ts
> +    headers.set("Authorization", authHeaderValue);
I see no need to put this in a variable if it's only going to get used right after.
```suggestion
    headers.set("Authorization", `Basic ${btoa(`${credentials.clientId}:${credentials.clientSecret}`)}`);
```

2023-05-15 15:28 UTC, jonkoops approved these changes

2023-05-15 15:32 UTC, jonkoops commented
Thanks for this @hmica, let's land these changes as they are. I've created #20368 to write the tests in the future.

2023-05-15 15:48 UTC, jonkoops requested changes
Looks like there are some linting issues that need to be resolved.

2023-05-15 16:29 UTC, jonkoops approved these changes, later dismissed

2023-05-16 09:35 UTC, jonkoops approved these changes

2023-05-16 11:18 UTC, merged