Update to Quarkus 3.0.1.Final
keycloak/keycloak pull request #20011
Opened 2023-04-27 20:00 UTC by abstractj

Closes #20010
Closes #19080
Closes #17476
Closes #19286
Closes #17557
Closes #17556
Closes #17555
Closes #17475
Closes #15879
Closes #15878

2023-04-28 07:13 UTC, vmuzikar requested changes
@abstractj Thanks, added one comment.

2023-04-28 07:13 UTC, vmuzikar commented on operator/pom.xml
> +        <quarkus.version>3.0.1.Final</quarkus.version>
Operator SDK 6.0.1 [uses](https://github.com/quarkiverse/quarkus-operator-sdk/blob/6.0.1/pom.xml#L15) Quarkus 3.0.0.  This property is not overriding the Quarkus version that SDK uses. It is just for alignment of other dependencies so it needs to match whatever the SDK uses.
```suggestion
        <quarkus.version>3.0.0.Final</quarkus.version>
```

2023-04-28 11:49 UTC, mabartos approved these changes, later dismissed

2023-04-28 13:39 UTC, vmuzikar reviewed
@abstractj Thanks, LGTM. Could you please rebase?

2023-04-28 14:40 UTC, vmuzikar approved these changes, later dismissed
@abstractj Thanks, LGTM (provided tests will pass).

2023-04-28 16:43 UTC, abstractj commented
It seems that model tests are broken due to the updates to Infinispan. @keycloak/store I'd appreciate your input on it.

2023-04-28 17:53 UTC, ahus1 commented
@abstractj - I had a short look at it, and was able to reproduce the exception in my IDE. 

I had a look and as I'm not too familiar with the code I'm hesitant to suggest a fix. 

The exception is gone once the two Infinispan dependencies are downgraded, so I suggest to upgrade the Infinispan dependency in a separate issue/PR.

2023-04-28 18:37 UTC, abstractj commented
Thank you @ahus1. Incorporated your suggestion to the changes.

2023-04-28 19:23 UTC, ahus1 approved these changes, later dismissed
Approving the downgrade of Infinispan assuming the build is now green.

2023-05-02 08:13 UTC, vmuzikar approved these changes

2023-05-02 08:13 UTC, merged