Execute attribute mappers on client initiated account linking (#11195)
keycloak/keycloak pull request #20248
Opened 2023-05-09 13:10 UTC by toddkazakov

Fixes #11195

2023-05-09 13:54 UTC, thomasdarimont commented
Thanks for your contribution! I think this is indeed useful. Just had a small note about the imports that needs fixing.

2023-05-09 14:15 UTC, thomasdarimont requested changes

2023-05-09 14:36 UTC, toddkazakov commented on testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/AccountLinkTest.java
> +import org.keycloak.models.*;
Thanks! Fixed.

2023-05-09 14:38 UTC, toddkazakov commented
Unfortunately, I'm unable to run the test suite locally, due to the jakarta migration. For some reason maven tries to use `keycloak-admin-client-jee` instead of `keycloak-admin-client` in the integration test suite.

2023-05-31 10:32 UTC, andre-nascimento-rh reviewed
I hope to test it in my Env ASAP, but it LGTM.

Good Job, @toddkazakov .

2023-05-31 14:50 UTC, toddkazakov commented
The added test doesn't work after rebase because of #15199. I'm working on moving it in a different spot, because the account linking mappers are not triggered with the refactored logic.

2023-06-02 09:20 UTC, toddkazakov commented
@andre-nascimento-rh tests should be ok now

2023-06-07 08:55 UTC, andre-nascimento-rh reviewed
@toddkazakov , I didn't have time to test it locally yet. Sorry. But from the coding perspective, it LGTM.

Let's see If all tests pass in GHA.

Thanks.

2023-06-07 12:09 UTC, pedroigor commented on services/src/main/java/org/keycloak/services/resources/IdentityBrokerService.java
> +        updateFederatedIdentity(context, federatedUser);
@toddkazakov I think calling this method here will cause errors when linking existing accounts. Could you please try to add the call at https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/services/resources/IdentityBrokerService.java#L942?

2023-06-12 23:38 UTC, pedroigor commented
@toddkazakov Sorry for the back and forth ...

I just realized that the test is not really covering the change I suggested. It is only passing because right after the first attempt to link the account, the test tries again to link the account and only at this time the attributes are set, as expected.

I created this branch with some minor updates. See https://github.com/pedroigor/keycloak/tree/issue-11195. 

I also found a difference in behavior when using legacy and new stores. This code returns null when using the new store (chm) but using the current store resolves the model instance. See https://github.com/pedroigor/keycloak/commit/e7b2041b2d0bb1231286114b555f978fa8bb1767#diff-e44efb607cb8cb833e99677c01e7fc10d67afc6ee54ce4faf06a01f5acaf50e7R953.

@keycloak/store-maintainers  Is this difference expected? Looks like changes made during a transaction are not immediately visible until it is committed.

2023-06-13 10:37 UTC, toddkazakov commented
@pedroigor no problem, makes sense. In the tests it's probably better to unlink the account after the first test is successful. 

How do you want to proceed with this one? Seems like the new store not seeing the uncommitted changes is a no go.

2023-06-13 11:43 UTC, pedroigor commented
@toddkazakov Thanks. I'm looking at the new store-related changes. I'll ping you back once my branch is updated.

2023-06-13 20:13 UTC, pedroigor commented
@toddkazakov Do you mind looking at https://github.com/keycloak/keycloak/pull/20965?

2023-06-15 12:28 UTC, toddkazakov commented
@pedroigor looks ok to me. Were there any changes related to the new store?

2023-06-19 14:24 UTC, pedroigor commented
@toddkazakov TBH, I'm not sure. I could not reproduce the behavior anymore.

Do you mind updating your PR (sorry, again) based on https://github.com/keycloak/keycloak/pull/20965?

2023-07-03 22:25 UTC, pedroigor commented
Fixed by https://github.com/keycloak/keycloak/pull/20965

2023-07-03 22:25 UTC, closed without merging