Fix LDAP user synchronization documentation
keycloak/keycloak pull request #20399
Opened 2023-05-16 18:21 UTC by sguilhen

Closes #16833

2023-05-17 09:56 UTC, abstractj approved these changes, later dismissed

2023-05-17 10:26 UTC, vramik requested changes
Thanks @sguilhen! 

There is also https://www.keycloak.org/docs/21.1.1/server_admin/index.html#proc-searching-user_server_administration_guide which needs to be changed.

We should also include there a description how the search behaves and what is a usable syntax there:

- `"value"` - exact search -> transformed into ... = 'value'
- `*value*` - infix search -> transformed into ... LIKE '%value%'
- `value*` and value - prefix search -> transformed into ... LIKE 'value%'

2023-05-26 16:59 UTC, vramik approved these changes
Thank you @sguilhen. LGTM

2023-05-30 11:36 UTC, mhajas approved these changes
Approving per @vramik 's approval

2023-05-30 11:36 UTC, merged