FAPI 2.0 security profile - supporting RFC 9207 OAuth 2.0 Authorization Server Issuer Identification
keycloak/keycloak pull request #20621
Opened 2023-05-29 00:01 UTC by tnorimat

Closes #20584

2023-05-29 11:54 UTC, pedroigor commented
@tnorimat The mix-up attack being mitigated by this implementation is basically an additional barrier to Keycloak clients, right? 

Most of the time, I see libraries integrating with Keycloak (including our adapters) validating the `iss` claim in both ID and our JWT Access tokens.

It looks more like a OAuth2-specific exploit, right? Is FAPI not forcing clients to use this parameter?

2023-05-29 17:43 UTC, mposolda commented
@pedroigor There is some interesting scenario described here https://datatracker.ietf.org/doc/html/draft-ietf-oauth-security-topics-19#section-4.4.1 .

@pedroigor @tnorimat I think that this is nice addition, but it will be likely still good to mention this in the "Upgrading guide" IMO. The OAuth2 mentions that client should ignore unknown parameters https://datatracker.ietf.org/doc/html/rfc6749#section-4.1.2 , however I still have some fear that people will start reporting bugs due their client adapters screaming about "Unknown parameter: iss" ;-) So will be good to have this documented at least. But apart from that, I am not seeing any reason why the parameter should not be included by default and I hope we don't need any additional configuration for that.

@pedroigor Can you think of any issue with including `iss` in the authorization response by default?

2023-05-30 04:11 UTC, tnorimat commented
@pedroigor @mposolda FAPI 2.0 requires this feature (#7 of [FAPI 2.0 spec](https://openid.bitbucket.io/fapi/fapi-2_0-security-profile.html#section-5.3.1.2)). The conformance test of FAPI 2.0 security profile checks this point, so we need this feature to pass the conformance test.

IMO, it is good to add iss parameter as default, and I agree with Marek's proposal for the documentation.
Of course, we add a settings of a client to determine whether iss parameter is added or not, but the number of settings increases.
It is difficult to realize this feature by Client policies because the current client policies cannot add iss parameter to a normal and error authorization response.

2023-05-30 06:07 UTC, tnorimat commented
@pedroigor @mposolda Some tests failed because an application using keycloak oidc adapter cannot strip iss parameter when it create redirect_uri parameter of a token request. I stripped iss parameter by [adapter codes of OAuthRequestAuthenticator](https://github.com/keycloak/keycloak/pull/20621/files#diff-f33a1c0a7187111ab3a15d98c6e068d4140579fc50d3cfabb402bda8b24f3eb2) and [ServerRequest](https://github.com/keycloak/keycloak/pull/20621/files#diff-db064681136ab6793c8c65df751b45eb474c43ea0d984b7957ca75e5c7945d3c). However, it seems that they did not work. If possible, could you give me some advices?

2023-05-31 09:18 UTC, tnorimat commented
@pedroigor @mposolda I do not know the reason why but erros happend by keycloak-adapter-core were resolved. I will investigate remaining errors in Base IT (5).

2023-05-31 12:47 UTC, pedroigor commented
@tnorimat @mposolda I don't see any issue. I was just curious if that affects OpenID Connect clients (not pure OAuth2 clients).

The fact you have the issuer there (and we are using JWT), makes this attack not really possible if your OIDC client (e.g.: quarkus-oidc, Elytron OIDC, or even our legacy adapters) is checking the `iss` from the ID Token.

Adding this change to the release notes makes a lot of sense ...

2023-05-31 15:10 UTC, mposolda commented
@pedroigor I think attack may be still possible even for OIDC clients.

If I understand correctly the scenario in https://datatracker.ietf.org/doc/html/draft-ietf-oauth-security-topics-19#section-4.4.1, the idea is that client receives AuthorizationResponse from "Honest AS", but then it sends the token request to "Attacker AS" (including `code` and `state` etc), which means that attacker will be able to use the `code` to obtain the tokens for "Honest AS". Per my understanding, the `iss` parameter in AuthorizationResponse is a hint for client, which AS to use. So since client see `iss` for "Honest AS", it won't try to send TokenRequest to "attacker AS".

2023-06-02 11:15 UTC, pedroigor commented
I think I'm starting to understand how OIDC is impacted after reading https://arxiv.org/abs/1704.08539 and https://arxiv.org/abs/1508.04324v2.

Thanks.

2023-06-12 10:43 UTC, jonkoops commented
@pedroigor @mposolda is this something we can land soon, are we blocked on anything specific?

2023-06-12 15:22 UTC, pedroigor approved these changes, later dismissed
Sorry, for the delay and noise :)

@tnorimat @mposolda LGTM.

2023-06-12 15:24 UTC, ghost reviewed
Unreported flaky test detected, please review

2023-06-13 08:53 UTC, mposolda commented
@tnorimat The PR looks good to me as well, but there are test failures. Maybe rebase on top of latest main can help, but not sure if that's sufficient...

2023-06-19 11:05 UTC, jonkoops approved these changes, later dismissed
Changes in Keycloak JS look good to me.

2023-06-19 11:06 UTC, jonkoops commented
@tnorimat could you give this PR a quick rebase, and possibly fix the tests if they still fail?

2023-06-24 01:16 UTC, tnorimat commented
@jonkoops @mposolda 
IMO, it might be better to have add one client configuration for enabling RFC 9207 "iss" parameter because
- A lot of integraiton tests failed because these tests expects that an authorization response does not include "iss" parameter. I am afraid that keycloak users also expect it for their application tests.
- When preparing [FAPI 2.0 security profile as defult](https://github.com/keycloak/keycloak/issues/21181), its profile's executor can enforce the client to RFC 9207 "iss" parameter.

Marek proposed the following options:

1. Add "iss" by some client policy executor. This means that it won't be added by default.
2. Add the "backward compatibility" switch to client similar to "Exclude session_state" parameter. We can just have "Exclude iss" parameter. This means that "iss" parameter would be added by default (similarly like "session_state"), but will be explicitly excluded just if disabled switch on the particular client.

I prefer the option 2, but IMO, it might be good that "iss" parameter would not be added by default because RFC 9207 "iss" parameter is optional. Therefore, it might be good that one client configuration parameter for adding "iss" field is added even I know its drawback that increases the number of client configuration. @mposolda WDYT?

2023-06-28 16:11 UTC, mposolda commented
@tnorimat TBH I would prefer to rename the switch to `Exclude Issuer from Authentication Response` . It will be good to be compatible with the switch `Exclude Session State from Authentication Response`, which is kind of similar thing (To me, it is a bit confusing to have inclusion for one of those and have exclusion for the other by default...). If there are any test failures (which AFAIK they were in the previous version of your PR), then maybe you can just disable the `iss` for particular clients in the particular tests, which is also a good prove that this works as expected :-)

Also there may be a need to update admin console as well and add the new switch to backwards compatibility switches.

Also it will be good to add the note to the upgrading guide similar to this https://www.keycloak.org/docs/latest/upgrading/index.html#added-session_state-parameter-to-openid-connect-authentication-response about this switch.

2023-06-29 00:51 UTC, tnorimat commented
@mposolda Thank you for the comments and suggestions. I will follow them and review the PR.

2023-06-29 06:01 UTC, mposolda commented
@tnorimat Thanks for the updates! Hopefully the failing tests are possible to solve by excluding `iss` or the other way...

For the upgrading guide, hopefully lots of the things can be (almost) copy-pasted from the similar post for "Exclude session_state" parameter from https://www.keycloak.org/docs/latest/upgrading/index.html#added-session_state-parameter-to-openid-connect-authentication-response

2023-06-29 06:34 UTC, tnorimat commented
@mposolda Thank you. I will fix failed CI tests and add migration codes (the current client's `exclude iss parameter` setting become ON from default OFF).

2023-06-29 06:45 UTC, tnorimat commented
@mposolda It seems that [the PR of `Exclude session_state parameter`](https://github.com/keycloak/keycloak/pull/4928) did not include the migration code (default `OFF` to `ON`). IMO, the PR also need not to do such migration. WDYT?
Also,  I will add documentaiton of migration guide the same as `Exclude session_state parameter`.

2023-06-29 06:51 UTC, mposolda commented
@tnorimat My vote is to have `Exclude Issuer from Authentication Response` to be OFF by default. Again - same behaviour like for session_state. Which means that `iss` parameter would be added by default. Administrator can disable `iss` explicitly for particular clients just if it causes the issues for him.

I don't see any issues regarding specifications? As you pointed before - RP should ignore unknown parameters in AuthorizationResponse if it doesn't understand them.

This means that we don't need to do any migration changes (As it is OFF by default for new as well as for existing clients).

2023-06-29 07:18 UTC, tnorimat commented
@mposolda Yes, I agree with you.

2023-06-30 00:26 UTC, tnorimat commented
@mposolda I revised the PR as you suggested. Could you check it? One CiI action failed (cypress/flake), but it seems that it is not relevant to the PR.

2023-06-30 07:46 UTC, mposolda reviewed
@tnorimat Thanks Takashi! I've added 2 minor comments inline.

@andymunro Could you please review the docs to this PR?

@pedroigor Does this OK to you? Is it fine to you to merge this before 22 release or do you prefer to wait after 22 release? For me, it's likely OK to do now (since we have backwards compatibility option), but I prefer to have 2nd opinion too.

2023-07-01 00:43 UTC, tnorimat commented on docs/documentation/upgrading/topics/keycloak/changes-22_0_0.adoc
> +RFC 9207 OAuth 2.0 Authorization Server Issuer Identification specification addes the parameter `iss` in the OAuth 2.0/OpenID Connect Authentication Response for realizing secure authorization respon
Yes, I will fix the typo.

2023-07-01 00:46 UTC, tnorimat commented on services/src/main/java/org/keycloak/protocol/oidc/OIDCLoginProtocol.java
> +                redirectUri.addParam(OAuth2Constants.ISSUER, clientSession.getNote(OIDCLoginProtocol.ISSUER));
Yes. I will fix the point.

2023-07-03 15:28 UTC, pedroigor commented
I'm not 100% convinced about the new setting but I see it can avoid headaches when upgrading.

2023-07-03 15:29 UTC, pedroigor approved these changes, later dismissed

2023-07-03 15:43 UTC, jonkoops submitted a review, later dismissed

2023-07-19 11:07 UTC, mposolda commented
@tnorimat The PR looks good to me, Thanks for all the updates!

I think that test failures are not related to this PR, so should be fine.

I have last comment related to docs: Is it possible to move the changes to file changes-23_0_0.adoc instead of changes-22_0_0.adoc? As Keycloak 22 is already released and we unfortunately did not manage to have this in time for 22. Maybe you will need to create the file changes-23_0_0.adoc and add it to changes.adoc.

@andymunro Could you please review the documentation part of this PR? See my previous comment for the migration, so you can ignore this in your review.

2023-07-20 02:14 UTC, tnorimat commented
@mposolda I added the file changes-23_0_0.adoc .

2023-07-20 08:09 UTC, mposolda submitted a review, later dismissed
@tnorimat Thanks! I am approving as this looks good to me.

I think we may have review of the documentation from @andymunro today. Also I hope that failing tests are not a regression of this PR, so I've re-triggered them.

2023-07-20 08:52 UTC, jonkoops requested changes
There are some linting issue for the UI code. You probably need to update the dependencies to fix them. Try running `pnpm i && pnpm --filter admin-ui run lint -- --fix` from the `js` directory.

2023-07-20 21:21 UTC, andymunro commented on docs/documentation/upgrading/topics/keycloak/changes-23_0_0.adoc
> +for the particular client in the {project_name} admin console, in client details in the section with `OpenID Connect Compatibility Modes`,
```suggestion
for the particular client in the {project_name} Admin Console, in client details in the section with `OpenID Connect Compatibility Modes`,
```

2023-07-20 21:24 UTC, andymunro requested changes
@tnorimat Just one change to request. Thanks.

2023-07-20 22:03 UTC, tnorimat commented on docs/documentation/upgrading/topics/keycloak/changes-23_0_0.adoc
> +for the particular client in the {project_name} admin console, in client details in the section with `OpenID Connect Compatibility Modes`,
Thank you. I fixed it.

2023-07-21 07:58 UTC, mposolda commented
@tnorimat Thanks! We should be good for docs now, so the only missing piece might be to fix the UI test failure. Maybe rebase helps (if you did not already?). Another possibility is to do what @jonkoops suggested in the comment above?

@jonkoops @tnorimat Also I don't know if it is relevant, but when I browse through the files https://github.com/keycloak/keycloak/pull/20621/files, then going bottom to the file OpenIDConnectCompatibilityModes.tsx and I see some message like:
```
 Check failure on line 73 in js/apps/admin-ui/src/clients/advanced/OpenIdConnectCompatibilityModes.tsx
GitHub Actions / Admin UI

Insert `,`
```
Could it be related to UI test failure?

2023-07-21 08:27 UTC, tnorimat commented
@mposolda @jonkoops I fixed the tsx file as Marek suggested.

2023-07-21 14:51 UTC, mposolda approved these changes
@tnorimat Seems it helped, UI tests are OK now. Thanks!

@jonkoops Is PR ok for you or is anything still missing from your point of view?

2023-07-22 14:39 UTC, jonkoops approved these changes
@mposolda this all looks good to me 👍

2023-07-24 07:11 UTC, mposolda commented
@jonkoops @andymunro @tnorimat Thanks for the reviews and for all the work on this!

2023-07-24 07:11 UTC, merged

2023-07-24 08:14 UTC, tnorimat commented
@mposolda Thank you. I will try to work on https://github.com/keycloak/keycloak/issues/21181 . Also, I will re-check whether the current keycloak can pass FAPI 2.0 Impl conformance test.