Deprecations
keycloak/keycloak pull request #20824
Opened 2023-06-06 17:29 UTC by vramik

2023-06-06 19:29 UTC, hmlnarik commented
I like the direction where this PR is going, and the removals make sense to me.

I'm +1 for including this for 22 since it simplifies the interfaces. Any thoughts, @mposolda @pedroigor @stianst ?

2023-06-08 11:43 UTC, mposolda commented
To me, it also looks good and definitely +1 to include in Keycloak 22. More legacy stuff removed, the better :-)

One quick though I've noticed: It seems that method `LegacySessionSupportProvider.userCache()` can be removed as well (at least it seems to not be used anywhere with this PR changes and I guess it it not supposed to be used directly by user's application?). But that's just a detail.

2023-06-09 09:25 UTC, vramik commented
> One quick though I've noticed: It seems that method `LegacySessionSupportProvider.userCache()` can be removed as well (at least it seems to not be used anywhere with this PR changes and I guess it it not supposed to be used directly by user's application?).

Thanks @mposolda for pointing this out. I've incorporated it into the PR.

2023-06-09 11:22 UTC, hmlnarik commented
@andymunro Could you please review the docs in this PR?

2023-06-09 11:58 UTC, andymunro commented on model/legacy/src/main/java/org/keycloak/storage/adapter/AbstractUserAdapterFederatedStorage.java
> +     * and therefore the parent interface can be used directly
```suggestion
     * @deprecated This interface is no longer necessary; collection-based methods were removed from the parent interface
     * and therefore the parent interface can be used directly
```

2023-06-09 11:59 UTC, andymunro commented on model/legacy/src/main/java/org/keycloak/storage/federated/UserAttributeFederatedStorage.java
> +     * and therefore the parent interface can be used directly
```suggestion
     * @deprecated This interface is no longer necessary; collection-based methods were removed from the parent interface
     * and therefore the parent interface can be used directly
```

2023-06-09 11:59 UTC, andymunro commented on model/legacy/src/main/java/org/keycloak/storage/federated/UserBrokerLinkFederatedStorage.java
> +     * and therefore the parent interface can be used directly
```suggestion
     * @deprecated This interface is no longer necessary; collection-based methods were removed from the parent interface
     * and therefore the parent interface can be used directly
```

2023-06-09 12:00 UTC, andymunro commented on model/legacy/src/main/java/org/keycloak/storage/federated/UserFederatedStorageProvider.java
> +     * @deprecated This interface is no longer necessary, collection-based methods were removed from the parent interface
```suggestion
     * @deprecated This interface is no longer necessary; collection-based methods were removed from the parent interface
```

2023-06-09 12:00 UTC, andymunro commented on model/legacy/src/main/java/org/keycloak/storage/federated/UserFederatedUserCredentialStore.java
> +     * @deprecated This interface is no longer necessary, collection-based methods were removed from the parent interface
```suggestion
     * @deprecated This interface is no longer necessary; collection-based methods were removed from the parent interface
```

2023-06-09 12:00 UTC, andymunro commented on model/legacy/src/main/java/org/keycloak/storage/federated/UserRequiredActionsFederatedStorage.java
> +     * @deprecated This interface is no longer necessary, collection-based methods were removed from the parent interface
```suggestion
     * @deprecated This interface is no longer necessary; collection-based methods were removed from the parent interface
```

2023-06-09 12:01 UTC, andymunro commented on model/legacy/src/main/java/org/keycloak/storage/federated/UserRoleMappingsFederatedStorage.java
> +     * @deprecated This interface is no longer necessary, collection-based methods were removed from the parent interface
```suggestion
     * @deprecated This interface is no longer necessary; collection-based methods were removed from the parent interface
```

2023-06-09 12:11 UTC, andymunro requested changes
Thanks, @hmlnarik. Just a few changes.

2023-06-09 15:06 UTC, hmlnarik submitted a review, later dismissed
Thank you for the PR!

2023-06-09 15:11 UTC, hmlnarik approved these changes

2023-06-09 17:11 UTC, merged