Update securing_applications guide for latest adapter changes (community)
keycloak/keycloak pull request #20995
Opened 2023-06-14 08:44 UTC by mposolda

closes #20994

- Added note that our OIDC java adapters are deprecated and applicable only to JEE
- Removed note from our OIDC JBoss adapter docs that "We test and support latest Wildfly version" as this is not accurate anymore. Instead added that people are encouraged to use elytron-oidc-client
- Some updates to SAML docs for Jakarta
- Some deprecation of SAML adapters (Jetty, Tomcat) and note that we don't support mod_auth_mellon.

2023-06-14 11:19 UTC, pedroigor reviewed
@mposolda Thanks.

2023-06-14 11:29 UTC, mposolda commented
@pedroigor Applied your suggestion. Thanks!

2023-06-14 21:46 UTC, andymunro commented on docs/documentation/securing_apps/topics/oidc/java/jboss-adapter.adoc
> +WARNING: We do not regularly test and maintain WildFly/EAP adapters. They may work only with WildFly version of 23 or earlier or with JBoss EAP 7. Also note
```suggestion
WARNING: We do not regularly test and maintain WildFly/EAP adapters. They may work only with WildFly version 23 or earlier or with JBoss EAP 7. Also note
```

2023-06-14 21:48 UTC, andymunro commented on docs/documentation/securing_apps/topics/oidc/java/jboss-adapter.adoc
> +secure your applications. It has very similar configuration to Keycloak Java adapters and migrating your applications to it should be smooth.
```suggestion
that they may work only with JEE applications, but not with Jakarta applications. We recommend that you switch to Elytron OIDC Java adapter to
secure your applications. This adapter has a similar configuration to Keycloak Java adapters and migrating your applications to it should be smooth.
```

2023-06-14 21:48 UTC, andymunro commented on docs/documentation/securing_apps/topics/saml/java/jetty-adapter.adoc
> +WARNING: {project_name} Jetty SAML adapter is deprecated. It is recommended to use other client adapter if possible.
```suggestion
WARNING: The {project_name} Jetty SAML adapter is deprecated. We recommend that you use another client adapter if possible.
```

2023-06-14 21:49 UTC, andymunro commented on docs/documentation/securing_apps/topics/saml/java/tomcat-adapter.adoc
> +WARNING: {project_name} Tomcat SAML adapter is deprecated. It is recommended to use other client adapter if possible.
```suggestion
WARNING: The {project_name} Tomcat SAML adapter is deprecated. We recommend that you use another client adapter if possible.
```

2023-06-14 21:50 UTC, andymunro commented on docs/documentation/securing_apps/topics/saml/mod-auth-mellon.adoc
> +It is recommended to stick to official mod_auth_mellon documentation for more details.
```suggestion
WARNING: {project_name} does not provide any official support to mod_auth_mellon. The instructions below are best-effort and may not be up-to-date.
We recommend that you stick to official mod_auth_mellon documentation for more details.
```

2023-06-14 21:51 UTC, andymunro requested changes
Looks good, @mposolda. A few changes to suggest.

2023-06-20 07:12 UTC, mposolda commented
@andymunro Applied your changes. Thanks!

2023-06-20 07:21 UTC, merged