ResourceType lost during cloning
keycloak/keycloak pull request #21004
Opened 2023-06-14 12:39 UTC by vramik

Closes #20947

2023-06-14 15:14 UTC, ahus1 requested changes
Hi @vramik - see PR https://github.com/vramik/keycloak/pull/3 for coding suggestion which clones the nested event. There's also a comment about an assumption. I looked at the code and I assume this is a valid assumption - please double-check. Thanks!

2023-06-15 11:15 UTC, ahus1 approved these changes
LGTM. As I contribute part of the change, it might be good for another person (maybe the maintainer merging this) to have another look. 

IMHO the two commits of this PR should be squashed, as they are about the same issue, and the second commit doesn't contain the issue number, but the PR number of a different repository, which would be confusing for future readers.

2023-06-15 17:34 UTC, vramik commented
Thank you @ahus1! Squashed commits and rebased. 

@hmlnarik could you also please take a look once you have a chance? Thank you

2023-06-23 07:31 UTC, hmlnarik approved these changes

2023-06-23 07:31 UTC, merged