TestLdapConnectionResource: give usefull feedback in UI on what faile…
keycloak/keycloak pull request #21013
Opened 2023-06-14 19:03 UTC by dinutine

…d in LDAP connection/authentication/sync users

Currently, for all errors, a meaningless message "LDAP test error" or "unknown_error" is returned by the API.
To give some usefull feedback to the user, by creating an error message based on the exception being thrown

Closes: #15434

2023-06-15 09:23 UTC, jonkoops approved these changes, later dismissed
Can't say anything about the Java code, but the changes on the font-end look good to me.

2023-06-15 10:20 UTC, hmlnarik requested changes
Thank you for the PR. It is a useful PR but the Java code needs polishing.

Due to a change in `KeycloakErrorHandler`, it can now leak internals of server-side information even to unauthorized users, as this handler can be used for all requests. For example, instead of `unknown_error`, in the login screen it could happen that `CommunicationError` would be displayed which can be seen as CWE-1230 (Exposure of Sensitive Information Through Metadata). The lack of verbosity there is intentional.

Translating the exception to error should thus be done in the testing endpoint which is only available in the admin UI.

2023-06-15 10:20 UTC, hmlnarik commented on services/src/main/java/org/keycloak/services/error/KeycloakErrorHandler.java
> +        String errorMsg = "UnknownError";
This change needs reverting. The `unknown_error` is a constant which must not be changed.

2023-06-16 08:58 UTC, hmlnarik reviewed
LGTM, just one minor nit and the Java part is good to go.

2023-06-16 08:58 UTC, hmlnarik commented on model/legacy-services/src/main/java/org/keycloak/services/resources/admin/UserStorageProviderResource.java
> +            }
```suggestion
                return getErrorCode(throwable.getCause());
```

2023-06-23 08:04 UTC, hmlnarik approved these changes, later dismissed

2023-06-23 08:08 UTC, hmlnarik commented
The java code LGTM, thank you!
There are test failures in the Admin UI test, could you please check?

2023-06-30 14:33 UTC, jonkoops approved these changes

2023-06-30 14:34 UTC, jonkoops commented
@hmlnarik if everything looks good, can you re-approve the PR? I think we can get this merged in.

2023-07-01 17:45 UTC, hmlnarik approved these changes

2023-07-01 17:45 UTC, merged