Incorrect Signature algorithms presented by Client Authenticator
keycloak/keycloak pull request #21101
Opened 2023-06-20 10:22 UTC by mposolda

closes #15853

2023-06-20 10:31 UTC, jonkoops requested changes

2023-06-20 10:31 UTC, jonkoops commented on js/apps/admin-ui/src/clients/credentials/SignedJWT.tsx
> +    : (useServerInfo().cryptoInfo?.clientSignatureSymmetricAlgorithms ?? []);
Although this does not result in errors, hooks [should not be called conditionally](https://react.dev/warnings/invalid-hook-call-warning). Instead you can store the value in side of a variable outside of these conditions:

```suggestion
  const { cryptoInfo } = useServerInfo();
  const providers =
    clientAuthenticatorType === "client-jwt"
      ? cryptoInfo?.clientSignatureAsymmetricAlgorithms ?? []
      : cryptoInfo?.clientSignatureSymmetricAlgorithms ?? [];`
``

2023-06-20 12:39 UTC, jonkoops submitted a review, later dismissed
Changes on the font-end side of things look good.

2023-06-20 23:55 UTC, tnorimat approved these changes
LGTM

2023-06-20 23:56 UTC, tnorimat commented
@mposolda As one optional comment,  whether are UI tests needed or not.

2023-06-21 06:55 UTC, mposolda commented
@jonkoops @tnorimat Thanks!

2023-06-21 06:55 UTC, mposolda commented
> @mposolda As one optional comment, whether are UI tests needed or not.

@tnorimat Thanks for the comment. It seems that `ServerInfoTest` is ok based on the approval from Jon from our UI team.

2023-06-21 06:55 UTC, merged