Improve French translation
keycloak/keycloak pull request #21174
Opened 2023-06-23 13:24 UTC by reda-alaoui

2023-06-23 15:32 UTC, jonkoops commented
@reda-alaoui could you get another French native speaker to review your PR?

2023-06-23 15:33 UTC, reda-alaoui commented
@jonkoops One of my colleague can do that if you want. I don't where to find one otherwise.

2023-06-23 15:38 UTC, jonkoops commented
That is fine, it always good to have another set of eyes on this. If your colleague can review it that would be great!

2023-06-23 15:52 UTC, roman-garcia requested changes

2023-06-23 15:52 UTC, roman-garcia commented on themes/src/main/resources-community/theme/base/login/messages/messages_fr.properties
> +webauthn-passwordless-help-text=Utilisez votre cl\u00e9 de s\u00e9curit\u00e9 pour vous connecter sans mots de passe.
sans mots de passe => sans mot de passe

2023-06-23 15:52 UTC, roman-garcia commented on themes/src/main/resources-community/theme/base/login/messages/messages_fr.properties
> +webauthn-error-auth-verification=Le r\u00e9sultat de l''authentification produit par la cl\u00e9 de s\u00e9curit\u00e9 est invalide.<br/> {0}
l''authentication produit => l''authentication produite

2023-06-23 16:04 UTC, roman-garcia approved these changes

2023-06-23 16:22 UTC, jonkoops approved these changes

2023-06-26 17:07 UTC, reda-alaoui commented
@jonkoops are we waiting for another reviewer?

2023-06-28 12:17 UTC, jonkoops commented
Yes, we need a maintainer to approve this. I'll see if one is available to do so.

2023-06-28 12:22 UTC, ssilvert approved these changes

2023-06-28 12:22 UTC, merged