prevent IDP creation from having an alias of empty string
keycloak/keycloak pull request #21193
Opened 2023-06-24 18:11 UTC by Scuilion

If you create an IDP with an empty string as an alias, it will prevent accessing that object since the API uses this field as a lookup. 

eg: https://github.com/keycloak/keycloak/blob/c02688473484bc6ee8185f613fa13c39dbbd7ea7/services/src/main/java/org/keycloak/services/resources/admin/IdentityProvidersResource.java#L209

2023-07-03 22:19 UTC, pedroigor reviewed
@Scuilion Thanks. Would you mind writing a test to https://github.com/keycloak/keycloak/blob/main/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/IdentityProviderTest.java.

2023-07-26 05:21 UTC, stianst approved these changes

2023-07-26 06:53 UTC, stianst requested changes
Failing tests

2023-09-06 18:06 UTC, pedroigor commented
Closing due to the lack of activity.

2023-09-06 18:06 UTC, closed without merging