widens status to be any type.
keycloak/keycloak pull request #21281
Opened 2023-06-28 10:04 UTC by shawkins

this is to avoid olm complaining about an incompatible schema during upgrade.  The jsonschema representation of AnyType isn't quite correct as it also includes a value property - this will be fixed in fabric8 6.8.  Regardless the important part is that it's simply marked as a field that preserves unknown.  Once the initial reconciliation is performed against a newer operator version, the stored version of the resources will be updated to strings.  A later version of the operator then will be free to change the representation to string and that will then pass the validation check performed by olm.

Relates to #13074

2023-06-28 11:55 UTC, vmuzikar requested changes
@shawkins Thanks for the PR. Please see https://github.com/keycloak/keycloak/pull/21056#issuecomment-1611266168

2023-06-28 15:55 UTC, vmuzikar approved these changes, later dismissed
LGTM based on https://github.com/keycloak/keycloak/pull/21056#issuecomment-1611680607, thanks @shawkins!

Could you please create a follow-up issue to eventually get rid of this workaround?

Also, it'd be nice to have this mentioned in the migration guide. It's [currently mentioned in the release notes](https://github.com/keycloak/keycloak/blob/main/docs/documentation/release_notes/topics/22_0_0.adoc?plain=1#L89-L91) but since it's a breaking change, it should be mainly in the migration guide. We could sneak this change into this PR, or create a separate one. Whatever you prefer.

2023-06-28 16:39 UTC, shawkins commented
> Could you please create a follow-up issue to eventually get rid of this workaround?

Captured as #21299

> Also, it'd be nice to have this mentioned in the migration guide. It's [currently mentioned in the release notes](https://github.com/keycloak/keycloak/blob/main/docs/documentation/release_notes/topics/22_0_0.adoc?plain=1#L89-L91) but since it's a breaking change, it should be mainly in the migration guide.

I'll add it here.

2023-06-29 06:56 UTC, vmuzikar approved these changes

2023-06-29 06:57 UTC, merged