Align naming of OTP policy window setting with actual semantics (#20469)
keycloak/keycloak pull request #21316
Opened 2023-06-29 13:46 UTC by thomasdarimont

This PR uses the term "look-around" to describe the used lookup window semantics.

Previously, the admin-ui incorrectly described the window setting as look-ahead although the implementation uses look-around semantics.

Note that this change affects only the admin-ui and the OTP implementation.

I  deliberately avoid changing RealmModel / Representation / persistence models to prevent the need for migration.

Fixes #20469

2023-06-30 12:34 UTC, edewit submitted a review, later dismissed

2023-06-30 14:04 UTC, jonkoops requested changes

2023-06-30 14:04 UTC, jonkoops commented on js/apps/admin-ui/public/locales/en/authentication-help.json
>    "lookAhead": "How far ahead should the server look just in case the token generator and server are out of time sync or counter sync?",
Same here, can this key be removed?

2023-07-03 08:20 UTC, thomasdarimont commented on js/apps/admin-ui/public/locales/en/authentication.json
>    "lookAhead": "Look ahead window",
I just removed the dangling keys.

2023-07-03 16:41 UTC, jonkoops approved these changes
LGTM

2023-07-03 21:37 UTC, pedroigor approved these changes

2023-07-03 21:38 UTC, pedroigor commented
@edewit Would mind reviewing the latest changes?

2023-07-04 10:40 UTC, jonkoops commented
@pedroigor Erik is on PTO this week, I think we can land this with a retro-active review.

2023-07-04 10:41 UTC, merged