Enable IPv6 dualstack support by default
keycloak/keycloak pull request #21340
Opened 2023-06-30 10:06 UTC by mabartos

Closes #15003

@vmuzikar Could you please check it? Thanks

2023-06-30 15:54 UTC, vmuzikar requested changes

2023-06-30 15:54 UTC, vmuzikar commented on quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/IpStackDistTest.java
> +        }
I think we can use something like this instead:
https://github.com/keycloak/keycloak/blob/72b238fb489aa9da257a5896772d6efde4a0f7d9/services/src/test/java/org/keycloak/vault/KeystoreVaultProviderTest.java#L67

2023-07-03 10:08 UTC, mabartos commented on docs/guides/server/outgoinghttp.adoc
> +== Configure Keycloak Server with IPv4 or IPv6
You're right. The section is not very suitable for this.

2023-07-03 10:20 UTC, mabartos commented
The most relevant section for including the settings for IPv4 and IPv6 is probably the Production configuration; doesn't have to be changed.

2023-07-03 10:20 UTC, vmuzikar approved these changes

2023-07-03 10:26 UTC, vmuzikar requested changes
@mabartos Actually, I realized we should probably mention this in the Migration Guide (we're changing the default behaviour here and it might be surprising to users that KC suddenly listens on IPv6). Could you please add it? Sorry about the last minute note.

2023-07-03 10:31 UTC, mabartos commented
@vmuzikar Good point. We could attach some notes to the migration guide to be more transparent in our actions.

2023-07-03 12:24 UTC, vmuzikar approved these changes

2023-07-03 13:35 UTC, merged