Inconsistent Wildcard handling for JPA
keycloak/keycloak pull request #21671
Opened 2023-07-13 08:17 UTC by vramik

Closes #20610

2023-07-13 11:46 UTC, ghost reviewed
Unreported flaky test detected, please review

2023-07-14 08:39 UTC, ahus1 requested changes
Thank you for providing the PR. This will make the behavior more consistent.

See below for some additional comments. 

As Keycloak's search behavior is something very central, I suggest to add this change to the release notes / migration guide as well. When mentioning the wildcard search with `*`, it would be helpful for readers to point out that adding quotes `"w*ord"` will do an exact search (as before).

2023-07-14 08:39 UTC, ahus1 commented on model/jpa/src/main/java/org/keycloak/models/jpa/JpaUserProvider.java
> +        value = value.toLowerCase().replace("%", "\\%").replace("_", "\\_");
I gave it a thought I think first all existing `\` should be escaped first before escaping the special characters.

2023-07-14 08:39 UTC, ahus1 commented on model/jpa/src/main/java/org/keycloak/models/jpa/JpaUserProvider.java
>              orPredicates.add(builder.like(from.get(EMAIL), value));
I had a look and one can add a thirst parameter to `.like()` with specifying the escape character. I had a look around what other frameworks do, and they seem to have `\` as the default escape character. Still there seems to be some intrinsic behavior at least in MS SQL where one can use backets to escape parts of a `LIKE`, unless you explicitly state the escaping character - see https://www.mytecbits.com/microsoft/sql-server/escape-square-brackets-in-like.

So I'd suggest to use the third parameter to make the escaping explicit in the code, and safe from MS SQL intrinsic. As `\` is then used in multiple places, it IMHO calls for a constant to be defined in this class for this value.

2023-07-27 12:49 UTC, ahus1 reviewed
@vramik - I reviewed the code and the tests worked nicely. I did some additional manual testing and found a corner case: 

When using an exact search like `"us%er"`, there shouldn't be any escaping. So I added one more commit where this is then moved into the LIKE block.

Please have a look if this change is OK from your point of view. Thanks!

2023-07-27 13:32 UTC, vramik commented
> Please have a look if this change is OK from your point of view. Thanks!

LGTM, thank you for the fix!

2023-07-27 15:03 UTC, ahus1 approved these changes
Thank you for this change which makes the behavior a lot more consistent for the users!

2023-07-27 15:03 UTC, merged