Fix infinite recursive loop causing application freeze
keycloak/keycloak pull request #22011
Opened 2023-07-26 22:41 UTC by alidandach

In the 'getInputStream()' contains an infinite recursive loop when 'needRequestRestore' was true and the 'body' was not null.

Fixes #22010

2023-07-27 07:09 UTC, ahus1 commented
Thank you for contributing this PR. Looking at the code changes this is really a problem, and you changes look good. 

I see that `FilterSessionStore` doesn't have any unit tests today, and it seems that any integration tests we have for this didn't catch this. 

So I wonder if you would be willing to add a unit test to `FilterSessionStore` at least for those methods you changed, or investigate if there are integration tests where this could be integrated. 

Please let me know how you want to proceed. Thanks!

2023-07-27 07:13 UTC, alidandach commented
> Thank you for contributing this PR. Looking at the code changes this is really a problem, and you changes look good.
> 
> I see that `FilterSessionStore` doesn't have any unit tests today, and it seems that any integration tests we have for this didn't catch this.
> 
> So I wonder if you would be willing to add a unit test to `FilterSessionStore` at least for those methods you changed, or investigate if there are integration tests where this could be integrated.
> 
> Please let me know how you want to proceed. Thanks!

By the end of this day I will add the unit tests

2023-07-27 08:14 UTC, alidandach commented
@ahus1 

The class `FilterSessionStore` is never used ....

Shall I delete it or write the unit tests....

2023-07-27 10:29 UTC, ahus1 commented
Well, it is being used. There is the `oidc/jakarata-servlet-filter` project which transforms the non-Jakarta version and generates the source code on the fly. 

See here for the transformer. Once you run it, you'll see the classes that use it.

https://github.com/keycloak/keycloak/blob/776bcbcbd43e745306c84e28b8cfe4e43163f31a/adapters/oidc/jakarta-servlet-filter/pom.xml#L115-L136

2023-07-31 08:12 UTC, ahus1 requested changes
Thanks for adding a test. As JUnit 4 is used throughout the project, I ask you to stick with JUnit 4. We also don't use Mockito here at the moment, and this test IMHO doesn't justify it for me to add it as a dependency. We also discourage the use of star imports. 

Please adjust your PR. Thanks.

2023-08-03 21:05 UTC, alidandach commented
I will fix it soon

2023-09-13 14:47 UTC, ahus1 approved these changes
I approve the first commit that was part of this PR and it can be merged. Future PRs might add tests for this. 

I will merge this PR if the automated tests pass.

2023-09-13 16:05 UTC, merged