French localization for account UI strings
keycloak/keycloak pull request #22089
Opened 2023-07-29 00:24 UTC by DimitriDR

Hi, here my proposal for the French localization for account UI strings. I'm sure it's not (still perfect), I'll adjust small details with use if I see any weird stuff.

2023-08-01 10:04 UTC, jonkoops commented
Hi @DimitriDR, thanks for your PR. Could you get your changes reviewed by another French native speaker? We always like to make sure there is at least one person reviewing that knows the subject matter.

2023-08-21 17:02 UTC, jonkoops commented
@Paul-Van-Uytvinck could I ask you to review this PR?

2023-08-22 07:31 UTC, Paul-Van-Uytvinck requested changes

2023-08-22 07:31 UTC, Paul-Van-Uytvinck commented on js/apps/account-ui/public/locales/fr/translation.json
> +  "infoMessage": "En cliquant sur Supprimer l'accès, vous supprimerez les permissions accordées de cette application. Cette application ne pourra plus utiliser vos informations.",
```suggestion
  "infoMessage": "En cliquant sur Supprimer l'accès, vous supprimerez les permissions accordées à cette application. Cette application ne pourra plus utiliser vos informations.",
```

2023-08-22 07:31 UTC, Paul-Van-Uytvinck commented on js/apps/account-ui/public/locales/fr/translation.json
> +  "linkedAccountsIntroMessage": "Gérew les connexion via les comptes tiers.",
```suggestion
  "linkedAccountsIntroMessage": "Gérez les connexions via les comptes tiers.",
```

2023-08-22 07:31 UTC, Paul-Van-Uytvinck commented on js/apps/account-ui/public/locales/fr/translation.json
> +  "resourceIntroMessage": "Partagez votre ressource avec vos membres de l'équipe",
```suggestion
  "resourceIntroMessage": "Partagez votre ressource avec les membres de votre équipe",
```

2023-08-22 07:31 UTC, Paul-Van-Uytvinck commented on js/apps/account-ui/public/locales/fr/translation.json
> +  "signingIn": "Connexoin",
```suggestion
  "signingIn": "Connexion",
```

2023-08-22 07:31 UTC, Paul-Van-Uytvinck commented on js/apps/account-ui/public/locales/fr/translation.json
> +  "signingInDescription": "Configuez les façons de vous authentifier.",
```suggestion
  "signingInDescription": "Configurez les façons de vous authentifier.",
```

2023-08-22 07:31 UTC, Paul-Van-Uytvinck commented on js/apps/account-ui/public/locales/fr/translation.json
> +  "unShare": "Tout ne plus partager",
```suggestion
  "unShare": "Ne plus rien partager",
```

2023-08-22 07:31 UTC, Paul-Van-Uytvinck commented on js/apps/account-ui/public/locales/fr/translation.json
> +  "unShareAllConfirm": "Êtes-vous sûr de vous complétement supprimer tous les partages ?",
```suggestion
  "unShareAllConfirm": "Êtes-vous sûr de vouloir complétement supprimer tous les partages ?",
```

2023-08-24 23:37 UTC, DimitriDR reviewed
Super useful typo fixes by @Paul-Van-Uytvinck

2023-08-25 15:34 UTC, jonkoops commented
@Paul-Van-Uytvinck can I ask you to take another look and confirm everything looks good now? If so, I think we can go ahead and merge this in.

2023-08-26 11:44 UTC, Paul-Van-Uytvinck approved these changes

2023-08-28 09:02 UTC, jonkoops approved these changes

2023-08-28 09:03 UTC, jonkoops commented
I've set this to automatically merge once the CI passes. Thanks for the contribution @DimitriDR and @Paul-Van-Uytvinck!

2023-08-29 11:47 UTC, merged