simplifying status updates to a single method for each controller
keycloak/keycloak pull request #22081
Opened 2023-07-28 12:35 UTC by shawkins

The operator sdk does not make it convienent to support a whiteboard approach to status aggregation.  Outside of our primary status update logic, the other methods were simply doing existence checks.  If the subsequent create running in the same reconciliation cycle suceeds, then there's no need to add the status stating that the resource doesn't exist.  If the subsequent create fails, then we'll have an error condition added to the status which should contain sufficent clues what and why it failed.

Partially addresses #13453

2023-07-28 16:36 UTC, shawkins commented
With the first commit the KeycloakIngressTest.testIngressOnHTTP(S) methods were flakey - it does not seem at first glance to be related to the change, nor was it reprodicible for me.

2023-07-30 11:46 UTC, shawkins commented
I'm still fuzzy about why a couple of ci runs had failures, with some additional logging it showed that a pod was stuck crashlooping - without a good indication of why.  I'd like to put #22093 in first, then rebase that pr on that and see if I can induce a failure again.

2023-07-31 18:58 UTC, shawkins commented
Removed the hold.  Still no good reproduction of the crash loop.

2023-08-01 15:01 UTC, shawkins commented
@vmuzikar this also contains a few cleanup to the changes for savePodLogs

2023-08-02 10:42 UTC, vmuzikar approved these changes
Thanks, LGTM.

2023-08-02 10:43 UTC, vmuzikar requested changes
Actually, I think this deserves a separate issue as it kinda affects functionality. Can you please create one?

2023-08-02 10:56 UTC, shawkins commented
> Actually, I think this deserves a separate issue as it kinda affects functionality. Can you please create one?

Do you mean the test related changes?

2023-08-02 11:01 UTC, vmuzikar commented
> Do you mean the test related changes?

Nah, the status updates simplification. That's basically a feature change and as such deserves an Issue.

2023-08-02 14:06 UTC, vmuzikar approved these changes

2023-08-02 14:44 UTC, merged