Update OCP4 Social IdP example setup in the latest docs
keycloak/keycloak pull request #22202
Opened 2023-08-02 18:55 UTC by Pepo48

* improved openshift.adoc

Closes #22159

2023-08-02 18:57 UTC, Pepo48 commented
@tondrusk PTAL, thanks.

2023-08-03 10:27 UTC, vmuzikar requested changes
@Pepo48 Thank you, added a few comments.

2023-08-03 10:27 UTC, vmuzikar commented on docs/documentation/server_admin/topics/identity-broker/social/openshift.adoc
> +. Enter your *Client ID*, *Client Secret*, *Valid Redirect URIs* and *Web Origins*.
I'm not sure I follow. :) Why to click Clients and create a Client? There's no Client at KC side. KC needs to have IdP, Client is created in OpenShift.

2023-08-03 10:27 UTC, vmuzikar commented on docs/documentation/server_admin/topics/identity-broker/social/openshift.adoc
> +. Enter the *Client ID* and *Client Secret* you used in the previous step and in the *Base URL* field, enter the API URL of your OpenShift 4 instance. Additionally, you can copy the *Redirect URI* to
See above. Client exists only in OpenShift, not in KC.

2023-08-03 12:04 UTC, Pepo48 commented
> @Pepo48 Thank you, added a few comments.

ou're right, I accidentally mixed two use-cases, my bad. Thanks for the review.

2023-08-03 15:24 UTC, vmuzikar approved these changes
@Pepo48 LGTM, thanks!

@ahus1 Do you want to review as well?

2023-08-03 16:56 UTC, ahus1 commented
@vmuzikar - while I can get my hands on an OpenShift instance to test this, this part is out of scope for both store and cross-dc, and I have never used it this way. So I choose not to review it. I hope you understand. Merging this as I see you've already reviewed it.

2023-08-03 16:57 UTC, merged

2023-08-04 06:11 UTC, vmuzikar commented
@ahus1 No problem. I pinged you just in case, as you've been keeping an eye on docs recently. ;)