Fix deprections in common module (#22209)
keycloak/keycloak pull request #22210
Opened 2023-08-02 23:23 UTC by thomasdarimont

- Use charset in `Encode` class
- Replace reflective call to protected `Liquibase#resetServices()` with call to exposed public method on a custom subclass `KeycloakLiquibase`
- Remove usage of deprecated AccessController class in Reflections
- Remove unused SetAccessibleProvilegedAction and UnsetAccessibleProvilegedAction

Fixes #22209

2024-06-28 08:29 UTC, ahus1 requested changes
Thank you for this PR. I agree the Liquibase parts can be improved by using less reflection. 

The removal of the classes in keycloak-common should be done by first deprecating them, and later removing them in a future issue. 

The change in `Encode.java` should not be a problem as we set `-Dfile.encoding=UTF-8` in the `JAVA_OPTS` in `kc.sh`, still it would be good to mention it in the release notes as it could lead to a different encoding of URL parameters.

2024-06-28 20:55 UTC, thomasdarimont commented
@ahus1 thanks for taking a look! I readded the removed classes and marked them for removal in KC27. I also added a brief note to the release notes.

2024-07-01 07:22 UTC, ahus1 requested changes
Thank you for the changes. Please add the deprecated methods to `changes-26_0_0.adoc` so people will know that that they'll need to change something.

2024-07-01 07:22 UTC, ahus1 commented on common/src/main/java/org/keycloak/common/util/reflections/Reflections.java
> +    public static <T> T newInstance(final Class<T> fromClass) throws ClassNotFoundException, IllegalAccessException, InstantiationException, InvocationTargetException, NoSuchMethodException {
Nitpick: Changing the signature of the method is also a breaking change at least when people want to compile their code. AFAIK this method is not used, so I'd suggest to either keep it as is for now, deprecate it for KC27 and eventually remove it.

2024-07-01 07:22 UTC, ahus1 commented on common/src/main/java/org/keycloak/common/util/reflections/Reflections.java
> -    public static <T> T newInstance(final Class<?> type, final String fullQualifiedName) throws ClassNotFoundException, IllegalAccessException, InstantiationException {
Nitpick - as above, I suggest deprecation and removal.

2024-07-02 14:56 UTC, ahus1 submitted a review, later dismissed
Thank you for this PR. I pushed one more commit as the updated class in `common` still contained additional exceptions in its signature. 

Thinking again about the docs, also decided to move all the docs changes to the `upgrading` guide as only those upgrading might be interested in them. The release notes usually only contain the highlights.

2024-07-02 14:58 UTC, ahus1 approved these changes

2024-07-02 16:02 UTC, merged