Release notes and documentation for FAPI 2
keycloak/keycloak pull request #22228
Opened 2023-08-03 16:07 UTC by mposolda

Closes #21945

2023-08-03 16:07 UTC, mposolda commented
@tnorimat @andymunro Can you please review this?

2023-08-03 17:27 UTC, andymunro commented on docs/documentation/release_notes/topics/23_0_0.adoc
> +Keycloak has new client profiles `fapi-2-security-profile` and `fapi-2-message-signing`, which ensure Keycloak to enforce compliance with
```suggestion
Keycloak has new client profiles `fapi-2-security-profile` and `fapi-2-message-signing`, which ensure Keycloak enforces compliance with
```

2023-08-03 17:28 UTC, andymunro requested changes
Looks good. Just one minor change.

2023-08-03 19:42 UTC, mposolda commented
@andymunro Thank you

2023-08-03 22:33 UTC, tnorimat approved these changes
LGTM.

2023-08-04 06:20 UTC, mposolda commented
@tnorimat Thanks!

2023-08-04 06:21 UTC, merged