DPoP release notes and documentation polishing
keycloak/keycloak pull request #22290
Opened 2023-08-07 09:33 UTC by mposolda

closes #21922

2023-08-07 10:05 UTC, tnorimat approved these changes
@mposolda LGTM.

2023-08-08 00:16 UTC, andymunro commented on docs/documentation/server_admin/topics/clients/oidc/con-advanced-settings.adoc
> +on if you want to make sure that particular client always uses DPoP binding.
```suggestion
If the switch `OAuth 2.0 DPoP Bound Access Tokens Enabled` is off, the client can still send `DPoP` proof in the token request. In that case, {project_name} will verify DPoP proof
and will add the thumbprint to the token. But if the switch is off, DPoP binding is not enforced by the {project_name} server for this client. It is recommended to have this switch
on if you want to make sure that particular client always uses DPoP binding.
```

2023-08-08 00:17 UTC, andymunro requested changes
Thanks just a couple of changes.

2023-08-08 07:47 UTC, mposolda commented
@tnorimat @andymunro Thanks for the review!
@andymunro I've applied the changes you requested.

2023-08-08 07:47 UTC, merged