Switch Trusted Host policy redirect verification to URI
keycloak/keycloak pull request #22314
Opened 2023-08-08 12:54 UTC by t0xicCode

Switch parsing of the redirect URIs for the Trusted Host Client Registration Policy from URL to URI. The java URL class tries to instantiate a handler for the scheme, which fails when a "custom" scheme, such as those used in phone apps is used. In contrast, the URI class simply parses the string, ensuring the format is valid. The other URLs (baseUrl, rootUrl, adminUrl) are still parsed as URLs. See https://openid.net/specs/openid-connect-registration-1_0.html#ClientMetadata for the Client Registration parameter documentation.

Closes #22309

2023-08-09 07:00 UTC, rmartinc requested changes
Thanks for the PR @t0xicCode! I think the changes are OK but can you please add a little test? I think [ClientRegistrationPoliciesTest](https://github.com/keycloak/keycloak/blob/22.0.1/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/ClientRegistrationPoliciesTest.java) can be a valid class to add a simple test there.

2023-08-10 14:02 UTC, rmartinc commented
@t0xicCode I don't see the test yet, and please better do a rebase than a merge when updating from the main branch. It's cleaner because only one commit is shown in the PR.

2023-08-10 14:15 UTC, t0xicCode commented
Will do!

I started the test but got distracted by other commitments. I should have
it all packaged up and rebased before the weekend.

2023-08-10 14:21 UTC, rmartinc commented
@t0xicCode No problem, there is no rush. Thanks a lot!

2023-08-10 23:21 UTC, t0xicCode commented
@rmartinc updated and test added!

2023-08-14 06:46 UTC, rmartinc approved these changes
LGTM! Thanks for the PR and the changes @t0xicCode!

2023-08-14 08:20 UTC, mposolda approved these changes
@t0xicCode Approving and merging as well.
@rmartinc Thanks for the review!

2023-08-14 08:20 UTC, merged