Update health.adoc to clarify the difference between the health endpoints
keycloak/keycloak pull request #22324
Opened 2023-08-08 18:20 UTC by smokris

While setting up a monitoring system to use Keycloak's health endpoints, I was unclear on the difference between `/health`, `/health/live`, and `/health/ready`, so I expanded the documentation based on the discussion in #11300.

2023-08-09 07:15 UTC, vmuzikar requested changes
@smokris Thank you for your contribution!

Added a few comments. Can you also please create and link an Issue to this PR?

2023-08-09 07:15 UTC, vmuzikar commented on docs/guides/server/health.adoc
> +** if the Keycloak server process is running but the database is not reachable, responds with HTTP status `503 Service Unavailable`
I would not mention the DB checks here as it depends on if metrics are enabled.

2023-08-12 01:44 UTC, smokris commented
@vmuzikar, thanks for the feedback and for pointing out the Quarkus docs.  Maybe it would be simpler to just link to those docs (rather than inaccurately duplicating some of it).  I just pushed a new version that does that, and includes additional sample output.  I also created issue #22402 as requested.

2023-08-25 16:47 UTC, vmuzikar approved these changes
@smokris LGTM, thank you.

2023-08-25 16:48 UTC, merged