Expose additional information (expiration, sha1 hash) about realm keys in admin UI
keycloak/keycloak pull request #22363
Opened 2023-08-10 08:00 UTC by thomasdarimont

- Show Not After information
- Show certificate sha1 thumbprint

Incorporates: #7890

Fixes #17743 and KEYCLOAK-17609

2023-08-10 09:51 UTC, thomasdarimont commented
Just tested this again locally, looks like that with current main:

![image](https://github.com/keycloak/keycloak/assets/314690/ac6fee33-16c3-4353-b730-eeccf4ff36bf)

2023-08-10 09:58 UTC, thomasdarimont commented on js/apps/admin-ui/src/realm-settings/keys/KeysListTab.tsx
> +                    <Button
@edewit  The button alignment seems a bit off, how can I fix that?

2023-08-10 10:04 UTC, thomasdarimont commented on js/apps/admin-ui/src/realm-settings/keys/KeysListTab.tsx
> +            displayKey: "realm-settings:notAfter",
Perhaps introduce a new translation key here "realm-settings:expiresAt" ?

2023-08-10 11:19 UTC, ahus1 commented on core/src/main/java/org/keycloak/crypto/KeyWrapper.java
> +            return MessageDigest.getInstance("SHA1").digest(certificate.getEncoded());
SHA-1 has been deprecated for some time, and shouldn't be used: https://en.wikipedia.org/wiki/SHA-1 around certificates (although this is "only" the fingerprint of the certificate itself, not the signed hash of the public key AFAIK).

I see that you manually create a hash for a certificate's byte stream. I wonder if there is a more ready-to-use Java mechanism to get a fingerprint of a certificate than this. Did you check that this matches for example the fingerprint provided by OpenSSL on the command line?

2023-08-11 15:25 UTC, pedroigor commented on core/src/main/java/org/keycloak/crypto/KeyWrapper.java
> +            return MessageDigest.getInstance("SHA1").digest(certificate.getEncoded());
That particular claim attribute is specific to SHA1. See https://datatracker.ietf.org/doc/html/rfc7515#section-4.1.7 and https://datatracker.ietf.org/doc/html/rfc7517#page-9.

But yeah, SHA-1 should be deprecated in favor of SHA-256 as it is less likely to collisions. Libraries like Nimbus already deprecated using SHA-1 in thumbprints.

2023-08-11 15:27 UTC, pedroigor requested changes

2023-08-11 15:27 UTC, pedroigor commented on core/src/main/java/org/keycloak/jose/jws/JWSBuilder.java
> +        if (thumbprint != null) builder.append(",\"x5t\" : \"").append(thumbprint).append("\"");
Is this related to exposing more info in admin UI?

If we are about to add support for adding the thumbprint to the JWS header, we should probably consider adding `x5t#S256`.

2023-09-06 19:43 UTC, thomasdarimont commented
I'm closing this PR in favor of #23025 which focusses on displaying the expiration date of a certificate in Keys List in admin-ui.

2023-09-06 19:43 UTC, closed without merging