Remove Brotli dependencies from the distribution
keycloak/keycloak pull request #22484
Opened 2023-08-16 12:23 UTC by Pepo48

* excluded the dependencies from the keycloak-quarkus-server pom

Closes #22482

2023-08-16 15:04 UTC, vmuzikar requested changes
More brotli4j dependencies seem to be present in the operator. Can you please remove it there too?

2023-08-17 06:53 UTC, vmuzikar approved these changes
@Pepo48 LGTM, thanks. Can you please create a backport?

2023-08-17 06:53 UTC, merged

2025-10-10 21:48 UTC, recena commented on operator/pom.xml
> +                    <artifactId>*</artifactId>
Wildcards does not work here.

2025-10-10 21:49 UTC, recena commented
If we want to stop including **brotli4j**, we should do:

```
diff --git a/pom.xml b/pom.xml
index 3e9f3b4bcf..25c231c3b3 100644
--- a/pom.xml
+++ b/pom.xml
@@ -1096,6 +1096,29 @@
                 <artifactId>keycloak-quarkus-server</artifactId>
                 <version>${project.version}</version>
             </dependency>
+            <dependency>
+                <groupId>io.quarkus</groupId>
+                <artifactId>quarkus-vertx-http</artifactId>
+                <version>${quarkus.version}</version>
+                <exclusions>
+                    <exclusion>
+                        <groupId>com.aayushatharva.brotli4j</groupId>
+                        <artifactId>brotli4j</artifactId>
+                    </exclusion>
+                    <exclusion>
+                        <groupId>com.aayushatharva.brotli4j</groupId>
+                        <artifactId>native-linux-x86_64</artifactId>
+                    </exclusion>
+                    <exclusion>
+                        <groupId>com.aayushatharva.brotli4j</groupId>
+                        <artifactId>native-osx-x86_64</artifactId>
+                    </exclusion>
+                    <exclusion>
+                        <groupId>com.aayushatharva.brotli4j</groupId>
+                        <artifactId>native-windows-x86_64</artifactId>
+                    </exclusion>
+                </exclusions>
+            </dependency>
             <dependency>
                 <groupId>org.keycloak</groupId>
                 <artifactId>keycloak-quarkus-server-deployment</artifactId>
```