Added missing hungarian translations, fix typos
keycloak/keycloak pull request #22504
Opened 2023-08-16 17:34 UTC by nkelemen18

Resource files synchronized with the original English files. Added missing entries and fixed some Hungarian typos.

Closes: #22503

2023-08-17 06:13 UTC, ahus1 commented
Thank you for your contribution. Please someone from the Keycloak community to review your translations and leave a comment or review in this issue. Once there is a review this PR can be merged. Thanks!

2023-09-12 20:22 UTC, Markerer requested changes
Nice job, only some extra typo fixes are necessary.

2023-09-12 20:22 UTC, Markerer commented on themes/src/main/resources-community/theme/base/login/messages/messages_hu.properties
> +doConfirmDelete=Törlése megerősítése
```suggestion
doConfirmDelete=Törlés megerősítése
```

2023-09-12 20:22 UTC, Markerer commented on themes/src/main/resources-community/theme/base/login/messages/messages_hu.properties
> +updateEmailMessage=Fiókja aktiválásához előbb le módosítania kell e-mail címét.
```suggestion
updateEmailMessage=Fiókja aktiválásához előbb módosítania kell e-mail címét.
```

2023-09-12 20:22 UTC, Markerer commented on themes/src/main/resources-community/theme/keycloak.v2/account/messages/messages_hu.properties
> +userNotFound=Nem található felhasználó a(z) {0} névvél vagy E-mail címmel.
```suggestion
userNotFound=Nem található felhasználó a(z) {0} névvél vagy e-mail címmel.
```

2023-09-12 20:22 UTC, Markerer commented on themes/src/main/resources-community/theme/keycloak.v2/account/messages/messages_hu.properties
> +applicationsPageSubTitle=Alkalmazások jogosultságainak kézelése
```suggestion
applicationsPageSubTitle=Alkalmazások jogosultságainak kezelése
```

2023-09-12 20:22 UTC, Markerer commented on themes/src/main/resources-community/theme/keycloak.v2/account/messages/messages_hu.properties
> +groupDescriptionLabel=Az Önhöz tartozó csoportok megtakintése
```suggestion
groupDescriptionLabel=Az Önhöz tartozó csoportok megtekintése
```

2023-09-12 20:30 UTC, Markerer approved these changes

2023-09-12 20:31 UTC, nkelemen18 commented
> Nice job, only some extra typo fixes are necessary.

Thank you, your suggestions are applied.

@ahus1: I think, this PR is ready from our side.

2023-09-13 06:37 UTC, ahus1 approved these changes, later dismissed
Thank you for updating the translation and the teamwork!

2023-09-13 07:16 UTC, nkelemen18 commented
@ahus1 I squashed my commits and rebased my branch on to of the main

2023-09-13 07:35 UTC, ahus1 commented
@nkelemen18 Please only rebase when you've been asked for once your changes have been approved, as rebases will discard previous approvals. I would have squashed and rebased the changes automatically.

2023-09-13 07:35 UTC, ahus1 approved these changes

2023-09-13 08:54 UTC, merged