user profile test
keycloak/keycloak pull request #22576
Opened 2023-08-21 12:17 UTC by edewit

- update personal info test with user profile
- global setup now imports all realms

2023-08-21 12:18 UTC, jonkoops approved these changes, later dismissed
LGTM

2023-08-29 15:28 UTC, agagancarczyk approved these changes, later dismissed

2023-08-30 07:02 UTC, jonkoops approved these changes, later dismissed

2023-08-30 09:04 UTC, jonkoops approved these changes

2023-08-30 12:53 UTC, jonkoops requested changes

2023-08-30 12:53 UTC, jonkoops commented on js/apps/admin-ui/src/user/components/SelectComponent.tsx.orig
This file looks to be a temporary one, can probably be removed.

2023-08-31 08:16 UTC, jonkoops approved these changes

2023-08-31 08:30 UTC, agagancarczyk approved these changes

2023-08-31 09:32 UTC, ahus1 approved these changes
Approving the workflow changes

2023-08-31 09:32 UTC, merged