Do not initialize barrier build items for deployment
keycloak/keycloak pull request #22616
Opened 2023-08-22 13:55 UTC by mabartos

We don't have to instantiate build items, which don't contain any data and are used only as barriers for execution order.

Check it here: https://quarkus.io/guides/writing-extensions#empty-build-items

2023-08-22 19:11 UTC, pedroigor approved these changes

2023-08-25 15:38 UTC, vmuzikar approved these changes
LGTM, thanks @mabartos

2023-08-25 15:40 UTC, vmuzikar requested changes
Actually, we're missing a GH Issue here. Since this could be considered an enhancement and it's not test related, I think it deserves one.

@mabartos Can you please create it?

2023-08-25 18:03 UTC, mabartos commented
@vmuzikar Done

2023-08-28 07:02 UTC, vmuzikar approved these changes

2023-08-28 07:02 UTC, merged