Support customize common path in welcome theme
keycloak/keycloak pull request #22717
Opened 2023-08-25 11:40 UTC by kamontat

2023-08-25 15:10 UTC, jonkoops commented
@ssilvert I think this might be up your alley?

2023-09-05 18:58 UTC, ssilvert commented
@kamontat Sorry for the lack of action on this one.  @jonkoops and I are trying to come up with a standard for dealing with "common" that will be consistent for all theme features (welcome, email, admin console, account console, login).

2023-09-11 14:50 UTC, kamontat commented
If you need me, I happy to help :)

2024-01-18 21:02 UTC, ssilvert commented
@jonkoops Given our recent conversations, I'm inclined to merge this as-is (with conflicts fixed, of course).  It's a little inconsistent with the other theme types, but the Welcome theme type is kind of on its own anyway.  So this seems to make sense.

@kamontat Can you fix the conflicts?

2024-01-19 10:16 UTC, kamontat commented
@ssilvert Resolved conflict.

2024-01-19 10:51 UTC, jonkoops requested changes

2024-01-19 10:51 UTC, jonkoops commented on services/src/main/java/org/keycloak/services/resources/WelcomeResource.java
> +            }
I believe we can provide a default value to `getProperty()` here, it wouldn't handle the empty case, but that is a user-error anyways.
```suggestion
            String commonPath = themeProperties.getProperty("common", "common/keycloak");
```

2024-01-19 12:28 UTC, ssilvert approved these changes, later dismissed

2024-01-19 15:00 UTC, jonkoops submitted a review, later dismissed

2024-01-19 15:02 UTC, jonkoops commented
@kamontat can you squash your commits and sign off on them? Also please don't keep merging `main` into your branch unless there are conflicts, as it will generate additional notifications and CI runs. If you do have to get things from `main` I recommend that you use a rebase instead, as it keeps the GIT history clean.

2024-01-20 07:19 UTC, kamontat commented
I make some mistake when rebase the commits, so I create new commit and force-push instead. This will resolve DCO as well. Sorry for any inconvenience.

2024-01-20 10:27 UTC, jonkoops approved these changes

2024-02-07 01:41 UTC, ssilvert approved these changes

2024-02-07 01:41 UTC, merged