feat: add error message to fetchWithError util function
keycloak/keycloak pull request #22827
Opened 2023-08-30 14:34 UTC by m1212e

This small adjustment adds the error message in case of an unsuccessful request to the error that is logged in the console. This helps to know what went wrong while developing.

2023-08-31 10:41 UTC, jonkoops requested changes
Perhaps this would be good to handle with the `cause` property, as [per MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/cause):

> The `cause` data property of an [`Error`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error) instance indicates the specific original cause of the error.
>
> It is used when catching and re-throwing an error with a more-specific or useful error message in order to still have access to the original error.

2023-09-12 11:48 UTC, jonkoops commented
@m1212e are you still interested in landing this? We have a policy of not keeping PRs out for too long, so let me know if you are still interested.

2023-09-12 12:18 UTC, m1212e commented
Sorry for the late response, got a lot going on atm. I understand, I will open a fresh PR when I have some spare time, thanks for the response, sorry for the inconvenience!

2023-09-12 12:18 UTC, closed without merging

2023-09-12 14:00 UTC, jonkoops commented
No worries at all, we very much appreciate you taking the time to do this. And as with all open-source, we are considerate of the fact that you are doing this in your free time. We simply need to make sure we don't keep too many things open at once.

Thanks again!