details about register token proivder added
keycloak/keycloak pull request #22908
Opened 2023-09-02 19:03 UTC by Srishtihere

with reference to the issue #20044

2023-09-03 10:42 UTC, jonkoops commented
Thanks for the PR @Srishtihere. I think the best place for this would be the README of the Admin Client itself, which can be found [here](https://github.com/keycloak/keycloak/blob/f99c82cd43461a9ad3debb2aca4bbfaec171696b/js/libs/keycloak-admin-client/README.md).

2023-09-03 12:58 UTC, Srishtihere commented
ooh okay sure I'll make the changes asap

2023-09-11 12:14 UTC, jonkoops requested changes

2023-09-11 12:14 UTC, jonkoops commented on js/libs/keycloak-admin-client/README.md
> +The term "keycloakAdminClient" refers to an instance of the Keycloak Admin Client library. Keycloak is an open-source identity and access management solution, and the Admin Client is a component that
I think this is already pretty self explanatory from the earlier examples in the README, no need to repeat things.
```suggestion
```

2023-09-11 12:14 UTC, jonkoops commented on js/libs/keycloak-admin-client/README.md
> +```
Let's add some markup so this interpreted as JavaScript, also let's be more explicit about returns for the sake of making things easier to understand for novice users.
```suggestion
```js
keycloakAdminClient.registerTokenProvider({
  getAccessToken() {
    return Promise.resolve('some access token');
  }
});
```
```

2024-01-03 13:54 UTC, hmlnarik commented
@Srishtihere Do you plan to address the review comments in this PR?

2024-01-03 14:36 UTC, Srishtihere commented
I am busy with my internship maybe you can close this pr

2025-08-18 16:28 UTC, shawkins commented
Closing due to lack of progress.

2025-08-18 16:28 UTC, closed without merging