Fix group roles mapping permissions
keycloak/keycloak pull request #22956
Opened 2023-09-04 18:18 UTC by daniel-pimenta-DME

Enables Role mapping tab when user has `manage` permission for the group

Closes issue #20125

2023-09-11 11:49 UTC, jonkoops requested changes
Please ensure there are no unnecessary code formatting changes and follow the configuration of the linter.

2023-09-12 17:21 UTC, ssilvert requested changes

2023-09-12 17:21 UTC, ssilvert commented on js/apps/admin-ui/src/components/role-mapping/AddRoleMappingModal.tsx
> +                                    }: AddRoleMappingModalProps) => {
Looks like these lines didn't change?  But introduced some spaces?

2023-09-19 12:08 UTC, ssilvert commented
@daniel-pimenta-DME Please fix conflicts.

2023-10-03 19:43 UTC, ssilvert commented
@daniel-pimenta-DME I'm going to go ahead and close this.  We can reopen later if you want to pick it up.

2023-10-03 19:43 UTC, closed without merging