Remove statement that minValidity is optional in isTokenExpired
keycloak/keycloak pull request #23050
Opened 2023-09-07 10:17 UTC by ddubrava

In the JavaScript adapter documentation it's said that `minValidity` in `updateToken` is optional, while it's not.

<img width="706" alt="Screenshot 2023-09-07 at 12 10 39" src="https://github.com/keycloak/keycloak/assets/22116465/3ae0cf2d-0407-4ae1-8afb-a5bff335839f">

2023-09-11 11:22 UTC, jonkoops requested changes
The value is [actually optional](https://github.com/keycloak/keycloak/blob/e2f344b85a2cf20344b5f4f762260d80936b5a59/js/libs/keycloak-js/src/keycloak.js#L613), the type definition is wrong and should be corrected instead.

2023-09-11 11:22 UTC, jonkoops commented
@ddubrava could you also log an issue for this? It will make it easier for us to backport this change to a patch release.

2023-09-11 16:03 UTC, ddubrava commented
sure, I will

2023-09-12 14:30 UTC, jonkoops commented
Thanks for that. Do you intend to update this PR to change this, or do you prefer to open up a new one?

2023-09-12 16:59 UTC, ddubrava commented
> Thanks for that. Do you intend to update this PR to change this, or do you prefer to open up a new one?

I'll fix it in this one

2023-09-12 17:48 UTC, ddubrava commented
The param description is copied from this method

<img width="612" alt="Screenshot 2023-09-12 at 19 48 00" src="https://github.com/keycloak/keycloak/assets/22116465/40ad0d42-4dd8-4473-8f58-48a8841d8ad1">

2023-09-14 09:32 UTC, jonkoops approved these changes

2023-09-14 09:34 UTC, jonkoops commented
I've set the PR to merge automatically once CI passes, thanks for your contribution @ddubrava!

2023-09-14 10:13 UTC, merged