partially remove name spaces
keycloak/keycloak pull request #23137
Opened 2023-09-11 09:57 UTC by edewit

this removes the prefixes for

* client-scopes
* client-scopes-help
* clients-help
* clients

working towards fixing #23094

2023-09-11 10:48 UTC, jonkoops requested changes
The messages for locales other than English have not been updated. It also seems like there are a lot of unrelated formatting changes (perhaps a `pnpm i` is needed?).

2023-09-12 13:52 UTC, jonkoops approved these changes, later dismissed

2023-09-13 08:35 UTC, jonkoops approved these changes, later dismissed

2023-09-13 14:05 UTC, ssilvert approved these changes

2023-09-13 14:05 UTC, merged