i18n: Add Thai language
keycloak/keycloak pull request #23165
Opened 2023-09-12 08:55 UTC by weeix

This PR is intended to incorporate the Thai language into Keycloak, specifically in the following Themes:

- Base > Account
- Base > Email
- Base > Login
- Keycloak.v2

2023-09-12 09:54 UTC, jonkoops commented
Hi @weeix, thanks for your PR. We require changes to localization to have at least one reviewer which is a native speaker of the language. If you know someone who can review your work here, please ask them to do so.

2023-09-13 06:47 UTC, weeix commented
Hello @jonkoops, I have shared invitations for reviewing this PR in several Facebook groups. These groups consist of Thai individuals who may potentially utilize Keycloak in their professional capacities.

2023-09-13 07:28 UTC, nickethachin approved these changes
I'm Thai native speaker and theses translation look good to me.
Both context and meaning is correct and to the point.

2023-09-13 07:37 UTC, ghost approved these changes
I’m Thai and this commit looks good to me.

2023-09-13 07:45 UTC, ahus1 submitted a review, later dismissed
Approving as of community reviews

2023-09-13 08:14 UTC, amincheloh commented
According to the Royal Society of Thailand (ราชบัณฑิตยสภา), the word 'Application' should be transliterated as 'แอปพลิเคชัน'.

2023-09-13 08:15 UTC, amincheloh commented on themes/src/main/resources-community/theme/base/account/messages/messages_th.properties
> +role_uma_authorization=ขออนุญาติ
ขออนุญาต

2023-09-13 08:18 UTC, ahus1 commented
@weeix - I see additional comments from the community. Please let me know if you want to address them in this pull request or a future pull request.

2023-09-13 10:02 UTC, weeix commented
> @weeix - I see additional comments from the community. Please let me know if you want to address them in this pull request or a future pull request.

I will address them in this pull request.

2023-09-13 11:13 UTC, sapondanaisriwan commented
แอพพลิเคชัน -> แอปพลิเคชัน

2023-09-13 15:14 UTC, bouroo requested changes

2023-09-13 15:14 UTC, bouroo commented on themes/src/main/resources-community/theme/keycloak.v2/account/messages/messages_th.properties
> +signedInDevicesExplanation=ลงชื่อออกจากอุปกรณ์ที่ไม่คุ้นเคยใด ๆ
should be nice with `ลงชื่ออกจากอุปกรณ์อื่นที่ไม่คุ้นเคย`

2023-09-13 15:14 UTC, bouroo commented on themes/src/main/resources-community/theme/base/account/messages/messages_th.properties
> +client_admin-cli=Admin CLI
CLI สำหรับผู้ดูแลระบบ

2023-09-13 15:14 UTC, bouroo commented on themes/src/main/resources-community/theme/base/account/messages/messages_th.properties
> +client_broker=Broker
may be `ตัวแทน` ?

2023-09-13 15:14 UTC, bouroo commented on themes/src/main/resources-community/theme/base/account/messages/messages_th.properties
> +totpDigits=Digits
ตัวเลข

2023-09-13 15:14 UTC, bouroo commented on themes/src/main/resources-community/theme/base/account/messages/messages_th.properties
> +totpInterval=Interval
ช่วงเวลา

2023-09-13 15:14 UTC, bouroo commented on themes/src/main/resources-community/theme/base/account/messages/messages_th.properties
> +user=ผู้ใช้
`user` should be nice with `ผู้ใช้งาน`

2023-09-13 15:14 UTC, bouroo commented on themes/src/main/resources-community/theme/base/account/messages/messages_th.properties
> +requestor=ผู้ขอ
ผู้ร้องขอ

2023-09-13 15:14 UTC, bouroo commented on themes/src/main/resources-community/theme/base/login/messages/messages_th.properties
> +loginTotpInterval=Interval
ช่วงเวลา

2023-09-13 15:41 UTC, weeix commented on themes/src/main/resources-community/theme/base/account/messages/messages_th.properties
> +totpDigits=Digits
หรือเป็น หลัก ดีไหมครับ ไปเจอภาพในเน็ตว่ามันมีให้เลือกระหว่าง 6 หรือ 8 หลัก

https://www.keycloak.org/docs/latest/server_admin/images/otp-policy.png

2023-09-13 16:13 UTC, weeix commented
Thank you. Additional suggestions are always welcome.

Changes (force-pushed):

- Translations have been enhanced based on community review suggestions.
- All changes have been consolidated into a single commit.
- The `totpAppMicrosoftAuthenticatorName` translation, previously missing, has now been added to the *Base > Account* section.
- The `access-denied-when-idp-auth` translation, previously missing, has now been added to the *Base > Account* section.
- The `totpAppMicrosoftAuthenticatorName` translation, previously missing, has now been added to the *Base > Login* section.
- A newline has been inserted in the *Base > Account* section for alignment with the English translation.
- All trailing spaces have been removed.

2023-09-13 17:27 UTC, chalut01 approved these changes
LGTM

2023-09-13 21:37 UTC, amincheloh commented
LGTM

2023-09-14 03:36 UTC, bouroo commented on themes/src/main/resources-community/theme/base/account/messages/messages_th.properties
> +totpDigits=Digits
ก็ดีนะครับ พอดีผมไม่เห็นว่าบริบทจริง ๆ เป็นยังไง

2023-09-14 06:54 UTC, ahus1 approved these changes
Thank you for these changes and the review from the community!

2023-09-14 07:12 UTC, bouroo commented on themes/src/main/resources-community/theme/base/login/messages/messages_th.properties
> +requiredAction.webauthn-register-passwordless=Webauthn Register Passwordless
ลงทะเบียนแบบไม่ใช้รหัสผ่านด้วย WebAuthn

2023-09-14 09:05 UTC, jonkoops commented
Giving this a quick rebase to hopefully pass the CI.

2023-09-14 09:05 UTC, jonkoops approved these changes

2023-09-14 10:53 UTC, merged

2023-09-14 11:05 UTC, ahus1 commented
Thank you for this PR. As there were some additional comments which weren't included in this PR, please create additional PRs as needed to address those comments. We'll be happy to merge them once they - like this one - have been reviewed by native speaker.