Clarify transient sessions documentation
keycloak/keycloak pull request #23328
Opened 2023-09-18 15:58 UTC by mposolda

Closes #23044

2023-09-18 15:58 UTC, mposolda commented
@andymunro Could you please review when you have some free cycles?

2023-09-25 16:02 UTC, andymunro commented on docs/documentation/server_admin/topics/sessions/transient.adoc
> +The `sid` and `session_state` of the tokens are usually empty when token is issued with transient sessions. So during transient sessions, the client application cannot refresh tokens or validate a sp
```suggestion
The `sid` and `session_state` of the tokens are usually empty when the token is issued with transient sessions. So during transient sessions, the client application cannot refresh tokens or validate a specific session.
```

2023-09-25 16:02 UTC, andymunro commented on docs/documentation/server_admin/topics/sessions/transient.adoc
> +At this moment, transient sessions are automatically used just during <<_service_accounts, service account authentication>> with disabled token refresh. Please note that token refresh is
```suggestion
At this moment, transient sessions are automatically used just during <<_service_accounts, service account authentication>> with disabled token refresh. Note that token refresh is
```

2023-09-25 16:03 UTC, andymunro requested changes
Thanks, @mposolda. A couple of suggestions.

2023-09-27 09:45 UTC, mposolda commented
@andymunro Applied your suggestions. Thanks!

2023-09-27 13:14 UTC, merged