Remove deprecated auto-build CLI option
keycloak/keycloak pull request #23361
Opened 2023-09-19 14:16 UTC by mabartos

Closes #23360

@vmuzikar I believe it's time to get rid of it and clean up the config a little bit, right? :))

2023-09-21 08:01 UTC, mabartos commented on docs/documentation/upgrading/topics/keycloak/changes-23_0_0.adoc
> +If you are using this option, you can leverage the `--optimized` CLI option, which provides a similar functionality.
Depends on how you think about it as it's kinda connected in the end. But you're right, doesn't have to be mentioned here. Thanks

2023-09-21 11:05 UTC, pedroigor submitted a review, later dismissed

2023-09-21 11:28 UTC, vmuzikar requested changes

2023-09-21 11:28 UTC, vmuzikar commented on quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/StartAutoBuildDistTest.java
I don't think we should remove this test class completely. I believe arts of it are still valid as they focus on `--optimized` flag and build process in general etc.

2023-09-21 12:42 UTC, pedroigor commented on quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/StartAutoBuildDistTest.java
Ohh, that is true.

2023-09-25 19:08 UTC, pedroigor approved these changes

2023-09-27 13:02 UTC, mabartos commented
@vmuzikar Can you check it, please?

2023-09-27 16:56 UTC, vmuzikar approved these changes
LGTM, thanks

2023-09-27 16:56 UTC, merged