Add references to OAuth 2.0 Security Best Practices for Implicit and
keycloak/keycloak pull request #23482
Opened 2023-09-22 14:12 UTC by jsorah

ROPC flow, reformat Device Auth section.

Closes keycloak/keycloak#23480

2023-09-22 15:52 UTC, mposolda submitted a review, later dismissed
@jsorah Thanks!
@andymunro Is this PR ok to you?

2023-09-25 15:22 UTC, andymunro commented on docs/documentation/securing_apps/topics/oidc/supported-grant-types.adoc
> +Per current https://datatracker.ietf.org/doc/html/draft-ietf-oauth-security-topics-23#name-implicit-grant[OAuth 2.0 Security Best Current Practice] this flow should not be used.
```suggestion
Per current https://datatracker.ietf.org/doc/html/draft-ietf-oauth-security-topics-23#name-implicit-grant[OAuth 2.0 Security Best Current Practice], this flow should not be used.
```

2023-09-25 15:23 UTC, andymunro commented on docs/documentation/securing_apps/topics/oidc/supported-grant-types.adoc
> +Per current https://datatracker.ietf.org/doc/html/draft-ietf-oauth-security-topics-23#name-resource-owner-password-cre[OAuth 2.0 Security Best Practices]
```suggestion
Per current https://datatracker.ietf.org/doc/html/draft-ietf-oauth-security-topics-23#name-resource-owner-password-cre[OAuth 2.0 Security Best Practices],
```

2023-09-25 15:24 UTC, andymunro commented on docs/documentation/securing_apps/topics/oidc/supported-grant-types.adoc
> +. The application requests {project_name} a device code and a user code.
```suggestion
. The application requests  that {project_name} provide a device code and a user code.
```

2023-09-25 15:24 UTC, andymunro requested changes
Thanks, @mposolda. Just  few changes.

2023-09-25 18:25 UTC, jsorah commented
@andymunro @mposolda  - accepted changes from code review and squashed commits.

2023-09-27 09:43 UTC, mposolda commented
@jsorah @andymunro Thanks for the review and follow-up changes!

2023-09-27 09:43 UTC, mposolda approved these changes

2023-09-27 09:43 UTC, merged