Rename "Realm name" field label to "Realm ID" on create realm page
keycloak/keycloak pull request #23497
Opened 2023-09-25 00:11 UTC by Anil-Shanker

Closes #23496

2023-09-25 08:25 UTC, jonkoops requested changes

2023-09-25 08:25 UTC, jonkoops commented on js/apps/admin-ui/src/realm/add/NewRealmForm.tsx
> +                  message: t("invalidRealmId"),
Looking at the translations this field doesn't exist, you'll probably have to rename it in the JSON files like you did with the realm name.

2023-09-26 02:32 UTC, Anil-Shanker commented on js/apps/admin-ui/src/realm-settings/GeneralTab.tsx
> +                message: t("realm:invalidRealmId"),
Does passing "realm:invalidRealmId" refer to something other than "invalidRealmId"?

2023-09-26 02:38 UTC, Anil-Shanker commented
I mistakenly had to add an extra commit - would it possible to squash the extra commits from inside GitHub?

2023-10-03 12:31 UTC, jonkoops requested changes

2023-10-10 11:59 UTC, jonkoops commented
@Anil-Shanker are you still interested in landing this? Could you processes the review comments?

2023-10-23 18:17 UTC, closed without merging

2023-10-23 18:17 UTC, ssilvert commented
@Anil-Shanker I'm going to close this now.  We can reopen when you are ready to work on it again.