Update Account UI French translation as of September 26th.
keycloak/keycloak pull request #23544
Opened 2023-09-26 20:53 UTC by DimitriDR

Hi,

This is my contribution to add the few new strings for Account UI.
Also fixed some little typos previously written.

2023-10-14 12:07 UTC, jonkoops commented
@Paul-Van-Uytvinck since you previously worked on the French localizations could I ask you to review this PR?

2023-10-16 15:37 UTC, Paul-Van-Uytvinck requested changes

2023-10-16 15:37 UTC, Paul-Van-Uytvinck commented on js/apps/account-ui/public/locales/fr/translation.json
> +  "flowTypeHelp": "Quel genre de formulaire est-ce",
```suggestion
  "flowTypeHelp": "De quel genre de formulaire s'agit-il",
```

2023-10-16 15:37 UTC, Paul-Van-Uytvinck commented on js/apps/account-ui/public/locales/fr/translation.json
> +  "rolesScope": "S'il n'y a aucun mappage de portée de rôle défini, chaque utilisateur est autorisé à utiliser cette portée client. S'il y a des mappages de portée de rôle, l'utilisateur doit être un
```suggestion
  "rolesScope": "S'il n'y a aucun mappage de portée de rôle défini, chaque utilisateur est autorisé à utiliser cette portée du client. S'il y a des mappages de portée de rôle, l'utilisateur doit être membre d'au moins l'un des rôles.",
```

2023-10-16 15:37 UTC, Paul-Van-Uytvinck commented on js/apps/account-ui/public/locales/fr/translation.json
> +  "scopeNameHelp": "Nom de la portée du client. Doit être unique dans le domaine. Le nom ne doit pas contenir d'espaces car il est utilisé comme valeur du paramètre de la portée",
```suggestion
  "scopeNameHelp": "Nom de la portée du client. Doit être unique dans le domaine. Le nom ne doit pas contenir d'espace car il est utilisé comme valeur du paramètre de la portée",
```

2023-10-16 15:37 UTC, Paul-Van-Uytvinck commented on js/apps/account-ui/public/locales/fr/translation.json
> +  "scopeTypeHelp": "Portés du client, qui seront ajoutées comme portées par défaut à chacun des clients créés",
```suggestion
  "scopeTypeHelp": "Portées du client, qui seront ajoutées comme portées par défaut à chacun des clients créés",
```

2023-10-16 15:37 UTC, Paul-Van-Uytvinck commented on js/apps/account-ui/public/locales/fr/translation.json
> +  "scopesHelp": "Les portées associées avec cette ressource."
```suggestion
  "scopesHelp": "Les portées associées à cette ressource."
```

2023-10-16 21:16 UTC, Paul-Van-Uytvinck approved these changes

2023-10-16 22:10 UTC, jonkoops approved these changes

2023-10-16 22:11 UTC, merged

2023-10-16 22:11 UTC, jonkoops commented
Thanks again @DimitriDR @Paul-Van-Uytvinck!