Improve ScheduledTask task-name handling
keycloak/keycloak pull request #23543
Opened 2023-09-26 20:15 UTC by thomasdarimont

This PR introduces a String getTaskName() default method to the ScheduledTask interface and adjusts callsites to use the implementation derived task-name where possible.

Previously, ScheduledTask names were passed around seperately, which lead to unhelpful debug messages.
We now give ScheduledTask implementations control over their task-name which allows for more flexible naming.

2023-09-26 20:21 UTC, thomasdarimont commented
While debugging ScheduledTask executions in Keycloak I noticed, that the debug log output of the executed tasks is quite inconsistent.

For instance the periodic scheduled task which propagates the LastSessionRefresh is shown like that in the debug log:
```
22:18:24,342 DEBUG Timer-0 [org.keycloak.services.scheduled.ScheduledTaskRunner] Executed scheduled task AbstractLastSessionRefreshStoreFactory$$Lambda$1570/0x00000008019108e0
```

Some other tasks were using explict task names derived from the getClass().getSimpleName() of the Task implementation which could be simplified a bit.

I just gave this a spin and with the changes from this PR we see:
```
22:17:31,974 DEBUG Timer-0 [org.keycloak.services.scheduled.ScheduledTaskRunner] Executed scheduled task PropagateLastSessionRefreshTask
```
and get rid of some redundant task names definitions.

2023-09-27 21:45 UTC, thomasdarimont commented on model/legacy-private/src/main/java/org/keycloak/storage/datastore/LegacyDatastoreProviderFactory.java
> +                    timer.schedule(new ClusterAwareScheduledTaskRunner(sessionFactory, task, interval), interval, task.getTaskName());
I just updated the example and incorporated your suggestion.

2023-10-31 18:51 UTC, pedroigor reviewed
@thomasdarimont What else we are missing to move forward?

2023-12-18 18:42 UTC, pedroigor commented
@thomasdarimont Hey, still interested in these changes? If so, please rebase and make sure to sign-off the commit.

2024-01-08 10:46 UTC, pedroigor approved these changes, later dismissed
@keycloak/store-maintainers LGTM.

2024-01-08 14:26 UTC, pedroigor reviewed
@thomasdarimont Test failures seem related.

2024-01-26 09:13 UTC, mhajas requested changes
Thank you for the PR @thomasdarimont! The change looks like a great improvement to our scheduled tasks. 

The CI is failing though, would you have time to have a look? Also, there is a conflict again, there were some changes related to the removal of `legacy` word from some places and in this PR there are some changes in affected files/modules.

2024-01-26 10:37 UTC, thomasdarimont commented
Thanks @mhajas for taking a look. I'll give this another spin over the weekend.

2024-01-29 10:32 UTC, thomasdarimont commented
@mhajas I gave this a spin and learned that the tests fail due to a NPE here:
https://github.com/keycloak/keycloak/actions/runs/7693017392/job/20961301376?pr=23543#step:4:1186

In some log messages I expect the RealmModel to be set, but on realmImport time this is not the case, as the events are fired too early in RealmManager here https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/services/managers/RealmManager.java#L610.

```java
// Refresh periodic sync tasks for configured storageProviders
StoreSyncEvent.fire(session, realm, false);
```       
this triggers `org.keycloak.storage.managers.UserStorageSyncManager.UserStorageClusterListener#eventReceived` which eventually yield the NPE when accessing `realm.getName();`.

I think we need to postpone `StoreSyncEvent.fire(session, realm, false);` until the realm is actually commited to the database.

Changing `StoreSyncEvent.fire(session, realm, false);`, seems to do the trick:
```java
session.getTransactionManager().enlistAfterCompletion(new AbstractKeycloakTransaction() {
    @Override
    protected void commitImpl() {
        StoreSyncEvent.fire(session, realm, false);
    }
});
```

2024-01-29 11:21 UTC, thomasdarimont commented
Needed to do the same (wrap in `enlistAfterCompletion`) in `org.keycloak.storage.UserStorageManager#onCreate`
See: https://github.com/keycloak/keycloak/compare/8c33562935e2b75b2dd23ab4a7add1913f155393..9d71edc40a5a9951aa464f8c19fae6efa0804186

2024-02-01 12:50 UTC, mhajas approved these changes
Thanks for the update @thomasdarimont! I like the change with `enlistAfterCompletion`. I am a little bit afraid of breaking something that relies on the fact the message is sent immediately but I couldn't find anything during review so I believe we should be ok.

@pedroigor Could you please re-review based on the latest updates?

2024-02-02 11:06 UTC, thomasdarimont commented
Thanks for the review @mhajas! Note that I only needed the realm in order to have the realm information for the log messages... here: https://github.com/keycloak/keycloak/pull/23543/files#diff-54be7294d9b4f077a162fe8f0e85a1daa389cace007e3cc2780e9b675ec12965R204

As it was not available before, it might be that most users didn't use the realm - so we could technically also just remove the realm and keep the old behavior without the `enlistAfterCompletion(...)`. However, I think having the Realm information available in the logs eases troubleshooting, e.g. "which provider sync failed in which realm failed?"

2024-02-02 12:10 UTC, mhajas commented
> Thanks for the review @mhajas! Note that I only needed the realm in order to have the realm information for the log messages... here: https://github.com/keycloak/keycloak/pull/23543/files#diff-54be7294d9b4f077a162fe8f0e85a1daa389cace007e3cc2780e9b675ec12965R204
> 
> As it was not available before, it might be that most users didn't use the realm - so we could technically also just remove the realm and keep the old behavior without the `enlistAfterCompletion(...)`. However, I think having the Realm information available in the logs eases troubleshooting, e.g. "which provider sync failed in which realm failed?"

Yes, I figured that out. To me, it seems incorrect to send the message across the cluster before the transaction is committed so I like the chosen approach regardless of the reason being only the logging message at the moment.

I was quite surprised when I learnt the user storage provider ComponentModel does not need to be in the database to schedule a task that loads data from the remote storage (because we rely on the data from the received event). I did not investigate this properly as your change is fixing it but if I understand correctly when the transaction for creating UserStorageProvider ComponentModel fails we schedule a task for loading the data for a non-existing storage provider and we are not able to cancel it as the task name contains the id of ComponentModel that is randomly generated.

2024-02-02 12:54 UTC, pedroigor approved these changes

2024-02-02 12:57 UTC, merged

2024-02-02 12:57 UTC, pedroigor commented
Thanks @thomasdarimont and @mhajas.