always allow browsing as we don't know the subgroups
keycloak/keycloak pull request #23657
Opened 2023-10-03 09:04 UTC by edewit

fixes: #23582

2023-10-10 12:41 UTC, ssilvert commented
@edewit I tried this out and navigation to subgroups looks good.  However, the other problem I mentioned in the issue is not fixed.  I have 11 groups.  When I bring up the "Join Group" dialog, I see the first 10 groups, 01 to 10.  Then when I go to the next page I should only see group 11.  But instead I see two groups, 01 and 11.

2023-10-10 12:42 UTC, ssilvert requested changes
See my other comment.

2023-10-12 00:10 UTC, ssilvert approved these changes
I changed my mind and approved this.  We can just fix the other issue in a new PR under https://github.com/keycloak/keycloak/issues/23707

2023-10-14 11:40 UTC, jonkoops approved these changes

2023-10-16 19:20 UTC, merged