operator: Replace dead documentation link
keycloak/keycloak pull request #23777
Opened 2023-10-06 09:35 UTC by pierreprinetti

Before this patch, the documentation link generated for the Operator page resulted in a 404 Not Found on Github pages.

With this change, the documentation link points to the "Operator" anchor in the Keycloak docs index. Note that the operator docs don't seem to be versioned on the Keycloak website.

Fixes #24143

2023-10-11 08:49 UTC, pierreprinetti commented
Rebased.

2023-10-19 09:25 UTC, pierreprinetti commented
Rebased.

2023-10-19 10:04 UTC, pierreprinetti commented
hmm, maybe I should ping someone. @jonkoops?

2023-10-19 10:08 UTC, jonkoops approved these changes
I am not a maintainer so I cannot merge this, but changes look good to me.

2023-10-19 10:14 UTC, pierreprinetti commented
@vmuzikar Is there anything else expected from me, before this PR can be merged?

2023-10-19 10:15 UTC, jonkoops commented
@pierreprinetti Please do not @ other team members, we're already pretty busy and this just adds more notifications for us. Your PR will be picked up when the maintainers have time to do so.

2023-10-19 10:16 UTC, jonkoops commented
Side-bar. Could you perhaps log an issue for this fix? This is something we might want to backport to the existing release, and we need an issue to track that.

2023-10-19 10:18 UTC, vmuzikar requested changes
@pierreprinetti Thanks for the PR!

Change LGTM but we need the GH Issue as mentioned by @jonkoops. Please see https://github.com/keycloak/keycloak/blob/main/CONTRIBUTING.md

2023-10-19 10:26 UTC, jonkoops commented
@vmuzikar issue us now linked, can you take another look?

2023-10-19 10:35 UTC, vmuzikar approved these changes

2023-10-19 11:53 UTC, merged