POC to see how we could extend the UI
keycloak/keycloak pull request #23772
Opened 2023-10-06 06:03 UTC by edewit

This is very crude and there are still open issues that need to be worked out

2023-12-15 13:22 UTC, hypery2k commented
would love to see this feature merged :D

2024-01-18 11:54 UTC, ssilvert requested changes

2024-01-18 11:54 UTC, ssilvert commented on common/src/main/java/org/keycloak/common/Profile.java
> +        UI_CUSTOMIZATION("UI customization spi", Type.EXPERIMENTAL),
Didn't we have another name for this?  Maybe it was something like, "Declarative UI?"

UI_CUSTOMIZATION is too broad of a term to describe what this does as there are other ways to customize the UI.

2024-01-18 11:54 UTC, ssilvert commented on js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
> +itemSaveSuccessful=Sucessful saved
I wouldn't change this for this first version, but in the future a developer would want to use the actual name of the item.

So for instance, `searchItem=Search item` would become `searchItem=Search {{itemName}}`

2024-01-19 12:49 UTC, ssilvert approved these changes

2024-01-22 08:19 UTC, merged

2024-04-04 14:47 UTC, smandlavdiya commented
> Initial version of the API that enables java developers to extend the admin UI

I was trying to add a new tab on client but unable to figure out how would i get client scope when i save and add values with oncreate()
any suggestions would be good to start please

2025-02-07 13:51 UTC, carlosrodovalho commented
I am experiencing an issue with my implementation of the ThemeUiTab class. The implementation works correctly when updating the realm attribute using the administrative interface. However, when I use the REST API to update the realm attribute, the new attribute is saved (as confirmed by checking Keycloak's database), but the input field in the administrative interface still displays the old value.

I have tried reloading Keycloak, but the interface does not load the new value from the database.

For reference, I implemented the example from the following repository: 
https://github.com/keycloak/keycloak-quickstarts/blob/latest/extension/extend-admin-console-spi/src/main/java/org/keycloak/admin/ui/ThemeUiTab.java