Correct the SyntaxError on old navigators
keycloak/keycloak pull request #23793
Opened 2023-10-06 13:56 UTC by ici-dev-gb

Closes #23743
https://github.com/keycloak/keycloak/issues/23743

2023-10-06 14:29 UTC, jonkoops requested changes

2023-10-06 14:29 UTC, jonkoops commented on services/src/main/resources/org/keycloak/protocol/oidc/endpoints/3p-cookies-step1.html
> +     // Encapsulate the code in an async to avoid syntax error
I don't think we need a comment for this, this is also exclusive to older versions of certain browsers.

```suggestion
```

2023-10-06 14:29 UTC, jonkoops commented on services/src/main/resources/org/keycloak/protocol/oidc/endpoints/3p-cookies-step1.html
> +      async function attemptCookie() {
I'd rather call this `checkStorageAccess()`, as the cookies are an implementation detail.
```suggestion
      async function checkStorageAccess() {
```

2023-10-06 14:29 UTC, jonkoops commented on services/src/main/resources/org/keycloak/protocol/oidc/endpoints/3p-cookies-step1.html
> +        window.parent.postMessage( isSupported ? "supported" : "unsupported", "*");
Can we get rid of these white-space changes?
```suggestion
        window.parent.postMessage(isSupported ? "supported" : "unsupported", "*");
```

2023-10-06 14:31 UTC, jonkoops commented
Normally we would not guarantee support for more than the last two major versions of Safari. But considering this a very mission critical path for clients and the fix doesn't compromise the code quality, I think we can make an exception here.

2023-10-08 10:44 UTC, jonkoops requested changes

2023-10-08 10:44 UTC, jonkoops commented on services/src/main/resources/org/keycloak/protocol/oidc/endpoints/3p-cookies-step1.html
> +      attemptCookie();
This function no longer exists, it should be calling `checkStorageAccess()` instead.
```suggestion
      checkStorageAccess();
```

2023-10-10 14:52 UTC, jonkoops approved these changes

2023-10-10 15:45 UTC, ahus1 approved these changes
Approving as of @jonkoops's review

2023-10-12 09:28 UTC, merged