Update fips.adoc
keycloak/keycloak pull request #24056
Opened 2023-10-17 12:17 UTC by stephenbjm

Fixed some typographical and language usage issues.

2023-10-18 11:18 UTC, mposolda commented
@stephenbjm Thanks for the PR!

@andymunro Could you please review this PR?

2023-10-18 13:37 UTC, andymunro commented on docs/guides/server/fips.adoc
> +however BouncyCastle also provides a FIPS validated version of its library. The FIPS validated BouncyCastle library cannot be shipped with Keycloak due to license constraints and
```suggestion
however,  BouncyCastle also provides a FIPS validated version of its library. The FIPS validated BouncyCastle library cannot be shipped with Keycloak due to license constraints and
```

2023-10-18 13:38 UTC, andymunro commented on docs/guides/server/fips.adoc
> +PKCS12 keystore can be generated with OpenJDK 17 Java on RHEL 9 in the standard way. For instance the following command can be used to generate the keystore:
```suggestion
PKCS12 keystore can be generated with OpenJDK 17 Java on RHEL 9 in the standard way. For instance,  the following command can be used to generate the keystore:
```

2023-10-18 13:38 UTC, andymunro commented on docs/guides/server/fips.adoc
> +When the system is in FIPS mode, the default `java.security` file is changed in order to use FIPS enabled security providers, so no additional configuration is needed. Additionally, in the PKCS12 key
```suggestion
When the system is in FIPS mode, the default `java.security` file is changed in order to use FIPS enabled security providers, so no additional configuration is needed. Additionally, in the PKCS12 keystore, you can store PBE (password-based encryption) keys simply by using the keytool command, which makes it ideal for using it with Keycloak KeyStore Vault and/or to store configuration properties in the KeyStore Config Source. For more details, see the <@links.server id="configuration"/> and the <@links.server id="vault"/>.
```

2023-10-18 13:41 UTC, andymunro requested changes
@mposolda a few changes to suggest.

2023-10-19 12:56 UTC, andymunro approved these changes

2023-10-20 08:01 UTC, mposolda commented
@stephenbjm @andymunro Thanks for the review and updates!

2023-10-20 08:02 UTC, mposolda approved these changes

2023-10-20 08:02 UTC, merged