Fix for issue #24035
keycloak/keycloak pull request #24154
Opened 2023-10-19 15:08 UTC by himanshi1099

Added 'navigate(toGroups({ realm }));' to 'DeleteGroup' component and rename 'GroupsModal' component in GroupTree.tsx

2023-10-19 15:10 UTC, himanshi1099 commented
@ssilvert @edewit @jonkoops I have raised PR for issue #24035. Can you please check. Thanks in Advance

2023-10-19 15:50 UTC, jonkoops commented
@himanshi1099 please do not @ team members as it causes more notifications and noise for us. We will get to your PR when we can.

2023-10-19 16:31 UTC, ssilvert commented
@himanshi1099 Please work with @edewit on this.

Also, I have updated your initial comment on this PR as per our [contribution guidelines](https://github.com/keycloak/keycloak/blob/main/CONTRIBUTING.md#commit-messages-and-issue-linking).

2023-10-20 07:21 UTC, edewit requested changes
I think it would be better to change the refresh in `GroupsSection` instead

2023-10-20 07:21 UTC, edewit commented on js/apps/admin-ui/src/groups/components/GroupTree.tsx
>              refresh();
The original `refresh` no longer makes sense when we navigate away before.

2023-10-20 09:56 UTC, edewit approved these changes

2023-10-20 10:18 UTC, merged