Improved credential select form accessibility
keycloak/keycloak pull request #24416
Opened 2023-10-31 10:01 UTC by Paul-Van-Uytvinck

Closes https://github.com/keycloak/keycloak/issues/24412

2023-10-31 11:16 UTC, ahus1 commented
@agagancarczyk - I know you've been into accessibility, would you mind to have a look at this issue and pull request?

2023-10-31 11:51 UTC, jonkoops commented
Thanks for this enhancement @Paul-Van-Uytvinck, it's really important that we get the accessibility of this right. I was thinking, perhaps the better option here would be to use more semantically valid controls such as buttons that submit the form. For example:

```html
<form>
  <button type="submit" name="authenticator" value="google-authenticator">
    Google Authenticator
  </button>
  <button type="submit" name="authenticator" value="microsoft-authenticator">
    Microsoft Authenticator
  </button>
</form>
```

This will submit the form with the appropriate `value` attached to the button when clicked. This also removes the need to have any JavaScript on the page. I've created [an example](https://stackblitz.com/edit/web-platform-6xfovm?file=index.html) to see how this works, let me know what you think.

2023-10-31 12:36 UTC, Paul-Van-Uytvinck commented
> Thanks for this enhancement @Paul-Van-Uytvinck, it's really important that we get the accessibility of this right. I was thinking, perhaps the better option here would be to use more semantically valid controls such as buttons that submit the form. For example:
> 
> ```
> <form>
>   <button type="submit" name="authenticator" value="google-authenticator">
>     Google Authenticator
>   </button>
>   <button type="submit" name="authenticator" value="microsoft-authenticator">
>     Microsoft Authenticator
>   </button>
> </form>
> ```
> 
> This will submit the form with the appropriate `value` attached to the button when clicked. This also removes the need to have any JavaScript on the page. I've created [an example](https://stackblitz.com/edit/web-platform-6xfovm?file=index.html) to see how this works, let me know what you think.

I was not sure if div was a strong preference upstream or not. Buttons would be for the best indeed! I tried replacing div with button in the browser dev tools and some css adjustments would be necessary for the UI to remain the exact same after we change the tag to button.

2023-10-31 12:43 UTC, jonkoops commented
> I was not sure if div was a strong preference upstream or not. Buttons would be for the best indeed! I tried replacing div with button in the browser dev tools and some css adjustments would be necessary for the UI to remain the exact same after we change the tag to button.

I think this was simply done at the time because the author was not aware this was an option, or did not want to deal with additional styling. Doing some CSS changes it totally fine, just be sure it works consistently across supported browser targets (Chrome, Firefox, Edge and Safari).

2023-10-31 15:11 UTC, Paul-Van-Uytvinck commented
> > I was not sure if div was a strong preference upstream or not. Buttons would be for the best indeed! I tried replacing div with button in the browser dev tools and some css adjustments would be necessary for the UI to remain the exact same after we change the tag to button.
> 
> I think this was simply done at the time because the author was not aware this was an option, or did not want to deal with additional styling. Doing some CSS changes it totally fine, just be sure it works consistently across supported browser targets (Chrome, Firefox, Edge and Safari).

Tested in all 4 browsers

2023-11-01 12:28 UTC, jonkoops commented on themes/src/main/resources/theme/base/login/webauthn-authenticate.ftl
> +                                <button id="kc-webauthn-authenticator" class="${properties.kcSelectAuthListItemClass!}">
Just realized these `id` attributes are likely not unique, as this is inside of a loop. We don't have to fix this now, so I logged a separate issue for it (#24462).

2023-11-01 12:40 UTC, jonkoops requested changes
LG

2023-11-01 12:40 UTC, jonkoops commented on themes/src/main/resources/theme/base/login/select-authenticator.ftl
>                  <input type="hidden" id="authexec-hidden-input" name="authenticationExecution" />
If the aforementioned changes are made this hidden input can be safely removed.

2023-11-01 13:53 UTC, Paul-Van-Uytvinck commented on themes/src/main/resources/theme/base/login/webauthn-authenticate.ftl
> +                                <button id="kc-webauthn-authenticator" class="${properties.kcSelectAuthListItemClass!}">
Ah you are right, I thought we could click the key when several configured. I will remove it

2023-11-01 15:03 UTC, jonkoops approved these changes
LGTM, let's see what the tests do.

2023-11-16 09:49 UTC, jonkoops commented
@Paul-Van-Uytvinck we can get this merged, can you squash your commits and [sign off on them](https://github.com/keycloak/keycloak/pull/24416/checks?check_run_id=18739116935)?

2023-11-16 13:39 UTC, Paul-Van-Uytvinck commented
> @Paul-Van-Uytvinck we can get this merged, can you squash your commits and [sign off on them](https://github.com/keycloak/keycloak/pull/24416/checks?check_run_id=18739116935)?

I added my Signed-off-by line to every commit in this branch. We can squash the moment we merge, no? Or did you mean squash all commits locally?

2023-12-08 16:42 UTC, ahus1 approved these changes
Approving as of @jonkoops's review. Thank you for making the front end more accessible!

2023-12-08 16:42 UTC, merged