Localize Spanish language.
keycloak/keycloak pull request #24467
Opened 2023-11-01 14:51 UTC by NeftaliYagua

First time I am going to contribute to this project, my changes are small, just contributing the phrases from the localization dictionary for the Spanish language.

2023-11-01 14:58 UTC, jonkoops commented
Thanks for your PR. We require a native speaker to review PRs that change localizations before we merge this in. If you could get another native Spanish speaker to review your code then we can get this landed.

2023-11-01 15:28 UTC, NeftaliYagua commented
I am a native Spanish speaker, I don't have anyone to vouch for me, but I have contributions to localization for Ubuntu since 2013. That should be enough, however, if you want I can examine it again and see if there are any details to examine.
https://translations.launchpad.net/~neftaliyagua

2023-11-01 17:48 UTC, jonkoops requested changes

2023-11-01 17:48 UTC, jonkoops commented on themes/src/main/resources-community/theme/base/account/messages/messages_es.properties
> +
This should already be the default, see #21755. You should be able to safely remove this.
```suggestion
```

2023-11-01 17:48 UTC, jonkoops commented on themes/src/main/resources-community/theme/base/admin/messages/messages_es.properties
> +
```suggestion
```

2023-11-01 17:48 UTC, jonkoops commented on themes/src/main/resources-community/theme/base/email/messages/messages_es.properties
> +
```suggestion
```

2023-11-01 17:48 UTC, jonkoops commented on themes/src/main/resources-community/theme/base/login/messages/messages_es.properties
> +
```suggestion
```

2023-11-01 17:48 UTC, jonkoops commented on themes/src/main/resources-community/theme/keycloak.v2/account/messages/messages_es.properties
> +# encoding: utf-8
```suggestion
```

2023-11-01 17:53 UTC, NeftaliYagua commented
I still need a few words from the admin, but there would be less to add. As soon as I have another breath I'll try to complete it, and I'll send another pull as soon as it's ready.

2023-11-01 20:03 UTC, jonkoops submitted a review, later dismissed
Looks good to me code-wise, I've asked some of my Spanish speaking colleagues to take a look as well.

2023-11-02 08:41 UTC, jonkoops commented
@NeftaliYagua no need to keep rebasing the PR on `main`, that will just cause more runs on CI and create additional notifications for us.

2023-11-02 10:05 UTC, rmartinc requested changes
Thanks @NeftaliYagua for the translations! Just a few suggestions...

2023-11-02 10:05 UTC, rmartinc commented on themes/src/main/resources-community/theme/keycloak.v2/account/messages/messages_es.properties
> +unShareSuccess=Recurso sin tener éxito.
`Recurso descompartido con éxito.`

2023-11-02 10:05 UTC, rmartinc commented on themes/src/main/resources-community/theme/keycloak.v2/account/messages/messages_es.properties
> +link=Cuenta de enlace
`Vincular cuenta`

2023-11-02 10:05 UTC, rmartinc commented on themes/src/main/resources-community/theme/keycloak.v2/account/messages/messages_es.properties
> +unLink=Cuenta de no unk
`Desvincular cuenta`

2023-11-02 10:05 UTC, rmartinc commented on themes/src/main/resources-community/theme/keycloak.v2/account/messages/messages_es.properties
> +error-username-invalid-character='' {0} '' contiene carácter inválido.
All to `''{0}''`.

2023-11-02 10:05 UTC, rmartinc commented on themes/src/main/resources-community/theme/keycloak.v2/account/messages/messages_es.properties
> +path=Camino
` Ruta`

2023-11-03 12:41 UTC, Aboullos requested changes

2023-11-03 12:41 UTC, Aboullos commented on themes/src/main/resources-community/theme/base/login/messages/messages_es.properties
> +emailUpdateConfirmationSent=Se ha enviado un correo electrónico de confirmación a {0}.Debe seguir las instrucciones del primero para completar la actualización del correo electrónico.
```suggestion
emailUpdateConfirmationSent=Se ha enviado un correo electrónico de confirmación a {0}. Debe seguir las instrucciones de este para completar la actualización del correo electrónico.
```

2023-11-03 12:41 UTC, Aboullos commented on themes/src/main/resources-community/theme/base/login/messages/messages_es.properties
> +displayUnsupported=Tipo de visualización solicitado sin apoyo
```suggestion
displayUnsupported=Tipo de visualización solicitado no soportado

2023-11-03 12:41 UTC, Aboullos commented on themes/src/main/resources-community/theme/base/login/messages/messages_es.properties
> +phoneNumberVerified=Número de teléfono Verificado
```suggestion
phoneNumberVerified=Número de teléfono verificado
```

2023-11-03 12:41 UTC, Aboullos commented on themes/src/main/resources-community/theme/base/login/messages/messages_es.properties
> +logoutOtherSessions=Firme de otros dispositivos
```suggestion
logoutOtherSessions=Cerrar sesión en otros dispositivos
```

2023-11-03 12:41 UTC, Aboullos commented on themes/src/main/resources-community/theme/base/login/messages/messages_es.properties
> +addressScopeConsentText=DIRECCIÓN
```suggestion
addressScopeConsentText=Dirección
```

2023-11-03 12:41 UTC, Aboullos commented on themes/src/main/resources-community/theme/base/account/messages/messages_es.properties
> +addressScopeConsentText=DIRECCIÓN
```suggestion
addressScopeConsentText=Dirección
```

2023-11-03 12:41 UTC, Aboullos commented on themes/src/main/resources-community/theme/base/login/messages/messages_es.properties
> +oauth2DeviceExpiredUserCodeMessage=El código ha expirado.Vuelva a su dispositivo e intente conectarse nuevamente.
```suggestion
oauth2DeviceExpiredUserCodeMessage=El código ha expirado. Vuelva a su dispositivo e intente conectarse nuevamente.
```

2023-11-03 12:41 UTC, Aboullos commented on themes/src/main/resources-community/theme/base/login/messages/messages_es.properties
> +error-user-attribute-read-only=Este campo solo se lee.
```suggestion
error-user-attribute-read-only=Este campo es de solo lectura.
```

2023-11-03 12:41 UTC, Aboullos commented on themes/src/main/resources-community/theme/base/login/messages/messages_es.properties
> +federatedIdentityUnmatchedEssentialClaimMessage=El token de identificación emitido por el proveedor de identidad no coincide con el reclamo esencial configurado.Póngase en contacto con su administrad
```suggestion
federatedIdentityUnmatchedEssentialClaimMessage=El token de identificación emitido por el proveedor de identidad no coincide con el reclamo esencial configurado. Póngase en contacto con su administrador.
```

2023-11-03 12:41 UTC, Aboullos commented on themes/src/main/resources-community/theme/base/login/messages/messages_es.properties
> +confirmLinkIdpTitle=la cuenta ya existe
```suggestion
confirmLinkIdpTitle=La cuenta ya existe
```

2023-11-03 12:41 UTC, Aboullos commented on themes/src/main/resources-community/theme/base/login/messages/messages_es.properties
> +delegationFailedHeader=Error de inicio de sesion
```suggestion
delegationFailedHeader=Error de inicio de sesión
```

2023-11-03 12:41 UTC, Aboullos commented on themes/src/main/resources-community/theme/base/login/messages/messages_es.properties
> +standardFlowDisabledMessage=El cliente no puede iniciar el inicio de sesión del navegador con Respuesta_Type dada.El flujo estándar está deshabilitado para el cliente.
```suggestion
standardFlowDisabledMessage=El cliente no puede iniciar el inicio de sesión del navegador con el tipo de respuesta dado. El flujo estándar está deshabilitado para el cliente.
```

2023-11-03 12:41 UTC, Aboullos commented on themes/src/main/resources-community/theme/base/login/messages/messages_es.properties
> +implicitFlowDisabledMessage=El cliente no puede iniciar el inicio de sesión del navegador con Respuesta_Type dada.El flujo implícito está deshabilitado para el cliente.
```suggestion
implicitFlowDisabledMessage=El cliente no puede iniciar el inicio de sesión del navegador con el tipo de respuesta dado. El flujo implícito está deshabilitado para el cliente.
```

2023-11-03 12:41 UTC, Aboullos commented on themes/src/main/resources-community/theme/base/login/messages/messages_es.properties
> +identityProviderLinkSuccess=Verificó con éxito su correo electrónico.Vuelva a su navegador original y continúe allí con el inicio de sesión.
```suggestion
identityProviderLinkSuccess=Verificó con éxito su correo electrónico. Vuelva a su navegador original y continúe allí con el inicio de sesión.
```

2023-11-03 12:41 UTC, Aboullos commented on themes/src/main/resources-community/theme/base/login/messages/messages_es.properties
> +differentUserAuthenticated=Ya está autenticado como un usuario diferente '' {0} '' en esta sesión.Por favor firme primero.
```suggestion
differentUserAuthenticated=Ya está autenticado como un usuario diferente ''{0}'' en esta sesión. Por favor cierre sesión primero.
```

2023-11-03 12:41 UTC, Aboullos commented on themes/src/main/resources-community/theme/base/login/messages/messages_es.properties
> +doX509Login=Se registrará como \:
```suggestion
doX509Login=Se registrará como\:
```

2023-11-03 12:41 UTC, Aboullos commented on themes/src/main/resources-community/theme/base/login/messages/messages_es.properties
> +clientCertificate=Certificado de cliente X509 \:
```suggestion
clientCertificate=Certificado de cliente X509\:
```

2023-11-03 12:41 UTC, Aboullos commented on themes/src/main/resources-community/theme/base/login/messages/messages_es.properties
> +console-verify-email=Debe verificar su dirección de correo electrónico.Enviamos un correo electrónico a {0} que contiene un código de verificación.Ingrese este código en la entrada a continuación.
```suggestion
console-verify-email=Debe verificar su dirección de correo electrónico. Enviamos un correo electrónico a {0} que contiene un código de verificación. Ingrese este código en la entrada a continuación.
```

2023-11-03 12:41 UTC, Aboullos commented on themes/src/main/resources-community/theme/base/login/messages/messages_es.properties
> +saml.post-form.js-disabled=JavaScript está deshabilitado.Recomendamos encarecidamente habilitarlo.Haga clic en el botón de abajo para continuar.
```suggestion
saml.post-form.js-disabled=JavaScript está deshabilitado. Recomendamos encarecidamente habilitarlo. Haga clic en el botón de abajo para continuar.
```

2023-11-03 12:41 UTC, Aboullos commented on themes/src/main/resources-community/theme/base/login/messages/messages_es.properties
> +auth-username-form-help-text=Comience Iniciar sesión ingresando su nombre de usuario
```suggestion
auth-username-form-help-text=Comience el inicio de sesión ingresando su nombre de usuario
```

2023-11-03 12:41 UTC, Aboullos commented on themes/src/main/resources-community/theme/base/login/messages/messages_es.properties
> +recovery-code-config-warning-message=Asegúrese de imprimir, descargarlos o copiarlos a un Administrador de contraseñas y mantenerlos Guardar.Cancelar esta configuración eliminará estos códigos de rec
```suggestion
recovery-code-config-warning-message=Asegúrese de imprimir, descargarlos o copiarlos a un administrador de contraseñas y mantenerlos seguros. Cancelar esta configuración eliminará estos códigos de recuperación de su cuenta.
```

2023-11-03 12:41 UTC, Aboullos commented on themes/src/main/resources-community/theme/base/login/messages/messages_es.properties
> +webauthn-unsupported-browser-text=WebAuthn no es compatible con este navegador.Pruebe con otro o comuníquese con su administrador.
```suggestion
webauthn-unsupported-browser-text=WebAuthn no es compatible con este navegador. Pruebe con otro o comuníquese con su administrador.
```

2023-11-03 12:41 UTC, Aboullos commented on themes/src/main/resources-community/theme/base/login/messages/messages_es.properties
> +finalDeletionConfirmation=Si elimina su cuenta, no se puede restaurar.Para mantener su cuenta, haga clic en Cancelar.
```suggestion
finalDeletionConfirmation=Si elimina su cuenta, no se puede restaurar. Para mantener su cuenta, haga clic en Cancelar.
```

2023-11-03 12:41 UTC, Aboullos commented on themes/src/main/resources-community/theme/keycloak.v2/account/messages/messages_es.properties
> +needAccessRights=No tiene derechos de acceso a esta solicitud.Póngase en contacto con su administrador.
```suggestion
needAccessRights=No tiene derechos de acceso a esta solicitud. Póngase en contacto con su administrador.
```

2023-11-03 12:41 UTC, Aboullos commented on themes/src/main/resources-community/theme/keycloak.v2/account/messages/messages_es.properties
> +loadingMessage=Carga de consola de cuentas ...
```suggestion
loadingMessage=Cargando consola de cuentas ...
```

2023-11-03 12:41 UTC, Aboullos commented on themes/src/main/resources-community/theme/keycloak.v2/account/messages/messages_es.properties
> +unknownUser=Anónima
```suggestion
unknownUser=Anónimo
```

2023-11-03 12:41 UTC, Aboullos commented on themes/src/main/resources-community/theme/keycloak.v2/account/messages/messages_es.properties
> +selectLocale=Seleccione un local
```suggestion
selectLocale=Seleccione una ubicación
```

2023-11-03 12:41 UTC, Aboullos commented on themes/src/main/resources-community/theme/keycloak.v2/account/messages/messages_es.properties
> +signOutWarning=Registrar la sesión?
```suggestion
signOutWarning=Cerrar la sesión?
```

2023-11-03 12:41 UTC, Aboullos commented on themes/src/main/resources-community/theme/keycloak.v2/account/messages/messages_es.properties
> +signedInDevices=Firmado en dispositivos
```suggestion
signedInDevices=Dispositivos conectados
```

2023-11-03 12:41 UTC, Aboullos commented on themes/src/main/resources-community/theme/keycloak.v2/account/messages/messages_es.properties
> +recentlyUsedDevicesExplanation=Los dispositivos utilizados en el último mes, pero actualmente no inician sesión.
```suggestion
recentlyUsedDevicesExplanation=Los dispositivos utilizados en el último mes, pero que actualmente no están conectados.
```

2023-11-03 12:41 UTC, Aboullos commented on themes/src/main/resources-community/theme/keycloak.v2/account/messages/messages_es.properties
> +lastAccess=Ultimo acceso
```suggestion
lastAccess=Ultimo acceso
```
```suggestion
lastAccess=Último acceso
```

2023-11-03 12:41 UTC, Aboullos commented on themes/src/main/resources-community/theme/keycloak.v2/account/messages/messages_es.properties
> +expires=Expirar
```suggestion
expires=Expira
```

2023-11-03 12:41 UTC, Aboullos commented on themes/src/main/resources-community/theme/keycloak.v2/account/messages/messages_es.properties
> +unShareAllConfirm=¿Estás seguro de que quieres eliminar completamente todas las acciones?
```suggestion
unShareAllConfirm=¿Estás seguro de que quieres descompartir todos los recursos?
```

2023-11-03 12:41 UTC, Aboullos commented on themes/src/main/resources-community/theme/keycloak.v2/account/messages/messages_es.properties
> +baseUrl=Url
```suggestion
baseUrl=URL
```

2023-11-03 12:41 UTC, Aboullos commented on themes/src/main/resources-community/theme/keycloak.v2/account/messages/messages_es.properties
> +removeModalMessage=Esto eliminará el permiso de acceso otorgado actualmente para {0}.Deberá otorgar acceso nuevamente si desea usar esta aplicación.
```suggestion
removeModalMessage=Esto eliminará el permiso de acceso otorgado actualmente para {0}.Deberá otorgar acceso nuevamente si desea usar esta aplicación.
```
```suggestion
removeModalMessage=Esto eliminará el permiso de acceso otorgado actualmente para {0}. Deberá otorgar acceso nuevamente si desea usar esta aplicación.
```

2023-11-03 12:41 UTC, Aboullos commented on themes/src/main/resources-community/theme/keycloak.v2/account/messages/messages_es.properties
> +infoMessage=Al hacer clic en 'Eliminar acceso', eliminará los permisos otorgados de esta aplicación.Esta aplicación ya no usará su información.
```suggestion
infoMessage=Al hacer clic en 'Eliminar acceso', eliminará los permisos otorgados de esta aplicación. Esta aplicación ya no usará su información.
```

2023-11-03 12:41 UTC, Aboullos commented on themes/src/main/resources-community/theme/keycloak.v2/account/messages/messages_es.properties
> +applicationType=Tipo de aplicacion
```suggestion
applicationType=Tipo de aplicación
```

2023-11-03 12:41 UTC, Aboullos commented on themes/src/main/resources-community/theme/keycloak.v2/account/messages/messages_es.properties
> +deleteAccountWarning=Esto es irreversible.Todos sus datos serán destruidos permanentemente e irrrendibles.
```suggestion
deleteAccountWarning=Esto es irreversible. Todos sus datos serán permanentemente destruidos  e irrecuperables.
```

2023-11-03 12:41 UTC, Aboullos commented on themes/src/main/resources-community/theme/keycloak.v2/account/messages/messages_es.properties
> +noGroupsText=No te unes en ningún grupo
```suggestion
noGroupsText=No estás unido a ningún grupo
```

2023-11-03 17:42 UTC, Aboullos requested changes

2023-11-03 17:42 UTC, Aboullos commented on themes/src/main/resources-community/theme/base/account/messages/messages_es.properties
> +updatePasswordMessage=Una contraseña segura contiene una combinación de números, letras y símbolos.Es difícil de adivinar, no se parece a una palabra real y solo se usa para esta cuenta.
```suggestion
updatePasswordMessage=Una contraseña segura contiene una combinación de números, letras y símbolos. Es difícil de adivinar, no se parece a una palabra real y solo se usa para esta cuenta.
```

2023-11-03 17:42 UTC, Aboullos commented on themes/src/main/resources-community/theme/base/login/messages/messages_es.properties
> +expiredActionTokenSessionExistsMessage=Acción expirada.Comience de nuevo.
```suggestion
expiredActionTokenSessionExistsMessage=Acción expirada. Comience de nuevo.
```

2023-11-03 17:42 UTC, Aboullos commented on themes/src/main/resources-community/theme/keycloak.v2/account/messages/messages_es.properties
> +recovery-codes-number-remaining={0} Códigos de recuperación restantes
```suggestion
recovery-codes-number-used={0} códigos de recuperación utilizados
recovery-codes-number-remaining={0} códigos de recuperación restantes
```

2023-11-04 19:03 UTC, NeftaliYagua commented on themes/src/main/resources-community/theme/base/account/messages/messages_es.properties
> +noResourcesSharedWithYou=No hay recursos compartidos con usted
Muchas gracias

2023-11-05 20:32 UTC, NeftaliYagua commented
Suggestions ready! Pull is ready for merge!

2023-11-06 09:39 UTC, Aboullos commented
There are still some change requests to be made

2023-11-08 17:55 UTC, NeftaliYagua commented on themes/src/main/resources-community/theme/keycloak.v2/account/messages/messages_es.properties
> +unLink=Cuenta de no unk
Fixed!

2023-11-08 17:55 UTC, NeftaliYagua commented on themes/src/main/resources-community/theme/keycloak.v2/account/messages/messages_es.properties
> +link=Cuenta de enlace
Done!

2023-11-08 17:55 UTC, NeftaliYagua commented on themes/src/main/resources-community/theme/base/account/messages/messages_es.properties
> +scopes=Escopas
Done!

2023-11-08 17:55 UTC, NeftaliYagua commented on themes/src/main/resources-community/theme/base/account/messages/messages_es.properties
> +access-denied-when-idp-auth=Acceso negado al autenticar con {0}
Done!

2023-11-08 17:56 UTC, NeftaliYagua commented on themes/src/main/resources-community/theme/base/account/messages/messages_es.properties
> +consentDenied=Consentimiento negado.
Done!

2023-11-08 17:56 UTC, NeftaliYagua commented on themes/src/main/resources-community/theme/base/account/messages/messages_es.properties
> +role_manage-consent=Gestionar los consentimiento
Done!

2023-11-08 17:56 UTC, NeftaliYagua commented on themes/src/main/resources-community/theme/base/account/messages/messages_es.properties
> +accountManagementWelcomeMessage=Bienvenido a KeyCloak Cuenta Management
Done!

2023-11-08 17:57 UTC, NeftaliYagua commented
I rest from this project, in your hands I leave my contributions.

2023-11-14 16:46 UTC, jonkoops commented
@Aboullos @rmartinc What do we want to do with this PR? It seems the author is no longer interested in landing this, so I am inclined to close it unless someone steps up to try and get it in a mergable state.

2023-11-20 08:49 UTC, Aboullos commented
@jonkoops I could check it

2023-11-20 08:54 UTC, rmartinc commented
@Aboullos! If you want to continue with the PR just work on top @NeftaliYagua commit and perform the rest of the changes in a second commit. This way we maintain all the authors. :smile: Thanks a lot!

2023-11-27 04:04 UTC, NeftaliYagua commented
I agree, I would love to continue with the PR but I maintain many other free software projects that do not give me space to spend too much time on one, please try to take advantage of what you can from my contribution, in favor of the community and do what that is most convenient for the good of the project. I'm outside, I wash my hands.

2023-11-27 08:27 UTC, jonkoops commented
Considering the previous comments I will go ahead and close this PR, if anyone wants to continue the work they can take this PR as an starting point and continue from there.

2023-11-27 08:27 UTC, closed without merging