set the searching state when we actually are
keycloak/keycloak pull request #24499
Opened 2023-11-02 14:08 UTC by edewit

fixes: #24430

2023-11-02 14:38 UTC, jonkoops submitted a review, later dismissed

2023-11-14 16:35 UTC, jonkoops requested changes

2023-11-21 16:21 UTC, jonkoops requested changes

2023-11-21 16:21 UTC, jonkoops commented on js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
> +noSearchResultsInstructions=Click on the search bar above to search agian
```suggestion
noSearchResultsInstructions=Click on the search bar above to search again
```

2023-11-22 10:46 UTC, agagancarczyk approved these changes, later dismissed

2023-11-23 23:56 UTC, jonkoops approved these changes, later dismissed

2023-12-07 11:06 UTC, jonkoops approved these changes

2023-12-07 11:06 UTC, merged