Upgrading notes for user profile
keycloak/keycloak pull request #24492
Opened 2023-11-02 11:24 UTC by mposolda

closes #24491

2023-11-02 18:45 UTC, andymunro commented on docs/documentation/release_notes/topics/23_0_0.adoc
> +ideally with label `area/user-profile`. It is also recommended to check link:{upgradingguide_link}[{upgradingguide_name}]  with the migration changes for this
```suggestion
ideally with the label `area/user-profile`. It is also recommended to check the link:{upgradingguide_link}[{upgradingguide_name}]  with the migration changes for this
```

2023-11-02 18:48 UTC, andymunro commented on docs/documentation/upgrading/topics/keycloak/changes-23_0_0.adoc
> +are overriding the built-in implementation with your own `UserProfileProvider` implementation (however note that `UserProfileProvider` is unsupported SPI).
```suggestion
This release includes many fixes and updates that are related to user profile as we are working on promoting this feature from preview to officially supported.
Minor changes exist for the SPI such as the newly added method `boolean isEnabled(RealmModel realm)` on `UserProfileProvider` interface. Also
some user profile classes and some validator related classes (but not builtin validator implementations) were moved from `keycloak-server-spi-private` to
`keycloak-server-spi` module. However, the packages for java classes remain the same. You might be affected in some corner cases, such as when you
are overriding the built-in implementation with your own `UserProfileProvider` implementation However, note that `UserProfileProvider` is an unsupported SPI.
```

2023-11-02 18:49 UTC, andymunro requested changes
A few suggestions, @mposolda

2023-11-03 19:30 UTC, mposolda commented
@andymunro Thanks!

2023-11-06 10:19 UTC, pedroigor approved these changes

2023-11-06 10:19 UTC, merged