Update Social Identity Providers documentation (#24601)
keycloak/keycloak pull request #24603
Opened 2023-11-07 12:29 UTC by tondrusk

Resolves #24601 
- Update configuration steps
- Update pictures
- Sort Social Identity Providers alphabetically

2023-11-13 08:40 UTC, wojnarfilip commented
This is optional and subjective. I kinda liked how the images previously showed also a navigation and active realm as it was giving user some additional context. On the other hand I can also see argument that the current images without navigation look cleaner.

Not sure if we have some general recommendations for this.

2023-11-13 08:52 UTC, tondrusk commented
> This is optional and subjective. I kinda liked how the images previously showed also a navigation and active realm as it was giving user some additional context. On the other hand I can also see argument that the current images without navigation look cleaner.
> 
> Not sure if we have some general recommendations for this.

@wojnarfilip This is also currently inconsistent in the documentation. The OCP 3 and OCP 4 IdPs do not show navigation, unlike the rest of the social IdPs. I prefer the cleaner version, which shows just the important.

2023-11-13 12:43 UTC, wojnarfilip requested changes

2023-11-13 12:43 UTC, wojnarfilip commented on docs/documentation/server_admin/topics/identity-broker/social/microsoft.adoc
> +. In a separate browser tab, hhttps://portal.azure.com/#view/Microsoft_AAD_RegisteredApps/CreateApplicationBlade/quickStartType~/null/isMSAApp~/false[create a Microsoft app].
```suggestion
. In a separate browser tab, https://portal.azure.com/#view/Microsoft_AAD_RegisteredApps/CreateApplicationBlade/quickStartType~/null/isMSAApp~/false[create a Microsoft app].
```

Double h in https

2023-11-13 12:43 UTC, tondrusk commented on docs/documentation/server_admin/topics/identity-broker/social/microsoft.adoc
> +. In a separate browser tab, hhttps://portal.azure.com/#view/Microsoft_AAD_RegisteredApps/CreateApplicationBlade/quickStartType~/null/isMSAApp~/false[create a Microsoft app].
Good catch! Thanks!

2023-11-15 07:25 UTC, wojnarfilip approved these changes
LGTM.

2023-11-15 08:23 UTC, ahus1 commented
Thank you for the review. Giving it some more time for @andymunro to review it. 

Is this something that should be backported to KC22?

2023-11-16 08:31 UTC, miquelsi commented
> Is this something that should be backported to KC22?

Yes this should be backported to KC22, together with the testsuite changes.

2023-11-16 16:58 UTC, ahus1 approved these changes
Approving as of @wojnarfilip's review.

2023-11-16 16:58 UTC, merged

2023-11-16 16:59 UTC, andymunro commented on docs/documentation/server_admin/topics/identity-broker/social/facebook.adoc
> +. From the `Add provider` list, select `Facebook`.
```suggestion
. From the *Add provider* list, select *Facebook*.
```

2023-11-16 17:01 UTC, andymunro commented on docs/documentation/server_admin/topics/identity-broker/social/facebook.adoc
> +.. Select `Consumer`.
```suggestion
.. Select *Other*.
+
.Select an app type
image:images/meta-select-app-type.png[Select an app type]
+
.. Select *Consumer*.
```

2023-11-16 17:02 UTC, andymunro commented on docs/documentation/server_admin/topics/identity-broker/social/facebook.adoc
> +.. Enter the *Redirect URI's* value into the `Site URL` field and click *Save*.
```suggestion
.. Enter the *Redirect URI's* value into the *Site URL* field and click *Save*.
```

2023-11-16 17:03 UTC, andymunro commented on docs/documentation/server_admin/topics/identity-broker/social/facebook.adoc
> +. Enter the https://developers.facebook.com/docs/facebook-login/guides/access-tokens[`App ID` and `App Secret`] values from your Facebook app into the *Client ID* and *Client Secret* fields in {proje
```suggestion
.. Note the *App ID* and the *App Secret*.
. Enter the https://developers.facebook.com/docs/facebook-login/guides/access-tokens[*App ID* and *App Secret*] values from your Facebook app into the *Client ID* and *Client Secret* fields in {project_name}.
```

2023-11-16 17:03 UTC, ahus1 commented
@tondrusk - sorry for merging this too early. Please address  @andymunro's comments in a new PR once his review is complete.

2023-11-16 17:04 UTC, andymunro commented on docs/documentation/server_admin/topics/identity-broker/social/facebook.adoc
>  . Enter the required scopes into the *Default Scopes* field. By default, {project_name} uses the `email` scope. See https://developers.facebook.com/docs/graph-api[Graph API] for more information abou
```suggestion
. Enter the required scopes into the *Default Scopes* field. By default, {project_name} uses the *email*  scope. See https://developers.facebook.com/docs/graph-api[Graph API] for more information about Facebook scopes. 
```

2023-11-16 17:08 UTC, andymunro requested changes
Looks good, but the standard is to use *asterisks* for anything you see on the screen and `back ticks` for anything you type.
I made suggestions in the document, but realized it's better to just explain this guideline.