UX improvements
keycloak/keycloak pull request #24602
Opened 2023-11-07 12:27 UTC by hmlnarik

This PR delivers UI for transient users for brokering feature. For transient users:

- Label `Transient` is added next to the user name in user detail
- Logout from the session tab of a user detail removes the user. Thus the browser is redirected to user list after logout
- Deleting a transient user is done by user logout (which effectively removes the user)

TODO: Tests

Closes: #24279

2023-11-14 13:07 UTC, jonkoops requested changes
Couple of small nits, otherwise LGTM. Looks like there are some failing test though.

2023-11-14 13:07 UTC, jonkoops commented on js/apps/admin-ui/src/user/utils.ts
> +export const isLightweightUser = (userId?: String) =>
For primitive values in TypeScripts (e.g. `number`, `string`, etc), we use the lowercase variant.
```suggestion
export const isLightweightUser = (userId?: string) =>
```

2023-11-14 13:07 UTC, jonkoops commented on js/apps/admin-ui/src/user/EditUser.tsx
> +                        data-testid={"user-details-label-transient-user"}
String literals can be passed directly.
```suggestion
                        data-testid="user-details-label-transient-user"
```

2023-11-20 10:12 UTC, hmlnarik commented
I believe the PR is now ready to go, so switching from draft to full.
@jonkoops Thank you for the review, could you please re-review?

2023-11-20 17:45 UTC, jonkoops approved these changes
LGTM

2023-11-21 07:31 UTC, merged