Addressing Server Admin review comments
keycloak/keycloak pull request #24671
Opened 2023-11-09 21:18 UTC by andymunro

Closes #2463

@ahus1 @vaceksimon Can you verify this.   This addressed most issues you raised.

2023-11-09 21:31 UTC, ahus1 submitted a review, later dismissed
@andymunro - your PR references a GitHub issue which is not related to the PR. GitHub PRs can only reference GitHub issues, not internal JIRA issues. Please duplicate the JIRA issue to a public GitHub issue first so it is clear what you intent to change. 

UPDATE: the commit in this PR doesn't contain a signoff, please add this as well. See https://www.keycloak.org/2023/10/dco for the details.

2023-11-10 11:46 UTC, vaceksimon requested changes
After these corrections it's ready for merge. Good job Andy

2023-11-10 11:46 UTC, vaceksimon commented on docs/documentation/server_admin/topics/authentication/flows.adoc
> -Executions have a *⚙️* menu item (the gear icon) to configure the execution. It is also possible to add executions and sub-flows to sub-flows with the *Add step* and *Add flow* links.
I apologize for the incorrect comment I left on the gear icon on the Jira ticket. The gear menu item to configure the execution is still there, it's just not there for every single execution.

2023-11-10 11:46 UTC, vaceksimon commented on docs/documentation/server_admin/topics/authentication/flows.adoc
>  . Click *⚙️* (gear icon).
```suggestion
. Click *⚙️* (gear icon) menu of the *Conditional - Level Of Authentication*
```

2023-11-10 11:46 UTC, vaceksimon commented on docs/documentation/server_admin/topics/admin-cli.adoc
> +$ kcadm get "authentication/config/dd91611a-d25c-421a-87e2-227c18421833" -r demorealm
```suggestion
$ kcadm.sh get "authentication/config/dd91611a-d25c-421a-87e2-227c18421833" -r demorealm
```

2023-11-10 11:46 UTC, vaceksimon commented on docs/documentation/server_admin/topics/admin-cli.adoc
> +$ kcadm update "authentication/config/dd91611a-d25c-421a-87e2-227c18421833" -r demorealm -b '{"id":"dd91611a-d25c-421a-87e2-227c18421833","alias":"my_otp_config","config":{"x509-cert-auth.extendedkey
```suggestion
$ kcadm.sh update "authentication/config/dd91611a-d25c-421a-87e2-227c18421833" -r demorealm -b '{"id":"dd91611a-d25c-421a-87e2-227c18421833","alias":"my_otp_config","config":{"x509-cert-auth.extendedkeyusage":"","x509-cert-auth.mapper-selection.user-attribute-name":"usercertificate","x509-cert-auth.ocsp-responder-uri":"","x509-cert-auth.regular-expression":"(.*?)(?:$)","x509-cert-auth.crl-checking-enabled":"true","x509-cert-auth.confirmation-page-disallowed":"","x509-cert-auth.keyusage":"","x509-cert-auth.mapper-selection":"Custom Attribute Mapper","x509-cert-auth.crl-relative-path":"crl.pem","x509-cert-auth.crldp-checking-enabled":"false","x509-cert-auth.mapping-source-selection":"Match SubjectDN using regular expression","x509-cert-auth.ocsp-checking-enabled":""}}'
```

2023-11-10 11:46 UTC, vaceksimon commented on docs/documentation/server_admin/topics/admin-cli.adoc
> +$ kcadm delete "authentication/config/dd91611a-d25c-421a-87e2-227c18421833" -r demorealm
```suggestion
$ kcadm.sh delete "authentication/config/dd91611a-d25c-421a-87e2-227c18421833" -r demorealm
```

2023-11-10 11:46 UTC, vaceksimon commented on docs/documentation/server_admin/topics/authentication/otp-policies.adoc
> +. Click the *Policy* tab.
```suggestion
. Click the *Policies* tab.
```

2023-11-10 11:46 UTC, vaceksimon commented on docs/documentation/server_admin/topics/authentication/webauthn.adoc
>  . Click *Add step*.
```suggestion
```

2023-11-10 11:46 UTC, vaceksimon commented on docs/documentation/server_admin/topics/authentication/webauthn.adoc
> -. Click *Add*.
This step is perfectly fine and should stay. Step 2 on line 77 is supposed to be the one deleted

2023-11-10 11:46 UTC, vaceksimon commented on docs/documentation/server_admin/topics/users/proc-requiring-tac-agreement-at-registration.adoc
> +Click the *Flows* tab.
```suggestion
. Click the *Flows* tab.
```

2023-11-10 11:46 UTC, vaceksimon commented on docs/documentation/server_admin/images/user-profile-select-options-simple-i18n.png
The picture from an older version of Keycloak I had in mind was [user-profile-select-options-custom-validator.png](https://github.com/keycloak/keycloak/blob/main/docs/documentation/server_admin/images/user-profile-select-options-custom-validator.png). This picture is fine as it is.

2023-11-10 17:08 UTC, andymunro commented
@ahus1 @vaceksimon Comments addressed and signed off to correct Jira.

2023-11-13 08:29 UTC, ahus1 approved these changes, later dismissed
DCO looks good to me. Waiting for review of @vaceksimon

2023-11-13 12:54 UTC, vaceksimon approved these changes
LGTM! Ready to merge @ahus1

2023-11-13 13:23 UTC, andymunro commented
@ahus1 I can fix one more issue with this guide related to the Account Console broken link

2023-11-13 13:32 UTC, andymunro commented
@ahus1 I fixed that last broken link issue.  Ready to merge.

2023-11-13 14:47 UTC, ahus1 approved these changes
LGTM

2023-11-13 14:48 UTC, merged