Added missing dependencies to themes/pom.xml
keycloak/keycloak pull request #24682
Opened 2023-11-10 15:17 UTC by tsaarni

This PR adds dependency to `keycloak-admin-ui` and `keycloak-account-ui` modules. Both modules contribute files to `themes` and are therefore dependencies for `themes`

Close #24571, with the precondition that #24537 is also merged and would resolve concurrent node and pnpm install execution https://github.com/keycloak/keycloak/pull/24537#discussion_r1389486794

2023-11-10 15:18 UTC, tsaarni commented
Cc @ASzc @jonkoops

2023-11-13 15:21 UTC, ASzc requested changes
Seems to make sense to me. I imagine the reason there isn't a dependency defined already is because of optimization. The poms have have several instances of broken maven metadata, especially where the javascript stuff is concerned, which I'm not overly happy with, but would slightly speed up a build

2023-11-13 15:21 UTC, ASzc commented on themes/pom.xml
> +            <version>${project.version}</version>
A `<version>` is not required, because these two modules have versions specified in `keycloak-parent`'s dependencyManagement

2023-11-13 18:12 UTC, jonkoops approved these changes
I have no objection against merging this in, but we do need a maintainer to take a look at this.

2023-11-14 08:10 UTC, ahus1 approved these changes
Thank you, the changes make sense.

2023-11-14 08:11 UTC, merged