Idp pager UI
keycloak/keycloak pull request #24933
Opened 2023-11-22 14:39 UTC by edewit

2023-11-23 16:04 UTC, jonkoops requested changes

2023-11-23 16:04 UTC, jonkoops commented on js/apps/admin-ui/src/identity-providers/IdentityProvidersSection.tsx
> +    async () => adminClient.identityProviders.find({ max: 1 }),
No need to mark this as `async` as the function already returns a `Promise`.
```suggestion
    () => adminClient.identityProviders.find({ max: 1 }),
```

2023-11-23 16:04 UTC, jonkoops commented on js/apps/admin-ui/src/identity-providers/ManageOrderDialog.tsx
> +    async () => adminClient.identityProviders.find(),
No need for this to be `async`, there is already a Promise returned.
```suggestion
    () => adminClient.identityProviders.find(),
```

2023-11-23 16:04 UTC, jonkoops commented on js/apps/admin-ui/src/identity-providers/ManageOrderDialog.tsx
> +    async () => adminClient.identityProviders.find(),
Should we be passing in a `max` here as well? Like the call in IdentityProvidersSection?

2023-11-27 11:53 UTC, edewit commented on js/apps/admin-ui/src/identity-providers/IdentityProvidersSection.tsx
> +    async () => adminClient.identityProviders.find({ max: 1 }),
This query is just to see if there are any, if not we how the tiles otherwise we can query the first 10

2023-11-27 11:56 UTC, edewit commented on js/apps/admin-ui/src/identity-providers/IdentityProvidersSection.tsx
> +    const providers = await adminClient.identityProviders.find(params);
No, when we are executing this only when there are providers

2023-11-27 13:29 UTC, jonkoops commented on js/apps/admin-ui/src/identity-providers/ManageOrderDialog.tsx
> +    async () => adminClient.identityProviders.find(),
This list can be quite long for some users right? Should we not instead be doing this sorting in the REST API itself?

2023-11-28 11:51 UTC, jonkoops approved these changes, later dismissed

2023-12-11 13:35 UTC, jonkoops approved these changes

2023-12-11 13:38 UTC, merged