Localize Spanish language
keycloak/keycloak pull request #25048
Opened 2023-11-27 12:21 UTC by Aboullos

Continuation from https://github.com/keycloak/keycloak/pull/24467 applying the merge requests

2023-11-27 13:28 UTC, jonkoops submitted a review, later dismissed
LGTM code-wise, can't say anything about the translations themselves.

2023-11-27 16:44 UTC, rmartinc requested changes
Thanks a lot for teh effort @Aboullos!
Just a few more and it's done... :smile:

2023-11-27 16:44 UTC, rmartinc commented on themes/src/main/resources-community/theme/base/account/messages/messages_es.properties
> +totpStep3DeviceName=Proporcione un nombre de dispositivo para ayudarlo a administrar sus dispositivos OTP.
ayudarle

2023-11-27 16:44 UTC, rmartinc commented on themes/src/main/resources-community/theme/base/account/messages/messages_es.properties
> +scanBarCode=¿Quieres escanear el código de barras?
¿Quiere escanear...

2023-11-27 16:44 UTC, rmartinc commented on themes/src/main/resources-community/theme/base/admin/messages/messages_es.properties
> +clientRedirectURIsIllegalSchemeError=Un URI de redirección utiliza un esquema ilegal
Una URI

2023-11-27 16:44 UTC, rmartinc commented on themes/src/main/resources-community/theme/base/email/messages/messages_es.properties
> +identityProviderLinkBody=Alguien quiere vincular su cuenta "{1}" con la cuenta "{0}" del usuario {2}. Si ha sido usted, haga clic en el siguiente enlace para vincular las cuentas \ n \ n {3} \ n \ nE
The message is OK, but take care with the spaces in the `\n`.

2023-11-27 16:44 UTC, rmartinc commented on themes/src/main/resources-community/theme/base/email/messages/messages_es.properties
> +emailVerificationBodyCode=Verifique su dirección de correo electrónico ingresando en el siguiente código. \ N \ n {0} \ n \ n.
Just the `\n` are not ok.

2023-11-27 16:44 UTC, rmartinc commented on themes/src/main/resources-community/theme/base/login/messages/messages_es.properties
> +hidePassword=Contraseña oculta
Ocultar contraseña

2023-11-27 16:44 UTC, rmartinc commented on themes/src/main/resources-community/theme/base/login/messages/messages_es.properties
> +successLogout=Estás desconectado
Está desconectado

2023-11-27 16:44 UTC, rmartinc commented on themes/src/main/resources-community/theme/base/login/messages/messages_es.properties
> +standardFlowDisabledMessage=l cliente no puede iniciar el inicio de sesión del navegador con el tipo de respuesta dado. El flujo estándar está deshabilitado para el cliente.
`El cliente`

2023-11-27 16:44 UTC, rmartinc commented on themes/src/main/resources-community/theme/keycloak.v2/account/messages/messages_es.properties
> +nextPage=Próxima
Siguiente

2023-11-27 16:44 UTC, rmartinc commented on themes/src/main/resources-community/theme/keycloak.v2/account/messages/messages_es.properties
> +thirdPartyApp=Tercero
Aplicación de terceros

2023-11-27 21:36 UTC, jonkoops commented
@rmartinc Just FYI, you can also [provide suggestions](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/commenting-on-a-pull-request#adding-comments-to-a-pull-request) in GitHub that can be committed directly from the comments.

2023-11-28 11:07 UTC, Aboullos commented
@rmartinc thanks for the review, change requests applied

2023-11-28 11:19 UTC, rmartinc approved these changes
Thanks a lot @Aboullos! Approved!

2023-11-28 11:49 UTC, jonkoops approved these changes

2023-11-30 17:08 UTC, ssilvert approved these changes

2023-11-30 18:04 UTC, merged