Delete container providers from the base testsuite
keycloak/keycloak pull request #25168
Opened 2023-11-30 13:33 UTC by vramik

Closes #24097

2023-12-01 11:32 UTC, martin-kanis reviewed
@vramik Thanks for the PR. Should be `testcontainers` dependency removed from `testsuite/integration-arquillian/tests/base/pom.xml` as part of this PR?

2023-12-01 11:57 UTC, mhajas requested changes
Thank you @vramik, I added some comments

2023-12-01 11:57 UTC, mhajas commented on testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/CockroachdbContainerProvider.java
> -    private static final Boolean START_CONTAINER = Boolean.valueOf(System.getProperty("cockroachdb.start-container", "false"));
We still mention some of these properties in `HOW_TO_RUN.md`. Do we want to remove it here? Or in a separate PR?

2023-12-01 11:57 UTC, mhajas commented on testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/zerodowntime/ZeroDowntimeTest.java
At the beginning of `ZeroDowntimeTest` it was running also with the current/legacy store. I think it still makes sense to have such test as we were discussing it may be possible to have some releases no-downtime upgradable. Should we consider keeping this test for this purpose or it is a different test?

2023-12-04 13:40 UTC, martin-kanis approved these changes

2023-12-04 13:44 UTC, mhajas approved these changes
Thank you @vramik

2023-12-04 13:44 UTC, merged