doc: adding a note about config expressions
keycloak/keycloak pull request #25218
Opened 2023-12-01 15:14 UTC by shawkins

I'm not sure if there's even more nuance to express here as some locations we may specifically look at the raw values instead.

There hasn't been any follow up on https://github.com/smallrye/smallrye-config/issues/1056 to know if the $$ behavior is expected.

fix: #19831

2023-12-04 11:40 UTC, ahus1 commented on docs/guides/server/configuration.adoc
> +To disable expression evaluation, the \ character is used as an escape character where needed. In particular it must be used to escape the usage of $ characters when they appear to define an expressi
Some comments here around quoting contents for the docs (apply here if necessary):

* If you struggle with escaping things for AsciiDoc, consider putting it into double-plus signs for pass-through content (`++passthrough++`).
* If you struggle with escaping freemarker stuff (like things in curly braces), wrap it as no-parse (`<#noparse>...</#noparse>`)

2023-12-04 11:49 UTC, shawkins commented on docs/guides/server/configuration.adoc
> +To disable expression evaluation, the \ character is used as an escape character where needed. In particular it must be used to escape the usage of $ characters when they appear to define an expressi
> Seems triple \$ is needed?

No, the key here is using \\ to escape the $.  Using \\$\\$\\$ would evaluate to 3 dollar signs, not 2.  There may be a fix upstream to correct the $$ behavior, so we don't want to document relying on that - https://github.com/smallrye/smallrye-config/issues/1056

2023-12-04 11:53 UTC, vmuzikar commented on docs/guides/server/configuration.adoc
> +To disable expression evaluation, the \ character is used as an escape character where needed. In particular it must be used to escape the usage of $ characters when they appear to define an expressi
@shawkins Not sure why (haven't investigated) but if I use something like `--db-username posgre\$\$\$ql`, it evaluates to `posgre$$ql` (looking at DB log of failed auth attempt).

2023-12-04 15:55 UTC, shawkins commented on docs/guides/server/configuration.adoc
> +To disable expression evaluation, the \ character is used as an escape character where needed. In particular it must be used to escape the usage of $ characters when they appear to define an expressi
@vmuzikar please review again, I've incorporated most the suggestions and further clarified shell handling.

2023-12-04 17:31 UTC, vmuzikar commented on docs/guides/server/configuration.adoc
> +To disable expression evaluation, the \ character is used as an escape character where needed. In particular it must be used to escape the usage of $ characters when they appear to define an expressi
I looked into it more. The issue with 3 `$$$` was truly caused by the shell backslash escaping as you hinted.

However, I think the docs change is a little bit confusing still. We're mixing together two things: the SmallRye expression escaping, and shell expressions escaping. For example, let's assume the `my$$password` value. When specified in shell, it needs to be entered as `"my\$\$password"` to mitigate for shell expressions. However, when specified via a properties file it needs to be entered as `my$$$$password` to mitigate SmallRye expressions (which are not evaluated on other config sources AFAIK). This is currently not captured in the docs.

2023-12-04 17:47 UTC, shawkins commented on docs/guides/server/configuration.adoc
> +To disable expression evaluation, the \ character is used as an escape character where needed. In particular it must be used to escape the usage of $ characters when they appear to define an expressi
> We're mixing together two things: the SmallRye expression escaping, and shell expressions escaping.

That's not intended - shell escaping only comes into this at the very end as an additional concern on top of the escaping needed for Microprofile config / smallrye.

> For example, let's assume the my$$password value. When specified in shell, it needs to be entered as "my\$\$password" to mitigate for shell expressions.

That's not at all what I'm trying to convey - it doesn't matter where the value appears, the $$ needs to be escaped.

> However, when specified via a properties file it needs to be entered as my$$$$password to mitigate SmallRye expressions

That's not at all what I would recommend.  As far as I can find, that's undocumented behavior - unless I'm missing something it doesn't appear in Microprofile config nor quarkus docs.  I do see references to \ as the escape character - and it's explicitly handled in the smallrye code as such wrt $.

> which are not evaluated on other config sources AFAIK

The removal of $$ is certainly happening when processing cli args, are you suggesting that you don't expect nested expressions to be resolved with cli or env variables?

2023-12-05 13:36 UTC, shawkins commented
@vmuzikar see if this further clarifies things.  It doesn't appear that additional general \ escape handling is coming from upstream anytime soon, so I wouldn't explicitly mention anything in our docs about that.  We can of course also push for quarkus to take ownership of spelling out escaping rules as well.

2023-12-05 15:40 UTC, vmuzikar commented on docs/guides/server/configuration.adoc
> +For example bash single quotes will preseve the single backslash --db-password=`'my\$\$password'`, or with bash double quotes you will need an additional backslash --db-password=`"my\\$\\$password"`.
Thanks for the update! I think it's clearer now.

One last nitpick. I think we should be putting whole key+value in the backticks. Seems It's more common throughout the docs.
```suggestion
To disable expression evaluation, the `\` character is used as an escape character. In particular it must be used to escape the usage of `$` characters when they appear to define a expression or are repeated. For example if you want the configuration value `my$$password`, use `my\$\$password` instead.  Note that the `\` character requires additional escaping or quoting when using most unix shells, or when it appears in properties files.  
For example bash single quotes will preserve the single backslash `--db-password='my\$\$password'`, or with bash double quotes you will need an additional backslash `--db-password="my\\$\\$password"`. Similarly in a properties file backslash characters must themselves be escaped: `kc.db-password=my\\$\\$password`
```

2023-12-05 15:47 UTC, vmuzikar submitted a review, later dismissed

2023-12-06 11:21 UTC, shawkins commented
@ahus1 do you want to review this before it is merged?

2023-12-06 18:25 UTC, ahus1 commented
@shawkins - I pushed one more commit to fix a typo (`a` -> `an`) and added a replacement for the project name with we need to do always. The single `/` is also very uncommon in our docs. 

For further writing style as some new paragraphs are added, I suggest to give @andymunro a chance to review the docs from a technical writing perspective.

2023-12-06 18:26 UTC, ahus1 reviewed
Once Andy's review is in, this should can be squashed and merged.

2023-12-06 19:03 UTC, andymunro commented on docs/guides/server/configuration.adoc
> +{project_name} depends upon Quarkus and MicroProfile for processing configuration values. Be aware that value expressions are supported - for example `$\{some_key}`, will evaluate to the value of `so
```suggestion
{project_name} depends upon Quarkus and MicroProfile for processing configuration values. Be aware that value expressions are supported. For example, `$\{some_key}` evaluates to the value of `some_key`.
```

2023-12-06 19:04 UTC, andymunro commented on docs/guides/server/configuration.adoc
> +To disable expression evaluation, the `\` character is used as an escape character. In particular it must be used to escape the usage of `$` characters when they appear to define an expression or are
```suggestion
To disable expression evaluation, the `\` character functions as an escape character. In particular, it must be used to escape the usage of `$` characters when they appear to define an expression or are repeated. For example, if you want the configuration value `my$$password`, use `my\$\$password` instead.  Note that the `\` character requires additional escaping or quoting when using most unix shells, or when it appears in properties files.
```

2023-12-06 19:05 UTC, andymunro commented on docs/guides/server/configuration.adoc
> +For example bash single quotes will preserve the single backslash `--db-password='my\$\$password'`, or with bash double quotes you will need an additional backslash `--db-password="my\\$\\$password"`
```suggestion
For example, bash single quotes preserve the single backslash `--db-password='my\$\$password'`. Also, with bash double quotes, you need an additional backslash `--db-password="my\\$\\$password"`. Similarly in a properties file, backslash characters must also be escaped: `kc.db-password=my\\$\\$password`
```

2023-12-06 19:10 UTC, andymunro requested changes
Just a few changes.

2023-12-06 19:16 UTC, ahus1 approved these changes
Approving as of @vmuzikar's previous review and as all of @andymunro's changes have been accepted. Ready to be merged!

2023-12-06 19:18 UTC, shawkins commented
@ahus1 @andymunro thank you for the updates, they've been squashed into the review commit.

2023-12-06 19:29 UTC, merged