Add missing Spanish translations for keycloak.v2 admin theme
keycloak/keycloak pull request #25284
Opened 2023-12-05 07:40 UTC by daniel-shuy

Fixes #25041

2023-12-05 08:46 UTC, jonkoops commented
@miquelsi @rmartinc @Aboullos can I ask you to put in a review for this PR?

2023-12-07 14:15 UTC, Aboullos requested changes
The file is really big but it looks generally good, some suggestions

2023-12-07 14:15 UTC, Aboullos commented on js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_es.properties
> +revocationDescription=Esta es una forma de revocar todas las sesiones activas y tokens de acceso. 'Not before' significa que puedes revocar cualquier token emitido antes de la fecha.
```suggestion
revocationDescription=Esta es una forma de revocar todas las sesiones activas y tokens de acceso. 'No antes' significa que puedes revocar cualquier token emitido antes de la fecha.
```

2023-12-07 14:15 UTC, Aboullos commented on js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_es.properties
> +setToNowError=�Error\! No se pudo establecer 'notBefore' en la fecha y hora actuales.
```suggestion
setToNowError=�Error\! No se pudo establecer 'No antes' en la fecha y hora actuales.
```

2023-12-12 12:14 UTC, jonkoops commented
@daniel-shuy could you process the review comments?

2023-12-13 08:24 UTC, daniel-shuy commented
@Aboullos Huge thanks for reviewing the translations!

@jonkoops Sorry for the delay, I've applied the suggestions

2023-12-13 08:30 UTC, jonkoops commented
@Aboullos coud you give this another pass? I think we can merge this pretty soon.

2023-12-14 13:51 UTC, Aboullos commented
LGTM!

2023-12-15 08:04 UTC, Aboullos approved these changes

2023-12-15 11:48 UTC, miquelsi approved these changes

2024-01-04 03:57 UTC, daniel-shuy commented
Happy New Year! Any chance this could be merged soon?

2024-01-04 12:22 UTC, jonkoops approved these changes

2024-01-04 12:23 UTC, jonkoops commented
Approving and merging this in based on previous approval.

2024-01-04 12:42 UTC, merged

2024-02-07 02:21 UTC, daniel-shuy commented
Any idea when we can expect this to be released?

2024-02-07 10:54 UTC, jonkoops commented
This will be in the next major version, so 24. This should be released in a couple of weeks, but no guarantee.

2024-02-07 12:01 UTC, daniel-shuy commented
@jonkoops okay, thanks