moved login screen to patternfly 5
keycloak/keycloak pull request #25340
Opened 2023-12-06 16:03 UTC by edewit

2023-12-12 09:51 UTC, edewit commented on themes/src/main/resources/META-INF/keycloak-themes.json
> +        "types": [ "account", "admin", "login" ]
No need to do that as the original doesn't change you have to pick it in the themes tab to enable it

2023-12-12 10:26 UTC, jonkoops commented on themes/src/main/resources/META-INF/keycloak-themes.json
> +        "types": [ "account", "admin", "login" ]
We should probably still add a feature flag to change the default it nothing is configured right? That is what we did with the other themes as well.

2023-12-13 15:23 UTC, jonkoops commented on themes/src/main/resources/theme/keycloak.v2/login/theme.properties
> +styles=css/login.css
This loads the original login styles, which might have incompatibilities with the new stuff we're doing. Perhaps we can clear this instead?
```suggestion
styles=
```

2024-01-10 10:30 UTC, jonkoops requested changes

2024-01-10 10:30 UTC, jonkoops commented on common/src/main/java/org/keycloak/common/Profile.java
> +        LOGIN2("New Login Theme", Type.PREVIEW),
I think we should probably default to `EXPERIMENTAL` here, considering this is very early code.

2024-01-11 14:55 UTC, jonkoops submitted a review, later dismissed

2024-01-12 14:51 UTC, jonkoops approved these changes, later dismissed

2024-01-12 14:51 UTC, jonkoops commented on common/src/test/java/org/keycloak/common/ProfileTest.java
> +        Profile.Feature.LOGIN2,
Indentation here seems off.

2024-01-12 16:03 UTC, jonkoops approved these changes, later dismissed

2024-01-23 08:55 UTC, jonkoops approved these changes, later dismissed

2024-01-25 11:30 UTC, jonkoops approved these changes

2024-01-25 12:45 UTC, mposolda approved these changes

2024-01-25 12:45 UTC, merged