Refactoring user profile interfaces and consolidating user representation for both admin and account context
keycloak/keycloak pull request #25482
Opened 2023-12-12 03:52 UTC by pedroigor

2023-12-12 07:48 UTC, mposolda submitted a review, later dismissed

2023-12-12 19:59 UTC, andymunro requested changes
Looks good. A few changes to suggest @mposolda

2023-12-12 19:59 UTC, andymunro commented on server-spi/src/main/java/org/keycloak/userprofile/Attributes.java
> + * administrators by setting any of the {@link org.keycloak.representations.userprofile.config.UPConfig.UnmanagedAttributePolicy}.
```suggestion
 * does not know about them and they cannot use capabilities provided by the server. However, they can still be managed by
 * administrators by setting any of the {@link org.keycloak.representations.userprofile.config.UPConfig.UnmanagedAttributePolicy}.
```

2023-12-13 03:16 UTC, pedroigor commented
Thanks @andymunro, please let me know if anything else is missing.

2023-12-13 07:23 UTC, mposolda approved these changes

2023-12-13 07:24 UTC, mposolda commented
@andymunro Thanks for the docs review!

@pedroigor LGTM, we can adjust later if there are some issues or more things to improve...

2023-12-13 07:27 UTC, merged