fix: adds --verbose to all commands
keycloak/keycloak pull request #25590
Opened 2023-12-14 20:25 UTC by shawkins

This is to replace / move forward #17553 

I agree with the arguments that it's a usability issue to recommend using --verbose, but then the user has to figure out that it can only go before the command. Seems much more straight-forward to allow it everywhere. The config-file option was left as is.

closes #13250

2023-12-15 11:15 UTC, mabartos approved these changes
I agree to provide this functionality.

However, I remember @pedroigor had some additional thoughts about it.

@pedroigor Are you ok to include it?

2023-12-15 11:21 UTC, mabartos requested changes
@shawkins Looks like the failures in CI are caused by this PR.

2023-12-15 13:01 UTC, shawkins commented
> @shawkins Looks like the failures in CI are caused by this PR.

Right, it should be assertStartedDevMode instead

2023-12-15 13:06 UTC, mabartos approved these changes
@shawkins Thanks. LGTM

2023-12-19 11:34 UTC, pedroigor approved these changes
As mentioned in that previous discussion, the idea is to have a repository for cross-cutting options and have a better organization.

Most of the time, you won't want to run verbose so the idea is to not make it explicit within every single command.

If you guys think it helps to improve UX, works for me too.

2023-12-20 12:12 UTC, mabartos commented
@shawkins @pedroigor I think it's worth including it in Keycloak.

2023-12-20 12:13 UTC, merged