added attributes to KeycloakProfile definition
keycloak/keycloak pull request #25617
Opened 2023-12-15 13:01 UTC by edewit

fixes: #25403
Signed-off-by: Erik Jan de Wit <erikjan.dewit@gmail.com>

2024-01-09 13:36 UTC, jonkoops requested changes

2024-01-09 13:36 UTC, jonkoops commented on js/libs/keycloak-js/dist/keycloak.d.ts
> +	attributes?: Record<string, any>;
Perhaps `unknown` would be a better type for the value here?
```suggestion
	attributes?: Record<string, unknown>;
```

2024-01-10 10:32 UTC, jonkoops approved these changes

2024-01-10 13:06 UTC, hmlnarik approved these changes

2024-01-15 14:14 UTC, merged