Do not allow verifying email from a different account
keycloak/keycloak pull request #25711
Opened 2023-12-20 00:24 UTC by pedroigor

Closes #14776

2023-12-20 08:15 UTC, mposolda submitted a review, later dismissed
LGTM

@andymunro Are you please able to review the documentation part?

2023-12-20 20:15 UTC, andymunro commented on docs/documentation/release_notes/topics/24_0_0.adoc
> +In this release, it is no longer possible to perform actions, such as email verification, if the user is already authenticated
```suggestion
In this release, you can no longer perform actions such as email verification if the user is already authenticated
```

2023-12-20 20:24 UTC, andymunro requested changes
Thanks, @pedroigor. Approved if these changes are made.

2024-01-05 11:44 UTC, mposolda approved these changes

2024-01-05 11:45 UTC, merged