refactored authentication to use the ui-shared
keycloak/keycloak pull request #25730
Opened 2023-12-20 13:13 UTC by edewit

Signed-off-by: Erik Jan de Wit <erikjan.dewit@gmail.com>

2023-12-20 13:31 UTC, ssilvert approved these changes, later dismissed
LGTM

2024-01-10 08:54 UTC, jonkoops submitted a review, later dismissed
This cleans up really nice! LGTM

2024-01-10 12:22 UTC, jonkoops requested changes

2024-01-10 12:22 UTC, jonkoops commented on convert.java
This seems to have been checked in, but I don't think it was supposed to.

2024-01-10 17:32 UTC, jonkoops requested changes

2024-01-10 17:32 UTC, jonkoops commented on js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties.orig
Looks like this file was checked in unintentionally.

2024-01-12 08:38 UTC, jonkoops requested changes

2024-01-12 08:38 UTC, jonkoops commented on js/apps/admin-ui/src/App.tsx.orig
> +<<<<<<< HEAD
Merge conflict here.

2024-01-12 09:52 UTC, jonkoops approved these changes

2024-01-12 09:52 UTC, merged