doc: adding notes about header priority
keycloak/keycloak pull request #25959
Opened 2024-01-05 17:37 UTC by shawkins

@vmuzikar are you good with the retroactive change all the way back to the 17 migration, or is there a better place to note this?

I think I was getting my wires crossed with this doc update and the one about spaces in the cli key - do you want this one reflected in the downstream docs?

closes: #23023

2024-01-08 07:45 UTC, vmuzikar requested changes
@shawkins Thanks for the PR.

Rather than using the release notes or upgrading guide for this, IMHO we should mention it just in the Quarkus migration guide (and in the RHBK 22 migration guide).

2024-01-08 16:52 UTC, shawkins commented
> Rather than using the release notes 

If this is not mentioned in the release notes, how - or should - new users be made aware of this behavior?

> or upgrading guide for this, IMHO we should mention it just in the Quarkus migration guide 

Okay, moved from the upgrading guide to the migration guide.

> (and in the RHBK 22 migration guide).

Once we agree on these changes, I'll open a downstreap pr.

2024-01-09 08:20 UTC, vmuzikar commented
> If this is not mentioned in the release notes, how - or should - new users be made aware of this behavior?

This is mainly a migration problem for users coming from the WF distribution. It is not really specific to the new `proxy-headers` option. Including it in 24 release notes indicates it's a new thing.

We could, however, include it in the proxy guide.

2024-01-09 19:25 UTC, shawkins commented
> We could, however, include it in the proxy guide.

Ah, I looked around more for that. The note has been moved to that guide now.

2024-01-10 08:21 UTC, vmuzikar approved these changes
@shawkins Thanks, LGTM!

2024-01-10 08:21 UTC, merged