13203 Adds documentation for Account API
keycloak/keycloak pull request #25974
Opened 2024-01-08 02:00 UTC by Hronom

Extend OpenAPI documentation with Account API.

This should help with this https://github.com/keycloak/keycloak/issues/13203 but there some nuances.

# How-to check
Generate schema:
```
mvn clean install -DskipTests=true smallrye-open-api:generate-schema -P jboss-release -pl services
```

Check generated file in:
```
${project.build.directory}/apidocs-rest/swagger/apidocs/openapi.yaml
```

# Nuances

There [issue related to how API organized](https://github.com/keycloak/keycloak/issues/13203#issuecomment-1876220056).
Specifically there sub resources here:
```
    @Path("/")
    public Object getAccountService() {
```
and here:
```
    @Path("{version : v\\d[0-9a-zA-Z_\\-]*}")
    @Produces(MediaType.APPLICATION_JSON)
    public Object getVersionedAccountRestService(final @PathParam("version") String version) {
```

During generation of OpenAPI plugin `smallrye-open-api-maven-plugin` not able to to get a clue about what Sub Resource will be returned by was methods.

So in order to provide at least something instead of nothing(for Account API) - there was added groups of fake methods in `AccountLoader`.
```
    /**
     * This needed to provide examples for Account API.
     * Here we return a specific sub resource, so OpenAPI generator able to scan it.
     */
    @Path("/account-api-cors-example")
    public CorsPreflightService getAccountApiCorsExample() {
        throw new ForbiddenException();
    }

    /**
     * This needed to provide examples for Account API.
     * Here we return a specific sub resource, so OpenAPI generator able to scan it.
     */
    @Path("/account-api-example")
    public AccountRestService getAccountApiExample() {
        throw new ForbiddenException();
    }
```

```
    /**
     * This needed to provide examples for Account API.
     * Here we return a specific sub resource, so OpenAPI generator able to scan it.
     */
    @Path("{version : v\\d[0-9a-zA-Z_\\-]*}/account-api-cors-example")
    @Produces(MediaType.APPLICATION_JSON)
    public CorsPreflightService getVersionedAccountApiCorsExample(final @PathParam("version") String version) {
        throw new ForbiddenException();
    }

    /**
     * This needed to provide examples for Account API.
     * Here we return a specific sub resource, so OpenAPI generator able to scan it.
     */
    @Path("{version : v\\d[0-9a-zA-Z_\\-]*}/account-api-example")
    @Produces(MediaType.APPLICATION_JSON)
    public AccountRestService getVersionedAccountApiExample(final @PathParam("version") String version) {
        throw new ForbiddenException();
    }
```

This allow `smallrye-open-api-maven-plugin` to generate OpenAPI spec. However it generates them under `*-example` paths.

To make it actual we need to do simple replace of `/account-api-cors-example` and `/account-api-example` to empty string. This helps developers to easily adopt generated OpenAPI for other services that need to use Account API.

2024-01-08 02:02 UTC, Hronom commented
cc @ahus1 

I'm totally ok if maintainers edit this PR.

Merging this PR helps a lot to others who need to work with Account API e.g. create custom Account Console

2024-02-07 21:57 UTC, thomasdarimont requested changes
Thanks for your PR! Changes look good to me, just a few nitpicks :)

2024-02-07 21:57 UTC, thomasdarimont commented on services/src/main/java/org/keycloak/services/resources/account/AccountLoader.java
> +import jakarta.ws.rs.*;
Nitpick: avoid *-imports

2024-02-07 21:57 UTC, thomasdarimont commented on services/src/main/java/org/keycloak/services/resources/account/AccountRestService.java
> +import jakarta.ws.rs.*;
Nitpick: Avoid *-imports

2024-02-07 21:57 UTC, thomasdarimont commented on services/src/main/java/org/keycloak/services/resources/account/AccountRestService.java
> +    @Operation(summary = "Applications.")
```suggestion
    @Operation(summary = "List applications available to the user.")
```

2024-02-07 21:57 UTC, thomasdarimont commented on services/src/main/java/org/keycloak/services/resources/account/AccountRestService.java
> +    @Operation(summary = "Group memberships.")
```suggestion
    @Operation(summary = "List group memberships.")
```

2024-02-07 21:57 UTC, thomasdarimont commented on services/src/main/java/org/keycloak/services/resources/account/AccountRestService.java
> +    @Operation(summary = "Update account.")
```suggestion
    @Operation(summary = "Update account information.")
```

2024-02-08 06:25 UTC, stianst requested changes
This would be great to get in, but it needs a bit of work.

We should not have a single docs for both account and admin I'd say, but rather have two separate docs.

The annotations here also need some more review and tuning.

For example this is not the right URL (it should be /realms/{realm}/account)
![image](https://github.com/keycloak/keycloak/assets/2271511/0d031342-b467-4ce3-9c01-16ca1959fe8f)

Another example is CORS preflight stuff shouldn't be listed I'd say:
![image](https://github.com/keycloak/keycloak/assets/2271511/d683d56f-e547-4782-abdf-c38b6b4b8e3f)

If you're still wanting to work on this, I'd be happy to review it in more depth and can also work on the website side of things if you want.

2024-03-03 17:05 UTC, Hronom commented
@thomasdarimont I'm ok if maintainers will do all changes that they think we need to do.
I wanna make sure that this PR will be not forgotten.

@stianst I wrote reasons in description about why it's done like this. I consider this ok solutions, since right now keycloak don't have any documentation for `/accounts` API's and it requested by many people. So instead of nothing I select something.

Maintainers, please adjust whatever you think to need to adjust. Let's not put this changes in forgotten mode.
I'm providing my verbal OK to do any changes in this PR, or feel free to create new one.

2024-03-16 16:11 UTC, Hronom commented
@stianst you probably really out of context and didn't read description of the PR. 
The way how Keycloack organize API there no possibility to make paths:
```
/accounts
```

And I would say this is the reasons why Accounts API still don't have documentation, because whenever maintainers of Keycloack tried to do it the hit same wall as I and drop work on it.

There was done CRITICAL architecture mistake in the beginning when Accounts API was created. 
Probably persons who created that was not care too much about it.
Unfortunately the documentation libraries can't support generic API's.

2024-03-18 07:01 UTC, closed without merging