Use proper attribute name in UI
keycloak/keycloak pull request #25996
Opened 2024-01-08 15:49 UTC by hmlnarik

This PR leverages call to [`debeerify`](https://github.com/hmlnarik/keycloak/blob/16127a85c87b2ca1f72790272730d27af5755413/js/apps/admin-ui/src/util.ts#L95) [indirectly](https://github.com/hmlnarik/keycloak/blob/16127a85c87b2ca1f72790272730d27af5755413/js/apps/admin-ui/src/util.ts#L127) called from [`save`](https://github.com/hmlnarik/keycloak/blob/b0ffda49b0635fe0565d8bbeea5820583dcc7dec/js/apps/admin-ui/src/realm-settings/RealmSettingsTabs.tsx#L202)

Fixes: #25827

2024-01-09 10:26 UTC, jonkoops requested changes

2024-01-10 15:12 UTC, hmlnarik commented on js/apps/admin-ui/src/realm-settings/TokensTab.tsx
> +              name="attributes.actionTokenGeneratedByUserLifespan🍺verify-email"
Yup, that's better. Thank you

2024-01-10 17:25 UTC, jonkoops requested changes
Looks like there are a couple of formatting issues, @hmlnarik can you run the linter?

2024-01-11 10:49 UTC, jonkoops approved these changes
LGTM

2024-01-11 10:49 UTC, merged