Make changes to the policy entities and corresponding store classes to delete entries on join tables from non-owning sides of the database
keycloak/keycloak pull request #26004
Opened 2024-01-08 20:18 UTC by alice-wondered

Resolves #25510

2024-01-08 21:32 UTC, alice-wondered commented
@ahus1 just getting this added to your queue properly. This is split off work from #25920 and passes off the handling of deleting join table entries to the entity to do things in line with how JPA recommends. 

Additionally, I change labels of "OneToMany" over to "ManyToMany" but I think that this more accurately reflects the reality of the underlying database as we are using jointables with two FKs that link to many records on either side. 

Could keep the "OneToMany" annotation but it would require the creation of new entities to track the join table so that ownership can be mapped on both sides of the relationship still

2024-01-11 08:37 UTC, ahus1 commented
@alice-wondered - thank you for looping me in here. I looked at the changes done to JPA, and they look ok for me from a high-level JPA point of view. 

Unfortunately I am not familiar enough with the AUTHZ table structure: 

* Are the changes valid from a business point of view?
* Would the access lead to large cardinalities where a lot of data would be loaded from the database? For example, looking at how the `JPAPolicyStore` deletes a policy, how many root policies a policy has, and associated policies a single root policy has. In that example, I assume are using similar code to set up the initial policy, so it wouldn't hopefully break existing setups. Depending on future growth we see in that area, that access model might still be limiting.

I am also not familiar enough with it to confirm if the changes to the test cases are valid even though I read your comments.

Something I assume (might be worth checking): there are contraints/foreign keys in the database to prevent dangling entities in the database.

Something I see in the code where you pass on `null` when the API states it must not be `null`. It was added in #11817 by @mhajas. I assume the realm information was used in the map store, but IMHO it is not used in many places in the current store (except maybe for the `count` method in the `PermissionTicketStore`. The comment "This results in search across all realms and resource servers. We need to avoid this because it can be highly ineffective." isn't very specific to me, and the link seems to point to the `count` method.

For now, I'd suggest to not pass null here. Depending on Michal's feedback a future change could simplify the interfaces by removing the parameters added for the map store and not used in the current store.

```
provider.getStoreFactory().getPolicyStore().delete(null, policyId);
```

This might not be the feedback you've hoped for, still I hope it helps you. If you have more specific questions, please let me know.

2024-01-11 14:44 UTC, alice-wondered commented
@ahus1 thanks for the review! It's good to know the changes to the entities look fine from a JPA perspective. These changes are also what resolve the FK issues mentioned (was mentioned that I forgot to mention that on this PR so wanted to properly reference that issue here) 

> * Would the access lead to large cardinalities where a lot of data would be loaded from the database? For example, looking at how the `JPAPolicyStore` deletes a policy, how many root policies a policy has, and associated policies a single root policy has. In that example, I assume are using similar code to set up the initial policy, so it wouldn't hopefully break existing setups. Depending on future growth we see in that area, that access model might still be limiting.

This is an interesting point that I think will probably be valid in some use cases. At the moment the creation of policies is not something that is used that often but, especially because users can create their own policies, I do think that this is something that at the very least can occur.

In that case, would your suggestion be to use something like a named query to handle the deletions of all relevant items at once?

2024-01-11 14:46 UTC, alice-wondered commented
It's also maybe worth noting that I would be more concerned about deletion of a policy that has many root policies. The use case of a single policy having so many associated policies that it affects runtime is, at least in my opinion, unlikely to happen. Though I think @pedroigor would be able to weigh in on that point

2024-01-11 16:42 UTC, alice-wondered commented
To create parity with other conversation threads:
> Something I assume (might be worth checking): there are contraints/foreign keys in the database to prevent dangling entities in the database.

This is correct. The changes here are mostly to deal with, at least what I understand, is a hibernate constraing where you need to update the owning side of a relation when you have bidirectional entities. Most of the policy tables have associations with each other in some way and can be deleted independently, but then you need to make sure that their join tables are updated. 

The FK constraints are in place and trigger without these changes on undertow but not on quarkus. Not sure why this happens, but making sure that deletions always update the owning side of the relation in this PR fixes that issue. 

Relevant documentation: https://docs.jboss.org/hibernate/orm/6.4/introduction/html_single/Hibernate_Introduction.html#bidirectional-problem 

You can reproduce this by using undertow to run the authz section of the testsuite

2024-01-22 17:27 UTC, alice-wondered commented
> To create parity with other conversation threads:
> 
> > Something I assume (might be worth checking): there are contraints/foreign keys in the database to prevent dangling entities in the database.
> 
> This is correct. The changes here are mostly to deal with, at least what I understand, is a hibernate constraint where you need to update the owning side of a relation when you have bidirectional entities. Most of the policy tables have associations with each other in some way and can be deleted independently, but then you need to make sure that their join tables are updated.
> 
> The FK constraints are in place and trigger without these changes on undertow but not on quarkus. Not sure why this happens, but making sure that deletions always update the owning side of the relation in this PR fixes that issue.
> 
> Relevant documentation: https://docs.jboss.org/hibernate/orm/6.4/introduction/html_single/Hibernate_Introduction.html#bidirectional-problem
> 
> You can reproduce this by using undertow to run the authz section of the testsuite

@ahus1 just want to bump this so that it doesn't get lost!

2024-01-26 13:43 UTC, mhajas commented
> Something I see in the code where you pass on `null` when the API states it must not be `null`. It was added in #11817 by @mhajas. I assume the realm information was used in the map store, but IMHO it is not used in many places in the current store (except maybe for the `count` method in the `PermissionTicketStore`. The comment "This results in search across all realms and resource servers. We need to avoid this because it can be highly ineffective." isn't very specific to me, and the link seems to point to the `count` method.
> 
> For now, I'd suggest to not pass null here. Depending on Michal's feedback a future change could simplify the interfaces by removing the parameters added for the map store and not used in the current store.
> 
> ```
> provider.getStoreFactory().getPolicyStore().delete(null, policyId);
> ```

@ahus1 The parameter was indeed introduced because of Map storage. The current store does not store realm info so we are not able to filter by it. I think we should remove these parameters as they are not used and I believe they won't be used soon. I created an issue for removal: https://github.com/keycloak/keycloak/issues/26530. In the meantime, I would recommend using the following static variable: https://github.com/keycloak/keycloak/blob/b7d2010af7f290d559c36c220d8cf89a85d0b1d2/model/jpa/src/main/java/org/keycloak/authorization/jpa/store/JPAAuthorizationStoreFactory.java#L45 so it is documented why we are putting `null` into these calls.

2024-01-29 15:58 UTC, ahus1 approved these changes
Thank you @alice-wondered for this PR. I reviewed the JPA parts of this PR and the `@ManyToMany` is handled correctly, updating both sides of the relation. So I approve it from the store side of things. As discussed today, with the current expected number of entries in the collections, there isn't the need to optimize the access.

The store team will pick up the issue Michal created and will remove those not needed parameters once this PR has been merged.

I don't feel knowledgeable enough about AUTHZ to confirm the changed test cases, and I'd be happy if someone from the core team could approve that part.

2024-01-31 12:20 UTC, mhajas commented
@ahus1 Do we want a review from someone else for this PR or we can merge?

2024-01-31 12:32 UTC, ahus1 commented
For this kind of change (a blank and a version number) I don't think we need some else to look at it.

2024-01-31 12:34 UTC, ahus1 commented
Oops, wrong context. Disregard my previous comment.

2024-01-31 13:32 UTC, ahus1 commented
@mhajas - see my comment from above that this PR still needs someone familiar with the AUTHZ functionality. Especially as the tests changed in this PR, I assume the behavior changed in some way, and I don't feel confident enough to review it.

> I don't feel knowledgeable enough about AUTHZ to confirm the changed test cases, and I'd be happy if someone from the core team could approve that part.

2024-02-02 12:33 UTC, mhajas commented
@pedroigor Could you please have a look?

2024-02-02 12:48 UTC, pedroigor requested changes
@mhajas This is one of the changes @alice-wondered is working to authorization services.

We've discussed this specific change and we decided to hold it a bit more as I'm not yet convinced about why we need this and their impact on the functionality.

Once we finish other changes that seem more important to improve the valuation engine itself, then we'll get back to this one.

2024-02-02 12:58 UTC, mhajas commented
Thank you @pedroigor!

2025-10-24 19:50 UTC, closed without merging