fix: groups should be clickable when user has view-access on the group
keycloak/keycloak pull request #26033
Opened 2024-01-09 12:45 UTC by pkeuter

I've skipped creating an issue because of this text:
>For minor changes you can skip this part and go straight ahead to sending a contribution.

This PR makes sure a user with limited rights can still open the subgroups it has access to. The current checking is based on the manage-rights of the parent group instead of checking the actual rights on the group the user wants to open.

This PR makes sure that the user has view-rights on the folder it wants to open.

2024-01-10 12:06 UTC, jonkoops commented
@pkeuter could you [sign off](https://github.com/keycloak/keycloak/pull/26033/checks?check_run_id=20302149935) your commit for this one?

2024-01-10 12:07 UTC, jonkoops requested changes
Commits need to be signed off

2024-01-10 12:22 UTC, pkeuter commented
> Commits need to be signed off

Thought that I already did that because of the force push, but apparently I didn't. I've enabled auto sign now so shouldn't be an issue going forward. Thanks!

2024-01-10 12:22 UTC, jonkoops approved these changes, later dismissed
LGTM, thanks again @pkeuter

2024-01-16 14:25 UTC, pkeuter commented
@jonkoops I don't really understand why tests are failing. They seem to be in the java-part of the application. Are these flaky tests?

2024-01-16 14:30 UTC, pkeuter commented
@jonkoops I have pushed a nullable fix which was making the tests fail. There were 2 js tests and 1 java test that was failing. Hopefully all is good now.

2024-01-16 15:49 UTC, jonkoops approved these changes

2024-01-24 07:42 UTC, pkeuter commented
@edewit @jonkoops is this the same test-issue? Or is there something else I can check/fix?

2024-01-24 09:02 UTC, jonkoops commented
@pkeuter looks like the CI had a glitch, I rebased your PR and I will set it to auto-merge, so it should come through now.

2024-01-24 09:17 UTC, merged