added choose as an option to reset
keycloak/keycloak pull request #26065
Opened 2024-01-10 08:09 UTC by edewit

fixes: #25939
Signed-off-by: Erik Jan de Wit <erikjan.dewit@gmail.com>

2024-01-10 08:54 UTC, jonkoops approved these changes

2024-01-10 12:51 UTC, ssilvert requested changes
What happens if the field is required?  In that case, you would want to have a default value and you would not want to allow the field to become unset.

Do we support a default value right now?

2024-01-16 13:02 UTC, ssilvert approved these changes

2024-01-16 13:02 UTC, merged

2024-01-19 20:08 UTC, pedroigor commented
Thanks @ssilvert @edewit !