Remove unnecessary tooltip on device activity page
keycloak/keycloak pull request #26078
Opened 2024-01-10 15:05 UTC by ReneZeidler

Removes a tooltip that just repeats the same text as the label of the button itself.

Closes #26032

2024-01-10 17:27 UTC, jonkoops requested changes
Code looks good, but since we're touching this anyways, let's clean it up a little.

2024-01-10 17:27 UTC, jonkoops commented on js/apps/account-ui/src/account-security/DeviceActivity.tsx
> +            aria-describedby="refresh page"
I actually cannot find any element that has that has this `id`, and in this case the element is already descriptive, so let's remove this attribute entirely.
```suggestion
```

2024-01-10 18:12 UTC, ReneZeidler commented
I actually noticed this earlier and forgot about it again.
Thanks, I've amended the PR. 😄

2024-01-11 11:48 UTC, jonkoops approved these changes
LGTM

2024-01-11 11:49 UTC, merged

2024-01-11 11:49 UTC, jonkoops commented
Thanks for the fix @ReneZeidler!