Add upgrading docs for changes to send-verify-email API
keycloak/keycloak pull request #26204
Opened 2024-01-15 17:14 UTC by lexcao

Closes #26146.

2024-01-17 09:45 UTC, mposolda approved these changes, later dismissed
@lexcao Thanks!
@andymunro Do you please have a chance to review this as well please?

2024-01-17 13:00 UTC, mposolda reviewed
@lexcao One suggestion though: Is it possible to add a note about what endpoint should people use if they want to achieve the previous behaviour? AFAIK It is the PUT request to `execute-actions-email` endpoint with the `VERIFY_EMAIL` action inside it, but would be good to doublecheck?

2024-01-17 13:01 UTC, mposolda reviewed
@lexcao One suggestion though: Is it possible to add a note about what endpoint should people use if they want to achieve the previous behaviour? AFAIK It is the PUT request to execute-actions-email endpoint with the VERIFY_EMAIL action inside it, but would be good to doublecheck?

2024-01-17 18:41 UTC, andymunro commented on docs/documentation/upgrading/topics/keycloak/changes-24_0_0.adoc
> +In this release, the API will use `email-verification.ftl` template instead of `executeActions.ftl`.
```suggestion
In this release, the API will use the `email-verification.ftl` template instead of `executeActions.ftl`.
```

2024-01-17 18:41 UTC, andymunro commented on docs/documentation/upgrading/topics/keycloak/changes-24_0_0.adoc
> +If you have customized the `executeActions.ftl` template to modify how users verify their email using this API, please ensure that you transfer your modifications to the new template.
```suggestion
If you have customized the `executeActions.ftl` template to modify how users verify their email using this API, ensure that you transfer your modifications to the new template.
```

2024-01-17 18:42 UTC, andymunro commented on docs/documentation/upgrading/topics/keycloak/changes-24_0_0.adoc
> +If you have customized the `executeActions.ftl` template to modify how users verify their email using this API, please ensure that you transfer your modifications to the new template.
We avoid saying "please" in the documentation since it is overly polite.

2024-01-17 18:43 UTC, andymunro requested changes
@lexcao Thanks, just a few suggestions.

2024-01-17 18:44 UTC, andymunro approved these changes

2024-01-17 18:46 UTC, lexcao commented
@andymunro Thanks, just fixed.

@mposolda  Thanks, just added.

Please review again.

2024-01-18 08:47 UTC, mposolda approved these changes
@lexcao @andymunro Thanks!

2024-01-18 08:48 UTC, merged