Update norwegian translation of groups
keycloak/keycloak pull request #26221
Opened 2024-01-16 09:54 UTC by vltmn

This PR updates the norwegian translation of "Groups" which is shown in the UI in the left-hand menu among other places. The previous long text does not correspond to the word "groups" and is therefore changed.

2024-01-16 12:55 UTC, jonkoops requested changes
@vltmn could you [sign off](https://github.com/keycloak/keycloak/pull/26221/checks?check_run_id=20523209547) on your commit?

2024-01-16 16:03 UTC, jonkoops approved these changes

2024-01-17 11:33 UTC, vltmn commented
> @vltmn please refrain from updating with `main` unless your PR has conflicts, it generates additional notifications and CI workload for us.

Sorry about that, will do.

2024-01-17 12:39 UTC, jonkoops commented
No worries, the GitHub UI kinda pushes people to do this, it's a UX problem :smile:

2024-01-17 13:05 UTC, merged