Don't fail reset credentials action upon first broker login without `EXISTING_USER_INFO`
keycloak/keycloak pull request #26324
Opened 2024-01-19 07:37 UTC by Devristo

Don't fail reset credentials action upon first broker login without `AbstractIdpAuthenticator.EXISTING_USER_INFO`.

The ResetCredentialsActionTokenHandler depends upon the `EXISTING_USER_INFO` through `AbstractIdpAuthenticator.getExistingUser` solely to log the username. However, if the first broker login flow does not include a `IdpCreateUserIfUniqueAuthenticator` or `IdpDetectExistingBrokerUserAuthenticator`, the `EXISTING_USER_INFO` is never set.

This commit does not attempt to fetch the existing user if we don't have this info set.

Closes #26323

2024-01-26 19:29 UTC, douglaspalmer requested changes
These changes look good. Can you please add a test to ResetCredentialsAlternativeFlowsTest for this pull request?

2024-01-27 17:16 UTC, Devristo commented
I am working on it. Although I wonder if org.keycloak.testsuite.broker.AbstractFirstBrokerLoginTest is not a better place? The `testLinkAccountByLogInAsUserAfterResettingPasswordUsingDifferentBrowsers` seems like good inspiration.

2024-01-27 17:48 UTC, Devristo commented
The test has been added to `org.keycloak.testsuite.broker.AbstractFirstBrokerLoginTest`. It was a bit easier to do as all the test setup was more applicable. The test has been added in a separate commit and will fail without the fixing commit.

Let me know if there is anything else I can do!

2024-01-29 19:08 UTC, douglaspalmer approved these changes
LGTM

2024-01-30 08:12 UTC, ahus1 approved these changes
Approving as of @douglaspalmer's review.

2024-01-30 11:16 UTC, merged