More a11y fixes
keycloak/keycloak pull request #26344
Opened 2024-01-19 18:10 UTC by agagancarczyk

A mix of a11y fixes based on the cypress dashboard report.

2024-01-19 19:42 UTC, ssilvert requested changes

2024-01-20 10:26 UTC, jonkoops approved these changes, later dismissed

2024-01-22 09:32 UTC, hmlnarik commented on js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
> +writtableSelection=Wrirable selection
```suggestion
writableSelection=Writable selection
```

2024-01-22 09:32 UTC, hmlnarik commented on js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
> +selectAuthorizationEncryptedResponseEnc=Select authorization encrypted response enc
The `authorization_encrypted_response_enc` and `authorization_encrypted_response_alg` come from [OIDC spec](https://openid.net/specs/openid-financial-api-jarm.html#client-metadata), thus I'd rather keep them named consistently for user's sake: either
```suggestion
selectAuthorizationEncryptedResponseAlg=Select authorization encrypted response alg
selectAuthorizationEncryptedResponseEnc=Select authorization encrypted response enc
```
or
```suggestion
selectAuthorizationEncryptedResponseAlg=Select authorization encrypted response algorithm (alg)
selectAuthorizationEncryptedResponseEnc=Select authorization encrypted response encryption method (enc)
```

2024-01-22 10:08 UTC, jonkoops approved these changes

2024-01-22 10:34 UTC, hmlnarik approved these changes

2024-01-22 13:04 UTC, ssilvert approved these changes

2024-01-22 13:04 UTC, merged