Added Client Type feature flag to begin client type work
keycloak/keycloak pull request #26389
Opened 2024-01-22 15:16 UTC by vickeybrown

Closes #26346

2024-01-22 16:01 UTC, jonkoops requested changes

2024-01-22 16:01 UTC, jonkoops commented on js/apps/admin-ui/src/utils/useIsFeatureEnabled.ts
There are some formatting issues here that the linter is reporting. You can fix these by running `pnpm --filter admin-ui lint -- --fix` in the `js` directory.

2024-01-22 17:53 UTC, jonkoops approved these changes, later dismissed
Not sure about introducing a profile without a feature, but the code looks good to me.

2024-01-22 17:54 UTC, jonkoops commented
@vickeybrown you'll have to [sign off](https://github.com/keycloak/keycloak/pull/26389/checks?check_run_id=20739032845) on your commits.

2024-01-23 08:52 UTC, hmlnarik requested changes
Please update HelpCommandDistTest expected messages in https://github.com/keycloak/keycloak/tree/main/quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help. See eg. #23977 for an example of adding an experimental feature flag

2024-01-23 08:53 UTC, hmlnarik commented
@mposolda Since this feature belongs to @keycloak/core  team, could you please review as well?

2024-01-23 16:03 UTC, jonkoops submitted a review, later dismissed

2024-01-24 09:13 UTC, mposolda approved these changes
@vickeybrown Thanks! I am fine with introducing the experimental feature flag for client types as long as tests are OK.

@hmlnarik PR is assigned to you, so leaving to you to further review/merge whenever you are ok. I've re-triggered the tests (as I am not sure those are real failures or instability)

2024-01-24 11:11 UTC, jonkoops approved these changes

2024-01-24 11:35 UTC, hmlnarik approved these changes

2024-01-24 12:07 UTC, merged