Possibility to email being not required
keycloak/keycloak pull request #26556
Opened 2024-01-29 12:58 UTC by mposolda

closes #26552

2024-01-30 12:03 UTC, pedroigor approved these changes, later dismissed

2024-01-31 08:20 UTC, jonkoops requested changes

2024-01-31 08:20 UTC, jonkoops commented on js/apps/admin-ui/src/realm-settings/user-profile/attribute/AttributeGeneralSettings.tsx
> +      {"username" != attributeName && (
Generally we put the constant value to compare to on the right hand side, as well as using [strict inequality](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Strict_inequality) for the operator.

```suggestion
      {attributeName !== "username" && (
```

2024-01-31 08:42 UTC, mposolda commented
@jonkoops Updated as you suggested. Thanks!

2024-01-31 09:00 UTC, jonkoops approved these changes
LGTM

2024-01-31 09:57 UTC, merged

2024-01-31 09:57 UTC, mposolda commented
@jonkoops Thanks!

2024-10-22 09:34 UTC, karanvishesh commented
Hey @mposolda, how can we make email as optional attribute from the keycloak admin console? Is it via user declarative profile, if yes, can you please suggest how can we do that. We are using jboss keycloak 15 image. Thanks!!