Introduce index.ftl into base account theme
keycloak/keycloak pull request #26596
Opened 2024-01-30 12:28 UTC by hmlnarik

Fixes: #26487

2024-01-30 13:57 UTC, hmlnarik commented on docs/documentation/server_development/topics/themes.adoc
> +consider extending the `base` theme. The `base` theme consists of a message bundle and therefore such implementation needs to start from scratch, including implementation of the main `index.ftl` Free
This intentionally does not mention UiPageProvider SPI for extending admin console as that should be documented on its own.

2024-01-31 13:53 UTC, jonkoops requested changes

2024-01-31 13:53 UTC, jonkoops commented on themes/src/main/resources/theme/base/account/index.ftl
> +<!DOCTYPE html>
No need to capitalize this.
```suggestion
<!doctype html>
```

2024-01-31 13:53 UTC, jonkoops commented on themes/src/main/resources/theme/base/account/index.ftl
> +<html>
Ideally a `lang` attribute is added as well. Not sure if we already have a theme property for that.
```suggestion
<html lang="en">
```

2024-01-31 13:53 UTC, jonkoops commented on themes/src/main/resources/theme/base/account/index.ftl
> +        <meta charset="UTF-8">
Can be lowercase as well.
```suggestion
        <meta charset="utf-8">
```

2024-01-31 13:53 UTC, jonkoops commented on themes/src/main/resources/theme/base/account/index.ftl
> +        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
No need for this, only old browsers use this, which we don't support.
```suggestion
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
```

2024-01-31 13:53 UTC, jonkoops commented on themes/src/main/resources/theme/base/account/index.ftl
> +        <link type="image/x-icon" rel="icon" href="data:image/x-icon;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAACOklEQVQ4ja2TPUwTcRjGf/e/O+hB21BahFYBB6oBY0wIRnfnIxoHFYPG6KaDu3Fw0UQnY2KYTNF
We can also just omit the favicon here.

2024-01-31 13:53 UTC, jonkoops commented on themes/src/main/resources/theme/base/account/index.ftl
> +        <div>${msg("accountManagementBaseThemeCannotBeUsedDirectly")}</div>
Semantically this should probably be a paragraph.
```suggestion
        <p>${msg("accountManagementBaseThemeCannotBeUsedDirectly")}</p>
```

2024-02-02 10:00 UTC, jonkoops requested changes
One small note, otherwise LGTM

2024-02-02 15:57 UTC, jonkoops approved these changes
LGTM

2024-02-06 13:29 UTC, ssilvert approved these changes

2024-02-06 13:29 UTC, merged