Release notes for Keycloak 24 with OIDC contributions
keycloak/keycloak pull request #27047
Opened 2024-02-15 11:38 UTC by mposolda

closes #25729

2024-02-15 21:52 UTC, andymunro commented on docs/documentation/release_notes/topics/24_0_0.adoc
> +This release contains support for Lightweight access tokens. This allows to use smaller access tokens for specified clients. Such tokens will not contain much
```suggestion
This release contains support for Lightweight access tokens. As a result, you can have smaller access tokens for specified clients. These tokens will have only a few 
```

2024-02-15 21:53 UTC, andymunro commented on docs/documentation/release_notes/topics/24_0_0.adoc
> +claims and hence will be much shorter in size. Note that lightweight access token is still JWT signed by the realm key by default and still contains some very basic claims.
```suggestion
claims, resulting in a smaller size. Note that lightweight access token is still JWT signed by the realm key by default and still contains some very basic claims.
```

2024-02-15 21:55 UTC, andymunro commented on docs/documentation/release_notes/topics/24_0_0.adoc
> +From this release, there is a flag *Add to lightweight access token* available on some OIDC protocol mappers. This flag allows to specify if particular claim will be added to lightweight
```suggestion
This release introduces an*Add to lightweight access token*  flag that is available on some OIDC protocol mappers. Use this flag to specify if a particular claim should be added to a lightweight
```

2024-02-15 21:57 UTC, andymunro commented on docs/documentation/release_notes/topics/24_0_0.adoc
> +access token. It is *OFF* by default, so most of the claims are not added by default. There is also client policy executor, which allows to specify if particular client request
```suggestion
access token. It is *OFF* by default, which means that most claims are not added. Also, a client policy executor exists. Use it to specify if a particular client request
```

2024-02-15 21:59 UTC, andymunro commented on docs/documentation/release_notes/topics/24_0_0.adoc
> +should use lightweight access tokens or regular access tokens. Note that in previous release, there was already added switch *Add to token introspection*, so it is possible to add
```suggestion
should use lightweight access tokens or regular access tokens. A previous release added  *Add to token introspection* switch. You use it to add
```

2024-02-15 22:02 UTC, andymunro commented on docs/documentation/release_notes/topics/24_0_0.adoc
> +claims, which are not present in the access token, into introspection endpoint response. Thanks to https://github.com/skabano[Shigeyuki Kabano] for the contribution and Thanks to
Use "that" to modify the meaning of the previous clause.
Use "which" to provide an additional clause that does not affect the meaning of the previous clause.
Also, precede "which" with a comma, but do not precede "that" with a comma.

2024-02-15 22:04 UTC, andymunro commented on docs/documentation/release_notes/topics/24_0_0.adoc
> +Since this release, we support `scope` parameter in the OAuth2/OIDC endpoint for token refresh. Note that it is possible to use it to request access tokens with smaller amount
```suggestion
Starting with this release, we support  the`scope` parameter in the OAuth2/OIDC endpoint for token refresh. You can use this parameter to request access tokens with a smaller amount
```

2024-02-15 22:06 UTC, andymunro commented on docs/documentation/release_notes/topics/24_0_0.adoc
> +of scopes than originally granted (so it is not possible to increase access token scope) and it does not affect scope of the refreshed refresh token. This works as
```suggestion
of scopes than originally granted, which means you cannot increase access token scope, and it does not affect the scope of the refreshed refresh token. This function works as
```

2024-02-15 22:09 UTC, andymunro commented on docs/documentation/release_notes/topics/24_0_0.adoc
> +There is new client policy executor `dpop-bind-enforcer`, which can be used to enforce DPoP is used for particular client. This is available just if `dpop` preview
```suggestion
A new client policy executor `dpop-bind-enforcer` is introduced. You can use it to enforce DPoP for a particular client if `dpop` preview
```

2024-02-15 22:09 UTC, andymunro commented on docs/documentation/release_notes/topics/24_0_0.adoc
> +feature is enabled. Thanks to https://github.com/tnorimat[Takashi Norimatsu] for the contribution.
```suggestion
 is enabled. Thanks to https://github.com/tnorimat[Takashi Norimatsu] for the contribution.
```

2024-02-15 22:10 UTC, andymunro commented on docs/documentation/release_notes/topics/24_0_0.adoc
> +It is possible to create EdDSA realm keys and use them as signature algorithms for various clients. For instance to sign tokens or for client authentication with signed JWT.
```suggestion
You can create EdDSA realm keys and use them as signature algorithms for various clients. For instance, you can use these keys to sign tokens or for client authentication with signed JWT.
```

2024-02-15 22:13 UTC, andymunro commented on docs/documentation/release_notes/topics/24_0_0.adoc
> +This includes also identity brokering where Keycloak itself signs client assertion used for `private_key_jwt` authentication to 3rd party identity provider. Thanks to
```suggestion
This feature includes identity brokering where {project_name} itself signs client assertions that are used for `private_key_jwt` authentication to third party identity provider. Thanks to
```

2024-02-15 22:14 UTC, andymunro commented on docs/documentation/release_notes/topics/24_0_0.adoc
> +for interoperability with some identity providers like Azure AD, which require the thumbprint to be present on the JWT. Thanks to https://github.com/MikeTangoEcho[MT] for the contribution.
```suggestion
OIDC identity providers now have the option *Add X.509 Headers to the JWT* for the case when client authentication with JWT signed by private key is used. This option can be useful
for interoperability with some identity providers such as Azure AD, which require the thumbprint to be present on the JWT. Thanks to https://github.com/MikeTangoEcho[MT] for the contribution.
```

2024-02-15 22:15 UTC, andymunro commented on docs/documentation/release_notes/topics/24_0_0.adoc
> +The CORS related Keycloak functionality was extracted into the SPI, which can allow additional flexibility. Just a note that `CorsSPI` is internal and may change in the
```suggestion
The CORS related Keycloak functionality was extracted into the SPI, which can allow additional flexibility. Note that `CorsSPI` is internal and may change in the
```

2024-02-15 22:22 UTC, andymunro requested changes
Looks good, @mposolda.  A few changes to suggest.

2024-02-16 01:08 UTC, tnorimat approved these changes

2024-02-16 07:30 UTC, mposolda commented
@andymunro Applied all your suggestions. Thanks!
@tnorimat Also Thanks for the review!

2024-02-16 07:34 UTC, merged