Replace Security Key with Passkey in WebAuthn UIs and their documents
keycloak/keycloak pull request #27151
Opened 2024-02-20 02:20 UTC by tnorimat

closes #27147

2024-02-20 13:13 UTC, mposolda approved these changes, later dismissed
@tnorimat Thanks!

2024-02-21 10:30 UTC, mposolda commented
@keycloak/ui-maintainers Anyone available to review UI changes in this PR please?

2024-02-26 11:16 UTC, jonkoops requested changes

2024-02-26 11:16 UTC, jonkoops commented on testsuite/integration-arquillian/tests/other/webauthn/src/test/java/org/keycloak/testsuite/webauthn/WebAuthnRegisterAndLoginTest.java
> +            // Password + WebAuthn passkey
```suggestion
            // Password + WebAuthn Passkey
```

2024-02-26 11:16 UTC, jonkoops commented on testsuite/integration-arquillian/tests/other/webauthn/src/test/java/org/keycloak/testsuite/webauthn/account/WebAuthnSigningInTest.java
> +            expectedHelpText = "Use your passkey for passwordless sign in.";
```suggestion
            expectedHelpText = "Use your Passkey for passwordless sign in.";
```

2024-02-26 11:16 UTC, jonkoops commented on testsuite/integration-arquillian/tests/other/webauthn/src/test/java/org/keycloak/testsuite/webauthn/account/WebAuthnSigningInTest.java
> +            expectedHelpText = "Use your passkey to sign in.";
```suggestion
            expectedHelpText = "Use your Passkey to sign in.";
```

2024-02-26 11:16 UTC, jonkoops commented on themes/src/main/resources/theme/base/login/messages/messages_en.properties
> +webauthn-passwordless-help-text=Use your passkey for passwordless sign in.
```suggestion
webauthn-passwordless-help-text=Use your Passkey for passwordless sign in.
```

2024-02-26 11:16 UTC, jonkoops commented on themes/src/main/resources/theme/keycloak.v2/account/messages/messages_en.properties
> +webauthn-passwordless-help-text=Use your passkey for passwordless sign in.
```suggestion
webauthn-passwordless-help-text=Use your Passkey for passwordless sign in.
```

2024-02-27 02:21 UTC, tnorimat commented on js/apps/account-ui/maven-resources/theme/keycloak.v3/account/messages/messages_en.properties
> +webauthn-display-name=PassKey
I fixed it.

2024-02-27 02:23 UTC, tnorimat commented on docs/documentation/server_admin/topics/account.adoc
> +image:images/account-console-signing-in-webauthn-2factor.png[Signing In With Passkey]
I fixed it.

2024-02-27 02:24 UTC, tnorimat commented on docs/documentation/server_admin/topics/account.adoc
> +image:images/account-console-signing-in-webauthn-2factor.png[Signing In With Passkey]
I fixed it.

2024-02-27 02:25 UTC, tnorimat commented on docs/documentation/server_admin/topics/account.adoc
> +. Click *Set up Passkey*.
I fixed it.

2024-02-27 02:26 UTC, tnorimat commented on docs/documentation/server_admin/topics/account.adoc
> +. Prepare your WebAuthn Passkey. How you prepare this key depends on the type of WebAuthn passkey you use. For example, for a USB based Yubikey, you may need to put your key into the USB port on your
I fixed it.

2024-02-27 02:26 UTC, tnorimat commented on docs/documentation/server_admin/topics/account.adoc
> +. Click *Set up Passkey* in the *Passwordless* section.
I fixed it.

2024-02-27 02:27 UTC, tnorimat commented on docs/documentation/server_admin/topics/account.adoc
> +image:images/account-console-signing-in-webauthn-passwordless.png[Signing In With Passkey]
I fixed it. I will update the screenshot.

2024-02-27 02:27 UTC, tnorimat commented on docs/documentation/server_admin/topics/account.adoc
> +image:images/account-console-signing-in-webauthn-passwordless.png[Signing In With Passkey]
I fixed it.

2024-02-27 02:29 UTC, tnorimat commented on docs/documentation/server_admin/topics/account.adoc
> +. Prepare your WebAuthn Passkey. How you prepare this key depends on the type of WebAuthn passkey you use. For example, for a USB based Yubikey, you may need to put your key into the USB port on your
I fixed it.

2024-02-27 02:37 UTC, tnorimat commented on docs/documentation/server_admin/topics/authentication/webauthn.adoc
> +If the *WebAuthn Register* required action is *Default Action* in a realm, new users must set up the WebAuthn passkey after their first login.
I fixed it.

2024-02-27 02:39 UTC, tnorimat commented on docs/documentation/server_admin/topics/authentication/webauthn.adoc
> +An administrator typically requires that Passkeys registered by users for the WebAuthn passwordless authentication meet different requirements. For example, the passkeys may require users to authenti
I fixed it.

2024-02-27 02:40 UTC, tnorimat commented on docs/documentation/server_admin/topics/authentication/webauthn.adoc
> +. Configure the policy. You can use the steps and configuration options described in <<_webauthn-policy, Managing Policy>>. Perform the configuration in the Admin Console in the tab *WebAuthn Passwor
I fixed it.

2024-02-27 02:42 UTC, tnorimat commented on docs/documentation/server_admin/topics/authentication/webauthn.adoc
> +An administrator typically requires that Passkeys registered by users for the WebAuthn loginless authentication meet different requirements. Loginless authentication requires users to authenticate to
I fixed it.

2024-02-27 02:44 UTC, tnorimat commented on docs/documentation/server_admin/topics/authentication/webauthn.adoc
> +. Configure the `WebAuthn Passwordless Policy`. Perform the configuration in the Admin Console, `Authentication` section,  in the tab `Policies` ->  `WebAuthn Passwordless Policy`. You have to set *U
I fixed it.

2024-02-27 02:45 UTC, tnorimat commented on docs/documentation/server_admin/topics/authentication/webauthn.adoc
> +Loginless authentication with {project_name} requires the passkey to meet the following features
I fixed it.

2024-02-27 02:45 UTC, tnorimat commented on docs/documentation/server_admin/topics/authentication/webauthn.adoc
> +** User verification: the ability for the passkey to authenticate the user (prevents someone finding your passkey to be able to authenticate loginless and passwordless)
I fixed it.

2024-02-27 02:56 UTC, tnorimat commented on docs/documentation/server_admin/topics/authentication/webauthn.adoc
> +** Discoverable Credential: the ability for the passkey to store the login and the cryptographic keys associated with the client application
I fixed it.

2024-02-27 02:57 UTC, tnorimat commented on docs/documentation/server_admin/topics/authentication/webauthn.adoc
> +To use Windows Hello based credentials to authenticate against {project_name}, configure the *Signature Algorithms* setting of the `WebAuthn Passwordless Policy` to include the *RS256* value. Note th
I fixed it.

2024-02-27 02:58 UTC, tnorimat commented on docs/documentation/server_admin/topics/authentication/webauthn.adoc
> +====== Supported passkeys
I fixed it.

2024-02-27 02:58 UTC, tnorimat commented on docs/documentation/server_admin/topics/authentication/webauthn.adoc
> +The following passkeys have been successfully tested for loginless authentication with {project_name}:
I fixed it.

2024-02-27 03:48 UTC, tnorimat commented on testsuite/integration-arquillian/tests/other/webauthn/src/test/java/org/keycloak/testsuite/webauthn/WebAuthnIdlessTest.java
> +                is("Use your passkey for passwordless sign in."));
I fixe it.

2024-02-27 03:49 UTC, tnorimat commented on testsuite/integration-arquillian/tests/other/webauthn/src/test/java/org/keycloak/testsuite/webauthn/WebAuthnRegisterAndLoginTest.java
> +                    is("Use your passkey for passwordless sign in."));
I fixed it.

2024-02-27 03:49 UTC, tnorimat commented on testsuite/integration-arquillian/tests/other/webauthn/src/test/java/org/keycloak/testsuite/webauthn/WebAuthnRegisterAndLoginTest.java
> +            // Password + WebAuthn passkey
I fixed it.

2024-02-27 03:53 UTC, tnorimat commented on testsuite/integration-arquillian/tests/other/webauthn/src/test/java/org/keycloak/testsuite/webauthn/account/WebAuthnSigningInTest.java
> +            expectedHelpText = "Use your passkey for passwordless sign in.";
I fixed it.

2024-02-27 03:54 UTC, tnorimat commented on themes/src/main/resources/theme/base/login/messages/messages_en.properties
> +webauthn-passwordless-help-text=Use your passkey for passwordless sign in.
I fixed it.

2024-02-27 04:02 UTC, tnorimat commented on themes/src/main/resources/theme/keycloak.v2/account/messages/messages_en.properties
> +webauthn-passwordless-help-text=Use your passkey for passwordless sign in.
I fixed it.

2024-02-27 04:24 UTC, tnorimat commented on docs/documentation/server_admin/topics/authentication/webauthn.adoc
> +You can now add the required action `WebAuthn Register Passwordless` to a user, already known to {project_name}, to test this. The user with the required action configured will have to authenticate (
I fixed it.

2024-02-27 07:00 UTC, tnorimat commented on docs/documentation/server_admin/topics/account.adoc
> +. Click *Register* to register your passkey.
I fixed it.

2024-02-27 07:00 UTC, tnorimat commented on docs/documentation/server_admin/topics/account.adoc
> +image:images/account-console-signing-in-webauthn-passwordless.png[Signing In With Passkey]
I updated the two screenshots.

2024-02-27 07:01 UTC, tnorimat commented
@jonkoops Thank you for your review comments. I incorporated all of your review comments into the PR. Could you check them?

2024-02-28 09:54 UTC, jonkoops approved these changes, later dismissed
LGTM!

2024-02-28 11:16 UTC, mposolda approved these changes, later dismissed
@tnorimat @jonkoops Thanks for the updates and review! I hope to merge once tests are OK

2024-02-28 16:50 UTC, mposolda commented
@tnorimat Could you please rebase? That should help with fixing the test failure in FIPS tests (it was fixed today in Keycloak main).

2024-02-29 01:03 UTC, tnorimat commented
@mposolda I rebased the PR on the main branch.

2024-02-29 07:22 UTC, ahus1 approved these changes
re-approving after @mposolda's review and rebase

2024-02-29 07:39 UTC, ahus1 commented
@jonkoops - could you please re-approve after the rebase? Thanks!

2024-02-29 09:30 UTC, mposolda approved these changes
@tnorimat Thanks for the rebase!

2024-02-29 09:31 UTC, merged