Set the selected locale to default realm locale when creating a user
keycloak/keycloak pull request #27163
Opened 2024-02-20 10:37 UTC by pkeuter

Closes #27162

2024-02-21 10:00 UTC, edewit requested changes

2024-02-21 10:30 UTC, pkeuter commented
@edewit Unfortunately, accepting your fix didn't work since the `setValue` function does not take undefined. I could bypass that by adding the `!`-operator but I think it's better to check the value for undefined. Do you agree?

2024-02-21 11:48 UTC, edewit commented
how about:
```
        form.setValue("attributes.locale", realm.defaultLocale || "");
```

2024-02-21 11:56 UTC, pkeuter commented
> how about:
> 
> ```js
>         form.setValue("attributes.locale", realm.defaultLocale || "");
> ```

Absolutely. Done!

2024-02-26 08:19 UTC, edewit approved these changes

2024-02-26 08:19 UTC, merged