Additional release notes for Keycloak 24
keycloak/keycloak pull request #27339
Opened 2024-02-28 09:28 UTC by mposolda

closes #27142

2024-02-28 19:58 UTC, andymunro commented on docs/documentation/release_notes/topics/24_0_0.adoc
> +will be compliant with OAuth 2.1 specification. There is dedicated client profile for confidential clients and dedicated profile for public clients.
```suggestion
This release contains optional OAuth 2.1 support. New client policy profiles were introduced in this release, which administrators can use to make sure that clients and particular client requests comply with the OAuth 2.1 specification. A dedicated client profile exists for confidential clients and a dedicated profile for public clients.
```

2024-02-28 20:00 UTC, andymunro commented on docs/documentation/release_notes/topics/24_0_0.adoc
> +A new client policy executor `secure-redirect-uris-enforcer` is introduced. Use it to restrict what are the redirect URIs, which can be used by the clients. For instance
```suggestion
A new client policy executor `secure-redirect-uris-enforcer` is introduced. Use it to restrict which redirect URIs can be used by the clients. For instance, 
```

2024-02-28 20:03 UTC, andymunro commented on docs/documentation/release_notes/topics/24_0_0.adoc
> +Internal update in the {project_name} codebase was done to introduce OAuth Grant Type SPI. This allows additional flexibility when introducing custom grant types
```suggestion
The {project_name} codebase includes an internal update  to introduce the OAuth Grant Type SPI. This update allows additional flexibility when introducing custom grant types
```

2024-02-28 20:03 UTC, andymunro commented on docs/documentation/release_notes/topics/24_0_0.adoc
> +supported by {project_name} OAuth 2 token endpoint.
```suggestion
supported by the {project_name} OAuth 2 token endpoint.
```

2024-02-28 20:05 UTC, andymunro commented on docs/documentation/server_admin/topics/clients/client-policies.adoc
> +for marking that particular client policy should be used for particular clients.
```suggestion
NOTE: A use-case often exists for requiring the application of a particular client policy for the specified clients such as `my-client-1` and `my-client-2`. The best way to achieve this result 
is to use a *Client Role* condition in your policy and then a create client role of specified name to requested clients. This client role can be used as a "marker role" used solely
for marking that particular client policy should be used for particular clients.
```

2024-02-28 20:09 UTC, andymunro requested changes
Looks good, @mposolda. A few suggestions.

2024-02-29 07:42 UTC, mposolda commented
@andymunro Thanks!

2024-02-29 07:43 UTC, merged