Fix error messages for unmanaged attributes
keycloak/keycloak pull request #27362
Opened 2024-02-28 16:32 UTC by hmlnarik

Fixes: #25977

This fixes multiple issues:
1. The `updateReadOnlyAttributesRejectedMessage` key is added to the correct bundle (first commit)
2. The form can be saved multiple times. Originally it was not possible to resubmit the form if errors were present on attributes and the form had to be reloaded
3. The errors are attached to the respective unmanaged attributes (see the image below)

![image](https://github.com/keycloak/keycloak/assets/5391360/449422ad-a625-4f40-96f7-e6c5e7db0e79)

2024-02-28 18:07 UTC, jonkoops requested changes

2024-02-29 10:18 UTC, hmlnarik commented on js/apps/admin-ui/src/components/key-value-form/KeyValueInput.tsx
> +            (errors as any)[name]?.[index]?.message || t("valueError");
Makes perfect sense

2024-02-29 10:18 UTC, hmlnarik commented on js/apps/admin-ui/src/user/EditUser.tsx
> +        const unmanagedAttributesInputs = form.getValues()[
That would be good. My concern is re type of `data.unmanagedAttributes` which is `KeyValueType[] | Record<string, string | string[]>` while here I need to have `KeyValueType[]`. Can `data.unmanagedAttributes` be retyped just to `KeyValueType[]`?

```suggestion
const unmanagedAttributesInputs = data.unmanagedAttributes as KeyValueType[];
```

2024-02-29 11:11 UTC, jonkoops commented on js/apps/admin-ui/src/user/EditUser.tsx
> +        const unmanagedAttributesInputs = form.getValues()[
Yeah, that is an option. You could also narrow the type using a run-time check, which is the most 'safe'. For example:

```ts
const unmanagedAttributesInputs = data.unmanagedAttributes;

if (!Array.isArray(unmanagedAttributesInputs)) {
  return;
}

// TypeScript knows that unmanagedAttributesInputs is KeyValueType[]
```

2024-02-29 11:36 UTC, hmlnarik commented on js/apps/admin-ui/src/user/EditUser.tsx
> +        const unmanagedAttributesInputs = form.getValues()[
I fixed this along this suggestion and simplified a bit further, thanks for the hint!

2024-03-01 12:31 UTC, jonkoops approved these changes
LGTM

2024-03-01 13:03 UTC, vmuzikar approved these changes
Approving based on @jonkoops' review.

2024-03-01 13:03 UTC, merged