migrated some of the controls to ui-shared
keycloak/keycloak pull request #27424
Opened 2024-03-01 13:16 UTC by edewit

Signed-off-by: Erik Jan de Wit <erikjan.dewit@gmail.com>

2024-03-01 13:56 UTC, jonkoops requested changes

2024-03-01 13:56 UTC, jonkoops commented on js/apps/admin-ui/src/user-federation/ldap/LdapSettingsGeneral.tsx
> +          id="kc-ui-provider-id"
Lets get rid of the `id`.
```suggestion
          id="kc-ui-provider-id"
```

2024-03-01 13:56 UTC, jonkoops commented on js/apps/admin-ui/src/user-federation/ldap/LdapSettingsGeneral.tsx
> +          id="kc-ui-provider-type"
```suggestion
```

2024-03-01 13:56 UTC, jonkoops commented on js/apps/admin-ui/src/user-federation/ldap/LdapSettingsGeneral.tsx
> +          id="kc-ui-parentId"
```suggestion
```

2024-03-01 13:56 UTC, jonkoops commented on js/apps/admin-ui/src/user-federation/ldap/LdapSettingsGeneral.tsx
> +            },
I might be wrong, but I believe this could be shortened to:
```suggestion
            required: t("validateName").toString(),
```

2024-03-01 13:56 UTC, jonkoops commented on js/apps/admin-ui/src/user-federation/ldap/LdapSettingsKerberosIntegration.tsx
> +                },
```suggestion
                required: t("validateRealm").toString(),
```

2024-03-01 13:56 UTC, jonkoops commented on js/apps/admin-ui/src/user-federation/ldap/LdapSettingsKerberosIntegration.tsx
> +                },
```suggestion
                required: t("validateServerPrincipal").toString(),
```

2024-03-01 13:56 UTC, jonkoops commented on js/apps/admin-ui/src/user-federation/ldap/LdapSettingsKerberosIntegration.tsx
> +                },
```suggestion
                required: t("validateKeyTab").toString(),
```

2024-03-01 13:56 UTC, jonkoops commented on js/apps/admin-ui/src/user-federation/ldap/LdapSettingsSearching.tsx
> +          defaultValue=""
This can be omitted, as it is the default value for `TextControl` if no value was provided.
```suggestion
```

2024-03-01 13:56 UTC, jonkoops commented on js/apps/admin-ui/src/user-federation/ldap/LdapSettingsSearching.tsx
> +            },
```suggestion
            required: t("validateUsersDn").toString(),
```

2024-03-01 13:56 UTC, jonkoops commented on js/apps/admin-ui/src/user-federation/ldap/LdapSettingsSearching.tsx
> +            },
```suggestion
            required: t("validateUsernameLDAPAttribute").toString(),
```

2024-03-01 13:56 UTC, jonkoops commented on js/apps/admin-ui/src/user-federation/ldap/LdapSettingsSearching.tsx
> +            },
```suggestion
            required: t("validateUuidLDAPAttribute").toString(),
```

2024-03-04 13:42 UTC, jonkoops approved these changes, later dismissed

2024-03-04 17:11 UTC, jonkoops submitted a review, later dismissed

2024-03-05 16:32 UTC, jonkoops approved these changes, later dismissed

2024-03-05 17:02 UTC, agagancarczyk approved these changes, later dismissed

2024-03-06 08:40 UTC, agagancarczyk approved these changes

2024-03-06 08:40 UTC, merged