docs(cpu and memory sizing): typo GB -> MB
keycloak/keycloak pull request #27505
Opened 2024-03-04 15:17 UTC by ahus1

Closes #27504

2024-03-04 15:24 UTC, mhajas approved these changes
Thanks @ahus1 @vojtechmares!

2024-03-04 17:15 UTC, jonkoops requested changes
@ahus1 make sure to cherry-pick the commit that was actually merged into `main`, rather than the commit as it was on the branch of the author.

2024-03-05 09:35 UTC, ahus1 commented
@jonkoops - I've updated the commit in the original PR to reference an issue, as I was planning to backport it to KC24. 
I then cherry-picked that updated commit from the main branch, which is now in this PR. See 823065588019416e7ad6ba8bb44d88c215bca6fc for the original commit.

AFAIK things are fine here. Please let me know if I missed something.

2024-03-05 10:19 UTC, jonkoops approved these changes

2024-03-05 10:24 UTC, merged