Update docs about when emails for changed credentials are sent
keycloak/keycloak pull request #27621
Opened 2024-03-06 16:32 UTC by ahus1

Closes #27620

2024-03-06 16:42 UTC, jonkoops submitted a review, later dismissed

2024-03-06 17:00 UTC, mposolda approved these changes, later dismissed

2024-03-06 18:56 UTC, ahus1 commented
@andymunro - could you please review the text changes when you have the time? Thanks!

2024-03-06 19:10 UTC, andymunro commented on docs/documentation/server_admin/topics/events/login.adoc
> +The Email Event Listener sends an email message to the user's email address when an event occurs and supports the following events:
```suggestion
The Email Event Listener sends a message to the user's email address when an event occurs and supports the following events:
```

2024-03-06 19:10 UTC, andymunro requested changes
Approved with one change.

2024-03-06 19:12 UTC, ahus1 commented
@mposolda - please re-approve when you have the time. Thanks!

2024-03-06 19:51 UTC, andymunro approved these changes

2024-03-07 06:16 UTC, stianst approved these changes

2024-03-07 06:16 UTC, merged