Limit the received content when handling the content as a String.
keycloak/keycloak pull request #27656
Opened 2024-03-07 11:10 UTC by ahus1

Closes #27293

2024-03-07 11:17 UTC, ahus1 commented
@rmartinc - as I've been working on the other issue, I had an idea on how to limit the response size without moving to v5 of the library. 

The maximum response size can be configured for `DefaultHttpClientFactory`, but all users of `SimpleHttp` would set their own maximum size. I don't have a good idea where to pull this information from. 

Maybe it is good enough for now? WDYT?

2024-03-07 17:15 UTC, ahus1 commented
@rmartinc - I've updated this PR. Please let me know if you think this is a valid approach when you have the time. 

Pinging also @abstractj as you've been managing the original issue.

2024-03-08 09:58 UTC, rmartinc requested changes
Very good job @ahus1!
Just some minor things that maybe you can consider to add.

2024-03-08 09:58 UTC, rmartinc commented on server-spi-private/src/main/java/org/keycloak/connections/httpclient/SafeInputStream.java
> +            throw new IOException(String.format("Response is longer than %s, with max bytes to be consumed being %d", bytesConsumed, maxBytesToConsume));
Just a minor thing, but this wouldn't be `>` insteadof `>=`, just to allow exact number. And I would use: ` Response is at least %s bytes in size, with max...`.

2024-03-08 09:58 UTC, rmartinc commented on server-spi-private/src/main/java/org/keycloak/connections/httpclient/SafeInputStream.java
> +        bytesConsumed += sizeRead;
Better do the same than in single read: `if (sizeRead > 0) bytesConsumed += sizeRead;`

2024-03-08 09:58 UTC, rmartinc commented on server-spi-private/src/test/java/org/keycloak/broker/provider/util/SimpleHttpTest.java
> +            SimpleHttp.Response response = new SimpleHttp.Response(httpResponse, HttpClientProvider.DEFAULT_MAX_CONSUMED_RESPONSE_SIZE);
I think we could add a test here too. I did something quick in this commit: https://github.com/rmartinc/keycloak/commit/1e6562339d8296c77f6a84fba2181be9f198c2ff
You can use it or something similar.

2024-03-11 17:12 UTC, rmartinc approved these changes
Thanks for the changes! Good idea limiting `SimpleHttp` to the methods that pass the session. LGTM now! Let's see the tests!

2024-03-11 18:25 UTC, abstractj approved these changes

2024-03-11 18:25 UTC, abstractj submitted a review, later dismissed

2024-03-12 09:47 UTC, ahus1 commented
@abstractj - I needed to rebase the PR due to conflicts in the documentation. Please re-approve when you have the time. Thanks!

2024-03-12 10:57 UTC, rmartinc approved these changes

2024-03-13 15:42 UTC, abstractj approved these changes

2024-03-13 15:43 UTC, merged