migrated discovery field
keycloak/keycloak pull request #27762
Opened 2024-03-11 11:23 UTC by edewit

Signed-off-by: Erik Jan de Wit <erikjan.dewit@gmail.com>

2024-03-11 13:00 UTC, jonkoops requested changes

2024-03-12 09:48 UTC, edewit commented on js/apps/admin-ui/src/identity-providers/add/AddOpenIdConnect.tsx
> +    mode: "onChange",
yes, so that the validate is triggered once the value has changed and not only on submit

2024-03-12 09:49 UTC, edewit commented on js/apps/admin-ui/src/identity-providers/component/DiscoveryEndpointField.tsx
>            validated={
Yes, because we want to have it go to "success" state once the values have been imported, otherwise it will go back to default

2024-03-12 10:30 UTC, jonkoops commented on js/apps/admin-ui/src/identity-providers/component/DiscoveryEndpointField.tsx
>            validated={
Makes sense, thanks

2024-03-12 13:11 UTC, jonkoops commented
I'd like to add some improved error handling, so let's wait for #27805 to be merged.

2024-03-12 15:27 UTC, jonkoops approved these changes
Let's get this one merged first.

2024-03-12 15:28 UTC, merged