use inputOptionLabels in select-radiobuttons input elements
keycloak/keycloak pull request #27782
Opened 2024-03-11 17:20 UTC by lme-atolcd

If available,  `select-radiobuttons` input elements will use `inputOptionLabels` annotation to provide labels for individual options.
This feature is already documented here https://www.keycloak.org/docs/latest/server_admin/index.html#_managing_options_for_select_fields, but it only works with `select` input element (not `select-radiobuttons`).

2024-03-25 09:44 UTC, edewit requested changes
Sorry seems I have already fixed this

2024-03-25 14:27 UTC, lme-atolcd commented
Hi @edewit, are you referencing #28087 as the fix?
If yes, I don't understand how adding a "on" label would help to translate input radio labels.
I've added a comment on the pull-request.

2024-04-05 10:32 UTC, edewit commented
@lme-atolcd well somebody else told me that it should be 'on' and to be honest the documentation isn't helping much as to how this should work

2024-04-05 13:30 UTC, edewit commented
there is also #28473 that fixes this

2024-04-05 15:16 UTC, jonkoops commented
Closing this in favor of #28473, thanks @lme-atolcd!

2024-04-05 15:16 UTC, closed without merging