User Profile attribute translation saves correct key to realm overrides
keycloak/keycloak pull request #28053
Opened 2024-03-19 14:43 UTC by agagancarczyk

Closes https://github.com/keycloak/keycloak/issues/28016

2024-03-19 17:00 UTC, jonkoops requested changes

2024-03-19 17:00 UTC, jonkoops commented on js/apps/admin-ui/src/realm-settings/user-profile/attribute/AttributeGeneralSettings.tsx
> +              : "profile.attributes." + `${newAttributeName}`
Let's use string interpolation for the entire string.
```suggestion
              : `profile.attributes.${newAttributeName}`
```

2024-03-20 11:46 UTC, jonkoops approved these changes

2024-03-20 11:46 UTC, merged

2024-03-20 11:47 UTC, jonkoops commented
LGTM, let's make sure to backport this.

2024-03-20 13:54 UTC, agagancarczyk commented
> LGTM, let's make sure to backport this.

hi @jonkoops this can't be backported as this functionality hasn't been released yet, it will be released in 25

2024-03-20 14:47 UTC, jonkoops commented
My bad, I thought this was a fix for something that broke in 24.