Changed package names in order to publish
keycloak/keycloak pull request #28157
Opened 2024-03-22 07:32 UTC by edewit

Added documentation version and docs to be able to publish these packages

- **changed name and added version number**
- **added readme for package usage**

2024-03-25 12:59 UTC, ssilvert requested changes
I'm wondering about how we deal with the names we have now exported.  

I think we at least should guarantee that code derived from our account ui will not break from a minor release.

Any ideas on how we make sure not to change what is essentially now a public API?  Maybe we could create tests that use all the names so code won't build if we change an exported name?

2024-03-27 14:06 UTC, edewit commented
> I'm wondering about how we deal with the names we have now exported.
> 
It's just a component name, even if we would want to change that at some point internally we could still export it under a different alias

> I think we at least should guarantee that code derived from our account ui will not break from a minor release.
> 
> Any ideas on how we make sure not to change what is essentially now a public API? Maybe we could create tests that use all the names so code won't build if we change an exported name?

I don't see how this is different from what we already have with the other customisation features. I would suggest to make a quickstart that get tested each with each release

2024-03-28 16:07 UTC, jonkoops reviewed
Let's hold off on this until we move to PatternFly 5, as I see a lot of merge conflicts waiting to happen.

2024-04-17 11:24 UTC, jonkoops requested changes
Got one small thing, but otherwise LGTM, there are also some small linting errors that will need to be fixed for CI to pass.

2024-04-17 11:24 UTC, jonkoops commented on js/apps/account-ui/package.json
> +  "version": "0.0.5-alpha",
If this package is published we should use `999.0.0-SNAPSHOT` as a version, that will then be replaced by the actual release version when the release is ran.
```suggestion
  "version": "999.0.0-SNAPSHOT",
```

2024-04-19 14:40 UTC, jonkoops approved these changes

2024-04-19 18:10 UTC, ssilvert approved these changes

2024-04-19 18:10 UTC, merged