fix: do not re-neable AuthorizationService if it is already enabled
keycloak/keycloak pull request #28160
Opened 2024-03-22 09:00 UTC by Tasssadar

The enable action needs the realm-wide "modify client" permission, which restricted admins with the fine-grained-authz feature do not have.

This causes a "forbidden" exception when try try to save a client with Authorization already enabled, even if the "enable" action does nothing since it was already enabled.

Fixes #22938

2024-04-18 19:54 UTC, pedroigor requested changes
@Tasssadar Thanks. LGTM but you need to sign-off the commit.

2024-05-22 15:56 UTC, Tasssadar commented
Hello, the commit is now signed, would you please take a look again @pedroigor?

2024-12-19 08:47 UTC, Tasssadar commented
Rebased to current `main`, would you please take a look?

2025-11-10 12:03 UTC, pedroigor approved these changes

2025-11-10 13:20 UTC, merged