Fix help key for firstBrokerLoginFlowAliasOverrideHelp
keycloak/keycloak pull request #28257
Opened 2024-03-27 23:48 UTC by ssilvert

Fixes #27691.  Most if this issue was already fixed.  The only thing left was to fix help text for `firstBrokerLoginFlowAliasOverrideHelp`.  Just needed to change to a different key in all the message bundles.

VS Code automatically made a several other changes, fixing line endings and such.  I'm not 100% sure it always did the right thing though.

2024-03-28 15:59 UTC, jonkoops requested changes

2024-03-28 15:59 UTC, jonkoops commented on js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_es.properties
Looks like this file suddenly has changes to the unicode contents as well. I am seeing a lot of weird conversion going on. Perhaps this is the IDE automatically using ANSI or something. @ssilvert I reccomend that you take a look at [this post](https://stackoverflow.com/questions/4659929/how-to-use-utf-8-in-resource-properties-with-resourcebundle#answer-4660195), as you'll likely want to change the default charset in IntelliJ.

2024-03-29 18:55 UTC, ssilvert commented on js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_es.properties
So it looks like the `messages_es.properties` was the only one that had a real issue.  The rest were just removing extra line endings, which I think is what we want.

To fix `messages_es.properties`, I had to use VS Code's `reopen` feature.  In bottom right, you select the `UTF-8` and then pick `Select Encoding`, then `Reopen with Encoding`.  Then I selected `ISO-8859-1`.

2024-04-02 16:34 UTC, jonkoops approved these changes
LGTM

2024-04-02 16:36 UTC, merged