Fixed loading translation values for User Profile attributes
keycloak/keycloak pull request #28408
Opened 2024-04-03 13:53 UTC by agagancarczyk

Closes https://github.com/keycloak/keycloak/issues/27837

2024-04-03 13:54 UTC, jonkoops approved these changes, later dismissed

2024-04-03 15:34 UTC, agagancarczyk commented on js/apps/admin-ui/src/realm-settings/user-profile/attribute/AddTranslationsDialog.tsx
> +  useEffect(() => {
sounds good @jonkoops

2024-04-04 01:14 UTC, ssilvert requested changes
I tried the code out and it's not working.  When I click on the button to bring up the translations dialog I get a NullPointerException on the server.  I am using the latest nightly build of the server.
`Caused by: java.lang.NullPointerException: Cannot invoke "org.keycloak.models.UserSessionModel.getUser()" because "userSession" is null`

The request that is failing is `http://localhost:8180/admin/realms/test/localization/en`.
500 Internal Server Error

@agagancarczyk Maybe try this with the latest nightly and see if you see this too?

2024-04-04 07:44 UTC, jonkoops commented
@ssilvert I've also been seeing that error locally in other places, it is related how things are proxied during development. It should work if you do a full production build and test against that. Unfortunately, this also makes it impossible to run the Cypress tests on some suites against the development server.

I think we should unify the dev server and the Keycloak server, so that the Keycloak server always is responsible for serving the front-end, even during development. I've started #27311 as a thought experiment on how to accomplish this.

2024-04-04 20:30 UTC, ssilvert commented
@agagancarczyk @jonkoops OK, I was able to run the code by doing a full build and scenario 1 is fixed.

I am still seeing scenario 2 from the issue.  Agi, note that I updated the steps for scenario 2 as I was unclear in my original post.

I also added scenario 3, which is another related problem.  See the issue.

2024-04-04 20:32 UTC, ssilvert commented
> I think we should unify the dev server and the Keycloak server, so that the Keycloak server always is responsible for serving the front-end, even during development. I've started #27311 as a thought experiment on how to accomplish this.

@jonkoops That would be amazing if you can pull it off.  It would also solve some other problems I've seen such as changes to message bundles that are not being reflected in dev mode.

2024-04-04 21:42 UTC, jonkoops commented
I'll try to put some time into it when we're done with the PatternFly migration :+1:

2024-04-05 09:37 UTC, agagancarczyk commented
> @agagancarczyk @jonkoops OK, I was able to run the code by doing a full build and scenario 1 is fixed.
> 
> I am still seeing scenario 2 from the issue. Agi, note that I updated the steps for scenario 2 as I was unclear in my original post.
> 
> I also added scenario 3, which is another related problem. See the issue.

@ssilvert scenario 2 has also been fixed. Can you try again? I pushed a fix yesterday. Maybe you are expecting something else? I'll take a look at scenario 3.

2024-04-18 15:53 UTC, agagancarczyk commented
Closing this PR as it's old in favour of https://github.com/keycloak/keycloak/pull/28899

2024-04-18 15:53 UTC, closed without merging