Memoize rendering flow diagram. Fixes #28449
keycloak/keycloak pull request #28451
Opened 2024-04-04 17:34 UTC by adhurjaty

Fixes #28449

Move the rendering of the flow diagram to a `useMemo` so it is correctly formatted by the time it is displayed

2024-04-04 21:51 UTC, jonkoops requested changes

2024-04-04 21:51 UTC, jonkoops commented on js/apps/admin-ui/src/authentication/FlowDetails.tsx
Perhaps rather than memoizing these values we could show a loading spinner until `executionList` has loaded, that should prevent it from getting mounted with data that doesn't exist.

2024-04-04 22:48 UTC, adhurjaty commented on js/apps/admin-ui/src/authentication/FlowDetails.tsx
I'm not sure what value to listen to for showing/hiding the loading spinner. In main, the `FlowDiagram` is only rendered if `executionList?.expandableList` is truthy, so listening to that value to conditionally show/hide a loading spinner won't fix the display issue.

The problem with the current version is that for some reason if the `FlowDiagram` is created and visibly rendered at the same time, the nodes don't get placed in the correct position. My solution is to create this element before it's displayed, which gives it time to do ??? then display this saved element when the user wants

2024-04-05 14:37 UTC, adhurjaty commented on js/apps/admin-ui/src/authentication/FlowDetails.tsx
The real fix is that the `FlowDiagram` component is being constructed as soon as `executionList` is loaded, not waiting for the user to click the diagram button to construct it. I'm using `useMemo` so the logic doesn't re-run on every state change (only on changes to `executionList`). I'll change the commit message/PR title to reflect this

2024-04-05 14:59 UTC, adhurjaty commented
Looks like the issue was fixed in a recent commit

2024-04-05 14:59 UTC, closed without merging

2024-04-05 15:03 UTC, jonkoops commented
Was looking to reproduce the issue and was not able to either. Thanks anyways @adhurjaty!