Denylist improvements
keycloak/keycloak pull request #28450
Opened 2024-04-04 17:30 UTC by cmiles74

We always lower case the inbound password before comparing against the deny list yet the deny list may contain passwords that contain upper case letters. With this change we will now convert passwords from the deny list into lower case while loading, ensuring that more passwords match the deny list.

2024-04-09 11:59 UTC, pedroigor reviewed
@cmiles74 LGTM. I guess you mean https://github.com/keycloak/keycloak/blob/main/server-spi-private/src/main/java/org/keycloak/policy/BlacklistPasswordPolicyProvider.java#L49.

We need an issue describing the problem you are solving and linking it in the commit.

Other than that, LGTM.

2024-04-09 12:40 UTC, cmiles74 commented
Yes, that's the one. I ran into an issue with a list that had passwords with both upper and lower case letters (although most were uppercase). The issue is over here...
- [28381: Password Denylist Doesn't Work as Expected](8fb6d43e073471ce01583760c8c8582062fad953)

Thank you! 🙂

2024-04-12 10:56 UTC, rmartinc requested changes
@cmiles74 The code changes looks good to me. Just two requests:

1. Please also change the documentation ([here](https://github.com/keycloak/keycloak/blob/24.0.2/docs/documentation/server_admin/topics/authentication/password-policies.adoc?plain=1#L89)). I would just remove the second sentence in that line.
2. Please squash the two commits in a single one and add a second line in the commit message with `Closes #28381` (we use that to link the PR/commit with the fixed issue). And add the `--signoff` as you have already done. You have this info in the [contributing page](https://github.com/keycloak/keycloak/blob/main/CONTRIBUTING.md).

Thanks a lot for the fix and even more for the tests! :smile:

2024-04-12 13:21 UTC, cmiles74 commented
I think this is all set, I updated the documentation and I've squashed down to one commit. 🙂

2024-04-12 17:56 UTC, rmartinc approved these changes
Thanks! Approved!

2024-04-15 06:49 UTC, mposolda approved these changes
@cmiles74 @rmartinc Thanks for the fix and review!

2024-04-15 06:49 UTC, merged