use label function to fetch the translation
keycloak/keycloak pull request #28473
Opened 2024-04-05 13:29 UTC by edewit

fixes: #28443
Signed-off-by: Erik Jan de Wit <erikjan.dewit@gmail.com>

2024-04-05 13:41 UTC, pedroigor submitted a review, later dismissed

2024-04-05 15:12 UTC, jonkoops requested changes
Looks like `unWrap()` is no longer used anywhere but the module it resides in, so let's remove the `export` statement so that it's private. That should avoid anyone from importing it by accident in the future.

2024-04-07 09:41 UTC, john-gom commented
Also fixes #28484

2024-04-08 08:03 UTC, jonkoops approved these changes

2024-04-08 08:28 UTC, merged