Fix incorrect branching for some authentication flow diagrams. Fixes #28479
keycloak/keycloak pull request #28480
Opened 2024-04-05 18:27 UTC by adhurjaty

Refactor the FlowDiagram class and set required flows to more reliably appear in series with their next step

Fixes #28479

2024-04-05 18:32 UTC, adhurjaty commented
This is a pretty big change to code that has no unit tests. How open is the team to me adding a new test file for `FlowDiagram`?

2024-04-05 22:10 UTC, jonkoops commented
> This is a pretty big change to code that has no unit tests. How open is the team to me adding a new test file for `FlowDiagram`?

We are always open for test suite improvements :+1:

2024-04-05 23:48 UTC, adhurjaty commented
This change introduces an issue where the warning
```
Warning: Received NaN for the `cx` attribute. If this is expected, cast the value to a string.
<stack trace>
```
is printed out to console when running the admin-cli tests. This does not cause any of the tests to fail, but is not ideal. I'm not sure how to fix this issue

2024-04-09 12:28 UTC, edewit submitted a review, later dismissed

2024-04-09 15:03 UTC, jonkoops requested changes, later dismissed

2024-04-09 15:03 UTC, jonkoops commented on js/apps/admin-ui/src/authentication/__tests__/FlowDiagram.test.tsx
This might be a better candidate for Cypress tests, I'd prefer we test these things in actual browsers.

2024-04-12 21:36 UTC, adhurjaty commented on js/apps/admin-ui/src/authentication/__tests__/FlowDiagram.test.tsx
Added a cypress test. Was this the kind of thing you had in mind?

2024-04-17 09:43 UTC, edewit approved these changes, later dismissed

2024-04-18 00:34 UTC, adhurjaty commented
> This change introduces an issue where the warning
> 
> ```
> Warning: Received NaN for the `cx` attribute. If this is expected, cast the value to a string.
> <stack trace>
> ```
> 
> is printed out to console when running the admin-cli tests. This does not cause any of the tests to fail, but is not ideal. I'm not sure how to fix this issue

using `jsdom` fixes this issue

2024-05-06 11:21 UTC, edewit approved these changes

2024-05-06 11:21 UTC, merged