OpenJDK 21 support
keycloak/keycloak pull request #28518
Opened 2024-04-08 13:55 UTC by mabartos

Closes #28517

AFAIK, only these provided changes should be necessary to make to support OpenJDK 21.

# Discussion

We need to assess the lifecycle of the currently supported OpenJDK 17 with the OpenJDK 21.
We may face some obstacles, which need a discussion. 

## Some considerations

- We'd like to stick to the latest LTS OpenJDK versions
- If we support OpenJDK 17 and OpenJDK 21 simultaneously, testing would need to be doubled = **NOK**
- Or we can test OpenJDK 17 only during nightly builds
- We can deprecate OpenJDK 17 and claim the testing of it will be limited
- If deprecated for Keycloak 25 and removed in **Keycloak 26**, it'd be a bad move for RHBK 26 (support for JDK 17 should be set - AFAIK) = **NOK**
- If deprecated for Keycloak 25 and removed in **Keycloak 27**, the OpenJDK 17 would be deprecated for RHBK 26 and removed in RHBK ~28 (potentially) = **OK**
- Java Distribution IT tests check OpenJDK 17 and the latest JDK (OpenJDK 22)

## Summary
I'd suggest the following:

- OpenJDK 21 is the default (users can still use JDK17-based extensions)
- Deprecate OpenJDK 17 for Keycloak 25
- Remove OpenJDK 17 in Keycloak ~27
- Test OpenJDK 17 only as part of Java Distribution IT tests

---------------

@stianst @vmuzikar @ahus1 @miquelsi 
What are the requirements for the JDK support, and what are your thoughts on this?

2024-04-08 20:11 UTC, ahus1 commented
@pruivo - could please comment if Infinispan 14.x officially support OpenJDK 21? This is more of a yes/no question. If it is no, we would need to discuss if/where/how we would request such a compatibility. Thanks!

2024-04-08 20:23 UTC, pruivo commented
@ahus1 simple answer:
* Infinispan 14 supports OpenJDK 21 and virtual threads (disabled by default, needs to be explicitly enabled via Java properties)
* RHDG 8.4 (based in ISPN 14) will not support OpenJDK 21 and does not have virtual threads support.

2024-04-09 08:12 UTC, tristantarrant commented
> @ahus1 simple answer:
>     * RHDG 8.4 (based in ISPN 14) will not support OpenJDK 21 and does not have virtual threads support.

Let me clarify: RHDG 8.4 not supporting JDK 21 is merely a QE thing. It will work on JDK 21.
vthreads support is a different matter. While upstream has support for them, they are disabled by default.

2024-05-15 14:46 UTC, iot2198 commented
I have a question regarding support with jdk 21.
I have few SPI that are being injected into keycloak image, these SPI are build on java 21 which eventually leads to failure as keycloak has jdk17 in built support.
How do we overcome this @mabartos @tristantarrant @ahus1

2024-05-15 14:52 UTC, shawkins commented
@iot2198 if using maven, you can set the compile target to 17, or to be extra safe set the release https://maven.apache.org/plugins/maven-compiler-plugin/examples/set-compiler-release.html

2024-05-15 14:58 UTC, iot2198 commented
for gradle we would have to manually install jdk 21 in it ?
i am making a custom image so it would require me to download it and install it, something along these lines:

`FROM quay.io/keycloak/keycloak:24.0.4

# Install JDK 21 manually
USER root
RUN curl -L -o openjdk-21_linux-x64_bin.tar.gz https://download.java.net/java/GA/jdk21/21/GPL/openjdk-21_linux-x64_bin.tar.gz && \
    mkdir /opt/jdk-21 && \
    tar -xvf openjdk-21_linux-x64_bin.tar.gz -C /opt/jdk-21 --strip-components=1 && \
    rm openjdk-21_linux-x64_bin.tar.gz

# Set JAVA_HOME to JDK 21 and update PATH
ENV JAVA_HOME=/opt/jdk-21
ENV PATH=$JAVA_HOME/bin:$PATH`

2024-05-15 15:05 UTC, pruivo commented
@iot2198 simple, or you compile your code with JDK17 compatibility or create a fresh image of Keycloak with JDK 21 installed instead of using the official one :+1:

2024-05-29 12:16 UTC, mabartos commented
Failed tests were related to certain instabilities -> restarted.

2024-05-29 12:19 UTC, mabartos commented
@stianst @vmuzikar @ahus1 @keycloak/cloud-native-maintainers

Could you please check it? Thanks!

2024-05-30 07:31 UTC, vmuzikar requested changes
@mabartos Nice work, thank you!

Added some comments.

Also, I believe we need a review from someone from core and possibly @ASzc as well (due to ant changes).

2024-05-30 07:31 UTC, vmuzikar commented on quarkus/container/Dockerfile
Should we make the switch to Java 21 in the Operator Dockerfile too?

2024-05-30 07:31 UTC, vmuzikar commented on docs/documentation/release_notes/topics/25_0_0.adoc
With regards to docs, IMHO we should also update the Getting Started guides that instruct users to install Java 17.

2024-05-30 07:31 UTC, vmuzikar commented on docs/documentation/release_notes/topics/25_0_0.adoc
> += Java 17 is deprecated
```suggestion
= Java 17 support is deprecated
```

2024-05-30 07:31 UTC, vmuzikar commented on docs/documentation/release_notes/topics/25_0_0.adoc
> +OpenJDK 17 is deprecated, and the support will be removed in the following releases in favor of OpenJDK 21.
```suggestion
OpenJDK 17 support is deprecated in {project_name}, and will be removed in a following release in favor of OpenJDK 21.
```

2024-05-30 07:52 UTC, mabartos commented
@vmuzikar Oops, not sure why I missed the docs, thanks! Added a new commit.

2024-05-30 08:39 UTC, vmuzikar approved these changes, later dismissed
@mabartos Thanks for the update. LGTM.

We might want to consider having the Java version as a variable in the docs. But that's something for the future. :)

2024-05-30 09:21 UTC, miquelsi approved these changes
Great job @mabartos, thanks!

2024-05-30 10:18 UTC, mposolda commented
@vmuzikar @mabartos @stianst I am not sure if we want to officially deprecate Java 17 in release notes considering FIPS? Not 100% sure if we need to use "RHEL ELS" image for the FIPS 140 support, which might be based on RHEL 8.6. But RHEL 8 seems to support Java 21 from 8.9 based on: https://access.redhat.com/articles/1299013 . Or do we still deprecate Java 17 and then re-evaluate in Keycloak 26?

2024-05-30 10:27 UTC, mposolda approved these changes, later dismissed

2024-05-30 12:52 UTC, vmuzikar submitted a review, later dismissed

2024-05-30 14:06 UTC, mposolda commented
@mabartos I think it is normal DCO usually fails in this case with 2 commits, but if we squash commits during merge, it might be ok

2024-05-30 14:12 UTC, vmuzikar commented
I've overridden the DCO check, it was a false positive.

Also, some tests failed, I tried re-running them.

2024-05-30 14:18 UTC, mposolda approved these changes, later dismissed

2024-05-31 05:57 UTC, stianst commented on docs/documentation/release_notes/topics/25_0_0.adoc
> +It is still possible to use it, but the test coverage might be decreased.
```suggestion
```

2024-05-31 10:09 UTC, mabartos commented on docs/documentation/release_notes/topics/25_0_0.adoc
> +It is still possible to use it, but the test coverage might be decreased.
ok

2024-05-31 12:31 UTC, mabartos commented
We're waiting for resolving WebAuthn tests by: https://github.com/keycloak/keycloak/pull/30027

2024-05-31 13:48 UTC, mabartos commented
@mposolda @vmuzikar Addressed Stian's comment and rebased. WebAuthn tests should be fine now.

2024-05-31 14:02 UTC, vmuzikar approved these changes

2024-06-03 11:15 UTC, mabartos commented
@vmuzikar I think we're ready to go, right?

The only failure is related to DCO:
```
Commit sha: c5d01ff, Author: Marek Posolda, Committer: Martin Bartoš; Expected "Marek Posolda mposolda@gmail.com", but got "mposolda mposolda@gmail.com".
```
But AFAIK, we accept 'username' as the DCO, so I set DCO to pass.

2024-06-03 12:17 UTC, merged

2025-07-02 19:03 UTC, LaughDonor commented
Naive question here, would it be simpler to use the OpenJDK21 container version of ubi9 here? https://catalog.redhat.com/software/containers/ubi9/openjdk-21-runtime/6501ce769a0d86945c422d5f

This is in reference to the Dockerfiles:
https://github.com/keycloak/keycloak/blob/7eef7697e6340ea367356293374b28de5f181471/operator/Dockerfile#L1

https://github.com/keycloak/keycloak/blob/7eef7697e6340ea367356293374b28de5f181471/quarkus/container/Dockerfile#L1

Please let me know if I should create a new issue.

2025-07-03 08:26 UTC, mabartos commented
@LaughDonor Thanks for the additional observation! 

It'd be great if you could create an enhancement issue where you describe this case and the benefits that it can bring to Keycloak. Then, we can discuss this further with our wider team.