Release notes and Migration guide for Hostname v2
keycloak/keycloak pull request #28621
Opened 2024-04-11 09:12 UTC by mabartos

Closes #27730

Not sure whether it should be more comprehensive, but I think it's sufficient as the guide contains all the necessary information.

2024-04-11 11:25 UTC, Pepo48 commented on docs/documentation/upgrading/topics/changes/changes-25_0_0.adoc
> +For more details, and more comprehensive scenarios, see https://www.keycloak.org/server/hostname2[Configuring the hostname (v2)].
```suggestion
For more details, and more comprehensive scenarios, see https://www.keycloak.org/server/hostname[Configuring the hostname (v2)].
```

2024-04-11 11:27 UTC, Pepo48 commented on docs/documentation/upgrading/topics/changes/changes-25_0_0.adoc
> +As you can see, the `*-url` suffixes were removed for `hostname`, and `hostname-admin` options.
```suggestion
As you can see, the `*-url` suffixes were removed for `hostname` and `hostname-admin` options.
```

2024-04-11 11:28 UTC, Pepo48 commented on docs/documentation/upgrading/topics/changes/changes-25_0_0.adoc
> +Additionally, there is no way how to separately set `path`, or `port`.
```suggestion
Additionally, there is no way how to separately set `path` or `port`.
```

2024-04-11 11:29 UTC, Pepo48 commented on docs/documentation/upgrading/topics/changes/changes-25_0_0.adoc
> +Be aware, that either `hostname:v1`, or `hostname:v2` can be enabled, not both.
```suggestion
Be aware, that either `hostname:v1` or `hostname:v2` can be enabled, not both.
```

2024-04-11 14:20 UTC, mabartos commented
@vmuzikar Could you please point me to what examples would be most suitable to mention in the migration guide?

2024-04-12 09:52 UTC, vmuzikar commented
> @vmuzikar Could you please point me to what examples would be most suitable to mention in the migration guide?

@mabartos I'd probably choose some more complex scenarios that uses as many old options as possible (admin-url, -path, -port, ...). We should also emphasise we no longer enforce HTTPS unless it's part of hostname-url, and that we don't assume any ports when proxy is used. See the [old docs](https://github.com/keycloak/keycloak/blob/6d74e6b2895d8b0820d910a818bef8f67d0df129/docs/guides/server/hostname.adoc?plain=1#L43-L44).

2024-04-16 14:07 UTC, vmuzikar requested changes
@mabartos Thank you for the update. Added some comments.

2024-04-16 16:22 UTC, vmuzikar approved these changes, later dismissed
LGTM, thanks!

2024-04-16 17:27 UTC, Pepo48 approved these changes, later dismissed
@mabartos nice work, thank you!

I have just small nitpicks to consider, related to clarification of two sentences. I'll leave it up to you, whether you want to include it or not.

Other than that LGTM, therefore I'm approving the PR.

2024-04-16 17:27 UTC, Pepo48 commented on docs/documentation/upgrading/topics/changes/changes-25_0_0.adoc
> +As the `hostname` now accepts hostname and URL, we can simplify the hostname settings directly by it.
Here I would get rid of "we" pronoun to redirect the narrative more towards "them". I assume you wanted to say that the setup process is now a lot simpler. If so, I would rephrase it a bit to make the sentence a bit more clear, something like: 
```suggestion
As you can see in the example, all the parts of a URL can be now specified via single `hostname` option, which simplifies the hostname setup process.
```

2024-04-16 17:27 UTC, Pepo48 commented on docs/documentation/upgrading/topics/changes/changes-25_0_0.adoc
> +In order to use the same URL for backend as for frontend endpoints, we need to be aware of a different behavior between hostname versions.
```suggestion
Be aware that there is a change in behavior if the same URL is to be used for both backend and frontend endpoints.
```

2024-04-16 20:01 UTC, mabartos commented
@Pepo48 make sense to me. Thanks!

@Pepo48 @vmuzikar Ready for another round of reviews.

2024-04-16 20:08 UTC, Pepo48 approved these changes

2024-04-17 07:29 UTC, vmuzikar approved these changes

2024-04-17 07:29 UTC, merged