Set OCSP nonce in requestExtensions and not singleRequestExtensions
keycloak/keycloak pull request #28768
Opened 2024-04-16 06:39 UTC by justin-tay

Closes #26439

This fixes the issue with the OCSP nonce as setting with `setRequestExtensions` sets it properly in `requestExtensions` while setting it as the second parameter to `addRequest` actually sets it in `singleRequestExtensions`.

For testing the `OcspHandler` was modified to require that the nonce is present otherwise it will return a `malformedRequest`.

Debug logs were added if no OCSP nonce is found in the response.

2024-04-17 09:44 UTC, rmartinc requested changes
Thanks @justin-tay for the PR!

I think the changes in the PR are OK. But I also detected that the nonce that is added right now is weird. At least wireshark detected the extension as incorrect saying something about not proper encoding. Reading about this I detected that the `nonce` extension is recommended to be encapsulated in another octet string (see this [issue](https://github.com/pyca/cryptography/issues/6404) for example). I checked openssl and it performs that. Wireshark does not show any error with the double octet string either. I also saw that this example [here](https://www.ietf.org/id/draft-ietf-lamps-ocsp-nonce-update-06.html) also performs double octet string. So I have added that change too over you PR. Besides I changed to create a nonce of 16 bytes because before I saw a nonce of 4 bytes which are too short IMHO.

In summary, can you please add this commit https://github.com/rmartinc/keycloak/commit/4f828518f6e3bfef8dc9ba215bb2f7a10c4d2a36 in the PR branch and check in your environment. If it works for you too just add it to this PR (you can squash it, modify or whatever you want to do with it).

Thanks again!

2024-04-18 03:19 UTC, justin-tay commented
Thanks a lot for the review and the fixes @rmartinc !

I've tested the changes and it works well. Have squashed the commit. Thanks!

2024-04-18 06:31 UTC, rmartinc approved these changes
Thanks a lot @justin-tay for this! Approved!
@mposolda This one is ready to go from my point of view.

2024-04-18 07:04 UTC, mposolda approved these changes
@justin-tay @rmartinc Nice, Thanks!

2024-04-18 07:04 UTC, merged