Remove deprecated EnvironmentDependentProviderFactory.isSupported method
keycloak/keycloak pull request #28806
Opened 2024-04-16 13:31 UTC by pruivo

Closes #26280

2024-04-16 19:02 UTC, ahus1 requested changes
Thank you for this PR. One more simplification is IMHO possible, see below.

2024-04-18 14:07 UTC, ahus1 commented on server-spi-private/src/main/java/org/keycloak/provider/EnvironmentDependentProviderFactory.java
> +        return false;
IMHO there shouldn't be a default impl here any more, as there is now only a single method in the Interface. Either you implement the interface, or not. 

So please remove the default implementation.

2024-04-18 15:20 UTC, ahus1 approved these changes, later dismissed
Thank you for this cleanup. This simplified things, and also remove some code areas where the two conditions deviated between the two methods.

2024-04-18 21:55 UTC, pedroigor reviewed
I think we want a release notes for this one to let people know that that method was finally removed.

Otherwise, glad we are finally doing this refactoring.

2024-04-18 22:05 UTC, pedroigor approved these changes, later dismissed
OK, the interface is in `keycloak-server-spi-private` so not a blocker :) But I think it is a good to have.

2024-04-18 22:07 UTC, ahus1 approved these changes

2024-04-18 22:07 UTC, ahus1 commented
@pedroigor - ok, added it to the release notes and upgrade guide.

2024-04-18 22:08 UTC, ahus1 commented
@keycloak/ui-maintainers - could you please review this change as the code-owners require you to approve as well? Thanks!

2024-04-18 22:14 UTC, pedroigor approved these changes

2024-04-19 11:20 UTC, mposolda approved these changes
@pruivo Good change, Thanks!

2024-04-19 14:36 UTC, edewit approved these changes

2024-04-19 14:36 UTC, merged