Fix docker image building + readme
keycloak/keycloak pull request #28809
Opened 2024-04-16 14:22 UTC by AlexNik

1. Add +x permission for `quarkus/container/ubi-null.sh`
2. Update `quarkus/container/README.md` to the correct command

2024-04-17 19:23 UTC, AlexNik commented
@hmlnarik @agagancarczyk ?

2024-04-25 07:02 UTC, AlexNik commented
@pedroigor @pskopek ?

2024-04-25 09:02 UTC, pskopek requested changes
The change of permission for the script quarkus/container/ubi-null.sh is not necessary.
The see the usage [in Dockerfile here](https://github.com/keycloak/keycloak/blob/d6f453f0d6d2946b5ea1637f3cfe89ceb999783d/operator/Dockerfile#L4) or [here](https://github.com/keycloak/keycloak/blob/86b280349b17aa401308c5a4ef21e726d795233f/quarkus/container/Dockerfile#L20).

2024-04-25 15:26 UTC, AlexNik commented on quarkus/container/README.md
> +    docker build --build-arg KEYCLOAK_DIST=keycloak-<VERSION>.tar.gz -t <YOUR_TAG> .
I've updated.

2024-05-02 09:25 UTC, AlexNik commented
@pskopek up

2024-05-03 08:01 UTC, AlexNik commented
@ahus1 could you review this PR please?

2024-05-03 10:19 UTC, ahus1 commented
@AlexNik - I see that @pskopek mentioned that changing the permissions on the shell script is not necessary, and that the change is still part of the PR. Please update your PR, or describe why the change in permissions is necessary.

2024-05-03 12:55 UTC, AlexNik commented
Ok.
Indeed, with the current usage, it is possible to not give permissions +x on the file. But I think it's good manners to set +x permissions on files that have have permissions to run, rather than run them via `bash xxx.sh`. As a last resort, you could not change the permissions on the file in the repository itself, but change the Dockerfile where the copying takes place:
`COPY --chmod=+x target/ubi-null.sh /tmp/`
But I prefer to set the permissions correctly and not bother.

2024-05-09 17:43 UTC, AlexNik commented
@ahus1?

2024-05-15 07:28 UTC, AlexNik commented
@ahus1 @pskopek ?

2024-05-15 08:18 UTC, ahus1 approved these changes
Thank you for the PR to update the docs!

2024-05-15 08:18 UTC, merged