Update messages_de.properties
keycloak/keycloak pull request #28962
Opened 2024-04-22 09:22 UTC by ch-lepp

Added missing German translations

2024-04-22 09:25 UTC, jonkoops commented
Could you [sign off](https://github.com/keycloak/keycloak/pull/28962/checks?check_run_id=24094141686) on your commit?

2024-04-22 10:02 UTC, ch-lepp commented
Done, I think...

2024-04-22 10:18 UTC, edewit commented
@ch-lepp you can do a `git rebase upstream/main --signoff`

2024-04-22 10:23 UTC, ch-lepp commented
Ok, I think I've got it now.

Thx

2024-04-22 10:31 UTC, jonkoops commented
@ch-lepp if you can get another German native speaker to review your work we can merge this in.

2024-04-22 10:32 UTC, jonkoops commented
Don't worry about the CI failures, we're working on a fix for it.

2024-04-22 11:06 UTC, Persi requested changes
I've commented some suggestions.

2024-04-22 11:06 UTC, Persi commented on themes/src/main/resources-community/theme/base/login/messages/messages_de.properties
> +error-invalid-length=Länge muss zwischen {1} und {2} liegen.
Vorschlag: Länge muss zwischen {1} und {2} Zeichen liegen.

2024-04-22 11:06 UTC, Persi commented on themes/src/main/resources-community/theme/base/login/messages/messages_de.properties
> +error-invalid-email=Ungültige E-Mail_Adresse.
E-Mail-Adresse

2024-04-22 11:06 UTC, Persi commented on themes/src/main/resources-community/theme/base/login/messages/messages_de.properties
> +error-reset-otp-missing-id=Bitte wählen Sie eine OTP Konfiguration aus.
OTP-Konfiguration

2024-04-22 11:06 UTC, Persi commented on themes/src/main/resources-community/theme/base/login/messages/messages_de.properties
> +updateEmailMessage=Sie müssen Ihre Email-Adresse aktualisieren, um das Benutzerkonto zu aktivieren..
E-Mail-Adresse

2024-04-22 11:06 UTC, Persi commented on themes/src/main/resources-community/theme/base/login/messages/messages_de.properties
> +insufficientLevelOfAuthentication=Die angefragte Sträke des Authentifizierungsverfahrens wurde nicht erfüllt.
Stärke

2024-04-22 11:06 UTC, Persi commented on themes/src/main/resources-community/theme/base/login/messages/messages_de.properties
> +identityProviderMissingCodeOrErrorMessage=Fehlender code oder error Parameter in der Antwort vom Identitätsanbieter.
Fehlender Code- oder Fehlerparameter in der Antwort vom Identitätsanbieter.

2024-04-22 11:18 UTC, ch-lepp commented
I applied the review suggestions

2024-04-22 11:20 UTC, Persi approved these changes
lgtm

2024-04-22 15:32 UTC, jonkoops commented
Thanks all, I will set the PR to merge.

2024-04-23 10:32 UTC, jonkoops commented
Please refrain from merging things in from `main` unless absolutely necessary, as this causes CI to re-trigger and creates additional work for us.

2024-04-24 04:57 UTC, ahus1 approved these changes

2024-04-24 07:05 UTC, merged