External Infinispan as cache - Part 3
keycloak/keycloak pull request #29071
Opened 2024-04-25 06:45 UTC by pruivo

Implementation of UserLoginFailureProvider using remote caches only.

Closes #28754

Draft PR since it needs a "unit" test to ensure the new implementation works.

2024-05-03 11:00 UTC, ahus1 commented
We found that in main there was a typo with the profiles in the CI, and I pushed one change to fix it for your tests. Before, the profile wasn't actually active :scream:. 

Let's wait for the CI to complete.

2024-05-03 11:12 UTC, ahus1 requested changes
Thank you for the PR, it looks good overall. 

Some general comments: 

* When adding a copyright header to a new file, use the current date. There is actually an IntelliJ setting to do this automatically, and I'll share that in another PR.
* When adding new classes, take a moment to add a class level JavaDoc to describe what their intent is. I see it present on some classes, still missing for example in `BaseUpdater` and `RemoteChangeLogTransaction`

2024-05-03 11:12 UTC, ahus1 commented on server-spi-private/src/main/java/org/keycloak/models/UserLoginFailureProviderFactory.java
> +public interface UserLoginFailureProviderFactory<T extends UserLoginFailureProvider> extends ProviderFactory<T>, EnvironmentDependentProviderFactory {
I didn't check the previous commits, but now I notice: While this technically works, the interface `EnvironmentDependentProviderFactory` should go on each implementation, as it is not a feature of the `UserLoginFailureProviderFactory`, but of each implementation.

2024-05-03 12:30 UTC, pruivo commented
@ahus1 What is the policy regarding the copyright? Is Keycloak requiring it in each file?

2024-05-03 12:39 UTC, ahus1 commented
@pruivo - yes, on each file. We are lacking an enforcement though.

2024-05-06 17:26 UTC, pruivo commented
Disabled the following tests because we are unable to control time in the docker container:
* `org.keycloak.testsuite.model.AuthenticationSessionProviderTest#testExpiredAuthSessions`
* `org.keycloak.testsuite.oauth.AccessTokenTest#accessTokenCodeExpired`

Modified the following test due to the async nature of hot rod client events
* `org.keycloak.testsuite.model.UserSessionProviderTest#testRemoveUserSessionsByRealm`

2024-05-08 16:52 UTC, ahus1 requested changes
Thank you for the PR! See below for two comment. Thanks!

2024-05-08 20:38 UTC, pruivo commented on testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/model/UserSessionProviderTest.java
> +        // TODO! the Hot Rod events are async
The `eventuallyEquals` can be removed after the `UserSessionProvider` is implemented to use the remote cache. Those TODOs are here to remind me to revert the code.

2024-05-08 20:39 UTC, pruivo commented on testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/model/AuthenticationSessionProviderTest.java
> +        // for some reason, Profile is always null.
I'm pretty sure `Profile.isFeatureEnabled` is throwing an NPE too. Anyway, I've applied your suggestion.

2024-05-14 13:56 UTC, ahus1 approved these changes
Thank you - all my comments have been addressed. Once this is merged, it might be time time rebase this PR, possibly after we change to Protostream in main.

2024-05-14 13:56 UTC, merged

2024-05-14 14:39 UTC, pruivo commented
thanks @ahus1 !