fix: minor refinements to collection utils
keycloak/keycloak pull request #29536
Opened 2024-05-14 18:39 UTC by shawkins

closes: #29535

Not sure what the policy is on common method removal - we don't use it anywhere else, but if we assume extension developers could be using it, then I'll add a deprecation instead.

2024-05-20 13:41 UTC, vmuzikar requested changes
@shawkins Thanks for this enhancement. Code changes look good to me. Only thing we're missing from my perspective is some note in the upgrading guide.

I believe this PR also needs an approve from the @keycloak/core.

2024-05-20 13:41 UTC, vmuzikar commented on common/src/main/java/org/keycloak/common/util/CollectionUtil.java
> -    }
This is the only breaking change (if I haven't overlooked something). I would probably go ahead and just remove it. But I'd suggest adding a note to the upgrading guide (with a suggested code to use instead).

2024-05-20 14:58 UTC, shawkins commented
@vmuzikar ok, added a note

2024-05-20 15:23 UTC, vmuzikar submitted a review, later dismissed
LGTM, thank you.

Let's give the Core Team a chance to chime in as well.

2024-05-22 13:35 UTC, vmuzikar approved these changes

2024-06-06 13:46 UTC, graziang approved these changes
@shawkins Thanks, LGTM!

2024-06-06 14:07 UTC, merged