OAuth 2.0 Device Polling Interval - Realms settings/Token Tab +- to change value not working
keycloak/keycloak pull request #29624
Opened 2024-05-16 18:33 UTC by ahanamallik1

The input was taking a String type variable. Fixed it by converting it to a number so that numeric calculations can be done on it. Also, applied a condition for Minus button so that the count is never less than zero since the default value is 0.

Fixes #29551

2024-05-20 18:29 UTC, ssilvert approved these changes

2024-05-20 21:18 UTC, ahanamallik1 commented
@ssilvert  thank you for the review and approval.
As I read the approving workflows, it should be approved by maintainer separately as it is first time PR by me.
Whom shall I approach for workflow approvals?

2024-05-21 08:38 UTC, edewit submitted a review, later dismissed

2024-05-21 09:05 UTC, agagancarczyk commented
@ahanamallik1 looks good, but there is some small linting error that will need to be fixed for CI to pass.

2024-05-21 18:42 UTC, ssilvert requested changes

2024-05-21 18:42 UTC, ssilvert commented on js/apps/admin-ui/src/realm-settings/TokensTab.tsx
> +                      onMinus={() => field.onChange((Number(field?.value) > 0) ? Number(field?.value) - 1 : 0)}
This should satisfy the linter.

```suggestion
                      onMinus={() =>
                        field.onChange(
                          Number(field?.value) > 0
                            ? Number(field?.value) - 1
                            : 0
                        )
                      }
```

2024-05-21 20:55 UTC, ahanamallik1 commented
> @ahanamallik1 looks good, but there is some small linting error that will need to be fixed for CI to pass.
@agagancarczyk
Thank you for your feedback . 
EsLint is already present in node_modules.
I also installed EsLint extension in VSCode. But no success in linting the changed file.

Is there any configuration am I missing ?

2024-05-21 22:03 UTC, ssilvert commented on js/apps/admin-ui/src/realm-settings/TokensTab.tsx
> +                            : 0
```suggestion
                            : 0,
```

2024-05-21 22:04 UTC, ssilvert commented
> > @ahanamallik1 looks good, but there is some small linting error that will need to be fixed for CI to pass.
> > @agagancarczyk
> > Thank you for your feedback .
> > EsLint is already present in node_modules.
> > I also installed EsLint extension in VSCode. But no success in linting the changed file.
> 
> Is there any configuration am I missing ?

@ahanamallik1 I think I've fixed it now.

2024-05-22 01:07 UTC, ssilvert commented
I messed this up.  I did the commits through web interface and didn't include signoff.  So I'm closing this in favor of https://github.com/keycloak/keycloak/pull/29767

2024-05-22 01:07 UTC, closed without merging