Update documentation after adapters removal
keycloak/keycloak pull request #29695
Opened 2024-05-20 11:06 UTC by mposolda

closes #28774

2024-05-20 15:22 UTC, andymunro approved these changes
Looks good, @mposolda

2024-05-20 18:35 UTC, douglaspalmer approved these changes
LGTM

2024-05-21 06:53 UTC, ahus1 requested changes
Thank you for this PR, @mposolda. 

Unfortunately, the guides no longer build successfully, possibly due to a change related to the PR. Please have a look.

2024-05-21 07:34 UTC, ahus1 approved these changes

2024-05-21 07:34 UTC, merged