Add information to SAML parser exceptions
keycloak/keycloak pull request #29703
Opened 2024-05-20 14:16 UTC by esagalara

Include namespaces and location of expected/found elements

Closes #29698

2024-09-20 20:50 UTC, ahus1 commented
@rmartinc / @mposolda - as this PR touches SAML, maybe you can review it when you have the time. Thanks!

2024-09-23 14:24 UTC, rmartinc requested changes
Thanks @esagalara! Just commenting about replacing the method instead of adding a new one, and this way chage all the usages (it seems there are two). WDYT?

2024-09-23 18:34 UTC, esagalara commented on saml-core/src/main/java/org/keycloak/saml/common/DefaultPicketLinkLogger.java
> +                ".\nAt line " + line.toString() + ", column " + column);
Sure, that sounds good.

2024-09-23 20:09 UTC, esagalara commented on saml-core/src/main/java/org/keycloak/saml/common/DefaultPicketLinkLogger.java
> +                ".\nAt line " + line.toString() + ", column " + column);
I have removed the previous version of the `parserExpectedTag` method now.

2024-09-24 16:09 UTC, rmartinc approved these changes
Thanks @esagalara!

2024-09-27 06:44 UTC, mposolda approved these changes
@rmartinc Thanks for the review!

2024-09-27 06:44 UTC, merged