Enable hibernate statistics logging
keycloak/keycloak pull request #29791
Opened 2024-05-22 16:48 UTC by cwelch-rh

Add hibernate.generate_statistics and hibernate.session.events.log to the ParsedPersistenceXmlDescriptor from the Java system properties

Closes #29786

2024-05-23 09:41 UTC, mabartos approved these changes, later dismissed
LGTM

2024-05-23 10:43 UTC, vmuzikar reviewed
@cwelch-rh Thank you for the PR!

I wonder if it would be possible to instruct users to just add it to their `persistence.xml`. See also [this thread](https://github.com/quarkusio/quarkus/issues/35325#issuecomment-1676826946). But we probably want something more generic...

Still, using sys props for configuring Keycloak seems a bit random, not aligned with other config options.

2024-05-23 10:50 UTC, shawkins commented
@vmuzikar #27320 and the associated discussions recommend against using persistence.xml files.

2024-05-23 10:54 UTC, vmuzikar commented
@shawkins Yes, that's the long term plan: #19427.

2024-05-23 14:33 UTC, cwelch-rh commented
@vmuzikar Agreed, the usage of system properties is weird. This is pretty much a hack to get it to work the way it used to. 
I've tried using the quarkus properties, but it fails to start with the following:

> Caused by: io.quarkus.runtime.configuration.ConfigurationException: A legacy persistence.xml file is present in the classpath, but Hibernate ORM is also configured through the Quarkus config file. Legacy persistence.xml files and Quarkus configuration cannot be used at the same time.

I expect https://github.com/keycloak/keycloak/issues/19427 to fix that so that we can use the correct configuration.

2024-05-23 17:03 UTC, vmuzikar commented
@cwelch-rh I wonder, have you tried putting the options to `persistence.xml`?

2024-05-23 22:23 UTC, cwelch-rh commented
@vmuzikar I'm not sure what you mean by that. I don't see a way to override the default-persistence.xml. It looks hard-coded and I saw some issue that said it's probably not possible and not officially supported.

If you're suggesting adding properties to default-persistence.xml, then I think we need some other configuration to specify potential replacement values, which is cleaner, but would we really want those exposed if they're temporary?

What about a hidden Option in DatabaseOptions or LoggingOptions? Something like "db-log-hibernate-statistics" or "log-hibernate-statistics" that would set those two properties if it's set to "true".

2024-05-27 07:22 UTC, vmuzikar commented
> I'm not sure what you mean by that. I don't see a way to override the default-persistence.xml. It looks hard-coded and I saw some issue that said it's probably not possible and not officially supported.

Sorry for the confusion, I misinterpreted the [migration guide](https://github.com/keycloak/keycloak/blob/1cfd4a82a564c779ab679635d60b149a9ac526c1/docs/documentation/upgrading/topics/changes/changes-22_0_0.adoc?plain=1#L29-L32).

> but would we really want those exposed if they're temporary?

Hmm, why would it be temporary? When we start using the Quarkus props instead of persistence.xml, we just change the implementation of the option, but to user it will look and behave the same, the contract will be unchanged.

> Something like "db-log-hibernate-statistics" or "log-hibernate-statistics" that would set those two properties if it's set to "true".

Having it in the DB category probably makes more sense to me than the log category. We're effectively configuring the DB subsystem, not log subsystem. But either way works for me.

2024-05-29 11:12 UTC, vmuzikar reviewed
@cwelch-rh Thanks for the update.

Would it make sense to mention it in the [docs](https://github.com/keycloak/keycloak/blob/main/docs/guides/server/db.adoc) too?

It'd be also good to test it if possible.

2024-05-29 14:24 UTC, stianst commented on quarkus/config-api/src/main/java/org/keycloak/config/DatabaseOptions.java
> +    public static final Option<Boolean> DB_LOG_HIBERNATE_STATISTICS = new OptionBuilder<>("db-log-hibernate-statistics", Boolean.class)
I would drop `hibernate` from the CLI name

```suggestion
    public static final Option<Boolean> DB_LOG_HIBERNATE_STATISTICS = new OptionBuilder<>("db-log-statistics", Boolean.class)
```

2024-06-04 21:53 UTC, cwelch-rh commented
@vmuzikar I updated the PR with tests and set the Option to not be hidden. I didn't see a place in the DB docs that made sense, so I think just having it in the "All Configuration" docs is probably good enough.

2024-06-10 12:48 UTC, vmuzikar approved these changes
@cwelch-rh Thank you for the updates and adding the test.

I wonder, if we could add some integration test as well. Something to check that option does what it's supposed to do. Perhaps we could check some specific log message that's produced by the enabled statistics?

Also, we'll need to fix the [help tests](https://github.com/keycloak/keycloak/tree/f05ccec9b564fc8714704bfd486b6bbcad8e03c1/quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help). I approved the CI so it should be visible there now.

2024-06-10 12:49 UTC, vmuzikar requested changes
Sorry, meant to request changes.

2024-08-07 09:02 UTC, mabartos commented
@cwelch-rh Do you plan to finish it?

2025-09-23 20:51 UTC, shawkins commented
After reviewing, the logging config option on the persistence xml is deprecated - it's just a matter or enabling a logging category: https://github.com/keycloak/keycloak/issues/29786#issuecomment-3325510048

Thank you @cwelch-rh for the contribution, but I don't think we need this pr anymore.

2025-09-23 20:51 UTC, closed without merging