Upgrade supported PostgreSQL to version 16
keycloak/keycloak pull request #29889
Opened 2024-05-27 14:20 UTC by miquelsi

Closes #29875

2024-05-27 15:18 UTC, ahus1 requested changes
When upgrading regular PostgreSQL to 16, please also upgrade Aurora PostgreSQL. The version of this flavor is always specified as major-minor, therefore it has a separate entry.

2024-05-27 15:18 UTC, ahus1 commented on pom.xml
>          <aurora-postgresql.version>15.5</aurora-postgresql.version>
```suggestion
        <aurora-postgresql.version>16.1</aurora-postgresql.version>
```

2024-05-28 05:46 UTC, stianst commented
We should probably also updated the tested version in https://www.keycloak.org/server/db?

2024-05-28 06:58 UTC, ahus1 commented
@stianst - the tested version in the docs is extracted from the `pom.xml` - so it will always be up to date.

2024-05-28 16:10 UTC, ahus1 submitted a review, later dismissed

2024-05-28 16:16 UTC, ahus1 commented
@miquelsi - is that something you want to put into the release notes or migration guide?

2024-05-28 17:33 UTC, miquelsi commented
> @miquelsi - is that something you want to put into the release notes or migration guide?

Yes, in the release notes

2024-05-29 08:32 UTC, ahus1 reviewed
@miquelsi - I don't see a release note change in this PR you mentioned in your previous comment. Did I miss something?

2024-05-29 11:16 UTC, ahus1 commented on docs/documentation/release_notes/topics/25_0_0.adoc
> +The supported and tested databases now include PostgreSQL 16
```suggestion
The supported and tested databases now include PostgreSQL 16.
```

2024-05-29 14:31 UTC, ahus1 approved these changes

2024-05-29 14:31 UTC, merged