Add initial translation for auth-x509-client-username-form (#29868)
keycloak/keycloak pull request #29951
Opened 2024-05-28 22:55 UTC by thomasdarimont

Fixes #29868

2024-05-29 05:54 UTC, edewit approved these changes, later dismissed

2024-05-29 06:21 UTC, ahus1 requested changes
Thank you for adding those missing keys. See below for a small grammar issue that seems to lurk in there.

2024-05-29 06:21 UTC, ahus1 commented on themes/src/main/resources/theme/base/login/messages/messages_en.properties
> +auth-x509-client-username-form-help-text=Sign in with a X509 client certificate
Should "an" as it is an "Ex-Five-Oh-Nine" certificate, and that starts with a vowel. 

```suggestion
auth-x509-client-username-form-help-text=Sign in with an X509 client certificate
```

2024-05-29 14:07 UTC, ahus1 submitted a review, later dismissed

2024-05-29 14:08 UTC, jonkoops approved these changes, later dismissed

2024-05-29 16:56 UTC, ahus1 requested changes
This PR now contains a change to `requiredAction.organization.confirm-membership` which seems to be unrelated. Please comment if it is really related, otherwise remove that change. 

Unfortunately due to the latest changes to `.editorconfig` there are some blank removed that we want to keep for now. See #29982 for a discussion.

2024-05-29 17:23 UTC, thomasdarimont commented
IntelliJ seems todo some strange automatic cleanup for spaces at the end? I'm just saving the file.

2024-05-29 17:26 UTC, thomasdarimont commented
Fixed

2024-05-30 13:57 UTC, agagancarczyk approved these changes
LGTM!

2024-05-31 06:40 UTC, ahus1 approved these changes

2024-05-31 08:18 UTC, merged