Fix claiming userInfoToken with DPoP
keycloak/keycloak pull request #29967
Opened 2024-05-29 10:31 UTC by Captain-P-Goldfish

Fix claiming userInfoToken with DPoP

- tokenType must be DPoP as defined in RFC9449 chapter 7.1

relatesTo #22311

2024-05-30 14:38 UTC, mposolda commented
@tnorimat Could you please help me review this one if you have some free cycles?

2024-05-30 20:44 UTC, tnorimat commented
@mposolda Hello, Yes I will review the PR.

2024-05-31 02:11 UTC, tnorimat requested changes
@Captain-P-Goldfish Hello, I add one minor review comment. Could you check it?

2024-05-31 02:11 UTC, tnorimat commented on testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/OAuthClient.java
>                  get.addHeader("DPoP", dpopProof);
`"DPoP"` might be `TokenUtil.TOKEN_TYPE_DPOP`.

2024-05-31 05:21 UTC, Captain-P-Goldfish commented
It would also be good to restructure the implementation here.
Currently DPoP is not supported for other grantTypes than AuthorizationCode. We should think of a way to add it dynamically to all grantTypes even customized grantTypes

2024-05-31 05:26 UTC, tnorimat commented on testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/OAuthClient.java
>                  get.addHeader("DPoP", dpopProof);
L1183 ` get.addHeader("DPoP", dpopProof);`
to
`get.addHeader(TokenUtil.TOKEN_TYPE_DPOP, dpopProof);`
But, you need not to modify it.

2024-06-05 19:03 UTC, mposolda commented
> It would also be good to restructure the implementation here. Currently DPoP is not supported for other grantTypes than AuthorizationCode. We should think of a way to add it dynamically to all grantTypes even customized grantTypes. But this would be a different ticket :-)

@Captain-P-Goldfish Could you please create separate GH issue for this topic you mentioned and add the comment here with  the link to that issue? TBH I am not 100% sure from the top of my head if DPoP is supposed to be used in other grant types besides authorizationCode. But it might be good to investigate this anyway...

2024-06-05 19:44 UTC, Captain-P-Goldfish commented
done.
I edited the comments above and linked the two issues:
Task: #https://github.com/keycloak/keycloak/issues/30179
Bug #https://github.com/keycloak/keycloak/issues/30181

2024-06-06 13:31 UTC, mposolda commented
@Captain-P-Goldfish Thanks!

2024-06-06 14:02 UTC, Captain-P-Goldfish commented
Could put this pull-request on hold?
I have a few other tasks I need to take care of first but when finished I would like pull the DPoP support directly into the tokenEndpoint. 

I tried yesterday evening to get the DPoP implementation out of the grantType implementations but this resulted in interface-changes all the way back to the authentication-flows because the cors-object would be affected by this change. Therefore, we have no other way but to add DPoP handling with Consumers into the `OAuth2GrantType` abstract class.

2024-06-18 07:18 UTC, Captain-P-Goldfish commented
unit tests are fixed except for the flaky tests from the main-branch :-)

2024-06-18 13:54 UTC, mposolda commented
@Captain-P-Goldfish Thanks! Failing `DockerClientTest` seems like a regression of this PR?

2024-06-19 06:09 UTC, Captain-P-Goldfish commented
that should fix it. I am having serious trouble getting the DockerClientTest running locally due to ClassNotFound exceptions and an outdated testcontainers version that does not get along with my docker-desktop version... Is there somewhere a documentation that explains how to get this test running reliably? 

The DockerClientLogin implementation was trying to get the ProtocolMappers which I extended by the DPoP ProtocolMapper and expected that the mappers were having only a single entry. I extended the stream by a filter that makes sure that only the expected mapper is returned.

2024-06-21 17:44 UTC, Captain-P-Goldfish commented
@mposolda are you going to review this or is someone else doing it?
If you would like to have any changes on this please let me know.

2024-07-16 10:00 UTC, mposolda commented
@tnorimat Does this PR look ok to you?

2024-07-18 04:09 UTC, tnorimat requested changes
@Captain-P-Goldfish I added some review comments. Could you check them?

2024-07-18 06:46 UTC, Captain-P-Goldfish commented
@tnorimat why do you want the documentation to be removed? I added it for those who read the code after us. People not knowing what DPoP is can find the related RFC and reasons why the code was added in this way faster if the comments are present. What is your reason that you want them removed?

2024-07-18 07:13 UTC, tnorimat commented
@Captain-P-Goldfish Hello, IMO, removing comments are Keycloak's convention. When I sent the PRs implementing several RFCs with comments, I requested to remove the comments.
@mposolda WDYT? If you are OK, keeping comments seems to be preferable.

2024-07-26 15:32 UTC, mposolda reviewed
@Captain-P-Goldfish Thanks! I've added small comment related to the refresh token constructor.

@Captain-P-Goldfish @tnorimat Regarding comments: I think comments in the code and also javadoc can be useful, but always depends on the context. It is not good if comments are mis-used and there is too much of them, but IMO comments are good if it makes the code more readable and adds the useful info why the particular code is used etc. So I think it is case by case.

AFAIK Keycloak does not have any strong convention on how much comments to use. Added the inline notes with some suggestions where comments can be useful IMO. For the other places mentioned by @tnorimat , I agree we can possibly remove comments.

What do you think?

2024-07-26 15:32 UTC, mposolda commented on services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java
> +        private AccessToken.Confirmation getConfirmation(AuthenticatedClientSessionModel clientSession,
I can see this comment can be useful for knowing some context about this change. So I can personally prefer to keep it, but not strong opinion on this...

2024-07-26 15:32 UTC, mposolda commented on services/src/main/java/org/keycloak/protocol/oidc/endpoints/TokenEndpoint.java
> +         */
Similar like the other case. I can see this can be useful, but not strong opinion on this...

2024-07-26 18:56 UTC, Captain-P-Goldfish commented
I have removed the comments that were not commented by @mposolda and re-added the constructor.

2024-07-27 05:06 UTC, tnorimat approved these changes
LGTM

2024-07-29 00:27 UTC, tnorimat commented
@mposolda I approved the PR. Could you check it?

2024-07-29 14:30 UTC, mposolda approved these changes
@Captain-P-Goldfish @tnorimat Thanks a lot for the reviews and applying all the comments from the review!

2024-07-29 14:30 UTC, merged