Do not inherit 'https-client-auth' property for the management interface
keycloak/keycloak pull request #30098
Opened 2024-06-03 15:17 UTC by mabartos

Closes #30094

2024-06-03 19:20 UTC, shawkins approved these changes, later dismissed
Looks good, just a couple of minor suggestions.

2024-06-03 19:20 UTC, shawkins commented on docs/guides/server/management-interface.adoc
> +To assess mTLS for the management interface, you need to explicitly set the `https-management-client-auth` option.
```suggestion
To enable mTLS for the management interface, you need to explicitly set the `https-management-client-auth` option.
```

2024-06-03 19:20 UTC, shawkins commented on docs/guides/server/management-interface.adoc
> +Specific {project_name} management interface options with the prefix `https-management-*` were provided for setting different TLS parameters for the management HTTP server.
```suggestion
Specific {project_name} management interface options with the prefix `https-management-*` are provided for setting different TLS parameters for the management HTTP server.
```

2024-06-04 10:20 UTC, mabartos commented
@shawkins Thanks, updated.

2024-06-10 13:06 UTC, vmuzikar requested changes
@mabartos Thank you for the PR. I was thinking about it and I'd probably keep it consistent with other TLS options. It might be confusing that one of them is behaving differently. I wonder if we should rather add some note to [mTLS docs](https://www.keycloak.org/server/enabletls#_enabling_mutual_tls) to highlight it also by default affects the management port. Alternatively, even a generic warning that all options affect the management port? WDYT?

2024-06-12 08:51 UTC, mabartos commented
@vmuzikar Thanks for the comment. Even though it makes sense to me not to inherit the property for the management interface, it'd be better to ensure consistency, as you've mentioned. The situation described in the issue happens only when the mTLS is being set up, so it's ok to provide only some notes to the mTLS docs.

Closing as different changes will be provided to close the issue.

2024-06-12 08:51 UTC, closed without merging