make admin-ui build as a library
keycloak/keycloak pull request #30268
Opened 2024-06-08 09:07 UTC by edewit

Signed-off-by: Erik Jan de Wit <erikjan.dewit@gmail.com>

2024-07-02 19:26 UTC, ssilvert requested changes

2024-07-02 19:26 UTC, ssilvert commented on .github/workflows/js-ci.yml
> +      WORKSPACE: "keycloak-admin-ui
Why the leading quote here?

2024-07-05 11:59 UTC, ssilvert approved these changes, later dismissed

2024-07-05 14:28 UTC, ssilvert approved these changes

2024-07-05 14:48 UTC, agagancarczyk approved these changes

2024-07-05 16:48 UTC, merged