fix(operator): Use the new image to actually perform a database migration
keycloak/keycloak pull request #30450
Opened 2024-06-14 15:24 UTC by torvitas

This fixes #30449.

This change makes the operator behave as described in the issue.
I think this is the way it should work according to the documentation as it is advised to shutdown keycloak completely before doing upgrades.

Assuming you have a set of three pods, the way it is right now the operator performs a database upgrade on keycloak-1 with keycloak-0 still running on the old version if keycloak-1 is able to get to that point, which it does not if for example the infinispan version is incompatible, in that scenario the whole process is stuck with one pod on the old version and a second one on the new version not coming up at all.

2024-06-19 11:39 UTC, shawkins commented
@torvitas can you add a commit signature to this please?

2024-06-20 17:02 UTC, vmuzikar requested changes
@torvitas Thank you for contributing the fix!

The change is assuming that if the Operator changes the image and scales down the deployment at the same time, K8s will first perform the scaling down and then rolls out the new image. AFAIK, while this behaviour might work in some clusters, it's not documented and might be different in different K8s distributions.

I'd suggest instead to handle the order fully via the Operator. I.e. instead of scaling down to 1, I'd just scale to 0 (note that downtime during upgrade is inevitable). WDYT?

2024-06-21 07:49 UTC, torvitas commented
I would argue that "scale to 1 and change image" is not something where either operation comes first. Also scaling down to zero increases the downtime as we will wait for the next reconciliation loop to scale the statefulset back 

Though I agree that the behavior is not very well documented and I would be fine with the proposed change aswell.

2024-06-21 09:01 UTC, vmuzikar requested changes
I believe the down time should not be significantly bigger. The Operator actively watches the statefulset, reconciliation should happen when the scale down is finished.

Could you please also update the condition here?
https://github.com/keycloak/keycloak/blob/bb0e9d69510ff10032da168e2c57fafb23d7d613/operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeploymentDependentResource.java#L464

2024-06-21 13:08 UTC, vmuzikar approved these changes
@torvitas LGTM, thank you.

2024-06-21 13:23 UTC, shawkins approved these changes
LGTM, thank you @torvitas

2024-06-21 13:44 UTC, merged