Added suffix to keycloak-admin-client artifacts in keycloak repository
keycloak/keycloak pull request #30588
Opened 2024-06-19 17:57 UTC by mposolda

2024-06-20 11:06 UTC, mposolda commented
Updated suffix to `keycloak-admin-client-tests` instead of `keycloak-admin-client-orig` as per the discussion with @stianst

2024-06-26 18:57 UTC, pskopek approved these changes
The changes look good to me.
My repository with proposal for keycloak-client-libs is here: https://github.com/pskopek/keycloak-client-libs

This PR works fine with it.

2024-06-27 06:55 UTC, jonkoops requested changes

2024-06-27 06:55 UTC, jonkoops commented on integration/admin-client-jee/pom.xml
> +        For the use by 3rd party applications, please use `org.keycloak:keycloak-admin-client` module.
```suggestion
        For the use by 3rd party applications, please use `org.keycloak:keycloak-admin-client-jee` module.
```

2024-06-27 08:13 UTC, jonkoops approved these changes
LGTM

2024-06-27 09:00 UTC, merged