Add support for managing SSH keys from Keycloak account console
keycloak/keycloak pull request #30793
Opened 2024-06-26 08:57 UTC by linathedog

Closes #30791

2024-06-26 11:47 UTC, linathedog commented
![Screenshot from 2024-06-26 14-46-07](https://github.com/keycloak/keycloak/assets/31310673/a5f705c0-39cd-4d15-8c21-c73bebaab3b8)

2024-06-28 09:18 UTC, ahus1 commented
@linathedog - thank you for the contribution. I'll ping the responsible maintainers for the areas your PR touches. While this is in review, there is no need to rebase the PR unless there are conflicts with the main branch. 

@pedroigor - this seems to be a @keycloak/core-iam topic, don't you think?

2024-07-09 11:17 UTC, edewit requested changes

2024-07-09 11:17 UTC, edewit commented on js/apps/account-ui/src/account-security/SSHKeys.tsx
> +                      Delete
This needs to be translated
```ts
  const { t } = useTranslation();
```
```suggestion
                      {t("delete")}
```

2024-07-09 11:17 UTC, edewit commented on js/apps/account-ui/src/account-security/SSHKeys.tsx
> +            console.log(props.deleteSSHKeyIndex);
this should be removed

2024-07-09 11:17 UTC, edewit commented on js/apps/account-ui/src/account-security/SSHKeys.tsx
> +        </FormGroup>
it would be better to use the react-form here and one the `TextAreaControl`

2024-07-09 11:17 UTC, edewit commented on js/apps/account-ui/src/personal-info/PersonalInfo.tsx
> +          (attribute: any) => attribute.name === "sshPublicKeys",
Why is this necessary?

2024-08-12 07:28 UTC, stianst approved these changes
Having support for managing SSH keys in the account console makes little sense to add directly in Keycloak, and would just be confusing feature for the majority of users.

This should be done through an extension or by customizing the account console rather than added directly to Keycloak.

2024-08-12 07:30 UTC, stianst requested changes
Having support for managing SSH keys in the account console makes little sense to add directly in Keycloak, and would just be confusing feature for the majority of users.

This should be done through an extension or by customizing the account console rather than added directly to Keycloak.

2024-08-13 12:25 UTC, closed without merging