Documenting LDAP connection pooling
keycloak/keycloak pull request #30996
Opened 2024-07-02 11:46 UTC by pedroigor

Closes #30995

2024-07-02 12:01 UTC, rmartinc requested changes
@pedroigor You mmissed one property description. The rest is OK to me.

2024-07-02 12:01 UTC, rmartinc commented on docs/documentation/server_admin/topics/user-federation/ldap.adoc
> +| `com.sun.jndi.ldap.connect.pool.debug` | Surname(s) or last name(s) of the End-User
```suggestion
| `com.sun.jndi.ldap.connect.pool.debug` | A string that indicates the level of debug output to produce. Valid values are "fine" (trace connection creation and removal) and "all" (all debugging information). 
```

2024-07-02 12:21 UTC, rmartinc approved these changes
LGTM!

2024-07-02 18:19 UTC, andymunro commented on docs/documentation/server_admin/topics/user-federation/ldap.adoc
> +For more details, consider looking at the link:https://docs.oracle.com/javase/jndi/tutorial/ldap/connect/config.html[Java LDAP Connection Pooling Configuration] documentation.
```suggestion
For more details, see the link:https://docs.oracle.com/javase/jndi/tutorial/ldap/connect/config.html[Java LDAP Connection Pooling Configuration] documentation.
```

2024-07-02 18:20 UTC, andymunro commented on docs/documentation/server_admin/topics/user-federation/ldap.adoc
> +- For tracking the performance or connection pooling issues, consider setting the value of property `com.sun.jndi.ldap.connect.pool.debug` to `all`. This will add lots of additional messages to serve
```suggestion
- For tracking the performance or connection pooling issues, consider setting the value of property `com.sun.jndi.ldap.connect.pool.debug` to `all`. This change adds many additional messages to the server log with the included logging for the LDAP connection
```

2024-07-02 18:21 UTC, andymunro commented on docs/documentation/server_admin/topics/user-federation/ldap.adoc
> +pooling. This can be used to track the issues related to connection pooling or performance. Look at the link:#_ldap_connection_pool[Configuring the connection pool] for more details.
```suggestion
pooling. As a result, you can track the issues related to connection pooling or performance. For more details, see link:#_ldap_connection_pool[Configuring the connection pool].
```

2024-07-02 18:24 UTC, andymunro requested changes
Looks well-written, @pedroigor, with a few suggestions.

2024-07-03 10:27 UTC, pedroigor commented
Thanks, @andymunro. Applied your suggestions.

2024-07-04 11:21 UTC, ahus1 approved these changes
Approving based on @rmartinc's and @andymunro's reviews

2024-07-04 11:21 UTC, merged