Translations update from Hosted Weblate
keycloak/keycloak pull request #30998
Opened 2024-07-02 12:11 UTC by weblate

Translations update from [Hosted Weblate](https://hosted.weblate.org) for [Keycloak/Admin UI](https://hosted.weblate.org/projects/keycloak/admin-ui/).

It also includes following components:

* [Keycloak/Account UI](https://hosted.weblate.org/projects/keycloak/account-ui/)

* [Keycloak/Theme base/admin](https://hosted.weblate.org/projects/keycloak/theme-baseadmin/)

* [Keycloak/Theme base/account](https://hosted.weblate.org/projects/keycloak/theme-baseaccount/)

* [Keycloak/Theme base/login](https://hosted.weblate.org/projects/keycloak/theme-baselogin/)

* [Keycloak/Theme base/email](https://hosted.weblate.org/projects/keycloak/theme-baseemail/)

Current translation status:

![Weblate translation status](https://hosted.weblate.org/widget/keycloak/admin-ui/horizontal-auto.svg)

2024-07-02 15:20 UTC, ahus1 requested changes
Hi @robson90 - thank you for these translations. IMHO you stumbled across some terms that are specific to SAML that maybe should not be translated. See below for some comments. Thanks!

2024-07-02 15:20 UTC, ahus1 commented on js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_de.properties
> +eventTypes.UPDATE_TOTP.name=Update totp
@robson90 - could you please create a PR for the English text that it is `Update TOTP`, as TOTP is an acronym for a time-based one-time password. In parallel, I suggest to name this `Aktualisierung TOTP`.

2024-07-02 15:20 UTC, ahus1 commented on js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_de.properties
> +subjectNameId=Betreff NameID
IMHO this is a technical term in SAML and therefore shouldn't be translated.

2024-07-02 15:20 UTC, ahus1 commented on js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_de.properties
> +eventTypes.LOGOUT_ERROR.name=Logout Fehler
Similar to the above, I suggest for example `Fehler beim Anmelden` or `Anmeldefehler`. Please review the other `eventTypes.*.name` entries as well.

2024-07-02 15:20 UTC, ahus1 commented on js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_de.properties
> +assertionLifespan=Behauptung Lebensdauer
IMHO an `Assertion` is again a SAML specific term which shouldn't be translated. Maybe `Assertion Gültigkeitsdauer`?

2024-07-02 15:20 UTC, ahus1 commented on js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_de.properties
> +eventTypes.IMPERSONATE.name=Impersonieren
Not sure if there is a good German word for this. What about `Sich ausgeben als`? The context where this is used: An admin can impersonate a user and then act as this user for example to verify a problem the user is reporting.

2024-07-02 16:32 UTC, robson90 reviewed
I checked some of the `eventTypes.*` and stumbled upon these words, that are very hard to get translated right. Do you have any suggestions ?

`Introspection`
`Impersonate error`

I did also Update all those Strings to be the same. Please re-review:
- Client update
- Delete Account
- Logout
- Execute actions
- Update password

2024-07-18 09:41 UTC, ahus1 approved these changes

2024-07-18 09:45 UTC, ahus1 commented
@robson90 - this one took a bit longer to review than I hoped as I found out that those events are really hard to translate. @jonkoops and me were also looking into Weblate configurations to figure out if we can split different languages into to different pull requests as this would allow us to onboard additional languages, and have a review of single languages in each PR. 

I change my mind about the translation of "impersonate" ... I now translated it as "Identität annehmen". Let me know what you think of this.

2024-07-18 10:25 UTC, merged