fix: remove the proxy setting is a url hostname is in use
keycloak/keycloak pull request #31003
Opened 2024-07-02 14:53 UTC by shawkins

closes: #30945

2024-07-02 16:53 UTC, Pepo48 approved these changes, later dismissed

2024-07-03 13:54 UTC, vmuzikar requested changes
As discussed in https://github.com/keycloak/keycloak/issues/30945#issuecomment-2205772347, I believe we should rather remove the defaults from the Operator.

2024-07-04 09:49 UTC, vmuzikar approved these changes
@shawkins LGTM, thank you.

2024-07-11 12:13 UTC, Pepo48 approved these changes

2024-07-11 12:21 UTC, merged