DRAFT. Adding database configuration.
keycloak/keycloak pull request #31073
Opened 2024-07-05 10:21 UTC by miquelsi

2024-07-08 09:45 UTC, vaceksimon requested changes

2024-07-08 09:45 UTC, vaceksimon commented on test-poc/framework/src/main/java/org/keycloak/test/framework/server/KeycloakTestServerSupplier.java
> +        DatabaseConfig databaseConfig = annotation.dbconfig() != null ? SupplierHelpers.getInstance(annotation.dbconfig()) : new DefaultDatabaseConfig();
I think it can be left like this because the `dbconfig()` returns the default value (`DefaultDatabaseConfig.class`) if it is not entered. 

```suggestion
        DatabaseConfig databaseConfig = SupplierHelpers.getInstance(annotation.dbconfig());
```

2024-07-09 07:51 UTC, vaceksimon approved these changes

2024-07-09 08:00 UTC, stianst reviewed
What I had in mind is close to this, but not quite.

My idea was that we would have multiple database suppliers:

* PostgresDatabaseSupplier
* MySQLDatabaseSupplier
* DevFileDatabaseSupplier
* DevMemDatabaseSupplier

Each supplier would supply a `TestDatabase` with `start`/`stop` methods, and a `getConfig()` method.

You'd select which DB supplier to use with https://github.com/keycloak/keycloak/issues/30609 in the same way as we would select a different server run-mode or browser.

`TestDatabase` would be responsible for starting/stopping the DB container using test containers.

For now it's fine that DBs are not configurable (we just let it auto configure itself to some sensible defaults), and that we don't support connecting to external DBs, we can do that as a follow-up.

2024-07-11 12:24 UTC, stianst commented on test-poc/framework/src/main/java/org/keycloak/test/framework/database/ExternalDatabaseConfig.java
What's the purpose of this class?

2024-07-11 12:26 UTC, stianst commented on test-poc/framework/src/main/java/org/keycloak/test/framework/server/AbstractKeycloakTestServerSupplier.java
> +        DatabaseSupplier databaseSupplier = new DevMemDatabaseSupplier();
This should not create the database supplier, but it should just use the registry to look it up:
```
registry.getDependency(TestDatabase.class, wrapper);
```

See https://github.com/keycloak/keycloak/blob/9247029ca3f1db14d92255e7804dd60a93f10e69/test-poc/framework/src/main/java/org/keycloak/test/framework/realm/RealmSupplier.java#L29-L50 as an example on how to get a dependency in a supplier.

2024-07-11 12:28 UTC, lhanusov commented on test-poc/framework/src/main/java/org/keycloak/test/framework/database/DevMemDatabaseConfig.java
> +public class DevMemDatabaseConfig implements DatabaseConfig {
Don't you want to introduce rather DefaultDatabaseConfig class?

2024-07-11 12:31 UTC, lhanusov commented on test-poc/framework/src/main/java/org/keycloak/test/framework/database/DatabaseSupplier.java
> +public abstract class DatabaseSupplier implements Supplier<TestDatabase, Annotation> {
Did you consider some TestManagedDatabase annotation which will be reused within KeycloakIntegrationTest annotation for ServiceLoader injection?

2024-07-11 12:32 UTC, stianst commented on test-poc/framework/src/main/java/org/keycloak/test/framework/server/DistributionKeycloakTestServer.java
> +    public void start(KeycloakTestServerConfig serverConfig, TestDatabase testDatabase) {
Maybe it would be cleaner to just pass the DatabaseConfig? Makes it clear that it shouldn't be stopping/starting the db or anything like that ;)

2024-07-11 12:32 UTC, stianst commented on test-poc/framework/src/main/java/org/keycloak/test/framework/server/AbstractKeycloakTestServerSupplier.java
>      public InstanceWrapper<KeycloakTestServer, KeycloakIntegrationTest> getValue(Registry registry, KeycloakIntegrationTest annotation) {
One thing to consider is that RemoteKeycloakTestServer shouldn't use a DatabaseSupplier, as it doesn't need one.

2024-07-11 12:32 UTC, stianst commented on test-poc/framework/src/main/java/org/keycloak/test/framework/server/EmbeddedKeycloakTestServer.java
> +            testDatabase.start();
KeycloakTestServer shouldn't be starting the database, that is the database suppliers job

2024-07-11 12:32 UTC, stianst commented on test-poc/framework/src/main/java/org/keycloak/test/framework/server/EmbeddedKeycloakTestServer.java
> +            rawOptions.add("--db-password=" + databaseConfig.password());
Could be good to create a helper of sorts for this, as both the embedded and the distribution servers needs to be able to convert a DatabaseConfig into CLI arguments.

2024-07-11 12:49 UTC, lhanusov commented on test-poc/framework/src/main/java/org/keycloak/test/framework/database/DatabaseSupplier.java
> +    protected static TestDatabase testDatabase = new TestDatabase(new DevMemDatabaseConfig());
Since the annotation introduction this could be then omitted and used like this: https://github.com/keycloak/keycloak/blob/main/test-poc/framework/src/main/java/org/keycloak/test/framework/KeycloakIntegrationTest.java#L15

2024-07-11 12:51 UTC, lhanusov commented on test-poc/framework/src/main/java/org/keycloak/test/framework/database/DatabaseSupplier.java
> +public abstract class DatabaseSupplier implements Supplier<TestDatabase, Annotation> {
e.g. https://github.com/keycloak/keycloak/blob/main/testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/JavascriptBrowser.java#L32

2024-07-11 12:53 UTC, lhanusov commented on test-poc/framework/src/main/java/org/keycloak/test/framework/server/AbstractKeycloakTestServerSupplier.java
> +        DatabaseSupplier databaseSupplier = new DevMemDatabaseSupplier();
Rather then getting supplier I am thinking of fully manged DB called within the KeycloakIntegrationTest annotation as a prerequisite, do you think @stianst it makes sense?

2024-07-15 13:53 UTC, lhanusov requested changes

2024-07-15 13:53 UTC, lhanusov commented on test-poc/framework/src/main/java/org/keycloak/test/framework/server/EmbeddedKeycloakTestServer.java
> +        serverConfig.adminUserName().ifPresent(username -> System.setProperty("keycloakAdmin", username));
@miquelsi dont't forget to rebase to main, because this change was added few days ago: https://github.com/keycloak/keycloak/commit/4970a9b7293359bb813accb16e12d4938d1928f5

2024-07-16 07:28 UTC, stianst approved these changes

2024-07-16 07:28 UTC, merged