Added template overrides
keycloak/keycloak pull request #31106
Opened 2024-07-08 11:59 UTC by edewit

fixes: #31021

2024-07-08 12:01 UTC, edewit commented
![image](https://github.com/keycloak/keycloak/assets/51133/f276b660-419e-45b2-9167-d4e6b71d4f6b)
![image](https://github.com/keycloak/keycloak/assets/51133/af3a91ac-9f74-42fa-a9f0-ac87e8fb293f)

2024-07-09 10:28 UTC, edewit commented
@xianli123 right, made "cancel button" a link

2024-07-15 08:45 UTC, thomasdarimont commented
@edewit I think you could also fix the invalid css selector in the javascript snippet, 
`.kc-recovery-codes-list li ` should be `#kc-recovery-codes-list li `.

See: https://github.com/keycloak/keycloak/issues/31260

2024-07-15 09:03 UTC, thomasdarimont requested changes
We should use the proper css selector for the recovery-codes-list.

2024-07-15 09:03 UTC, thomasdarimont commented on themes/src/main/resources/theme/base/login/login-recovery-authn-code-config.ftl
> +    var recoveryCodes = document.querySelectorAll(".kc-recovery-codes-list li");
```suggestion
    var recoveryCodes = document.querySelectorAll("#kc-recovery-codes-list li");
```

2024-07-15 09:03 UTC, thomasdarimont commented on themes/src/main/resources/theme/keycloak.v2/login/login-recovery-authn-code-config.ftl
> +    var recoveryCodes = document.querySelectorAll(".kc-recovery-codes-list li");
```suggestion
    var recoveryCodes = document.querySelectorAll("#kc-recovery-codes-list li");
```

2024-07-15 09:03 UTC, thomasdarimont commented on themes/src/main/resources/theme/keycloak.v2/login/resources/css/styles.css
> +.kc-recovery-codes-list {
```suggestion
#kc-recovery-codes-list {
```

2024-07-15 09:33 UTC, jonkoops requested changes

2024-07-15 09:33 UTC, jonkoops commented on themes/src/main/resources/theme/base/login/login-recovery-authn-code-config.ftl
I see a bunch of PatternFly 5 classes here. The base theme is used by login v1 as well, so would this not break that version of the login theme as it doesn't include PatternFly 5?

2024-07-15 10:19 UTC, edewit commented on themes/src/main/resources/theme/base/login/login-recovery-authn-code-config.ftl
v1 has it's own version of this

2024-07-15 10:21 UTC, jonkoops commented on themes/src/main/resources/theme/base/login/login-recovery-authn-code-config.ftl
Still, users could be extending the `base` theme, that happens quite frequently. If the V2 one has it's own template this one does not need to be updated.

2024-07-15 10:42 UTC, jonkoops approved these changes

2024-07-15 11:14 UTC, thomasdarimont approved these changes

2024-07-15 12:47 UTC, merged