TestSuite PoC - Remove Test prefix from annotations
keycloak/keycloak pull request #31528
Opened 2024-07-23 12:03 UTC by jonkoops

Closes #31522

2024-07-23 12:17 UTC, vaceksimon approved these changes
I'm not a fan of what it did to references to the selenium `WebDriver` class, but I can live with it

2024-07-23 12:17 UTC, vaceksimon commented on test-poc/examples/src/test/java/org/keycloak/test/examples/WelcomePageTest.java
> +    org.openqa.selenium.WebDriver driver;
So we have a little conflict. But I think this is fine

2024-07-23 12:27 UTC, miquelsi commented on test-poc/examples/src/test/java/org/keycloak/test/examples/WelcomePageTest.java
> +    org.openqa.selenium.WebDriver driver;
Can we think of a better name for this case? I'm also not convinced with the conflict

2024-07-23 13:03 UTC, vaceksimon commented on test-poc/examples/src/test/java/org/keycloak/test/examples/WelcomePageTest.java
> +    org.openqa.selenium.WebDriver driver;
Maybe `WebBrowser`, `Browser`, `BrowserDriver`, or just `Driver`? :car:

2024-07-24 06:23 UTC, stianst requested changes
What happened to WebDriver makes me re-consider this naming convention, and I propose we continue to have a prefix. That also would help to differ these type of annotations from other annotations.

I propose we stick with `@TestRealm`, or change to `@InjectRealm`.

2024-07-24 10:17 UTC, jonkoops commented
> I propose we stick with `@TestRealm`, or change to `@InjectRealm`.

Created #31570 to rename this to `Inject`

2024-07-24 10:45 UTC, lhanusov commented
Can you please close this one? @jonkoops.

2024-07-24 11:21 UTC, Aboullos commented on test-poc/examples/src/test/java/org/keycloak/test/examples/WelcomePageTest.java
> +    org.openqa.selenium.WebDriver driver;
What usually did was name it DriverHelper

2024-07-24 12:58 UTC, jonkoops commented
I'll close it if we decide to merge the other one :)

2024-07-25 07:23 UTC, stianst requested changes
Let's go with the `Inject` prefix. @jonkoops can you update the PR?

2024-07-25 11:14 UTC, stianst commented
#31570 was merged, so closing this one

2024-07-25 11:14 UTC, closed without merging