Bugfix: "User Profile" attributes not available for Users Attribute search
keycloak/keycloak pull request #31771
Opened 2024-07-30 15:19 UTC by danielFesenmeyer

... when admin user does not have view- or manage-realm realm-management role

Closes #27536

2024-08-12 08:49 UTC, edewit commented
@pedroigor what do you think about this?

2024-08-19 10:10 UTC, pedroigor submitted a review, later dismissed

2024-08-20 09:42 UTC, edewit requested changes

2024-08-20 09:42 UTC, edewit commented on js/apps/admin-ui/src/components/users/UserDataTableAttributeSearchForm.tsx
> +      data-testid={"user-attribute-search-form"}
```suggestion
      data-testid="user-attribute-search-form"
```

2024-08-20 09:42 UTC, edewit commented on js/apps/admin-ui/src/components/users/UserDataTableAttributeSearchForm.tsx
> +              data-testid={"user-attribute-search-add-filter-button"}
```suggestion
              data-testid="user-attribute-search-add-filter-button"
```

2024-08-20 09:42 UTC, edewit commented on js/apps/admin-ui/src/components/users/UserDataTable.tsx
> +                  data-testid={"user-attribute-search-chips-group"}
```suggestion
                  data-testid="user-attribute-search-chips-group"
```

2024-09-03 10:20 UTC, danielFesenmeyer commented on js/apps/admin-ui/src/components/users/UserDataTableAttributeSearchForm.tsx
> +      data-testid={"user-attribute-search-form"}
Adjusted.

2024-09-03 10:23 UTC, danielFesenmeyer commented
@edewit I've applied your simplifications, thanks for those suggestions.

If tests are still passing, the PR can be merged from my POV.

2024-09-18 19:49 UTC, sguilhen approved these changes
LGTM

2024-09-19 05:56 UTC, edewit approved these changes

2024-09-20 14:30 UTC, mposolda approved these changes

2024-09-20 18:06 UTC, merged

2024-09-23 08:08 UTC, danielFesenmeyer commented
Thanks guys for the review and merge :smiley:

2025-07-07 20:04 UTC, fvales commented on js/apps/admin-ui/src/components/users/UserDataTable.tsx
> +  if (!uiRealmInfo || !realm) {
Shouldn't this be 
```
if (uiRealmInfo.userProfileProvidersEnabled === undefined || !realm) {
  return <KeycloakSpinner />;
}
``` 
as uiRealmInfo is initialized as empty object?
API call to fetch users is made even if user federation is enabled

2025-07-08 09:43 UTC, ahus1 commented on js/apps/admin-ui/src/components/users/UserDataTable.tsx
> +  if (!uiRealmInfo || !realm) {
@fvales - if you think this is a bug, please create a new issue, possibly describing the expected vs. actual behavior.