Added gh-dependabot-failure-stats script
keycloak/keycloak pull request #31773
Opened 2024-07-30 16:06 UTC by agagancarczyk

Closes https://github.com/keycloak/keycloak/issues/31772

2024-07-31 06:10 UTC, edewit approved these changes, later dismissed

2024-07-31 08:22 UTC, edewit submitted a review, later dismissed

2024-07-31 14:30 UTC, ssilvert requested changes

2024-08-07 18:56 UTC, agagancarczyk commented on js/util/gh-dependabot-failure-stats.sh
> +  gh api -X GET "/repos/${REPO_OWNER}/${REPO_NAME}/commits/$(gh pr view "$pr_number" --repo "${REPO_OWNER}/${REPO_NAME}" --json headRefOid -q .headRefOid)/check-runs" -q '.check_runs[] | select(.conc
I added new implementation of this. Should work now :)

2024-08-08 18:09 UTC, ssilvert approved these changes

2024-08-08 19:09 UTC, merged