Deprecate legacy cookie behaviour
keycloak/keycloak pull request #31809
Opened 2024-07-31 14:17 UTC by jonkoops

Closes #16181

2024-08-12 10:13 UTC, stianst commented on services/src/main/java/org/keycloak/cookie/DefaultCookieProviderFactory.java
You'll also need to update:
https://github.com/keycloak/keycloak/blob/a17fd5566962d54b24e54a16f6598c9e36856e62/services/src/main/java/org/keycloak/cookie/DefaultCookieProviderFactory.java#L23

As well as update the test in https://github.com/keycloak/keycloak/blob/main/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/cookies/DefaultCookieProviderTest.java. This may be a bit challenging to test that legacy cookies can still be enabled

2024-08-12 10:18 UTC, ahus1 requested changes
I still see some UX problems with the current implementation when we disable it as you describe. The following will not work, and we should make it work somehow:

* You start Keycloak and open it on http://0.0.0.0:8080/ as printed on the console (or like the bookmark that worked earlier) -> you can't log in, as it is not a secure context. Maybe we should redirect to http://localhost:8080/ automatically?

* You have Keycloak running in a setup without https, and Keycloak knows that, so every login attempt will fail. Keycloak knows that as you started the server with `--http-enabled true` and the hostname doesn't start with `https://` and/or the forwarded headers don't show that you are using `https`.

* The message "Cookie not found. Please make sure cookies are enabled in your browser." is only half-true, as it might actually be a misconfiguration on the server side to not have HTTPS enabled.

To turn it around a bit:

* If we know that the caller doesn't use https, we shouldn't send a secure cookie
* If you don't want your caller to use http, you'll need to configure your reverse proxy to redirect to https / not to accept http.

At the same time I know that only "localhost" can provide a secure context, while other non-HTTPS URLs can't provide it. Still, we need to fix the UX. 

Feel free to schedule a meeting around that topic.

2024-08-12 11:07 UTC, stianst commented
`_LEGACY` cookies end up defaulting to SameSite=Lax, but differently to those where we set SameSite explicitly they don't use the secure flag.

That means that with the LEGACY cookies you can still login to Keycloak without http (as well as any applications using the same context). This is behaviour that we may want to keep rather than deprecate?

One option we could consider is being a bit smarter about how we set the secure flag to keep the behaviour without needing the LEGACY cookies. We could leverage the Realm.getSslRequired option, and also perhaps consider introducing a server-wide default for this. 

We could set the secure flag simply based on if a secure context is used or not; and simply show an error page if `https` is required (either by realm, or the new global option).

One additional thing here is that we should probably make it more clear that a secure context is required for OIDC/SAML flows across multiple contexts.

2024-08-12 13:23 UTC, jonkoops commented
Converting this to a draft until we have resolved the pending discussion.

2024-08-15 13:31 UTC, closed without merging

2024-08-15 13:31 UTC, ahus1 commented
obsolete due to #32130