Fix for Incorrect warning log about deprecated options hostname, hostname-debug
keycloak/keycloak pull request #31827
Opened 2024-08-01 08:45 UTC by kaustubh-rh

Added a check in handleDeprecated function in Picocli.java

2024-08-01 09:42 UTC, kaustubh-rh commented
Hi @vmuzikar , raised a PR for the same :)

2024-08-06 12:30 UTC, mposolda commented
@vmuzikar Assigning PR to you as the issue itself is also assigned to you.

2024-08-06 14:09 UTC, vmuzikar requested changes
@kaustubh-rh Thank you for the PR!

2024-08-06 14:09 UTC, vmuzikar commented on quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java
> +            if (!mapper.getDeprecatedMetadata().get().getNewOptionsKeys().isEmpty() || mapper.getDeprecatedMetadata().get().getNote() != null || !mapper.getDeprecatedMetadata().get().getDeprecatedVal
I'm afraid we can't do this. With this condition that don't have any new keys, note, or value will not be printed. A warning should be emitted when e.g. Keycloak is started as:
```
kc.sh start-dev --features=hostname:v1 --hostname=abc
```

2024-08-06 17:33 UTC, closed without merging