Aligning the JS build and caching with the main build
keycloak/keycloak pull request #31846
Opened 2024-08-01 17:07 UTC by ahus1

Closes #31845

2024-08-01 17:19 UTC, jonkoops approved these changes, later dismissed

2024-08-05 08:12 UTC, edewit approved these changes, later dismissed

2024-08-12 12:17 UTC, jonkoops requested changes

2024-08-12 12:17 UTC, jonkoops commented on .github/actions/pnpm-setup/action.yml
Looking at the code that uses this action I no longer see the `working-directory` input being passed anywhere, so let's get rid of it altogether.

2024-08-12 12:17 UTC, jonkoops commented on .github/actions/pnpm-setup/action.yml
> +        pnpm store prune
That is a useful command, very nice.

2024-08-12 14:36 UTC, ahus1 commented
@jonkoops - thank you for spotting this. This is now fixed. Please re-approve.

2024-08-12 15:03 UTC, jonkoops approved these changes
LGTM!

2024-08-13 07:05 UTC, mhajas approved these changes
Approving based on the reviews from @jonkoops and @edewit

2024-08-13 07:05 UTC, merged