fix: always replacing placeholders
keycloak/keycloak pull request #31871
Opened 2024-08-02 16:32 UTC by shawkins

closes: #31625

2024-08-07 10:17 UTC, mabartos reviewed
@shawkins Just a few nitpick suggestions. Otherwise, LGTM.

2024-08-07 10:17 UTC, mabartos commented on docs/documentation/upgrading/topics/changes/changes-26_0_0.adoc
> += kc import placeholder replacement
```suggestion
= CLI import placeholder replacement
```
I'd prefer this.

2024-08-07 10:17 UTC, mabartos commented on docs/documentation/upgrading/topics/changes/changes-26_0_0.adoc
> +kc.[sh|bat] import now has placeholder replacement enabled. Previously placeholder replacement was only enabled for realm import at startup.
```suggestion
CLI command `kc.[sh|bat] import` now has placeholder replacement enabled. Previously placeholder replacement was only enabled for realm import at startup. 
```

2024-08-08 09:01 UTC, mabartos commented
Some conflict there; otherwise, LGTM.

2024-08-08 13:23 UTC, mabartos submitted a review, later dismissed

2024-08-12 08:39 UTC, vmuzikar requested changes
@shawkins Thank you for the changes! We should probably also update [this](https://github.com/keycloak/keycloak/blob/e7d9a717c9cf4d3b0089af3618f78efce15b38db/docs/guides/server/importExport.adoc?plain=1#L114) chapter in the guide to be generic for the `import` command as well as startup.

2024-08-12 11:46 UTC, shawkins commented
> @shawkins Thank you for the changes! We should probably also update [this](https://github.com/keycloak/keycloak/blob/e7d9a717c9cf4d3b0089af3618f78efce15b38db/docs/guides/server/importExport.adoc?plain=1#L114) chapter in the guide to be generic for the `import` command as well as startup.

Quite right, I had missed that it was specific to startup. Corrected now.

2024-08-12 11:47 UTC, mabartos commented on docs/documentation/upgrading/topics/changes/changes-26_0_0.adoc
> += kc import placeholder replacement
It seems the changes were reverted.

2024-08-12 11:53 UTC, shawkins commented on docs/documentation/upgrading/topics/changes/changes-26_0_0.adoc
> += kc import placeholder replacement
Applied again.

2024-08-12 12:22 UTC, mabartos submitted a review, later dismissed

2024-08-12 14:10 UTC, vmuzikar approved these changes, later dismissed

2024-08-12 14:12 UTC, vmuzikar commented
Realized we can also remove:
https://github.com/keycloak/keycloak/blob/242796b89679933ae8df63953960308eef5afb07/operator/src/main/java/org/keycloak/operator/controllers/KeycloakRealmImportJobDependentResource.java#L152

But we can do it as a follow-up.

2024-08-12 14:20 UTC, shawkins commented
> Realized we can also remove:
> 
> https://github.com/keycloak/keycloak/blob/242796b89679933ae8df63953960308eef5afb07/operator/src/main/java/org/keycloak/operator/controllers/KeycloakRealmImportJobDependentResource.java#L152
> 
> But we can do it as a follow-up.

Updated fine to remove that with this pr - since the feature just went into 26 there's no concern about a behavioral change.

2024-08-12 14:26 UTC, vmuzikar approved these changes

2024-08-12 16:20 UTC, merged