Initial implementation of ClientRepresentation
keycloak/keycloak pull request #32306
Opened 2024-08-21 11:52 UTC by vmuzikar

Partially addresses #31813

Follows the design (with its caveats) as specified in https://github.com/keycloak/keycloak/issues/31813#issuecomment-2299102909.

2024-08-21 11:54 UTC, vmuzikar commented
CC @keycloak/cloud-native

2024-08-21 14:58 UTC, shawkins commented
@vmuzikar the only minor consideration is that if the inner records are effectively like inner classes, then the sundrio builder logic won't currently work with that - but that's not a blocker for me as we can workaround it and is something that could be improved in sundrio.

2024-09-02 16:05 UTC, jonkoops requested changes

2024-09-02 16:05 UTC, jonkoops commented on core/src/main/java/org/keycloak/representations/admin/v2/ClientRepresentation.java
> +}
One major irk I have with the current REST API is the lack of information about which values are possibly `null`, this causes major headaches for the front-end. If possible all fields should be annotated with `@JsonProperty(required = true)`.
```suggestion
public record ClientRepresentation(
    @JsonProperty(required = true)
    @JsonPropertyDescription("ID uniquely identifying this client")
    String clientId,

    @JsonProperty(required = true)
    @JsonPropertyDescription("Human readable name of the client")
    String displayName,

    @JsonProperty(required = true)
    @JsonPropertyDescription("Human readable description of the client")
    String description,

    @JsonProperty(required = true)
    @JsonPropertyDescription("The protocol used to communicate with the client")
    String protocol,

    @JsonProperty(required = true)
    @JsonPropertyDescription("Whether this client is enabled")
    Boolean enabled,

    @JsonProperty(required = true)
    @JsonPropertyDescription("URL to the application's homepage that is represented by this client")
    String appUrl,

    @JsonProperty(required = true)
    @JsonPropertyDescription("URLs that the browser can redirect to after login")
    Set<String> appRedirectUrls,

    @JsonProperty(required = true)
    @JsonPropertyDescription("Login flows that are enabled for this client")
    Set<String> loginFlows,

    @JsonProperty(required = true)
    @JsonPropertyDescription("Authentication configuration for this client")
    Auth auth,

    @JsonProperty(required = true)
    @JsonPropertyDescription("Web origins that are allowed to make requests to this client")
    String webOrigins,

    @JsonProperty(required = true)
    @JsonPropertyDescription("Roles associated with this client")
    Set<String> roles,

    @JsonProperty(required = true)
    @JsonPropertyDescription("Service account configuration for this client")
    ServiceAccount serviceAccount
) {
    public record Auth(
            @JsonProperty(required = true)
            @JsonPropertyDescription("Whether authentication is enabled for this client")
            Boolean enabled,
 
            @JsonProperty(required = true)
            @JsonPropertyDescription("Which authentication method is used for this client")
            String method,

            @JsonProperty(required = true)
            @JsonPropertyDescription("Secret used to authenticate this client with Secret authentication")
            String secret,

            @JsonProperty(required = true)
            @JsonPropertyDescription("Public key used to authenticate this client with Signed JWT authentication")
            String certificate
    ) {}

    public record ServiceAccount(
            @JsonProperty(required = true)
            @JsonPropertyDescription("Whether the service account is enabled")
            Boolean enabled,

            @JsonProperty(required = true)
            @JsonPropertyDescription("Roles assigned to the service account")
            Set<String> roles
    ) {}
}
```

2025-01-17 08:31 UTC, closed without merging