Add `didInitialize` to Keycloak typings
keycloak/keycloak pull request #32331
Opened 2024-08-22 09:04 UTC by maapteh

closes https://github.com/keycloak/keycloak/issues/27040

follow up on https://github.com/keycloak/keycloak/pull/20722 where it was added to JS but not in its d.ts

2024-08-27 14:01 UTC, jonkoops requested changes

2024-08-27 14:27 UTC, maapteh commented on js/libs/keycloak-js/dist/keycloak.d.ts
> +	didInitialize?: true
I think i wanted to do that, but the Keycloak type is used for intialisation as well which means when i type it as non optional suddenly there it also gets required. For me coding in pure js is long time ago so i have to see how.

Thanks for the review btw!

2024-08-28 19:27 UTC, maapteh commented
@jonkoops I think i resolved them :) could not find test suite?

2024-09-02 11:42 UTC, jonkoops requested changes

2024-09-02 11:42 UTC, jonkoops commented on js/libs/keycloak-js/dist/keycloak.d.ts
> +	didInitialize: true
```suggestion
	didInitialize: boolean;
```

2024-09-03 12:51 UTC, jonkoops approved these changes
LGTM, thanks @maapteh!

2024-09-03 12:52 UTC, merged

2024-10-02 13:52 UTC, maapteh commented
@jonkoops do you know when this typing fix wil land, approximately :)

2024-10-02 16:10 UTC, jonkoops commented
You can see when things land by looking at the labels on the issue it [is attached to](https://github.com/keycloak/keycloak/issues/27040). So in this case the tag is `release/26.0.0`, which means it will be part of `26.0.0`.

2024-10-08 07:59 UTC, maapteh commented
Thanks for the release Jon!