Add OAuth SIG meeting link to README
keycloak/keycloak pull request #32385
Opened 2024-08-26 07:51 UTC by y-tabata

Closes https://github.com/keycloak/keycloak/issues/32384

2024-08-28 08:04 UTC, francis-pouatcha approved these changes

2024-09-03 07:21 UTC, tnorimat commented
@abstractj Hello, what do you think about the PR for being aligned with CNCF project

2024-09-04 15:29 UTC, abstractj commented
> @abstractj Hello, what do you think about the PR for being aligned with CNCF project

What exactly do you mean @tnorimat ?

Reading the proposal, I don't see any harm about having it in the README file, but I'm curious about what our @keycloak/maintainers think.

Another good alternative is the approach used by the Knative team, providing a shared calendar - https://knative.dev/docs/community/#meetings. That would make things easy to add to the website (I believe).

2024-09-05 02:11 UTC, y-tabata commented
@abstractj 
From a CNCF perspective, this proposal stems from [this discussion](https://github.com/keycloak/keycloak/discussions/30843) created by Chris, the CNCF CTO.
Considering Keycloak becoming a CNCF Graduated project, he said that one of the effective ways is to up [the CLOMonitor Score](https://clomonitor.io/projects/cncf/keycloak).
This proposal is an effort to pass [the Best Practice Community meeting check](https://clomonitor.io/docs/topics/checks/#community-meeting).

2024-09-18 02:50 UTC, y-tabata commented
@abstractj Could you check the above comment and review this PR?

2024-10-10 09:00 UTC, stianst requested changes
I don't think this belongs in the README, but rather on the website.

I'd suggest adding a section to https://www.keycloak.org/community (https://github.com/keycloak/keycloak-web/blob/main/pages/community.ftl) that lists the OAuth SIG, and also community meetings.

2024-10-11 03:34 UTC, y-tabata commented
@stianst 
Thank you for your feedback. 
Does it make sense to write a link to the community site's meeting section in the "Help and Documentation" section of the README, after posting information about the meetings on the community site?

2024-10-11 05:00 UTC, stianst commented
> @stianst Thank you for your feedback. Does it make sense to write a link to the community site's meeting section in the "Help and Documentation" section of the README, after posting information about the meetings on the community site?

Not sure, doesn't feel the most natural place for it. Maybe it would make more sense in the contributing section? We could definitively expand a bit on that on how people can engage by joining SIGs, finding things to work on, etc.

2024-10-11 05:10 UTC, y-tabata commented
Okay, so I'll add the information to the community site and then create a PR to add a link to it in the README.

2024-10-11 08:00 UTC, y-tabata commented
@stianst 
I added the link to the community site in the README.

2024-10-11 08:08 UTC, stianst commented on README.md
> +Our [website](https://www.keycloak.org/community) lists the community meetings, you may find things to work on by joining them.
```suggestion
Joining a [community meeting](https://www.keycloak.org/community) is a great way to get involved and help shape the future of Keycloak.
```

2024-10-11 08:20 UTC, y-tabata commented on README.md
> +Our [website](https://www.keycloak.org/community) lists the community meetings, you may find things to work on by joining them.
@stianst 
Thanks, I've incorporated your suggested fixes.

2024-10-11 08:49 UTC, stianst approved these changes

2024-10-11 08:49 UTC, merged