added text and tooltip to idp
keycloak/keycloak pull request #32411
Opened 2024-08-27 05:37 UTC by edewit

Signed-off-by: Erik Jan de Wit <erikjan.dewit@gmail.com>

2024-08-27 08:21 UTC, agagancarczyk submitted a review, later dismissed

2024-08-27 08:26 UTC, ahus1 requested changes
Several brand names should need fixing of the capitalization. The test failure might be related, not sure.

2024-08-27 08:26 UTC, ahus1 commented on themes/src/main/resources/theme/keycloak.v2/login/login.ftl
> +                                                <title id="title">Github</title>
```suggestion
                                                <title id="title">GitHub</title>
```

2024-08-27 08:26 UTC, ahus1 commented on themes/src/main/resources/theme/keycloak.v2/login/login.ftl
> +                                                <title id="title">Gitlab</title>
```suggestion
                                                <title id="title">GitLab</title>
```

2024-08-27 08:26 UTC, ahus1 commented on themes/src/main/resources/theme/keycloak.v2/login/login.ftl
> +                                                <title id="title">Openshift</title>
```suggestion
                                                <title id="title">OpenShift</title>
```

2024-08-27 08:26 UTC, ahus1 commented on themes/src/main/resources/theme/keycloak.v2/login/login.ftl
> +                                                <title id="title">Stackoverflow</title>
```suggestion
                                                <title id="title">Stack Overflow</title>
```

2024-08-27 08:26 UTC, ahus1 commented on themes/src/main/resources/theme/keycloak.v2/login/login.ftl
> +                                                <title id="title">Paypal</title>
```suggestion
                                                <title id="title">PayPal</title>
```

2024-09-10 11:02 UTC, ahus1 approved these changes
Thank you, the brand names now look good!

2024-09-10 11:05 UTC, merged