changed the size of the welcome logo
keycloak/keycloak pull request #32493
Opened 2024-08-29 14:07 UTC by edewit

fixes: #32492
Signed-off-by: Erik Jan de Wit <erikjan.dewit@gmail.com>

2024-08-29 18:16 UTC, ssilvert approved these changes, later dismissed

2024-09-02 09:47 UTC, jonkoops requested changes

2024-09-02 09:47 UTC, jonkoops commented on themes/src/main/resources/theme/keycloak/welcome/index.ftl
> +            <img src="${resourcesPath}/logo.svg" alt="${productName} Logo" style="height: 63px;width: 300px;display: block;margin: 0 auto;">
Can we not use in-line styles for this? There is already a stylesheet present for the welcome page that can be used.

2024-09-03 12:37 UTC, jonkoops commented on themes/src/main/resources/theme/keycloak.v2/login/theme.properties
> -kcLoginContent=pf-v5-c-login__container
This change seems unrelated, why is it here?

2024-09-03 13:11 UTC, jonkoops approved these changes
LGTM

2024-09-03 18:03 UTC, ssilvert approved these changes

2024-09-03 18:03 UTC, merged