Propagate admin action lifespan to ResetCredentialDialog (#32547)
keycloak/keycloak pull request #32671
Opened 2024-09-05 00:07 UTC by thomasdarimont

Fixes #32547

2024-09-05 11:47 UTC, edewit requested changes
So the original code is not good. I think we don't need the default value on the controller when we already have it in the form

2024-09-13 08:07 UTC, thomasdarimont commented
@edewit Thanks for taking a look! Can you be a bit more specific about what I should change?

2024-09-13 08:46 UTC, thomasdarimont commented
I removed the lifespan constant value from the code.

2024-09-13 09:28 UTC, edewit commented on js/apps/admin-ui/src/user/user-credentials/ResetCredentialDialog.tsx
> +      lifespan: realm?.actionTokenGeneratedByAdminLifespan,
You either set the lifespan default value here

2024-09-13 09:29 UTC, edewit commented on js/apps/admin-ui/src/user/user-credentials/LifespanField.tsx
> +        defaultValue: lifespan,
or you set it here on the controller one of these can be removed

2024-09-13 09:30 UTC, edewit requested changes
only one of these is needed, setting both with the same value is overkill

2024-09-13 13:14 UTC, thomasdarimont commented
Thanks for the hints @edewit. I tried to follow your suggestions in the latest commit.

2024-09-16 09:45 UTC, edewit approved these changes

2024-09-16 09:45 UTC, merged