added username field like suggested in issue comment
keycloak/keycloak pull request #32866
Opened 2024-09-12 14:41 UTC by edewit

related: #32522
Signed-off-by: Erik Jan de Wit <erikjan.dewit@gmail.com>

2024-09-12 14:44 UTC, jonkoops requested changes

2024-09-12 17:22 UTC, edewit commented on themes/src/main/resources/theme/keycloak.v2/login/template.ftl
> +            <i class="fa-sync-alt fas" aria-hidden="true"></i>
This one is still supported in PF5

2024-09-12 18:59 UTC, edewit commented on themes/src/main/resources/theme/keycloak.v2/login/template.ftl
> +        <button tabindex="-1" class="${properties.kcFormPasswordVisibilityButtonClass} kc-login-tooltip" type="button" aria-label="${msg('restartLoginTooltip')}"
this is a very black humor joke, you want people that are blind to be able to "show password"?

2024-09-13 08:54 UTC, ahus1 commented on themes/src/main/resources/theme/keycloak.v2/login/template.ftl
> +        <button tabindex="-1" class="${properties.kcFormPasswordVisibilityButtonClass} kc-login-tooltip" type="button" aria-label="${msg('restartLoginTooltip')}"
Like comment in the other issue: IMHO it is important to make it navigatable by keyboard for those you can't use a mouse but can see just fine.

On another note: Looking at the label, this is not about showing the password, but about restarting the login. This control is IMHO important for everyone.

2024-09-13 08:56 UTC, ahus1 commented
Thank you for the visual design, IMHO it is a lot clearer now what's happening here.

2024-09-13 11:29 UTC, jonkoops submitted a review, later dismissed

2024-09-16 11:11 UTC, agagancarczyk approved these changes

2024-09-18 11:00 UTC, ahus1 approved these changes
Approving based in my manual test and @agagancarczyk's review. Thank you for this enhancement!

2024-09-18 11:03 UTC, merged