Add cache for IdentityProviderStorageProvider.getForLogin
keycloak/keycloak pull request #32918
Opened 2024-09-13 17:35 UTC by sguilhen

Closes #32573

2024-09-16 11:48 UTC, vramik approved these changes
LGTM, thanks @sguilhen

2024-09-18 07:05 UTC, mhajas approved these changes
Approving based on the review from @vramik

2024-09-18 07:05 UTC, merged

2026-04-10 00:45 UTC, mfeuerstein reviewed
## PR Review — approved

Reviewed 4 files. 0 high-severity issues found. Verdict: approved.

### `model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/idp/InfinispanIdentityProviderStorageProvider.java` (low)

- Reviewed model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/idp/InfinispanIdentityProviderStorageProvider.java — looks good

### `server-spi/src/main/java/org/keycloak/models/IdentityProviderStorageProvider.java` (low)

- Reviewed server-spi/src/main/java/org/keycloak/models/IdentityProviderStorageProvider.java — looks good

### `testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/cache/OrganizationCacheTest.java` (low)

- Reviewed testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/cache/OrganizationCacheTest.java — looks good

### `services/src/main/java/org/keycloak/organization/forms/login/freemarker/model/OrganizationAwareIdentityProviderBean.java` (low)

- Reviewed services/src/main/java/org/keycloak/organization/forms/login/freemarker/model/OrganizationAwareIdentityProviderBean.java — looks good

2026-07-31 00:15 UTC, zach-source requested changes
Cache inconsistency in getForLogin — see inline.

<!-- review-fingerprint:b63ddfba2924fde6 -->