Identity Providers Pagination in account console (#21261)
keycloak/keycloak pull request #32913
Opened 2024-09-13 15:00 UTC by linathedog

Closes #21261 
Added Pagination for Identity Providers in the Linked Accounts Page in account console.

2024-09-13 15:38 UTC, jonkoops requested changes

2024-09-13 15:38 UTC, jonkoops commented on js/apps/account-ui/src/account-security/LinkedAccounts.tsx
> +  const [paramsUnlinked, setParamsUnlinked] = useState<Record<string, any>>({
Let's avoid using `any` as a type, please create a new type for the parameters that matches this data structure.

2024-09-13 15:38 UTC, jonkoops commented on js/apps/account-ui/src/api/methods.ts
> +  requestParams: Record<string, any>,
Same here, let's avoid using `any` if the parameters can be defined explicitly in their own type.

2024-09-17 09:43 UTC, edewit commented
closed in favour of #33019
Andreas used your commit, but added the review comments of @jonkoops couldn't update this PR for some reason

2024-09-17 09:43 UTC, closed without merging