fix: Update fr community translation for account/ui
keycloak/keycloak pull request #33075
Opened 2024-09-18 20:40 UTC by mrleblanc101

2024-09-20 15:24 UTC, ahus1 requested changes, later dismissed
Thank you for this PR. Please add a sign-off to your commit as outlined in the CONTRIBUTING.md in this repository. Thanks!

2024-09-20 15:33 UTC, mrleblanc101 commented
@ahus1 Sorry, I used Github.dev (VS Code for the web), will add the sign-off

2024-09-20 15:52 UTC, ahus1 commented
@DimitriDR - can you please review this PR? Maybe @mrleblanc101 wants to join you for the [translations via Weblate](https://github.com/keycloak/keycloak/discussions/9270#discussioncomment-10523162).

2024-09-21 18:56 UTC, DimitriDR requested changes
Very clean, I just added few minor suggestions :)

2024-09-21 18:56 UTC, DimitriDR commented on js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_fr.properties
> +rolesScopeConsentText=Roles utilisateurs
Rôles avec un « ô » 😃

2024-09-21 18:56 UTC, DimitriDR commented on js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_fr.properties
> +emptyUserOrganizationsInstructions=Vous n'avez pas encore joint d'organisation.
Rejoint ? Peut-être ? C'est souvent le verbe utilisé dans ces cas ? J'ai rarement vu juste "joint"

2024-09-21 18:56 UTC, DimitriDR commented on js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_fr.properties
> +refresh=Rafraichir
Rafraîchir avec le petit accent qui va bien

2024-09-23 04:59 UTC, mrleblanc101 commented on js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_fr.properties
> +refresh=Rafraichir
Ah oui, je vais l'ajouté pour «refreshPage=Rafraichir la page» aussi

2024-09-23 04:59 UTC, mrleblanc101 commented on js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_fr.properties
> +emptyUserOrganizationsInstructions=Vous n'avez pas encore joint d'organisation.
Mon québécois qui resort

2024-09-23 04:59 UTC, mrleblanc101 commented on js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_fr.properties
> +rolesScopeConsentText=Roles utilisateurs
Parfait

2024-09-23 06:08 UTC, ahus1 commented
@DimitriDR  / @mrleblanc101 - please keep the discussion in this repository in English except where quoting a translation. This helps other contributors to follow the discussion. 

I asked for another review from @DimitriDR before this can be merged.

2024-09-23 12:27 UTC, DimitriDR approved these changes
Approved!

2024-09-23 12:33 UTC, jonkoops approved these changes
Thanks all!

2024-09-23 12:34 UTC, merged