Add Health Checks for Multi-Site guide to Docs
keycloak/keycloak pull request #33112
Opened 2024-09-19 16:54 UTC by kami619

2024-09-24 13:03 UTC, ahus1 requested changes, later dismissed
Thank you for this guide. IMHO it would be sufficient to assume only Kubernetes in this deployment and not OpenShift, which would make it more approachable to the wider community. 

So I'd ask you to change "oc" to "kubectl" and replace "OpenShift" with "Kubernetes" except where we reference the prerequisite of the previous installation explicitly.

2024-09-25 01:26 UTC, kami619 commented
@ahus1 I have addressed your previous review comments, please take another look if that's enough.

2024-09-25 12:47 UTC, ahus1 reviewed
Thank you for he docs. I updated the formatting a bit and shortened some of the headings and sentences for better readability. Please let me know if that breaks any meaning. 

I'll ask Andy to a review of the guide before this will then be merged.

2024-09-25 12:48 UTC, ahus1 commented
@andymunro - we would like to include this guide in KC26. Can you please review this new text? Thanks!

2024-10-01 15:17 UTC, ahus1 commented
@andymunro - gentle reminder. Please review when you have the time. We'd like to merge it tomorrow the latest to finish this task which is in our sprint. If you don't have the time, We could merge this version and postpone a review until the RHBK release. Thanks!

2024-10-01 18:15 UTC, andymunro commented
Thanks for the reminder, @ahus1.  I will check it now.

2024-10-01 18:19 UTC, andymunro commented on docs/guides/high-availability/health-checks-multi-site.adoc
> +Kubernetes resources and Healthcheck endpoints available to verify a multi-site setup of {project_name}.
```suggestion
This page provides an overview of URLs,
Kubernetes resources, and Healthcheck endpoints available to verify a multi-site setup of {project_name}.
```

2024-10-01 18:19 UTC, andymunro commented on docs/guides/high-availability/health-checks-multi-site.adoc
> +A proactive monitoring strategy aims to detect and alert on issues before they impact users. It is the key for a highly resilient and highly available {project_name} application.
```suggestion
A proactive monitoring strategy aims to detect and alert about issues before they impact users. This strategy is the key for a highly resilient and highly available {project_name} application.
```

2024-10-01 18:20 UTC, andymunro commented on docs/guides/high-availability/health-checks-multi-site.adoc
> +Health checks across various architectural components (like application health, load balancing, caching, and overall system status) are critical for:
```suggestion
Health checks across various architectural components (such as application health, load balancing, caching, and overall system status) are critical for:
```

2024-10-01 18:22 UTC, andymunro commented on docs/guides/high-availability/health-checks-multi-site.adoc
> +Ensuring High Availability:: By verifying that all sites and the load balancer are operational, it helps guarantee that the system can handle requests even if one site goes down.
```suggestion
Ensuring High Availability:: Verifying that all sites and the load balancer are operational is a key to ensure that  a system can handle requests even if one site goes down.
```

2024-10-01 18:24 UTC, andymunro commented on docs/guides/high-availability/health-checks-multi-site.adoc
> +. Install https://jqlang.github.io/jq/download/[jq] if it is not available on your OS already.
```suggestion
. Install https://jqlang.github.io/jq/download/[jq] if it is not available on your operating system already.
```

2024-10-01 18:25 UTC, andymunro commented on docs/guides/high-availability/health-checks-multi-site.adoc
> +Maintaining Performance:: Checking the health and distribution of the {jdgserver_name} cache ensures that {project_name} can maintain optimal performance by efficiently handling sessions and other te
```suggestion
Maintaining performance:: Checking the health and distribution of the {jdgserver_name} cache ensures that {project_name} can maintain optimal performance by efficiently handling sessions and other temporary data.
```

2024-10-01 18:25 UTC, andymunro commented on docs/guides/high-availability/health-checks-multi-site.adoc
> +Operational Resilience:: By continuously monitoring the health of both {project_name} and its dependencies within the Kubernetes environment, the system can quickly identify and possibly auto-remedia
```suggestion
Operational resilience:: By continuously monitoring the health of both {project_name} and its dependencies within the Kubernetes environment, the system can quickly identify and possibly auto-remediate issues, reducing downtime.
```

2024-10-01 18:25 UTC, andymunro commented on docs/guides/high-availability/health-checks-multi-site.adoc
> +== Specific Health Checks
```suggestion
== Specific health checks
```

2024-10-01 18:27 UTC, andymunro commented on docs/guides/high-availability/health-checks-multi-site.adoc
> +=== {project_name} Load Balancer and Sites
```suggestion
=== {project_name} load balancer and sites
```

2024-10-01 18:27 UTC, andymunro commented on docs/guides/high-availability/health-checks-multi-site.adoc
> +This command returns the health status of the {project_name} application's connection to its configured database, thus confirming the reliability of db connections.
```suggestion
This command returns the health status of the {project_name} application's connection to its configured database, thus confirming the reliability of database connections.
```

2024-10-01 18:29 UTC, andymunro commented on docs/guides/high-availability/health-checks-multi-site.adoc
> +In a Kubernetes setup, the sub-status `health/ready` is checked periodically to make the Pod as ready.
```suggestion
This command is available only on the management port and not from the external URL.
In a Kubernetes setup, the sub-status `health/ready` is checked periodically to make the Pod as ready.
```

2024-10-01 18:30 UTC, andymunro commented on docs/guides/high-availability/health-checks-multi-site.adoc
> +These commands will return the running status of the Site A and Site B of the {project_name} in a cross-site setup (be it Active/Passive or Active/Active).
```suggestion
These commands will return the running status of the Site A and Site B of the {project_name} in a cross-site setup (whether it is Active/Passive or Active/Active).
```

2024-10-01 18:31 UTC, andymunro commented on docs/guides/high-availability/health-checks-multi-site.adoc
> +as {jdgserver_name} is often used for distributed caching and session clustering in {project_name} deployments.
```suggestion
=== {jdgserver_name} Cache health
Check the health of the default cache manager and individual caches in an external {jdgserver_name} cluster.
This check is vital for {project_name} performance and reliability,
as {jdgserver_name} is often used for distributed caching and session clustering in {project_name} deployments.
```

2024-10-01 18:32 UTC, andymunro commented on docs/guides/high-availability/health-checks-multi-site.adoc
> +This command returns the overall health of the {jdgserver_name} cache manager, this is useful as the Admin user doesn't need to provide user credentials to get the health status.
```suggestion
This command returns the overall health of the {jdgserver_name} cache manager, which is useful as the Admin user does not need to provide user credentials to get the health status.
```

2024-10-01 18:34 UTC, andymunro commented on docs/guides/high-availability/health-checks-multi-site.adoc
> +Whereas for these health checks, Admin user needs to provide the {jdgserver_name} user credentials as part of the request to peek into the overall health of the external {jdgserver_name} cluster cach
```suggestion
In contrast to the preceding health checks, the following health checks require the Admin user to provide the {jdgserver_name} user credentials as part of the request to peek into the overall health of the external {jdgserver_name} cluster caches.
```

2024-10-01 18:35 UTC, andymunro commented on docs/guides/high-availability/health-checks-multi-site.adoc
> +Optionally you can run the above command without the `jq` filter to see the full details.
```suggestion
You can also choose to run the above command without the `jq` filter to see the full details.
```

2024-10-01 18:36 UTC, andymunro commented on docs/guides/high-availability/health-checks-multi-site.adoc
> +=== {jdgserver_name} Cluster Distribution
```suggestion
=== {jdgserver_name} Cluster distribution
```

2024-10-01 18:37 UTC, andymunro commented on docs/guides/high-availability/health-checks-multi-site.adoc
> +=== Overall, {jdgserver_name} System Health
```suggestion
=== Overall, {jdgserver_name} system health
```

2024-10-01 18:37 UTC, andymunro commented on docs/guides/high-availability/health-checks-multi-site.adoc
> +Uses `kubectl` CLI tool to query the health status of {jdgserver_name} clusters and the {project_name} service in the specified namespace. This comprehensive check ensures that all components of the
```suggestion
Uses the `kubectl` CLI tool to query the health status of {jdgserver_name} clusters and the {project_name} service in the specified namespace. This comprehensive check ensures that all components of the {project_name} deployment are operational and correctly configured within the Kubernetes environment.
```

2024-10-01 18:37 UTC, andymunro commented on docs/guides/high-availability/health-checks-multi-site.adoc
> +=== {project_name} Readiness in Kubernetes
```suggestion
=== {project_name} readiness in Kubernetes
```

2024-10-01 18:41 UTC, andymunro requested changes
Thanks, @kami619. Well written.  Just a few suggestions.

2024-10-01 19:30 UTC, kami619 commented
@ahus1 I think this should be all set now, after @andymunro's review and feedback.

2024-10-02 08:36 UTC, ahus1 submitted a review, later dismissed

2024-10-02 08:38 UTC, ahus1 approved these changes

2024-10-02 08:43 UTC, merged