Operator's guides: Clarify that options need to be baked in the custo…
keycloak/keycloak pull request #33241
Opened 2024-09-24 12:59 UTC by Pepo48

…m image to make the feature available

Closes: #32717

2024-09-24 15:10 UTC, shawkins commented
@Pepo48 @vmuzikar I think we also discussed having the server throw an exception instead of emitting a warning in the case where build time options seem to change. Was something like that going to be included here?

2024-09-24 15:42 UTC, Pepo48 commented
@shawkins you're correct and I already have it prepared under different branch (I might've misunderstood it should be part of this PR). Let me do a cherrypick.

2024-09-26 12:00 UTC, shawkins reviewed
Generally looks good, just some thoughts about the exception.

2024-09-27 11:42 UTC, vmuzikar commented on docs/guides/operator/customizing-keycloak.adoc
> +Options like `health-enabled` and `metrics-enabled` are good examples of why this is sometimes necessary. By default, these options are disabled. To make these endpoints available, you can either use
I'd be even more explicit here. I'd state that when using optimized custom image, `health-enabled` and `metrics-enabled` need to be explicitly set in the Containerfile. And maybe make it a warning even.

2024-09-27 12:07 UTC, vmuzikar commented
We also need some mention in the upgrading guide.

2024-09-30 14:22 UTC, vmuzikar requested changes

2024-09-30 14:22 UTC, vmuzikar commented on docs/documentation/upgrading/topics/changes/changes-26_0_0.adoc
> += Stricter startup behavior for CLI build-time options
```suggestion
= Stricter startup behavior for build-time options
```

2024-09-30 14:27 UTC, vmuzikar approved these changes
@Pepo48 Thank you for the changes, LGTM!

2024-09-30 16:08 UTC, shawkins approved these changes
LGTM, thanks @Pepo48

2024-09-30 17:28 UTC, merged