Release notes update with the core-clients contributions
keycloak/keycloak pull request #33279
Opened 2024-09-25 16:15 UTC by mposolda

closes #32990

2024-09-25 18:43 UTC, andymunro commented on docs/documentation/release_notes/topics/26_0_0.adoc
> +There is also new key provider `ecdh-generated` for generating realm keys and the support for ECDH algorithms is added into Java KeyStore provider.
```suggestion
Also, a new key provider, `ecdh-generated`, is available to generate realm keys and support for ECDH algorithms is added into the Java KeyStore provider.
```

2024-09-25 18:46 UTC, andymunro commented on docs/documentation/release_notes/topics/26_0_0.adoc
> +Until the previous release, it was supported only for the `authorization_code` grant type. There is also support for the DPoP token type on the UserInfo endpoint.
```suggestion
The DPoP (OAuth 2.0 Demonstrating Proof-of-Possession) preview feature has improvements. The DPoP is now supported for all grant types.
With previous releases, this feature was supported only for the `authorization_code` grant type. Support also exists for the DPoP token type on the UserInfo endpoint.
```

2024-09-25 19:05 UTC, andymunro commented on docs/documentation/release_notes/topics/26_0_0.adoc
> +for client policies.
```suggestion
The condition based on the client-attribute was added into Client Policies. You can use condition to specify for the clients
with the specified client attribute having specified value. It is possible to use either an AND or OR condition when evaluating this condition as mentioned in the documentation
for client policies.
```

2024-09-25 19:07 UTC, andymunro commented on docs/documentation/release_notes/topics/26_0_0.adoc
> +happen in the https://github.com/keycloak/kc-sig-fapi[Keycloak OAuth SIG]. Anyone from the Keycloak community is welcome to join.
```suggestion
The OpenID for Verifiable Credential Issuance (OID4VCI) is still an experimental feature in {project_name}, but it was greatly improved in this release. You will find significant development and discussions
in the https://github.com/keycloak/kc-sig-fapi[Keycloak OAuth SIG]. Anyone from the Keycloak community is welcome to join.
```

2024-09-25 19:08 UTC, andymunro requested changes
Looks good, @mposolda

2024-09-26 04:52 UTC, mposolda commented
@andymunro Thanks!

2024-09-26 04:53 UTC, merged