Fix duplicated screenshots in the Fine grain admin permissions sectio…
keycloak/keycloak pull request #33314
Opened 2024-09-26 20:40 UTC by sguilhen

…n of the Server Admin Guide

Closes #31083

2024-09-26 21:00 UTC, andymunro commented on docs/documentation/server_admin/topics/admin-console-permissions/fine-grain.adoc
>  rules in JavaScript.  For this simple example, we're going to create a `User Policy`.
```suggestion
On this page, look for the `Create client policy` button, which you can use to define many policies.  You can define a policy that is associated with a role or a group or even define
rules in JavaScript.  For this simple example, we are going to create a `User Policy`.
```

2024-09-26 21:00 UTC, andymunro commented on docs/documentation/server_admin/topics/admin-console-permissions/fine-grain.adoc
> +There's one more thing we have to do.  Go to `Users`, select the `sales-admin` user, then go to the `Role Mappings` tab and assign the `query-clients` role to the user.
```suggestion
There is one more thing we have to do.  Go to `Users`, select the `sales-admin` user, then go to the `Role Mappings` tab and assign the `query-clients` role to the user.
```

2024-09-26 21:01 UTC, andymunro requested changes
Thanks for fixing this lost issue, @sguilhen

2024-09-26 21:31 UTC, andymunro approved these changes
LGTM, @sguilhen

2024-09-27 02:08 UTC, sguilhen commented
Please squash the commits when merging.

2024-09-27 07:03 UTC, ahus1 approved these changes
Approving as of @andymunro's review

2024-09-27 07:04 UTC, merged