Update organizations documentation in the server admin guide
keycloak/keycloak pull request #33311
Opened 2024-09-26 17:46 UTC by sguilhen

Closes #33199

2024-09-26 19:53 UTC, andymunro commented on docs/documentation/server_admin/topics/organizations/authenticating-members.adoc
> +* Seamlessly authenticate users through an identity provider associated with an organization if the email domain matches the domain set to the identity provider.
```suggestion
* Matching an email domain to an organization.
* Deciding if the authentication flow should continue or not if an account already exists for the username provided
* Deciding how the user should be authenticated depending on how the domains and the identity providers are configured to an organization
* Seamlessly authenticating users through an identity provider associated with an organization if the email domain matches the domain set to the identity provider
```

2024-09-26 19:54 UTC, andymunro commented on docs/documentation/server_admin/topics/organizations/authenticating-members.adoc
> +* Seamlessly authenticate users through an identity provider associated with an organization if the email domain matches the domain set to the identity provider.
No need for semi-colons or periods if a bullet is a partilal sentence

2024-09-26 19:58 UTC, andymunro commented on docs/documentation/server_admin/topics/organizations/managing-identity-providers.adoc
> +
```suggestion
You can edit any of the organization-related settings of a linked identity provider at any time. 
```

2024-09-26 19:58 UTC, andymunro commented on docs/documentation/server_admin/topics/organizations/managing-identity-providers.adoc
> +
The procedure already has the steps.

2024-09-26 20:01 UTC, andymunro commented on docs/documentation/server_admin/topics/organizations/managing-identity-providers.adoc
> +. Click *Save*
```suggestion
. In the organization settings, go to the *Identity providers* tab.
. Locate the *identity provider* in the list.
+
You can use the search option for this step.
. Click the action button (three dots) at the end of the line.
. Click *Edit*.
. Make the necessary changes.
. Click *Save*.
```

2024-09-26 20:02 UTC, andymunro commented on docs/documentation/server_admin/topics/organizations/managing-identity-providers.adoc
> +. Click *Save*
We include a period for a complete sentence and use "click" not "click on"

2024-09-26 20:04 UTC, andymunro commented on docs/documentation/server_admin/topics/organizations/managing-identity-providers.adoc
> +
```suggestion
When an identity provider is unlinked from an organization, it remains available as a realm-level provider that is no longer ssociated with an organization. If you want to delete the unlinked provider, use the *Identity Providers* section in the menu.

.Procedure

```

2024-09-26 20:42 UTC, andymunro commented on docs/documentation/server_admin/topics/organizations/managing-identity-providers.adoc
> +
```suggestion
.  In the organization settings, go to the *Identity providers* tab.
. Locate the *identity provider* in the list.
.+
You can use the search capabilities for this step.
. Click the action button (three dots) at the end of the line.
. Click *Unlink provider*.

```

2024-09-26 20:51 UTC, andymunro commented on docs/documentation/server_admin/topics/organizations/managing-identity-providers.adoc
> +. In the organization settings, go to the *Identity providers* tab.
```suggestion
. In the menu, click *Organizations* and go to the *Identity providers* tab.
```

2024-09-26 20:52 UTC, andymunro commented on docs/documentation/server_admin/topics/organizations/managing-identity-providers.adoc
> +.  In the organization settings, go to the *Identity providers* tab.
```suggestion
. In the menu, click *Organizations* and go to the *Identity providers* tab.
```

2024-09-26 20:53 UTC, andymunro commented on docs/documentation/server_admin/topics/organizations/managing-organization.adoc
> +An alias for this organization, used to reference the organization internally. The alias is unique within a realm and must be URL-friendly, so characters not usually allowed in URLs won't be allowed
```suggestion
An alias for this organization, used to reference the organization internally. The alias is unique within a realm and must be URL-friendly, so characters not usually allowed in URLs will not be allowed in the alias. If not set, {project_name} will attempt to use the name as the alias. If the name is not URL-friendly, you will get an error and will be asked to specify an alias. Once defined, the alias cannot be changed afterwards.
```

2024-09-26 20:54 UTC, andymunro commented on docs/documentation/server_admin/topics/organizations/managing-organization.adoc
> +To delete an organization, you can click the *Delete* action for the corresponding organization in the listing page or when editing an organization.
```suggestion
To delete an organization, click the *Delete* action for the corresponding organization in the listing page or when editing an organization.
```

2024-09-26 20:54 UTC, andymunro commented on docs/documentation/server_admin/topics/organizations/managing-organization.adoc
> +To delete an organization, you can click the *Delete* action for the corresponding organization in the listing page or when editing an organization.
Generally, a "you can do x" can be replace with "do x" which is more concise.

2024-09-26 20:56 UTC, andymunro commented on docs/documentation/server_admin/topics/organizations/mapping-organization-claims.adoc
> +By default the organization attributes are not included in the organization claim. To include the attributes in the claim, edit the mapper and switch the *Add organization attributes* setting to on.
```suggestion
By default, the organization attributes are not included in the organization claim. To include the attributes in the claim, edit the mapper and enable *Add organization attributes*.
```

2024-09-26 20:56 UTC, andymunro requested changes
Looks good. A few more changes.

2024-09-26 21:27 UTC, andymunro commented on docs/documentation/server_admin/topics/organizations/managing-identity-providers.adoc
> +.+
```suggestion
+
```

2024-09-26 21:27 UTC, andymunro commented on docs/documentation/server_admin/topics/organizations/managing-identity-providers.adoc
> +.+
I added the period by mistake.

2024-09-26 21:30 UTC, andymunro commented on docs/documentation/server_admin/topics/organizations/mapping-organization-claims.adoc
> +about the organizations the user is a member of to tokens.
```suggestion
authorization requests to the server. When authenticating in the context of an organization, clients can request the `organization` scope to map information
about the organizations where the user is a member.
```

2024-09-26 21:30 UTC, andymunro requested changes
A couple of final changes, @sguilhen

2024-09-26 21:40 UTC, andymunro approved these changes
APPROVED, @sguilhen!

2024-09-27 02:08 UTC, sguilhen commented
Please squash the commits when merging.

2024-09-27 07:07 UTC, ahus1 commented
@martin-kanis / @vramik - can someone from the team review the contents of the docs that they match the implementation? It is great to have Andrew reviewing it from a technical writing perspective, but for these changes another review from the team would be great. Thanks!

cc: @sguilhen

2024-09-27 11:37 UTC, martin-kanis approved these changes
Thanks @sguilhen, LGTM.

2024-09-27 13:47 UTC, sguilhen commented
@ahus1 When you find some time to merge, the reviews are in place!

2024-09-27 14:27 UTC, ahus1 approved these changes
Approving based on previous reviews

2024-09-27 14:27 UTC, merged