Fixes release notes section on new login theme, keycloak.v2
keycloak/keycloak pull request #33359
Opened 2024-09-27 18:27 UTC by ssilvert

Fixes #33351

2024-09-28 10:11 UTC, jonkoops requested changes

2024-09-28 10:11 UTC, jonkoops commented on docs/documentation/release_notes/topics/26_0_0.adoc
> +For all new realms, `keycloak.v2` will be the default login theme.
This is wrong, the theme will be the default in every realm unless a specific login theme is configured.

2024-09-30 11:40 UTC, jonkoops approved these changes, later dismissed
LGTM!

2024-09-30 12:50 UTC, miquelsi approved these changes

2024-09-30 12:58 UTC, jonkoops approved these changes

2024-09-30 12:58 UTC, agagancarczyk approved these changes

2024-09-30 13:38 UTC, stianst approved these changes

2024-09-30 13:38 UTC, merged