initial version of the password strength policy
keycloak/keycloak pull request #33396
Opened 2024-09-30 13:46 UTC by edewit

fixes: #23573

2024-10-11 07:48 UTC, stianst requested changes
As previously mentioned I'm not convinced we should have a password strength meter, and have concerns that the heuristics to decide if a password is strong enough will be inaccurate initially, or that it will not be updated as new recommendations are published around password recommendations.

Please provide some details on what the heuristics are here, as well as any research that has been done in terms of best practices around passwords and if this matches current best practices.

2024-10-11 12:48 UTC, edewit commented
We can't grantee that things get updated when they should, tbh we can't grantee that for anything

It uses [zxcvbn](https://zxcvbn-ts.github.io/zxcvbn/) and it gives us a score from 0 - 4 on how good the password is. To quote the website:
> It recognizes and analyzes over 40 thousand common passwords using pattern matching and conservative estimation and filters out common first names, last names, popular words from Wikipedia and common words in many cultures, and recognizes common patterns like dates, repetitions (e.g. 'aaa'), sequences (e.g. 'abcd'), keyboard smashes (e.g. 'qwertyuiop'), and l33t speak.

And there are more options that we could add, like extra dictionaries and user input.

So for instance a password `P@$$word` would satisfy policies around upper lower case and special characters but it wouldn't have a high score ( it would be 0 ) on the password strength indicator

As stated in the issue it's something that OWASP recommends https://github.com/OWASP/ASVS/blob/master/4.0/en/0x11-V2-Authentication.md#v21-password-security-requirements

2024-12-12 11:06 UTC, edewit commented
@stianst now uses the vendor package to install the dependencies

2025-06-05 11:38 UTC, closed without merging

2025-06-11 09:35 UTC, AndreVirtimo commented
@ssilvert why do you close this PR without discussion? I think this is a valuable feature.

2025-06-12 10:00 UTC, viktorspacil commented
@ssilvert any explanation why this OR was closed?

2025-06-12 18:18 UTC, ssilvert commented
This was closed because @edewit is leaving the project, @stianst has reservations about it, and nobody from @keycloak/core-maintainers has responded.

We can revisit this, but we need a larger discussion about it and someone new to champion the implementation.