fix: deprecate various aspects of SslRequired
keycloak/keycloak pull request #33538
Opened 2024-10-03 19:43 UTC by shawkins

closes: #31914

2024-10-08 14:52 UTC, vmuzikar requested changes
@shawkins Thanks for the PR.

I'd suggest this should be worded differently. We're not deprecating `EXTERNAL` and `ALL`. We're deprecating the whole SSL Required option. And this should be also reflected in the UI.

2024-10-08 15:59 UTC, vmuzikar commented
@shawkins I think the proper new way of deprecating things is to wrap it in a new Profile Feature that will be enabled by default but deprecated right away. Disabling it will effectively act as `NONE` but will also make the field disappear from exports etc.

2024-10-08 17:51 UTC, shawkins commented
> @shawkins I think the proper new way of deprecating things is to wrap it in a new Profile Feature that will be enabled by default but deprecated right away. Disabling it will effectively act as `NONE` but will also make the field disappear from exports etc.

To clarify, you are saying that there should be a narrow feature, called sslrequired v1 for example, that is initially the default. Then you want it transitioned to deprecated in a later major release - at that point it time it will be breaking change for anyone relying on SslRequired, and they will have to use features=sslrequired:v1 to keep the existing functionality. 

Or do you want to introduce v1 and v2 of some appropriately named feature such that initially v1 is deprecated, but the default, and v2 is disabled by default, such that users must initially opt into the new functionality - which keeps the rollout as non-breaking and eligble for a minor release.

2024-10-09 13:00 UTC, shawkins commented
> Does it make sense?

No, because that is new behavior. A deprecated feature is not enabled by default. That currently only happens if it's marked as DEFAULT, or PREVIEW (and we're in the preview profile). So do you also want to introduce a new Feature Type?

2024-10-09 13:22 UTC, shawkins commented
> Yeah, seems like that's what needs to be done. For the new release scheme where we're not allowed to make breaking changes so often, we definitely need to be able to deprecate features that are still enabled by default at the same time.

Ok, so here's what that roughly looks like:

- We add sslrequired:v1 as deprecated, but enabled. On every start of the server users will be warned that they are using a a deprecated feature. Their remediation is to add features-disabled=sslrequired... They may need to be warned about toggling this feature due to have it will affect realm import / exports and the sslrequired field (omitting the field will make it default to external in older releases or those still supporting sslrequired, even if the new desired behavior is none).
- We remove sslrequired:v1 in a later release. Users will then have to remove the usage of features-disabled=sslrequired

2024-10-09 14:13 UTC, vmuzikar commented
@shawkins That's sounds right to me.

2024-10-09 14:21 UTC, shawkins commented
> @shawkins That's sounds right to me.

My qualm with that approach is that users who stay on the happy path will have to take two actions to deal with warnings / feature removal - when only a small subset of users should actually be relying on SslRequired.

It seems better to do this in a way that will be more transparent to most users.

2024-10-09 14:23 UTC, stianst requested changes
See my comments on the issue

2024-10-10 11:41 UTC, shawkins commented
> See my comments on the issue

I saw your comment, but you may need to further clarify your suggested approach. Are you saying that you don't want any deprecation of SslRequired (either the field or individual values) at the realm level until security profiles are implemented?

2024-10-10 11:54 UTC, stianst commented
Yes, my thoughts are that we introduce a server security profile of sorts as a first step. We could make that an opt-in feature initially perhaps, and when enabled it would disable the whole SslRequire stuff. Then we can deprecate SslRequired and just get rid of it completely in the future.

2025-05-14 18:49 UTC, closed without merging