Improve error handling in JS adapter's updateToken
keycloak/keycloak pull request #34113
Opened 2024-10-19 12:49 UTC by adropofliquid

Closes #13852

2024-10-19 16:41 UTC, jonkoops requested changes

2024-10-19 16:41 UTC, jonkoops commented on js/libs/keycloak-js/lib/keycloak.js
> +                                    p.setError("Failed to refresh the token. Status: " + req.status);
Let's not add any status codes or network details here, that is what the network inspector for the devtools are for.
```suggestion
                                    p.setError("Failed to refresh token: An unexpected HTTP error occurred while attempting to refresh the token.");
```

2024-10-20 11:08 UTC, jonkoops commented
PR looks good to me like this. @adropofliquid could you squash your commits and [sign off](https://github.com/keycloak/keycloak/pull/34113/checks?check_run_id=31778712387) on your commit?

2024-10-23 07:14 UTC, adropofliquid commented
@jonkoops  just confirming I have completed what you asked. Anything else?

2024-10-23 09:59 UTC, jonkoops approved these changes
LGTM

2024-10-23 10:23 UTC, adropofliquid commented
I'm also seeing that this branch is out of date and won't auto-merge:

This branch is out-of-date with the base branch
Merge the latest changes from main into this branch.

2024-10-23 10:36 UTC, jonkoops commented
It will, there is no need to rebase unless there are conflicts.

2024-10-23 11:07 UTC, merged