Expose membership type in the Admin UI for organization members and users
keycloak/keycloak pull request #34235
Opened 2024-10-23 08:58 UTC by agagancarczyk

Closes https://github.com/keycloak/keycloak/issues/33498

I have this implemented in Organizations > Organization details > Members and Users > User details > Organizations

To test this, you'll need to have managed and unmanaged users in the organization.

2024-10-23 17:07 UTC, pedroigor approved these changes, later dismissed
Nice. LGTM!

2024-10-24 06:06 UTC, edewit requested changes

2024-10-24 06:06 UTC, edewit commented on js/apps/admin-ui/src/user/Organizations.tsx
> +            });
Is it not slow to query all users of an organisation?

2024-10-24 06:06 UTC, edewit commented on js/apps/admin-ui/src/user/Organizations.tsx
> +          return { ...org, membershipType };
this seems duplicated, you could maybe put it into a separated file

2024-10-28 20:28 UTC, pedroigor commented
@agagancarczyk Updated the member listing page in organizations to use the new filter. However, there are two issues I'm not sure how to proceed:

* If you provide a search string and select a membership type, the search string is lost and query will only filter by the selected membership type
* If the selected membership type filter does not return any result, you will see the "empty page" asking the administrator to add members to the organization

2024-10-29 13:23 UTC, sguilhen reviewed
@pedroigor I haven't really reviewed the UI side of things, just the backend, and in general it looks good to me. Only thing I really don't like is those default impls in the provider delegating to each other

2024-10-29 13:23 UTC, sguilhen commented on server-spi/src/main/java/org/keycloak/organization/OrganizationProvider.java
> +    }
Not sure I like these defaults - even though they are overridden, the default impls are calling each other leading possibly to a stack overflow?

2024-10-30 11:25 UTC, edewit commented on js/apps/admin-ui/src/organizations/Members.tsx
> +      }));
This is not needed, we just need to translate this key

2024-10-30 13:08 UTC, pedroigor commented on server-spi/src/main/java/org/keycloak/organization/OrganizationProvider.java
> +    }
True, done.

2024-10-30 13:08 UTC, pedroigor commented on server-spi/src/main/java/org/keycloak/organization/OrganizationProvider.java
> +    default Stream<UserModel> getMembersStream(OrganizationModel organization, String search, Boolean exact, Integer first, Integer max) {
True, done.

2024-10-30 15:05 UTC, sguilhen approved these changes

2024-11-08 07:52 UTC, edewit submitted a review, later dismissed

2024-11-12 10:27 UTC, pedroigor approved these changes

2024-11-12 11:53 UTC, edewit approved these changes

2024-11-12 12:13 UTC, merged