only enable the when there are idp available
keycloak/keycloak pull request #34247
Opened 2024-10-23 11:49 UTC by edewit

fixes: #33743
Signed-off-by: Erik Jan de Wit <erikjan.dewit@gmail.com>

2024-10-23 12:00 UTC, ahus1 requested changes
Thank you for this PR. Maybe we wait for the core-iam team to have an opinion on the performance. Thanks!

2025-01-31 11:34 UTC, pedroigor commented on services/src/main/java/org/keycloak/services/resources/account/AccountConsole.java
> +        map.put("isLinkedAccountsEnabled", session.identityProviders().getAllStream(searchOptions, 0, null).findAny().isPresent());
Yeah, we only need to check if there is at least one. The PR was updated.

2025-01-31 11:35 UTC, pedroigor submitted a review, later dismissed
@ahus1 Can you please re-review?

2025-01-31 16:27 UTC, sguilhen approved these changes

2025-01-31 19:30 UTC, ahus1 approved these changes, later dismissed
Approving. Sorry if my question in the initial review caused a month-long delay on this change.

2025-01-31 20:28 UTC, ahus1 commented
@edewit - the tests fail (both in the UI and the base test suite), please have a look.

2025-02-04 11:57 UTC, pedroigor approved these changes, later dismissed

2025-02-04 12:41 UTC, ssilvert submitted a review, later dismissed

2025-02-04 13:35 UTC, pedroigor approved these changes

2025-02-04 13:35 UTC, pedroigor commented
Fixed the failure in base tests.

2025-02-04 19:20 UTC, ssilvert approved these changes

2025-02-04 19:20 UTC, merged