remove copied FileUpload component
keycloak/keycloak pull request #34290
Opened 2024-10-24 10:16 UTC by edewit

fixes: #32420
Signed-off-by: Erik Jan de Wit <erikjan.dewit@gmail.com>

2024-10-24 10:25 UTC, jonkoops requested changes

2024-10-24 10:25 UTC, jonkoops commented on js/apps/admin-ui/src/components/json-file-upload/patternfly/FileUpload.tsx
> -import { fromEvent } from "file-selector";
This dependency is now orphaned and can be removed.

2024-10-24 10:25 UTC, jonkoops commented on js/apps/admin-ui/src/components/json-file-upload/FileUploadForm.tsx
>  import { DropEvent } from "react-dropzone";
Looking at the PatternFly code it seems this type [already exists](https://github.com/patternfly/patternfly-react/blob/4ce551e98b489e4227306ed882e58d896e2fe810/packages/react-core/src/helpers/typeUtils.ts#L18) there, so we can likely remove the direct dependency on `react-dropzone` and use that type instead.

2024-10-24 16:07 UTC, jonkoops approved these changes

2024-10-25 13:27 UTC, ssilvert approved these changes

2024-10-25 13:27 UTC, merged