Update brute force docs
keycloak/keycloak pull request #34531
Opened 2024-10-31 02:11 UTC by gilvansfilho

Fixes #27378

2024-10-31 02:13 UTC, gilvansfilho commented
@andymunro @rmartinc @douglaspalmer 
Please, could you review?

2024-11-01 00:30 UTC, douglaspalmer approved these changes
This is great, thank you. I'm approving as is but would it be possible to add images for each Brute Force Mode?

2024-11-01 20:09 UTC, gilvansfilho commented
@douglaspalmer done...

2024-11-01 22:01 UTC, andymunro commented on docs/documentation/server_admin/topics/threat/brute-force.adoc
> +At the fifth failed attempt the account is disabled for `30` seconds. After reaching the next multiple of `Max Login Failures`, in this case `10`, the time increases from `30` to `60` seconds.
```suggestion
At the fifth failed attempt, the account is disabled for `30` seconds. After reaching the next multiple of `Max Login Failures`, in this case `10`, the time increases from `30` to `60` seconds. 
```

2024-11-01 22:01 UTC, andymunro commented on docs/documentation/server_admin/topics/threat/brute-force.adoc
> +At the fifth failed attempt the account is disabled for `30` seconds. Each new failure increases wait time according value specified at `wait increment`.
```suggestion
At the fifth failed attempt, the account is disabled for `30` seconds. Each new failure increases wait time according value specified at `wait increment`.
```

2024-11-01 22:02 UTC, andymunro requested changes
Looks good. Just a few changes to suggest, @gilvansfilho

2024-11-04 08:05 UTC, rmartinc approved these changes
The changes LGTM. Thanks @gilvansfilho! 
Perform the modifications requested by @andymunro and we are good with it.

2024-11-04 09:40 UTC, ahus1 approved these changes
Approving as of @rmartinc's review

2024-11-04 09:41 UTC, merged

2024-11-04 12:11 UTC, gilvansfilho commented
@andymunro @rmartinc PR was merged before I made the requested changes. Should I submit a new PR?

2024-11-04 12:24 UTC, ahus1 commented
@gilvansfilho - I've accepted @andymunro's review comments (which were about adding commas) via the GitHub UI which I could do as a maintainer. You now see 3 commits associated with this PR. Those were then squashed when I merged them.

So the work should be completed, and no additional tasks are necessary.