Fix credential_type in update/remove credential email template
keycloak/keycloak pull request #34685
Opened 2024-11-06 09:20 UTC by hauptrolle

This fixes the broken update/remove credential email templates, as mentioned in #32685 

Background:
The `event.details` are transformed by the `ThemeBean` to a list of a key/value pairs, so a direct access with `event.details.credential_type` is not possible. We have to lookup the key `credential_type ` in the list, and display its value.

2024-11-06 16:47 UTC, rmartinc requested changes
Thanks a lot for the PR @hauptrolle!

We need some tests for the issue. I also think that adding a method in the `EventBean` to get the detail by name is better. WDYT?

I have created a follow-up commit in this branch: https://github.com/rmartinc/keycloak/tree/refs/heads/pr-34685. Can you please cherry-pick the commit https://github.com/keycloak/keycloak/commit/643e0be87fb7449dbe01cc4310d174b341991d70 on top of this branch? You can change anything you like in it, I just wanted to speed up the PR.

Thanks again!

2024-11-07 08:20 UTC, hauptrolle commented
LGTM. I cherry-pick your commit 👍

2024-11-07 09:49 UTC, rmartinc approved these changes
Thanks @hauptrolle! Approved! I'm going to ask a @keycloak/maintainers to re-run the failed test (again the download issue).

2024-11-07 09:52 UTC, ahus1 approved these changes
Approving based on previous reviews.

2024-11-07 10:13 UTC, merged