fix: mark slf4j as not optional for the operator (#32652)
keycloak/keycloak pull request #34699
Opened 2024-11-06 13:51 UTC by vmuzikar

closes: #32651

2024-11-06 13:53 UTC, mabartos approved these changes

2024-11-06 13:53 UTC, miquelsi approved these changes

2024-11-06 13:54 UTC, vmuzikar commented
jFTR – reusing the old issue

2024-11-06 14:06 UTC, stianst requested changes
We shouldn't merge this as it's just a temporary fix for downstream, and has nothing to do with Keycloak community releases

2024-11-07 07:10 UTC, stianst approved these changes

2024-11-07 07:10 UTC, merged