Don't show global event listeners in the admin UI
keycloak/keycloak pull request #34746
Opened 2024-11-07 13:56 UTC by ahus1

Closes #34602

2024-11-11 07:50 UTC, ahus1 commented
This is my first contribution to the React code of Keycloak. It would be great if someone from the @keycloak/ui could have an extra careful look at this.

Thanks!

cc: @ssilvert

2024-11-11 09:56 UTC, edewit requested changes
Some small line savers, otherwise :+1:

2024-11-11 09:56 UTC, edewit commented on js/apps/admin-ui/src/realm-settings/event-config/EventListenersForm.tsx
> +    },
```suggestion
    () =>
      fetchAdminUI<EventListenerRepresentation[]>(
        adminClient,
        "ui-ext/available-event-listeners",
      ),
```

2024-11-11 09:56 UTC, edewit commented on js/apps/admin-ui/src/realm-settings/event-config/EventListenersForm.tsx
> +    },
```suggestion
      setEventListeners,
```

2024-11-11 09:56 UTC, edewit commented on js/apps/admin-ui/src/realm-settings/event-config/EventListenersForm.tsx
> +        }))}
```suggestion
        options={eventListeners!.map((value) => value.id)}
```

2024-11-11 10:29 UTC, jonkoops commented on js/apps/admin-ui/src/realm-settings/event-config/EventListenersForm.tsx
> +        }))}
You can probably also omit the `!`

2024-11-11 10:52 UTC, ahus1 commented
@edewit - thank you for the review! I've apply your suggested changes. Ready for another round of review.

2024-11-18 06:44 UTC, edewit approved these changes

2024-11-18 16:08 UTC, mhajas approved these changes
Thank you @ahus1 and @edewit!

2024-11-18 16:09 UTC, merged