Upgrade to ISPN 15.0.11.Final
keycloak/keycloak pull request #34932
Opened 2024-11-13 14:45 UTC by pruivo

Closes #34931

2024-11-13 16:03 UTC, ahus1 requested changes
Thank you for the PR. I suppose one more version needs to be updated in-line with the Infinispan version. Please have a look. Thanks!

2024-11-13 16:14 UTC, pruivo commented on pom.xml
>          <protostream.version>5.0.8.Final</protostream.version>
Infinispan 15.0.10.Final already uses ProtoStream 5.0.10.Final. I've removed this property.

2024-11-15 11:04 UTC, ahus1 approved these changes
Thank you for the change!

2024-11-15 11:04 UTC, ahus1 commented
fyi: @ryanemerson

2024-11-15 12:38 UTC, merged