fix: providing stable ordering for deprecation metadata
keycloak/keycloak pull request #34999
Opened 2024-11-15 15:19 UTC by shawkins

closes: #34858

2024-11-19 16:40 UTC, shawkins commented on quarkus/config-api/src/main/java/org/keycloak/config/DeprecatedMetadata.java
> +        this.newOptionsKeys = newOptionsKeys == null ? Collections.emptySet() : newOptionsKeys.stream().sorted().toList();
To keep the original intent of immutablity, it doesn't save us anything to use a treeset.

2024-11-19 18:16 UTC, mabartos commented on quarkus/config-api/src/main/java/org/keycloak/config/DeprecatedMetadata.java
> +        this.newOptionsKeys = newOptionsKeys == null ? Collections.emptySet() : newOptionsKeys.stream().sorted().toList();
ok

2024-11-19 18:17 UTC, mabartos approved these changes

2024-11-19 18:17 UTC, mabartos requested changes
@shawkins It would be good to add some simple test.

2024-11-20 14:31 UTC, mabartos approved these changes

2024-11-20 14:32 UTC, mabartos requested changes
Oops, the test xD 

I see that you added changes regarding the PicocliTest package, so I can close this PR: https://github.com/keycloak/keycloak/pull/35146

2024-11-20 15:16 UTC, shawkins commented
> Oops, the test xD
> 
> I see that you added changes regarding the PicocliTest package, so I can close this PR: #35146

Right, I had just noticed that as well. A test has been added to this pr as well - it was missing from the last commit.

2024-11-21 11:12 UTC, vmuzikar approved these changes
LGTM, thanks for the fix!

2024-11-21 11:46 UTC, mabartos approved these changes
LGTM as well

2024-11-21 11:47 UTC, merged