Upgrade to Quarkus 3.15.2
keycloak/keycloak pull request #35078
Opened 2024-11-19 08:26 UTC by mabartos

Closes #35077
Closes #33469

2024-11-19 09:08 UTC, vmuzikar requested changes
@mabartos Thank you for the PR. I believe we need to wait with the merge for RHBQ 3.15.2 to be released. @drichtarik Is that correct?

2024-11-19 09:10 UTC, vmuzikar submitted a review, later dismissed
Never mind, this is targeting `main`. LGTM.

2024-11-21 10:58 UTC, mabartos commented
The `AccountRestServiceCorsTest` test fails due to this change in Quarkus 3.15.2 -https://github.com/quarkusio/quarkus/pull/43440. Need to verify how to proceed.

2024-12-18 15:01 UTC, shawkins approved these changes, later dismissed
LGTM, thanks @mabartos

2024-12-18 15:50 UTC, mabartos commented
@keycloak/core Could you please take a look at it as it touches `services` module? Thanks!

2024-12-19 07:14 UTC, mabartos commented
@pedroigor May I ask you for a review? Thanks!

2024-12-19 14:09 UTC, mabartos commented
@shawkins @pedroigor Fixed small Javadoc typo and rebased.

2025-01-06 16:04 UTC, mabartos commented
Rebased to have it properly checked.

2025-01-06 22:46 UTC, shawkins approved these changes
Looks good, thanks @mabartos

2025-01-07 10:37 UTC, vmuzikar approved these changes
Nice work, LGTM, thanks!

2025-01-07 10:37 UTC, merged