Remove upgrading client libraries from the server documentation
keycloak/keycloak pull request #35101
Opened 2024-11-19 13:14 UTC by mposolda

closes #34949

2024-11-19 13:15 UTC, jonkoops approved these changes, later dismissed

2024-11-19 15:15 UTC, jonkoops approved these changes, later dismissed

2024-11-20 14:07 UTC, andymunro commented on docs/documentation/upgrading/topics/intro.adoc
> +the {project_name} server. For more information, see the link:{upgradingclientlibs_link}[{upgradingclientlibs_name}].
```suggestion
. Upgrade the {project_name} Client Libraries (Admin client, Authorization client, Policy enforcer). These are released independently of the {project_name} server
and could be typically updated independently of the {project_name} server as the last released version of the client libraries should be compatible with the last released version of
the {project_name} server. For more information, see the link:{upgradingclientlibs_link}[{upgradingclientlibs_name}].
```

2024-11-20 14:08 UTC, andymunro requested changes
@mposolda Looks good with a few changes.

2024-11-20 15:14 UTC, merged