First completed chapters
keycloak/keycloak pull request #35579
Opened 2024-12-03 20:04 UTC by ssilvert

This is a draft PR for the new UI Customization document.  The main goals for this PR were to establish the new document so it would build, create the outline, and complete a few chapters.

2025-01-07 15:45 UTC, andymunro commented on docs/documentation/ui_customization/topics/localization.adoc
> +* To enable internationalization for a realm, you must enable internationalization in the `Realm settings` section of the admin console. See the {adminguide_link}[{adminguide_name}].
"You must" sounds controlling.  "You" alone means the same thing.

2025-01-07 15:58 UTC, andymunro commented on docs/documentation/ui_customization/topics/localization.adoc
> +For a language to be available to users the realms `login`, `account` and `email`, the theme has to support the language, so you need to add your language for those theme types.
```suggestion
. Add this file to the `locales` property in `<THEME TYPE>/theme.properties`.
+
For a language to be available to users and the `login`, `account` and `email` realms, the theme has to support the language, so you need to add your language for those theme types.
```

2025-01-07 15:59 UTC, andymunro commented on docs/documentation/ui_customization/topics/localization.adoc
> +For example, to add Norwegian translations to the `mytheme` theme create the file `themes/mytheme/login/messages/messages_no.properties` with the
```suggestion
For example, to add Norwegian translations to the `mytheme` theme, create the file `themes/mytheme/login/messages/messages_no.properties` with the
```

2025-01-07 16:01 UTC, andymunro commented on docs/documentation/ui_customization/topics/localization.adoc
> +. Add the same for the `account` and `email` theme types. To do this create `themes/mytheme/account/messages/messages_no.properties` and
```suggestion
. Make the same changes to the `account` and `email` theme types. To make these changes, create `themes/mytheme/account/messages/messages_no.properties` and
```

2025-01-07 16:03 UTC, andymunro commented on docs/documentation/ui_customization/topics/localization.adoc
> +`themes/mytheme/email/messages/messages_no.properties`. Leaving these files empty will result in the English messages being used.
```suggestion
`themes/mytheme/email/messages/messages_no.properties`. If you leave these files empty, English messages are used.
```

2025-01-07 16:05 UTC, andymunro commented on docs/documentation/ui_customization/topics/localization.adoc
> +`themes/mytheme/account/messages/messages_en.properties` and `themes/mytheme/login/messages/messages_en.properties`:
```suggestion
. Add a translation for the language selector by adding a message to the English translation. Add the following to
`themes/mytheme/account/messages/messages_en.properties` and `themes/mytheme/login/messages/messages_en.properties`:
```

2025-01-07 16:32 UTC, andymunro commented on docs/documentation/ui_customization/topics/localization.adoc
> +Previous versions of Keycloak supported specifying the encoding in the first line with a comment like `# encoding: UTF-8`, which is no longer supported.
```suggestion
Previous versions of {project_name} supported specifying the encoding in the first line with a comment such as `# encoding: UTF-8`, which is no longer supported.
```

2025-01-07 18:44 UTC, andymunro commented on docs/documentation/ui_customization/topics/localization.adoc
> +
```suggestion
You also have the option to declare translations that take effect for an entire realm.  You specify key/value pairs in the realm settings.  Any key specified in this way overrides the key/value pairs deployed with a theme.

```

2025-01-07 18:45 UTC, andymunro commented on docs/documentation/ui_customization/topics/localization.adoc
> +. Select your realm
```suggestion
. Log into the Admin Console.
. Select your realm.
```

2025-01-07 18:46 UTC, andymunro commented on docs/documentation/ui_customization/topics/localization.adoc
> +. Create a key/value pair from the modal dialog
```suggestion
. Select a language from the option list.
. Click *Add translation*.
. Create a key/value pair from the modal dialog.
```

2025-01-07 18:47 UTC, andymunro commented on docs/documentation/ui_customization/topics/localization.adoc
> +Note that there is another subtab called *Effective message bundles*.  This subtab provides a tool to query key/value pairs for a combination of theme, language, and theme type.  You can use this too
```suggestion
Notice another subtab called *Effective message bundles*.  This subtab provides a tool to query key/value pairs for a combination of theme, language, and theme type.  You can use this tool to test and make sure your realm overrides took effect.
```

2025-01-07 18:55 UTC, andymunro commented on docs/documentation/ui_customization/topics/preface.adoc
> +So:
```suggestion
In some sample listings, the intended content for one line exceeds the available page width. These lines have been broken up. A '\' at the end of a line means that a break is introduced to fit in the page, with the following lines indented.  For example:
```

2025-01-07 18:55 UTC, andymunro commented on docs/documentation/ui_customization/topics/preface.adoc
> +Is really:
```suggestion
The actual content is as follows:
```

2025-01-07 18:57 UTC, andymunro commented on docs/documentation/ui_customization/topics/themes-react.adoc
> +There are two packages:
```suggestion
The Admin Console and Account Console are based on React.
To fully customize these consoles, you can use the React based npm packages.
Two packages exist:
```

2025-01-07 18:58 UTC, andymunro commented on docs/documentation/ui_customization/topics/themes-react.adoc
> +
```suggestion
* `@keycloak/keycloak-admin-ui`: This is the base theme for the Admin Console.
* `@keycloak/keycloak-account-ui`: This is the base theme for the Account Console.
```

2025-01-07 18:59 UTC, andymunro commented on docs/documentation/ui_customization/topics/themes-react.adoc
> +To use these pages you'll need to add KeycloakProvider in your component hierarchy to setup what client, realm and url to use.
```suggestion
To use these pages, you add KeycloakProvider in your component hierarchy to choose the client, realm and url to use.
```

2025-01-07 19:26 UTC, andymunro commented on docs/documentation/ui_customization/topics/themes-react.adoc
> +Or have a look at the [quick start](https://github.com/keycloak/keycloak-quickstarts/tree/main/extension/extend-account-console-node) to see how to use them.
```suggestion
Instead you can conisider [quick start](https://github.com/keycloak/keycloak-quickstarts/tree/main/extension/extend-account-console-node) to see how to use them.
```

2025-01-07 19:29 UTC, andymunro commented on docs/documentation/ui_customization/topics/themes-react.adoc
> +Or have a look at the [quick start](https://github.com/keycloak/keycloak-quickstarts/tree/main/extension/extend-account-console-node) to see how to use them.
```suggestion
Instead , you can conisider the (quick start)(https://github.com/keycloak/keycloak-quickstarts/tree/main/extension/extend-account-console-node) to see how to use them.
```

2025-01-07 19:45 UTC, andymunro requested changes
Looks good, @ssilvert.  A few suggestions for you.

2025-01-07 22:22 UTC, andymunro commented
@ssilvert I also recommend we name it the User Interface Customization Guide.

2025-01-10 20:04 UTC, ssilvert commented on docs/documentation/ui_customization/topics/localization.adoc
> +For a language to be available to users the realms `login`, `account` and `email`, the theme has to support the language, so you need to add your language for those theme types.
> Rewording is my best guess.

Those are not realms.  They are theme types.  But it's a little confusing because as I recall, they are just referred to as `themes`.

This language comes from the current documentation, so I think it's safe to leave it alone for now.

2025-02-28 15:14 UTC, andymunro commented on docs/documentation/ui_customization/topics/admin-console.adoc
> +== Customizing the Administration Console
```suggestion
== Customizing the Admin Console
```

2025-02-28 15:14 UTC, andymunro commented on docs/documentation/ui_customization/topics/admin-console.adoc
> +== Customizing the Administration Console
In general we are calling it the Admin Console.  Maybe we should change it on the Welcome page.

2025-02-28 15:16 UTC, andymunro commented on docs/documentation/ui_customization/topics/avatars.adoc
> +Both the admin and account consoles allow use of an avatar to personalize the user experience.  {project_name} supports avatars using the oidc standard `picture` claim.
```suggestion
The Admin Console and Account Console both allow use of an avatar to personalize the user experience.  {project_name} supports avatars using the OpenID Connect standard `picture` claim.
```

2025-02-28 15:20 UTC, andymunro commented on docs/documentation/ui_customization/topics/avatars.adoc
> +This `picture` claim should have a URI as its value.  The URI should point to the avatar meant to be displayed in the masthead section of the admin console or account console.
```suggestion
The value for `picture` claim should be a URI that points to the avatar to be displayed in the masthead section of the console.
```

2025-02-28 15:23 UTC, andymunro commented on docs/documentation/ui_customization/topics/avatars.adoc
> +The simplest way to allow users to specify the avatar URI is to add a `picture` attribute in User profile.  Just go to the admin console and navigate to the `Realm Settings -> User profile` tab.
```suggestion
A simple way to allow users to specify the avatar URI is to add a `picture` attribute in the User profile. In the Admin Console, click *Realm Settings* and the *User profile* tab.
```

2025-02-28 15:24 UTC, andymunro commented on docs/documentation/ui_customization/topics/avatars.adoc
> +image::images/picture-attribute-general-settings.png[caption="",title="User profile picture attribute setup in admin console"]
.User profile picture attribute setup

2025-02-28 15:26 UTC, andymunro commented on docs/documentation/ui_customization/topics/avatars.adoc
> +image::images/account-console-with-avatar.png[caption="",title="Avatar shown in account console"]
```suggestion
.Avatar in Account Console
image::images/account-console-with-avatar.png[caption="",title="Avatar in Account Console"]
```

2025-02-28 15:28 UTC, andymunro commented on docs/documentation/ui_customization/topics/avatars.adoc
> +CAUTION: Allowing users to specify their own URI could lead to security concerns.  An avatar can contain malware so it is important that images come from a trusted source.  One way to accomplish this
```suggestion
CAUTION: Allowing users to specify their own URI could lead to security concerns.  An avatar can contain malware so ensure that images come from a trusted source.  One practical approach is to make sure that the `picture` has a regular expression validator to restrict the URI.
```

2025-02-28 15:30 UTC, andymunro commented on docs/documentation/ui_customization/topics/introduction.adoc
> +{project_name} includes user interfaces (UIs) for login, Admin Console, and Account Console.  It also has a "welcome" screen used for initial setup.
```suggestion
{project_name} includes user interfaces (UIs) for the login page, Admin Console, and Account Console.  It also has a "welcome" screen used for the first administrator of the Admin Console.
```

2025-02-28 15:32 UTC, andymunro commented on docs/documentation/ui_customization/topics/localization.adoc
> +* To enable internationalization for a realm, you enable internationalization in the `Realm settings` section of the Admin Console. See {adminguide_link}#enabling-internationalization[{Enabling inter
```suggestion
* You enable internationalization for a realm in the `Realm settings` section of the Admin Console. See {adminguide_link}#enabling-internationalization[{Enabling internationalization}].
```

2025-02-28 15:34 UTC, andymunro commented on docs/documentation/ui_customization/topics/localization.adoc
> +Text in the templates is loaded from message bundles. A theme that extends another theme inherits all messages from the parent's message bundle. You can
```suggestion
Text in the templates is loaded from message bundles. When a theme extends another theme, the child theme inherits all messages from the parent's message bundle. You can
```

2025-02-28 15:35 UTC, andymunro commented on docs/documentation/ui_customization/topics/localization.adoc
> +Texts of these message bundles can be overwritten by realm-specific values. The realm-specific values are manageable by the UI and API.
```suggestion
Texts of these message bundles can be overwritten by realm-specific values, which are manageable by the UI and API.
```

2025-02-28 15:41 UTC, andymunro commented on docs/documentation/ui_customization/topics/localization.adoc
> +For a language to be available to users the realms `login`, `account` and `email`, the theme has to support the language, so you need to add your language for those theme types.
Okay, not sure what it should be, but it seems there is missing punctuation somewhere.  
I was thinking, it should be "For a language to be available to users COMMA..." but I not sure.

2025-02-28 15:42 UTC, andymunro commented on docs/documentation/ui_customization/topics/localization.adoc
> +If you omit a translation for messages, they will use English.
```suggestion
If you omit a translation for messages, those messages appear in English.
```

2025-02-28 15:49 UTC, andymunro commented on docs/documentation/ui_customization/topics/localization.adoc
> +* See <<_locale_selector,Locale Selector>> for details on how the current locale is selected.
```suggestion
* For details on how the current locale is selected, see <<_locale_selector,Locale Selector>>.
```

2025-02-28 15:50 UTC, andymunro commented on docs/documentation/ui_customization/topics/localization.adoc
> +CAUTION: Using realm overrides is not the typical way to do localization in {project_name}.  Consider carefully if you want every theme in your realm to use these key/value pairs.
```suggestion
CAUTION: Using realm overrides is not the recommended wayt to achieve localization in {project_name}.  Consider carefully if you want every theme in your realm to use key/value pairs.
```

2025-02-28 15:52 UTC, andymunro commented on docs/documentation/ui_customization/topics/quick-theme.adoc
> +"Quick Theme" is an experimental feature which allows you to quickly and easily create themes with new logos and colors.  Often, this is all you need to facilitate branding and skinning for account c
```suggestion
"Quick Theme" is an experimental feature which allows you to quickly and easily create themes with new logos and colors.  Often, this is all you need to facilitate branding and skinning for the Account Console, Admin Console, and login page.
```

2025-02-28 15:53 UTC, andymunro commented on docs/documentation/ui_customization/topics/quick-theme.adoc
> +As shown below, when you change a color or image, you get a preview of how your colors and images will look together for various elements of your theme.  The color options correspond to https://www.p
```suggestion
In the following example, when you change a color or image, you get a preview of how your colors and images appear together for various elements of your theme.  The color options correspond to https://www.patternfly.org/developer-resources/global-css-variables/[PatternFly global CSS variables], which are used by {project_name} to create themes.
```

2025-02-28 15:54 UTC, andymunro commented on docs/documentation/ui_customization/topics/quick-theme.adoc
> +image::images/color-chooser.png[alt="Color chooser with dropper", title="Color chooser with the dropper tool"]
```suggestion
.Color chooser with the dropper tool
image::images/color-chooser.png[alt="Color chooser with dropper", title="Color chooser with the dropper tool"]
```

2025-02-28 15:54 UTC, andymunro commented on docs/documentation/ui_customization/topics/quick-theme.adoc
> +image::images/easy-theme-find-color.png[alt="Find a color with the dropper tool", title="Find a color with the dropper tool"]
```suggestion
.Find a color with the dropper tool
image::images/easy-theme-find-color.png[alt="Find a color with the dropper tool", title="Find a color with the dropper tool"]
```

2025-02-28 15:55 UTC, andymunro commented on docs/documentation/ui_customization/topics/quick-theme.adoc
> +When your new theme is complete, press the `Download theme JAR` button to download a theme JAR that is ready for deployment.
```suggestion
When your new theme is complete, click `Download theme JAR` button to download a theme JAR that is ready for deployment.
```

2025-02-28 15:57 UTC, andymunro commented on docs/documentation/ui_customization/topics/quick-theme.adoc
> +CAUTION: For security reasons, never deploy a theme unless you are confident of its origin.  An image can be a possible attack vector.  This is why {project_name} does not allow automatic deployment
```suggestion
CAUTION: For security reasons, never deploy a theme unless you are confident of its origin.  An image can be a possible attack vector.  This issue is reason that {project_name} does not allow automatic deployment of a theme through the Admin Console.  Only those administrators with file access to your production server should deploy a theme in production.
```

2025-02-28 15:58 UTC, andymunro commented on docs/documentation/ui_customization/topics/quick-theme.adoc
> +Another deployment option is to "unjar" the archive into the `themes/` directory.  This allows you to explore the theme and make manual changes.
```suggestion
Another deployment option is to "unjar" the archive into the `themes/` directory.  With this option, you explore the theme and make manual changes.
```

2025-02-28 16:00 UTC, andymunro commented on docs/documentation/ui_customization/topics/quick-theme.adoc
> +Your theme will include the images and colors you provided.  These will then be used throughout the `account console`, `admin console`, and `login`.
```suggestion
Your theme includes the images and colors you provided. They appear throughout the Account Console, Admin Console, and login pages.
```

2025-02-28 16:02 UTC, andymunro commented on docs/documentation/ui_customization/topics/themes-react.adoc
> +To use these pages, you add KeycloakProvider in your component hierarchy to choose the client, realm and url to use.
```suggestion
To use these pages, you add KeycloakProvider in your component hierarchy to choose the client, realm, and URL that you need.
```

2025-02-28 16:04 UTC, andymunro commented on docs/documentation/ui_customization/topics/welcome-theme.adoc
> +The welcome theme is simply the web page that is served when you request the default page from the {project_name} server.  For instance, if your server is deployed on your local machine at port 8080
```suggestion
The welcome theme is the web page that is served when you request the default page from the {project_name} server.  For instance, if your server is deployed on your local machine at port 8080, http://localhost:8080 serves the welcome theme.
```

2025-02-28 16:05 UTC, andymunro commented on docs/documentation/ui_customization/topics/welcome-theme.adoc
> +By default, the welcome theme is only used to create the initial, temporary admin user.  Once that user is created, any time users navigate to the welcome theme, they will be redirected to the admin
```suggestion
By default, the welcome theme is only used to create the initial temporary admin user.  Once that user is created, whenever users navigate to the welcome theme, they are redirected to the Admin Console.  However, this behavior can be changed and the welcome theme can be completely customized or replaced.
```

2025-02-28 16:06 UTC, andymunro commented on docs/documentation/ui_customization/topics/welcome-theme.adoc
> +Since the welcome theme is not associated with a realm, it can not be selected in the admin console like other themes.
```suggestion
Since the welcome theme is not associated with a realm, it cannot be selected in the admin console like other themes.
```

2025-02-28 16:06 UTC, andymunro commented on docs/documentation/ui_customization/topics/welcome-theme.adoc
> +To change the welcome theme, simply create and deploy a new welcome theme as discussed in <<_creating-a-theme,Creating a theme>>.  Then, start the keycloak server using the `spi-theme-welcom-theme` o
```suggestion
To change the welcome theme, create and deploy a new welcome theme as described in <<_creating-a-theme,Creating a theme>>.  Then, start the {project_name} server using the `spi-theme-welcom-theme` option.
```

2025-02-28 16:22 UTC, andymunro requested changes
Looks good, @ssilvert.  I have a few suggestions.  Also general comments:

- Always use Admin Console and Account Console (using initial capital letters)
- Enclose anything you click or see on the screen in *asterisks*
- Add a figure title above images and make that title match the tag you already using following the image pathname
- Use present tense whenever possible because it means the same as sounds more active.

2025-02-28 16:24 UTC, andymunro commented on docs/documentation/ui_customization/topics/localization.adoc
> +For a language to be available to users the realms `login`, `account` and `email`, the theme has to support the language, so you need to add your language for those theme types.
```suggestion
For a language to be available to users in a realm, the login, account, and email theme types must support the language, so you need to add your language for those theme types.
```

2025-02-28 16:24 UTC, andymunro commented on docs/documentation/ui_customization/topics/localization.adoc
> +For a language to be available to users the realms `login`, `account` and `email`, the theme has to support the language, so you need to add your language for those theme types.
On more attempt.

2025-02-28 18:11 UTC, edewit commented on docs/documentation/ui_customization/images/color-chooser.png
This is dependend on the implementation of the browser on firefox it look like :
![image](https://github.com/user-attachments/assets/7e7aad50-5678-42b2-bba9-d88b42664446)

2025-03-12 11:51 UTC, edewit commented on docs/documentation/ui_customization/topics/quick-theme.adoc
> +== Customizing with Quick Theme
Could we publish this also as a guide?

2025-03-12 19:49 UTC, ssilvert commented on docs/documentation/ui_customization/topics/quick-theme.adoc
> +== Customizing with Quick Theme
@edewit What do you mean?  I envision this document getting published with the rest of our docs.

Is your question specific to Quick Theme?

2025-04-28 05:16 UTC, edewit commented on docs/documentation/ui_customization/topics/creating-your-own-console.adoc
> +Now everything is set up and we are ready to start hacking.  To see a customized version of the Account Console, point your browser to http://localhost:8080/realms/master/account.
Why do you have two spaces after a period, everywhere?

2025-04-28 05:20 UTC, edewit approved these changes, later dismissed

2025-04-28 20:50 UTC, ssilvert commented on docs/documentation/ui_customization/topics/creating-your-own-console.adoc
> +Now everything is set up and we are ready to start hacking.  To see a customized version of the Account Console, point your browser to http://localhost:8080/realms/master/account.
@edewit That's the way I was taught back in high school typing class. 

I asked an LLM about it.  Here is the response:
`Using two spaces between sentences is a matter of style, not correctness. Historically, typewriters used monospaced fonts, and two spaces helped visually separate sentences. Modern style guides, like APA, Chicago, and MLA, recommend one space for clarity and consistency in digital typography, as proportional fonts handle spacing better. However, some fields (e.g., legal writing) or personal preferences may still use two spaces. Always follow the specific guidelines for your context.`

I probably need to break that habit.

2025-07-22 12:05 UTC, ssilvert commented
Out of date

2025-07-22 12:05 UTC, closed without merging