Implement a conditional authenticator to check if a sub-flow was executed or not previously in the process
keycloak/keycloak pull request #35668
Opened 2024-12-05 15:36 UTC by rmartinc

Closes #35231

The PR adds a new conditional authenticator to check if a previous sub-flow has been executed (or not executed) successfully during the process. This allows to specify more complex flows and execute steps in case a previous one was executed or missed.

I checked and I don't see a list of authenticators in the docs so I added nothing in the server development doc.

Is a note needed in the release notes? To what version? Do we want to add this in 26.0 or just 26.1? (Adding the condition is not a big change but maybe it's better to document this in the release.)

2024-12-06 08:53 UTC, mposolda commented
@rmartinc Thanks, Looks nice in my opinion!

Agree that documentation can be nice. Maybe something to the "Server admin guide" - https://www.keycloak.org/docs/latest/server_admin/index.html#configuring-authentication_server_administration_guide (I can imagine example with multiple 2FA in the 1st conditional subflow and then 2nd subflow with `ResetOTP` authenticator , which means the guy without any 2FA is required to configure OTP during authentication. But different example is completely OK as well, so whatever you prefer) 

Also release notes could be nice as well.

IMO this is for Keycloak 26.1 . It is not bugfix, but rather new thing, so no need to backport this. People just need to wait for new capabilities IMO.

2024-12-11 11:43 UTC, mposolda approved these changes, later dismissed
@rmartinc Thanks!

There is another conflict in release notes for 26.1.0.

@andymunro Do you please have a chance to review this one please?

2024-12-11 11:49 UTC, rmartinc commented
Rebased! Notes are always a hot area! :smile:

2024-12-11 14:20 UTC, andymunro commented on docs/documentation/release_notes/topics/26_1_0.adoc
> +The `Condition - sub-flow executed` is a new conditional authenticator in {project_name}. The condition checks if a previous sub-flow was executed (or not executed) successfully during the authentica
```suggestion
The `Condition - sub-flow executed` is a new conditional authenticator in {project_name}. The condition checks if a previous sub-flow was executed (or not executed) successfully during the authentication flow execution. For more details, see link:{adminguide_link}#conditions-in-conditional-flows[Conditions in conditional flows].
```

2024-12-11 14:22 UTC, andymunro commented on docs/documentation/server_admin/topics/authentication/conditions.adoc
> +The condition checks if a previous sub-flow was successfully executed (or not executed) in the authentication process. This way, the flow can trigger some other steps depending on a previous sub-flow
```suggestion
The condition checks if a previous sub-flow was successfully executed (or not executed) in the authentication process. Therefore, the flow can trigger other steps based on a previous sub-flow termination. Configuration fields:
```

2024-12-11 14:25 UTC, andymunro commented on docs/documentation/server_admin/topics/authentication/conditions.adoc
> +image:images/2fa-example1.png[2FA all alternative]
```suggestion
,2FA all alternative
image:images/2fa-example1.png[2FA all alternative]
```

2024-12-11 14:30 UTC, andymunro commented on docs/documentation/server_admin/topics/authentication/conditions.adoc
> +image:images/2fa-example2.png[2FA all alternative and deny access]
```suggestion
.2FA all alternative and deny access
image:images/2fa-example2.png[2FA all alternative and deny access]
```

2024-12-11 14:30 UTC, andymunro commented on docs/documentation/server_admin/topics/authentication/conditions.adoc
> +image:images/2fa-example2-config.png[Configuration for the sub-flow executed]
```suggestion
.Configuration for the sub-flow executed
image:images/2fa-example2-config.png[Configuration for the sub-flow executed]
```

2024-12-11 14:31 UTC, andymunro commented on docs/documentation/server_admin/topics/authentication/conditions.adoc
> +image:images/2fa-example3.png[2FA all alternative with OTP default]
```suggestion
.2FA all alternative with OTP default
image:images/2fa-example3.png[2FA all alternative with OTP default]
```

2024-12-11 14:31 UTC, andymunro requested changes
@rmartinc A few suggestions. Looks very good.

2024-12-12 07:59 UTC, mposolda approved these changes
@andymunro Thanks for the review!

2024-12-12 10:16 UTC, merged