fix: detecting provider changes when running start optimized
keycloak/keycloak pull request #35845
Opened 2024-12-12 00:57 UTC by shawkins

also using the optimized mixin rather than scanning the args

closes: #34665

2024-12-13 17:28 UTC, shawkins commented
This should be ready. The message format will mention that something with the kc.provider.file. prefix has changed. Alternatively we could reuse auto-build option changed logic showing the old and new values - but we'd probably need to mask quarkus. values.

Using a single check for all persisted build state does make things more stringent - the operator was trying to unilaterally turn off health-enabled via an env var, but use an optimized image that would no longer work. If we consider something like that a breaking change for optimized non-server commands, then this will need to be reworked.

cc @mabartos @vmuzikar @Pepo48

2025-01-08 18:31 UTC, vmuzikar requested changes

2025-01-08 18:31 UTC, vmuzikar commented on operator/src/main/java/org/keycloak/operator/controllers/KeycloakRealmImportJobDependentResource.java
> -        var runBuild = !keycloakContainer.getArgs().contains(KeycloakDeploymentDependentResource.OPTIMIZED_ARG) ? "/opt/keycloak/bin/kc.sh --verbose build && " : "";
I'm probably doing something wrong but even if I do something like this with the current main:
```
kc.sh build --db=postgres
kc.sh start --http-enabled=true --hostname-strict=false --optimized
```
I get an error. So not sure why it worked like that in the Operator before.

2025-01-09 13:55 UTC, shawkins commented on quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java
> +                || key.startsWith(KC_PROVIDER_FILE_PREFIX) || isIgnoredPersistedOption(key);
For the purposes of showing what has changing with autobuild we're omitting quarkus and kc.provider.file properties. For the build check we want to include both of those.

So we could move that check, but it would at least require creating yet another condition in the build check - one already exists for the kc.provider.file keys, so another one would be needed for quarkus keys.

2025-01-09 13:58 UTC, shawkins commented on operator/src/main/java/org/keycloak/operator/controllers/KeycloakRealmImportJobDependentResource.java
> -        var runBuild = !keycloakContainer.getArgs().contains(KeycloakDeploymentDependentResource.OPTIMIZED_ARG) ? "/opt/keycloak/bin/kc.sh --verbose build && " : "";
Do you mean if you then do an import with the env setting for health-enabled after that it errors?

2025-01-09 15:06 UTC, shawkins commented on quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/cli/PicocliTest.java
> +        assertTrue(nonRunningPicocli.getErrString().contains("The following build time options have values that differ from what is persisted - the new values will NOT be used until another build is
Ok added a general message about the a provider jar changing.

2025-01-09 15:06 UTC, shawkins commented on operator/src/test/java/org/keycloak/operator/testsuite/integration/RealmImportTest.java
> +        assertThat(envvars.stream().filter(e -> e.getName().equals(getKeycloakOptionEnvVarName("health-enabled"))).findAny().isEmpty());
Added.

2025-02-03 14:20 UTC, vmuzikar approved these changes, later dismissed
Sorry for the late response.

LGTM. Added one minor question but approving regardless.

I'm also gonna rebase to see if tests still pass.

2025-02-03 14:20 UTC, vmuzikar commented on operator/src/main/java/org/keycloak/operator/controllers/KeycloakRealmImportJobDependentResource.java
> -        var runBuild = !keycloakContainer.getArgs().contains(KeycloakDeploymentDependentResource.OPTIMIZED_ARG) ? "/opt/keycloak/bin/kc.sh --verbose build && " : "";
Never mind, I think I just got confused here. 🙈

However, I do still wonder what is the benefit of disabling health in import. It doesn't help perf too much.

2025-02-03 14:21 UTC, vmuzikar commented
@shawkins Rebase here complains about conflict. Can you please rebase manually?

2025-02-03 15:16 UTC, shawkins commented
> @shawkins Rebase here complains about conflict. Can you please rebase manually?

Should be up-to-date now.

2025-02-03 15:21 UTC, vmuzikar commented on services/src/main/java/org/keycloak/authentication/forms/RegistrationRecaptcha.java
> +
Just a nitpick. This seems like an unintentional change caused by the rebase.

2025-02-03 15:24 UTC, shawkins commented on services/src/main/java/org/keycloak/authentication/forms/RegistrationRecaptcha.java
> +
Indeed, removed.

2025-02-03 15:31 UTC, vmuzikar approved these changes
Thank you, LGTM.

2025-02-03 16:20 UTC, merged