fix: resetting failingSince on datasourceHealthCheck == UP
keycloak/keycloak pull request #35905
Opened 2024-12-13 19:45 UTC by shawkins

closes: #35904

2025-01-07 11:38 UTC, vmuzikar requested changes
@shawkins Thanks for the PR. It'd be nice to have a test for it as well. Can you please add some?

2025-01-07 14:03 UTC, shawkins commented
> @shawkins Thanks for the PR. It'd be nice to have a test for it as well. Can you please add some?

Would you mind if this pulled in the quarkus mock dependency? It will be much easier than coming up with an integration test for this.

2025-01-07 14:28 UTC, vmuzikar commented
While we generally [try and avoid](https://github.com/keycloak/keycloak/blob/1c4dd66f523c22942c26b001585466eaf56de1f4/CONTRIBUTING.md?plain=1#L74) any mock frameworks, IMHO in an isolated case like that it's fine and actually improves the maintainability of the test.

2025-01-07 16:53 UTC, shawkins commented
> While we generally [try and avoid](https://github.com/keycloak/keycloak/blob/1c4dd66f523c22942c26b001585466eaf56de1f4/CONTRIBUTING.md?plain=1#L74) any mock frameworks, IMHO in an isolated case like that it's fine and actually improves the maintainability of the test.

The alternative seems to be a containerized test where we can control the database being up or down and do something that will ensure an active connection will be in the pool. 

I've updated with a mock QuarkusTest, let me know if you are ok with that.

2025-01-08 13:21 UTC, vmuzikar approved these changes
@shawkins Thanks for the update. Looking at the changes, IMHO it's ok to go ahead with the mock in the end. It's a unit test and we're naturally extending an existing one. And it was already kinda hacky (closing manually agroal resource), so mocking it doesn't do any harm in this specific case.

LGTM.

2025-01-08 13:21 UTC, merged