Correct documention of GET GroupResources
keycloak/keycloak pull request #36022
Opened 2024-12-18 21:20 UTC by RichieB2B

Fixes erroneous statement added by #34128

2024-12-18 21:24 UTC, ahus1 requested changes
In my original comment I mixed up `empty` with `not provided`, so this is what had in mind originally. Please let me know if this makes sense.

2024-12-18 21:24 UTC, ahus1 commented on services/src/main/java/org/keycloak/services/resources/admin/GroupsResource.java
> +     * If these parameters are empty, the top-level groups are returned with `{@code subGroups} being filled.
```suggestion
     * If none of these parameters is provided, the top-level groups are returned without `{@code subGroups} being filled.
```

2024-12-18 21:24 UTC, ahus1 commented on services/src/main/java/org/keycloak/services/resources/admin/GroupsResource.java
> +    @Operation( summary = "Get group hierarchy.  Only `name` and `id` are returned.  `subGroups` are only returned when using the `search` or `q` parameter. If these parameters are empty, the top-lev
```suggestion
    @Operation( summary = "Get group hierarchy.  Only `name` and `id` are returned.  `subGroups` are only returned when using the `search` or `q` parameter. If none of these parameters is, the top-level groups are returned without `subGroups` being filled.")
```

2024-12-18 21:38 UTC, RichieB2B commented
I totally agree but please remember the whole reason for this documentation change is the strange behaviour of `getGroups` since the 23.0 release. In #27694 this was described as intended behaviour but the breaking change has not been documented anywhere. This keeps confusing users of the API. If you revert the docs change, please also fix the bug. Otherwise we'll be back at square one.

2024-12-19 10:10 UTC, ahus1 approved these changes
As it is unclear when the original issue is handled, let's update the docs only. I'll re-open the original issue once this PR is merged.

2024-12-19 10:10 UTC, merged