Create credential signer providers to complement credential building
keycloak/keycloak pull request #36056
Opened 2024-12-19 14:38 UTC by IngridPuppet

Closes #32953

Upon checking this PR, reviewers are invited to leave a feedback as to what extent they believe the following issues are indirectly covered:
- https://github.com/keycloak/keycloak/issues/32959
- https://github.com/keycloak/keycloak/issues/32958

2025-01-10 08:47 UTC, mposolda commented
@IngridPuppet Thanks!

I did a look to your PR and it looks OK, but I would like that the PR is reviewed by more members of OAuth SIG, who are directly involved in the OID4VCI work. So additional reviews would be welcome. CC @Captain-P-Goldfish @tnorimat @wistefan @francis-pouatcha

2025-01-13 13:22 UTC, babisRoutis commented on js/apps/account-ui/test/realms/verifiable-credentials-realm.json
> +          "providerId": "vc+sd-jwt",
I am not sure how the value `vc+sd-jwt` is being used. 
Perhaps, though, it needs to change to `dc+sd-jwt` 

I guess the same is true for `Format.SD_JWT_VC`

Reason for this change is that in [draft 15](https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0.html#appendix-J) of openid4vci the format value for SD-JWT-VC changed from `vc+sd-jwt` to `dc+sd-jwt`. The later is the one used by [SD-JWT-VC](https://www.ietf.org/archive/id/draft-ietf-oauth-sd-jwt-vc-08.html#name-application-dcsd-jwt)

This could a subject for an other issuer/PR, of course

2025-01-13 16:26 UTC, IngridPuppet commented on js/apps/account-ui/test/realms/verifiable-credentials-realm.json
> +          "providerId": "vc+sd-jwt",
Hello @babisRoutis - Thank you for your feedback. At this specific point, the value is intended as a mere identifier for an SD-JWT credential builder provider. You're right on that it is actually reflecting the constant `Format.SD_JWT_VC`.

For what I know, we've been implementing Draft 13 of the specification so far. I'm also not sure if it is right the time or the right PR to start bringing in recent updates to the specification, and would hence agree to have another issue for the matter.

2025-01-14 19:39 UTC, francis-pouatcha requested changes

2025-01-14 19:39 UTC, francis-pouatcha commented on services/src/main/java/org/keycloak/protocol/oid4vc/issuance/OID4VCIssuerEndpoint.java
>      private final Map<String, CredentialBuilder> credentialBuilders;
Consider adding comments to explain the rationale behind the changes and the benefits of the new approach. I guess this change removes the signingServices map and associated logic.

2025-01-14 19:39 UTC, francis-pouatcha commented on services/src/main/java/org/keycloak/protocol/oid4vc/issuance/OID4VCIssuerWellKnownProvider.java
> +    private static List<String> getSupportedFormats(KeycloakSession keycloakSession) {
What about edge cases such as mismatches between builders and signers (e.g jwt_vc builder and sdjwt signer).

2025-01-16 07:10 UTC, Captain-P-Goldfish requested changes

2025-01-16 07:10 UTC, Captain-P-Goldfish commented on services/src/main/java/org/keycloak/protocol/oid4vc/issuance/signing/LDCredentialSigner.java
> +    private static final String PROOF_KEY = "proof";
I'd prefer to have such constants public.
Could be interesting if the provider gets overridden for some reason

2025-01-16 07:10 UTC, Captain-P-Goldfish commented on services/src/main/java/org/keycloak/protocol/oid4vc/model/CredentialBuildConfig.java
> +    private String overrideKeyId;
Just out of curiosity. Why using simple code-comments instead of javadoc?

2025-01-16 07:11 UTC, Captain-P-Goldfish commented
despite the minor change-requests from my side, the changes look very good to me.

2025-01-16 09:53 UTC, wistefan commented on services/src/main/java/org/keycloak/protocol/oid4vc/issuance/keybinding/ProofValidatorFactory.java
> +
I think some line of documentation, explaining why those methods are defaulted to noop would be helpful

2025-01-16 09:53 UTC, wistefan commented on services/src/main/java/org/keycloak/protocol/oid4vc/issuance/keybinding/ProofValidatorSpi.java
> + * @author <a href="https://github.com/wistefan">Stefan Wiedemann</a>
I doubt that;)

2025-01-17 08:00 UTC, mposolda commented on services/src/main/java/org/keycloak/protocol/oid4vc/model/CredentialBuildConfig.java
> +    private String overrideKeyId;
IMO simple comment is fine as this is private variable and javadoc won't be published anywhere? So the only one, who see this comment/javadoc, is the guy who is reading the source code and hence he may not care if it is javadoc or comment?

So comment is maybe slightly better due the fact that javadocs are supposed to be published, which this one won't be AFAIK. But no strong on this... If you prefer javadoc instead of comment for private variables, it is fine to me.

2025-01-21 00:44 UTC, tnorimat approved these changes
LGTM.

2025-01-21 10:34 UTC, IngridPuppet commented on services/src/main/java/org/keycloak/protocol/oid4vc/issuance/OID4VCIssuerEndpoint.java
>      private final Map<String, CredentialBuilder> credentialBuilders;
Thank you for your review. Signing services are indeed removed and substituted by the combination of a credential builder and its corresponding signer. But note that the line you highlight is not an addition of this PR. Credential signers can be loaded accurately from Keycloak's component container and thus do not require an explicit property map as opposed to credential builders. I've extended the JavaDoc to better describe the role of credential builders and their relation to credential signers.

2025-01-21 10:34 UTC, IngridPuppet commented on services/src/main/java/org/keycloak/protocol/oid4vc/issuance/OID4VCIssuerWellKnownProvider.java
> +    private static List<String> getSupportedFormats(KeycloakSession keycloakSession) {
With the implementation proposed, supported credential formats are those for which a credential builder AND a credential signer are available. I think this logic is per se a guarantee for such edge cases to not occur.

2025-01-21 10:36 UTC, IngridPuppet commented on services/src/main/java/org/keycloak/protocol/oid4vc/issuance/OID4VCIssuerWellKnownProvider.java
> +    private static List<String> getSupportedFormats(KeycloakSession keycloakSession) {
Thank you for your review. I agree with you on this point and turned the method public.

2025-01-21 10:37 UTC, IngridPuppet commented on services/src/main/java/org/keycloak/protocol/oid4vc/issuance/credentialbuilder/SdJwtCredentialBody.java
>      private final Map<String, Object> claimSet;
Agree. I added a getter-method for the claimSet property.

2025-01-21 10:38 UTC, IngridPuppet commented on services/src/main/java/org/keycloak/protocol/oid4vc/issuance/signing/LDCredentialSigner.java
> +    private static final String PROOF_KEY = "proof";
Agree. The pointed constants are now public.

2025-01-21 10:39 UTC, IngridPuppet commented on services/src/main/java/org/keycloak/protocol/oid4vc/model/CredentialBuildConfig.java
> +    private String overrideKeyId;
I understand the benefits of using javadocs, but I tend to find simple comments less obstructive, especially when there is no strong requirement for using the former.

2025-01-21 10:41 UTC, IngridPuppet commented on services/src/main/java/org/keycloak/protocol/oid4vc/issuance/keybinding/ProofValidatorSpi.java
> + * @author <a href="https://github.com/wistefan">Stefan Wiedemann</a>
Spoofing attack neutralized 😅 The authorship claim was updated.

2025-01-21 13:11 UTC, francis-pouatcha approved these changes

2025-01-22 07:38 UTC, wistefan commented
LGTM

2025-01-22 07:39 UTC, wistefan approved these changes

2025-01-23 06:19 UTC, Captain-P-Goldfish commented on services/src/main/java/org/keycloak/protocol/oid4vc/model/CredentialBuildConfig.java
> +    private String overrideKeyId;
no objections

2025-01-23 06:22 UTC, Captain-P-Goldfish commented
looks also good to me. Good work!

2025-01-23 18:48 UTC, mposolda approved these changes

2025-01-23 20:11 UTC, Captain-P-Goldfish approved these changes

2025-01-24 10:27 UTC, edewit approved these changes

2025-01-24 16:15 UTC, merged