Fixed alternative flow execution
keycloak/keycloak pull request #36082
Opened 2024-12-20 09:18 UTC by VonRehberg

Hey keycloak team,

We are evaluating the use of keycloak and stumbled across issue #17411.
After investigating the code I made a fix but need some feedback whether this would be mergable from your perspective and if not, what exactly is necessary to bring it to a mergeable state :-)

Thanks in advance!

2024-12-20 15:06 UTC, VonRehberg commented
FYI: this is what the response looks like in case no alternative is successfully executed:
<img width="453" alt="Screenshot 2024-12-20 at 16 05 45" src="https://github.com/user-attachments/assets/4ac19cfe-093a-4032-bb55-e5e3b00aead7" />

2025-01-07 10:05 UTC, adrianhanrath commented
Happy to see that the #17411 was fixed 🚀 

is there an update on this merge request? 😄

2025-01-17 13:14 UTC, VonRehberg commented
I just noticed that my changes could break browser flows so I fixed it accordingly :-)

2025-03-05 14:19 UTC, adrianhanrath commented
Any update?

2025-03-13 11:09 UTC, adrianhanrath commented
@mposolda do you have any feedback? Are there changes needed? We are happy to assist if needed.

2025-06-13 13:50 UTC, AndreV93 commented
Hey, is there any support required? @mposolda? I'd really love to have that fix in place

2025-08-01 12:32 UTC, AndreV93 commented
Another gentle push @mposolda

2026-01-23 14:00 UTC, adrianhanrath commented
What is missing here to get it merged?

2026-03-23 17:48 UTC, adrianhanrath commented
🚀

2026-03-25 07:22 UTC, VonRehberg commented
Hey @mposolda 
Last week we did the production migration to keycloak. Although we are not yet using mTLS with direct grant, we already built the flow and activated it.
Having it in action we noticed that, although token requests succeeded, the failing alternative flows spammend the logs and events with LOGIN_ERROR messags.
We are currently working on this and will push some more changes soon.
Cheers

2026-03-26 12:04 UTC, VonRehberg commented
@mposolda Done with the changes :-) Ready for review

2026-05-05 13:03 UTC, VonRehberg commented
Sounds like it would make sense to mark all alternatives as failed instead of attempted, when the entire flow fails so we won't miss the brute force protection!?
@mabartos

2026-05-07 07:00 UTC, rmartinc requested changes
Sorry @VonRehberg for not checking this in a long time. But I think that @mposolda was right and the flows are more thought for the browser flow than the direct grants. But I think that a quick option fix was returning just attempted in the case the authenticator does not have the needed things (username parameter and certs respectively). All the rest would be not needed. 

Can you please give a try with that minimal change? Does it work for you?

We also need a test for this, you can check `src/test/java/org/keycloak/testsuite/x509/X509DirectGrantTest` as it seems the correct place to start looking.

2026-05-07 07:00 UTC, rmartinc commented on services/src/main/java/org/keycloak/authentication/authenticators/directgrant/ValidateUsername.java
>              context.failure(AuthenticationFlowError.INVALID_USER, challengeResponse);
Probably what we need here is just do:


```suggestion
                        context.getEvent().error(Errors.USER_NOT_FOUND);
                        context.attempted();
```

But just in this first case, after that return failure as it is now. This way if the username parameter is there it is executed and if not it's just attempted and the next alternative would be tried. IMO all the rest is not needed as a first approximation.

2026-05-07 07:00 UTC, rmartinc commented on services/src/main/java/org/keycloak/authentication/authenticators/x509/ValidateX509CertificateUsername.java
>              context.failure(AuthenticationFlowError.INVALID_USER, challengeResponse);
Same here more or less:


```suggestion
            context.getEvent().error(Errors.USER_NOT_FOUND);
            context.attempted();
```

Same idea, if there are no certs just attempt and go to the next authenticator.

2026-05-13 14:36 UTC, rmartinc commented
I'm closing this for the moment. @VonRehberg, if you want to rebase and try with my simpler suggestion, feel free to re-open it or send a new PR.

2026-05-13 14:36 UTC, closed without merging

2026-05-16 20:58 UTC, VonRehberg commented
Hi Martin,
thanks for the feedback!
As the project we are working on progressed, we decided to go for a different approach, so pursuing this pull request became more and more academic.
In case anyone is interested:
At the beginning of the project we expected our clients connecting to the platform either have passwords or X509 certificates and are authenticating using the same OAuth clients.
Since x509 certificates have an expiry date and it should not be possible to stay authenticated beyond the expiry date, we decided to go for a dedicated oAuth mTLS client with:
* Custom X509 direct grant flow binding (no alternative, no username+password authentication, just plain x509)
* refresh tokens disabled
This requires clients to present an up to date certificate when requesting a new access token.