KEYCLOAK-4086 Client credentials missing in bearer-only JSON config
keycloak/keycloak pull request #3649
Opened 2016-12-14 23:26 UTC by sldab

For bearer-only clients the client credentials are only added to the JSON configuration if a node reregistration timeout is set for the client. I guess this was fine as long as the JSON configuration contained the realm public key, but now that the key is fetched dynamically, the client credentials are necessary.

2016-12-15 12:08 UTC, mposolda commented
@sldab Strange, this shouldn't be necessary. Even our own example demo doesn't have client credentials is working fine https://github.com/keycloak/keycloak/blob/master/examples/demo-template/database-service/src/main/webapp/WEB-INF/keycloak.json .

Any details of the scenario where the missing client credentials for bearer-only client breaks stuff for you?

2016-12-15 18:41 UTC, sldab commented
I have checked this. The issue only occurs if you enable authorization for the client.
There's some logic in https://github.com/keycloak/keycloak/blob/master/server-spi-private/src/main/java/org/keycloak/models/utils/RepresentationToModel.java#L1812-L1818 that turns a bearer-only client into a confidential client when authorization is enabled. But this is only called when importing a realm configuration, not when enabling authorization in the UI.

2016-12-16 08:09 UTC, stianst commented
This PR is a bit oversimplified as it will return credentials for all bearer-only applications, not just those that have authorization services enabled. @pedroigor what do you think?

@mposolda bearer-only clients actually requires credentials to invoke the authorization service endopoints, so when authz services is enabled it's required

2016-12-17 12:24 UTC, sldab commented
Unfortunately, there is no easy way to find out if authz services are enabled for a specific client as of now. However, `serviceAccountsEnabled` is set to `true` for bearer-only once authz is enabled. We could check for this for now.

BTW, service accounts stay enabled even after disabling authz again.

2016-12-18 19:20 UTC, sldab commented
Updated PR to use the `serviceAccountsEnabled` flag instead and deactivate it when disabling authz for bearer clients.

2016-12-19 11:13 UTC, stianst requested changes

2016-12-19 11:13 UTC, stianst commented on services/src/main/java/org/keycloak/protocol/oidc/installation/KeycloakOIDCClientInstallation.java
> +        if (client.isBearerOnly() && !client.isServiceAccountsEnabled() && client.getNodeReRegistrationTimeout() <= 0) {
Seems OK, but could you add tests to https://github.com/keycloak/keycloak/blob/master/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/client/InstallationTest.java please?

2016-12-19 11:13 UTC, stianst commented on themes/src/main/resources/theme/base/admin/resources/js/controllers/clients.js
> +        } else if ($scope.client.bearerOnly) {
This is not correct. A service (bearer-only) should be able to have credentials so it can use the authz services.

2016-12-19 14:53 UTC, sldab commented on themes/src/main/resources/theme/base/admin/resources/js/controllers/clients.js
> +        } else if ($scope.client.bearerOnly) {
This is actually makes sure that the service account is disabled once authz services are disabled. Its stays enabled before after deactivating them.

2016-12-19 16:05 UTC, sldab commented
Added tests. @stianst: Could you please have a second look at the change in `client.js`. IMO, this should be correct.

2016-12-20 11:30 UTC, stianst commented on themes/src/main/resources/theme/base/admin/resources/js/controllers/clients.js
> +        } else if ($scope.client.bearerOnly) {
Yep, you're right. I missed the if statement that makes sure this is not used for clients with authz services enabled.

2016-12-20 11:31 UTC, stianst approved these changes

2016-12-20 11:32 UTC, stianst commented
Looks good - thanks

2016-12-20 11:32 UTC, merged