KEYCLOAK-4412: Allow multible theme directories
keycloak/keycloak pull request #3860
Opened 2017-02-13 19:05 UTC by ssilvert

2017-02-14 07:37 UTC, stianst requested changes

2017-02-14 07:37 UTC, stianst commented on testsuite/integration-arquillian/tests/other/console/pom.xml
> +        <developer.theme.dir>${project.basedir}/../../../../../themes/src/main/resources/theme</developer.theme.dir>
Is this not changing the server that is tested? There seems to be a chance here that resources not copied by mistake when building the server would be loaded directly from themes/src and the bug wouldn't be caught during testing.

2017-02-14 12:39 UTC, ssilvert commented on testsuite/integration-arquillian/tests/other/console/pom.xml
> +        <developer.theme.dir>${project.basedir}/../../../../../themes/src/main/resources/theme</developer.theme.dir>
I'm not sure I understand your question.  It's not changing the server being tested.  

Line 35 changes the directory where the custom themes are copied and later found at runtime.
Line 36 lets the "base" and "keycloak" themes be read from the development directory.

2017-02-15 08:26 UTC, stianst commented on testsuite/integration-arquillian/tests/other/console/pom.xml
> +        <developer.theme.dir>${project.basedir}/../../../../../themes/src/main/resources/theme</developer.theme.dir>
Exactly what I'm saying. You're reading the themes from a different directory, so the setup doesn't match an actual real installation.

2017-02-15 12:05 UTC, ssilvert commented on testsuite/integration-arquillian/tests/other/console/pom.xml
> +        <developer.theme.dir>${project.basedir}/../../../../../themes/src/main/resources/theme</developer.theme.dir>
Ah.  I thought you meant I was somehow changing which server instance was being tested.  But in this case I don't understand your objection.   We have plenty of other tests that use the default configuration.

If you like, I can just move those two lines to a different profile.

2017-02-17 17:43 UTC, closed without merging