KEYCLOAK-4489 SAML assertion with newlines fails during parsing
keycloak/keycloak pull request #3886
Opened 2017-02-22 11:28 UTC by anderius

Use event reader from AbstractParser, which handles newlines and whitespace.

2017-02-22 11:29 UTC, anderius commented
Again, if there is any test that could easily be extended to cover this, I will be happy to do it.

2017-02-22 13:14 UTC, anderius commented
From Travis:

> The job exceeded the maximum time limit for jobs, and has been terminated.

2017-02-23 19:12 UTC, anderius commented
I am not sure if it is documented somewhere, but OpenAM seems to like adding line breaks inside xml tags, as seen in this discussion: https://marc.info/?l=forgerock-openam&m=139603408827362&w=2.

Given the widespread use of OpenAM, I hope this fix will make it into master!

There is more work needed for signature verification, I am looking into that now...

2017-02-27 08:48 UTC, hmlnarik commented
Thank you for the code, it looks good to me. Please add a test to [SAMLParserTest](https://github.com/keycloak/keycloak/blob/master/saml-core/src/test/java/org/keycloak/saml/processing/core/parsers/saml/SAMLParserTest.java), similar to e.g. testSaml20AuthnResponseNonAsciiNameDefaultLatin2.

2017-02-27 08:48 UTC, hmlnarik requested changes
Please add test as per above

2017-02-28 08:52 UTC, anderius commented on saml-core/src/test/java/org/keycloak/saml/processing/core/parsers/saml/SAMLParserTest.java
> +    public void testAsml20EncryptedAssertionWithNewlines() throws Exception {
I have verified that this test actually does not succeed without the fix.

2017-02-28 08:53 UTC, anderius commented
@hmlnarik: Test added, thanks for the pointer!

2017-02-28 11:03 UTC, anderius commented
> The job exceeded the maximum time limit for jobs, and has been terminated.

2017-02-28 11:44 UTC, hmlnarik requested changes
Thank you for the test. Just a small nit remaining, I believe then after fixing that the code can be incorporated in master.

2017-02-28 11:44 UTC, hmlnarik commented on saml-core/src/test/java/org/keycloak/saml/processing/core/parsers/saml/SAMLParserTest.java
> +            PrivateKey privateKey = PemUtils.decodePrivateKey(StreamUtil.readString(privateKeyStream, StandardCharsets.UTF_8));
To minimize number of files around, can you please declare the keys as a constant instead of loading them from a separate files?

2017-02-28 13:11 UTC, anderius commented on saml-core/src/test/java/org/keycloak/saml/processing/core/parsers/saml/SAMLParserTest.java
> +            PrivateKey privateKey = PemUtils.decodePrivateKey(StreamUtil.readString(privateKeyStream, StandardCharsets.UTF_8));
Good idea! Done.

2017-02-28 13:15 UTC, anderius commented
@hmlnarik: Test is now changed, I agree it is much cleaner this way. :-)

2017-02-28 14:16 UTC, anderius commented
@hmlnarik Would it be possible to also get this in 2.5.x? Should I create a pull-request there as well? I hope to get it included in RH-SSO 7.1...

2017-03-07 11:21 UTC, anderius commented
@hmlnarik, @stianst: Is there anything else I can do to get progress here? It is a samll fix, and it will make Keycloak usable with an OpenAM IdP that encrypts the assertion...

2017-03-07 14:28 UTC, stianst commented
@hmlnarik can you check again please and give me a go ahead if it's ok to merge?

2017-03-07 14:29 UTC, hmlnarik requested changes
One more typo I didn't spot earlier and then IMHO good to go

2017-03-07 14:29 UTC, hmlnarik commented on saml-core/src/test/java/org/keycloak/saml/processing/core/parsers/saml/SAMLParserTest.java
> +    public void testAsml20EncryptedAssertionWithNewlines() throws Exception {
Nit: test**As**ml20EncryptedAssertionWithNewlines -> test**Sa**ml20EncryptedAssertionWithNewlines

2017-03-07 18:06 UTC, anderius commented
Thank you, well spotted @hmlnarik! I have now fixed the spelling mistake!

2017-03-09 05:38 UTC, hmlnarik commented
This one looks good to me, thanks.
@stianst Could you please merge this PR?

2017-03-09 07:29 UTC, stianst commented
@anderius I'm afraid we can't include this in RH-SSO 7.1 at this stage as it's currently just going through last stages of testing. If you talk to support you can probably get a one-off patch for this one and also request that it's included in 7.1.1.

2017-03-09 07:29 UTC, merged

2017-03-09 07:37 UTC, anderius commented
@stianst Thank you!

That is understandable. I will have to use a private fork anyway, until https://github.com/keycloak/keycloak/pull/3897 is included.