KEYCLOAK-4366
keycloak/keycloak pull request #3962
Opened 2017-03-21 07:12 UTC by mhajas

2017-03-24 11:09 UTC, stianst requested changes

2017-03-24 11:09 UTC, stianst commented on testsuite/integration-arquillian/test-apps/js-console/example-realm.json
> +            ],
This makes no sense. A javascript client shouldn't have a secret.

2017-03-27 09:21 UTC, mhajas commented on testsuite/integration-arquillian/test-apps/js-console/example-realm.json
> +            ],
I would have sworn I needed this for some reason. But maybe I mixed it with something else. Thanks for notice.

2017-04-04 08:54 UTC, mhajas commented
Requested changes are done.

2017-04-10 06:44 UTC, merged