KEYCLOAK-4743 Add support for HTTP Proxy in DefaultHttpClientFactory
keycloak/keycloak pull request #4040
Opened 2017-04-18 16:18 UTC by thomasdarimont

We now support basic proxy configuration for out-bound calls
via the HttpClient provided by the HttpClientProvider.

To configure a proxy one needs to set the proxy-url property to the
"default" connectionsHttpClient in the standalone(-ha).xml file.
The `HttpClientBuilder` builder will derive the proxy configuration
from the provided proxy-url.
By default no proxy is configured.

The following jboss-cli command can be used to configure
the proxy-url.
```
/subsystem=keycloak-server/spi=connectionsHttpClient/provider=default:write-attribute(name=properties.proxy-url,value="http://www-proxy.tdlabs.local:3128")
```

2017-04-19 07:05 UTC, stianst commented
We'll need this added to documentation and also a test for it.

2017-04-19 11:54 UTC, thomasdarimont commented
Documentation is here: https://github.com/keycloak/keycloak-documentation/pull/108
testing a proxy is a bit difficult. Would it be enough to show that a configured `proxy-url`
is applied to a `HttpClient`?

2017-04-19 12:13 UTC, stianst commented
The more I think about it the more complicated introducing support for a web proxy becomes. Keycloak makes outgoing HTTP requests in a number of situations. Logout requests to clients, captcha support, identity brokering, etc.. There's probably a few I've missed as well. Even worse a client could be internal or external, in which case it should use the web proxy only when it's external, which in turns means there needs to be two differently configured http clients.

With regards to testing. No, simply testing that the proxy-url is not sufficient. We can't introduce a new feature without having functional testing for it. That means checking that identity brokering, clients, captcha, etc. all work when behind a web proxy.

2017-04-19 12:41 UTC, thomasdarimont commented
Stian, I'm totally with you on that proper proxy support is quite involved, especially if you need to support things like proxy authentication, dynamic proxy routes, different http/https proxies etc.
I have to deal with that on a daily basis... :-/
But unfortunately proxies are quite common in corporate environments.

I think having a solution that works for a majority of users is a good default and 
a simple proxy configuration would provide this.

Of course the documentation could also tell users to provide their own `org.keycloak.connections.httpclient.HttpClientFactory` to build a `HttpClient` that suits their needs,
but this should IMHO not be the default answer.

Another less preferable option is of course to instruct the Network Ops team to allow communication to certain destinations without proxy...

A full integration test with proxies can be quite tricky... 
I way that might work is:
* start a simple proxy server on the same machine, e.g. https://tinyproxy.github.io/
* configure it as proxy-server in the application
* run all integration tests (again)

This would require that all components that are making outbound calls are 
using the `HttpClientProvider`.

2017-04-19 12:50 UTC, stianst commented
I think a single httpclient will be insufficient even in the simplest cases. Most companies will have some internal applications and either some external applications, a social provider or use the captcha.

It wouldn't even be possible to do it with a custom factory as the factory doesn't know what the client is going to be used for. Is there a way to configure the http client to use the web proxy only for external requests?

I'm pretty sure we no longer have anything making outgoing HTTP requests that don't use the provider, but that would need to be confirmed as part of this work.

2017-04-19 12:51 UTC, stianst commented
BTW if it was a simple as adding a configuration option to the factory we would have done it a long time ago ;)

2017-04-19 13:01 UTC, thomasdarimont commented
There are ways to dynamically determine the proxy to use based on the destination host.

In plain java there is a `ProxySelector`:
https://docs.oracle.com/javase/8/docs/api/java/net/ProxySelector.html

For the Version of httpclient there is `org.apache.http.impl.conn.DefaultProxyRoutePlanner`
See: http://stackoverflow.com/questions/25567973/apache-httpclient-4-3-5-set-proxy

2017-04-19 13:08 UTC, stianst commented
In that case I'd suggest the default implementation should use the proxy only when it's an external IP. It can use the logic from https://github.com/keycloak/keycloak/blob/master/common/src/main/java/org/keycloak/common/enums/SslRequired.java#L51

2017-04-19 13:31 UTC, thomasdarimont commented
Can do that but, in some environments even intra-company traffic needs to go though a proxy... :-/

2017-04-19 13:46 UTC, stianst commented
Hmm... let's make it a configurable option then?

proxy-exclude-internal : true/false??

2017-04-20 09:21 UTC, rouxcorp commented
I think we should use the system settings for that with `.useSystemProperties()` (see http://stackoverflow.com/a/26062205)

So we can set the proxy with `-Dhttp.proxyHost` and `-Dhttp.proxyPort` and exclude some hosts with the `-Dhttp.nonProxyHosts=` option as we did before.

2017-04-20 11:16 UTC, stianst commented
Absolutely no way. We're not doing system properties to configure Keycloak. Configuration goes in standalone.xml where all the other configuration is.

2017-04-20 11:17 UTC, stianst commented
BTW If you still would like to use system properties that's fine as you can use variables inside standalone.xml, including env variables

2017-04-21 09:27 UTC, stianst requested changes
Will need an option to enable/disable proxy for internal requests. Needs testing.

2017-04-24 12:47 UTC, rouxcorp commented
No, in a real environment we DO NOT set the proxy configuration for EACH services...
There is a set of well-known environment variables named `http_proxy`, `https_proxy`, `ftp_proxy` and `no_proxy`. They are used in a vast majority of net/HTTP libraries.

This configuration is a system one - not a specific one.
It has nothing to do in the `standalone.xml` file

If you want to re-invent the well, fell free to do it... but think twice.

2017-04-24 13:30 UTC, stianst commented
@antoine-roux Configuration for Keycloak server goes into standalone.xml that's the way we do it. As I said you can use variables in standalone.xml to then make it pull the values from whatever system property or environment variable you want. So I don't understand what you are complaining about.

2017-04-24 14:57 UTC, antoine-roux commented
@stianst You don't seem to admit that the proxy configuration is not a Keycloak configuration.
If we go further, I'm sure you don't want to put the entire network settings in `standalone.xml`. So I don't understand why you persist to want to include the proxy one in the Keycloak configuration file.

In order to see the complexity of the thing, search for `.pac` files and read https://libproxy.github.io/libproxy/ This library is a good example of a try to make the proxy more abstract in the GNOME code.

PAC files are Java-scripts written by sysadmins. It says to programs which machine to contact to reach the Internet. It's an existing solution used by many programs.
Here, a simpler solution would be to take into account the system settings through the library himself with `.useSystemProperties()`. It will read the Java Settings.

As I said, you can re-write the same thing in you code, but you must consider the features of the libraries you use.

2017-04-25 06:51 UTC, stianst commented
@antoine-roux I don't get why you are complaining as you will be able to do it the way you want. I just don't see the need for this argument. HttpClient doesn't read the variables you are talking about. We need to wire them in somehow. Rather than hard-code it we can do it more flexibly in standalone.xml which allows folks to do it however they want. They can put the proxy URL directly into standalone.xml, use system properties or environment values. It comes for free with no extra work and is more flexible.

2017-04-28 08:14 UTC, stianst commented
@thomasdarimont are you planning on addressing the issues with testing and also with client/idps being on both internal and external networks? If not I'm going to close this PR as we can't merge it until we have a plan to test it and we don't have resources to deal with that ourselves at the moment.

2017-04-28 08:46 UTC, thomasdarimont commented
I'm working on it, but I need to change some things based on the discussions.

2017-05-23 11:21 UTC, stianst commented
Closing due to lack of progress. Please re-open when/if issues and tests have been resolved.

2017-05-23 11:21 UTC, closed without merging

2017-10-06 16:50 UTC, thomasdarimont commented
@antoine-roux would you mind having a look at #4543 ?
I revised the proxy support a bit and I think I'm now flexible enough to meet the discussed requirements.

Bonne weekend & cheers,
Thomas