KEYCLOAK-4752
keycloak/keycloak pull request #4138
Opened 2017-05-13 00:30 UTC by ASzc

Use warnings in the server log to avoid confusing the user with ignored required actions

2017-05-23 12:24 UTC, stianst commented
I'm not keen on this PR. I don't think there's anything wrong in ignoring an action that is disabled even though it is set as a default action. Both are configured on the same screen so I think it's fairly visible to a user that is configuring this that the action is not enabled. In either case it's not nice behaviour to potentially flood the server log with warning messages.

2017-05-23 12:25 UTC, stianst commented
We could make the "default action" checkbox disabled if the action is disabled. We could also clear the "default action" checkbox when an action is disabled.

2017-05-23 12:28 UTC, stianst requested changes
See previous comment

2017-05-30 15:22 UTC, ASzc commented
Updated: Logging changes dropped, UI changes added with some test cases.

2017-06-27 06:34 UTC, merged