[KEYCLOAK-4900] Pass login_hint parameter to idp
keycloak/keycloak pull request #4233
Opened 2017-06-15 15:32 UTC by dmnboutin

Hi, job done to pass login to idp.
Let me.know if i have to do some modification.
Regards

2017-06-27 07:19 UTC, stianst commented
A better way would be to just add the login_hint in AbstractOAuth2IdentityProvider.createAuthorizationUrl like so:
.queryParam(OIDCLoginProtocol.LOGIN_HINT_PARAM, request.getAuthenticationSession().getClientNote(OIDCLoginProtocol.LOGIN_HINT_PARAM))

That's a one line change rather than passing it around.

We would also need a test added for this.

2017-06-29 15:01 UTC, dmnboutin commented
Hello,
ok so no toggle in the identity provider to pass this value or not ?

2017-06-29 18:03 UTC, stianst commented
Yes, please add the toggle, but you don't need to pass the query param around as it'll be already set in the authentication session.

2017-07-04 18:32 UTC, stianst commented
Ping - will you update this to use the note from the authentication session and add tests?

2017-07-05 08:16 UTC, dmnboutin commented
Hi, 
Yes I will push changes as soon as possible.

2017-07-06 07:09 UTC, dmnboutin commented
Hi,
I have pushed modification

2017-07-11 06:57 UTC, stianst requested changes

2017-07-11 06:57 UTC, stianst commented on services/src/main/java/org/keycloak/forms/login/freemarker/FreeMarkerLoginFormsProvider.java
> +        String loginHint = uriInfo.getQueryParameters().getFirst(OIDCLoginProtocol.LOGIN_HINT_PARAM);
This shouldn't be needed. In fact you can't rely on the query param being set at this point due to the way authentication flows work.

2017-07-11 06:57 UTC, stianst commented on services/src/main/java/org/keycloak/forms/login/freemarker/FreeMarkerLoginFormsProvider.java
> +        if(loginHint != null) {
See above

2017-07-11 06:57 UTC, stianst commented on services/src/test/java/org/keycloak/test/broker/oidc/AbstractOAuth2IdentityProviderTest.java
> +	@Test
I'm not following this test. It doesn't seem to be a proper functional test which is what we need. The tests should have a identity provider configured with the pass login hint option enabled. Then go to the login with the login_hint param, click on the link and check that the username field is prefilled in the external IdP login screen (external IdP can be another KC realm on the same server). We should also check that if the pass login_hint option is disabled the username field is not prefilled.

2017-07-11 07:26 UTC, dmnboutin commented on services/src/test/java/org/keycloak/test/broker/oidc/AbstractOAuth2IdentityProviderTest.java
> +	@Test
Hi, in this test I was just validating that "performLogin" service, which create the authorization url is working properly after the change I have done.
That's why, here I have testes it with an idp configured with activated/deactivated toggle on loginHint.

Can you explain, or show an exemple of the kind of test you are waiting for ? 
Thx in advance

2017-07-11 11:28 UTC, stianst commented on services/src/test/java/org/keycloak/test/broker/oidc/AbstractOAuth2IdentityProviderTest.java
> +	@Test
We require proper functional tests with driving the tests through the actual login pages. Take a look at https://github.com/keycloak/keycloak/blob/master/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/AbstractBrokerTest.java#L94. It uses Selenium/Webdriver to go to the actual login page, click on the IDP button, fill in the form on the IDP, etc..

2017-07-13 06:54 UTC, dmnboutin commented on services/src/test/java/org/keycloak/test/broker/oidc/AbstractOAuth2IdentityProviderTest.java
> +	@Test
Ok I will add these tests as soon as possible

2017-07-24 08:16 UTC, dmnboutin commented on services/src/test/java/org/keycloak/test/broker/oidc/AbstractOAuth2IdentityProviderTest.java
> +	@Test
Hi,
I have added functional test as requested

2017-07-25 13:49 UTC, dmnboutin commented
Hi, Changes requested have been done.
Is it ok for you ?

2017-08-22 06:18 UTC, stianst approved these changes

2017-08-25 06:31 UTC, stianst commented
Sent new PR with merge conflicts resolved, removed unnecessary changes to AbstractOAuth2IdentityProviderTest (no need to test URL as it's tested properly in KcOidcBrokerLoginHintTest). Updated KcOidcBrokerLoginHintTest to not pass in username to make sure login works without setting username.

Closing this PR and will merge https://github.com/keycloak/keycloak/pull/4421 with the above changes instead.

2017-08-25 06:31 UTC, closed without merging

2017-08-25 06:31 UTC, stianst commented
Thanks for your contribution and sorry it took so long to get it merged

2017-09-04 08:37 UTC, dmnboutin commented
No problem, thanks for helping