Improve performance of JSPolicyProvider
keycloak/keycloak pull request #4236
Opened 2017-06-16 16:01 UTC by janslow

Creating a new `NashornScriptEngine` is quite slow, so only create a single one and just use new Bindings per evaluation (which are much cheaper). As the engine/global scopes are empty and we're creating a new scope per evaluation, this will still keep each evaluation independent of one another.

In addition, `NashornScriptEngine` implements `Compilable`, so we can compile the JavaScript on policy create/update, rather than per evaluation.

2017-06-16 18:10 UTC, pedroigor requested changes
Thanks for these changes.

Regarding the ```ScriptingSPI```, here is a branch with some initial changes [1] to get it working with the ```JSPolicyProvider```.

I think you can adapt your code to also use the ```ScriptingSPI``` and maybe have there what you did around pre-compiled scripts.

What do you say ?

[1] https://github.com/pedroigor/keycloak/commit/0b5e6b0d497a596fa24e56f367037ed60a716b78

2017-06-16 18:26 UTC, pedroigor commented
@janslow , I've created https://issues.jboss.org/browse/KEYCLOAK-5072 as a umbrella for all changes we are discussing.

2017-06-16 18:33 UTC, pedroigor requested changes

2017-06-16 18:33 UTC, pedroigor commented on authz/policy/common/src/main/java/org/keycloak/authorization/policy/provider/js/JSPolicyProviderFactory.java
> +    private Map<String, CompiledScript> compiled = Collections.synchronizedMap(new HashMap<>());
We can probably use a simple LRU map to cache entries. Where the number of cached entries can be defined by users.

There is a simple LRU map implementation we are already using in other places, we can probably re-use the same code here.

2017-06-16 20:36 UTC, janslow commented
Sure, I'll rebase on your branch.

2017-06-16 20:39 UTC, janslow commented on authz/policy/common/src/main/java/org/keycloak/authorization/policy/provider/js/JSPolicyProviderFactory.java
> +    private Map<String, CompiledScript> compiled = Collections.synchronizedMap(new HashMap<>());
Could you point me at the LRU implementation? I couldn't find it.

2017-06-19 16:46 UTC, janslow commented
I've reapplied my changes on top of your branch.

Originally, the `JSPolicyProvider` was evaluating the JavaScript twice, so I extracted a `EvaluatableScriptAdapter` (which can evaluate a script with some custom bindings), which is used by the JSPolicyProvider and DefaultScriptingProvider (to convert into an `InvocableScriptAdapter`).

I haven't solved the issue of tracking `ScriptModel`s in the `DefaultScriptingProvider`, as that may start to raise concurrency issues. Nashorn's `ScriptEngine` and `CompiledScript` are [thread-safe](https://stackoverflow.com/questions/30140103/should-i-use-a-separate-scriptengine-and-compiledscript-instances-per-each-threa/30159424#30159424), whilst `Bindings` isn't, so when the `ScriptEngine` is associated with a `Bindings`, it is no longer thread safe. This could be avoided by using [something like this](https://stackoverflow.com/a/36020936), but that would involve more Nashorn specific code.

2017-06-20 11:36 UTC, pedroigor commented
Regarding the issue you mentioned, I think we don't need to worry about it and just leave as it is. So we handle bindings accordingly within the new code you added to policy evaluation.

Will merge this PR today.

2017-06-20 11:36 UTC, pedroigor approved these changes

2017-06-20 18:11 UTC, merged

2017-06-20 20:14 UTC, janslow commented
That's great, thanks!