KEYCLOAK-5186 createUser: set federationLink
keycloak/keycloak pull request #4316
Opened 2017-07-13 07:32 UTC by wvdhaute

2017-07-13 08:09 UTC, stianst commented
Please add tests

2017-07-13 10:57 UTC, stianst commented
This is not how we tests things in Keycloak. Please write proper functional tests instead of mocks.

2017-07-13 10:57 UTC, stianst commented
https://github.com/keycloak/keycloak/blob/master/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/UserTest.java

2017-08-15 07:00 UTC, stianst requested changes

2017-08-15 07:00 UTC, stianst commented on testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/AbstractAdminTest.java
> +        // add dummy federation provider
Don't add a dummy federation provider here as it affects a large amount of other tests. Use the admin client in the one test you need it in to add it

2017-08-22 05:17 UTC, stianst requested changes
DummyUserFederationProviderFactory is already part of testsuite-providers which is added to the server. There's no need to add additional service definition file. Also don't add the provider in AbstractAdminTest as that will affect many tests that don't need it. Use the adminClient to add it where needed.

2017-08-30 06:17 UTC, stianst commented
@wvdhaute are you able to do the requested changes?

2017-08-30 07:22 UTC, wvdhaute commented
@stianst sorry, had some time off.
Just rebased and squashed an update for the test. Should be ok now

2017-08-31 04:07 UTC, stianst approved these changes

2017-08-31 04:07 UTC, stianst commented
Thanks

2017-08-31 04:07 UTC, merged