KEYCLOAK-5162: Adding indices to speed up event queries
keycloak/keycloak pull request #4394
Opened 2017-08-17 14:52 UTC by mariapavlova

2017-08-18 08:40 UTC, mariapavlova commented
We would like to have the indices created concurrently, otherwise updates are taking a long time to complete. Please advise

2017-08-18 11:57 UTC, stianst commented
What do you mean by "indices created concurrently"?

2017-08-18 15:12 UTC, mariapavlova commented
I meant something like this "CREATE INDEX CONCURRENTLY idx_event_entity_type ON event_entity (type);" as described in https://issues.jboss.org/browse/KEYCLOAK-5162

2017-08-23 14:08 UTC, hmlnarik requested changes
I don't think we should have index for each of the columns. This would be counterproductive, the writes into this - potentially heavy loaded - table would be too expensive. It certainly makes sense to have events indexed by time. What are your use cases, what do you usually filter by?

2017-08-23 14:08 UTC, hmlnarik commented on model/jpa/src/main/resources/META-INF/jpa-changelog-3.3.0.xml
> +    <changeSet author="maria.pavlova@quest.com" id="3.3.0">
Id has to be unique, set it to e.g. "3.3.0-index-event"

2017-09-18 16:33 UTC, mariapavlova commented
Thank you, can you please take a look at the ticket mentioned above? the use cases described there in details.

2017-09-26 11:39 UTC, stianst commented
3.3 has now been released so this has to be added to 3.4 changelog. The ID also has to be unique as Hynek mentions.

@hmlnarik we support searching events based on all columns this PR adds indexes for so the indexes make sense to me. Can you comment?

2017-09-27 09:57 UTC, hmlnarik commented
@stianst I see. In that case we should limit the max_results as we do now. 

Looking at the code, filtering mandates having realm ID. The indices hence have to be composite ones, having realm ID as the first component. Otherwise we'll be getting into similar performance troubles with multiple realms.

My other concern is regarding startup time should this PR be merged. For fresh installation, there is no issue. In existing installations, building the indices can easily take tens of minutes which will timeout Keycloak startup (see comments on the JIRA). The only way I can see this PR merged would be:

1. Either the PR would contain database-specific commands for all supported databases protected by preconditions (CREATE INDEX CONCURRENTLY for Postgres, CREATE INDEX xyz ONLINE for Oracle, CREATE INDEX xy LOCK NONE for mysql, ALTER INDEX xyz REBUILD WITH (ONLINE = ON) for myssql),
2. Or have a migration guide stating that the if there is already an existing database, the DBA has to apply the changeset manually, otherwise timeouts can occur.

@stianst WDYT?

2017-10-02 12:35 UTC, stianst commented
I really don't like the idea of requiring manual steps to upgrade the DB. So option 1 is the only way to go IMO.

2018-02-02 11:47 UTC, closed without merging

2019-12-18 14:17 UTC, hmlnarik commented
Related PR: #6324