Fix for Oracle null value when having an empty String as attribute value
keycloak/keycloak pull request #4406
Opened 2017-08-21 14:09 UTC by filipelautert

Oracle don't have empty strings: empty strings are handled as null. So if you set one value to an empty string, when you select it you will get null. Due to that we need to add this check or we will get a null pointer down this method on applications running on oracle backend.

Sample test:
update USER_ATTRIBUTE set value = '' where id = '145d02c2-111e-4fa4-8e5d-fa4970cb7010';
select 1 from USER_ATTRIBUTE where value = '' and id = '145d02c2-111e-4fa4-8e5d-fa4970cb7010'; -- returns nothing
select 1 from USER_ATTRIBUTE where value is null  and id = '145d02c2-111e-4fa4-8e5d-fa4970cb7010'; -- returns 1

2017-08-21 14:28 UTC, stianst commented
Can you add a test for this please?

2017-08-21 16:46 UTC, filipelautert commented
Sure. Just to be sure, should the test be created at testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/OidcUserAttributeMapperTest.java ?

2017-08-22 06:22 UTC, stianst commented
Wouldn't OIDCProtocolMappersTest be better?

2017-08-23 20:15 UTC, filipelautert commented
Values tests added to existing tests. The problem is that the issue just triggers when using an Oracle database, and by default tests are run against h2. Anyway tests are there now :)

2017-08-24 11:47 UTC, stianst commented on testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/OIDCProtocolMappersTest.java
> +            assertNotNull(idToken.getOtherClaims().get("null"));
Shouldn't this be null?

2017-08-24 11:55 UTC, filipelautert commented on testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/OIDCProtocolMappersTest.java
> +            assertNotNull(idToken.getOtherClaims().get("null"));
Sorry, still not finished yet. It is retuning a string containing the word "null". I've changed it to hamcrest matcher isEmpty() and discovered that - working to fix it .

2017-08-25 06:32 UTC, stianst requested changes
Claim should be null or non-existent if value is null

2017-08-25 16:26 UTC, filipelautert commented
So the main trick for the "null" string was on UserRepresentation. In my commit I choose to use an empty ArrayList when we it's requested to add null values. The other option would be to return and not add the value to the map, but in this case we would also need to check if the value already exists there and remove it.
In fact I already had seen this happening before: creating/updating an user with a null attribute using the rest api returned the "null" string to this attribute later... so it's a "plus" for this merge request.

2017-08-30 06:19 UTC, stianst requested changes

2017-08-30 06:19 UTC, stianst commented on testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/OIDCProtocolMappersTest.java
> +            //assertThat(((String)idToken.getOtherClaims().get("empty")), isEmptyString());
Remove rather than comment out if these are not going to be tested

2017-08-30 06:19 UTC, stianst commented on testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/OIDCProtocolMappersTest.java
> +            assertThat((empty == null ? null : (String) empty), isEmptyOrNullString());
Why isEmptyOrNullString? Should it not be just empty string?

2017-08-30 06:19 UTC, stianst commented on testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/OIDCProtocolMappersTest.java
> +            assertThat((nulll == null ? null : (String) nulll), isEmptyOrNullString());
Why isEmptyOrNullString? Should it not be just null?

2017-08-30 15:35 UTC, filipelautert commented
Changes applied as requested.

2017-08-31 04:09 UTC, merged