KEYCLOAK-5416 Migration from 3.2.1 to 3.3.0 doesn't work on MSSQL due to constraint violation
keycloak/keycloak pull request #4461
Opened 2017-09-06 16:08 UTC by ouzklcn

… to constraint violation

2017-09-13 07:39 UTC, hmlnarik requested changes
Thanks for the fix. As it is now, it may fail on existing installations where application of 3.2.0-fix has already succeeded. Please adjust as per inline comment.

2017-09-13 07:39 UTC, hmlnarik commented on model/jpa/src/main/resources/META-INF/jpa-changelog-3.2.0.xml
>          </preConditions>
Id of this changeset (line 27) has to be changed to e.g. `3.2.0-fix-with-keycloak-5416`, and the following precondition needs to be added into `<preConditions>` tag:
```xml
<not>
    <changeSetExecuted id="3.2.0-fix" author="keycloak" changeLogFile="META-INF/jpa-changelog-3.2.0.xml"/>
</not>
```

2017-09-13 09:04 UTC, hmlnarik commented
@ouzklcn Thanks, that looks good. Could you please squash the changes into a single commit?

2017-09-14 09:48 UTC, hmlnarik commented
I've checked the new commit, and on mysql the new changeset sadly fails:
```
[...]
Caused by: java.sql.SQLException: Cannot drop index 'IDX_CLIENT_INIT_ACC_REALM': needed in a foreign key constraint
```

So instead of changing existing changeset, what is needed here is to have changeset specific to mssql:
- leave the original changeset, only add a precondition `<not><dbms type="mssql"/></not>`
- copy it to another changeset with the changes from this PR and with precondition `<dbms type="mssql"/>`

2017-09-14 11:38 UTC, hmlnarik commented
Thanks, I'm going to check it now. Hopefully all DBs would be happy now.

2017-09-14 12:23 UTC, hmlnarik commented
All DBs seem happy with the current version.
@ouzklcn Thank you for the PR.
@stianst This PR can be merged.

2017-09-15 07:40 UTC, stianst commented
Please send PR to 3.3.x branch as well.

2017-09-15 07:50 UTC, hmlnarik commented
PR for 3.3.x: https://github.com/keycloak/keycloak/pull/4479

2017-09-15 07:56 UTC, merged