[KEYCLOAK-4374] Support SAML 2.0 AttributeValue of type anyType and nil in Assertions
keycloak/keycloak pull request #4499
Opened 2017-09-25 14:01 UTC by pskopek

https://github.com/keycloak/keycloak/pull/4368

Fixing issue when SAML20 attribute "AttributeValue" is of type "anyType". On the way I have added handling of nil attribute as well.
Commit contains tests to check the handling.

2017-09-25 15:31 UTC, hmlnarik requested changes
Please see inline comments.

2017-09-25 15:31 UTC, hmlnarik commented on saml-core/src/test/java/org/keycloak/saml/processing/core/parsers/saml/SAMLParserTest.java
> +                    assertTrue(attrTypeStatement, attr.getAttributeValue().get(0) instanceof String);
`Assert.assertThat(attrTypeStatement, attr.getAttributeValue().get(0), Matchers.isA(String))` gives better info on failure.

2017-09-25 15:31 UTC, hmlnarik commented on saml-core/src/test/java/org/keycloak/saml/processing/core/parsers/saml/SAMLParserTest.java
> +                    assertTrue(attrValueStatement, value.contains("<n3:stuff xmlns:n3=\"ftp://example.org\">00DD0000000F7L5</n3:stuff>"));
Similarly, to get better output, use `Assert.assertThat(attrValueStatement, value, containsString("..."));`

2017-09-25 15:31 UTC, hmlnarik commented on saml-core/src/main/java/org/keycloak/saml/processing/core/parsers/util/SAMLParserUtil.java
> +                } while (xmlEventReader.hasNext() && !endTagReached);
Would the following xml snippet be processed correctly?
```xml
<status>
  <code>
    <status>XYZ</status>
  <code>
</status>
```
Please add a testcase for that.

2017-09-27 15:40 UTC, pskopek commented
@hmlnarik all your concerns fixed. Can you review again, please?

2017-09-27 19:40 UTC, hmlnarik approved these changes
Thanks, looks good to me.
@stianst This PR can be merged.

2017-09-28 08:39 UTC, merged