KEYCLOAK-5298: Enable autoescaping in Freemarker
keycloak/keycloak pull request #4561
Opened 2017-10-13 18:32 UTC by ssilvert

Note that we are upgrading Freemarker to version "2.3.26-incubating".  This only denotes that the project is moved to the Apache incubator.  It is the official 2.3.26 release.

2017-10-16 12:20 UTC, stianst commented
Looks like there was some real tests failures here, but rescheduled to see.

2017-10-16 12:37 UTC, ssilvert commented
I'm guessing that the escaped HTML is not expected by some of these tests.  Planning to work on that today.

2017-10-16 12:49 UTC, stianst requested changes
Shouldn't URLs be escaped? Referrer URI for instance is passed by query parameter is there a chance that can be exploited?

We also need to have the new version available in Brew otherwise it'll block RH-SSO builds.

2017-10-16 16:51 UTC, ssilvert commented
Referrer URI does get escaped.  My first test was using the referrer URI exploit that we originally patched with ?html.  Now you can't use ?html any more because everything is automatically escaped.

2017-10-17 02:22 UTC, ssilvert commented
So now the tests all pass but I'm not 100% certain that I've fixed them correctly.  I need to determine for sure if changing the test was the right thing to do.

2017-10-17 06:19 UTC, stianst commented
You're explicitly not escaping URLs for example:
https://github.com/keycloak/keycloak/pull/4561/files#diff-d0223180521470c06fb57bd068d3c81fR106

That was what I was wondering about, not the removal of ?html

2017-10-17 12:08 UTC, ssilvert commented
That's just the text.  The href is still escaped.  The text says "<< Back to Application".  If you escape that then the "<<" looks funny on the screen.  For any text that comes from a message bundle and contains "<", I assume it is safe and put in a ?no_esc.

2017-10-17 12:11 UTC, ssilvert commented
I did find one instance where a link is passed in as a param to the message bundle.  If that link is unsafe then we have a problem.  I need to hunt that one down and ask you about it.

2017-10-17 18:45 UTC, stianst commented
Strange that << isn't escaped properly by FreeMarker, would expect it to be escaped to &#60;. Would it make sense to change the message bundle to '&#60;' rather than marking it as unescaped?

2017-10-17 18:46 UTC, stianst commented
For the link in message bundle. Doesn't it work if the message is escaped? This stuff seems a bit weird, especially since you had to do the hacks in the test.

2017-10-23 16:03 UTC, merged