KEYCLOAK-5230 Add indices to FED_* tables
keycloak/keycloak pull request #4621
Opened 2017-10-27 08:27 UTC by hmlnarik

2017-10-27 08:28 UTC, hmlnarik commented
@vramik Could you please check this PR on supported DBs?

2017-10-27 10:14 UTC, vramik requested changes
There are too long identifiers for Oracle DB

2017-10-27 10:14 UTC, vramik commented on model/jpa/src/main/resources/META-INF/jpa-changelog-3.4.0.xml
> +        <createIndex tableName="FED_USER_GROUP_MEMBERSHIP" indexName="IDX_FED_USER_GROUP_MEMBERSHIP_RU">
indexName IDX_FED_USER_GROUP_MEMBERSHIP_RU is too long on Oracle DB, the limit is 30

2017-10-27 10:14 UTC, vramik commented on model/jpa/src/main/resources/META-INF/jpa-changelog-3.4.0.xml
> +        <createIndex tableName="FED_USER_REQUIRED_ACTION" indexName="IDX_FED_USER_REQUIRED_ACTION_RU">
indexName IDX_FED_USER_REQUIRED_ACTION_RU is too long on Oracle DB, the limit is 30

2017-10-27 10:44 UTC, hmlnarik commented
@vramik Thanks, this should be fixed in the new commit, could you please recheck?

2017-10-30 12:35 UTC, vramik commented
@hmlnarik tested and passed, thank you.

2017-10-31 07:48 UTC, hmlnarik commented
@vramik Thank for checking

2017-10-31 07:48 UTC, merged