KEYCLOAK-5352 Basic Auth fails if password contains a ':'
keycloak/keycloak pull request #4639
Opened 2017-11-07 03:16 UTC by ricehull

Modified 3 source files:
./adapters/oidc/adapter-core/src/main/java/org/keycloak/adapters/BasicAuthRequestAuthenticator.java
./core/src/main/java/org/keycloak/util/BasicAuthHelper.java
./services/src/main/java/org/keycloak/protocol/saml/profile/ecp/authenticator/HttpBasicAuthenticator.java

2017-11-07 09:25 UTC, stianst requested changes

2017-11-07 09:25 UTC, stianst commented on adapters/oidc/adapter-core/src/main/java/org/keycloak/adapters/BasicAuthRequestAuthenticator.java
> +            log.debug("user: " + user);
This is not good logging. Please use a sensible message, use a single log entry and make it trace

2017-11-07 09:25 UTC, stianst commented on services/src/main/java/org/keycloak/protocol/saml/profile/ecp/authenticator/HttpBasicAuthenticator.java
> +            log.debug("user: " + user);
See earlier comment on logging

2017-11-08 05:34 UTC, ricehull reviewed
Done for the log.

2017-11-09 06:18 UTC, stianst commented
Thinking about it some more we shouldn't log user passwords. It would probably be best to just remove the logging.

2017-11-09 06:32 UTC, ricehull commented
I thought this is a debug log, so I logged the user name and password, But I think your comments is more resonable, we can remove the log of the modification.

2017-11-09 07:30 UTC, ricehull commented
It's failed as yesterday, looks nothing to do with my change, I just remove the logs for the methods.

2017-11-09 12:56 UTC, stianst commented
The failing test is one we've had problems with so it's not your fault. Thanks for the fix

2017-11-09 12:56 UTC, merged

2017-11-09 15:02 UTC, stianst commented
Looks like some tests are failing due to this.. Specifically UndertowDemoFilterServletAdapterTest.testBasicAuth which isn't ran on Travis for some reason.

2017-11-09 15:22 UTC, stianst commented
Never mind. I've tried to run the affected test with the last commit before yours and it's broken there as well. So just happen to be broken at the same time.