[KEYCLOAK-2052] Allows independently set timeouts for e-mail verification link and rest e.g. forgot password link
keycloak/keycloak pull request #4676
Opened 2017-11-11 23:12 UTC by abstractj

2017-11-13 13:45 UTC, hmlnarik requested changes
Thanks for the changes, overall looks good to me, please only fix few nits and squash to single commit.

2017-11-13 13:45 UTC, hmlnarik commented on testsuite/integration-arquillian/tests/other/console/src/test/java/org/keycloak/testsuite/console/realm/TokensTest.java
> +        assertTrue("Action Token attributes list should contain 2 items", userActionTokens.size() == 2);
Better use
```java
assertThat("Action Token attributes list should contain 2 items", userActionTokens, Matchers.hasSize(2));
```
as it gives more descriptive error messages on assertion failure.

2017-11-13 13:45 UTC, hmlnarik commented on testsuite/integration-arquillian/tests/other/console/src/test/java/org/keycloak/testsuite/console/realm/TokensTest.java
> +        assertEquals("VerifyEmailActionToken expected to be propagated",
```java
assertThat(userActionTokens, Matchers.hasEntry(VerifyEmailActionToken.TOKEN_TYPE), Long.toString(TimeUnit.DAYS.toSeconds(TIMEOUT)));
assertThat(userActionTokens, Matchers.hasEntry(ResetCredentialsActionToken.TOKEN_TYPE), Long.toString(TimeUnit.HOURS.toSeconds(TIMEOUT)));
```
that allows removing the following two asserts.

2017-11-13 13:45 UTC, hmlnarik commented on themes/src/main/resources/theme/base/admin/messages/admin-messages_en.properties
> +action-token-generated-by-user.idp-verify-account-via-email=Identity Provider E-mail Verification
Identity Provider *Account* e-mail Verification ?

2017-11-13 19:22 UTC, abstractj commented
@hmlnarik I did all the changes you mentioned with some minor changes to what you suggested. I only disagree with a single "nit" :) Define *Identity Provider Account e-mail Verification*, instead of something like *IdP Account E-mail Verification*. But I did the change anyways.

I understand the idea of something user-friendly, at the same time, people are familiar with the term IdP. Also, this is gonna make our UI component huge and not perfectly aligned with other selects. See the screenshot:

![](https://i.imgur.com/HyJDeMr.png)

2017-11-13 21:15 UTC, hmlnarik commented
@abstractj ack, IdP makes sense and it would make the UI cleaner. Go for it :-) And thanks for the changes!

2017-11-14 08:15 UTC, hmlnarik approved these changes

2017-11-14 08:19 UTC, merged