KEYCLOAK-5830 Automated stress test
keycloak/keycloak pull request #4685
Opened 2017-11-13 19:26 UTC by tkyjovsk

Added a `stress-test-loop.sh` script.

2017-11-16 13:39 UTC, hmlnarik requested changes
Please remove so many empty lines in the beginning and end of every output.

Furthermore, this seems like having O(n) complexity with most likely no issue found in the first rounds. Have you considered O(log N) algorithm (for example bisection) with initial parameters considered safely within and beyond the actual performance, and in e.g. 10 rounds getting closer and closer to the actual maximal number of users?

2017-11-16 13:39 UTC, hmlnarik commented on testsuite/performance/stress-test-loop.sh
> +if [ -z $RUN_USERS_INITIAL ]; then RUN_USERS_INITIAL=60; fi
Can be replaced with
```bash
RUN_USERS_INITIAL=${RUN_USERS_INITIAL:-60}
```

2017-11-16 13:39 UTC, hmlnarik commented on testsuite/performance/stress-test-loop.sh
> +    eval "$TEST_COMMAND"
Lines 24-26 can be replaced with
```bash
if ! $TEST_COMMAND; then
```

2017-11-16 16:34 UTC, tkyjovsk commented
O(log n) would be nice to have but I'm not sure if it is a good idea to put the system under such extreme load spikes which would result from first rounds of the bisection algorithm. This way the load is increased at least somewhat gradually which reduces the risk of "breaking" something in the server.

2017-11-20 08:28 UTC, hmlnarik commented
I don't understand the last comment. Stress test is exactly about finding out the boundary. Should we be afraid to reach it?

2017-11-24 11:47 UTC, tkyjovsk commented
If we overstress the server too much in the initial iteration it may break something and subsequent iteration which would pass under normal circumstances, could fail. Leading to incorrect result.

2017-11-24 14:43 UTC, hmlnarik commented
You need to rerun the *whole* test in clean installation for every new parameterization anyway, otherwise the previous runs could interfere, leading to incorrect results.

2018-03-14 14:12 UTC, stianst commented
@tkyjovsk @hmlnarik bump

2018-03-26 14:57 UTC, tkyjovsk commented
Closing as outdated. Will create a new PR shorthly.

2018-03-26 14:57 UTC, closed without merging