KEYCLOAK-5857 Supports PBKDF2 hashes with different key size
keycloak/keycloak pull request #4697
Opened 2017-11-15 10:04 UTC by trecloux

The original use case is to support imported credentials with a different key size without
implementing a totally new PasswordHashProvider

2017-11-15 11:59 UTC, stianst commented
Thanks for your PR. We're past feature freeze for 3.x and are not able to review or accept any more features/enhancements until we start development for 4.x.

2018-01-16 11:52 UTC, stianst requested changes
The provided test is a simple unit tests which doesn't mean it'll actually work properly. Please add a test-case to the existing functional test PasswordHashingTest and remove the unit test.

2018-01-22 15:54 UTC, trecloux commented
@stianst I pushed an updated version, with a new test in `PasswordHashingTest`.

2018-01-24 08:02 UTC, stianst approved these changes

2018-01-24 08:02 UTC, stianst commented
Nice, thanks for updating the tests

2018-01-24 08:02 UTC, merged

2020-02-20 17:34 UTC, JoelBennett commented
I realize I'm a little late to the party here, but is it possible to specify the key size when importing users via the .json importer?  Attempting to specify either `keySize` or `derivedKeySize` in the `credentials` object within the JSON causes the importer to fail with error such as:

```
Unrecognized field "derivedKeySize" (class org.keycloak.representations.idm.CredentialRepresentation), not marked as ignorable
``

Am I just using the wrong field name in the JSON?