Add impersonator to user session note
keycloak/keycloak pull request #4813
Opened 2017-12-06 20:23 UTC by foo4u

Allow attribute mappers to expose the impersonator to clients.

2017-12-07 09:57 UTC, stianst commented
Thanks. We can't merge this until we get started on 4.x as we've been in feature freeze for 3.x a while now. We'd also need some tests added. Should be possible to extend on the existing impersonation test and add one that adds a protocol mapper with the above. Maybe it would be worth having it on by default or at least having a new impersonator mapper to make it easy to add?

2018-01-16 12:48 UTC, stianst commented
Changes looks OK to me, but we need the tests to be updated (I believe it's ImpersonationTest). 

@mposolda @hmlnarik what do you guys think about this approach?

2018-01-16 14:20 UTC, stianst requested changes
Tests and docs missing

2018-01-17 02:23 UTC, foo4u commented
If the approach is fine I’ll take a shot at tests. I was originally just trying to show a common solution for both OIDC & SAML clients.

2018-01-17 15:01 UTC, stianst commented
@mposolda @hmlnarik bump

2018-01-25 19:29 UTC, stianst commented
No feedback from @mposolda or @hmlnarik. However, adding this info to the user session is really the only way so I'm fine with this.

What I'd like to see is a new impersonation protocol mapper for OIDC and SAML to make it easy to add this info to the token. We also need some tests for it. Finally a note about the protocol mappers in http://www.keycloak.org/docs/latest/server_admin/index.html#impersonation would be good as well.

2018-01-26 10:36 UTC, mposolda commented
@stianst Sorry, I somehow missed this. Have lots of github notifications and this one was lost. Should improve the mail filter likely...

I agree with the approach in the PR.

Not sure if need new protocolMapper implementation, probably not. We may just need to add new builtin mappers of type UserSessionNote, which will be preconfigured to use the "impersonated" and "impersonator" notes to the token. It will be builtin (preconfigured) mapper, but not added to client by default. We already have similar thing for Kerberos delegation credential (Builtin mapper "gss delegation credential" documented here:  http://www.keycloak.org/docs/latest/server_admin/index.html#credential-delegation ).

2018-01-31 05:27 UTC, stianst commented
@mposolda that sounds better, I wasn't really aware of that stuff.

2018-02-02 08:15 UTC, stianst commented
Closing due to lack of feedback. Please reopen once comments have been addressed.

2018-02-02 08:15 UTC, closed without merging