Update changes on sssd.conf file to make script idempotent
keycloak/keycloak pull request #4843
Opened 2017-12-13 11:17 UTC by morenod

When executing script more than one time, consecutive lines are added to the sssd.conf file, and sssd fails to start

2017-12-14 12:59 UTC, stianst commented
Please create a JIRA

2017-12-14 13:10 UTC, abstractj commented
@morenod  +1 for Jira, please link your PR and I will look into that.

2018-01-31 07:22 UTC, stianst commented
https://issues.jboss.org/browse/KEYCLOAK-6041

2018-01-31 16:41 UTC, abstractj requested changes
@morenod The change looks good, just needs a rebase.

2018-01-31 17:01 UTC, morenod commented
@abstractj rebase done

2018-01-31 18:47 UTC, abstractj submitted a review, later dismissed

2018-01-31 19:01 UTC, abstractj commented
@stianst approved but can't merge. Probably because it requires another rebase after Pedro's changes.

2018-02-01 08:24 UTC, morenod commented
@abstractj rebased again

2018-02-06 11:07 UTC, abstractj commented
Rebased here https://github.com/keycloak/keycloak/pull/4973 to merge

2018-02-06 11:07 UTC, closed without merging