KEYCLOAK-5968 Move configuration of Infinispan server from Dockerfile to maven
keycloak/keycloak pull request #4908
Opened 2018-01-09 11:48 UTC by tkyjovsk

2018-01-17 08:41 UTC, hmlnarik requested changes
Overall lgtm, the way infinispan servers are prepared could be improved though.

2018-01-17 08:41 UTC, hmlnarik commented on testsuite/performance/infinispan/pom.xml
> +        <infinispan.version>8.2.8.Final</infinispan.version>
Can this use ${infinispan.version} from https://github.com/keycloak/keycloak/blob/master/pom.xml#L68?

2018-01-17 08:41 UTC, hmlnarik commented on testsuite/performance/infinispan/pom.xml
> +                                    <outputDirectory>${project.build.directory}/dc1</outputDirectory>
Currently this extracts 2 infinispan servers into two different locations (dc1, dc2) and then updates clustered.xml just in the same way. Can you update it to extract it just once instead and then work on configuration clustered-dc*X*.xml instead, and run the appropriate configuration file in docker?

2018-02-08 22:06 UTC, tkyjovsk commented
I made changes based on previous comments. Infinispan servers in cross-DC scenario start up fine. I haven't tested the whole cross-dc deployment because of this blocker: KEYCLOAK-6411.

2018-02-12 13:52 UTC, tkyjovsk commented
I tested this using workaround for KEYCLOAK-6411. (mariadb 10.3.3 instead of 10.3.4)

2018-02-14 15:48 UTC, hmlnarik approved these changes

2018-02-14 15:48 UTC, merged