KEYCLOAK-6222 Check syntax for errors on ScriptBasedOIDCProtocolMapper validation
keycloak/keycloak pull request #4916
Opened 2018-01-12 12:07 UTC by thomasdarimont

We now explicitly check for syntax errors during validation of ScriptBasedOIDCProtocolMappers.

2018-01-30 17:41 UTC, abstractj commented
@thomasdarimont sorry about the late feedback. I believe we need to do the same for the Script Execution under the Authentication Flows?

2018-01-31 12:57 UTC, thomasdarimont commented
@abstractj I just rebased this PR to current master. 

Yes it would be nice to have that as well for Script based authenticators but I couldn't find an API that allows to validate an authenticator config. Would be great to have something similar to  ` org.keycloak.protocol.ProtocolMapper#validateConfig` for authenticators.

2018-01-31 14:20 UTC, abstractj requested changes
@thomasdarimont the PR looks good to me. But I would appreciate if you remove the TODOs and convert them into Jiras with a detailed description. Otherwise this can be easily lost.

Despite this small change, the PR looks good.

2018-01-31 14:43 UTC, thomasdarimont commented
I created https://issues.jboss.org/browse/KEYCLOAK-6443 to capture the essence of the TODOs

2018-01-31 14:50 UTC, thomasdarimont commented
Removed the //TODOs as requested

2018-01-31 19:03 UTC, abstractj approved these changes

2018-02-02 07:28 UTC, merged