KEYCLOAK-4315 Remove dead/duplicate SAML classes
keycloak/keycloak pull request #4931
Opened 2018-01-23 11:25 UTC by hmlnarik

2018-01-23 11:27 UTC, hmlnarik commented on saml-core/src/test/java/org/keycloak/saml/common/util/StringUtilTest.java
> -/*
This test has been removed since it only tests removed method `getSystemPropertyAsString`

2018-02-05 12:51 UTC, pskopek requested changes

2018-02-05 12:51 UTC, pskopek commented on saml-core/src/main/java/org/keycloak/saml/common/util/SecurityActions.java
Each public static method call running privileged code should be guarded via checkPermission.
This applies to all methods in this class.

2018-02-13 07:21 UTC, pskopek approved these changes

2018-02-13 14:39 UTC, mposolda approved these changes

2018-02-13 14:41 UTC, merged