[KEYCLOAK-6111] 'Override User-Initiated Action Lifespan' admin GUI can break realm configuration
keycloak/keycloak pull request #4933
Opened 2018-01-24 14:39 UTC by abstractj

2018-02-02 11:58 UTC, hmlnarik requested changes
Thanks for the changes yet this fix should also add a filter - `entry.getValue()` should only pass when being non-null and a positive integer string (e.g. via some `static Pattern` field) at https://github.com/abstractj/keycloak/blob/03d0488335231a7e3ebf49b4bafae967844db128/model/jpa/src/main/java/org/keycloak/models/jpa/RealmAdapter.java#L483

2018-02-06 16:32 UTC, abstractj commented
@hmlnarik updated my PR with the checks at the filter you suggested. I didn't see any good reason for checking negative values, the UI already validates it and we don't do the same for other fields, as far as I know.

2018-02-09 07:10 UTC, hmlnarik submitted a review, later dismissed
@abstractj The check for non-null is good enough. Reason for checking for non-sane values is that it is generally not only UI accessing the admin endpoints so it may happen that an invalid value is entered e.g. via CLI. But I guess that's a minor thing now so let's live with the current solution and see if anyone objects.

2018-02-09 08:53 UTC, hmlnarik approved these changes

2018-02-09 08:57 UTC, merged