Fix Locale Negotiation for omitted Country Code
keycloak/keycloak pull request #4958
Opened 2018-02-01 15:17 UTC by iilei

This fixes the following scenario:

If the request Header asks for a language without providing a Country Code whilst the theme provides a language with a specific Country Code no match is found.
([Failing test case](https://github.com/iilei/keycloak/commit/a8b6e82291c31d6198ce7866400d03b5e52b4063#diff-e98fd037c6e3c3f60346c60831adbcf9R45))

Thanks :)

2018-02-02 08:02 UTC, stianst reviewed
Can you provide an example when this actually happens? Please create a JIRA and describe exactly when this happens and what the changes you are doing actually does.

For the implementation please don't refactor the code and extract into yet another utility class. LocaleHelper already is a Locale helper class and we don't need two for functionality like this. Further, this refactoring makes it very hard to see what changes you are actually doing here.

We do also not rely on unit tests for testing. I would like to see this being tested in one of the existing functional tests instead.

2018-02-02 08:16 UTC, stianst requested changes
See comment

2018-02-02 11:38 UTC, iilei commented
Okay I have created an issue; #KEYCLOAK-6461 
Amendments to the pr will follow. Thanks

2018-02-02 11:59 UTC, stianst commented
Not sure about this change to be honest. The user can configure the browser to include a list of locales in preferred order. So a user should send a request like (Accept: en-GB, en, en-US).

If the user sends pt for instance they don't want pt-BR returned.

I would actually argue that we should remove the current behaviour that matches requested pt-BR to pt. It should be up to the user to decide what they want and we shouldn't override that behaviour.

2018-02-02 15:45 UTC, iilei commented
I doubt that a user has in depth knowledge of locale matching. Therefore I would not agree that, if the accept header says 'pt' the user would not be okay with receiving 'pt-BR' if that would be the only offered variant of the Portuguese language.

Rather, I'd say Portuguese is better than some language the user doesn't know at all.
There are just country specific details which might look like misspelled words but at least a user would be able to understand the language.

2018-02-05 05:00 UTC, stianst commented
Please send a mail to keycloak-dev to discuss further

2018-02-05 15:03 UTC, iilei commented
Done.

Still I' like to refer to [RFC 4647 - Matching of Language Tags](https://www.ietf.org/rfc/rfc4647.txt) as it could possibly help to find a common understanding:

>    In the lookup scheme, the language range is progressively truncated
>    from the end until a matching language tag is located.  Single letter
>    or digit subtags (including both the letter 'x', which introduces
>    private-use sequences, and the subtags that introduce extensions) are
>    removed at the same time as their closest trailing subtag.  For
>    example, starting with the range "zh-Hant-CN-x-private1-private2"
>    (Chinese, Traditional script, China, two private-use tags) the lookup
>    progressively searches for content as shown below:
> 
>    Example of a Lookup Fallback Pattern
> 
>    Range to match: zh-Hant-CN-x-private1-private2
>    1. zh-Hant-CN-x-private1-private2
>    2. zh-Hant-CN-x-private1
>    3. zh-Hant-CN
>    4. zh-Hant
>    5. zh
>    6. (default)

2018-02-05 18:18 UTC, stianst commented
You've convinced me with your last comment. Thanks.

2018-02-05 18:18 UTC, stianst submitted a review, later dismissed

2018-02-05 18:18 UTC, stianst commented
Will leave it one day just to see if there's any comments on keycloak-dev ML, if not I'll merge this.

2018-02-05 20:36 UTC, iilei commented
👍  Thank you

2018-02-06 10:08 UTC, iilei commented
Just did a rebase with master -- sorry for messing with the review.

2018-02-06 11:45 UTC, stianst commented
Shouldn't it really first search all requested and all supported for an exact match. Then search without country?

2018-02-06 11:46 UTC, stianst commented
As in I'd expect at least two for loops ;)

2018-02-08 19:54 UTC, stianst commented
Ah, sorry missed the return on the exact match. Much better than my suggestion of two for loops. Thanks.

2018-02-08 19:54 UTC, stianst approved these changes

2018-02-08 19:55 UTC, merged

2018-02-08 20:11 UTC, iilei commented
:+1: