[KEYCLOAK-6301] Disable service account after disabling in Client
keycloak/keycloak pull request #4980
Opened 2018-02-07 15:07 UTC by douglaspalmer

2018-02-08 13:43 UTC, stianst commented
I can't see how this fixes the problem. This seems to only change the field of service account on the JSON returned.

What I think we need is that when someone changes the client to disabled we should disable the associated service account user. Then re-enable it if the client is re-enabled.

2018-02-08 13:44 UTC, stianst commented
We also need a test that gets a refresh token for the client, then disables the client, then tries to refresh the token.

2018-02-26 09:28 UTC, stianst requested changes
Looks good. One minor thing is to not use * in imports.

2018-02-26 09:28 UTC, stianst commented on services/src/main/java/org/keycloak/services/resources/admin/ClientResource.java
> +import org.keycloak.models.*;
Please don't use * in imports.

2018-02-26 20:24 UTC, douglaspalmer commented
Sorry, I’ll fix that, Intellij did it automatically and I accepted it.

Regards
Doug


> On Feb 26, 2018, at 1:28 AM, Stian Thorgersen <notifications@github.com> wrote:
> 
> @stianst requested changes on this pull request.
> 
> Looks good. One minor thing is to not use * in imports.
> 
> In services/src/main/java/org/keycloak/services/resources/admin/ClientResource.java <https://github.com/keycloak/keycloak/pull/4980#discussion_r170532868>:
> 
> > @@ -25,17 +25,7 @@
>  import org.keycloak.common.util.Time;
>  import org.keycloak.events.admin.OperationType;
>  import org.keycloak.events.admin.ResourceType;
> -import org.keycloak.models.AuthenticatedClientSessionModel;
> -import org.keycloak.models.ClientModel;
> -import org.keycloak.models.ClientTemplateModel;
> -import org.keycloak.models.Constants;
> -import org.keycloak.models.KeycloakSession;
> -import org.keycloak.models.ModelDuplicateException;
> -import org.keycloak.models.RealmModel;
> -import org.keycloak.models.RoleModel;
> -import org.keycloak.models.UserCredentialModel;
> -import org.keycloak.models.UserModel;
> -import org.keycloak.models.UserSessionModel;
> +import org.keycloak.models.*;
> Please don't use * in imports.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/keycloak/keycloak/pull/4980#pullrequestreview-99229789>, or mute the thread <https://github.com/notifications/unsubscribe-auth/AAnM8XuxMpK9qklL-hdYIqevFP6OEkScks5tYnkqgaJpZM4R82_l>.
>

2018-02-28 06:31 UTC, stianst approved these changes

2018-03-14 14:09 UTC, merged