[KEYCLOAK-6334] Minor typo: "read only" should be "read-only"
keycloak/keycloak pull request #4990
Opened 2018-02-09 23:29 UTC by abstractj

2018-02-12 07:29 UTC, stianst approved these changes

2018-02-16 09:13 UTC, hmlnarik commented
@abstractj The Travis failure is relevant, please fix also https://github.com/keycloak/keycloak/blob/master/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/kerberos/AbstractKerberosTest.java#L226

2018-02-19 08:32 UTC, stianst requested changes
Failing test needs fixing

2018-02-19 10:42 UTC, abstractj commented
@stianst all green now

2018-02-20 19:18 UTC, stianst approved these changes

2018-02-20 19:18 UTC, merged