KEYCLOAK-6622
keycloak/keycloak pull request #5037
Opened 2018-02-26 20:36 UTC by patriot1burke

2018-02-27 02:39 UTC, ssilvert requested changes
I marked a couple of lines where you need to move text to the message bundle.

Also wondering if you meant to leave so many console.log statements in there?

Only other thing I see is a few places where you used double equals instead of triple equals.  Probably best to change those but it's not a big deal.

2018-02-28 08:53 UTC, mposolda commented
I don't have any more concerns besides what Stan mentioned. For myself, I am adding approve.

2018-02-28 08:53 UTC, mposolda approved these changes

2018-02-28 13:46 UTC, ssilvert approved these changes

2018-02-28 13:47 UTC, merged