KEYCLOAK-6775 : fix french typos
keycloak/keycloak pull request #5045
Opened 2018-02-28 09:51 UTC by sebastienblanc

2018-02-28 16:10 UTC, gaetancollaud requested changes
minor mistake

2018-02-28 16:10 UTC, gaetancollaud commented on themes/src/main/resources-community/theme/base/account/messages/messages_fr.properties
> +totpScanBarcode=Scanner le code-barre ?
Seems like `code-barres` has an `s` => http://www.larousse.fr/dictionnaires/francais/code-barres_codes-barres/16884

2018-03-14 14:19 UTC, stianst commented
@sebastienblanc bump

2018-03-14 14:25 UTC, gaetancollaud approved these changes

2018-03-14 15:18 UTC, sebastienblanc commented
@stianst someone with reiew/merge rights can merge this, I can not do it myself, can you approve the PR ?

2018-03-14 20:13 UTC, stianst approved these changes

2018-03-14 20:13 UTC, merged