[KEYCLOAK-6147] Include Nonce in OIDC authentication
keycloak/keycloak pull request #5068
Opened 2018-03-08 17:28 UTC by jayblanc

Include Nonce in OIDC authentication request to avoid problem with FranceConnect

2018-03-19 07:07 UTC, mposolda requested changes
PR looks good. I just left one very minor comment here.

2018-03-19 07:07 UTC, mposolda commented on services/src/main/java/org/keycloak/broker/oidc/AbstractOAuth2IdentityProvider.java
> +        if (nonce != null) {
It couldn't happen that "nonce" will be null if I read correctly? Isn't this "if" check unecessary? Besides that, PR looks good to me.

2018-03-19 07:21 UTC, jayblanc commented
You're right, It is because I made a version that include checkox in the
Identity provider config and I downgrade to this simplest version for the
first PR letting this useless check on non null.
(In the case of the config, it could be null).
By the way, do you have any advice for testing the admin app config because
I also made the version that include config but I did'nt made the PR
because of missing testing) ?
Best regards, Jérôme.

Le lun. 19 mars 2018 à 08:07, Marek Posolda <notifications@github.com> a
écrit :

> *@mposolda* requested changes on this pull request.
>
> PR looks good. I just left one very minor comment here.
> ------------------------------
>
> In
> services/src/main/java/org/keycloak/broker/oidc/AbstractOAuth2IdentityProvider.java
> <https://github.com/keycloak/keycloak/pull/5068#discussion_r175344692>:
>
> > @@ -319,6 +320,16 @@ protected UriBuilder createAuthorizationUrl(AuthenticationRequest request) {
>          if (acr != null) {
>              uriBuilder.queryParam(OAuth2Constants.ACR_VALUES, acr);
>          }
> +
> +        String nonce = request.getAuthenticationSession().getClientNote(OIDCLoginProtocol.NONCE_PARAM);
> +        if (nonce == null || nonce.isEmpty()) {
> +            nonce = UUID.randomUUID().toString();
> +            request.getAuthenticationSession().setClientNote(OIDCLoginProtocol.NONCE_PARAM, nonce);
> +        }
> +        if (nonce != null) {
>
> It couldn't happen that "nonce" will be null if I read correctly? Isn't
> this "if" check unecessary? Besides that, PR looks good to me.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/keycloak/keycloak/pull/5068#pullrequestreview-104855810>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAHcUOCu62QTJl-PAc6v2tjFNdPxejGUks5tf1kigaJpZM4SjDRr>
> .
>

2018-03-19 18:29 UTC, mposolda commented
PR looks completely messed now. Could you just rebase from latest master and add just single commit with your change on top?

2018-03-19 21:33 UTC, jayblanc commented
I made a rebase but i don't know why it make all that mess !! I will make
it cleaner asap. sorry.

Le lun. 19 mars 2018 à 19:29, Marek Posolda <notifications@github.com> a
écrit :

> PR looks completely messed now. Could you just rebase from latest master
> and add just single commit with your change on top?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/keycloak/keycloak/pull/5068#issuecomment-374317864>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAHcUDRwuTxyBuBJ5C-R-RY_ahxdoi1iks5tf_kRgaJpZM4SjDRr>
> .
>

2018-03-19 21:54 UTC, jayblanc commented
I'm going to make a new pull request without mess.

2018-03-19 21:57 UTC, jayblanc commented
The new pull request is #5082 (https://github.com/keycloak/keycloak/pull/5082)

2018-03-20 09:52 UTC, mposolda commented
@jayblanc Thanks! I've merged new PR. I am closing this one then.

2018-03-20 09:52 UTC, closed without merging