[KEYCLOAK-6529] - Resource Attributes
keycloak/keycloak pull request #5079
Opened 2018-03-16 17:53 UTC by pedroigor

2018-03-16 18:59 UTC, pedroigor commented
Please, merge https://github.com/keycloak/keycloak/pull/5077 first.

2018-03-21 13:54 UTC, sguilhen approved these changes

2018-03-22 07:26 UTC, vramik requested changes

2018-03-22 07:26 UTC, vramik commented on model/jpa/src/main/resources/META-INF/jpa-changelog-authz-4.0.0.CR1.xml
> +        <addPrimaryKey columnNames="ID" constraintName="CONSTRAINT_RESOURCE_ATTRIBUTE_PK" tableName="RESOURCE_ATTRIBUTE"/>
The CONSTRAINT_RESOURCE_ATTRIBUTE_PK identifier is too long for Oracle databases, 30 characters is max value

2018-03-22 09:36 UTC, ghost approved these changes

2018-03-22 09:37 UTC, mhajas approved these changes

2018-03-22 10:50 UTC, vramik commented
@pedroigor it works now on all DBs, LGTM now. Maybe one more think, you can squash commits ;)

2018-03-27 06:12 UTC, stianst approved these changes

2018-03-27 12:30 UTC, merged