KEYCLOAK-6942 Cut off background on the new login page
keycloak/keycloak pull request #5091
Opened 2018-03-22 10:31 UTC by junezhang

Fixed the bug: https://issues.jboss.org/browse/KEYCLOAK-6942
When the content is long enough and the page needs to be scrolled the background is cut off.

<img width="600" alt="screen shot 2018-03-22 at 6 27 52 pm" src="https://user-images.githubusercontent.com/701009/37765393-f6ab6e7e-2dfe-11e8-8e78-8217bafd7c75.png">

@vmuzikar Please help to check this bug.

2018-03-23 07:38 UTC, stianst commented
The fix here is only for RH-SSO theme. While the image attached to the JIRA is using the Keycloak theme. I believe the issue may be restricted to Keycloak and not RH-SSO, but @vmuzikar should confirm.

2018-03-23 11:49 UTC, vmuzikar requested changes
@junezhang Thanks for the fix.

RH-SSO theme is fixed. Could you please port this changes to Keycloak theme as well? This concerned both RH-SSO and Keycloak themes (as it's stated in the Environment field of the JIRA).

2018-03-26 03:32 UTC, junezhang commented
@vmuzikar 
![screen shot 2018-03-26 at 11 30 04 am](https://user-images.githubusercontent.com/701009/37885672-313a42f8-30e9-11e8-8d4f-403ff4888feb.png)

Fixed the KeyCloak theme. please help to verify.

2018-03-26 08:08 UTC, stianst commented
Using auto makes it not behave on wide screens. That's why I changed it to cover which it used to be. 

![image](https://user-images.githubusercontent.com/2271511/37894158-9421a1ce-30dd-11e8-9ba1-bc8063b074cb.png)

2018-03-26 08:09 UTC, stianst commented
It's strange that cover doesn't do the job. It should stretch/cut the image to make it cover the whole screen.

2018-03-26 09:23 UTC, vmuzikar approved these changes
I've tested it with the latest changes and looks good to me. Thanks @junezhang!

@stianst I was unable to reproduce the issue with the wide Keycloak background. Maybe it was fixed in the meantime?

2018-03-26 16:23 UTC, stianst approved these changes

2018-03-26 16:23 UTC, merged