Fixes KEYCLOAK-6970 Update HTML for profile page
keycloak/keycloak pull request #5146
Opened 2018-04-12 06:37 UTC by junezhang

Fixes KEYCLOAK-6970 Update HTML for profile page
https://issues.jboss.org/browse/KEYCLOAK-6970

2018-04-12 06:38 UTC, junezhang commented
@ssilvert Hello, Stan, please help to review the profile page.

2018-04-13 17:21 UTC, ssilvert requested changes
Didn't you need to update account-page.component.ts like we discussed?  Perhaps you accidentally left it out of the commit?

@Component({
    moduleId: module.id,
    selector: 'app-account-page',
    templateUrl: './account-page.component.html',
    styleUrls: ['account-page.component.css']
})

2018-04-13 17:33 UTC, ssilvert commented
Nevermind.  I see you are using styles.css instead of account-page.component.ts.

2018-04-13 17:34 UTC, ssilvert approved these changes

2018-04-13 17:34 UTC, merged