KEYCLOAK-5461 Upgrade to Liquibase 3.5.5
keycloak/keycloak pull request #5161
Opened 2018-04-19 13:01 UTC by martin-kanis

2018-04-19 13:07 UTC, hmlnarik commented
@vramik Could you please test DB matrix and migration?

2018-04-20 09:40 UTC, vramik requested changes
The DB matrix passed, but I get: 
liquibase.exception.ValidationFailedException: Validation Failed:
      3 change sets check sum
           META-INF/jpa-changelog-1.0.0.Final.xml::1.0.0.Final::sthorger@redhat.com was: 7:00a57f7a6fb456639b34e62972e0ec02 but is now: 7:4e70412f24a3f382c82183742ec79317
           META-INF/db2-jpa-changelog-1.0.0.Final.xml::1.0.0.Final::sthorger@redhat.com was: 7:f061c3934594ee60a9b2343f5100ae4e but is now: 7:cb16724583e9675711801c6875114f28
           META-INF/jpa-changelog-2.1.0.xml::2.1.0::bburke@redhat.com was: 7:e01599a82bf8d6dc22a9da506e22e868 but is now: 7:f1f9fd8710399d725b780f463c6b21cd

when running migration testsuite

2018-04-20 09:45 UTC, hmlnarik requested changes
Thanks for the changes. See inline

2018-04-20 09:45 UTC, hmlnarik commented on model/jpa/src/main/resources/META-INF/jpa-changelog-1.0.0.Final.xml
>      <changeSet author="sthorger@redhat.com" id="1.0.0.Final">
The changeset IDs should be modified (e.g. to 1.0.0.Final-KEYCLOAK-5461) to avoid checksum changes. This applies to all affected changesets.

2018-04-20 10:17 UTC, martin-kanis commented
@hmlnarik updated

2018-04-23 07:07 UTC, vramik commented on model/jpa/src/main/resources/META-INF/jpa-changelog-1.0.0.Final.xml
> +                <changeSetExecuted id="1.0.0.Final-KEYCLOAK-5461" author="sthorger@redhat.com" changeLogFile="META-INF/jpa-changelog-1.0.0.Final.xml"/>
@martin-kanis @hmlnarik I've re-run the tests and now I get liquibase.exception.MigrationFailedException: Migration failed for change set META-INF/jpa-changelog-1.0.0.Final.xml::1.0.0.Final-KEYCLOAK-5461::sthorger@redhat.com:
...
...
...
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'client' already exists

The problem is IMO in the change of changelog IDs on this file (the same for other changes). This precondition has to assume that changese id="1.0.0.Final" was not executed.

2018-04-23 09:50 UTC, vramik commented
@martin-kanis thanks for the changes, DB matrix, auto-migration works fine now, the problem remains with manual-migration. There is an error when executing 
`INSERT INTO dballo10.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) 
VALUES ('1.0.0.Final-KEYCLOAK-5461', 'sthorger@redhat.com', 'META-INF/jpa-changelog-1.0.0.Final.xml', NOW(), 39, '7:4e70412f24a3f382c82183742ec79317', 'createTable tableName=APPLICATION_DEFAULT_ROLES; createTable tableName=CLIENT; createTable tableName=CLIENT_SESSION; createTable tableName=CLIENT_SESSION_ROLE; createTable tableName=COMPOSITE_ROLE; createTable tableName=CREDENTIAL; createTable tab...', '', 'MARK_RAN', NULL, NULL, '3.5.4', '4469375888');`
Specifically: Unknown column 'DEPLOYMENT_ID' in 'field list'

@hmlnarik any ideas?

2018-04-23 10:09 UTC, hmlnarik commented
Caused by https://liquibase.jira.com/browse/CORE-2657
Update is needed, most likely in the [`updateChangeSet`](https://github.com/keycloak/keycloak/blob/master/model/jpa/src/main/java/org/keycloak/connections/jpa/updater/liquibase/LiquibaseJpaUpdaterProvider.java#L116) method would be sufficient, that would check whether the column is there in the changelog table, and if not, issue the alter table command.

2018-04-23 18:08 UTC, hmlnarik requested changes
DATABASECHANGELOG is not the only name of changelog table, there may be multiple ones. That is why the name should be put into parameter

2018-06-19 10:03 UTC, martin-kanis commented
@hmlnarik @vramik The PR is updated. I've run the following CI jobs:
test-keycloak-jpa-migration-manual - all green

2018-06-19 11:21 UTC, vramik submitted a review, later dismissed
@martin-kanis test-keycloak-jpa is fine, there are missing some build parameters 
Thank you.

2018-06-19 11:35 UTC, hmlnarik requested changes

2018-06-19 11:35 UTC, hmlnarik commented on model/jpa/src/main/java/org/keycloak/connections/jpa/updater/liquibase/LiquibaseJpaUpdaterProvider.java
> +                logger.infov("Column name {0} of type {1}({2}) found.", name, type, size);
should be debug at most

2018-06-19 11:35 UTC, hmlnarik commented on model/jpa/src/main/java/org/keycloak/connections/jpa/updater/liquibase/LiquibaseJpaUpdaterProvider.java
> +                logger.infov("Adding missing column {0} to {1} table", DEPLOYMENT_ID_COLUMN, changelogTableName);
decrease logger verbosity to debug

2018-06-19 11:35 UTC, hmlnarik commented on model/jpa/src/main/java/org/keycloak/connections/jpa/updater/liquibase/LiquibaseJpaUpdaterProvider.java
> +                SqlStatement sqlStatement = new AddColumnStatement(null, defaultSchema, changelogTableName, DEPLOYMENT_ID_COLUMN, "varchar(10)", null, null);
The column should be nullable, see https://github.com/liquibase/liquibase/commit/b16a5d97086f9ac1c0efdf983fdb1667376699b3#diff-4aa547987494c9c61353be5bd6406a5bR180

2018-06-19 14:17 UTC, martin-kanis commented
@hmlnarik changed

2018-06-21 13:00 UTC, hmlnarik commented
Looks good to me.
Found one thing when running a final check - distribution contains old license files and needs to be updated:
- https://github.com/keycloak/keycloak/blob/master/distribution/feature-packs/server-feature-pack/src/main/resources/licenses/keycloak/org.liquibase,liquibase-core,3.4.1,Apache%20Software%20License%202.0.txt
- https://github.com/keycloak/keycloak/blob/master/distribution/feature-packs/server-feature-pack/src/main/resources/licenses/keycloak/licenses.xml
- https://github.com/keycloak/keycloak/blob/master/distribution/feature-packs/server-feature-pack/src/main/resources/licenses/rh-sso/org.liquibase,liquibase-core,3.4.1.redhat-2,Apache%20Software%20License%202.0.txt
- https://github.com/keycloak/keycloak/blob/master/distribution/feature-packs/server-feature-pack/src/main/resources/licenses/rh-sso/licenses.xml

2018-06-21 15:19 UTC, hmlnarik commented
Looks good now, thank you!
Last check - @vramik could you please recheck jpa and migration jobs?

2018-06-22 07:42 UTC, vramik approved these changes
@hmlnarik @martin-kanis already rechecked the jobs with latest changes.

2018-06-22 08:01 UTC, vramik commented
I need to re-test the PR one more time, hold the merging for now, pls

2018-06-22 11:02 UTC, vramik commented
@hmlnarik all tests passed. As far as I'm concerned it could be merged. Thank you.

2018-06-22 11:19 UTC, hmlnarik approved these changes

2018-06-22 11:20 UTC, merged