split ticket management and permission endpoint
keycloak/keycloak pull request #5203
Opened 2018-05-15 12:35 UTC by chicco785

* created new endpoint for ticket management /permission/ticket
* removed unused class
* support for direct creation of ticket by resource owner
* fix DELETE ticket

2018-05-15 13:49 UTC, chicco785 commented
@pedroigor so for the time being i split the ticket and the permissionTicket management.
so that /permission is compliant with the standard and we don't have to create work around with additional parameters.

2018-05-15 14:13 UTC, pedroigor requested changes
@chicco785, could you change your commit to reference https://issues.jboss.org/browse/KEYCLOAK-7354 ?

2018-05-16 13:12 UTC, chicco785 commented
commit summary and message should be up-to-date now

2018-05-17 18:22 UTC, pedroigor approved these changes

2018-05-17 18:22 UTC, merged