KEYCLOAK-7433 KEYCLOAK-7434 Align versions
keycloak/keycloak pull request #5221
Opened 2018-05-24 09:38 UTC by hmlnarik

2018-05-24 22:10 UTC, pskopek requested changes
I have spotted following additional differences from EAP component versions:

<wildfly.core.version>3.0.15.Final</wildfly.core.version>
<jboss.logging.tools.version>2.1.0.Final</jboss.logging.tools.version>
<resteasy.version>3.0.25.Final</resteasy.version>

Can you update them, please?

2018-05-25 07:31 UTC, hmlnarik commented
Thanks for the review! Only jboss.logging.tools were updated, the new versions of the other two dependencies are not yet available in maven central.

2018-05-25 08:13 UTC, pskopek approved these changes

2018-05-25 09:27 UTC, pdrozd approved these changes

2018-05-25 09:27 UTC, merged