Map group members of authenticated subject into subject info (KEYCLOAK-7309).
keycloak/keycloak pull request #5222
Opened 2018-05-24 12:19 UTC by DennisBayer

This commit contains a POC for the issue "Roles get lost after security context was propagated back to wildfly-swarm, if using jwt for authentication" (KEYCLOAK-7309).

2018-06-01 13:48 UTC, pedroigor requested changes
The problem here is on how JASPIC in Wildfly is obtaining roles from the security context. It expects roles from ```SubjectInfo``` instead of relying on the principals associated with the subject.

@DennisBayer, changes look good although I think you could just call ```sc.getUtil().setRoles``` to achieve the same result.

Also, are you able to write a test to make sure we don't break integration with JASPIC/MP-JWT in Swarm ?

2018-06-01 18:37 UTC, DennisBayer commented
Hi @pedroigor 
as soon as I'm back in the office, I'll test your `sc.getUtil().setRoles` suggestion.

About the test: Could you point me to an example, where and how to put a test for this specific case?

Best regards!

2018-06-05 12:55 UTC, pedroigor commented
@DennisBayer, thanks for your latest changes.

Regarding tests, I was expecting to write tests using wildfly, but I think we could include a specific module for wildfly swarm. For that, I need to discuss with our team about it. It would also be good to make sure we are working with MP-JWT.

I'm looking at this now and will let you know about updates. Hope have something this week.

2018-06-12 12:07 UTC, pedroigor commented
@DennisBayer, I'm going to merge this one. Thanks for all changes so far.

Will do some tests before merging though, running some adapter tests.

We really need to prepare our testsuite to make it more easier to tests things like that though.

2018-06-14 00:02 UTC, pedroigor approved these changes

2018-06-14 00:03 UTC, merged

2018-06-14 00:03 UTC, pedroigor commented
@DennisBayer, thanks.

2018-06-14 07:01 UTC, DennisBayer commented
@pedroigor No problem :)

Greetings!