KEYCLOAK-7444: LANG specific check
keycloak/keycloak pull request #5226
Opened 2018-05-25 06:17 UTC by rlfnb

The line commented out breaks the test run on on non-english LANG 
settings as described in the ticket.

2018-05-25 19:23 UTC, hmlnarik requested changes
Is this the only test that fails with non-Englsh locale?

2018-06-01 07:38 UTC, hmlnarik commented
@rlfnb Do you have time to update the PR according to the comment above?

2018-06-01 16:50 UTC, rlfnb commented
rebased the branch, seems there are no additional lang dependent failures but I cannot say for sure as its still NOT building:

`
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project keycloak-saml-core: Compilation failure: Compilation failure:
[ERROR] /Users/rlfnb/workspace/keycloak/saml-core/src/main/java/org/keycloak/saml/processing/core/util/XMLSignatureUtil.java:[757,42] incompatible types: java.util.List<java.lang.Object> cannot be converted to java.util.List<? extends javax.xml.crypto.XMLStructure>
[ERROR] /Users/rlfnb/workspace/keycloak/saml-core/src/main/java/org/keycloak/saml/processing/api/util/KeyInfoTools.java:[51,70] incompatible types: java.util.List<javax.xml.crypto.XMLStructure> cannot be converted to java.lang.Iterable<java.lang.Object>
[ERROR] /Users/rlfnb/workspace/keycloak/saml-core/src/main/java/org/keycloak/saml/processing/api/util/KeyInfoTools.java:[55,70] incompatible types: java.util.List<javax.xml.crypto.XMLStructure> cannot be converted to java.lang.Iterable<java.lang.Object>
[ERROR] /Users/rlfnb/workspace/keycloak/saml-core/src/main/java/org/keycloak/saml/processing/api/util/KeyInfoTools.java:[60,58] incompatible types: java.util.List<capture#1 of ?> cannot be converted to java.lang.Iterable<java.lang.Object>
`
started maven as below:
`
$ mvn -X clean package
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T18:41:47+02:00)
Maven home: /Users/rlfnb/java/apache-maven-3.3.9
Java version: 10.0.1, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.10.0.1/Contents/Home
Default locale: de_DE, platform encoding: UTF-8
OS name: "mac os x", version: "10.13.4", arch: "x86_64", family: "mac"
`

Any obvious idea so far? Would you merge the first fix into master or should we try to resolve the other issue as well?

2018-06-04 09:08 UTC, hmlnarik commented
This is an issue with JDK 10 compilation. Feel free to file a JIRA

2018-06-05 08:11 UTC, rlfnb commented
Maybe, I missed something, but even if the subsequent failure is jdk10 relevant, the LANG specific check should be merged in for sure?

2018-06-05 09:30 UTC, hmlnarik commented
@rlfnb Quoting:

> rebased the branch, seems there are no additional lang dependent failures but I cannot say for sure as its still NOT building

So is it still relevant or not?

2018-06-05 14:36 UTC, rlfnb commented
PR is still relevant and in addition I'll open a new issue for the jdk10 related problem.

2018-06-06 08:21 UTC, hmlnarik approved these changes

2018-06-06 10:53 UTC, merged

2018-06-06 10:54 UTC, hmlnarik commented
@rlfnb Thank you for the contribution!