Bugfix/keycloak 7316
keycloak/keycloak pull request #5242
Opened 2018-06-05 00:08 UTC by drofe

https://issues.jboss.org/browse/KEYCLOAK-7316
IsPassive is not a mandatory field.
Some SAML plugins is not capable of setting this attribute to its default value and a NPE is created. This fix does not allow null valued isPassive in AuthnRequest but rather falls back to default FALSE.

2018-06-05 14:27 UTC, hmlnarik commented
@drofe Thank you for the PR. Unfortunately, this is not viable approach, since the IsPassive as well as ForceAuthn is a three-state field (unset, true, false), which needs to be respected, and is masked in this PR. Note that the setters might not be called at all, leaving the field value set to default which is `null`.

The correct approach is to check for nulls at appropriate places in the code. This also requires adding integration tests similar to those in `org.keycloak.testsuite.saml` package.

2018-06-05 14:27 UTC, hmlnarik requested changes
see above

2018-06-05 23:42 UTC, drofe commented
Hi @hmlnarik.
Thank you for reviewing and considering my PR!

Could you please elaborate what the NULL value means since I currently don't know how to write proper tests for that scenario.

My very simple solution was heavily based on the fact that the default value if setters are not called is _NOT_ NULL but rather false,
see L68 and L70 in org.keycloak.dom.saml.v2.protocol.AuthnRequestType. Lines which I haven't changed. I.e. only way to get NULL is to explicitly call
setter with NULL (which happens if attribute is not in request).

The SAML v2.0 protocol does not dictate a valid "third" option for these values, see:

According to this xsd they are boolean and optional:
http://docs.oasis-open.org/security/saml/v2.0/saml-schema-protocol-2.0.xsd

Also L2105 to 2113 in https://www.oasis-open.org/committees/download.php/35711/sstc-saml-core-errata-2.0-wd-06-diff.pdf states:

ForceAuthn [Optional]
A Boolean value. If "true", the identity provider MUST authenticate the presenter directly rather than
rely on a previous security context. If a value is not provided, the default is "false". However, if both
ForceAuthn and IsPassive are "true", the identity provider MUST NOT freshly authenticate the
presenter unless the constraints of IsPassive can be met.

IsPassive [Optional]
A Boolean value. If "true", the identity provider and the user agent itself MUST NOT visibly take control
of the user interface from the requester and interact with the presenter in a noticeable fashion. If a
value is not provided, the default is "false".

The only references I find to the getters of these values are in the SAMLRequestWriter (where a NULL value is just ignored) and in the
org.keycloak.protocol.saml.SamlService.BindingProtocol#loginRequest where the value is unboxed and hence causing the NPE.

I'm happy to add a nullcheck in the loginRequest instead but as it is passed as a primitive boolean all the way down to: org.keycloak.protocol.AuthorizationEndpointBase#handleBrowserAuthenticationRequest
I still just need to pass a "false" down if NULL or change the signature of all those methods to object boolean and handle that case in the if-statement.

IF there actually is a valid use case for NULL value (which I think would violate the protocol) shouldn't we change the field to a Enum and third value should be more descriptive than NULL? Or is it simply so that we just don't want it to be written (i.e ignored as is today if NULL) by the writer in certain circumstances?

I'm happy to re-write my solution and add integration tests on a higher level but what I'm trying to state above is that I don't see the use case and hence can't write tests for it that I know is valid and correct. I.m.h.o. removing the NULL possibility would solve the issue and avoid similar issues in the future.

Best
@drofe

2018-06-06 07:19 UTC, hmlnarik commented
@drofe While I understand that when *used*, ultimately the "unset" and "false" *behave* just the same, however the layer you are adjusting is used for *parsing* and writing back the SAML XML representation and needs to match the XML elements and attribute values.

Hence the right place where to fix it is where the XML is *used*, not where it is parsed to and written from.

2018-06-06 08:38 UTC, drofe commented
Ok, I get your point.
However, I then think it is wrong to default them to FALSE on L68 and L70 and they should be initiated to NULL. I'll make the changes according to your input and push to my branch.

2018-06-07 04:53 UTC, drofe commented
@hmlnarik Sorry for the late response but I've been busy at work. I've made the changes as per your suggestions and ran the integration tests with:
mvn -f testsuite/integration-arquillian/pom.xml clean install -Pauth-server-wildfly -Papp-server-wildfly -Dtest=AuthnRequestTest
First without the fix to verify failure and then with fix to verify solution. Thanks a million for the integration test.
I've kept my JUnit tests but now of course validating that values are unset of not set in message.

2018-06-07 05:28 UTC, hmlnarik commented
@drofe Could you please rebase and squash all your changes into a single commit?

2018-06-07 06:04 UTC, drofe commented
@hmlnarik Done.

2018-06-07 06:45 UTC, hmlnarik approved these changes

2018-06-07 06:50 UTC, merged