KEYCLOAK-7698: Update Japanese properties for 4.0
keycloak/keycloak pull request #5453
Opened 2018-08-10 06:18 UTC by k-tamura

Please merge my request.

See also:
https://issues.jboss.org/browse/KEYCLOAK-7698

This request has already been reviewed by @tnorimat (Hitachi, Ltd.) and @hiroyuki-sato on my GitHub:
https://github.com/k-tamura/keycloak400-japanese-properties/issues

2018-08-24 05:33 UTC, k-tamura commented
Hi Keycloak developer team,

Could you add @wadahiro as a reviewer?

Best regards,

2018-09-05 07:32 UTC, wadahiro commented
@stianst @k-tamura Ok, I'll review this pr.

2018-09-05 11:15 UTC, wadahiro requested changes

2018-09-05 11:15 UTC, wadahiro commented on themes/src/main/resources-community/theme/base/email/messages/messages_ja.properties
> +identityProviderLinkBody=誰かがあなたの"{1}"アカウントをユーザー{2}の"{0}"アカウントにリンクさせたいと思っています。これがあなたの場合は、下のリンクをクリックしてアカウントをリンクしてください。\n\n{3}\n\nこのリンクの有効期限は{5}以内です。\n\nアカウントをリンクしたくない場合は、このメッセージを無視してください。アカウントをリンクすると、{
@k-tamura `you will be able to login to {1} through {0}` は、`{0}経由で{1}にログイン` (外部Idp経由でKeycloakにログイン) かと思っていましたが違います？

2018-09-05 11:15 UTC, wadahiro commented on themes/src/main/resources-community/theme/base/email/messages/messages_ja.properties
> +identityProviderLinkBodyHtml=<p>誰かがあなたの<b>{1}</b>アカウントをユーザー{2}の<b>{0}</b>アカウントにリンクさせたいと思っています。これがあなたの場合は、下のリンクをクリックしてアカウントをリンクしてください。</p><p><a href="{3}">アカウントのリンクを確認する</a></p><p>このリンクの有効期限は{5}以内です。<
@k-tamura 同上

2018-09-05 11:15 UTC, wadahiro commented on themes/src/main/resources-community/theme/base/email/messages/messages_ja.properties
> +emailVerificationBodyCode=次のコードを入力してメールアドレスを確認してください。\n\n{0}\n\n.
@k-tamura 末尾のドットはなしのほうが良いかも

2018-09-07 05:40 UTC, k-tamura commented on themes/src/main/resources-community/theme/base/account/messages/messages_ja.properties
> +personalSubMessage=この基本情報を管理してください：名字、姓、メール
「字」が余分ですね...消します

2018-09-07 05:41 UTC, k-tamura commented on themes/src/main/resources-community/theme/base/account/messages/messages_ja.properties
> +clearAllFilter=全てのフィルターをクリア
了解です

2018-09-07 05:56 UTC, k-tamura commented on themes/src/main/resources-community/theme/base/email/messages/messages_ja.properties
> +identityProviderLinkBody=誰かがあなたの"{1}"アカウントをユーザー{2}の"{0}"アカウントにリンクさせたいと思っています。これがあなたの場合は、下のリンクをクリックしてアカウントをリンクしてください。\n\n{3}\n\nこのリンクの有効期限は{5}以内です。\n\nアカウントをリンクしたくない場合は、このメッセージを無視してください。アカウントをリンクすると、{
その方が分かりやすいですね。うーん、和田さんが翻訳済みの前のバージョンの日本語を無駄に再翻訳してしまっていますね。他にも同件がありそうなので、見直して、必要ない変更であれば、元に戻します。

2018-09-07 05:56 UTC, k-tamura commented on themes/src/main/resources-community/theme/base/email/messages/messages_ja.properties
> +emailVerificationBodyCode=次のコードを入力してメールアドレスを確認してください。\n\n{0}\n\n.
そうですね。削除します

2018-09-07 06:00 UTC, k-tamura commented on themes/src/main/resources-community/theme/base/admin/messages/admin-messages_ja.properties
> +userManagedAccess=User-Managed Access
でいいと思いますが、何かアイディアあります？

2018-09-07 06:29 UTC, k-tamura commented on themes/src/main/resources-community/theme/base/admin/messages/admin-messages_ja.properties
> +hidden=Hidden
あえて訳しませんでしたが、非表示とかでもいいかもしれませんね。このプロパティは、管理コンソールのIdP一覧ページの列のラベルで、IdPの編集ページの「Hide on Login Page」に対応します。ログイン画面にこのIdPへのリンクは表示せずに、kc_idp_hintパラメーターを使ったときのみIdP経由でログイン可能になるようです。

2018-09-07 06:30 UTC, k-tamura commented on themes/src/main/resources-community/theme/base/admin/messages/admin-messages_ja.properties
> +envelopeFrom=Envelope From
はい。対応するいい日本語が無かったので。

2018-09-07 06:30 UTC, k-tamura commented on themes/src/main/resources-community/theme/base/admin/messages/admin-messages_ja.properties
> +action-token-generated-by-user-lifespan.tooltip=ユーザーが送信したアクション許可（パスワード忘れのEメールなど）の有効期限が切れるまでの最大時間。ユーザーが自分で作成した操作にすばやく反応することが期待されるため、この値は短くすることをお勧めします
了解です

2018-09-07 06:30 UTC, k-tamura commented on themes/src/main/resources-community/theme/base/admin/messages/admin-messages_ja.properties
> +addressClaim.street.tooltip=「address」トークンクレーム内の「street_address」サブクレイムにマップするために使用されるユーザー属性の名前。デフォルトは「street」です。
了解です

2018-09-07 06:33 UTC, k-tamura commented on themes/src/main/resources-community/theme/base/admin/messages/admin-messages_ja.properties
> +addressClaim.formatted.label=書式付きアドレスのユーザー属性名
了解です。そっちにあわせましょう

2018-09-07 06:33 UTC, k-tamura commented on themes/src/main/resources-community/theme/base/admin/messages/admin-messages_ja.properties
> +include-onetimeuse-condition.tooltip=OneTimeUse 条件をログインレスポンスに含める必要があるかどうか？
そうですね。そうします

2018-09-07 06:33 UTC, k-tamura commented on themes/src/main/resources-community/theme/base/admin/messages/admin-messages_ja.properties
> +hide-on-login-page.tooltip=非表示の場合、明示的にリクエストされていれば（例えば、'kc_idp_hint'パラメーターを使用していれば）、このプロバイダーによるログインが可能です
OK

2018-09-07 06:35 UTC, k-tamura commented on themes/src/main/resources-community/theme/base/admin/messages/admin-messages_ja.properties
> +gitlab.default-scopes.tooltip=ログイン時に要求するスコープ。openidは常に要求されます。何も指定しない場合は、さらにAPIを追加します。
これは間違いですね。直します

2018-09-07 06:57 UTC, k-tamura commented on themes/src/main/resources-community/theme/base/account/messages/messages_ja.properties
> +clearAllFilter=全てのフィルターをクリア
もともと「全て」を使ってる箇所もありました。このプルリクがマージされたら、全体的に見直して、翻訳スタイルガイドにそった日本語訳にしますかね。

2018-09-18 03:42 UTC, k-tamura commented
@stianst Could you merge this PR? If needed, I will rebase and squash my commits.

2018-09-18 06:25 UTC, wadahiro submitted a review, later dismissed
LGTM

2018-09-18 06:46 UTC, k-tamura commented
@stianst Could you merge this PR? If needed, I will rebase and squash my commits.

2018-09-20 13:50 UTC, stianst commented
Please squash into a single commit and I'll merge

2018-09-20 15:48 UTC, k-tamura commented
@stianst Done. Could you please merge this?

2018-09-28 01:50 UTC, k-tamura commented
@stianst Could you merge this before the completion of 4.x (feature freeze)?

2018-10-04 11:07 UTC, stianst commented
@k-tamura yes, just re-scheduled the test that didn't pass. I assume it was a false negative. Just waiting for that to complete and I'll merge

2018-10-04 18:59 UTC, stianst approved these changes

2018-10-04 18:59 UTC, merged

2018-10-04 21:16 UTC, k-tamura commented
Thank you!