KEYCLOAK-8010 Improve handling of Conditions SAML tag
keycloak/keycloak pull request #5547
Opened 2018-09-10 08:41 UTC by hmlnarik

2018-09-12 12:10 UTC, pskopek requested changes
Only minor issue (see other comment).
Otherwise it looks good to me.

2018-09-18 14:57 UTC, hmlnarik commented on testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcSamlIdPInitiatedSsoTest.java
> +import static org.hamcrest.Matchers.*;
You're indeed right, fixing in next commit. Thanks for spotting this!

2018-09-19 11:06 UTC, hmlnarik commented
@pskopek Done, could you please re-review?

2018-09-19 11:12 UTC, pskopek approved these changes
Looks good!

2018-09-19 12:00 UTC, mposolda approved these changes

2018-09-19 12:00 UTC, merged