Add Turkish Language File
keycloak/keycloak pull request #5678
Opened 2018-10-26 08:47 UTC by adilarli

2018-10-31 05:36 UTC, stianst commented
Thanks, we need to find someone from the community that can review this

2018-10-31 05:41 UTC, stianst commented
@keycloak-ci-bot test

2018-11-05 15:47 UTC, neslihanedes commented on themes/src/main/resources-community/theme/base/account/messages/messages_tr.properties
> +updatePasswordMessage=G\u00FC\u00E7l\u00FC bir \u015Fifre, say\u0131lar, harfler ve sembollerin bir kar\u0131\u015F\u0131m\u0131n\u0131 i\u00E7erir. Tahmin etmek zor, ger\u00E7ek bir kelimeye benzeme
updatePasswordMessage=G\u00FC\u00E7l\u00FC bir \u015Fifre, say\u0131lar, harfler ve sembollerin kar\u0131\u015F\u0131m\u0131ndan olu\u015Fmal\u0131d\u0131r. Tahmin etmesi zor ve ger\u00E7ek bir kelimeye benzemeyen \u015Fifre sadece bu hesap i\u00E7in kullan\u0131l\u0131r.

2018-11-05 15:47 UTC, neslihanedes commented on themes/src/main/resources-community/theme/base/account/messages/messages_tr.properties
> +locality=Semt
locality = \u015Eehir

2018-11-05 15:47 UTC, neslihanedes commented on themes/src/main/resources-community/theme/base/account/messages/messages_tr.properties
> +started=Ba\u015Flang\u0131\u00E7 Tarihi
If 'Tarihi' is used here (which means the **date**) is should also used for the next 2 lines.

2018-11-05 15:47 UTC, neslihanedes commented on themes/src/main/resources-community/theme/base/account/messages/messages_tr.properties
> +lastAccess=Son Eri\u015Fim
lastAccess=Son Eri\u015Fim Tarihi

2018-11-05 15:47 UTC, neslihanedes commented on themes/src/main/resources-community/theme/base/account/messages/messages_tr.properties
> +expires=Son Kullanma
expires=Son Kullanma Tarihi

2018-11-05 15:47 UTC, neslihanedes commented on themes/src/main/resources-community/theme/base/account/messages/messages_tr.properties
> +grantedPermissions=\u0130zin Verilen \u0130zinler
grantedPermissions= Verilen \u0130zinler

2018-11-05 15:47 UTC, neslihanedes commented on themes/src/main/resources-community/theme/base/account/messages/messages_tr.properties
> +needMyApproval=Onay\u0131ma ihtiyac\u0131m var
needMyApproval=Onay\u0131m gerekli

2018-11-05 15:47 UTC, neslihanedes commented on themes/src/main/resources-community/theme/base/account/messages/messages_tr.properties
> +permissionRequestion=\u0130zin \u0130stekleri
permissionRequestion=\u0130zin Talepleri

2018-11-05 15:47 UTC, neslihanedes commented on themes/src/main/resources-community/theme/base/account/messages/messages_tr.properties
> +locale_ja=Afrikanca
not sure about this, is it 	Japanese (Japonca)?
locale_ja=Japonca

2018-11-05 15:47 UTC, neslihanedes commented on themes/src/main/resources-community/theme/base/account/messages/messages_tr.properties
> +group=Gurup
group=Grup

2018-11-06 05:35 UTC, AlicanAkkus commented on themes/src/main/resources-community/theme/base/account/messages/messages_tr.properties
> +role_view-identity-providers=Identity Provider g\u00F6r\u00FCnt\u00FCle
should be 'Kimlik Sağlayıcılar'

2018-11-06 05:35 UTC, AlicanAkkus commented on themes/src/main/resources-community/theme/base/account/messages/messages_tr.properties
> +role_manage-identity-providers=Identity Provider y\u00F6net
should be 'Kimlik Sağlayıcıları Yönet'

2018-11-06 12:49 UTC, batuhankok submitted a review, later dismissed

2018-11-08 15:30 UTC, stianst commented
@AlicanAkkus @neslihanedes can you review again and approve if you are happy with changes?

2018-11-08 18:05 UTC, AlicanAkkus submitted a review, later dismissed

2018-11-08 18:06 UTC, AlicanAkkus commented
> @AlicanAkkus @neslihanedes can you review again and approve if you are happy with changes?

looks like good. 👍🏻

2018-11-08 20:40 UTC, neslihanedes commented on themes/src/main/resources-community/theme/base/account/messages/messages_tr.properties
> +inResource=kaynak
`inResource=Kaynak`

2018-11-08 20:42 UTC, neslihanedes commented on themes/src/main/resources-community/theme/base/account/messages/messages_tr.properties
> +shares=payla\u015F\u0131m(lar)
`shares=Payla\u015F\u0131m(lar)`

2018-11-08 20:45 UTC, neslihanedes commented on themes/src/main/resources-community/theme/base/account/messages/messages_tr.properties
> +people=insanlar
`people=\u0130nsanlar`

2018-11-08 20:48 UTC, neslihanedes requested changes
I have suggested some capital letter corrections, the rest seems fine :)

2018-11-09 07:41 UTC, stianst commented
@AlicanAkkus thanks

@neslihanedes thanks for second review,. @adilarli has pussed changes for capital letters, can you let me know if you are happy with the PR now?

2018-11-09 11:01 UTC, neslihanedes approved these changes

2018-11-09 11:02 UTC, neslihanedes approved these changes

2018-11-09 11:03 UTC, neslihanedes commented
@stianst I'm happy with the last changes :)

2018-11-12 10:49 UTC, merged