KEYCLOAK-8702:Fix Offline Sessions requires column
keycloak/keycloak pull request #5691
Opened 2018-11-02 22:36 UTC by mgottl04

Prevent RemoveDuplicateOfflineSessions from running when database has already dropped CLIENT_SESSION_ID from  OFFLINE_CLIENT_SESSION table. This change unblocks migrating from 3.2.0 to 4.4.0 and later.

2018-11-06 01:07 UTC, mgottl04 commented
Failure seems to be unrelated to this change and is an instability present in multiple other PRs.

2018-11-06 12:25 UTC, hmlnarik requested changes
Than you for investigating this issue and the contribution.

The correct way to fix this issue is to ensure that this changeset is excluded if either `3.2.0` or `3.2.0-fixed` has been executed. Conditioning on `columnExists` is inconsistent with the rest of the changelogs.

Could you please update the PR?

2018-11-06 19:16 UTC, mgottl04 commented
@hmlnarik  I've updated the PR as you have suggested. Thanks for the timely reply!

2018-11-06 19:33 UTC, mgottl04 commented
@hmlnarik would it also be possible to get this changed cherry picked or service released into keycloak 4.5? I'm not completely up to speed with Keycloak's processes.

2018-11-08 17:36 UTC, mgottl04 commented
@hmlnarik  I am not able to squash the commits on this pull request as I do not have merge rights for keycloak. Squashing occurs when you or anyone else who has merge rights merges the PR. Here is the documentation on this functionality: https://help.github.com/articles/about-pull-request-merges/
Please see the section titled "Squash and merge your pull request commits"

Please let me know if you are referring to a different action or provide documentation or  other clarification about how I might help get this line merged as soon as possible. Thanks for your time.

2018-11-13 10:30 UTC, hmlnarik commented
@mgottl04 Yeah, by squashing the commits I rather mean for you to squash the two commits locally and then force-push them to your branch, this will update it also here in the PR. Thank you.

2018-11-13 18:19 UTC, mgottl04 commented
@hmlnarik I've squashed it locally and force pushed it. This PR is updated. Please let me know if there is anything else I can do to move this along.

2018-11-13 19:22 UTC, hmlnarik commented
Thank you, let's now see how CI goes.

2018-11-14 14:10 UTC, pdrozd commented
@keycloak-ci-bot test

2018-11-14 17:18 UTC, mgottl04 commented
@hmlnarik the build result is not visible to me. Please let me know if there is anything I can do to help move this along.

2018-11-15 08:35 UTC, hmlnarik commented
@keycloak-ci-bot test

2018-11-15 11:48 UTC, vramik commented
@hmlnarik DB migration matrix passed with the PR

2018-11-15 12:54 UTC, hmlnarik commented
@keycloak-ci-bot test

2018-11-15 20:48 UTC, hmlnarik approved these changes

2018-11-15 20:48 UTC, hmlnarik commented
@keycloak-ci-bot test

2018-11-16 07:54 UTC, hmlnarik commented
@keycloak-ci-bot test

2018-11-16 10:30 UTC, hmlnarik commented
@keycloak-ci-bot test

2018-11-16 11:03 UTC, merged