KEYCLOAK-8940 Stabilize SessionsPreloadCrossDCTest.loginFailuresPreloadTest
keycloak/keycloak pull request #5759
Opened 2018-11-28 05:55 UTC by hmlnarik

2018-11-29 10:13 UTC, mposolda submitted a review, later dismissed

2018-12-04 10:40 UTC, mposolda approved these changes

2018-12-04 11:26 UTC, vramik requested changes
There are still some failures. I've attached log form last build to the jira.

2018-12-04 13:23 UTC, vramik approved these changes
@hmlnarik thank you for creating the other issue (KEYCLOAK-9007) and for the PR.

2018-12-04 13:27 UTC, merged