[KEYCLOAK-9077] Adds support for SAML SessionNotOnOrAfter attribute in response xml serialization
keycloak/keycloak pull request #5811
Opened 2018-12-13 17:41 UTC by mrparkers

Loosely based on #3250

JIRA: https://issues.jboss.org/browse/KEYCLOAK-9077

For context, I'm working on integrating some software with my Keycloak deployment via SAML.  I want to be able to control the client session length using `SessionNotOnOrAfter` in order to force that client to re-authenticate with Keycloak every hour or so.  I noticed that there is a setter on `AuthnStatementType` for this attribute, so I wrote a custom `SAMLLoginResponseMapper` to use this setter.  Once I was finished, I realized that this getter is never invoked when serializing the XML response, so all I am changing here is invoking that getter during the serialization process and adding that attribute if it exists.

Even after this change, there is still no "official" way to set this attribute without using a custom mapper like I did.  I am willing to look into adding this, perhaps as a setting for SAML clients, but I felt like that was out of scope for this PR.

2019-01-25 10:42 UTC, hmlnarik requested changes
Thank you for the PR!

Could you please address the one inline comment, and at the same time update https://github.com/keycloak/keycloak/blob/master/saml-core/src/main/java/org/keycloak/saml/processing/core/parsers/saml/assertion/SAMLAuthnStatementParser.java#L51 which refers wrong constant?

2019-01-25 10:42 UTC, hmlnarik commented on saml-core-api/src/main/java/org/keycloak/saml/common/constants/JBossSAMLConstants.java
> +    SESSION_NOT_ON_OR_AFTER(PROTOCOL_NSURI, "SessionNotOnOrAfter"),
Please move this constant to `org.keycloak.saml.processing.core.parsers.saml.assertion.SAMLAssertionQNames` as an `ATTR_SESSION_NOT_ON_OR_AFTER` constant similarly to other `ATTR_*` constants declared there. `JBossSAMLConstants` is eventually going to be removed.

2019-01-25 14:45 UTC, mrparkers commented
Thanks for the review, @hmlnarik.  I think I have addressed everything.  Please let me know if you need anything else from me!

2019-01-25 15:23 UTC, hmlnarik commented
Changes look good, thanks. One thing remaining - please squash the commits to a single one and ensure that its title is prefixed with *KEYCLOAK-9077* key

2019-01-25 16:05 UTC, mrparkers commented
@hmlnarik Does that look good?

2019-01-25 16:39 UTC, mrparkers commented
Just pushed up a fix for a failing test that the unrelated change broke.  I think the build should be green now.

2019-01-28 09:57 UTC, hmlnarik approved these changes
@mrparkers Thank you! Once the repo opens for PRs, this can be merged

2019-01-30 14:40 UTC, mrparkers commented
Great, thanks!  Would you be able to give me a rough estimate of when that will be?

2019-02-05 14:42 UTC, austinlyons commented
My team is also curious on when this will merge, any updates?

2019-02-15 14:54 UTC, Collin3 commented
@hmlnarik just curious if there is any timeline as to when this will get merged. Thanks!

2019-03-04 10:41 UTC, hmlnarik commented
@keycloak-ci-bot test

2019-03-04 12:10 UTC, hmlnarik commented
@keycloak-ci-bot test

2019-03-05 08:05 UTC, merged