Add support for wildcards in subdomains for valid redirect URIs
keycloak/keycloak pull request #5826
Opened 2018-12-18 23:12 UTC by cainj13

See https://issues.jboss.org/browse/KEYCLOAK-3585.

This is a re-work of previous MR.

2019-02-21 10:17 UTC, stianst requested changes

2019-02-21 10:17 UTC, stianst commented on pom.xml
> +        <mockito.version>1.10.19</mockito.version>
We have decided not to use mocking frameworks so we can't accept this

2019-02-21 10:17 UTC, stianst commented on services/src/test/java/org/keycloak/protocol/oidc/utils/RedirectUtilsTest.java
> +package org.keycloak.protocol.oidc.utils;
Look at OAuthRedirectUriTest which can be extended to cover these tests properly

2019-03-10 23:26 UTC, davidholsgrove commented
Hi, any chance this PR will be merged into a Keycloak release soon?
Allowing the (optional) use of wildcard redirect urls on a controlled subdomain would vastly reduce administrative overhead for dynamic environment creation.
thanks,
David

2019-04-25 19:47 UTC, josh-cain commented
Closing.  It's clear that this is not going to happen (at least not with this PR), and it's so stale at this point, might as well re-write it.

2019-04-25 19:47 UTC, closed without merging

2019-04-25 19:56 UTC, sharedprophet commented
@josh-cain Could you link the new PR here if you create one, so I can watch it?

2019-04-25 20:19 UTC, josh-cain commented
@sharedprophet  - my apologies, I can see where that comment was not clear.  I have no intentions of re-writing this myself at this point.  Per @stianst 's comment, they're not going to take anything with mocks, so a re-write will entail one of:

 1. refactoring to decouple the data domain from a utility function as simple as wildcard validation (RealmModel), as you must have a properly populated RealmModel to test the exposed `verifyRedirectUri` function.
 1. manipulating the accessibility of the private `matchesRedirects` (commonly done with something like PowerMock, which I suppose would once again be taboo).
 1. writing massive integration tests involving an application server to test its ability to properly parse a url string since mocks cannot be used.

Pretty sure #1 or #2 above would get rejected, and I don't have the time/patience for #3.  Sorry to abandon it, hopefully the community can band together for this one soon!