KEYCLOAK-4722 : Support reCAPTCHA v3
keycloak/keycloak pull request #5949
Opened 2019-03-18 22:35 UTC by codaabraham

Added support for reCAPTCHA v3 as per the Google Specification.

User can configure:
- Site Key
- Site Secret Key
- Site Score
- Site Action Name 
from the configuration modal on the Keycloak Admin.

2019-03-18 23:10 UTC, codaabraham commented
@keycloak-ci-bot test

2019-05-07 08:13 UTC, stianst commented
Thanks for your PR and sorry for the late response. One issue I can see here is with regards to upgrade for existing users. Will this just work for users that are upgrading from an older Keycloak version without having to change any configuration in Keycloak or Google side? If not it may be better to introduce an option to use the old recaptcha for upgrades, while new for new realms. Alternatively we could consider a completely new authenticator for v3. We also need a corresponding PR to update the documentation.

2019-05-07 08:14 UTC, stianst requested changes
This will most likely break recaptcha for current users when upgrading. We need a backwards compatible way to introduce v3. We also need PR to docs.

2019-05-17 14:16 UTC, codaabraham commented
@stianst I will introduce an option to use the old version too & will get back with the PR to update the documentation.

2019-09-11 16:58 UTC, stianst commented
I would like to see this added, but a few things should be addressed first. @codaabraham are you still interested in working on this PR?

2019-09-11 17:01 UTC, codaabraham commented
@stianst  I would like to work on this PR. I will push the changes by this weekend.

2019-09-11 21:59 UTC, codaabraham commented
@stianst  Updated PR, Now reCAPTCHA is backward-compatible. Raised PR to update documentation also. [Link](https://github.com/keycloak/keycloak-documentation/pull/736)

2019-09-23 19:48 UTC, douglaspalmer commented
Sorry, I don’t have bandwidth for this sprint.

> On Sep 12, 2019, at 6:22 AM, Bruno Oliveira da Silva <notifications@github.com> wrote:
> 
> Thanks. @abstractj <https://github.com/abstractj> could someone from your team review this properly please?
> 
> @douglaspalmer <https://github.com/douglaspalmer> could you please review?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub <https://github.com/keycloak/keycloak/pull/5949?email_source=notifications&email_token=AAE4Z4PPSMN77CP2ISFKBR3QJI7BLA5CNFSM4G7LVFS2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD6R3OSY#issuecomment-530822987>, or mute the thread <https://github.com/notifications/unsubscribe-auth/AAE4Z4NSTBN5MCOPO72PLW3QJI7BLANCNFSM4G7LVFSQ>.
>

2019-09-24 06:42 UTC, vmuzikar commented
Hello @codaabraham and thanks for your contribution!

If I understand it correctly, this can potentially break backward compatibility and migration. Should we have some high level migration test just to cover the captcha config created in older Keycloak version works after migration to newer version? AFAIK we don't have any integration tests for this, so no need for any sophisticated test. Just something simple that would verify
1) The older reCAPTCHA is used after migration.
2) The Admin Console works properly after migration.

Would it make any sense, @stianst?

2019-09-24 06:55 UTC, stianst commented
@vmuzikar there's no migration, but rather just backward compatiblity. As such the test doesn't need to be a migration test, but rather just a reCaptcha test that uses the old config approach.

2019-09-24 06:59 UTC, vmuzikar commented
@stianst Yeah, maybe not true migration test. Just something that would create reCAPTCHA config in old Keycloak and then upgraded to new Keycloak and check it's not broken.

2019-09-26 08:22 UTC, stianst commented
@codaabraham any chance you could work on some testing for this PR? @vmuzikar can probably give you some good pointers on what you'd need to do.

2019-09-30 12:52 UTC, vmuzikar requested changes
@codaabraham Thanks again for your contribution! I've tried to thoroughly test your changes and found some issues especially with upgrade.

**Upgrade breaks previous reCAPTCHA configuration**
1. Configure reCAPTCHA (v2) in older Keycloak version (e.g. 7.0).
1. Upgrade Keycloak to the version with your changes. I.e. build distribution from your fork and follow the [upgrade instructions](https://www.keycloak.org/docs/7.0/upgrading/#_install_new_version).
1. Try to use the reCAPTCHA, i.e. navigate to the Registration page.
1. Error 500 appears with [this exception in the server log](https://gist.github.com/vmuzikar/02461473d3dbaa0d291bd60a14d62991).
1. Reload the page.
1. Registration form now appears but reCAPTCHA now doesn't work (user is unable to register) because the keys were deleted from the reCAPTCHA configuration. You need to re-enter the keys in the Admin Console.

There's also one more issue. Let's say you want to migrate from v2 to v3. This is normally possible just by switching the version and entering new keys but when you upgrade Keycloak (like stated in the steps above), the reCAPTCHA config is in some weird state and v3 doesn't work (similar exception as in 4.). In order to use v3 after Keycloak upgrade you need to completely remove the reCAPTCHA config and create it again.

**UX improvement suggestion**
In the Admin Console, could we dynamically hide "reCAPTCHA Score" and "reCAPTCHA Action" when v2 is selected? Those field are relevant only for v3 so no need to for them to be visible for v2.

**Testing**
Since this PR introduces some new complexity, we should have some tests for it. Something like:
1. Verify the upgrade doesn't brake previous configuration. We don't currently have any true "upgrade tests" but as a workaround you could import a realm previously exported from older Keycloak version – just manually create a test realm, configure reCAPTCHA (with some dummy keys), export it and use it in test like e.g. [here](https://github.com/keycloak/keycloak/blob/6aa90963614d607e1bc4ba83300007bf2d96d9af/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/authz/UmaDiscoveryDocumentTest.java#L48). The test would then open the Registration page and check reCAPTCHA v2 is present in the source code (no need to actually test reCAPTCHA).
1. Verify both reCAPTCHA v2 and v3 is present on the Registration page. In the test, configure reCAPTCHA v2 and check it's present. The same for v3. Both versions have different source code so this would check it works as its supposed to. (Again, no need to actually test reCAPTCHA.).

@codaabraham Let me know if you need any help with this. Thank you!

2019-10-01 14:17 UTC, codaabraham commented
Thanks @vmuzikar! I will review this today and will get back to you if I have any issues.

2019-10-18 09:38 UTC, vmuzikar commented
@stianst Is there any update since my last review? :) I believe not, correct?

2019-11-06 10:22 UTC, abstractj commented
@codaabraham do you still would like to work on this?

2019-12-02 10:28 UTC, mkurte commented
Anyone knows whats the status here?

2019-12-12 18:27 UTC, mjallday commented on services/src/main/java/org/keycloak/authentication/forms/RegistrationRecaptcha.java
> +                    if(userScore > configScore){
> or >= ?. seems like >= would be more logical since i don't see any help text saying that the user score needs to be _above_ the threshold.

2019-12-13 11:15 UTC, yyunikov commented
Any updates on this PR? reCAPTCHA v3 support would be really useful

2019-12-20 12:24 UTC, stianst commented
We need to refactor the support for captcha. There should be a CaptchaSPI that allows to plugin any captcha solution to the pages where it makes sense. That would at least be registration and password reset.

The Captcha provider should be able to load JS scripts onto the page, as well as a HTML fragment. Then it should have a verify method that is called when submitting the form.

We should keep the current reCaptcha provider as is, then add a new one for reCaptcha v3, instead of trying to make both work from the same code. 

We should also consider something non-Google.

2019-12-20 12:26 UTC, stianst commented
A basic captcha could just be to do some expensive JavaScript calculation on the client-side (something that takes 500 ms). That could be sufficient in many cases.

2020-01-08 18:13 UTC, seseso commented
This should be also available (maybe optionally through configuration) on login page and not just registration?

2020-01-10 13:20 UTC, closed without merging

2020-09-16 07:22 UTC, spetar commented
Is there any news on this issue ?
reCAPTCHA v3 support would be very useful, more user friendly and more secure.
It should be possible to use as you configure it (on registration and also on **sign-in** page and other flows/pages).

2021-02-17 21:14 UTC, aidachami-qc commented
Is there any update about the integration of reCAPTCHA v3?

2023-11-25 08:01 UTC, edulix commented
Still no recaptcha v3 in keycloak. Sad.

2023-11-25 14:19 UTC, jonkoops commented
See https://github.com/keycloak/keycloak/pull/24223