Update authentification to accept Basic Auth
keycloak/keycloak pull request #5975
Opened 2019-04-03 08:51 UTC by NizarSteria

We use keykcloak-4.5.0.Final. Can you please update this pull request in this release 4.5.0.Final :)

The ideal idea is to make another parameter in admin ui keycloak to choice the mode of authentification.

Please give me a feed back about this idea.

Thank you for help

2019-04-04 17:38 UTC, pedroigor commented
@NizarSteria, I understand the motivation for this given that OAuth 2.0 specs is open in regards to the client authentication mechanism.

I agree that a config option in the broker configuration is the best thing to do. The reasons are:

* It is not recommended to use two mechanism in the same request (basic + client/secret).
* We should support both mechanisms

2019-04-04 17:41 UTC, pedroigor requested changes

2019-04-04 17:41 UTC, pedroigor commented on services/src/main/java/org/keycloak/broker/oidc/AbstractOAuth2IdentityProvider.java
> +            String authHeader = "Basic " + new String(Base64.encodeBytes(auth.getBytes()));
You can reuse code from here `org.keycloak.util.BasicAuthHelper#createHeader`.

2019-05-15 13:17 UTC, stianst commented
I'm going to close this issue as we don't have any demand for it. In the current state the PR introduces breaking compatibility issues, as well as breaking integration with social providers.

From our POV there is little difference if basic or param is used, so unless this is needed to interract with an IdP that only supports basic there is no need for this.

Feel free to re-open, but please address following first:

* Create a JIRA
* Configurable whether to use basic or params for custom OIDC provider. Where params should be the default option.
* Tests added

2019-05-15 13:17 UTC, closed without merging