KEYCLOAK-8062 - use givenName instead of cn for rhds
keycloak/keycloak pull request #5976
Opened 2019-04-03 16:17 UTC by slominskir

Fixes the default First Name Mapper for LDAP vendor Red Hat Directory Server to use "givenName" instead of "cn".

2019-05-15 10:57 UTC, mposolda commented
@slominskir Thanks for the PR. I think it is good, however I fear there is risk of break some of our automated tests with the RHDS. There is currently no easy way to run the LDAP tests with RHDS (and all other servers) against the PR, but we're working on have such capability in near future (hopefully within 2 months or so). Will get back to this PR then. Sorry and thanks for the understanding.

2019-09-20 09:10 UTC, stianst commented
@mposolda can we somehow review this PR now?

2019-09-23 10:58 UTC, mposolda commented
@stianst IMO nothing changed regarding this PR. I think it is potential that some automated tests will be broken with RHDS when we add this, so IMO we should wait until we have easy way to test PRs with all LDAP servers, which currently doesn't work.

The PR changes the default behaviour, but it's possible to configure the behaviour later anyway by manually change LDAP mapper. So the PR shouldn't block anyone and it's not a big priority.

2019-09-26 08:24 UTC, stianst commented
@mposolda ok, we either need a plan to get this tested and merged, or we need to reject it. We can't just leave it around indefinitively

2019-09-26 10:38 UTC, mposolda commented
@stianst I expect "Hold" label is exactly something, which is used for PRs, which can't be currently merged due waiting for some other external thing (like environment for testing etc) ?Is there any maximum time for which PR can be "Hold" ? I wasn't expecting any maximum time like this exists and I don't see much issues with having open "Hold" PR for longer time.

The possibility of having ability to easily run tests can be clarified with @pdrozd . But I guess this won't be available before mid of November...

@slominskir Did you have ability to run LDAP tests with RHDS in your environment and see if they work?

2019-09-26 11:33 UTC, slominskir commented
@mposolda We are using Red Hat Identity Manager (IdM) to manage our internal network, and IdM includes RHDS (which is based on 389).    Since Red Hat has an upstream project for Keycloak, Red Hat SSO, should someone from their group look at this?  I assume someone affiliated with Red Hat is a contributor to Keycloak and has access to Red Hat Directory Server?   I did test this change manually.

2019-09-26 13:03 UTC, mposolda commented
@slominskir TBH we currently have issues with easily running LDAP tests against RHDS. If you have opportunity to do it in your environment, it can be nice.

2019-09-26 18:45 UTC, slominskir commented
@mposolda I'm not familiar with the automated tests Keycloak uses for RHDS, and getting them running sounds like a whole separate project.  I'm not in a position to take that on right now.

2020-05-04 15:42 UTC, mposolda commented
@slominskir Do you please have a chance to rebase this PR to the latest master? We have automated a way to run LDAP automated tests against PRs, so we will be finally able to run the tests and see if your PR doesn't introduce regressions to the testsuite.

2020-05-04 18:55 UTC, slominskir commented
@mposolda I think I've rebased this, though I probably went around the long way - I reset hard the whole thing then used cherry-pick to replay the original commit.    I probably should have this change on a patch branch.  Oh well.

2020-05-05 20:05 UTC, mposolda requested changes
@slominskir I've tried to run LDAP tests in our environment for 2 times. And as I expected, there are unfortunately test failures/errors when testing with "rhds10" . The results from both runs for rhds10 were those:
```
[ERROR] Tests run: 86, Failures: 1, Errors: 73, Skipped: 5
```

So the PR can't be merged as is. It seems it will require some changes in the testsuite (possibly revert default "rhds10" mappers for some tests and replace them with the same mappers as used right now before this PR is merged).

2020-05-05 20:09 UTC, mposolda commented
https://keycloak-jenkins.com/view/pipelines/job/universal-test-pipeline-server/1725/

@slominskir Sorry, you won't be able to see the build above. I've added it just for tracking purposes.

2020-05-18 13:42 UTC, mposolda commented
@slominskir I need to close this as it breaks the existing LDAP tests.  Feel free to re-open in case you want to revisit this, but this will require a plan for have tests passing with RHDS.

Unfortunately this is kind of the issue when the change itself is quite easy task, but the major effort would be to change the testsuite to work with all the vendors (and especially with RHDS) with no test failures.

2020-05-18 13:42 UTC, closed without merging

2020-05-18 15:05 UTC, slominskir commented
This seems backwards.  We can't fix a bug because the test framework doesn't work.   You are right, the fix is trivial, so why not just apply it.  The fact that the test suite is a mess is a problem, but a separate one.