[KEYCLOAK-10159] display users in roles
keycloak/keycloak pull request #6024
Opened 2019-04-29 14:29 UTC by unly

Currently the listing of users of a role is only supported for realm roles. Client roles lack this feature. This PR is adding a listing for client roles in the admin web console.
https://issues.jboss.org/browse/KEYCLOAK-10159

2019-06-24 11:02 UTC, unly commented
Hi @abstractj have you had a look at this pr?

2019-06-25 18:52 UTC, abstractj commented
@douglaspalmer  could you please review when you get the chance?

2019-06-25 18:53 UTC, abstractj commented
@unly unfortunately not yet, but I'm asking more people to take a look, once it adds some changes to our themes.

2019-07-17 12:32 UTC, stianst commented
@abstractj can you get someone to review this please? It's been around for quite some time now with now feedback from us and it looks like a very straightforward review and quality PR so should be quick.

2019-07-17 14:49 UTC, abstractj reviewed
@stianst @unly the changes look good to me and they make sense. Thinking about usability. I just wonder whether or not we should keep it in a single place for example:

## Roles
| Realm Roles | Client Roles | Default Roles |
|-------------|--------------|---------------|

Where the *Client Roles* tab would display all the client roles available.

This is just my personal opinion and not a blocker to get it merged.

@stianst what do you think?

2019-07-18 14:57 UTC, stianst commented
@abstractj I'm not quite following your suggestion, can you explain it a bit more? 

Just to make sure I fully understand this. Currently it is possible to list realm roles, click on a specific realm role, then click on users in role to see a list of users that has that role. However, that is missing for client roles. This PR adds the same for those, where you go to a client, click roles, open the role you want to look at, then click on users in role.

Unless I've misunderstood something that seems a valid approach to me. I've never liked the concept of client roles at all, but that's a whole different issue ;)

2019-07-18 15:05 UTC, stianst submitted a review, later dismissed
LGTM - non-binding approval though as I haven't reviewed it properly ;)

2019-07-18 18:01 UTC, abstractj commented
> @abstractj I'm not quite following your suggestion, can you explain it a bit more?
> 
> Just to make sure I fully understand this. Currently it is possible to list realm roles, click on a specific realm role, then click on users in role to see a list of users that has that role. However, that is missing for client roles. This PR adds the same for those, where you go to a client, click roles, open the role you want to look at, then click on users in role.
> 
> Unless I've misunderstood something that seems a valid approach to me. I've never liked the concept of client roles at all, but that's a whole different issue ;)

The approach is valid, just wondered whether or not we should have the client roles in a single place (a new tab), as we do for realm roles. So people would know where to look. Anyways, not a blocker.

2019-07-18 18:02 UTC, abstractj submitted a review, later dismissed

2019-07-18 18:41 UTC, ssilvert requested changes

2019-07-19 10:56 UTC, unly commented on themes/src/main/resources/theme/base/admin/resources/js/controllers/clients.js
> +
@ssilvert you were right. this code isn't needed and I deleted it

2019-07-19 10:56 UTC, unly commented
Applied the requested changes and rebased on the master. Feel free to have another look

2019-07-19 13:52 UTC, ssilvert approved these changes

2019-07-19 13:52 UTC, merged

2019-07-19 13:52 UTC, ssilvert commented
Merged.  Thanks for the contribution!