KEYCLOAK-9944 Add Primary Key Constraint into RESOURCE_URIS table
keycloak/keycloak pull request #6039
Opened 2019-05-09 17:29 UTC by hmlnarik

2019-05-09 18:26 UTC, pedroigor approved these changes

2019-05-10 22:03 UTC, vramik approved these changes

2019-05-13 05:14 UTC, vramik requested changes
unfortunately DBLockTest fails with mariadb_galera: https://keycloak-jenkins.com/job/test-keycloak-jpa/DB=mariadb_galera_101,jdk=local_openjdk8,label_exp=rhel7_large/109/consoleFull

2019-05-13 10:42 UTC, vramik approved these changes
The problem is also with daily build, so it's unrelated to this, thanks.

2019-05-13 10:43 UTC, merged