KEYCLOAK-9936 Added optional extension to preprocess SAML authentication
keycloak/keycloak pull request #6044
Opened 2019-05-16 06:06 UTC by gideonray

Added optional extension to pre-process SAML authentication allowing custom authenticators flexibility to handle custom requests, SAML extensions and other behavior.

The code should be extensible to support other types of requests.

2019-05-23 16:05 UTC, gideonray commented
@hmlnarik , how can i trigger the CI pipeline again?

2019-05-28 20:48 UTC, gideonray commented
hi @stianst ,

How can i trigger CI pipeline again?
Seems like the failed test is not related to my code changes. Thanks

2019-08-09 16:16 UTC, gideonray commented
Hi @hmlnarik , did you get the chance to review this PR? It would really help if we can have this feature in keycloak. Thanks.

2019-09-12 21:43 UTC, hmlnarik requested changes
Thank you for the PR! I like the idea of ability to add custom hook into early SAML request processing.

I suggest to keep this simple and not introduce too abstract `AuthenticationPreprocessor` SPI, and rather start directly with `SamlAuthenticationPreprocessor` SPI. This SPI would live e.g. in `org.keycloak.protocol.saml.preprocessor` package. The `SamlAuthenticationPreprocessor` should rather contain a method that takes a parameter of type `SAML2Object` instead of `T`. This would be called with appropriate parameter from `loginRequest()` and `idpInitiatedSSO()` (as it is now).

Perhaps the `SamlAuthenticationPreprocessor` could actually have two methods - one with `AuthenticationSessionModel` and `SAML2Object` parameters for login scenario, and `UserSessionModel` and `SAML2Object` for logout scenarios.

Note that this also needs to be called from respective methods in `org.keycloak.broker.saml.SAMLEndpoint` class. That is going to be a bit tricky, since the `AuthenticationSessionModel` is only available in the `org.keycloak.services.resources.IdentityBrokerService.authenticated(BrokeredIdentityContext)`. But inside this method, the response would be available inside the context in `SAML_LOGIN_RESPONSE` data, so I believe even here it should be possible to call the SAML authentication preprocessor.

2019-10-08 09:38 UTC, hmlnarik requested changes
@gideonray Thank you for the changes. I went through them deeply and tried to clear the interface a bit. With the current way, it turned out to be overly overloaded, more descriptive names would be beneficial both for the SPI implementors and better for usage. Could you please update the PR per the inline review comments.

2019-10-14 07:50 UTC, hmlnarik reviewed
Thanks @gideonray , I like your changes! Once you address the two minor comments in JavaDoc and squash all the commits into a single one, I believe this PR can be merged.

2019-10-14 07:50 UTC, hmlnarik commented on services/src/main/java/org/keycloak/protocol/saml/preprocessor/SamlAuthenticationPreprocessor.java
> +     */
Please add a comment to `@param clientSession` that it would be `null` if client is not applicable (specifically when used within identity broker)

2019-10-14 07:50 UTC, hmlnarik commented on services/src/main/java/org/keycloak/protocol/saml/preprocessor/SamlAuthenticationPreprocessor.java
> +     */
Please add a comment to @param clientSession that it would be null if client is not applicable (specifically when used within identity broker)

2019-10-16 18:25 UTC, gideonray reviewed
Thank you @hmlnarik for your feedback. I just squashed all commits, let me know if additional changes are needed.

2019-10-23 07:29 UTC, hmlnarik commented
Please see https://github.com/gideonray/keycloak/pull/1 for suggested changes

2019-10-29 10:03 UTC, hmlnarik approved these changes

2019-10-29 10:04 UTC, hmlnarik commented
Thank you @gideonray!

2019-10-29 12:07 UTC, merged