[KEYCLOAK-8104] Keycloak SAML Adapter does not support clockSkew conf…
keycloak/keycloak pull request #6050
Opened 2019-05-17 16:24 UTC by steevebtib

…iguration

2019-05-22 08:15 UTC, vramik requested changes
@steevebtib thank you a lot for the PR. I've noticed there is no integration tests. Would you have time to write some? I can help you with those if needed or I can add some myself. 

Otherwise it looks good to me, I've got few minor things.

2019-05-22 08:15 UTC, vramik commented on adapters/saml/core/src/main/java/org/keycloak/adapters/saml/config/parsers/DeploymentBuilder.java
> +    private int convertClockSkewInMillis(int duration, TimeUnit unit) {
I'd suggest to just cut the rest from nanoseconds and microsecods, It'd simplify the method. We also doesn't need `long` here, `int` would be sufficient. And the INFO log message with value in ms should be added.
```suggestion
    private int convertClockSkewInMillis(int duration, TimeUnit unit) {
        int durationMillis = (int) unit.toMillis(duration);
        switch (unit) {
            case NANOSECONDS:
            case MICROSECONDS:
                log.warn("Clock skew value will be rounded down.");
            default:
                log.info("Clock skew set to " + durationMillis + "ms.");
        }
        return durationMillis;
    }
```

2019-05-22 08:54 UTC, steevebtib commented on adapters/saml/core/src/main/java/org/keycloak/adapters/saml/config/parsers/DeploymentBuilder.java
> +        sso.setRequestBinding(SamlDeployment.Binding.parseBinding(sp.getIdp().getSingleSignOnService().getRequestBinding()));
in fact, this was related to a previous commit that I fetched after my initial pull, I will see how I can remove my updates on those lines

2019-05-22 08:55 UTC, steevebtib commented
I can try to write integration test, could you please explain how to proceed?

2019-05-23 06:59 UTC, vramik commented
@steevebtib 

> I can try to write integration test, could you please explain how to proceed? 

I'll create sample test and send it to you. Then you can add more tests according this one, does that work for you? Maybe we could create another task for tests, I'm not sure, @hmlnarik wdyt?

> I guess that I should amend and force push for the requested modifications right?

Exactly, thank you

2019-05-23 07:57 UTC, steevebtib commented
@vramik 
> @steevebtib
> 
> > I can try to write integration test, could you please explain how to proceed?
> 
> I'll create sample test and send it to you. Then you can add more tests according this one, does that work for you? Maybe we could create another task for tests, I'm not sure, @hmlnarik wdyt?
That's ok for me, thank you for your feedback, I will wait for you then.

2019-05-23 08:07 UTC, hmlnarik commented
> I'll create sample test and send it to you. Then you can add more tests according this one, does that work for you? Maybe we could create another task for tests, I'm not sure, @hmlnarik wdyt?

The tests need to be part of the same task, please keep it in the same PR.

Side note - if you prefer, the PR can contain several commit while in progress. These would need to be squashed into a single one before final review and merge.

2019-06-04 08:26 UTC, steeveborc commented
@vramik 
Do you confirm that the integration tests for this use case go to package **org.keycloak.testsuite.saml** inside of project **integration-arquillian-tests-base** ? This is the place I have found by browsing your source and documentation

2019-06-04 14:30 UTC, vramik commented
@steeveborc I've opened [PR](https://github.com/steevebtib/keycloak/pull/1) to your fork with example test, pls read comments there.

2019-06-12 12:31 UTC, hmlnarik commented
@steevebtib Would you please have time to continue work on this PR?

2019-06-12 16:20 UTC, steevebtib commented
@hmlnarik I have implemented the changes, I will try to implement integration test tomorrow as Vlasta has provided an example.

2019-06-19 05:50 UTC, hmlnarik commented
@steevebtib Before submitting the next round of changes, please rebase to latest upstream master

2019-06-19 07:28 UTC, steevebtib commented
@hmlnarik ok I will do

2019-06-21 09:13 UTC, vramik commented
@steevebtib to make the travis pass this [commit](https://github.com/keycloak/keycloak/pull/6050#issuecomment-495109831) needs to also backported, thanks

2019-06-21 09:16 UTC, steevebtib commented
@vramik yes I have fetched your latest update, and then I will rebase on latest upstream master

2019-06-21 09:17 UTC, vramik commented on testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/servlet/SAMLClockSkewAdapterTest.java
> +    public void testErrorExample() throws Exception {
nit: the test method name was meant to be changed, I was sending it as an example for you to make it easier for you add another tests.

2019-06-21 09:17 UTC, vramik commented on testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/servlet/SAMLClockSkewAdapterTest.java
> +    public void testSuccessExample() throws Exception {
dtto

2019-06-21 09:18 UTC, vramik commented
@steevebtib thanks, I've added two more comments regarding test names, but those are rather nits. Thanks

2019-06-25 08:26 UTC, vramik commented
Hello @steevebtib, would you have possibility to continue with this one?

2019-06-25 08:34 UTC, steevebtib commented
Hello @vramik, I should have more time tomorrow to continue on this, I have merged your latest updates, but not updated the tests yet either rebased on upstream

2019-06-26 15:40 UTC, steevebtib commented
Hello @vramik, I have modified the tests and added a new one, and got all the latest changes, I am just checking again all tests

2019-06-27 08:03 UTC, hmlnarik commented
@steevebtib Feel free to submit the changes here, the automation will do the testing for all the app servers for you. Should there be any issue, we will be happy to help, but I believe that it will pass just fine.

Also please consider including the following line in the commit message since @vramik developed the testsuite support for clock skew testing delivered in this PR:
```
Co-Authored-By: vramik <vramik@redhat.com>
```

2019-06-27 08:16 UTC, steevebtib commented
@hmlnarik I have done all the requested changes and force pushed, I hope it will be fine for you.

2019-07-01 06:22 UTC, hmlnarik commented
@steevebtib Thank you, overall the PR looks good. It is now being checked.

2019-07-08 07:36 UTC, vramik commented
@steevebtib I've opened https://github.com/steevebtib/keycloak/pull/3 with fix for tomcat and jetty app servers, once that one is merged and rebased to latest upstream master, it's good to go in. Thanks

2019-07-10 11:26 UTC, hmlnarik commented
@steevebtib Could you please merge the steevebtib/keycloak#3 and squash the commits? Once this is ready, the PR can be merged.

2019-07-11 13:37 UTC, steevebtib commented
@hmlnarik Hi, sorry I was too busy the last days, I didn’t have time to check but I will do tomorrow

2019-07-15 11:06 UTC, vramik approved these changes

2019-07-15 11:08 UTC, hmlnarik approved these changes
Thanks @steevebtib

2019-07-15 11:08 UTC, merged