KEYCLOAK-9895 Fix wrongly called assertCurrent method
keycloak/keycloak pull request #6065
Opened 2019-05-22 13:14 UTC by mhajas

2019-05-22 15:26 UTC, vramik requested changes
@mhajas thanks, it looks good to me.

2019-05-22 15:26 UTC, vramik commented on testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/example/fuse/EAP6Fuse6HawtioAdapterTest.java
> +        waitUntilUrlStartsWith(testRealmLoginPageFuse.toString(), 60);
I'd suggest the same approach used in FuseAdapterTest 

- https://github.com/keycloak/keycloak/commit/ac6d877954a01ad77de8ae7826fa398612eadd96#diff-0811a74e7c159fc73e1604954ca77456R89
- https://github.com/keycloak/keycloak/commit/ac6d877954a01ad77de8ae7826fa398612eadd96#diff-0811a74e7c159fc73e1604954ca77456R137
- https://github.com/keycloak/keycloak/commit/ac6d877954a01ad77de8ae7826fa398612eadd96#diff-0811a74e7c159fc73e1604954ca77456R119

2019-05-23 06:43 UTC, vramik approved these changes

2019-05-23 08:41 UTC, hmlnarik approved these changes

2019-05-23 08:41 UTC, merged