KEYCLOAK-10696 - fixed missing client role attributes after import
keycloak/keycloak pull request #6115
Opened 2019-06-21 14:49 UTC by br0xpl

Fixed issue https://issues.jboss.org/browse/KEYCLOAK-10696

2019-06-25 18:47 UTC, abstractj requested changes
@br0xpl I appreciate you took the time working on it, but I would like to request integration tests for it. Also, see more comments in the code.

2019-06-25 18:48 UTC, abstractj commented on server-spi-private/src/main/java/org/keycloak/models/utils/RepresentationToModel.java
> -    public static void updateClientProtocolMappers(ClientRepresentation rep, ClientModel resource) {
All the tests on Travis are broken, because this method was removed. Could you please elaborate more on why we have to remove this?

2019-06-25 20:08 UTC, br0xpl reviewed
> @br0xpl I appreciate you took the time working on it, but I would like to request integration tests for it. Also, see more comments in the code.

Will soon try to add the integration tests for the client role attributes.

2019-06-25 21:53 UTC, br0xpl commented
@abstractj : Added integration tests, removed the strange deleted lines, added null check. Please verify.

2019-07-18 11:05 UTC, br0xpl commented
@abstractj can we proceed?

2019-10-13 18:17 UTC, br0xpl commented
@abstractj  are you there?
@pedroigor  can you check this PR, as @abstractj seems to be not available for some time. 

Thanks

2020-01-17 20:00 UTC, douglaspalmer approved these changes
LGTM

2020-02-10 15:22 UTC, abstractj approved these changes
Managed to run all the tests and code looks good.

@br0xpl thanks for submitting this and I'm sorry it took too long. I will fix all the conflicts and handle this.

2020-02-10 17:47 UTC, abstractj commented
@br0xpl rebased your PR here https://github.com/keycloak/keycloak/pull/6761 keeping the authorship. For now I'm closing this PR because it was superseded by the new one.

2020-02-10 17:47 UTC, closed without merging