KEYCLOAK-10734 Let the check-sso feature do the check in hidden iframe
keycloak/keycloak pull request #6131
Opened 2019-06-27 12:18 UTC by dasniko

This is yet a _work-in-progress_ PR for https://issues.jboss.org/browse/KEYCLOAK-10734, based on the discussions in https://github.com/keycloak/keycloak/pull/5932

Still no tests and still no documentation.

Similar to the originating PR, it's necessary to specifiy a `silentCheckSsoRedirectUri` at the KC.init() method and providing a valid endpoint at the specified uri within the application of course (e.g. like documented here: https://github.com/keycloak/keycloak-documentation/pull/600/files#diff-e17f71a40a51038c46666bac2e71268dR160).

I'd like to discuss, if this yields into the right direction (@stianst ?)

2019-06-28 05:54 UTC, stianst commented
Approach looks good, haven't had a chance to review code deeply or try it out, but looks like the right approach. I will be on holiday for the next two weeks, but will be happy to review it when I get back.

2019-07-31 14:27 UTC, yashnalla commented
Hi @stianst, wanted to reach out and see what the progress on this PR is? Is there anything I can do/contribute to  push this along?

2019-07-31 15:07 UTC, mhajas commented
Hello @yashnalla, unfortunately, @stianst won't be available for some time. I will do a review ASAP probably tomorrow and then discuss within the team whether we need to wait for him or we can merge it.

2019-08-01 14:45 UTC, yashnalla commented
@mhajas Great Thanks!

2019-08-05 16:48 UTC, yashnalla commented
@mhajas  any updates??

2019-08-14 08:57 UTC, mmaryo commented
I'm waiting this feature :+1:

2019-08-14 13:32 UTC, ryelo commented
We're waiting on this too. Anything we can do to help?

2019-08-14 16:02 UTC, mhajas requested changes
To be honest, I do not like the way of redirecting back to a user-provided webpage, I think it should be somehow provided by Keycloak. However, I am not able to come up with any other solution than we currently have as redirecting to a page on Keycloak side doesn't make sense. We can leave it as it is and possibly improve later.

Besides that^ I am missing two things here:
- We need to create a docs PR, where should be an example of silent-check-sso.html
- A test with checkLoginIframe set to false and silentCheckSsoRedirectUri set for both calls of init function

2019-08-14 18:41 UTC, yashnalla commented
@mhajas I'm gonna start doing those now, should I just open a new pr for them?

2019-08-14 18:57 UTC, dasniko commented
I was on vacation until now... sorry for not responding.

The discussion about the target of the redirect, whether it's user- or keycloak-provided, we had already in #5932 

The docs PR wouldn't be a problem, I can do this in the next two days.

For the tests I need some help. No matter what I do or configure, my tests won't fail (I want failing tests first to proof the correct implementation). I guess it's because the `unchanged` variable of the `checkLoginIframe().success(function (unchanged)...)` promise is always `true` in the test scenarios.
Testing it manually in the browser, all works well and I also get "failing tests" when configuring/acting contrary to plan.
If anybody knows how to do it in the automated test scenario, I would be thankful.

2019-08-15 14:00 UTC, mhajas commented
@dasniko Hey, I just realized the test actually doesn't get into checkSsoSilently function at all. The test, as it is now, works like this:

1. calling init -> keycloak and adapter session doesn't exists -> unchanged variable is true because iframe returned '[unchanged](https://github.com/keycloak/keycloak/blob/master/adapters/oidc/js/src/main/resources/login-status-iframe.html#L57)'

2. redirect to login page and login
3. Calling init again, however, redirect URL from keycloak contains valid flow query parameters which mean onload function [won't be called at all](https://github.com/keycloak/keycloak/blob/master/adapters/oidc/js/src/main/resources/keycloak.js#L194).

What you need to do in the test is something like that:

````java
    @Test
    public void testSilentCheckSso() {
        JSObjectBuilder checkSSO = defaultArguments().checkSSOOnLoad();
        testExecutor.init(checkSSO, this::assertInitNotAuth)
                .login(this::assertOnLoginPage)
                .loginForm(testUser, this::assertOnTestAppUrl)
                .init(checkSSO, this::assertSuccessfullyLoggedIn)
                .refresh()
                .init(checkSSO.add("silentCheckSsoRedirectUri", authServerContextRootPage + JAVASCRIPT_URL + "/silent-check-sso.html"),
                                this::assertSuccessfullyLoggedIn);
    }
````

The `refresh()` call will refresh the webpage, which results in changing adapter session value into '', and loginIframe will result in '[changed](https://github.com/keycloak/keycloak/blob/master/adapters/oidc/js/src/main/resources/login-status-iframe.html#L32)'  message and you get false for the unchanged variable.

We should also add a test which looks like that:
````java
    @Test
    public void testSilentCheckSso() {
        JSObjectBuilder checkSSO = defaultArguments().checkSSOOnLoad();
        testExecutor.init(checkSSO.add("silentCheckSsoRedirectUri", authServerContextRootPage + JAVASCRIPT_URL + "/silent-check-sso.html"), this::assertInitNotAuth)
    }
````

this ensures that checkSso feature won't redirect a user to the login page and it won't authorize user as Keycloak session doesn't exist.

2019-08-16 06:01 UTC, dasniko commented
Thanks for the help @mhajas !
I added some tests, docs will follow.

2019-08-19 12:39 UTC, mhajas commented
@dasniko Tests now seems better. I have just two comments (I suggest changes in https://github.com/mhajas/keycloak/commit/4a1a02483e3f7b954ff61b3f5c5c472f87caa03d):

1. `.add("checkLoginIframe", false)` doesn't work because JSObjectBuilder enquotes `false` value.
2. At the moment `testSilentCheckSsoNotAuthenticated` doesn't test silentCheckSso because onLoad function ends up [here](https://github.com/keycloak/keycloak/pull/6131/files#diff-f41a82d32ba240c5165fc1ee64741068R196). I would say this is correct behavior as it doesn't make sense to silently check-sso, if we already know we are not logged in from CheckLoginIframe. We need to add `.add("checkLoginIframe", false)` in order to end up [here](https://github.com/keycloak/keycloak/pull/6131/files#diff-f41a82d32ba240c5165fc1ee64741068R203).

2019-08-20 13:24 UTC, dasniko commented
@mhajas I added your suggestions.

2019-08-20 13:49 UTC, mhajas approved these changes

2019-08-20 18:40 UTC, abstractj approved these changes

2019-08-20 18:41 UTC, merged

2019-08-21 17:15 UTC, mohsinilyas commented
When is the next release that this feature would be part of keycloak, so that we can use it?

2019-08-21 20:45 UTC, yashnalla commented
@mohsinilyas I can't answer questions about keycloak-js's release cycle but as a stop-gap measure but we cloned the most recent changes in keycloak/keycloak and are creating our own version until these features are released

2019-08-21 21:09 UTC, abstractj commented
> When is the next release that this feature would be part of keycloak-js, so that we can use it?

Hopefully soon. The release announcement will be available on the mailing list, please be patient and keep an eye on it.

2019-08-23 13:22 UTC, mohsinilyas commented
Can you also tell me that when I try to init keycloak with 'check-sso', iframe doesn't seem to work for me. As I have opened the application in one tab and in other tab I have opened keycloak but when I logout of keycloak my application doesn’t get logout, however, if I use ‘login-required’ the application logs out simultaneously with keycloak. Do you know any reason for this guys?

2020-02-21 09:44 UTC, RomainWilbert commented
I could figure out if this feature is available in the latest version :(

2020-02-21 12:41 UTC, abstractj commented
> I couldn't figure out if this feature is available in the latest version :(

@RomainWilbert  for these kind of questions, please use keycloak-user mailing lists which is the appropriate medium. We do not monitor comments on merged pull-requests.