KEYCLOAK-10849 KeycloakRole equals only with itself
keycloak/keycloak pull request #6173
Opened 2019-07-15 09:23 UTC by Valeran86

I use Keycloak Spring Adapter (KSA) to secure existing application. Today I realized that some functions didn't work anymore because of security checking like this:
```
GrantedAuthority adminRole = new MySpecialGrantedAuthority( "superadmin" );
for ( GrantedAuthority role : userRoles ) {
        if ( role.equals( adminRole ) ) {
          return true;
        }
      }
```
In this example, when I use KSA authorization fails.
I believe, that more preferable in `KeycloakRole` use this implementation of `equals` method.

Previous discussion:
https://github.com/keycloak/keycloak/pull/6113

2019-08-02 13:05 UTC, pedroigor commented
@Valeran86, could you just change the commit message to `[KEYCLOAK-10849] - KeycloakRole equals only with itself`. After that, I'll just merge :)

2019-08-02 13:05 UTC, pedroigor requested changes
Missing reference to JIRA in commit message. After that we can merge.

2019-08-06 03:53 UTC, Valeran86 commented
@pedroigor, thanks for your reply. I apologize for long time of answer. Now I changed commit message as you recommended :)

2019-08-15 18:41 UTC, abstractj commented
@Valeran86 could you please rebase your PR with the changes from master? Seems like Travis is stable again.

2019-08-16 03:37 UTC, Valeran86 commented
@abstractj , Hi! Yep, sure.

2019-08-16 08:19 UTC, abstractj approved these changes

2019-08-16 08:20 UTC, merged