KEYCLOAK-10875 Adding quotes around the path to the JAR in case %DIRNAME% contains spaces
keycloak/keycloak pull request #6179
Opened 2019-07-17 12:33 UTC by tpodom

Adding quotes around path to JAR to handle the scenario where Keycloak is installed to C:\Program Files\Keycloak

2019-08-01 08:23 UTC, vmuzikar requested changes
Hello @tpodom,
thank you for your contribution! Overall it looks good to me. However, there are some issues with the tests.

Everything is ok (both auth-server-undertow and auth-server-wildfly) when the tests are executed from a path that *does not* contain spaces (i.e. keycloak repo is checked out to e.g. `C:\keycloak`).

**Failures with auth-server-undertow and spaces in the path**
The following tests are failing when the path contains spaces (i.e. keycloak repo is checked out to e.g. `C:\keycloak with spaces`):
```
[ERROR] Failures:
[ERROR]   KcAdmSessionTest.test:40->AbstractCliTest.assertExitCodeAndStreamSizes:43 exitCode == 0 expected:<0> but was:<1>
[ERROR]   KcAdmUpdateTest.testUpdateIDPWithoutInternalId:57->AbstractCliTest.assertExitCodeAndStdErrSize:39->AbstractCliTest.assertExitCodeAndStreamSizes:43 exitCode == 0 expected:<0> but was:<1>
[ERROR]   KcAdmUpdateTest.testUpdateThoroughly:83->AbstractCliTest.assertExitCodeAndStdErrSize:39->AbstractCliTest.assertExitCodeAndStreamSizes:43 exitCode == 0 expected:<0> but was:<1>
```
Command used: `mvn clean test -f .\testsuite\integration-arquillian\tests\base\ '-Dtest=org.keycloak.testsuite.cli.admin.**'`

**Failures with auth-server-wildfly and spaces in the path**
The testsuite doesn't run at all - failing on: `WFLYSRV0073: Invalid option 'with'`. This issue may be out of scope of this PR. WDYT @hmlnarik?
Command used: `mvn clean test -f .\testsuite\integration-arquillian\tests\base\ -Pauth-server-wildfly '-Dtest=org.keycloak.testsuite.cli.admin.**'`

I believe the most important for us is that the tests are passing without any spaces in the path. However, we need some way how to specifically test KEYCLOAK-10875 which is currently not possible. @tpodom Do you think you could try and fix the test failures?

Also FYI - `kcreg.bat` is affected by the same bug, created [KEYCLOAK-10974](https://issues.jboss.org/browse/KEYCLOAK-10974) for it.

2019-09-20 10:42 UTC, stianst commented
@vmuzikar the change looks okay to me. Is it currently already failing with "The following tests are failing when the path contains spaces"? seems like this is an improvement and that there are some separate issues in the testsuite?

2019-09-20 12:44 UTC, vmuzikar commented
@stianst You're correct that the test failures with spaces in the path are a separate issue. However, this issue is blocking us from (automatically) test this PR (if it really fixes what's it supposed to fix).

The only solution to avoid fixing tests in this PR I can see is to manually reproduce the tests that failed with Undertow (with Wildfly all tests failed). The thing is, do we really want to avoid fixing the tests for now? Because until it's fixed, we're unable to test it for regression.

2019-09-20 13:09 UTC, stianst commented
I think fixing the test is a low priority in this case and shouldn't be a blocker for this issue. I'd say as long as we can get someone with a windows machine to confirm it doesn't work with spaces currently and that this fixes it we're good to merge it. Anything else I feel this will just sit in the backlog for ever.

2019-09-20 15:40 UTC, vmuzikar approved these changes
@stianst In that case I'm going to approve this. As far as I can tell, LGTM (tested on a Windows machine). Also I've created a follow-up task for the tests: https://issues.jboss.org/browse/KEYCLOAK-11522

2019-09-26 08:28 UTC, merged