KEYCLOAK-10782: Credentials tab on clients can only be displayed with view-realm
keycloak/keycloak pull request #6235
Opened 2019-08-12 08:17 UTC by rmartinc

PR for KEYCLOAK-10782. I have requested "query-clients" for those two endpoints, if you think "view-clients" or "manage-clients" should be used instead just let me know (I was not sure what to requests, so I did more or less the same than in KEYCLOAK-9489).

2019-08-20 12:09 UTC, pedroigor requested changes

2019-08-20 12:09 UTC, pedroigor commented on services/src/main/java/org/keycloak/services/resources/admin/permissions/RealmPermissionEvaluator.java
> +    void requireViewClientAuthenticatorProviders();
I'm not sure if you need both methods but just a single one ? I would keep `requireViewClientAuthenticatorProviders`.

2019-08-20 12:09 UTC, pedroigor commented on services/src/main/java/org/keycloak/services/resources/admin/permissions/RealmPermissions.java
> +    public void requireViewClientAuthenticatorProviders() {
Same thing here. I think we should keep `requireViewClientAuthenticatorProviders`.

2019-08-20 12:09 UTC, pedroigor commented on services/src/main/java/org/keycloak/services/resources/admin/permissions/RealmPermissions.java
> +        if (!(canViewRealm() || root.hasOneAdminRole(AdminRoles.QUERY_CLIENTS))) {
Don't you also need to include `VIEW_CLIENTS` and `MANAGE_CLIENTS` roles ?

2019-08-20 12:11 UTC, pedroigor commented
@rmartinc, sorry for the late reply. I think `query-clients` is OK but you also need to consider `VIEW_CLIENTS` and `MANAGE_CLIENTS`.

2019-08-20 15:03 UTC, rmartinc commented
@pedroigor No problem Pedro, I have added only the  "requireViewClientAuthenticatorProviders" method and the condition now checks the three client perms (I just copied what it was done in the other case). I added some more tests to check that everything works. Check if now it's OK.

2019-08-20 22:15 UTC, pedroigor commented
@rmartinc looks good now. Thanks for the tests too. I'll run your changes now and see if everything is OK.

2019-09-06 19:44 UTC, pedroigor approved these changes

2019-09-06 19:45 UTC, merged