KEYCLOAK-11227 Removed enabled/disabled flag from Providers
keycloak/keycloak pull request #6284
Opened 2019-09-02 08:30 UTC by slaskawi

https://issues.jboss.org/browse/KEYCLOAK-11227

This Pull Requests removes "disabled" flag usages from Providers. This check if already performed by `DefaultKeycloakSessionFactory`.

I used the following expressions to hunt all the expressions:

```
grep -lir \"enabled\" --include="*ProviderFactory.java"
grep -lir \"disabled\" --include="*ProviderFactory.java"
```

@hmlnarik mentioned that we might need a migration mechanism here. After thinking about this for a while, I'm  not convinced. I believe mentioning it in the Release Notes should be enough.

2019-09-20 10:00 UTC, stianst commented
This is introducing a breaking change I believe. For vault we can make the change as it has not been released, but for the truststore we need migration otherwise it can break existing installs.

Take a look at https://www.keycloak.org/docs/latest/server_installation/index.html#_truststore. It documents disabled as a supported property, while now we are asking people to use enabled instead. That means we need to add to the migration cli script to migrate this. We also would need to double check that disabled property is the equivalent of disabling the provider. Taking a quick look at the code I'm not convinced.

I would suggest splitting this PR into two. One fixing it for vault providers as they can be fixed without considering migration so we can get that fixed before we do 8.0.0 release. Second on the truststore, which probably will end up being more work than it's worth though.

2019-09-20 10:00 UTC, stianst requested changes
See comment

2019-09-23 11:11 UTC, slaskawi commented
> We also would need to double check that disabled property is the equivalent of disabling the provider. Taking a quick look at the code I'm not convinced.

@stianst Could you please elaborate why?

2019-09-24 12:49 UTC, slaskawi commented
I double checked and it seems @mhajas removed it from `PlainTextVaultProviderFactory` already. So this PR can be re-purposed to cleaning up `FileTruststoreProviderFactory.java` and providing a small migration script.

2019-09-25 13:13 UTC, slaskawi commented
@stianst @hmlnarik I managed to repurpose this PR to target only the Trust Store provider. I also added a short migration script to automatically change necessary flags.

2019-10-15 03:24 UTC, stianst approved these changes

2019-10-15 03:24 UTC, merged