KEYCLOAK-10907 Add configurable token settings per client
keycloak/keycloak pull request #6309
Opened 2019-09-12 02:06 UTC by y-tabata

[specification]
- Like "Access Token Lifespan", the following settings can be overridden per client.
  - Revoke Refresh Token
  - SSO Session Idle
  - SSO Session Max
  - Offline Session Idle
  - Offline Session Max
- The above values are set by the "Advanced Settings" of [Settings] tab in each client view on Admin Console.
- To be able to override the above values, some behaviors of UserSession and AuthenticatedClientSession are changed.

  [Administrator operation]

  1. Delete user session using Admin Console or Admin CLI or Admin REST API.
    -> UserSession and the all AuthenticatedClientSessions in the UserSession are deleted. This behavior is not changed.

  [User operation]

  2. Delete own user session using [Sessions] > [Logout All Sessions] in User Account.
    -> UserSession and the all AuthenticatedClientSessions in the UserSession are deleted. This behavior is not changed.

  3. Frontchannel logout with SSO Cookie (KEYCLOAK_IDENTITY).
    -> UserSession and the all AuthenticatedClientSessions in the UserSession are deleted. This behavior is not changed.

  [Client operation]

  4. Backchannel logout with the refresh token.
    -> UserSession and the all AuthenticatedClientSessions in the UserSession are deleted. This behavior is not changed.

  5. Token refresh with the refresh token.
    -> Check expiry time per client and delete AuthenticatedClientSession which is expired. When all AuthenticatedClientSessions in the UserSession are deleted, delete the UserSession.
This is a new behavior.

  6. Token introspection with the refresh token.
    -> Check expiry time per client and delete AuthenticatedClientSession which is expired. When all AuthenticatedClientSessions in the UserSession are deleted, delete the UserSession.
This is a new behavior.

  [Keycloak itself]

  7. Check expiry time of session periodically and delete session which is expired.
    -> Check expiry time per client and delete AuthenticatedClientSession which is expired. When all AuthenticatedClientSessions in the UserSession are deleted, delete the UserSession.
This is a new behavior.

JIRA ticket is the following.
https://issues.jboss.org/browse/KEYCLOAK-10907

2019-09-12 11:48 UTC, stianst reviewed
I'm not in favour of adding these options to the clients. Sessions are shared between multiple clients for web-based flows. For other application types it would probably be better to have a realm option to configure different session timeouts for different client types, rather than for individual clients.
 
Could you please describe a use-case where this is necessary?

2019-09-17 02:14 UTC, y-tabata commented
@stianst For API management purpose, "Realm" is generally created per resource server, and "Client" is created per client application. And client applications are not the same level (i.e. security level, alliance level, development level), so there are often cases we'd like to set the different session timeout for each client, just like we'd like to set the different OAuth 2.0 authorization grant for each client. In those cases, we have to prepare multiple realms with almost all settings are the same up until now. This is troublesome so we created this PR.

2019-09-17 10:19 UTC, stianst commented
Controlling session timeouts is not a great way to address that use-case properly though. What you want is 1) ability to require user to re-authenticate if more than N days since authenticated, which is already supported, and 2) ability to step-up authentication for clients with higher security levels (i.e. asking only for two factor for some clients).

Controlling session timeout per client makes no sense, but what could make sense is to add.an option to set max auth timeout directly on the client in case you are using a library that doesn't support setting max_age in the authorization request

2019-09-18 01:38 UTC, y-tabata commented
@stianst This is not single sign-on purpose but API management purpose, so sessions are not shared among clients.
For example the case of cloud-native application systems, there are various client applications. And generally, a realm manager or a resource server manager tends to set a different timeout to tokens per client in order to deal with clients as a suitable way in accordance with its property.
Before, we can set a different timeout to "access token" per client but cannot set a different timeout to "refresh token" per client. This PR enables setting a different timeout to "refresh token" per client.

The "max_age" is set by clients, and we resource server cannot force to set the client refresh token expiration, so not suitable for our requirement.

2019-09-18 09:55 UTC, stianst commented
I'm still not following your use-case. Sessions and refresh token timeouts are not relevant to resource servers though, they are relevant to clients that obtain the tokens.

This approach is not a great solution regardless and would just cause confusion and potentially weird behaviour. Please start a thread on the dev ML clearly describing your use-case and separately explain your proposed solution.

2019-09-18 09:56 UTC, stianst requested changes
Use-case needs to be described and discussed on ML. Accepting these configuration options as is on a client is not going to be accepted, so we need to understand the use-case and discuss how it can be solved in a better way.

2019-09-19 10:28 UTC, closed without merging