KEYCLOAK-10975: Clock skew configuration in keycloak-saml.xml can't be found in the keycloak-saml subsystem
keycloak/keycloak pull request #6328
Opened 2019-09-20 06:59 UTC by rmartinc

Fix for KEYCLOAK-10975. @sguilhen I have taken the following decisions:

1. The format of the clock skew is a bit strange for the CLI structure, there is no direct mapping for that. So we had two options: setting an inner element `AllowedClockSkew` with the attribute `unit` and something like `value`; setting both at `IDP` level. I decided to use the latter because I think it's easier to understand. But we can change to the other option if you prefer.
2. I have tested expressions but removed them after that. Allow expressions is false in everything so I think it's better to track it down in another JIRA.
3. There is specific test for testing this in both versions.

As always, if you see something wrong or you prefer another decision, just let me know.

2019-09-20 08:31 UTC, rmartinc commented
Ah! And I have used the same 1.2 version for the subsystem. If it's needed to bump to new 1.3 more changes are needed. But I suppose we can use the same version if there is no new version of keycloak.

I forgot to mention this point in the description.

2019-09-20 17:05 UTC, sguilhen commented
@rmartinc thanks for taking this, I'm replying to your comments inline:

> Fix for KEYCLOAK-10975. @sguilhen I have taken the following decisions:
> 
> 1. The format of the clock skew is a bit strange for the CLI structure, there is no direct mapping for that. So we had two options: setting an inner element `AllowedClockSkew` with the attribute `unit` and something like `value`; setting both at `IDP` level. I decided to use the latter because I think it's easier to understand. But we can change to the other option if you prefer

Don't you mean the former here? The XSDs have a new element with the unit attribute. I prefer this approach of having an element instead of adding two distinct (but related) attributes directly in the IDP.

The biggest issue here is that whatever format we have in the subsystem it must match the format of the keycloak-saml.xml that is read by the adapter. When they start, the subsystems simply invoke their XML writer to write their own model back into XML and then they store this XML as a String in a ServeltContext init param. When one of the adapters run, they first check if this param is set and if it is they use it to read the adapter config instead of looking for the keycloak-saml.xml file.

For example, check what the as7-eap6 adapter does here: https://github.com/keycloak/keycloak/blob/master/adapters/saml/as7-eap6/subsystem/src/main/java/org/keycloak/subsystem/saml/as7/KeycloakAdapterConfigDeploymentProcessor.java#L124

And then, for example, the undertow adapter here: https://github.com/keycloak/keycloak/blob/master/adapters/saml/undertow/src/main/java/org/keycloak/adapters/saml/undertow/SamlServletExtension.java#L72

What this means is that the adapters first check if the subsystem has already provided the configuration before trying to load keycloak-saml.xml but the formats of both XMLs must be identical or the adapter parser won't be able to read it. The bottom line is that if you change how the clock skew is configured in the subsystem you must also make sure to change the xsd in the adapter core so the XML formats match.

> 2. I have tested expressions but removed them after that. Allow expressions is false in everything so I think it's better to track it down in another JIRA.

I'm fine with that, this is consistent with the rest of the config.

> 3. There is specific test for testing this in both versions.
Great, this is good!

> As always, if you see something wrong or you prefer another decision, just let me know.

You've also mentioned the XSD not being bumped and I think it is fine as long as the current version has not yet been included in a Final release.

2019-09-20 17:06 UTC, sguilhen requested changes
Make sure the XSDs of the subsystems and the SAML core adapter match - failure to do so implies in subsystems producing configs that cannot be read by the adapters.

2019-09-20 17:59 UTC, rmartinc commented
OK @sguilhen I'll use the second option. But the generated XML is identical to the one in the external {{keycloak-saml.xml}} (I know that the idea behind the subsystem is producing the same exact XML to be used as deployment config just in the same way). The difference between both options is only at CLI level. But if you think the second option is better, don't worry, I'll try to implement it the next week.

I think that in the XSD there are more differences, for example the {{HttpClient}} in {{IDP}} element is also missed in the subsystem. But that is another JIRA in my opinion.

2019-09-20 18:04 UTC, sguilhen commented
> OK @sguilhen I'll use the second option. But the generated XML is identical to the one in the external `keycloak-saml.xml` (I know that the idea behind the subsystem is producing the same exact XML to be used as deployment config just in the same way). The difference between both options is only at CLI level. But if you think the second option is better, don't worry, I'll try to implement it the next week.

Ah, I see now what you mean. Indeed the XMLs are the same. I think this is fine the way you did, no need to switch to the other option, I'm fine with it.

> 
> I think that in the XSD there are more differences, for example the `HttpClient` in `IDP` element is also missed in the subsystem. But that is another JIRA in my opinion.

Yeah. I noticed that too. I'm trying to check all the differences that exist between kc-saml.xml and the subsystems, certainly to be covered by a separate Jira.

2019-09-20 18:05 UTC, sguilhen approved these changes

2019-09-20 19:54 UTC, rmartinc commented
@sguilhen I have realized that the `unit` CLI option is lost if the real value is not set. SO it's better the second option. Don't merge this, remove the approve. I'll change to the second option, it's almost the same. I'll provide the change the next week. Have a nice weekend.

2019-09-20 21:35 UTC, sguilhen requested changes
Waiting for changes from @rmartinc

2019-09-23 06:44 UTC, rmartinc commented
Done! It was almost the same. Now there is an optional `AllowedClockSkew` object with a compulsory `value` and an optional `unit`. The rest is more or less the same. I can work in the `HttpClient` addition if you want.

2019-09-24 15:55 UTC, sguilhen approved these changes
@hmlnarik I'm approving this PR, it looks good to me.

2019-09-24 15:56 UTC, sguilhen commented
> Done! It was almost the same. Now there is an optional `AllowedClockSkew` object with a compulsory `value` and an optional `unit`. The rest is more or less the same. I can work in the `HttpClient` addition if you want.

@rmartinc I left a comment in Jira about this. I've also been tracking the discrepancies between the core XML and the subsystems configuration. Let's handle that as part of a different Jira.

2019-09-27 07:34 UTC, hmlnarik approved these changes
Thank you @rmartinc and @sguilhen !

2019-09-27 07:35 UTC, merged

2019-10-21 15:24 UTC, davidcblaney commented
Hi, 

Is this assigned to a release? This is currently stopping us using ADFS without manually changing the ADFS servers time (testing only ;) )? 

Thanks,
David

2019-10-21 15:40 UTC, rmartinc commented
Check the JIRA: https://issues.jboss.org/browse/KEYCLOAK-10975
The change is expected in next version 8.0.0, but you can always use the parameter in the `keycloak-saml.xml` of the application. It was missed in the subsystem configuration (`standalone.xml` or `domain.xml`).

2019-10-21 15:52 UTC, davidcblaney commented
Thanks for your quick reply, I'll keep an eye on it.

Is there anywhere in the docs where it explains how I can do:

> but you can always use the parameter in the keycloak-saml.xml of the application. 

I have seen the issue that introduced this configuration option but I don't know how to apply it, that's what brought me here assuming this was not actually available yet. 

Thanks in advance.

2019-10-21 16:06 UTC, rmartinc commented
It's in the [doc](https://www.keycloak.org/docs/latest/securing_apps/index.html#_saml-general-config), just use the `AllowedClockSkew` inside the `IDP`, you have an example [here](https://github.com/keycloak/keycloak/blob/master/adapters/saml/core/src/test/resources/org/keycloak/adapters/saml/config/parsers/keycloak-saml-with-allowed-clock-skew-default-unit.xml). This configuration is not taken into account if you set the clock skew at server (subsystem) level because of this issue, but it works in the `keycloak-saml.xml` file since 7.0.0.

Please use the keycloak user mail-list for asking questions like this one.

Regards!