KEYCLOAK-8779: Partial export and import to an existing realm is breaking clients with service accounts
keycloak/keycloak pull request #6331
Opened 2019-09-24 09:05 UTC by rmartinc

Hi,
Changes for KEYCLOAK-8779 and related KEYCLOAK-6987. It's the import side of the KEYCLOAK-4923. Add @ssilvert for the review if possible (both PRs are quite related).

The solution just adds three things:

1. The authorization resource server was missed in the import. The import of the resource server is checked to also import the authz information if it's there.
2. The service account of a client is deleted when overwrite is selected for the import. If not, the service account remains in the system and it can trigger issues later on if the client activates services accounts again. This is the issue for KEYCLOAK-6987, in this JIRA the client is imported without the service account, so the old service account remains but the client ID is different, so when the server tries to create the new service account it conflicts in name with the old one).
3. Tests for the above two changes.

After working on this PR I realized that it modifies different classes (KEYCLOAK-4923 modifies export, and this one import). So it can reviewed at the same time.

2019-09-26 17:19 UTC, pedroigor submitted a review, later dismissed

2019-09-26 17:21 UTC, pedroigor commented
@mhajas From a test suite perspective, the tests look/run fine. If you are OK about the tests herein we can merge it.

2019-10-01 08:33 UTC, mhajas requested changes
Besides one comment in code, I have one question. It seems like the PR is not addressing whole described issue. I tried following steps:
1. Create client and enable authz
2. Create a Role policy and add it to default permission 
3. Export realm (including roles and clients)
4. Remove client created in step 1
5. Import file exported in step 3
6. For me the client has authz enabled, however no changes made in step 2 are imported

Is this correct? @rmartinc  @pedroigor

2019-10-01 09:26 UTC, rmartinc commented
Hi,
I have moved the resource server sample configuration to an external file that is loaded as a static property. This is just done in order to set something in the authz configuration and check that it is still there after the client import (it was lost before).

Regarding the first question, you are right. This PR only fixes the import part because I first worked in KEYCLOAK-4923 (the export part). So in order to export the service accounts you need also the other PR. The other PR is:

https://github.com/keycloak/keycloak/pull/6313

And that's why I commented at first comment to assign this issue to the same reviewer. Sorry but I started working in KEYCLOAK-4923 and later I tested KEYCLOAK-8779 (they are very related).

2019-10-01 10:50 UTC, mhajas commented
@rmartinc thank you and sorry I missed your comment here. Will look at it again.

2019-10-02 09:46 UTC, mhajas approved these changes
Thanks for extracting to separate json file. Looks good to me. https://github.com/keycloak/keycloak/pull/6313 should be probably merged first.

2019-11-06 11:41 UTC, abstractj commented
@douglaspalmer could you please review when you get the chance?

2019-12-27 18:58 UTC, pedroigor approved these changes

2019-12-27 18:59 UTC, merged

2019-12-27 19:01 UTC, pedroigor commented
@rmartinc thanks.