KEYCLOAK-11633 Order clientId and roles in role-selector.html
keycloak/keycloak pull request #6359
Opened 2019-10-06 06:01 UTC by jermarchand

https://issues.jboss.org/browse/KEYCLOAK-11633

In the modal to select roles, "realm Roles", "clientId" and "client roles" are not sorted.

2019-11-06 10:24 UTC, abstractj commented
@vmuzikar I just wonder if we gonna break the console tests with these changes. When you get the chance could you please review?

2019-11-06 10:28 UTC, vmuzikar commented
@abstractj I believe the main risk here is that this PR is potentially conflicting with https://github.com/keycloak/keycloak/pull/6320. Am I correct? Maybe this PR is even not needed if https://github.com/keycloak/keycloak/pull/6320 is merged as it heavily changes how client roles are selected.

2019-11-06 10:42 UTC, abstractj commented
> @abstractj I believe the main risk here is that this PR is potentially conflicting with #6320. Am I correct? Maybe this PR is even not needed if #6320 is merged as it heavily changes how client roles are selected.

@vmuzikar I can be wrong, but this PR is about sorting clientId and roles, while #6320 is about pagination. Thinking a bit about this, I just wonder if the sorting of clientId and roles should return from the server, instead of adding it to the UI. 
//cc @ssilvert

2019-11-06 10:46 UTC, vmuzikar commented
@abstractj The thing is #6320 also replaces all client selectors in Admin Console as a by-product. The selectors are then searchable.

Good point with server-side sorting though. +1 on it.

2019-11-06 11:37 UTC, abstractj requested changes
@jermarchand thanks for submitting this. After talking with @vmuzikar we both agreed that it would be better to add sorting on the server-side. The UI should be used only to display data, and we try to avoid any logic on it unless it's required.

Also, if you would like to move forward with this change, I'd appreciate if you review the changes at https://github.com/keycloak/keycloak/pull/6320 and join the discussions there. There's a slight chance that your PR becomes superseded by the changes there and your help would be really welcome reviewing.

2019-11-14 10:47 UTC, abstractj commented
@stianst when you get the chance, please take a look at my comments and also @vmuzikar review. I'm afraid to say that we shouldn't move forward with this change, unless we do it on the server side.

2019-11-22 11:44 UTC, stianst commented
As we have PR open for pagination of clients and another PR for pagination of roles it will be required to do the ordering on the server-side, and that will be required in those PRs before they can be merged.

So we should not do client-side pagination, as it simply won't work in combination with server-side pagination.

2019-11-22 11:44 UTC, closed without merging