KEYCLOAK-10977 Allow disabling Kerberos athentication with LDAP feder…
keycloak/keycloak pull request #6422
Opened 2019-10-24 09:22 UTC by spahrson

…ation provider

As mentioned in the issue [KEYCLOAK-10977](https://issues.jboss.org/browse/KEYCLOAK-10977) there is a problem keep the Kerberos authentication disabled using a LDAP federation provider with Kerberos settings. Evertime a LDAP sync is triggered the Kerberos Authentication gets enabled again.

I created a fix for this behavior by adding an extra check to the `CredentialsHelper` to avoid switching the Authenticator execution if it's already disbaled. IMHO this is sufficient to fix the problem without any side effects. 

We checked this using an AD integration and it works fine so far.

2019-10-24 15:40 UTC, mposolda commented
I agree that what you describe in KEYCLOAK-10977 is a bug. When the switch "Allow Kerberos authentication" is turned to ON, then authenticator execution should be switched to ON. So this is working correctly. But during sync, it shouldn't be switched.

I am not sure if you're fixing it this way in your PR, but I see that there are some failing tests. Those should be fixed for sure as it seems that you introduced some regression in the behaviour.

2019-10-29 07:25 UTC, spahrson commented
I dived a little bit depper into the code about federation. The source of the problem is IMHO the fact, that after each sync `onUpdate` and therefore a "resetting" of the switch get called. But as a Keycloak user I  need to have the same configuration before and after a sync. It's ok to switch the authentication after removing or creation of a new ldap federation provider. 
A corresponding use-case would be to have mutlitple authentication flows (e.g. browser-flows) for different clients. for one client we want to have Kerberos enabled, for another not. Thats currently not achievable.
My first solution was symptom fighting. If we remove the call for `org.keycloak.utils.CredentialHelper#setOrReplaceAuthenticationRequirement()` at `onUpdate` it could be a proper solution for the cause? I updated and tested my PR for this proposal.

2019-11-01 09:15 UTC, mposolda requested changes
@spahrson Thanks, I wonder if we can keep the "onUpdate" as well, but just change Kerberos authenticator to ALTERNATIVE in case that kerberos switch was really enabled during this update? This is possible as we know the old component. In other words:
- during create of the provider with the "allowKerberos" switch enabled, the ALTERNATIVE will be enabled
- during update of the provider with the "allowKerberos" switch enabled and "allowKerberos" switch disabled in the old component, the ALTERNATIVE on the authenticator will be enabled. As it means that admin actively enabled kerberos during this update
- during update of the provider with the "allowKerberos" switch enabled and "AllowKerberos" switch enabled in the old component too, nothing will be updated on the authenticator. As it means that admin didn't change anything. This means that during sync, the switch will be kept disabled and also the changes you did in UserStorageRestTest will still work.

2019-11-08 10:07 UTC, spahrson commented
@mposolda Thanks. I understand your remarks and I changed my code. But I hade to improve the test class too, it was not sufficient.

2019-11-18 13:12 UTC, mposolda approved these changes
@spahrson Thanks

2019-11-18 13:12 UTC, merged