[KEYCLOAK-11821] add the account api roles to the client on creation
keycloak/keycloak pull request #6426
Opened 2019-10-25 07:47 UTC by unly

Potential fix for https://issues.jboss.org/browse/KEYCLOAK-11821.

2019-11-01 12:41 UTC, stianst commented
This only solves the problem when there is a brand new installation of Keycloak, but doesn't address the problem for existing users that want to migrate their database.

2019-11-05 11:46 UTC, stianst requested changes
We need to consider what to do for existing realms. Perhaps the simplest would be to just always add these roles even if the endpoints are preview.

Also, we need some tests to make sure things are added as expected.

2019-11-05 13:07 UTC, unly commented
Hey @stianst thanks for getting back. Since the Account API is still under development, I added the required roles just on the creation on a new realm when the feature is enable. Reading your comment I assume you prefer to always have those roles even though users might not use the preview feature at all. So far, I left this out. This would require a migration in the database for existing realms. When you agree on this I can try to provide the scripts and the requested tests.

2019-11-07 13:06 UTC, stianst commented
+1 Let's just add the roles always as it simplifies things, and there's no big side-effects of having them there even with the account endpoints disabled.

2019-11-20 09:49 UTC, unly commented
Hi @stianst I added the three required roles for the account api to the migration to 8.0.0. Can you please have another look at it

2019-11-22 14:51 UTC, stianst commented
@unly afraid 8 is release already, so migration need to go to 9 :(

2019-11-22 14:54 UTC, stianst commented
Didn't review the rest, but will do that early next week

2019-12-18 12:14 UTC, stianst requested changes
Some minor comments. We also need a migration test added.

2019-12-18 12:14 UTC, stianst commented on server-spi-private/src/main/java/org/keycloak/migration/migrators/MigrateTo9_0_0.java
> +        RoleModel manageAccountRole = accountClient.getRole(AccountRoles.MANAGE_ACCOUNT);
Manage account shouldn't be a composite role. Instead the rest endpoints should check for both manage account and manage consent roles. I believe this was already added

2019-12-18 12:14 UTC, stianst commented on server-spi-private/src/main/java/org/keycloak/migration/migrators/MigrateTo9_0_0.java
> +        ClientModel accountClient = realm.getClientByClientId(Constants.ACCOUNT_MANAGEMENT_CLIENT_ID);
Extract into a separate method, something like "addAccountRoles(RealmModel realm)"

2020-01-10 07:27 UTC, stianst commented
@unly are you able to address the minor comments and add a migration test?

2020-01-10 09:46 UTC, unly commented
@stianst thanks for reminding :) i missed it after a couple days off. I added some tests but the travis test still seem to fail with something different

2020-01-23 08:40 UTC, stianst approved these changes

2020-01-23 08:41 UTC, stianst commented
@unly failing tests looks completely unrelated, and I can't see how your changes would have any impact on those tests, so they are likely just some unstable tests.

2020-01-23 11:38 UTC, stianst commented
Changes look good now. There was an issue in MigrateTo9_0_0 where it invokes addAccountConsoleClient instead of migrateRealmCommon, which results in realms being updated in the DB not having these roles added (see https://github.com/keycloak/keycloak/pull/6694/files#diff-8b9a09a2f90de5a0f095e0e5a0b9db23R49 for the fix).

2020-01-23 11:38 UTC, stianst commented
Opened a new PR here https://github.com/keycloak/keycloak/pull/6694 with the fix, so closing this PR.

2020-01-23 11:39 UTC, closed without merging

2020-01-27 08:07 UTC, unly commented
Thanks @stianst