[KEYCLOAK-11971] Remove credentials option from configuration
keycloak/keycloak pull request #6454
Opened 2019-11-07 13:36 UTC by jonkoops

Removal of `credentials` option following discussion in https://github.com/keycloak/keycloak/pull/6400 and on [keycloak-dev](https://lists.jboss.org/pipermail/keycloak-dev/2019-November/012808.html).

2019-11-07 13:40 UTC, stianst approved these changes

2019-11-07 13:42 UTC, abstractj approved these changes

2019-11-07 21:42 UTC, mhajas approved these changes
It looks good to me, thank you. @jonkoops Will you create also docs PR? I think this should be mentioned at least in release notes.

2019-11-08 06:47 UTC, stianst requested changes
We need to make sure we have a note in release notes and upgrade guide prior to merging this

2019-11-08 09:28 UTC, abstractj commented
@stianst @mhajas @jonkoops could you please review https://github.com/keycloak/keycloak-documentation/pull/777 ?

2019-11-08 10:36 UTC, stianst approved these changes

2019-11-08 10:36 UTC, merged

2020-06-19 06:31 UTC, jaydavid1996 reviewed
is there any alternative to enable this credentials option ?

2020-07-28 08:50 UTC, TejashreeD commented
@jaydavid1996 For now I downgraded it to 
```
    "keycloak-angular": "^6.1.0",
    "keycloak-js": "7.0.1",

```

2020-07-28 10:15 UTC, mhajas commented
@jaydavid1996 Please refer to this page: https://www.keycloak.org/community to find the best way how to approach other community/keycloak team members. 

@jaydavid1996 @TejashreeD clientSecret was removed from JS adapter for security reasons, you should never use JS adapter with a confidential client. See following keycloak-dev thread for more details: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/keycloak-dev/PJ-Cd2gzT8E/5LcxR_9FBQAJ

2020-07-28 14:27 UTC, jaydavid1996 commented
thanks guys will have a look on your recommendations 👍

On Tue, 28 Jul 2020, 6:15 pm Michal Hajas, <notifications@github.com> wrote:

> @jaydavid1996 <https://github.com/jaydavid1996> Please refer to this
> page: https://www.keycloak.org/community to find the best way how to
> approach other community/keycloak team members.
>
> @jaydavid1996 <https://github.com/jaydavid1996> @TejashreeD
> <https://github.com/TejashreeD> clientSecret was removed from JS adapter
> for security reasons, you should never use JS adapter with a confidential
> client. See following keycloak-dev thread for more details:
> https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/keycloak-dev/PJ-Cd2gzT8E/5LcxR_9FBQAJ
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/keycloak/keycloak/pull/6454#issuecomment-664956478>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AE2SF7XRDRQUIE34F6HW453R52QMBANCNFSM4JKGWGBA>
> .
>