KEYCLOAK-12000: Allow overriding time lifespans on a SAML client
keycloak/keycloak pull request #6488
Opened 2019-11-15 11:03 UTC by rmartinc

Adding a "saml.assertion.lifespan" attribute in the SAML clients in order to override default realm timestamps used in the assertion (useful for replaying it).

Things to consider:

- I have been doubting from adding one or two attributes (because in the default realm configuration two realm properties are used: AccessCodeLifespan and AccessTokenLifespan). Finally I decided that one is better because it's simpler and the smaller lifespan wins.
- I have not overridden the "SsoSessionMaxLifespan" used in the attribute "SessionNotOnOrAfter". That one is still managed by the realm. It's very big by default and I considered it as sufficient.

If you prefer to change something, just let me know.

@hmlnarik Check when you have time, there is no harry at all and the change is easy to rebase (not a lot files modified).

Thanks!

2019-11-15 14:11 UTC, stianst requested changes
Please see the thread "Session duration for clients" on dev ML. I think we should rather introduce a higher level option for setting session duration for clients, which controls the underlying bits, and not have "low" level options for OIDC/SAML separately.

2019-11-15 14:46 UTC, rmartinc commented
@stianst I was not aware of that email and I was just replicating the current OIDC behavior. Note that this change only affects the SAML assertion generation, no session max or idle. Modifying the SSO max and idle also affects how the sessions should be deleted in memory (because with your idea idle and max timeouts are different per client).

If you prefer, I can just close this PR and wait for the other idea to be implemented (but your idea is much more complicated than what I'm doing here).

Regards!

2019-11-17 12:30 UTC, hmlnarik approved these changes

2019-11-17 12:30 UTC, hmlnarik commented
@rmartinc Thank you for the PR, it looks good to me!

> I think we should rather introduce a higher level option for setting session duration for clients, which controls the underlying bits, and not have "low" level options for OIDC/SAML separately.

@stiantst The SAML handles client session validity by `AuthnStatement/SessionNotOnOrAfter` attribute and that handling has been introduced in #6161. There is no change in this regard in this PR. This PR allows setting per-client lifespan of a SAML assertion (corresponding to an access token), by that it brings SAML client settings on par with OIDC clients where one can override access token lifespan already. Could you please revisit your review?

2019-11-18 12:29 UTC, stianst commented
I don't see the comparison between access token and SAML assertion. A SAML assertion can't be refreshed so it should be valid for however long the Client Session should be valid. Further, it would be good to make this more consistent and introduce the concept of "client session durations" which can be set at the realm level, and overridden at the client level. Please see the thread "Session duration for clients" on the dev ML.

2019-11-18 15:34 UTC, hmlnarik commented
> A SAML assertion can't be refreshed so it should be valid for however long the Client Session should be valid.

I'm afraid I don't follow. The access token contains more or less same information as SAML assertion. Refreshing assertions could and perhaps should be done via ECP profile (PAOS binding). [1] That Keycloak adapters do not support this is sad, but does not change anything on that SAML assertion is functionally similar to access token, and its lifespan should be considered as such.

[1] https://docs.oasis-open.org/security/saml/v2.0/saml-profiles-2.0-os.pdf

2019-11-18 18:26 UTC, stianst commented
I guess you know my SAML knowledge is not the best ;)

My assumption for SAML was that as it's only used for authentication you basically throw away the assertion once you've setup a session in the client. Then expect a logout request to initiate the logout.

If SAML has support for backchannel refresh it makes sense to support shorter lifespan so you can "pull" the login status from the IdP, similar to what you can do with an id token.

Doesn't compare to an access token though as access tokens are used to access resources external to the client, which is a different case. 

SAML assertions are only used for authentication right? Not as a bearer token.

So it seems to me that the assertion lifespan can still be controlled by client session max/idle, rather than something different.

2019-11-18 18:58 UTC, hmlnarik commented
> I guess you know my SAML knowledge is not the best ;)

SAML is too extensive a protocol, as is OIDC where I would rely on your rather than my knowledge :) 

> My assumption for SAML was that as it's only used for authentication you basically throw away the assertion once you've setup a session in the client. Then expect a logout request to initiate the logout.

Keycloak SAML adapter can be configured to retain the assertion, and this assertion can have several audience, so it can serve as a bearer token. Actually the use case @rmartinc is requiring this PR for is exactly about forwarding the assertion. It would make a lot of sense to revisit the assertion handling in Keycloak adapters (but that's for another set of long PRs, certainly not until Dec).

> If SAML has support for backchannel refresh it makes sense to support shorter lifespan so you can "pull" the login status from the IdP, similar to what you can do with an id token.

It does, though Keycloak adapter does not use it unfortunately, and the revisiting server to improve support of ECP would be needed (not to mention an ideal case of implementing token exchange for SAML ;-) )

> Doesn't compare to an access token though as access tokens are used to access resources external to the client, which is a different case.

This is exactly the case for this PR. SAML assertions can contain desired audience just the same as OIDC tokens, and those listed might generally be outside the requestor.
 
> SAML assertions are only used for authentication right? Not as a bearer token.

They can actually be used as a bearer token since they contain lots of additional information. Hence I still think this PR is valid.

> So it seems to me that the assertion lifespan can still be controlled by client session max/idle, rather than something different.

2019-11-21 11:35 UTC, rmartinc commented
Hey @stianst @hmlnarik what is the final decision with the PR?

Checking a bit the related issue @stianst has filed, I really think that they are different issues. This PR just updates the time constraints in the SAML assertion (which by default are determined by realm AccessCodeLifespan and AccessTokenLifespan, and are usually very short for a SAML assertion replay). I asked for this because I was playing with a little PoC of a keycloak SAML client that gets the signed SAML assertion and replays it calling a CXF/wss4j endpoint deployed in a different wildfly server (SAML can reuse the assertion for other things like calling a wss secured endpoint). In this context, the modified lifespan is almost the same than the `access.token.lifespan` option used for OIDC clients.

The new JIRA [KEYCLOAK-12103](https://issues.jboss.org/browse/KEYCLOAK-12103) only mentions sso max and idle which are not even used in this PR. I think that in SAML those new parameters will only affect the session lifespan which is not modified in this PR.

But it's up to you guys, if you want I can just close the PR. I'm also progressing in the [KEYCLOAK-12001](https://issues.jboss.org/browse/KEYCLOAK-12001)  but both are quite related. I think both JIRAs are needed to do a proper SAML assertion replay.

2019-11-21 12:26 UTC, stianst commented
From @hmlnarik last response I'm thinking that this is not related to client sessions and would be a nice to have in addition. I need to have a chat with @hmlnarik though so he can educate me a bit more about SAML. I'll have a chat with @hmlnarik next week and we'll get back to you.

2019-11-21 13:01 UTC, rmartinc commented
Ok @stianst, there is no hurry for the PR. I was just doing it because [KEYCLOAK-10757](https://issues.jboss.org/browse/KEYCLOAK-10757) introduced the concept of assertion replay and I think it is very short for any real use-case without different lifespans and audience support. As @hmlnarik mentions there are room for improvement but at least with these two additions it can be used.

2019-11-26 08:58 UTC, stianst approved these changes

2019-11-26 09:02 UTC, merged