KEYCLAOK-12069: keycloak.js changes broke new account console
keycloak/keycloak pull request #6500
Opened 2019-11-18 18:40 UTC by ssilvert

KEYCLOAK-11971 broke the new account console.  This PR fixes it by:
1) Removing extra slash when requesting keycloak.js and keycloak.json
2) Making "account" be a public client.

2019-11-19 02:38 UTC, sunny728 commented
test

2019-11-19 07:17 UTC, vmuzikar commented on services/src/main/java/org/keycloak/services/managers/RealmManager.java
> +            client.setPublicClient(true);
Just a suggestion (didn't do a full review). Couldn't we do this only when account2 profile is enabled?

2019-11-19 08:57 UTC, stianst commented
Added a new PR that adds a new client account-console dedicated for the new account console here: https://github.com/keycloak/keycloak/pull/6501

2019-11-19 08:59 UTC, stianst requested changes
Proper solution is to create new public client dedicated for the new account console. Opened a PR here for that: https://github.com/keycloak/keycloak/pull/6501

2019-11-20 20:00 UTC, ssilvert commented
This PR incorporated into https://github.com/keycloak/keycloak/pull/6509.  Closing.

2019-11-20 20:00 UTC, closed without merging