KEYCLOAK-8162 Added resourcesPath
keycloak/keycloak pull request #6512
Opened 2019-11-20 16:08 UTC by vidhya03

Regarding [KEYCLOAK-8162 Attribute for Resourse path in keycloak html email
](https://issues.jboss.org/browse/KEYCLOAK-8162)

Please check the keycloak-dev email https://lists.jboss.org/pipermail/keycloak-dev/2018-September/011213.html

This PR add url.resourcesPath to the email html templates

2019-11-21 09:32 UTC, stianst requested changes

2019-11-21 09:32 UTC, stianst commented on services/src/main/java/org/keycloak/forms/login/freemarker/model/UrlBean.java
> +        return getHostPortScheme(baseURI)+ getResourcesPath();
The following should work and is much cleaner than manually building the hostname bit:

`Urls.themeRoot(baseURI).toString() + "/" + theme.getType().toString().toLowerCase() +"/" + theme.getName()`

2019-11-22 04:39 UTC, vidhya03 commented
@stianst Could you please review. Thanks

2019-11-22 09:37 UTC, stianst approved these changes

2019-11-22 09:37 UTC, merged