Remove unused method from org.keycloak.saml.common.util.DocumentUtil
keycloak/keycloak pull request #6519
Opened 2019-11-21 21:30 UTC by Captain1653

I'm not sure about PR, but maybe it makes sense. I have noticed some unusde methods in classes. It's my first attempt to clean up. If it will be useful I can create JIRA-issue and continue to remove unused methods. 
I have removed public methods, but evething was compiled. Maybe these method really unsued.

2019-11-29 21:50 UTC, hmlnarik approved these changes

2019-11-29 21:51 UTC, hmlnarik requested changes
The code looks good but please file a JIRA and ensure both the PR and commit message are prefixed with this JIRA.

2019-11-29 22:11 UTC, Captain1653 commented
@hmlnarik I have done it.

2019-12-20 14:03 UTC, hmlnarik approved these changes
@Captain1653 Thank you

2019-12-20 14:03 UTC, merged