KEYCLOAK-12094 Change to remove client sessions when the client deleted
keycloak/keycloak pull request #6554
Opened 2019-11-28 03:03 UTC by y-tabata

The problem is that client sessions were left when the client was deleted.

I changed to the following:
- When a client deleted, CLIENT_REMOVED_SESSION_EVENT is added.
- In CLIENT_REMOVED_SESSION_EVENT, client sessions are unregistered from its user session and removed.
- This is worked for both online and offline.

2019-11-28 03:32 UTC, sunny728 commented
test

2019-11-28 06:52 UTC, sunny728 commented
test

2019-12-05 18:08 UTC, mposolda requested changes
@y-tabata Thanks for the fix. I appreciate the work, however I have some doubts about the potential performance bottlenecks with this...

We have deployments with millions of user sessions and client sessions. This would mean that deleting client will need to remove many client sessions and in turn send many messsages over the network. That is the reason why "onClientRemoved" method is empty and instead removed client sessions are supposed to be handled "on-the-fly" .

So instead of this, I suggest to simply remove changes from Infinispan provider and just add null checks in RealmAdminResource . Basically something like:
```
ClientModel client = realm.getClientById(entry.getKey());
if (client != null) {
....
```

Also the test would need to be removed from UserSessionProviderTest and instead some admin REST API test, which will remove the client through REST API and then doublecheck through REST endpoints that just stats for existing clients are returned and no NPE is thrown.

2019-12-06 02:00 UTC, y-tabata commented
@mposolda I changed it as you said.

2019-12-06 09:37 UTC, mposolda approved these changes
@y-tabata Thanks!

2019-12-06 09:37 UTC, merged