KEYCLOAK-12406 Add "Client Session Max" and "Client Session Idle" for…
keycloak/keycloak pull request #6581
Opened 2019-12-09 08:20 UTC by y-tabata

… OIDC

JIRA:
https://issues.redhat.com/browse/KEYCLOAK-12103
https://issues.redhat.com/browse/KEYCLOAK-12406

# Current exp claim
## access token / ID token
  - MIN ([Access Token Lifespan] or [Client Access Token Lifespan] or [Access Token Lifespan For Implicit Flow], [SSO Session Max] or [SSO Session Max Remember Me])

## refresh token
  - MIN ([SSO Session Max] or [SSO Session Max Remember Me], [SSO Session Idle] or [SSO Session Idle Remember Me])

# Future exp claim
## access token / ID token
  - MIN ([Access Token Lifespan] or [Client Access Token Lifespan] or [Access Token Lifespan For Implicit Flow], [SSO Session Max] or [SSO Session Max Remember Me] **or [Client Session Max]**)

## refresh token
  - MIN ([SSO Session Max] or [SSO Session Max Remember Me] **or [Client Session Max]**, [SSO Session Idle] or [SSO Session Idle Remember Me] **or [Client Session Idle]**)

 - [Client Session Max] and [Client Session Idle] can be overridden per client.
 - Even if [Client Session Max] or [Client Session Idle] is set, when [Client Session Max] > [SSO Session Max] or [Client Session Idle] > [SSO Session Idle], [SSO Session Max] or [SSO Session Idle] is adopted.

# Other points
In JIRA ticket, 
> A new claim "exp_max" should be added to the Refresh Token which is set to "Client Session Max".

However, "exp_max" is not adopted because we can use the existing "exp" claim.
Currently, keycloak judges the expiration of refresh token with the "exp" claim, and if we change it to use the "exp_max" claim, the "exp" claim will be an unnecessary claim.

2019-12-19 19:53 UTC, pedroigor commented
@y-tabata Changes look good. 

The failures I suspect I related to `org.keycloak.services.managers.AuthenticationManager#isSessionValid`. There is an additional time window to consider when running Keycloak in different DCs.

I'm going to check the UI and see how it goes too.

2019-12-19 19:54 UTC, pedroigor requested changes
@y-tabata Changes look good.

The failures I suspect I related to org.keycloak.services.managers.AuthenticationManager#isSessionValid. There is an additional time window to consider when running Keycloak in different DCs.

I'm going to check the UI and see how it goes too.

2019-12-20 04:00 UTC, y-tabata commented
@pedroigor thanks! I'm not so familiar with the CrossDC tests. I would appreciate it if you would give me some advice about how to fix.

2019-12-24 20:00 UTC, pedroigor commented
@y-tabata I'm going to try locally and see how it goes.

2019-12-24 20:43 UTC, pedroigor commented
@y-tabata Try running a test like this:

```
cd testsuite/integration-arquilian
 mvn clean install -Pauth-servers-crossdc-jboss,auth-server-wildfly,cache-server-infinispan -DskipTests
```

Then:

```
cd tests/base
mvn test -B -nsu -Pcache-server-infinispan,auth-servers-crossdc-jboss,auth-server-wildfly -Dtest=SessionExpirationCrossDCTest  2>&1 |         java -cp ../../../utils/target/classes org.keycloak.testsuite.LogTrimmer
```

I think this test is quite related to the changes you are proposing, so it would make sense to start with it.

I did not investigate the cause, just passing you the commands to execute tests locally. Let me know how you go with this so I can help finding the cause.

2019-12-24 21:15 UTC, pedroigor commented
@y-tabata, I also checked master and the same test also fails there. It looks like failures are unrelated but something unstable (or not working) in cross-dc testsuite.

I'll need to talk with Marek about this and see if he knows what may be causing this.

2020-01-07 09:05 UTC, y-tabata commented
@pedroigor thanks! I'll try to run the test.

> I'll need to talk with Marek about this and see if he knows what may be causing this.

@pedroigor @mposolda If you find anything wrong, I would appreciate hearing from you.

2020-01-09 07:08 UTC, y-tabata commented
@pedroigor When I executed the below command you taught me, the below error has occurred. Do you have any idea what is wrong? The first command (`mvn clean install`) was succeeded.

Command:
```
mvn test -B -nsu -Pcache-server-infinispan,auth-servers-crossdc-jboss,auth-server-wildfly -Dtest=SessionExpirationCrossDCTest  2>&1 |         java -cp ../../../utils/target/classes org.keycloak.testsuite.LogTrimmer
```

Result:
```
-- main:
-- [INFO] ------------------------------------------------------------------------
-- [INFO] BUILD FAILURE
-- [INFO] ------------------------------------------------------------------------
-- [INFO] Total time:  29.054 s
-- [INFO] Finished at: 2020-01-09T15:43:33+09:00
-- [INFO] ------------------------------------------------------------------------
-- [ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.8:run (copy-auth-server-crossdc-nodes) on project integration-arquillian-tests-base: An Ant BuildException has occured: C:\Users\user\git\keycloak-dev\testsuite\integration-arquillian\tests\base\target\containers\auth-server-wildfly does not exist.
-- [ERROR] around Ant part ...<move todir="C:\Users\user\git\keycloak-dev\testsuite\integration-arquillian\tests\base\target/containers/auth-server-wildfly-crossdc01">... @ 4:144 in C:\Users\user\git\keycloak-dev\testsuite\integration-arquillian\tests\base\target\antrun\build-main.xml
-- [ERROR] -> [Help 1]
-- [ERROR]
-- [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
-- [ERROR] Re-run Maven using the -X switch to enable full debug logging.
-- [ERROR]
-- [ERROR] For more information about the errors and possible solutions, please read the following articles:
-- [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

2020-01-09 08:27 UTC, mposolda commented
@y-tabata Hi, I am not 100% sure, but you may also first need to build distribution. So before running the tests suggested by @pedroigor in this comment, you can also try to run this in the `keycloak` directory:
```
mvn clean install -DskipTests=true -Pdistribution
```
After it is successfully finished, you can continue with the commands suggested by @pedroigor in this comment - https://github.com/keycloak/keycloak/pull/6581#issuecomment-568800525

2020-01-10 00:37 UTC, y-tabata commented
@mposolda thanks!
I ran the commands suggested by @pedroigor after [1] was successfully finished, but the result was the same. I ran them in both the Windows environment and the UNIX environment, the result was the same.

[1] `mvn clean install -DskipTests=true -Pdistribution`

Result:
```
-- main:
-- [INFO] ------------------------------------------------------------------------
-- [INFO] BUILD FAILURE
-- [INFO] ------------------------------------------------------------------------
-- [INFO] Total time:  16.238 s
-- [INFO] Finished at: 2020-01-10T09:21:34+09:00
-- [INFO] ------------------------------------------------------------------------
-- [ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.8:run (copy-auth-server-crossdc-nodes) on project integration-arquillian-tests-base: An Ant BuildException has occured: /root/keycloak/testsuite/integration-arquillian/tests/base/target/containers/auth-server-wildfly does not exist.
-- [ERROR] around Ant part ...<move todir="/root/keycloak/testsuite/integration-arquillian/tests/base/target/containers/auth-server-wildfly-crossdc01">... @ 4:124 in /root/keycloak/testsuite/integration-arquillian/tests/base/target/antrun/build-main.xml
-- [ERROR] -> [Help 1]
-- [ERROR]
-- [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
-- [ERROR] Re-run Maven using the -X switch to enable full debug logging.
-- [ERROR]
-- [ERROR] For more information about the errors and possible solutions, please read the following articles:
-- [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

```
$ ls target/containers/
auth-server-undertow           auth-server-wildfly-crossdc11  keycloak-client-tools
auth-server-wildfly-crossdc01  auth-server-wildfly-crossdc12
auth-server-wildfly-crossdc02  cache-server-infinispan
```

2020-01-10 06:55 UTC, y-tabata commented
When I ran [1] before [2], the `auth-server-wildfly does not exist` error was disappeared, and a similar error [3] to Travis's one was displayed.
However, when I ran them with the master branch, almost the same error [4] was displayed.
I wonder my local environment is wrong or the test is wrong.


[1] cp -r servers/auth-server/jboss/wildfly/target/unpacked/keycloak-9.0.0-SNAPSHOT tests/base/target/containers/auth-server-wildfly
[2] mvn test -B -nsu -Pcache-server-infinispan,auth-servers-crossdc-jboss,auth-server-wildfly -Dtest=SessionExpirationCrossDCTest  2>&1 |         java -cp ../../../utils/target/classes org.keycloak.testsuite.LogTrimmer

[3] Result (KEYCLOAK-12406 branch): 
```
-- [INFO] Results:
-- [INFO]
-- [ERROR] Failures:
-- [ERROR]   SessionExpirationCrossDCTest.testClearDetachedClientSessions:549->createInitialSessions:163->lambda$createInitialSessions$0:173 expected:<11> but was:<21>
-- [ERROR]   SessionExpirationCrossDCTest.testClearDetachedOfflineClientSessions:580->createInitialSessions:163->lambda$createInitialSessions$0:173 expected:<10> but was:<20>
-- [ERROR]   SessionExpirationCrossDCTest.testLogoutAllInRealm:241->createInitialSessions:163->lambda$createInitialSessions$0:173 expected:<11> but was:<21>
-- [ERROR]   SessionExpirationCrossDCTest.testLogoutUser:398->createInitialSessions:163->lambda$createInitialSessions$0:173 expected:<11> but was:<21>
-- [ERROR]   SessionExpirationCrossDCTest.testLogoutUserWithFailover:431->createInitialSessions:163->lambda$createInitialSessions$0:173 expected:<11> but was:<21>
-- [ERROR]   SessionExpirationCrossDCTest.testLogoutWithAllStartedNodes:482->createInitialSessions:163->lambda$createInitialSessions$0:173 expected:<7> but was:<21>
-- [ERROR]   SessionExpirationCrossDCTest.testPeriodicExpirationAuthSessions:632->assertAuthSessionsStatisticsExpected:673->lambda$assertAuthSessionsStatisticsExpected$9:682 expected:<0> but was:<10>
-- [ERROR]   SessionExpirationCrossDCTest.testPeriodicExpirationOfflineSessions:304->createInitialSessions:163->lambda$createInitialSessions$0:173 expected:<10> but was:<20>
-- [ERROR]   SessionExpirationCrossDCTest.testPeriodicExpirationSessions:260->createInitialSessions:163->lambda$createInitialSessions$0:173 expected:<11> but was:<21>
-- [ERROR]   SessionExpirationCrossDCTest.testRealmRemoveOfflineSessions:222->createInitialSessions:163->lambda$createInitialSessions$0:173 expected:<10> but was:<20>
-- [ERROR]   SessionExpirationCrossDCTest.testRealmRemoveSessions:118->createInitialSessions:163->lambda$createInitialSessions$0:173 expected:<11> but was:<21>
-- [ERROR]   SessionExpirationCrossDCTest.testUserRemoveOfflineSessions:374->createInitialSessions:163->lambda$createInitialSessions$0:173 expected:<10> but was:<20>
-- [ERROR]   SessionExpirationCrossDCTest.testUserRemoveSessions:352->createInitialSessions:163->lambda$createInitialSessions$0:173 expected:<11> but was:<21>
-- [ERROR] Errors:
-- [ERROR]   SessionExpirationCrossDCTest.testRealmRemoveAuthSessions:696 ≫ NotAuthorized H...
-- [INFO]
-- [ERROR] Tests run: 14, Failures: 13, Errors: 1, Skipped: 0
-- [INFO]
-- [INFO] ------------------------------------------------------------------------
-- [INFO] BUILD FAILURE
-- [INFO] ------------------------------------------------------------------------
-- [INFO] Total time:  07:19 min
-- [INFO] Finished at: 2020-01-10T14:59:10+09:00
-- [INFO] ------------------------------------------------------------------------
-- [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.0:test (default-test) on project integration-arquillian-tests-base: There are test failures.
-- [ERROR]
-- [ERROR] Please refer to /root/keycloak/testsuite/integration-arquillian/tests/base/target/surefire-reports for the individual test results.
-- [ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
-- [ERROR] -> [Help 1]
-- [ERROR]
-- [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
-- [ERROR] Re-run Maven using the -X switch to enable full debug logging.
-- [ERROR]
-- [ERROR] For more information about the errors and possible solutions, please read the following articles:
-- [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

[4] Result (master branch): 
```
-- [INFO] Results:
-- [INFO]
-- [ERROR] Failures:
-- [ERROR]   SessionExpirationCrossDCTest.testClearDetachedClientSessions:549->createInitialSessions:163->lambda$createInitialSessions$0:173 expected:<11> but was:<21>
-- [ERROR]   SessionExpirationCrossDCTest.testClearDetachedOfflineClientSessions:580->createInitialSessions:163->lambda$createInitialSessions$0:173 expected:<10> but was:<20>
-- [ERROR]   SessionExpirationCrossDCTest.testLogoutAllInRealm:241->createInitialSessions:163->lambda$createInitialSessions$0:173 expected:<11> but was:<21>
-- [ERROR]   SessionExpirationCrossDCTest.testLogoutUser:398->createInitialSessions:163->lambda$createInitialSessions$0:173 expected:<11> but was:<21>
-- [ERROR]   SessionExpirationCrossDCTest.testLogoutUserWithFailover:431->createInitialSessions:163->lambda$createInitialSessions$0:173 expected:<11> but was:<21>
-- [ERROR]   SessionExpirationCrossDCTest.testLogoutWithAllStartedNodes:482->createInitialSessions:163->lambda$createInitialSessions$0:173 expected:<7> but was:<21>
-- [ERROR]   SessionExpirationCrossDCTest.testPeriodicExpirationAuthSessions:632->assertAuthSessionsStatisticsExpected:673->lambda$assertAuthSessionsStatisticsExpected$9:682 expected:<0> but was:<10>
-- [ERROR]   SessionExpirationCrossDCTest.testPeriodicExpirationOfflineSessions:304->createInitialSessions:163->lambda$createInitialSessions$0:173 expected:<10> but was:<20>
-- [ERROR]   SessionExpirationCrossDCTest.testPeriodicExpirationSessions:260->createInitialSessions:163->lambda$createInitialSessions$0:173 expected:<11> but was:<21>
-- [ERROR]   SessionExpirationCrossDCTest.testRealmRemoveAuthSessions:699->assertAuthSessionsStatisticsExpected:673->lambda$assertAuthSessionsStatisticsExpected$9:682 expected:<0> but was:<10>
-- [ERROR]   SessionExpirationCrossDCTest.testRealmRemoveOfflineSessions:222->createInitialSessions:163->lambda$createInitialSessions$0:173 expected:<10> but was:<20>
-- [ERROR]   SessionExpirationCrossDCTest.testRealmRemoveSessions:118->createInitialSessions:163->lambda$createInitialSessions$0:173 expected:<11> but was:<21>
-- [ERROR]   SessionExpirationCrossDCTest.testUserRemoveOfflineSessions:374->createInitialSessions:163->lambda$createInitialSessions$0:173 expected:<10> but was:<20>
-- [ERROR]   SessionExpirationCrossDCTest.testUserRemoveSessions:352->createInitialSessions:163->lambda$createInitialSessions$0:173 expected:<11> but was:<21>
-- [INFO]
-- [ERROR] Tests run: 14, Failures: 14, Errors: 0, Skipped: 0
-- [INFO]
-- [INFO] ------------------------------------------------------------------------
-- [INFO] BUILD FAILURE
-- [INFO] ------------------------------------------------------------------------
-- [INFO] Total time:  07:18 min
-- [INFO] Finished at: 2020-01-10T15:28:21+09:00
-- [INFO] ------------------------------------------------------------------------
-- [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.0:test (default-test) on project integration-arquillian-tests-base: There are test failures.
-- [ERROR]
-- [ERROR] Please refer to /root/keycloak/testsuite/integration-arquillian/tests/base/target/surefire-reports for the individual test results.
-- [ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
-- [ERROR] -> [Help 1]
-- [ERROR]
-- [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
-- [ERROR] Re-run Maven using the -X switch to enable full debug logging.
-- [ERROR]
-- [ERROR] For more information about the errors and possible solutions, please read the following articles:
-- [ [...]

2020-01-10 08:53 UTC, y-tabata commented
@pedroigor @mposolda when I ran them with the 8.0.1, the test was passed.
So maybe the test in the current master branch is wrong.

```
-- [INFO] Results:
-- [INFO]
-- [INFO] Tests run: 14, Failures: 0, Errors: 0, Skipped: 0
-- [INFO]
-- [INFO]
-- [INFO] --- docker-maven-plugin:0.28.0:stop (stop-db-container) @ integration-arquillian-tests-base ---
-- [INFO]
-- [INFO] --- db-allocator-plugin:8.0.1:release (release-db) @ integration-arquillian-tests-base ---
-- [info] Skipping
-- [INFO] ------------------------------------------------------------------------
-- [INFO] BUILD SUCCESS
-- [INFO] ------------------------------------------------------------------------
-- [INFO] Total time:  07:16 min
-- [INFO] Finished at: 2020-01-10T17:48:42+09:00
-- [INFO] ------------------------------------------------------------------------
```

2020-01-16 04:32 UTC, y-tabata commented
Docs PR: https://github.com/keycloak/keycloak-documentation/pull/822

2020-01-23 00:07 UTC, y-tabata commented
@hmlnarik @pedroigor As mentioned in https://github.com/keycloak/keycloak/pull/6649, tests are broken. Is there anything else I can do for proceeding with this PR?
This patch is strongly desired in Japan to use for API authz server.

2020-01-23 09:55 UTC, mposolda commented
@y-tabata @hmlnarik @pedroigor I confirm that cross-dc tests are not regression of this PR. They are failing in latest master as well :( Created https://issues.redhat.com/browse/KEYCLOAK-12759 for it.

2020-01-27 13:42 UTC, pedroigor submitted a review, later dismissed
@mposolda @y-tabata Approved. Is there anything I can do to help to make the tests pass and merge the PR ?

2020-01-30 10:05 UTC, stianst commented
We would like to put this on hold until after Keycloak 9 is released. Reasoning behind that is we want to introduce the feature for SAML 2.0 at the same time as we introduce it for OIDC, which we don't have capacity to do now.

@y-tabata Would it be okay for you if we put this on hold for a bit and aim to get it included in Keycloak 10. We can work on what is needed for SAML 2.0, as I don't expect you to contribute that as well.

2020-01-30 23:37 UTC, y-tabata commented
@stianst thanks. I understand.

2020-02-03 07:56 UTC, stianst commented
@y-tabata Thanks for your understanding, and thanks for contributing these changes. Once Keycloak 9 is out we will plan to get this included in 10.

2020-04-24 13:33 UTC, stianst commented
As we didn't get much progress on the SAML work here. I would like to continue with this on its own, then we can do SAML as a follow-up.

Would be great to get this merged asap - ideally for Keycloak 10 release next week, but that may be a bit of a push.

@mposolda @pedroigor can you guys review this?

2020-04-24 13:33 UTC, stianst commented
@y-tabata could you do a quick rebase?

2020-04-27 09:22 UTC, y-tabata commented
@stianst I will do a rebase. Just a moment please.

2020-04-27 13:40 UTC, y-tabata commented
@stianst I did a rebase.

2020-04-27 14:18 UTC, mposolda approved these changes
LGTM.

The fact is that timeout settings are already non-tirivial and this adds additional complexity to it. On the other hand, I understand why this can be needed. So approving.

2020-04-28 00:37 UTC, y-tabata commented
@mposolda The Travis CI tests were failed in the point not related to this PR. Could you check it?

2020-04-28 12:09 UTC, pedroigor approved these changes

2020-04-28 13:34 UTC, merged

2020-04-28 13:34 UTC, stianst commented
Failing tests are cross-DC tests, and failures have nothing to do with this change. Looks like they are completely broken.