KEYCLOAK-10894 Adds a ready indicating promise
keycloak/keycloak pull request #6619
Opened 2019-12-20 20:01 UTC by ath88

https://issues.redhat.com/browse/KEYCLOAK-10894

This is non-intrusive and backwards compatible. With this change it is possible
to `await keycloakAuthorization.ready` to make sure the component has been
properly initialized.

The 'steps to reproduce' can now be altered to mitigate the problem by doing:

``` javascript 
const keycloak = new Keycloak("/keycloak.json");
keycloak.init({ promiseType: 'native'}).then(async () => {
  const authorization = new KeycloakAuthorization(keycloak);
  await authorization.ready();
  authorization.entitlement('resource-service');
});
```

I am a JavaScript developer, and I have had a hard time figuring out how to run the test-suite through maven, I keep encountering unrelated errors in the codebase. This change is intentionally very low impact.

2019-12-20 23:41 UTC, pedroigor requested changes
LGTM. Could you please squash your commits?

2019-12-21 04:14 UTC, shousper commented
LGTM too, thanks @ath88 !!

2019-12-22 09:44 UTC, ath88 commented
@pedroigor Squashed.

2019-12-24 21:33 UTC, pedroigor approved these changes

2019-12-24 21:33 UTC, merged

2019-12-24 21:34 UTC, pedroigor commented
@ath88 Thanks.