[KEYCLOAK-12439] Update to Angular 1.7.9
keycloak/keycloak pull request #6654
Opened 2020-01-14 11:30 UTC by abstractj

## [KEYCLOAK-12439](https://issues.redhat.com/browse/KEYCLOAK-12439)
* Update to Angular 1.7.9

## Verification Steps

1. Remove `themes/src/main/node_modules/` only to make sure that there's no cache
2. `cd themes/src/main && npm i`
3. At the root folder of the Keycloak server repository run: 
```
mvn clean install -Pdistribution -DskipTests=true
```
As alternative you can also run:
```
mvn -f testsuite/utils/pom.xml exec:java -Pkeycloak-server -Dkeycloak.profile.feature.account_api=enabled -Dkeycloak.profile.feature.account2=enabled -Dresources
```
4. Check if nothing was broken into the server
5. Run the integration tests as described in https://github.com/keycloak/keycloak/blob/master/testsuite/integration-arquillian/HOW-TO-RUN.md#base-ui-tests.

## Additional Notes
* This PR introduces a ridiculous amount of changes, to be more precise **5,521* changed files. For this reason I made sure to split the commits. So people can focus on [what really matters](https://github.com/keycloak/keycloak/commit/2be4701d51f5ab0cce7a8470e20db44ba43dac9b).

2020-01-22 09:29 UTC, vmuzikar requested changes
@abstractj I've very quickly checked your changes (I wanted to run the Admin Console tests) and the deps weren't really updated. You need to update [common/resources](https://github.com/keycloak/keycloak/tree/master/themes/src/main/resources/theme/keycloak/common/resources) dir too.

2020-01-22 09:55 UTC, edewit commented
@abstractj I was expecting to have 1.7.9 here as well
![image](https://user-images.githubusercontent.com/51133/72884004-aa543e80-3d05-11ea-85c2-973fd5d17171.png)

2020-01-22 18:07 UTC, abstractj commented
@edewit @vmuzikar thank you both for reviewing it, it should be ready to go now.

2020-01-23 08:28 UTC, edewit commented
@abstractj I might do something wrong but I still get angular version 1.6.10 in the console

2020-01-23 08:48 UTC, vmuzikar commented
@edewit @abstractj I've just briefly checked the latest changes and I can confirm Angular was updated in the Admin Console. Running Admin Console tests now.

2020-01-23 08:55 UTC, vmuzikar commented
Btw, I think this PR conflicts with https://github.com/keycloak/keycloak/pull/6432.

2020-01-23 20:12 UTC, abstractj commented
@vmuzikar I believe once that's merged I can do the updates to remove the conflicts. The only commit that truly matters for us is https://github.com/keycloak/keycloak/pull/6654/commits/46f4ffd7b56309eeef4b602290e65bb01fa74728.

If we get the approval tomorrow on Alex's PR, I can do the updates.

2020-01-24 17:20 UTC, vmuzikar submitted a review, later dismissed
I've done a very brief review (basically just verified Angular.js was updated and Admin Console test passed). LGTM but we need to be careful about those conflicts. Thanks @abstractj!

2020-01-29 09:51 UTC, abstractj commented
@vmuzikar @ssilvert @hmlnarik rebased after the merge of Alex's PR.

2020-01-30 11:40 UTC, vmuzikar reviewed
Found two non-blocking issue (any of them doesn't affect functionality). Other than that LGTM, thanks @abstractj!

2020-01-30 11:40 UTC, vmuzikar commented on package-lock.json
> +  "lockfileVersion": 1
@abstractj I'm not sure we should have a package-lock directly in the root directory (where's no node_modules). How did this even get here? :) However, it's a non-blocking issue.

2020-01-30 11:40 UTC, vmuzikar commented on themes/src/main/package-lock.json
> +{
Again, non-blocking but I believe this package-lock shouldn't be here. If anywhere, should be in `themes/src/main/resources/theme/keycloak/common/resources` where the `package.json` lives.

2020-01-30 13:25 UTC, stianst approved these changes

2020-01-30 13:25 UTC, merged