KEYCLOAK-11877 Theme support for ValidateX509CertificateUsername
keycloak/keycloak pull request #6662
Opened 2020-01-15 13:38 UTC by slaskawi

[KEYCLOAK-11877](https://issues.redhat.com/browse/KEYCLOAK-11877)

This Pull Request introduces theme support for `ValidateX509CertificateUsername` authenticator

2020-01-23 19:40 UTC, stianst requested changes
See inline comments. In general this fixes the bug reported in KEYCLOAK-11877, but reviewing this I found a general issue with the wrong level of details being returned to the user, which we should address.

Also, since we didn't catch that it was returning a JSON error instead of an error page it is clear that there's a complete lack of testing here. We need to at least add some tests for error conditions like this.

2020-01-23 19:40 UTC, stianst commented on services/src/main/java/org/keycloak/authentication/authenticators/x509/ValidateX509CertificateUsername.java
> +            Response challengeResponse = ErrorPage.error(context.getSession(), context.getAuthenticationSession(), Response.Status.UNAUTHORIZED, Messages.X509_CERTIFICATE_MISSING);
When would this error happen? It seems if there is no certificate x509 authentication should not be attempted?

2020-01-23 19:40 UTC, stianst commented on services/src/main/java/org/keycloak/authentication/authenticators/x509/ValidateX509CertificateUsername.java
> +            Response challengeResponse = ErrorPage.error(context.getSession(), context.getAuthenticationSession(), Response.Status.UNAUTHORIZED, Messages.MISSING_CONFIGURATION);
Missing configuration should return a 500 internal server error. Message returned to user should be generic, it should not expose internal error messages to end-users.

2020-01-23 19:40 UTC, stianst commented on services/src/main/java/org/keycloak/authentication/authenticators/x509/ValidateX509CertificateUsername.java
>              context.getEvent().error(Errors.USER_NOT_FOUND);
This looks wrong. Config is missing, but it is showing that the user is not found

2020-01-23 19:40 UTC, stianst commented on services/src/main/java/org/keycloak/authentication/authenticators/x509/ValidateX509CertificateUsername.java
>              context.getEvent().error(Errors.USER_NOT_FOUND);
This is not right, certificate is not found, but it's showing user is not found

2020-01-23 19:40 UTC, stianst commented on services/src/main/java/org/keycloak/services/messages/Messages.java
> +    public static final String AUTHENTICATION_FAILED = "AuthenticationFailedMessage";
authenticationFailedMessage

2020-01-23 19:40 UTC, stianst commented on services/src/main/java/org/keycloak/authentication/authenticators/x509/ValidateX509CertificateUsername.java
> +            Response challengeResponse = ErrorPage.error(context.getSession(), context.getAuthenticationSession(), Response.Status.UNAUTHORIZED, Messages.AUTHENTICATION_FAILED, e.getMessage());
We should just use internalServerError, with 500 as the return status code here I think

2020-01-23 19:40 UTC, stianst commented on services/src/main/java/org/keycloak/authentication/authenticators/x509/ValidateX509CertificateUsername.java
> +            Response challengeResponse = ErrorPage.error(context.getSession(), context.getAuthenticationSession(), Response.Status.UNAUTHORIZED, Messages.X509_USER_IDENTITY_EXTRACT_ERROR);
internalServerError, with 500 I think

2020-01-23 19:40 UTC, stianst commented on services/src/main/java/org/keycloak/authentication/authenticators/x509/ValidateX509CertificateUsername.java
>              logger.modelDuplicateException(e);
Not sure why there would be a ModelDuplicateException. There's no writes to the DB are there?!

2020-01-23 19:40 UTC, stianst commented on services/src/main/java/org/keycloak/authentication/authenticators/x509/ValidateX509CertificateUsername.java
> +            Response challengeResponse = ErrorPage.error(context.getSession(), context.getAuthenticationSession(), Response.Status.UNAUTHORIZED, Messages.AUTHENTICATION_FAILED, e.getMessage());
internalServerError, with 500 I think

2020-01-23 19:40 UTC, stianst commented on services/src/main/java/org/keycloak/services/messages/Messages.java
> +    public static final String MISSING_CONFIGURATION = "missingConfigurationMessage";
Remove this. We should return details like this to end-users.

2020-01-23 19:40 UTC, stianst commented on services/src/main/java/org/keycloak/authentication/authenticators/x509/ValidateX509CertificateUsername.java
>              logger.modelDuplicateException(e);
If it's valid catch, then 500 with internalServerError

2020-01-23 19:40 UTC, stianst commented on services/src/main/java/org/keycloak/services/messages/Messages.java
> +    public static final String AUTHENTICATION_FAILED = "AuthenticationFailedMessage";
Remove this. We should return details like this to end-users.

2020-01-23 19:40 UTC, stianst commented on services/src/main/java/org/keycloak/services/messages/Messages.java
> +    public static final String X509_CERTIFICATE_MISSING = "authenticatorX509CertificateMissing";
Remove this. We should return details like this to end-users.

2020-01-23 19:40 UTC, stianst commented on services/src/main/java/org/keycloak/services/messages/Messages.java
> +    public static final String X509_USER_IDENTITY_EXTRACT_ERROR = "authenticatorX509UserIdentityExtractError";
Remove this. We should return details like this to end-users.

2020-01-23 19:40 UTC, stianst commented on themes/src/main/resources/theme/base/login/messages/messages_en.properties
> +authenticationFailedMessage=Authentication failed. Reason: {0}
Remove this. We should return details like this to end-users.

2020-01-23 19:40 UTC, stianst commented on themes/src/main/resources/theme/base/login/messages/messages_en.properties
> +authenticatorX509CertificateMissing=X509 client certificate is missing.
Remove this. We should return details like this to end-users.

2020-01-23 19:40 UTC, stianst commented on themes/src/main/resources/theme/base/login/messages/messages_en.properties
> +authenticatorX509UserIdentityExtractError=Unable to extract user identity from specified certificate.
Remove this. We should return details like this to end-users.

2020-01-23 19:40 UTC, stianst commented on themes/src/main/resources/theme/base/login/messages/messages_en.properties
> +missingConfigurationMessage=Missing configuration
Remove this. We should return details like this to end-users.

2020-01-28 07:59 UTC, slaskawi commented
> See inline comments. In general this fixes the bug reported in KEYCLOAK-11877, but reviewing this I found a general issue with the wrong level of details being returned to the user, which we should address.

@stianst Ok, no problem, I'll fix them.

> Also, since we didn't catch that it was returning a JSON error instead of an error page it is clear that there's a complete lack of testing here. We need to at least add some tests for error conditions like this.

@stianst The tests seem to be there - `X509DirectGrantTest`. Moreover, they seem not to be executed in Travis (I'll check why) and I broke them with this PR. Let me fix this as well.

2020-01-28 09:13 UTC, slaskawi commented
After investigation, together with @stianst we decided to close this one. See comments in [KEYCLOAK-11877](https://issues.redhat.com/browse/KEYCLOAK-11877).

2020-01-28 09:13 UTC, closed without merging