KEYCLOAK-12732 Improve SAMLAttribute parsing of unknown attributes
keycloak/keycloak pull request #6681
Opened 2020-01-21 11:07 UTC by thomasdarimont

We now store all unknown attributes present on a SAMLAttribute element
in the "otherAttributes" map associated with the element.

Previously only the x500:encoding attribute was handled while parsing
attribute elements.

2020-01-30 10:52 UTC, stianst commented
Is the Java update needed? saml-core is used in adapters and I believe we still support 1.7 in some cases :/

2020-01-30 11:05 UTC, thomasdarimont commented
I updated the Java Version to be able to use the Stream API. Of course I could rework that again, but I thought the upgrade would be fine, since most of the other Keycloak modules on the server-side are also using Java 8 API.
https://lists.jboss.org/pipermail/keycloak-dev/2016-January/006221.html

2020-01-30 11:16 UTC, thomasdarimont commented
I downgraded the PR to be compatible with Java 7 API.

2020-01-30 14:05 UTC, hmlnarik requested changes
Thanks for your PR. I believe once the attributes would use qualified names instead of local names, and fixing the static initialization (please see inline), this would be a do contribution.

2020-01-30 14:05 UTC, hmlnarik commented on saml-core/src/main/java/org/keycloak/saml/processing/core/parsers/saml/assertion/SAMLAttributeParser.java
> +            if (attributeQName == null || DEFAULT_KNOWN_LOCAL_ATTRIBUTE_NAMES.contains(attributeQName.getLocalPart())) {
```suggestion
            if (attributeQName == null || DEFAULT_KNOWN_LOCAL_ATTRIBUTE_NAMES.contains(attributeQName)) {
```

2020-01-30 17:46 UTC, thomasdarimont commented on saml-core/src/main/java/org/keycloak/saml/processing/core/parsers/saml/assertion/SAMLAttributeParser.java
> +            if (LOGGER.isTraceEnabled()) {
That's what I wanted to do in the first place, but there is no classic JBoss-Logging "logger" field available for this class, just the PicketLinkLogger LOGGER. That's why I added the guard to spare the string concat.

2020-01-30 17:52 UTC, thomasdarimont commented
@hmlnarik thanks for the review! I just applied the requested changes, except for the logging, please see comments for reasoning.

2020-01-31 00:00 UTC, thomasdarimont commented on saml-core/src/main/java/org/keycloak/saml/processing/core/parsers/saml/assertion/SAMLAttributeParser.java
> +            if (LOGGER.isTraceEnabled()) {
I didn't want to add a JBoss-Logging `logger` just for this one logging statement.

2020-01-31 08:17 UTC, hmlnarik commented on saml-core/src/main/java/org/keycloak/saml/processing/core/parsers/saml/assertion/SAMLAttributeParser.java
> +            if (LOGGER.isTraceEnabled()) {
I see, that makes sense then. Perhaps we should unify the logging to use single logging framework but that's definitely out of scope for this PR.

2020-01-31 08:21 UTC, hmlnarik approved these changes
Looks good now, thanks @thomasdarimont !

2020-01-31 09:15 UTC, merged