KEYCLOAK-12240 MigrationModelTest fails in pipeline
keycloak/keycloak pull request #6697
Opened 2020-01-24 22:27 UTC by vramik

2020-01-24 23:09 UTC, vramik commented
https://keycloak-jenkins.com/job/universal-test-pipeline-server/1235/
https://keycloak-jenkins.com/job/test-keycloak-jpa/148/

2020-01-31 08:46 UTC, hmlnarik requested changes
Thanks for the fix! 
Please see inline for the biggest issue.
Nit: Perhaps it would be safer to use even a bigger time difference, if that helps.

2020-01-31 08:46 UTC, hmlnarik commented on testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/model/MigrationModelTest.java
> +            System.out.println("%% " + l.get(0).getId() + "; " + l.get(0).getVersion() + "; " + l.get(0).getUpdateTime());
Please use Logger instead.

2020-02-03 10:33 UTC, hmlnarik approved these changes
Thanks!

2020-02-03 12:14 UTC, merged