KEYCLOAK-12177 KEYCLOAK-12178 WebAuthn: Improve usability
keycloak/keycloak pull request #6710
Opened 2020-01-31 12:16 UTC by mabartos

[KEYCLOAK-12177](https://issues.redhat.com/browse/KEYCLOAK-12177) WebAuthn authentication: improve usability by remove checkboxes

[KEYCLOAK-12178](https://issues.redhat.com/browse/KEYCLOAK-12178) WebAuthn register: Improve usability

2020-01-31 17:13 UTC, mposolda requested changes
@mabartos Looks nice! Thanks! I have few things:

1) Rebase will be needed. There is conflict in messages_en.properties file (which was probably introduced by me, Sorry :)

2) Is it possible to change some messages to not display "WebAuthn" to the user, but rather use terminology like "Security Key" ? We aim to do the same in some other places like "Select Authenticator" screen, new account console etc. See inline comments for more details.

3) I found a bug when testing this. Let's assume that you have authentication flow configuration like this:

![Screenshot from 2020-01-31 18-09-41](https://user-images.githubusercontent.com/1223965/73559229-f2393b00-4454-11ea-9b20-fe8b6f6e2cd6.png)

and you have user with both "password" and "WebAuthn passwordless" credential. Then I am trying to login and doing this:
- Provide username
- I am on the password form. I click "try another way"
- I select "WebAuthn passwordless"
- I press "Cancel" dialog on the WebAuthn login page.
- I click "Try again" . Now I expect WebAuthn login to be retried, but instead of it, I will be redirected back to the Password form.

It is a chance that when you rebase, this bug won't happen anymore. But probably it will still happen.

2020-01-31 17:13 UTC, mposolda commented on themes/src/main/resources/theme/base/login/messages/messages_en.properties
> +webauthn-registration-title=WebAuthn security key registration
Is it possible to change this to "Security Key Registration" ?

2020-01-31 17:13 UTC, mposolda commented on themes/src/main/resources/theme/base/login/messages/messages_en.properties
> +webauthn-login-title=WebAuthn Login
Is it possible to change this to "Security Key Login" ?

2020-01-31 17:13 UTC, mposolda commented on themes/src/main/resources/theme/base/login/messages/messages_en.properties
> +webauthn-error-title=WebAuthn Error
Is it possible to change this to "Security Key Error" ?

2020-02-03 07:14 UTC, mabartos commented
@mposolda Thanks for your advice!

2020-02-03 19:32 UTC, mposolda commented
@mabartos Thanks a lot Martin! Unfortunately still few more points. Sorry...

1) Another conflict :( Now in the template.ftl file due some other commit by Jan. Do you have a chance to rebase one more and take a look at @iankko's changes and fix the conflict? Thanks!

2) Found another issue when testing - not sure if it was still there, or if it is regression since previous work. 
- Add WebAuthn Register required action to some user and login. WebAuthn Register required action is triggered
- Browser dialog about register new WebAuthn credential is shown. 
- I click "Cancel" on the browser dialog. Error page is shown with the message "Failed to register your WebAuthn Authenticator." - small issue 1 - the message is not localized and it contains word WEbAuthn on it. But this is not a blocker and can be fixed in some other commit
- I click "Try Again" . Now the page "We are sorry" is shown and the NullPointerException in server.log with stacktrace like this:
```
java.lang.NullPointerException
	at java.util.Base64$Decoder.decode(Base64.java:549)
	at org.keycloak.authentication.requiredactions.WebAuthnRegister.processAction(WebAuthnRegister.java:180)
```

I suppose it is possible to add another hidden parameter to the webauthn-error.ftl file and in the WebAuthnRegister.processAction method you can check if this parameter exists and just render the page if yes?

2020-02-05 07:35 UTC, mposolda approved these changes
@mabartos Thanks, I am still seeing the issue above, so will create the follow-up JIRA

2020-02-05 07:35 UTC, merged