KEYCLOAK-12853 Add license information for account2 dependencies
keycloak/keycloak pull request #6711
Opened 2020-01-31 15:40 UTC by ASzc

Went through the jar, and found the sources and license for each of the keycloak-preview node_modules.

Emotion doesn't have a declared license in the source repo, so I had to use the package.json, which states "MIT", and matches the LICENSE file distributed with the module.

2020-02-04 13:29 UTC, abstractj requested changes
@ASzc I can be wrong and @vmuzikar can correct me if I'm wrong. But we also need the same for https://github.com/keycloak/keycloak/blob/master/distribution/feature-packs/server-feature-pack/src/main/resources/licenses/keycloak/licenses.xml.

2020-02-04 13:33 UTC, vmuzikar commented
@abstractj No, you're not wrong. ;) I can confirm this.

2020-02-04 14:39 UTC, ASzc commented
Sorry, forgot about that one. Copied the info over, no need to edit it since we're not using productized dependency versions for this.

2020-02-04 18:41 UTC, abstractj approved these changes

2020-02-04 18:41 UTC, merged

2020-02-05 10:10 UTC, vmuzikar reviewed
@ASzc @abstractj Please see https://issues.redhat.com/browse/KEYCLOAK-12853?focusedCommentId=13963955&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13963955