KEYCLOAK-10898 WildFly Adapter CLI based installation scripts
keycloak/keycloak pull request #6726
Opened 2020-02-04 11:09 UTC by vramik

2020-02-05 10:34 UTC, stianst submitted a review, later dismissed
Looks good, only thing I could spot is values with spaces should use quotes. In SAML it should use quotes to leave spaces there so it's consistent with XML-snippet installation file instead of using _.

2020-02-05 10:34 UTC, stianst commented on services/src/main/java/org/keycloak/protocol/oidc/installation/KeycloakOIDCJbossSubsystemClientCliInstallation.java
> +                .append("/subsystem=keycloak/secure-deployment=").append(deploymentName).append("/:add( \\\n")
deploymentName should have quotes around it, otherwise spaces are lost and it becomes "WARMODULENAME.war" in standalone.xml.

2020-02-05 10:34 UTC, stianst commented on services/src/main/java/org/keycloak/protocol/saml/installation/KeycloakSamlSubsystemCliInstallation.java
> +        String entityId = client.getBaseUrl() == null ? "SPECIFY_YOUR_entityID!" : client.getBaseUrl();
Use quotes instead of _ to make it consistent with XML download.

2020-02-05 10:34 UTC, stianst commented on services/src/main/java/org/keycloak/protocol/saml/installation/KeycloakSamlSubsystemCliInstallation.java
> +                .append(",logoutPage=SPECIFY_YOUR_LOGOUT_PAGE!)\n\n");
Use quotes instead of _ to make it consistent with XML download.

2020-02-05 10:34 UTC, stianst commented on services/src/main/java/org/keycloak/protocol/saml/installation/KeycloakSamlSubsystemCliInstallation.java
> +                    .append(samlClient.getClientEncryptingPrivateKey() == null ? "PRIVATE_KEY_NOT_SET_UP_OR_KNOWN" : samlClient.getClientEncryptingPrivateKey())
Use quotes instead of _ to make it consistent with XML download.

2020-02-05 10:34 UTC, stianst commented on services/src/main/java/org/keycloak/protocol/saml/installation/KeycloakSamlSubsystemCliInstallation.java
> +                    .append(samlClient.getClientSigningCertificate() == null ? "YOU_MUST_CONFIGURE_YOUR_CLIENT's_SIGNING_CERTIFICATE" : samlClient.getClientSigningCertificate())
Use quotes instead of _ to make it consistent with XML download.

2020-02-05 10:34 UTC, stianst commented on services/src/main/java/org/keycloak/protocol/saml/installation/KeycloakSamlSubsystemCliInstallation.java
> +                    .append(samlClient.getClientSigningPrivateKey() == null ? "PRIVATE_KEY_NOT_SET_UP_OR_KNOWN" : samlClient.getClientSigningPrivateKey())
Use quotes instead of _ to make it consistent with XML download.

2020-02-05 14:30 UTC, vramik commented
@stianst thanks for the review, I've incorporated changes you've requested, please re-review it again.

2020-02-06 13:38 UTC, hmlnarik commented on services/src/main/java/org/keycloak/protocol/oidc/installation/KeycloakOIDCJbossSubsystemClientCliInstallation.java
> +                .append("/subsystem=keycloak/secure-deployment=\"").append(deploymentName).append("\"/:add( \\\n")
introduce a method for escaping the quotes in any user-entered data: https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/7.1/html-single/management_cli_guide/index#quotation_marks

```suggestion
                .append("/subsystem=keycloak/secure-deployment=\"").append(quote(deploymentName)).append("\"/:add( \\\n")
```

2020-02-25 15:29 UTC, hmlnarik requested changes

2020-02-25 15:29 UTC, hmlnarik commented on services/src/main/java/org/keycloak/protocol/saml/installation/KeycloakSamlSubsystemCliInstallation.java
> +        return "\"" + value + "\"";
The `value` has to be quoted per https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/7.2/html-single/management_cli_guide/index#cli_special_characters

2020-03-02 09:07 UTC, hmlnarik approved these changes

2020-03-02 09:08 UTC, merged