KEYCLOAK-12749 fix "invalid state" error due to IE requesting favicon
keycloak/keycloak pull request #6734
Opened 2020-02-05 14:18 UTC by thokuest

Internet Explorer occasionally requests a favicon before doing the
actual redirect to localhost. This commit adds Undertow to properly
handle those unwanted requests.

Remarks:

* I tried to keep it as low-level as possible but miserably failed. I'm obviously not smart enough to implement the HTTP protocol properly.
* The `import` statements have been auto-organized by the IDE, hope that's okay.
* `HttpResponseWriter` interface for customized login and logout responses has been removed. That might be a breaking change but I really doubt that's actually used out there.
* We included this change in our product already and initial tests look good so far.
* There're no unit tests, so I deliberately ignored to provide them here. I might need further support to add them if required.

2020-02-21 14:10 UTC, pedroigor requested changes

2020-02-21 14:10 UTC, pedroigor commented on adapters/oidc/installed/src/main/java/org/keycloak/adapters/installed/KeycloakInstalled.java
> -                    System.err.println("Using a writer is deprecated.  Please remove its usage.  This is now handled by endpoint on server");
We should probably advertise in our change notes the removal of `HttpResponseWriter` from the API?

2020-02-21 14:15 UTC, pedroigor commented
@thokuest thanks for the changes. Only minor comments.

@stianst @thokuest When logging out using the example from [here](https://github.com/keycloak/keycloak-documentation/blob/master/securing_apps/topics/oidc/java/installed-adapter.adoc#example), I noticed that the `delegated` endpoint in Keycloak redirects to the `Login Successful` page instead of a specific page for a successful logout?

2020-02-21 16:15 UTC, thokuest commented on adapters/oidc/installed/src/main/java/org/keycloak/adapters/installed/KeycloakInstalled.java
> +            errorDescription = getQueryParameterIfPresent(exchange, "error-description");
Good point. I already changed that locally to `ERROR_DESCRIPTION` but then I realized the `_` vs. `-`. Thought it was by intention.

2020-02-21 16:35 UTC, thokuest commented
@pedroigor Yes, that's true. And it doesn't perform an actual logout, [KEYCLOAK-10752](https://issues.redhat.com/browse/KEYCLOAK-10752) for your reference. This is likely to go away with [KEYCLOAK-11518](https://issues.redhat.com/browse/KEYCLOAK-11518) I assume?

2020-03-03 15:33 UTC, pedroigor commented
@thokuest Sorry for the delay. LGTM.

2020-03-03 15:33 UTC, pedroigor approved these changes

2020-03-03 15:39 UTC, merged