[KEYCLOAK-12909] - Keycloak uses embedded cache manager instead of container-managed one
keycloak/keycloak pull request #6736
Opened 2020-02-05 20:36 UTC by pedroigor

2020-02-05 20:50 UTC, pedroigor commented
@mposolda, the fix tries to fail boot if no `ManagedCacheManagerProvider` if none was found. I've just added a check for an `embedded` property which is required if running the server using an embedded cache manager (e.g.: undertow).

Another option would be to have a specific implementation of `ManagedCacheManagerProvider` and move the embedded cache manager code to there. So that only the test suite will be able to run in embedded mode.

2020-02-05 23:25 UTC, tkyjovsk requested changes

2020-02-05 23:25 UTC, tkyjovsk commented on testsuite/utils/src/main/resources/META-INF/keycloak-server.json
> +}
Redundant bracket here. Also it seems like this needs to be updated in `testsuite/integration-arquillian/tests/base/src/test/resources/META-INF/keycloak-server.json` to be reflected in the undertow-mode in the base testsuite.

2020-02-06 11:12 UTC, tkyjovsk commented
`cec2c1f` looks good. Based on travis logs and some additional testing on my side, it fixed both KEYCLOAK-12579 and KEYCLOAK-12718.

2020-02-06 12:13 UTC, stianst approved these changes

2020-02-06 12:14 UTC, merged