[KEYCLOAK-11345] - Test basic features of Keycloak.X with current testsuite
keycloak/keycloak pull request #6754
Opened 2020-02-07 16:20 UTC by pedroigor

2020-02-07 16:22 UTC, pedroigor commented
@dteleguin The initial work to support the Quarkus Server in our test suite. We've changed the context-root to `/auth`, reason being that the corresponding configuration property is a build time config and can not be changed when booting the server.

2020-02-27 08:02 UTC, stianst requested changes

2020-02-27 13:09 UTC, pedroigor commented on distribution/server-x/src/main/content/bin/kc.sh
> +GREP="grep"
Yes, it is. See line #62.

2020-02-27 13:13 UTC, stianst commented on distribution/server-x/src/main/content/bin/kc.sh
> +GREP="grep"
I see. So it was missing ;)

2020-02-27 13:16 UTC, pedroigor commented on services/src/main/java/org/keycloak/authentication/authenticators/challenge/NoCookieFlowRedirectAuthenticator.java
> +            KeycloakUriInfo uriInfo = context.getSession().getContext().getUri();
I can send a separate PR, I thought that this change was too simple to deserve one.

Basically, we get some errors when calling `getUri` on the `httpRequest` when running Quarkus. I did not investigate further the reasons but I suspect some mismatch in resteasy versions.

2020-02-27 13:19 UTC, pedroigor commented on distribution/server-x/pom.xml
> +                                    <excludes>**/node_modules/**,**/node/**</excludes>
I did not want to touch the main distribution so I thought to remove this from here. I think that centralize changes in Quarkus dist (even though they may not be the best) will help us in the future when reviewing what we have done.

2020-03-05 13:01 UTC, stianst commented on distribution/server-x/pom.xml
> +                                    <excludes>**/node_modules/**,**/node/**</excludes>
Not sure why "node" is there in themes jar. That is a bug if it is.

There's node_modules that should be in the dist, and without it things won't actually work.

2020-03-05 13:08 UTC, stianst commented on services/src/main/java/org/keycloak/authentication/authenticators/challenge/NoCookieFlowRedirectAuthenticator.java
> +            KeycloakUriInfo uriInfo = context.getSession().getContext().getUri();
OK

2020-03-05 13:18 UTC, stianst commented on distribution/server-x/pom.xml
> +                                    <excludes>**/node_modules/**,**/node/**</excludes>
Just tried building from master, and I don't have any "node" directories within the server-x distro, and I only have the expected node_modules directories:

    find -name node_modules
    ./keycloak-preview/account/resources/node_modules
    ./keycloak/common/resources/node_modules

2020-03-05 13:58 UTC, pedroigor commented on distribution/server-x/pom.xml
> +                                    <excludes>**/node_modules/**,**/node/**</excludes>
Maybe something that was fixed. I'm going to remove.

2020-03-05 15:29 UTC, dteleguin commented on quarkus/server/pom.xml
> +            <artifactId>commons-logging-jboss-logging</artifactId>
we have this one in the POM already (see line 204)

2020-03-05 15:30 UTC, dteleguin commented on quarkus/server/pom.xml
> +            <artifactId>resteasy-multipart-provider</artifactId>
same here (line 200)

2020-03-05 15:36 UTC, dteleguin commented on testsuite/integration-arquillian/servers/auth-server/quarkus/pom.xml
> +        <version>9.0.0-SNAPSHOT</version>
need to bump version after rebase?

2020-03-10 14:59 UTC, stianst approved these changes

2020-03-10 14:59 UTC, merged