KEYCLOAK-12860 KEYCLOAK-12875 Fix for Account REST Credentials to wor…
keycloak/keycloak pull request #6776
Opened 2020-02-12 12:09 UTC by mposolda

…k with LDAP and social users

2020-02-12 18:46 UTC, mposolda commented
@ssilvert @vmuzikar Do you have a chance to review please? I've did pretty much what we discussed in the JIRA for REST endpoints in the comments in KEYCLOAK-12875 . Attaching some screenshots how it looks like now:

Screenshot for normal Keycloak user (with password):
![screenshot-1-keycloak-user](https://user-images.githubusercontent.com/1223965/74366114-adf05800-4dcf-11ea-8a27-37f90fa57eec.png)

Screenshot for LDAP user:
![screenshot-2-ldap-user](https://user-images.githubusercontent.com/1223965/74366169-c6607280-4dcf-11ea-8154-4323e6214839.png)

Screenshot for user, which was registered through social login and doesn't have any password set in Keycloak:
![screenshot-3-social-registered-user-without-password](https://user-images.githubusercontent.com/1223965/74366211-d8daac00-4dcf-11ea-99ec-5311e2e06bc3.png)

None of the password credentials have userLabel as userLabel will be very rarely set for password credentials IMO.

2020-02-12 19:38 UTC, ssilvert submitted a review, later dismissed
LGTM.  

Don't worry about my "Log in/Log out" comment.  I've opened https://issues.redhat.com/browse/KEYCLOAK-12987 to address all of those.

2020-02-12 19:38 UTC, ssilvert commented on themes/src/main/resources/theme/keycloak-preview/account/messages/messages_en.properties
> +password-help-text=Log in by entering your password.
Our standard is to use "Sign in/Sign Out" instead of "Log in/Log Out".  But I see we've messed this up in a lot of places.

2020-02-13 11:05 UTC, vmuzikar commented
@mposolda Thanks for the update!

We need to extend the test for that here:
https://github.com/keycloak/keycloak/blob/0801cfb01f3e56ec4526171ff0d37ca340fc5a61/testsuite/integration-arquillian/tests/other/base-ui/src/test/java/org/keycloak/testsuite/ui/account2/SigningInTest.java#L184
Let me know if you need any help with that.

2020-02-13 14:12 UTC, vmuzikar requested changes
From my PoV looks good except the missing UI tests.

At the very least, we should add the test for setting up the password when user has no password set as I mentioned in my previous comment.

It would be nice to have a UI test also for the dummy credentials that would check if createdAt field is handled correctly by the UI. But IMHO this could be done as a follow-up as it's not that critical scenario.

2020-02-14 11:50 UTC, mposolda commented
@vmuzikar Thanks, I've added the scenario for missing password to the SigningInTest. Also did some more fixes, so the test is passing now. I've used separate commit just so it is easier for you to re-review. I will squash it afterwards when merging.

Agree that test for userStorage scenario can be done as a follow-up.

2020-02-14 13:44 UTC, ssilvert reviewed
LGTM

Just ping me after you squashed.  As long as @vmuzikar thinks the tests look OK I'll give final approval so you can merge.

2020-02-14 14:08 UTC, vmuzikar submitted a review, later dismissed
Created a follow-up JIRA for the missing test: https://issues.redhat.com/browse/KEYCLOAK-13007.

LGTM, thanks @mposolda!

2020-02-14 14:17 UTC, mposolda commented
@ssilvert @vmuzikar I've squashed the commits now. Thanks!

2020-02-14 14:25 UTC, ssilvert approved these changes
Approved.  @mposolda merge at will!

2020-02-14 19:24 UTC, mposolda commented
@ssilvert Thanks

2020-02-14 19:24 UTC, merged