[KEYCLOAK-12980] Username not updated when "Email as username" is ena…
keycloak/keycloak pull request #6827
Opened 2020-02-24 22:56 UTC by douglaspalmer

…bled

2020-02-27 10:04 UTC, stianst requested changes

2020-02-27 10:04 UTC, stianst commented on testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/UserTest.java
> +        assertEquals("user1@localhost", userRep.getEmail());
Should this be userRep.getUsername()?

2020-02-27 10:04 UTC, stianst commented on testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/UserTest.java
> +        assertEquals("user1@localhost", userRep.getEmail());
Should this be userRep.getUsername()?

2020-02-27 10:04 UTC, stianst commented on testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/UserTest.java
> +        assertEquals("user11@localhost", userRep.getEmail());
Should this be userRep.getUsername()?

2020-02-27 18:54 UTC, douglaspalmer commented on testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/UserTest.java
> +        assertEquals("user1@localhost", userRep.getEmail());
Yes, fixed, thanks

2020-02-27 18:55 UTC, douglaspalmer commented on testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/UserTest.java
> +        assertEquals("user1@localhost", userRep.getEmail());
Yes, fixed, thanks.

2020-02-27 18:55 UTC, douglaspalmer commented on testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/UserTest.java
> +        assertEquals("user11@localhost", userRep.getEmail());
Yes, fixed, thanks.

2020-03-03 09:26 UTC, stianst approved these changes

2020-03-03 09:26 UTC, merged