[KEYCLOAK-13187] - Concurrency issue when refreshing tokens and updating security context state
keycloak/keycloak pull request #6881
Opened 2020-03-09 13:55 UTC by pedroigor

2020-04-03 08:06 UTC, hmlnarik requested changes
Thanks @pedroigor ! One small nit and it is good to go IMO.

2020-04-03 12:01 UTC, pedroigor commented on adapters/oidc/adapter-core/src/main/java/org/keycloak/adapters/RefreshableKeycloakSecurityContext.java
> +        synchronized (this) {
You are right. That should avoid unnecessary refreshes if it happened before.

2020-04-04 19:32 UTC, hmlnarik approved these changes

2020-04-14 18:16 UTC, pdrozd approved these changes

2020-04-16 10:25 UTC, merged