Keycloak 13007
keycloak/keycloak pull request #6893
Opened 2020-03-13 15:55 UTC by Aboullos

2020-03-13 16:11 UTC, vmuzikar requested changes
Thank you, @Aboullos, nice work! Over all looks good, just found a few redundant lines of code.

2020-03-13 16:11 UTC, vmuzikar commented on testsuite/integration-arquillian/tests/other/base-ui/src/test/java/org/keycloak/testsuite/ui/account2/LDAPAccountTest.java
> +    public static final String WEBAUTHN_FLOW_ID = "75e2390e-f296-49e6-acf8-6d21071d7e10";
No need for WebAuthn in this test.

2020-03-13 16:11 UTC, vmuzikar commented on testsuite/integration-arquillian/tests/other/base-ui/src/test/java/org/keycloak/testsuite/ui/account2/LDAPAccountTest.java
> +@EnableFeature(value = Profile.Feature.WEB_AUTHN, skipRestart = true, onlyForProduct = true)
No need for WebAuthn in this test.

2020-03-13 16:11 UTC, vmuzikar commented on testsuite/integration-arquillian/tests/other/base-ui/src/test/java/org/keycloak/testsuite/ui/account2/LDAPAccountTest.java
> + * @author Vaclav Muzikar <vmuzikar@redhat.com>
Change the author to yourself. ;)

2020-03-13 16:11 UTC, vmuzikar commented on testsuite/integration-arquillian/tests/other/base-ui/src/test/java/org/keycloak/testsuite/ui/account2/LDAPAccountTest.java
> +        RealmRepresentation realm = testRealmResource().toRepresentation();
This is not used anywhere.

2020-03-13 16:11 UTC, vmuzikar commented on testsuite/integration-arquillian/tests/other/base-ui/src/test/java/org/keycloak/testsuite/ui/account2/page/SigningInPage.java
> +                result = getItemElement(CREATED_AT) != null;
`getItemElement` can never return null. It will either return the element or throw an exception.

2020-03-13 16:11 UTC, vmuzikar commented on testsuite/integration-arquillian/tests/other/base-ui/src/test/java/org/keycloak/testsuite/ui/account2/page/SigningInPage.java
> +            return result;
This is just a code style / optimization suggestion. I'll leave it up to you if you change it.

No need to create another variable. You can use something like:
```suggestion
            try {
                return getItemElement(CREATED_AT).isDisplayed();
            } catch (NoSuchElementException e) {
                return false;
            }
```

2020-03-16 11:26 UTC, vmuzikar approved these changes
@Aboullos LGTM, thank you!

2020-03-16 11:26 UTC, vmuzikar requested changes
Forgot one last thing. Please rename the PR.

2020-03-17 14:50 UTC, vmuzikar approved these changes

2020-03-18 13:11 UTC, abstractj approved these changes

2020-03-18 13:12 UTC, merged