[KEYCLOAK-11282] - Properly resolve config resolver
keycloak/keycloak pull request #6898
Opened 2020-03-16 14:19 UTC by pedroigor

2020-03-16 14:21 UTC, pedroigor commented
@mhajas Here it is

2020-03-16 19:44 UTC, pedroigor commented
Quickstart https://github.com/keycloak/keycloak-quickstarts/pull/172.

2020-03-17 07:42 UTC, mhajas requested changes
Thank you for the PR @pedroigor. Looks good to me, there is just one unnecessary import.

2020-03-17 07:42 UTC, mhajas commented on adapters/oidc/spring-boot-adapter-core/src/main/java/org/keycloak/adapters/springboot/KeycloakBaseSpringBootConfiguration.java
> +import org.springframework.context.annotation.Import;
Remove

2020-03-17 12:47 UTC, mhajas approved these changes

2020-03-17 14:48 UTC, stianst approved these changes

2020-03-17 14:49 UTC, merged