KEYCLOAK-13383 WebAuthnRegisterAndLoginTest fails with -Dproduct with…
keycloak/keycloak pull request #6919
Opened 2020-03-23 18:26 UTC by mposolda

As pointed by @vramik in the JIRA, the KeycloakContainerFeaturesController.handleEnableFeaturesAnnotationAfterTest with the "After" observer is not executed in case that test is finished preliminary due some "Assume" check.

The workaround was to move some methods of WebAuthnRegisterAndLoginTest to separate class. The test just checks just whether the feature is enabled/disabled and doesn't need the "WebAuthnAssume", hence it helps to have the KeycloakContainerFeaturesController.handleEnableFeaturesAnnotationAfterTest correctly triggered.

2020-03-24 07:49 UTC, mabartos approved these changes
@mposolda LGTM, but as you've mentioned, that's just a workaround. What if there will be a situation, in the future, a test will needs the `WebAuthnAssume`. It could results in the same behavior. I know it's not scope of this issue, but shouldn't be there some follow-up task for resolving (or deeper investigating) that?

2020-03-24 08:30 UTC, mposolda commented
@mabartos Good point. Could you please create follow-up JIRA for this? And possibly add it to the epic https://issues.redhat.com/browse/KEYCLOAK-13131 ?

It would be a problem just if we need to use "WebAuthnAssume" and at the same time, we can't enable/disable WebAuthn feature at the class level, but we need to use "method" level. Which hopefully won't be so common situation, but it can surely happen.

2020-03-24 08:57 UTC, mabartos commented
@mposolda Ok, I'll do the follow-up task. I understand your point. But I think, the situation, which has happened, is little bit weird. Just investigate why the `After` event doesn't execute :)

2020-03-24 09:31 UTC, vramik requested changes
Thank you @mposolda for quick fix. 

For auth-server-wildly everything works fine. 

However for auth-server-eap fails here. https://github.com/keycloak/keycloak/pull/6919/files#diff-8941e469f1b1d8721c2b16282042c788R67 

There is no `WebAuthnAuthenticatorFactory.PROVIDER_ID` in the list `serverInfo.getProviders()`.

2020-03-26 12:27 UTC, vramik approved these changes
@mposolda with latest master the tests started to pass. Approving.

2020-03-26 15:26 UTC, pdrozd approved these changes

2020-03-26 15:27 UTC, merged