KEYCLOAK-8836 Add test to check product name on welcome page
keycloak/keycloak pull request #6925
Opened 2020-03-24 09:57 UTC by Aboullos

Add test to check the presence of the correct product name on the welcome page

2020-03-24 20:00 UTC, ssilvert reviewed
LGTM.  If @vmuzikar agrees then we can merge.

2020-03-25 07:19 UTC, stianst requested changes

2020-03-25 07:19 UTC, stianst commented on testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/welcomepage/WelcomePageTest.java
> +        String expectedMessage = suiteContext.getAuthServerInfo().isEAP() ? "Red Hat Single Sign-On" : "Keycloak";
Do we have a way to get profile information on the test side?

2020-03-25 09:41 UTC, vmuzikar commented on testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/welcomepage/WelcomePageTest.java
> +        String expectedMessage = suiteContext.getAuthServerInfo().isEAP() ? "Red Hat Single Sign-On" : "Keycloak";
@stianst I don't know of a better approach (and I use it myself like that too :D).

2020-03-25 10:31 UTC, stianst commented on testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/welcomepage/WelcomePageTest.java
> +        String expectedMessage = suiteContext.getAuthServerInfo().isEAP() ? "Red Hat Single Sign-On" : "Keycloak";
Oki dokey

2020-03-25 10:31 UTC, stianst approved these changes
LGTM

2020-04-06 10:25 UTC, vmuzikar approved these changes
LGTM, tests passed with both KC and RH-SSO.
Thanks @Aboullos!

2020-04-21 09:30 UTC, merged