KEYCLOAK-8100 Improve handling of available claims in IdentityBroker Mappers
keycloak/keycloak pull request #6927
Opened 2020-03-24 18:24 UTC by thomasdarimont

We now expose the claim "sub" along side other claims for use in Identity Broker mappers.
Previously claims directly mapped to `JsonWebToken` fields (like sub) were not accessible for mappings.

2020-06-16 19:46 UTC, pedroigor requested changes
@thomasdarimont A bit of nitpicking although important to make our review a bit easier (even though your PR and changes are simple, but others may come with more changes).

Other than that, LGTM.

2020-06-16 19:46 UTC, pedroigor commented on services/src/main/java/org/keycloak/broker/oidc/mappers/AbstractClaimMapper.java
> +                jsonObject = (Map<String, Object>) val;
Could you please leave the format as is? The reason is that it makes a review more extensive if we start accepting code formatting changes. Yeah, we don't have a code style, but we're working on it :)

2020-06-16 19:46 UTC, pedroigor commented on services/src/main/java/org/keycloak/broker/oidc/mappers/AbstractClaimMapper.java
> +            JsonWebToken token = (JsonWebToken) context.getContextData().get(KeycloakOIDCIdentityProvider.VALIDATED_ACCESS_TOKEN);
Same here, please remove changes formatting the code.

2020-06-16 19:46 UTC, pedroigor commented on services/src/main/java/org/keycloak/broker/oidc/mappers/AbstractClaimMapper.java
> +            JsonWebToken token = (JsonWebToken) context.getContextData().get(KeycloakOIDCIdentityProvider.VALIDATED_ID_TOKEN);
Same here, please remove changes formatting the code.

2020-06-16 19:46 UTC, pedroigor commented on services/src/main/java/org/keycloak/broker/oidc/mappers/AbstractClaimMapper.java
> +            List list = (List) value;
Same here, please remove changes formatting the code.

2020-06-17 08:48 UTC, thomasdarimont commented
@pedroigor Thanks for your comments! I just rebased and adapted the PR.

2020-06-17 08:51 UTC, thomasdarimont commented
I also revised the name of the PR and the commit message.

2020-06-17 15:56 UTC, pedroigor approved these changes

2020-06-17 15:56 UTC, merged