KEYCLOAK-13445 Modify SigningInTest for changes in credential type
keycloak/keycloak pull request #6930
Opened 2020-03-25 09:32 UTC by Aboullos

Modify SigningIn tests according to the functionality changes in the credential types

2020-03-26 13:28 UTC, vmuzikar requested changes
@Aboullos Thank you for the fix! Please see comments below.

2020-03-26 13:28 UTC, vmuzikar commented on testsuite/integration-arquillian/tests/other/base-ui/src/test/java/org/keycloak/testsuite/ui/account2/SigningInTest.java
> +        assertTrue("Title is not visible", otpCredentialType.isTitleVisible());
Before this, we need to disable given required action and also add an assert to check that the setup link is not visible. We could also check the user credential count didn't change after that. Something like:
```suggestion
        assertTrue("Set up link is not visible", otpCredentialType.isSetUpLinkVisible());

        RequiredActionProviderRepresentation requiredAction = new RequiredActionProviderRepresentation();
        requiredAction.setEnabled(false);
        testRealmResource().flows().updateRequiredAction(CONFIGURE_TOTP.name(), requiredAction);

        assertFalse("Set up link is visible", otpCredentialType.isSetUpLinkVisible());
        assertFalse("Not set up link is visible", otpCredentialType.isNotSetUpLinkVisible());
        assertTrue("Title is not visible", otpCredentialType.isTitleVisible());
        assertEquals(2, otpCredentialType.getUserCredentialsCount());
```

2020-03-26 13:28 UTC, vmuzikar commented on testsuite/integration-arquillian/tests/other/base-ui/src/test/java/org/keycloak/testsuite/ui/account2/SigningInTest.java
> +        assertTrue("Title is visible", credentialType.isTitleVisible());
Same as above in `otpTest`.

2020-03-27 10:28 UTC, vmuzikar approved these changes
LGTM, thank you @Aboullos!

2020-03-27 11:12 UTC, hmlnarik approved these changes

2020-03-27 12:26 UTC, hmlnarik commented
Travis run - https://travis-ci.com/github/keycloak/keycloak/builds/155045890

2020-03-27 12:29 UTC, pdrozd approved these changes

2020-03-27 12:29 UTC, hmlnarik commented
Travis failed to report back for some reason but the tests passed. Thus merging regardless

2020-03-27 12:29 UTC, merged