KEYCLOAK-13439 Enhanced the processes of fetching a realm's IdentityProvider by alias or by id
keycloak/keycloak pull request #6942
Opened 2020-03-27 21:40 UTC by laskasn

Enhanced the processes of fetching a realm's IdentityProviders by alias or by id, by removing the for loops, and making calls where IdPs come prefiltered by the database, which is faster.

This change is needed, because we plan to add quite a few identityproviders on a realm (of a saml federation), thus we need to speed-up the fetching of the IdPs.

Did not add additional tests, because all what was changed, was on existing methods, which were already covered by the tests in 
IdentityProviderTest class
- testUpdate() -> calls the IdentityProvidersResource.get() which in turn calls the functions which fetch Identity Providers by alias or by id  
- testRemove() -> calls the IdentityProvidersResource.get() and the IdentityProvidersResource.remove() which at some point, fetches the realm's Identity provider by id

2020-03-31 13:35 UTC, stianst commented
Thanks for the PR, but does this actually provide any real benefits?

2020-03-31 13:59 UTC, laskasn commented
Well, it makes it faster when you have a large number of idps and need to loop over them (i.e. with a client) in order to apply a specific task on them. No? At least it scales a little better.

2020-03-31 14:36 UTC, stianst commented
Have you performed any performance testing here? Or are you just guessing.

2020-03-31 14:38 UTC, stianst commented
Identity providers are cached/fetched together with the realm data, so I'm not quite following why this change is needed, so would like to get some more details/motivation around this, otherwise we'll need to reject this.

2020-03-31 14:38 UTC, stianst requested changes
Provide rational and evidence of why this change is needed

2020-03-31 17:08 UTC, laskasn commented
Ok then, if everything's cached there's no point in making any changes, since a cached version will always be served. Plus the fact that the number of idps will be at most (extreme cases) a couple of thousands.
I'll close it.

2020-03-31 17:08 UTC, closed without merging

2020-04-01 07:42 UTC, stianst commented
Thousands is more than we have expected really, so if you can show us some bad performance figures with an amount of IdPs you are expecting then we can consider doing some improvements.

2020-04-09 13:18 UTC, laskasn commented
We added in keycloak the IdPs of the EduGain (saml) federation as published here:
https://md.aai.grnet.gr/feeds/edugain-idp-samlmd.xml
(3590 IdPs), but we now face even more problems than just a presumable performance loss from a loop.
Clicking any of the UI tabs related to the Realm, {Realm Settings, Clients, Client Scopes, Roles, Identity Providers, etc} the loading time takes ~15 seconds, including a freeze of the ui. Diggind a little into the server calls, there are 2 calls ('admin/realms' and 'admin/realms/master') which fetch 11,5 mb of serialized json each, 23mb in total. Digging even more into the json, we see that it brings the whole realm (including a full description of the 3.5k of IdPs), just to show basic realm settings. Maybe we could work on an enhancement for that. What do you think?

2020-04-15 08:01 UTC, stianst commented
@laskasn it would be great to be able to support this, as I appreciate there are some situations like this especially in the education domain. Can you start a thread on the dev mailing list around this and we can discuss there? Thinking about this a bit made me wonder if actually you want to have support for a different way to define providers. I.e. some external list of providers, rather than having to define them all in the KC db.