KEYCLOAK-13916 Refactor SAML metadata generation to use the SAMLMetadataWriter class
keycloak/keycloak pull request #6996
Opened 2020-04-22 12:04 UTC by lscorcia

Changes the current IdP/SP metadata generation logic, based on string manipulations, to use the more robust SAMLMetadataWriter class. The generated XML is functionally the same as before. 

Small notes:
* I had to add a couple of constants to the JBossSAMLURIConstants class. Are those really useful? Does Keycloak client really support SAML1/SECEXT protocols?
* I had to fix some minor errors in the SAMLMetadataWriter class, i.e.:
  a. Attribute protocolSupportEnumeration in SPSSODescriptor: was rendering only the first protocol of the supplied list
  b. SPSSODescriptor did not output KeyDescriptors
  c. IDPSSODescriptor-generated files were not compliant with the SAML Metadata XSD (the NameIDFormat tag must be placed after the SingleLogout elements)
* I had to change the value of the constant FALLBACK_ERROR_URL_STRING to make it a valid URI (replaced spaces with underscores)
* The previous generated XMLs were indented - after this PR they no longer are. I haven't been able to find a way to set the XMLStreamWriter class to pretty print. Suggestions welcome!
* The tests have been updated and are all passing (after pulling in https://github.com/keycloak/keycloak/pull/6993).

2020-04-22 15:51 UTC, lscorcia commented
I have no idea why the automatic tests failed, the tests complete successfully if I run `mvn -Dtest=IdentityProviderTest -DfailIfNoTests=false package`, even after merging latest master into my branch. Am I running the tests incorrectly?

2020-04-23 01:09 UTC, lscorcia commented
I fixed the failing tests with a simple check, but the right fix would probably to correctly import the `NameIDFormat` tag in the `SamlIdentityProviderFactory.parseConfig` class. Anyway I felt like that would deserve a separate pull request. Please, let me know if it's good enough to go in!

2020-04-30 14:19 UTC, lscorcia commented
Rebased to current and squashed commits.

2020-07-03 13:13 UTC, hmlnarik requested changes
Thank you very much for your contribution! Looking at the code, the changes look good to me, nice work!

> I had to add a couple of constants to the JBossSAMLURIConstants class. Are those really useful? Does Keycloak client really support SAML1/SECEXT protocols?

You are correct, neither of them is needed, please remove them.

> The previous generated XMLs were indented - after this PR they no longer are. I haven't been able to find a way to set the XMLStreamWriter class to pretty print. Suggestions welcome!

No worries, indentation is not a concern at all.

Apart from this, only a few nits and the PR is ready to go.

2020-07-03 13:13 UTC, hmlnarik commented on services/src/main/java/org/keycloak/protocol/saml/IDPMetadataDescriptor.java
> +import org.keycloak.dom.saml.v2.metadata.*;
Please avoid star imports

2020-07-03 13:13 UTC, hmlnarik commented on services/src/main/java/org/keycloak/protocol/saml/installation/SamlSPDescriptorClientInstallation.java
> +            if (logoutUrl == null || assertionUrl.trim().isEmpty()) logoutUrl = FALLBACK_ERROR_URL_STRING;
```suggestion
            if (logoutUrl == null || logoutUrl.trim().isEmpty()) logoutUrl = client.getManagementUrl();
            if (logoutUrl == null || logoutUrl.trim().isEmpty()) logoutUrl = FALLBACK_ERROR_URL_STRING;
```

2020-07-03 14:02 UTC, lscorcia commented on services/src/main/java/org/keycloak/protocol/saml/IDPMetadataDescriptor.java
> +import org.keycloak.dom.saml.v2.metadata.*;
Thanks, done!

2020-07-03 14:03 UTC, lscorcia commented on services/src/main/java/org/keycloak/protocol/saml/installation/SamlSPDescriptorClientInstallation.java
> +            if (logoutUrl == null || assertionUrl.trim().isEmpty()) logoutUrl = FALLBACK_ERROR_URL_STRING;
Nice catch!

2020-07-03 14:03 UTC, lscorcia commented
Applied code review suggestions, squashed commits and rebased to current.

2020-07-09 07:39 UTC, hmlnarik approved these changes
Thank you for the contribution!

2020-07-09 07:39 UTC, merged