Update InstagramIdentityProvider.java
keycloak/keycloak pull request #7015
Opened 2020-04-28 07:35 UTC by jbpin

Update Instagram provider to support instagram graph api. Unfortunately we can't retrieve user's name.

2020-04-30 06:23 UTC, stianst commented
Please explain why you are proposing this change

2020-04-30 07:35 UTC, jbpin commented
Hi @stianst. Instagram user endpoint have change: 
https://developers.facebook.com/docs/instagram-basic-display-api/reference/me

Actually I'm not sure we should change it or create a new one ?

2020-04-30 07:36 UTC, jbpin commented
Maybe related to this: https://issues.redhat.com/browse/KEYCLOAK-7761

2020-04-30 07:45 UTC, jbpin commented
I've created a new Issue: https://issues.redhat.com/browse/KEYCLOAK-14023

2020-05-05 01:41 UTC, hguerrero commented
@stianst can we merge this? it should be fixing the problem with the instagram login as described correctly in the JIRA

2020-06-13 02:21 UTC, JavaSwitch commented on services/src/main/java/org/keycloak/social/instagram/InstagramIdentityProvider.java
> +	  		String username = getJsonProperty(profile, "username");
raw no 'data' of node

```suggestion
			JsonNode raw = SimpleHttp.doGet(PROFILE_URL,session)
				.param("access_token", accessToken)
				.param("fields", PROFILE_FIELDS)
				.asJson();
			
			logger.debug(raw.toString());

			String id = getJsonProperty(raw, "id");
	  		String username = getJsonProperty(raw, "username");
```

2020-06-13 02:33 UTC, huangwenkan9 approved these changes

2020-06-13 03:19 UTC, JavaSwitch commented on services/src/main/java/org/keycloak/social/instagram/InstagramIdentityProvider.java
> +	  		String username = getJsonProperty(profile, "username");
raw not 'data' of node
```suggestion
			logger.debug(raw.toString());
			
			String id = getJsonProperty(raw, "id");
	  		String username = getJsonProperty(raw, "username");
```

2020-06-15 13:22 UTC, vmuzikar commented
Will try to review by the end of this week.

2020-06-24 11:27 UTC, vmuzikar reviewed
@jbpin Thank you for your contribution. What's the motivation to make this change? The Instagram IdP seems to be working as expected and the [used API](https://www.instagram.com/developer/endpoints/users/#get_users_self) doesn't seem to be deprecated.

2020-06-24 12:28 UTC, vmuzikar commented
Scratch that. The old API is really deprecated and will get disabled in a few days(!)

2020-06-24 13:20 UTC, hguerrero commented
So yes, the old API is deprecated and moved to the new Facebook Graph for most of the old features. However there is a basic API that includes the OAuth flow to autenticate. This API won't return the name but still returns an username at works for the purpose of brokering.

2020-06-24 15:10 UTC, vmuzikar requested changes
@jbpin Thank you for your contribution.

As @JavaSwitch already mentioned, this requires fixing which I can confirm.

Also, we need to address migration. Let's say someone uses older Keycloak version that uses legacy Instagram API. Then upgrades to newer Keycloak version to use the new Instagram API but users are now unable to login using Instagram, because the new API uses different user IDs. Luckily, per the documentation [we can get the old legacy ID](https://developers.facebook.com/docs/instagram-basic-display-api). Those legacy IDs will be however available only temporarily, so the IdP in Keycloak will have to update it to the new ID.

This will also require updating the [documentation](https://www.keycloak.org/docs/latest/server_admin/#social-identity-providers) (incl. the note about legacy IDs).

As this is quite critical fix, please let us know if you're able to work on this.

2020-06-29 07:04 UTC, vmuzikar commented
Since this is quite an urgent matter, we'll take changes from this PR and finish them up in a new PR.

2020-06-29 07:12 UTC, jbpin commented
> Since this is quite an urgent matter, we'll take changes from this PR and finish them up in a new PR.

Sorry I don't have time to work on this one.

2020-06-29 07:48 UTC, vmuzikar commented
@jbpin No worries! :) Thanks again for your contribution, I'll use it in the new PR.

2020-07-01 21:39 UTC, abstractj commented
Superseded by #7219

2020-07-01 21:39 UTC, closed without merging