KEYCLOAK-13998 ConditionalRoleAuthenticator doesn't work with composite roles
keycloak/keycloak pull request #7030
Opened 2020-04-29 20:27 UTC by vanrar68

- Check if user has role by invoking user.hasRole() instead of getting matches with user.getRoleMappings() which only returns direct roles
- Add error message in case of non existent role name
- Update tooltip text for ConditionalRoleAuthenticator to mention the syntax for client roles (same text as OIDC Hardcoded Role Mapper)

2020-05-04 09:09 UTC, mposolda commented
@vanrar68 Thanks a lot. The fix looks good. It will be good to also add an automated test for this. Do you have a chance for this? For the inspiration, there is already BrowserFlowTest.testConditionalRoleAuthenticator . I suppose some other similar method can be added to test the scenario with composite roles? There is also CompositeRolesTest, which contains some utilities how to add composite role to some other role, which can be nice for inspire as well.

2020-05-04 09:10 UTC, mposolda requested changes
LGTM, only the test may need to be added. See above

2020-05-04 17:27 UTC, vanrar68 commented
Added 2 tests (realm composite role and client composite role). Let me know if more are needed

2020-05-04 18:35 UTC, mposolda requested changes
@vanrar68 The tests are nice, Thanks for them!

However I see that some other tests are failing. In general, it will be better to avoid any changes in the testrealm.json file as that file is used by many tests and that is probably reason of failing tests. Instead of update testrealm.json, you can possibly add required roles, composite roles, role mappings etc programatically in the test.

See for example CompositeRolesTest, which is adding roles, role mappings etc programaticaly during the tests. It uses admin REST API for it.

2020-05-04 22:34 UTC, vanrar68 commented
@mposolda Done!

2020-05-05 06:38 UTC, mposolda approved these changes
@vanrar68 Nice work! Thanks

2020-05-05 06:39 UTC, merged