KEYCLOAK-14044 Move impl of processAccessTokenResponse to OIDCIdentityProvider
keycloak/keycloak pull request #7034
Opened 2020-05-02 10:30 UTC by jonaskello

This resolves the problem that Identity Provider of type "Open ID Connect 1.0" cannot map claims from access token to user attributes using user attribute importer mapper. The reason it was not working is that the `OIDCIdentityProvider` did not store the access token in the context as the `processAccessTokenResponse()` method was empty. However the `KeycloakOIDCIdentityProvider` that derives from it did override the `processAccessTokenResponse()` method and added impl to add access token to context. So to solve it this PR moves the impl of `processAccessTokenResponse()` up to `OIDCIdentityProvider` so both classes store the access token in the context.

2020-05-05 14:52 UTC, mposolda requested changes
@jonaskello Thanks for the PR. However it doesn't look like a valid change.

Per OIDC specification, the format of accessToken is an opaque string. This means that in the generic OIDC provider, you cannot assume that accessToken is JWT. In case of Keycloak implementation, the accessToken is JWT, however that is specific to Keycloak implementation. So instead of this PR, I think you should use claims from IDToken or from UserInfo endpoint. This should work with OIDCIdentityProvider

2020-05-05 15:22 UTC, jonaskello commented
I did not know that about the OIDC specification. I think in practice though, many OIDC implementations use JWT? I have not seen one that does not so I would be curious what else they would use :-)

Perhaps there could be a check if it is a JWT and then allow mapping from it same as for the keycloak identity provider?

If it will be totally impossible to map from access token in OIDCIdentityProvider then at the very least I think the documentation needs to be updated becuase it clearly states [here](https://github.com/keycloak/keycloak/blob/master/services/src/main/java/org/keycloak/broker/oidc/mappers/UserAttributeMapper.java#L174) that it will "Import declared claim if it exists in ID, access token or the claim set returned by the user profile endpoint into the specified user property or attribute.". This led me on a long chase which ended with this PR.

Our scenario is that we have an existing OIDC server that we cannot change. So I cannot move claims around. I need to get them from the access token. The eventual plan is to migrate to keycloak but I need to do it in steps, the first one being using keycloak in front of the old OIDC server where the old OIDC server is the default IdP so users still think they are logging in to the old one. Not sure how to support this scenario if it is not possible to map from the access token?

Would it be acceptable to allow access token mapping for general OIDC providers in the case that JWT is detected and update the docs to reflect that limitation? In that case I could try to change the PR into somthing like that.

Another Idea would be to add another IdentityProvider class that inherits from OIDCIdentityProvider, something like OIDCIdentityProviderJWT and add the override for parsing the access token to it. Then it could be documented that that IdP impl is for standard OIDC servers that use JWT and it can handle mapping from access token.

2020-05-05 16:02 UTC, mposolda commented
@jonaskello I see. I suggest to start a thread on keycloak-dev mailing list with this suggested change. You can expect more feedback on the ML than on this PR.

BTV. I am not 100% sure, but I think that Google is the example of OIDC provider, which doesn't have accessToken in the JWT format.

2020-05-05 16:30 UTC, jonaskello commented
@mposolda ok, thanks. I started a [thread here](https://groups.google.com/forum/#!topic/keycloak-dev/xQZOe_nfyTs). Lets discuss there instead. I guess we can leave this PR open until the discussions come to a conclusion? For the alternative of try-parsing JWT I think this PR could easily be updated to support that.

2020-06-09 07:13 UTC, mposolda commented
@jonaskello As discussed on the mailing list, we are not going to add this feature for now. So I am closing this PR. Sorry for being so late with finally doing the decision on this.

2020-06-09 07:13 UTC, closed without merging

2020-06-09 15:12 UTC, jonaskello commented
@mposolda Having studied the OIDC standard a little closer I understand your decision. However the documentation clearly states that it should work so to avoid having others spending several hours trying to make it work in the future I would recommend a documentation update instead of this PR.

For our use-case a better solution would probably be to migrate all user directly instead of trying to migrate them step by step by mapping claims over from the access token issued by the old login server. The problem there is that  keycloak does not seem to have built-in support to import from other solutions with different password hashing algos.

2020-06-09 15:26 UTC, mposolda commented
@jonaskello Yes, true. But Keycloak has User Storage SPI, which can be an alternative for you? See Development guide for more details - but it requires some Java development, which I am not sure is an option for you...

2020-06-09 15:26 UTC, mposolda commented
@jonaskello I updated the JIRA for improve the tooltip in the documentation