KEYCLOAK-7209: Always send id_token received initially for logout
keycloak/keycloak pull request #7059
Opened 2020-05-12 08:22 UTC by micedre

Fix for KEYCLOAK-7209, the method always use the old token, without checking its expiration.

2020-05-18 13:38 UTC, mposolda requested changes
@micedre Thanks for the PR. Few points:
- It will be good to still try to refresh the token and use the refreshed ID Token in case that it is available. We can fallback to the FEDERATED_ID_TOKEN just if refresh fails for some reason (EG. unavailable refreshToken, failed to send (or parse) the tokenResponse or the case when tokenResponse.getIdToken() is null.)
- It will be good to have automated test for this. You can use time-offset to simulate stuff with expired tokens. See for example KcOidcBrokerLogoutTest where the new test method can be added. Also see for example AbstractKeycloakTest.setTimeOffset (and the usage of it) for the time-offset example

2020-05-19 07:05 UTC, micedre commented
>     * It will be good to still try to refresh the token and use the refreshed ID Token in case that it is available. We can fallback to the FEDERATED_ID_TOKEN just if refresh fails for some reason (EG. unavailable refreshToken, failed to send (or parse) the tokenResponse or the case when tokenResponse.getIdToken() is null.)

Is it really useful ? We are loging out the user, I think trying to get a non expired token is a waste of time, don't you think ? I may have missed something :)

>     * It will be good to have automated test for this. You can use time-offset to simulate stuff with expired tokens. See for example KcOidcBrokerLogoutTest where the new test method can be added. Also see for example AbstractKeycloakTest.setTimeOffset (and the usage of it) for the time-offset example

Thanks, I didn't know where to look, I will try and add them.

2020-05-19 09:44 UTC, mposolda commented
>> It will be good to still try to refresh the token and use the refreshed ID Token in case that it is available. We can fallback to the FEDERATED_ID_TOKEN just if refresh fails for some reason (EG. unavailable refreshToken, failed to send (or parse) the tokenResponse or the case when tokenResponse.getIdToken() is null.)

> Is it really useful ? We are loging out the user, I think trying to get a non expired token is a waste of time, don't you think ? I may have missed something :)

It is possible that some IDPs can reject the logout in case that you send them expired token as id_token_hint. Hence I assume it is always slightly better option to send the "up-to-date" ID Token (if possible) instead of sending the expired ID Token.

2020-06-08 18:24 UTC, mposolda commented
@micedre I am closing the PR as we need to reduce the queue of the pull requests ;) But feel free to re-open once you are able to add the requested changes and the test

2020-06-08 18:24 UTC, closed without merging