KEYCLOAK-14176 updated license for account preview
keycloak/keycloak pull request #7075
Opened 2020-05-15 07:17 UTC by edewit

2020-05-15 14:00 UTC, vmuzikar reviewed
I'm afraid this might be a bit more difficult than we though. All the dependencies are now bundled to a single JS file. Is there any way how can we tell what dependencies are really included there? I think we even have some new deps added with the My Resource page implementation, so this should be reflected too.

We'll need to update the `locations` attributes because many of them are now pointing to non-existing JS files as they are now part of the one big file.

Also, the licenses have to be updated for [RH-SSO](https://github.com/keycloak/keycloak/tree/master/distribution/feature-packs/server-feature-pack/src/main/resources/licenses/rh-sso) too.

2020-05-16 16:09 UTC, edewit commented
All the dependencies are mentioned in the `package.json` with snowpack we
removed a lot of dependencies in favour of our own implementation. I guess
it would be better to write a little script to do this. I meant to ask
about this, why does it sometimes mention the individual files in the
folder and sometimes the entire package? Guess it will be easier and more
"robust" to just name the folders.

On Fri, May 15, 2020 at 4:00 PM Václav Muzikář <notifications@github.com>
wrote:

> *@vmuzikar* commented on this pull request.
>
> I'm afraid this might be a bit more difficult than we though. All the
> dependencies are now bundled to a single JS file. Is there any way how can
> we tell what dependencies are really included there? I think we even have
> some new deps added with the My Resource page implementation, so this
> should be reflected too.
>
> We'll need to update the locations attributes because many of them are
> now pointing to non-existing JS files as they are now part of the one big
> file.
>
> Also, the licenses have to be updated for RH-SSO
> <https://github.com/keycloak/keycloak/tree/master/distribution/feature-packs/server-feature-pack/src/main/resources/licenses/rh-sso>
> too.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/keycloak/keycloak/pull/7075#pullrequestreview-412675125>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAAMPPOXDCSQA5UDT3GFKPLRRVDIFANCNFSM4NBKOWRQ>
> .
>

2020-05-27 10:57 UTC, edewit commented
@vmuzikar update with the generated xml

2020-06-08 09:54 UTC, edewit commented
@vmuzikar updated now that #7128 has been merged

2020-06-08 13:07 UTC, ssilvert commented
@vmuzikar Can you take one last look before we merge?

2020-06-08 15:35 UTC, vmuzikar commented
@ssilvert Sure, will re-review tomorrow.

2020-06-08 18:38 UTC, ssilvert commented
> @ssilvert Sure, will re-review tomorrow.

@vmuzikar Thanks.  I'll try not to jump the gun this time.

2020-06-09 12:03 UTC, vmuzikar requested changes
Thanks for the update. Even though it's a bit hard to double check if are dependencies are correct, I know you're using some kind of snowpack plugin you've developed (good work, BTW!) to get the deps list, so there's not much room for error. BTW, we should [document](https://github.com/keycloak/keycloak/blob/master/docs/dependency-license-information.md) that, but that's out of scope of this PR.

Last thing to do is to run [download-license-files.sh](https://github.com/keycloak/keycloak/blob/master/distribution/licenses-common/download-license-files.sh).

2020-06-11 12:17 UTC, edewit commented on distribution/feature-packs/server-feature-pack/src/main/resources/licenses/keycloak/licenses.xml
> +        <file>themes/keycloak/common/resources/web_modules/common/index-fd2ed651.js</file>
> Last thing to do is to run [download-license-files.sh](https://github.com/keycloak/keycloak/blob/master/distribution/licenses-common/download-license-files.sh).

I already did that...

2020-06-11 20:41 UTC, ssilvert commented on distribution/feature-packs/server-feature-pack/src/main/resources/licenses/keycloak/licenses.xml
> +        <file>themes/keycloak/common/resources/web_modules/common/index-fd2ed651.js</file>
@vmuzikar Do you approve to merge this one now?

2020-06-15 06:26 UTC, vmuzikar commented on distribution/feature-packs/server-feature-pack/src/main/resources/licenses/keycloak/licenses.xml
> +        <file>themes/keycloak/common/resources/web_modules/common/index-fd2ed651.js</file>
We need to (re-)run the mentioned script. Currently, there are many license files missing. This is a problem for the licenses.html that is generated during the build and included in the distribution – there are many broken links to local files.

2020-06-15 08:06 UTC, edewit commented
Updated all urls

2020-06-16 08:41 UTC, vmuzikar submitted a review, later dismissed
LGTM, thanks @edewit!

Created a JIRA to document for others how to actually update the licenses: https://issues.redhat.com/browse/KEYCLOAK-14485

2020-06-17 07:55 UTC, vmuzikar approved these changes

2020-06-17 11:41 UTC, ssilvert approved these changes

2020-06-17 11:41 UTC, merged