KEYCLOAK-13915 Update Jetty 9.4.x dependency to latest version
keycloak/keycloak pull request #7094
Opened 2020-05-22 20:56 UTC by thomasdarimont

Adapted Jetty94SessionManager to workaround Jetty 9.4 API changes.
The Method org.eclipse.jetty.server.session.SessionHandler#getHttpSession
was changed from public to protected which makes it no longer accessible.

As a workaround the method contents were inlined.

2020-06-18 06:00 UTC, slaskawi requested changes
The code LGTM! Only one, very small nitpick found.

2020-06-18 07:55 UTC, thomasdarimont commented
Thanks for review. I adapted the PR and rebased on current master.
The build will fail due to: #7178

2020-06-18 10:25 UTC, slaskawi submitted a review, later dismissed

2020-06-18 10:27 UTC, martin-kanis submitted a review, later dismissed

2020-06-18 12:52 UTC, martin-kanis approved these changes

2020-10-07 14:40 UTC, abstractj approved these changes

2020-10-07 14:40 UTC, merged