KEYCLOAK-12729 Add password policy not-email
keycloak/keycloak pull request #7103
Opened 2020-05-23 23:44 UTC by thomasdarimont

Added test cases and initial translations

2020-05-24 22:10 UTC, thomasdarimont commented
The tests work from me locally - perhaps I'm missing a cleanup procedure after the test run.

2020-06-19 09:22 UTC, mposolda requested changes
@thomasdarimont Thanks for the contribution! It looks good to me. Just 2 very minor things:
- Cleanup will be probably needed in some tests as you already pointed in some comment above
- It will be good to send small PR to the documentation as well to make sure this page is updated with the new policy https://www.keycloak.org/docs/latest/server_admin/index.html#_password-policies

2020-06-19 09:22 UTC, mposolda commented on testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/RegisterTest.java
> +        notEmailRealm.setRegistrationEmailAsUsername(true);
@thomasdarimont As you pointed, you are missing cleanup of those things after the test method.

2020-06-19 09:22 UTC, mposolda commented on testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/account/AccountFormServiceTest.java
> +        setPasswordPolicy("notEmail(1)");
I guess this probably worth cleanup as well.

2020-07-29 07:55 UTC, mposolda commented
@thomasdarimont Any update regarding this PR?

2020-08-20 15:10 UTC, mposolda commented
@thomasdarimont Hi, any update on this PR or are you in the middle of PTO season? :-)

2020-08-21 12:54 UTC, mposolda approved these changes
@thomasdarimont Cool, Thanks! :-)

2020-08-21 12:55 UTC, merged