More polish translation and fixed language name translation
keycloak/keycloak pull request #7144
Opened 2020-06-07 00:25 UTC by psztoch

2020-06-08 10:25 UTC, VinodAnandan commented
@psztoch Thank you for your contribution.

As mentioned in the following contribution guidelines, the commit message needs a JIRA number. Sometimes you may find the issue in JIRA backlog (https://issues.redhat.com/projects/KEYCLOAK/ ). If you can't find it, could you please create a JIRA issue and prefix it?

https://github.com/keycloak/keycloak/blob/master/CONTRIBUTING.md

2020-06-16 21:08 UTC, psztoch commented
Sorry, but I can't add Jira issue.
RedHat SSO team can't solve problem with my account registration... and I can't login to your Jira system.

2020-06-16 21:30 UTC, VinodAnandan commented
@psztoch I have created one - https://issues.redhat.com/browse/KEYCLOAK-14492 . I hope the team can fix the issues soon

2020-06-17 11:51 UTC, slaskawi requested changes
Thanks for this contribution @psztoch !

Overall it looks great. I found a couple of small issues that could be fixed. Let's give @bdaw a few days to check it up. 

Also - may I ask you to squash all your commits?

2020-06-17 11:51 UTC, slaskawi commented on themes/src/main/resources-community/theme/base/account/messages/messages_pl.properties
> +authenticatorTitle=Autentykator dwuetapowy
Maybe better "Uwierzytelnienie dwuetapowe"?

2020-06-17 11:51 UTC, slaskawi commented on themes/src/main/resources-community/theme/base/account/messages/messages_pl.properties
> +clients=Klienci
@bdaw I always have a problem with this one: "Klienci" or "Klienty" ? Usually, I use "Aplikacje klienckie", so I don't hit this problem.

2020-06-17 11:51 UTC, slaskawi commented on themes/src/main/resources-community/theme/base/account/messages/messages_pl.properties
> +backTo=Wróć do {0}
In the account console this gets rendered as "Wróć do Konsola administratora bezpieczeństwa". Perhaps we should put ":" at the end?

2020-06-17 22:32 UTC, psztoch commented
@slaskawi Fixed and squashed.

2020-06-20 20:24 UTC, psztoch commented
I fixed some typos and add the reported to me demand for missing fields from OpenID connect.

2020-06-30 13:08 UTC, psztoch commented
@bdaw Have you any progress in evaluation? ;-)

2020-08-04 18:12 UTC, psztoch commented
What is problem with this pull request?!

2020-08-06 06:55 UTC, bdaw commented
Looks good on my end. 

Sorry for the delay in the review. Vacation season and I missed it when catching up.

2020-08-06 06:58 UTC, bdaw submitted a review, later dismissed

2020-08-10 08:12 UTC, slaskawi reviewed
@psztoch The code looks good. Could you please remove the merging commit from this PR? Once this is done, please ping me and I'll approve it.

2020-08-11 13:35 UTC, psztoch commented
@slaskawi What is next?

2020-10-16 20:25 UTC, psztoch commented
Panowie @slaskawi i @bdaw, czy mam rozumieć, że nie warto inwestować swojego zaangażowania w projekt Keycloak, bo jest to bezcelowe i tak nie zostanie wykorzystane?

2020-10-23 09:12 UTC, slaskawi approved these changes

2020-11-03 14:59 UTC, psztoch commented
@bdaw ?!

2020-11-24 15:02 UTC, psztoch commented
@slaskawi Czy mogę prosić Cię o wsparcie w zakresie tego pull request'a?

2020-12-07 07:05 UTC, bdaw approved these changes
lgtm

2020-12-07 07:10 UTC, slaskawi approved these changes

2020-12-07 07:36 UTC, merged