KEYCLOAK-14394 Update to WebAuthn4J 0.12.0.RELEASE
keycloak/keycloak pull request #7145
Opened 2020-06-07 11:36 UTC by ynojima

Adresses https://issues.redhat.com/browse/KEYCLOAK-14394

Update to WebAuthn4J 0.12.0.RELEASE.

Replace `WebAuthnManager` with `WebAuthnAuthenticationManager` and `WebAuthnRegistrationManager`, which are introduced in 0.12.0.RELEASE.
Originally `WebAuthnManager` is intended that its instance is shared between registration processing and authentication processing, but the design doesn't fit the case like Keycloak, `WebAuthnAuthenticationManager` and `WebAuthnRegistrationManager` are introduced.

2020-06-07 19:13 UTC, tnorimat submitted a review, later dismissed
LGTM

2020-06-09 08:09 UTC, ynojima commented
Rebased to the master HEAD to re-run stalled Travis tests.

2020-06-09 14:49 UTC, mposolda reviewed
@ynojima Thanks for the PR! It looks good to me from the technical perspective.

However as @tnorimat already knows, the main issue with upgrade of the dependency is an additional effort needed to make sure that things will still work in our internal productization process. I will check with @drichtarik and @pskopek , but as far as I know, the upgrade of the webauhn4j dependency is the task for few days for us and our productization process...

Hence it is about the ratio to upgrade regularly in some intervals to not miss important updates and security fixes, but at the same time, not spend too much time as every version upgrade is additional effort for us. I need to doublecheck with the rest of the team and will get back to you...

2020-06-10 03:15 UTC, ynojima commented
@mposolda, 
Updating WebAuthn4J has an aspect of remediation for the bug filed in https://issues.redhat.com/browse/KEYCLOAK-14362.
Sorry, I wrote it in the JIRA ticket (KEYCLOAK-14394) description, but I haven't written it in this pull-request description.
Please keep it in mind when you judge the priority.

2020-06-10 07:16 UTC, mposolda commented
@ynojima Thanks for the info!

2020-06-22 18:26 UTC, drichtarik commented on distribution/feature-packs/server-feature-pack/src/main/resources/licenses/rh-sso/licenses.xml
> +          <url>https://raw.githubusercontent.com/webauthn4j/webauthn4j/0.12.0.RELEASE/LICENSE.txt</url>
Can you please update the <version> tag to `0.12.0.RELEASE-redhat-00001`

2020-06-22 18:29 UTC, drichtarik requested changes
The licenses need webauthn version tag

2020-06-22 18:29 UTC, drichtarik commented on distribution/feature-packs/server-feature-pack/src/main/resources/licenses/rh-sso/licenses.xml
> +          <url>https://raw.githubusercontent.com/webauthn4j/webauthn4j/0.12.0.RELEASE/LICENSE.txt</url>
The url is correct but can you please update the version tag to `0.12.0.RELEASE-redhat-00001`

2020-06-23 08:51 UTC, mposolda approved these changes

2020-06-23 08:52 UTC, mposolda commented
@ynojima After talking with @drichtarik, we will merge your PR and then we will send another PR for update licences. Thanks again!

2020-06-23 08:53 UTC, merged