[KEYCLOAK-14037] Enable s390x build support in Travis
keycloak/keycloak pull request #7151
Opened 2020-06-08 16:18 UTC by shahidhs-ibm

JIRA: [KEYCLOAK-14037](https://issues.redhat.com/browse/KEYCLOAK-14037)
Enable s390x builds in Keycloak Travis CI.

**Note:** Some tests are skipped for s390x as there is some known issue with phantomjs which causes these tests fail.

2020-06-09 06:36 UTC, stianst requested changes
We don't have any plans to add s390x or multi-arch support to our container images and would need to see more interest in this from the community to maintain this.

2020-06-09 07:41 UTC, stianst commented
I'm closing this for now as we don't use Travis for matrix jobs like testing different VMs, we have internal CI for that. We also need to have a discussion if and how we add support for s390x so please open a thread on the dev mailing list around this.

2020-06-09 07:41 UTC, closed without merging

2020-06-16 14:50 UTC, Siddhesh-Ghadi commented
^^ @gerrith3

2020-06-17 07:19 UTC, shahidhs-ibm commented
Discussion thread is [here](https://groups.google.com/forum/#!topic/keycloak-dev/sy9Tkihth5w).