KEYCLOAK-6304: Czech translation
keycloak/keycloak pull request #7198
Opened 2020-06-22 22:20 UTC by jakubknejzlik

Add czech translations based on previous PR:
https://github.com/keycloak/keycloak/pull/4925

2020-06-23 17:49 UTC, hmlnarik requested changes
Thank you, looks pretty good to me! Few minor comments and is good to go from my perspective
@vramik @mposolda Would you like to double check?

2020-06-23 17:49 UTC, hmlnarik commented on themes/src/main/resources-community/theme/base/email/messages/messages_cs.properties
> +linkExpirationFormatter.timePeriodUnit.minutes=minuty
```suggestion
linkExpirationFormatter.timePeriodUnit.minutes=minut
```

2020-06-23 17:49 UTC, hmlnarik commented on themes/src/main/resources-community/theme/base/email/messages/messages_cs.properties
> +linkExpirationFormatter.timePeriodUnit.seconds=sekundy
```suggestion
linkExpirationFormatter.timePeriodUnit.seconds=sekund
```
and alternatives for 2, 3, and 4 (similarly to what you have for _minutes_ below)

2020-06-23 17:49 UTC, hmlnarik commented on themes/src/main/resources-community/theme/base/email/messages/messages_cs.properties
> +linkExpirationFormatter.timePeriodUnit.hours=hodiny
```suggestion
linkExpirationFormatter.timePeriodUnit.hours=hodin
```
and alternatives for 2, 3, and 4 (similarly to what you have for _minutes_ above)

2020-06-23 17:49 UTC, hmlnarik commented on themes/src/main/resources-community/theme/base/email/messages/messages_cs.properties
> +linkExpirationFormatter.timePeriodUnit.days=dny
```suggestion
linkExpirationFormatter.timePeriodUnit.days=dní
```
and alternatives for 2, 3, and 4 (similarly to what you have for _minutes_ above)

2020-06-23 18:32 UTC, jakubknejzlik commented
@hmlnarik Thanks for such quick reply. I've updated the email translations according to Your suggestions

2020-06-24 06:48 UTC, vramik reviewed
Thank you @jakubknejzlik for the PR. It seems good to me, I've found just one small thing, otherwise it's good to go in.

2020-06-24 06:48 UTC, vramik commented on themes/src/main/resources-community/theme/base/account/messages/messages_cs.properties
> +accountLogHtmlTitle=Účet účtu
```suggestion
accountLogHtmlTitle=Log účtu
```

2020-06-24 07:33 UTC, jakubknejzlik commented on themes/src/main/resources-community/theme/base/account/messages/messages_cs.properties
> +accountLogHtmlTitle=Účet účtu
Oh, good catch 👍 ...fixed

2020-06-24 11:25 UTC, vramik approved these changes
@jakubknejzlik thanks

2020-06-24 20:13 UTC, vramik requested changes

2020-06-24 20:13 UTC, vramik commented on themes/src/main/resources-community/theme/base/account/messages/messages_cs.properties
> +accountLogHtmlTitle=Lod účtu
I'm sorry, but there is a typo. 
```suggestion
accountLogHtmlTitle=Log účtu
```

2020-06-25 05:35 UTC, jakubknejzlik commented on themes/src/main/resources-community/theme/base/account/messages/messages_cs.properties
> +accountLogHtmlTitle=Lod účtu
Oh, sorry for that :-/ ... fixed.

2020-06-25 07:31 UTC, vramik approved these changes

2020-06-26 10:55 UTC, hmlnarik approved these changes
@jakubknejzlik Thank you!

2020-06-26 10:56 UTC, merged