KEYCLOAK-12326 when `WebAuthnCredentialModel` is set as a "password" …
keycloak/keycloak pull request #7204
Opened 2020-06-24 09:40 UTC by edewit

…removing the IdP should be allowed

new stab at KEYCLOAK-12326 with tests in favor of #7019

2020-08-03 19:35 UTC, ssilvert commented
@vmuzikar Can you review this when you get a chance?

2020-08-04 06:10 UTC, vmuzikar commented
@ssilvert Sure, I'll try to check it by the end of this week if that's ok.

2020-08-06 13:37 UTC, vmuzikar requested changes
Changes look good, thank you @edewit. The only thing I'm missing is a test for one more scenario, please see below.

BTW, I've created a related issue: https://issues.redhat.com/browse/KEYCLOAK-15067

2020-08-06 13:37 UTC, vmuzikar commented on testsuite/integration-arquillian/tests/other/base-ui/src/test/java/org/keycloak/testsuite/ui/account2/LinkedAccountsTest.java
> +        signingInPage.navigateTo();
Should we also test that unlinking the only IdP is not possible when there's no password or webauthn passwordless set?

2020-08-06 13:37 UTC, vmuzikar commented on testsuite/integration-arquillian/tests/other/base-ui/src/test/java/org/keycloak/testsuite/ui/account2/LinkedAccountsTest.java
> +        waitForPageToLoad();
I believe this could've been done just by using admin REST endpoints (UI is tested in another test) but that's ok since you already have this.

2020-09-15 21:16 UTC, ssilvert commented
Out of date.

2020-09-15 21:16 UTC, closed without merging