[KEYCLOAK-14344] Cannot revoke offline access for an app if the app d…
keycloak/keycloak pull request #7206
Opened 2020-06-24 21:44 UTC by douglaspalmer

…oesn't require consent

2020-06-25 07:03 UTC, vmuzikar requested changes
It seems like UI tests are failing.
Could you please also add some simple new UI test for this?

2020-06-25 20:50 UTC, ssilvert commented
UI tests are passing now.  Build number 936.

@vmuzikar Do you approve to merge?

2020-06-26 06:55 UTC, vmuzikar requested changes

2020-06-26 06:55 UTC, vmuzikar commented on testsuite/integration-arquillian/tests/other/base-ui/src/test/java/org/keycloak/testsuite/ui/account2/ApplicationsTest.java
> +        assertClientRep(apps.get("account-console"), "Account Console", false, true, "https://localhost:8543/auth/realms/test/account/", false);
Please don't use hardcoded localhost. If we would need to run the tests e.g. with a different host (and we do need that now in some cases to properly test cookies) or without SSL, this won't work.

Something like:
```suggestion
        assertClientRep(apps.get("account-console"), "Account Console", false, true, getAuthServerRoot() + "/realms/test/account/", false);
```

This concerns other lines as well.

2020-06-26 15:56 UTC, vmuzikar submitted a review, later dismissed
@douglaspalmer Thanks for the update. If the tests pass, we can merge.

2020-06-26 16:43 UTC, ssilvert commented
Kicked off UI tests.  Build number 939.

2020-06-26 17:48 UTC, ssilvert commented
Doug kicked off UI tests. Build number 940.

2020-06-26 18:40 UTC, ssilvert commented
Build 940 looks good.  ApplicationsTests now passing.

2020-06-26 18:40 UTC, ssilvert approved these changes

2020-06-26 18:56 UTC, merged