KEYCLOAK-14602 Remove extra navigation in test
keycloak/keycloak pull request #7226
Opened 2020-07-02 14:31 UTC by Aboullos

Looks like Selenium is inserting some kind of refresh on the method "getCurrentUrl()" and "executeWithJavaScript()" that is making the test to fail when waiting between the navigation. And like the test is just expected to check the timeout the functionality of the test is still the same.

2020-07-02 14:42 UTC, edewit approved these changes
:+1:

2020-07-02 17:26 UTC, ssilvert commented
Kicked off UI tests build number 948

2020-07-03 11:29 UTC, vmuzikar requested changes
I'm afraid this is not a correct fix, it just works around the problem by accident. Why would navigation caused a redirect to login page?

I did some investigation and this happens when the JS adapter tries to refresh the access token. Just try to increase the token lifespan (e.g. to 20) here:
https://github.com/keycloak/keycloak/blob/34faba1a9a6861e7af9632953f5d66a0da7a3f29/testsuite/integration-arquillian/tests/other/base-ui/src/test/java/org/keycloak/testsuite/ui/account2/SessionTest.java#L55
and the test will pass. That's because the token is valid longer and the adapter doesn't need to refresh it.

Your fix worked because it sped up the test so no refresh was necessary.

Please investigate it a bit more and be careful, it might be a bug.

2020-07-03 12:01 UTC, Aboullos commented
But changing it to 20 it is still posible that it fails in a slow machine or internet, being there 2 navigation gives mores possibilities that when the second one occurs the time has run out.

Just changing the time make it possible to fail again in the future if the machines are slow or if the load time increases, like this test hasn't changed but it started failing now. But like the token refresh occurs in the first request it should be ready with just the first navigation.

If the solution is changing the time can it be increased more than just to 20?

2020-07-03 12:52 UTC, vmuzikar commented
@Aboullos We've been looking into that with @edewit and found it is actually a bug caused by https://github.com/keycloak/keycloak/pull/7163. I believe we can close this, correct @edewit?

2020-07-03 12:55 UTC, Aboullos commented
But this branch is 1 commit ahead of that PR

2020-07-03 13:00 UTC, vmuzikar commented
@Aboullos I can see the [commit](https://github.com/Aboullos/keycloak/commit/f37fa31639dc188270876c6027e3c1e0e1ac4d26) in [your branch](https://github.com/Aboullos/keycloak/commits/KEYCLOAK-14602) this PR is based on.

2020-07-03 13:01 UTC, Aboullos commented
Oh okay, I read wrong, I thought you meant that commit fixed the error

2020-07-03 13:26 UTC, edewit commented
@vmuzikar yes we can close this one in favor of https://github.com/keycloak/keycloak/pull/7230 sorry @Aboullos I screwed up

2020-07-03 13:34 UTC, closed without merging