KEYCLOAK-14653 Changed operation type to UPDATE when updating client scopes
keycloak/keycloak pull request #7233
Opened 2020-07-06 08:15 UTC by eedzjee

Changed operation type to UPDATE when updating client scopes and added representation in the admin event.

Fix for issue: https://issues.redhat.com/browse/KEYCLOAK-14653

2020-11-18 16:43 UTC, abstractj commented
@eedzjee would you like to move forward with this change? If yes, please iterate over the comments on https://issues.redhat.com/browse/KEYCLOAK-14653 and reopen the issue if you disagree.

2020-11-19 07:15 UTC, eedzjee commented
@abstractj yes, I still think this update is needed. I added a comment in the ticket as I am able to reproduce it and the code speaks for itself.
If you want to monitor on when clients are created or deleted, the current events are misleading.

2021-01-11 21:29 UTC, hmlnarik requested changes
Thank you for the PR. I agree that the current behaviour is wrong. The fix should be rather logging that the client scope link to a particular client has been created / deleted, so it is needed to introduce a proper `ResourceType` that would be logged together with a proper `CREATE` / `DELETE` operation. Please see inline for suggestions. When pushing the updated version, please rebase to the current master

2021-01-11 21:29 UTC, hmlnarik commented on services/src/main/java/org/keycloak/services/resources/admin/ClientResource.java
> +        adminEvent.operation(OperationType.UPDATE).resource(ResourceType.CLIENT).resourcePath(session.getContext().getUri()).representation(rep).success();
```suggestion
                adminEvent.operation(OperationType.CREATE).resource(ResourceType.CLIENT_SCOPE_CLIENT_MAPPING).resourcePath(session.getContext().getUri()).success();
```

2021-01-11 21:29 UTC, hmlnarik commented on services/src/main/java/org/keycloak/services/resources/admin/ClientResource.java
> +        adminEvent.operation(OperationType.UPDATE).resource(ResourceType.CLIENT).resourcePath(session.getContext().getUri()).representation(rep).success();
```suggestion
        adminEvent.operation(OperationType.DELETE).resource(ResourceType.CLIENT_SCOPE_CLIENT_MAPPING).resourcePath(session.getContext().getUri()).success();	```

2021-01-13 15:23 UTC, hmlnarik approved these changes
Thank you for the PR!

2021-01-13 15:23 UTC, merged