KEYCLOAK-14811 KEYCLOAK-14812 RoleProvider, RoleStorageManager
keycloak/keycloak pull request #7305
Opened 2020-07-30 12:44 UTC by vramik

2020-07-30 13:51 UTC, mhajas requested changes
Thanks for the PR @vramik. I tried to update `RealmProvider` so that it doesn't contain any `RoleProvider` methods (just to test if we completely avoid RealmProvider class when working with Roles). There were to places with the usage of deprecated methods that are no longer present in RoleProvider, we should replace them with the corresponding `RoleProvider` method. See following commit: https://github.com/mhajas/keycloak/commit/2e06cc5c2d48af66e4420de901870f567a20c530

There are also some compilation errors in RoleStorageManager, see comments in code.


Otherwise, it looks good, I will do some more testing, but we should have those^ fixed asap so that we can see results from Travis.

2020-07-30 13:51 UTC, mhajas commented on services/src/main/java/org/keycloak/storage/RoleStorageManager.java
> +    @Override
This method doesn't exist in RoleProvider interface.

2020-07-30 13:51 UTC, mhajas commented on services/src/main/java/org/keycloak/storage/RoleStorageManager.java
> +        return session.roleLocalStorage().removeRole(realm, role);
We should use `removeRole(role)`.

2020-07-30 13:51 UTC, mhajas commented on services/src/main/java/org/keycloak/storage/RoleStorageManager.java
> +public class RoleStorageManager implements RoleProvider {
This class doesn't implement methods `removeRoles(realm/client)`.

2020-07-30 17:53 UTC, vramik commented
> I tried to update `RealmProvider` so that it doesn't contain any `RoleProvider` methods (just to test if we completely avoid RealmProvider class when working with Roles). There were to places with the usage of deprecated methods that are no longer present in RoleProvider, we should replace them with the corresponding `RoleProvider` method. See following commit: [mhajas@2e06cc5](https://github.com/mhajas/keycloak/commit/2e06cc5c2d48af66e4420de901870f567a20c530)

Thanks for that, I should have tried it myself, will fix this.

2020-07-31 08:52 UTC, mhajas submitted a review, later dismissed
LGTM! Thanks, @vramik!

2020-07-31 11:30 UTC, vramik commented
@mposolda @pedroigor would you like to review this PR?

2020-07-31 12:43 UTC, pedroigor submitted a review, later dismissed
@vramik The new tests are failing for Quarkus (the others are expected). Not a blocker for merging, but I appreciate a fix for them.

2020-07-31 12:44 UTC, martin-kanis submitted a review, later dismissed
@vramik It looks good to me. Thanks!

2020-07-31 13:29 UTC, sguilhen requested changes
LGTM, thanks @vramik

2020-07-31 15:15 UTC, vramik commented
The test failures on Quarkus are caused by the fact that `DefaultKeycloakSessionFactory.init()` in not called on quarkus. We discussed it with @pedroigor and agreed that we should move the resolving of the default value to the get methods.

2020-07-31 15:23 UTC, pedroigor commented
@vmuzikar This type of confusion was expected as we decided to replicate some code from main dist to Quarkus to not mess with the main dist. We should keep an eye on the changes to some classes and avoid more duplications. And fix that in the future so that we have more hooks to customize behavior depending on the stack we're running.

2020-07-31 15:36 UTC, martin-kanis approved these changes

2020-07-31 15:50 UTC, vmuzikar commented
@pedroigor Did you mean @vramik? :)

2020-07-31 17:19 UTC, sguilhen approved these changes

2020-07-31 18:11 UTC, pedroigor approved these changes

2020-07-31 18:11 UTC, merged