KEYCLOAK-15221 Add sid claim to ID Token and fix backchannel logout Content-Type
keycloak/keycloak pull request #7357
Opened 2020-08-19 15:34 UTC by benjamin37

Like noted in the dev mailing list by Mateusz Małek <mmalek@agh.edu.pl> there are 2 issues with the backchannel logout implementation:

* The ID Token in Keycloak doesn't contain a `sid` claim
* The Content-Type of the Back-Channel logout POST request is `application/x-www-form-urlencoded; charset=UTF-8` instead of `application/x-www-form-urlencoded`

2021-03-01 13:59 UTC, EmilIfrim commented
Any plans on merging this?

2021-06-30 14:39 UTC, benjamin37 commented
Hi @abstractj,

it has been a while since I opened this PR. Do you have any feedback?

Kind regards
Benjamin

2021-07-06 14:03 UTC, pedroigor requested changes
@benjamin37 Thanks.

We should avoid some redundancy when setting the session id by just leveraging the `sessionState`.

For instance:

```
@JsonProperty(SESSION_STATE)
@JsonAlias("sid")
protected String sessionState;

@JsonProperty("sid")
    public String getSessionId() {
        return sessionState;
    }
```

Then remove any change to `setSessionId`.

2021-07-06 16:27 UTC, benjamin37 commented
Hi @pedroigor,

thanks for your feedback. That's a good idea, like this it's not possible to set different values for `sid` and `session_state`. I updated the PR and extended an existing test in AccessTokenTest to also check for the `sid` claim in the `IDToken` or should I rather add a new test method?

Kind regards
Benjamin

2021-07-06 18:29 UTC, pedroigor approved these changes

2021-07-06 18:30 UTC, merged