[KEYCLOAK-14432] Unhandled NPE in identity broker auth response
keycloak/keycloak pull request #7358
Opened 2020-08-19 15:46 UTC by mabartos

JIRA: [KEYCLOAK-14432 Unhandled NullPointerException if state is missing in Auth. Response (Identity Brokerage)](https://issues.redhat.com/browse/KEYCLOAK-14432)

By OAuth2 and OIDC spec, the state parameter in auth response is required only when it's included in auth request to identity provider too. But Keycloak always send state parameter in request to identity provider. So, if there's no state parameter in response, it's bug on the 3rd party OAuth2/OIDC provider side, as @mposolda said in the JIRA issue. It follows that the parameter is required for the type of identity providers. So, purpose of this PR is properly handle error, when it happens.

I think, it's not necessary to provide test case for that. AFAIK, It'd be difficult to simulate identity provider, which would provide response without the state parameter.

2020-08-19 18:56 UTC, mposolda requested changes
@mabartos Thanks for the fix! LGTM but some test may be nice as well.

IMO the test can be done by manually opening URL like "localhost:8081/auth/realms/myrealm/broker/myidp/endpoint?code=foo" and check the page with correct error message is displayed?

2020-08-20 17:18 UTC, mabartos commented
@mposolda Thanks for your comment. There's a problem with provided 'code' parameter. The param is used in auth response sooner than the 'state' param. If the code is invalid, the proper message occurs. So, the 'code' param has to be valid and then the 'state' param is used. But, after more investigation, I think it'd be possible to create some use case. It won't be so difficult as I've thought. :)

2020-08-21 12:51 UTC, mposolda requested changes
@mabartos Thanks for the test! I've added 2 inline comments :)

2020-08-25 14:59 UTC, mabartos commented
The test case was moved to `KcOidcBrokerTest` and remade.

2020-08-31 12:14 UTC, mposolda approved these changes
@mabartos Thanks!

2020-08-31 12:14 UTC, merged