KEYCLOAK-15226: fix decoding issue for utf-8 encoded tokens
keycloak/keycloak pull request #7360
Opened 2020-08-20 13:40 UTC by Nowheresly

2020-08-21 10:51 UTC, andreclemente approved these changes

2020-08-21 10:52 UTC, andreclemente approved these changes

2020-08-21 10:57 UTC, andreclemente submitted a review, later dismissed

2020-08-22 13:42 UTC, kris2kris submitted a review, later dismissed

2020-08-26 16:13 UTC, hmlnarik commented
@vmuzikar @abstractj Could you please review this PR?

2020-09-02 11:17 UTC, vmuzikar requested changes
@Nowheresly Thank you for your contribution!

Could you please share an example name/characters that are causing issues with the old implementation? I tried it myself using characters you provided in the JIRA (`à ï ö`) and also some Czech characters like like `ř á` without success. The token was always correctly decoded by the JS adapters. I tried it with latest versions of Safari, FF, Chrome and even IE. Or maybe ideally, could you share your exported realm with me?
From this standpoint, I don't see any reason for this fix as I'm unable to reproduce the actual issue. But maybe I'm just doing something wrong. :)

I believe this deserves a simple test as well. Could you please add it to the [JavascriptAdapterTest](https://github.com/keycloak/keycloak/blob/master/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/javascript/JavascriptAdapterTest.java)? You can do this later once we've confirmed it's a real bug.

2020-09-10 19:51 UTC, kspar commented
@vmuzikar, we see this issue with a name containing ž and I was able to fix/reproduce by removing/adding that character.

2020-09-10 20:48 UTC, Nowheresly commented
Hi @vmuzikar 
thanks for taking the time to review my PR.

Unfortunately, I was not able to catch exactly which characters may cause this kind of error. I only had a acreenshot from a user showing the javascript error while decoding the token. After investigating the problem, I found that the current implementation:
`decodeURIComponent(escape(atob(str)))`
is deprecated and may fail on some browser `atob` implementation.

I was *not* able to reproduce the issue, yet I patched the keycloak-js lib to to use the recommended implementation:
```
decodeURIComponent(Array.prototype.map.call(atob(str), function(c) {
 return '%' + ('00' + c.charCodeAt(0).toString(16)).slice(-2)
 }).join(''))

```
and our user confirmed later that the issue was fixed.
It seems @kspar  found a way to reproduce the bug. I will try to reproduce it as well.

And, yes, it deserves a test: I'll adjust my PR to include it.

2020-09-22 10:50 UTC, vmuzikar reviewed
@kspar @Nowheresly Thank you for your reply! I'm afraid I'm still not able to reproduce it. I tried more national characters incl. `ž` and even some emojis. :) Ideally, I'd like to have a test with a reproducer as part of this PR. But since we don't have that reproducer, we have nothing to test.

I'll leave it up to other reviewers whether we should merge this or not. I'd say there's no harm in it and at the very least, we won't use the deprecated `escape` function anymore.

2020-11-18 12:59 UTC, abstractj requested changes
@Nowheresly  thank you for submitting these changes. Unfortunately, we could not reproduce the steps you mention, plus we need tests to make sure that the issue won't happen again.

Could you please provide more information on this?

@kspar @andreclemente if you would like to help by providing the steps to reproduce, you're more than welcome.

@vmuzikar unless there are reproducible steps for this issue and tests, I don't see any reason for moving forward.

2021-03-10 14:02 UTC, fdussert commented
Hi,
if it could help

`let decodeToken = function(str) {
            str = str.split('.')[1];

            str = str.replace('/-/g', '+');
            str = str.replace('/_/g', '/');
            switch (str.length % 4) {
                case 0:
                    break;
                case 2:
                    str += '==';
                    break;
                case 3:
                    str += '=';
                    break;
                default:
                    throw 'Invalid token';
            }

            str = decodeURIComponent(escape(atob(str)));

            str = JSON.parse(str);
            return str;
        }

let decodeToken2 = function(str) {
            str = str.split('.')[1];

            str = str.replace(/-/g, '+').replace(/_/g, '/');
            switch (str.length % 4) {
                case 0:
                    break;
                case 2:
                    str += '==';
                    break;
                case 3:
                    str += '=';
                    break;
                default:
                    throw 'Invalid token';
            }

            str = decodeURIComponent(atob(str).split('').map(function(c) {
                return '%' + ('00' + c.charCodeAt(0).toString(16)).slice(-2);
            }).join(''));


            str = JSON.parse(str);
            return str;
        }


let token = 'fakePart.eyJleHAiOjE2MTUzMDM1MTgsImlhdCI6MTYxNTMwMzIxOCwiYXV0aF90aW1lIjowLCJqdGkiOiI1ZGZlN2I0MC1kZDgyLTRiOGYtYjZkZC1hMWNjZTkwYTE2NzAiLCJpc3MiOiJodHRwczovL2F1dGgucmVuZGVtZW50bG9jYXRpZi5jb20vYXV0aC9yZWFsbXMvcmVuZGVtZW50LWxvY2F0aWYiLCJhdWQiOiJyZWZvbnRlLWFwcCIsInN1YiI6ImY6YTEzNDIxNTktYzE1MS00ZjBhLWEyZDctNDlmZWJiZmYzODA5OjIzMzciLCJ0eXAiOiJJRCIsImF6cCI6InJlZm9udGUtYXBwIiwibm9uY2UiOiJiMzEwMDAxNy01ZmIyLTRkNzEtODdlMC1lODc2MzVkZDEwYWIiLCJzZXNzaW9uX3N0YXRlIjoiMmFjYTQyMGItYzEzOS00ZWNjLWI2OTMtMGVmMDg5NzFlZGViIiwiYXRfaGFzaCI6IndjMlotWWxpaHRBYlZTRUg4djl6WUEiLCJhY3IiOiIwIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJybF9wcm9maWxlIjp7Imxhc3ROYW1lIjoiUk9USCIsImZpcnN0TmFtZSI6IkJlbm_DrnQiLCJwaG9uZSI6IiszMzY4MTQwNTIwMSIsInByb2ZpbGVzIjp7IkxPQyI6ImZhbHNlIiwiQ0FOIjoiZmFsc2UiLCJQSU4iOiJ0cnVlIiwiR0NVIjoiZmFsc2UiLCJHQVIiOiJmYWxzZSIsIlBSUCI6ImZhbHNlIn0sInJlbnRhbENob2ljZSI6InJlZm9udGUiLCJyZWdpc3RlcmVkIjoxMzkzMDg3MjE5LCJpZCI6MjMzNywicGxhbiI6InBybyIsImVtYWlsIjoiYmVub2l0LnJvdGhAZXF1aWxhYi5mciIsInVzZXJuYW1lIjoiQk9SRyJ9LCJuYW1lIjoiQmVub8OudCBST1RIIiwicHJlZmVycmVkX3VzZXJuYW1lIjoiQk9SRyIsImdpdmVuX25hbWUiOiJCZW5vw650IiwiZmFtaWx5X25hbWUiOiJST1RIIiwiZW1haWwiOiJiZW5vaXQucm90aEBlcXVpbGFiLmZyIn0';`

![KEYCLOAK-15226__fix_decoding_issue_for_utf-8_encoded_tokens_by_Nowheresly_·_Pull_Request__7360_·_keycloak_keycloak](https://user-images.githubusercontent.com/419201/110640860-9d1c3c80-81b1-11eb-95b8-6a4426e15bb0.png)

2021-05-15 05:59 UTC, RoopanV commented
Hi all, do we get the changes recommended by @fdussert  in keycloak-js

2021-07-15 07:27 UTC, hmlnarik commented
Thank you for the PR. There has been no activity on this PR for considerable amount of time, and thus is being closed. Feel free to reopen the PR if you still feel it is valid.
@fdussert @RoopanV Feel free to submit a separate PR for this fix.

2021-07-15 07:27 UTC, closed without merging