KEYCLOAK-14055 Add SASL EXTERNAL authentication for LDAP federation
keycloak/keycloak pull request #7365
Opened 2020-08-24 07:12 UTC by tsaarni

- gui: adds option for SASL EXTERNAL bind type
- truststore spi: make it possible to use keyStore (for LDAP client) even while using TrustStore SPI 
- tests: added support for SASL EXTERNAL authentication to LDAPEmbeddedServer
- tests: added support for LDAP admin to authenticate with X509 cert towards LDAPEmbeddedServer

2020-08-24 07:22 UTC, tsaarni commented
Summary of GUI changes:
* added menu entry SASL EXTERNAL
* moved "Test authentication" button on bind type line, so that authentication can be tested in all bind types but "none" (grayed out while "none" is selected)
* mentioned SASL EXTERNAL in the tooltip

Here is a preview as gif animation: 

![keycloak-sasl-external-gui](https://user-images.githubusercontent.com/85464/91014675-7e2dd280-e5f2-11ea-9c2b-452577be20e1.gif)


Notes about test suite changes:

I needed to include two modified files from Apache DS in order to support X509 authentication for LDAP admin in LDAPEmbeddedServer.  I discussed about the lack of this capability in the ApacheDS dev email list [here](http://mail-archives.apache.org/mod_mbox/directory-dev/202008.mbox/browser) (subjectUsing client certificate authentication for LDAP admin). I proposed the change to upstream ApacheDS, but I need to ping the developers again.
The files that were copied & modified from ApacheDS are:
* util/embedded-ldap/src/main/java/org/keycloak/util/ldap/CertificateMechanismHandler.java
* util/embedded-ldap/src/main/java/org/keycloak/util/ldap/ExternalSaslServer.java

2020-09-08 12:46 UTC, mposolda requested changes
@tsaarni Thanks a lot for the PR! Nice work!

I've replied to your email to keycloak-dev with the proposal of introduce Keystore SPI. So we can eventually continue discuss there.

Besides that, the PR may need also documentation and maybe some very minor changes, but maybe we can wait with that until there is more feedback for the keycloak-dev email?

2020-10-06 14:07 UTC, tsaarni commented
Link to keycloak-dev https://groups.google.com/g/keycloak-dev/c/QwKjr2I8Eyg/m/qMAAZ0-1BAAJ

2020-10-12 12:04 UTC, mposolda commented
@tsaarni Thanks for sending "ping" mail to the keycloak-dev . I was wondering about doing this, but you were faster. We will see if there is some more feedback...

2021-10-01 06:42 UTC, mposolda commented
@tsaarni Sorry for the delay with this PR :/ Do we want still to proceed with this PR or is it out of date from your point of view?

2021-10-01 08:07 UTC, tsaarni commented
Hi @mposolda!  Yes the feature is still valid from my point of view. 

SASL EXTERNAL can be used with LDAP today, by using small tricks https://github.com/tsaarni/cloud-playground/tree/master/kubernetes/keycloak, but it would be still interesting to me to have it officially.

Previously this was blocked due to architectural issues. But I wonder, are you asking now because you are cleaning up old PRs or do you think it would be now possible to get guidance to develop this feature?

2021-10-14 17:51 UTC, mposolda commented
@tsaarni I think it will be nice to have it in since you already did the work.

There is no other response on keycloak-dev, so my vote would be to do it in a way I originally proposed. So just introducing "Keystore SPI" and use it in JSSETruststoreConfigurator instead of directly using system properties in this configurator.

From my point of view, it is fine if we do separate Keystore SPI (no attempt to use the same certificates used by "https"). We can adjust later if needed. I hope most of the testsuite work, which you did for this PR, will work fine with this approach and will be possible to re-use? WDYT?

2021-11-16 14:10 UTC, mposolda commented
@tsaarni Hi, Any update for this PR?

2021-11-16 14:13 UTC, tsaarni commented
@mposolda Sorry, I have not had time yet to start with a proposal for the new Keystore SPI.

2022-01-17 09:16 UTC, tsaarni commented
@mposolda I would like to pick this up now and I started to look at adding Keystore SPI. I found some design decision challenges where I would like to ask for some guidance:

**1 Dependency between TruststoreSPI and KeystoreSPI**

During initialization of TruststoreSPI in `FileTruststoreProviderFactory::init()` it will immediately instantiate `JSSETruststoreConfigurator` and `SSLSocketFactory`. The keystore would be needed already at that point. However, it seems bit awkward to me to have dependency to another SPI inside init of one SPI. For example, it would become critical to have initialization order set correctly: KeystoreSPI should be initialized first and reference of KeystoreSPI factory would somehow need to relayed to `FileTruststoreProviderFactory::init()` which does not have access to provider factories currently, as far as I can see.  

Is there other examples of such "chicken-egg" situation of SPIs in the code base, that I could use as examples? Or should they rather be avoided?


**2 Rotating certificates without restarting Keycloak**

It is very important for me to have the ability to rotate / hot-reload client certificates without restarting Keycloak. I think I've found enough background information how to do it ([link](https://tersesystems.com/blog/2018/09/08/keymanagers-and-keystores/)): I believe I need to wrap `X509ExtendedKeyManager` which would mean that the new `KeystoreSPI` would actually need to have method to get `KeyManager` instead of just plain `KeyStore`

```java
public interface KeyStoreProvider extends Provider {
    KeyManager[] getKeyManagers();
}
```

So maybe it is rather KeyManagerSPI that I'd need to introduce, though still it would of course take keystore path and password as parameters.

**3 Organization of the SPIs**

If I add the interface in (2) above, it means that we have bit "asymmetric" functionality in SPIs: _truststore_ vs _keymanager_.
Though, when looking at the implementation of TruststoreSPI, to me it actually looks like it is already more than truststore: it is a socket factory as well. In theory, we could even create new SocketFactorySPI, combining functionality of both truststore and keystore handling into one. Possibly then we would not have that awkward inter-SPI dependency (1).

I browsed through the code base and I can find following uses for truststore SPI related functionality (use cases are: using truststore as _socket factory_, using it to get _trusted CA certificates_ or getting peer certificate _validation policy_)

| User | Socket factory |  CA certificates | Validation policy |
|---|---|---|---|
| `LDAPContextManager` | X | | |
| `LDAPOperationManager`  | X | | |
| `CertificateValidator` |  | X | | 
| `WebAuthnRegisterFactory` |  | X | | 
| `DefaultHttpClientFactory` |  | X | X | 
| `NginxProxySslClientCertificateLookup`|  | X | | 
| `CRLUtils` |  | X | | 

Curiously, there is one _socket factory_ use case that also introduces SPI->SPI dependency: `DefaultEmailSenderProvider`. But in this case it bypasses the initialization order problem by directly referencing `JSSETruststoreConfigurator` without going through truststore SPI to instantiate the socket factory, unlike the other cases.

**4 How to differentiate trust/keystores between use cases**

Currently in TruststoreSPI it seems that there is just one truststore that user can configure and it is applied to all use cases.

When it comes to KeystoreSPI, would the user need to be able to set specific keystore for specific use?  For example, LDAP client could need one keystore, and in theory Email Sender another? Or maybe we should avoid configuring any keystore for email SSL socket, which also would require ability to distinguish who is the caller?

2022-01-18 13:07 UTC, tsaarni commented
@mposolda I've added a commit that adds very initial draft of the new Keystore SPI for commenting and getting some guidance to the above topics.

It is used only by Truststore SPI.  I do not particularly like the interdependency of the two SPIs but is this something that could become accepted? 

Obviously user must set `useTruststoreSpi` to `true` in LDAP federation settings. I assume the name cannot change due to backwards compatibility, but maybe the UI label can be changed to something like "User Truststore and Keystore SPIs" since they always go together, but I'm unsure about this?

I reorganized Truststore SPI so that it does not anymore create socket factory already during the SPI initialization. In this way, `init()` of both SPIs can be executed before creating the socket factory. 

As I mentioned above, I would need a SPI to create `KeyManager` instead of `KeyStore`. I still call it Keystore SPI since the user is still configuring keystore parameters like file path and password, but this is also something I'm unsure about.

Creating `KeyManager` allowed me to create `ReloadingKeyManager` wrapper that supports keystore hot reload. User can set time-to-live duration that triggers reload of cached keystore when the last use of the keystore was more than TTL ago.  This is a simple approach that does not require e.g. background thread monitoring the change of the keystore file, using inotify or by other means.

2022-01-24 19:23 UTC, tsaarni commented
@mposolda I have a remaining problem that I'd really appreciate some help:

The tests fail occasionally because keystore will not always get configured and therefore client cert is not sent to server.  The reason is the dependency from Truststore SPI to Keystore SPI.  KeyStore SPI would need to be initialized first, but it is not always - I've checked with debugger, it looks like service load order is not guaranteed to be the same as service order in `server-spi-private/src/main/resources/META-INF/services/org.keycloak.provider.Spi` file.  When Truststore SPI is initialized first, it will create socket factory without keystore.

I would have liked to move the socket factory instantiation to `TruststoreProvider.create()` to remove initialization order dependency, but it did not work https://github.com/keycloak/keycloak/pull/7365#issuecomment-1015395199.

2022-01-26 12:15 UTC, tsaarni commented
I removed the "SPI initialization race" by removing provider specific singleton (`TruststoreProviderSingleton` and corresponding one I had created for keystore SPI).  Now the providers now register themselves to `org.keycloak.truststore.SSLSocketFactory` which holds the instances. It was already a singleton before this change, so I'd guess this could be acceptable. I removed `JSSETruststoreConfigurator` as its use became unnecessary complication when SPI initialization order is not guaranteed.

I will now stop working with this PR and wait for feedback.

(Not sure about the model test failure and if it relates to the changes I did)

2022-07-27 11:46 UTC, trixpan commented
@mposolda this is a terrific PR.  We have the same need and our implementation ended up being intercepting LDAPS calls with a Java agent.

Would be great to support EXTERNAL straight out of the box.

2022-08-09 09:37 UTC, tsaarni commented
Hi @mposolda! 

I wonder if I'm right with my observation that maintainers might have too much work and it is difficult for you to arrange time for reviews and guiding the contributors? It's [not just problem with this PR](https://github.com/keycloak/keycloak/pulls/tsaarni). I understand the flood of PRs might be overwhelming.  

 I hate to be "pushy" here but is there _anything_ that could be done to make this still happen?  

This PR has now became critical for us because of migration to Quarkus (our workaround does not work anymore). I really would like to work on TLS improvements for Keycloak:

1) I have better proposal for `KeyStore SPI` based on JSSE KeyStore SPI - rewriting parts of what I have done so far during the two years that this PR has existed. **I will push it here within couple of days**. Since truststore basically is just a KeyStore used by Trust Manager, I'd be also interested to present an idea how to unify the two SPIs (KeyStore and TrustStore) as the next step, as well as adding support for PEM files as trust anchors.

2) Unrelated to this PR, I'd like to add certificate rotation for the HTTPS certifcate https://github.com/keycloak/keycloak/discussions/10654 which we lost at Quarkus migration.

I think these could be valuable for the project if there is any possibility of getting them merged.

2022-08-11 15:16 UTC, tsaarni commented
I've updated this PR, including its description and marking some old comments as outdated.  Some unit tests failed, I'll investigate.

2022-08-11 15:32 UTC, mposolda commented
@tsaarni I am very sorry for the lack of feedback on this PR. I appreciate your contribution, but as you pointed, bunch of other priority work is in progress and we have lack of sources for the PR reviews etc...

I really hope to have time to review your PR, but I am heading to PTO and will return on Monday August 22. Hope to have some more accurate review afterwards.

Thanks again!

2022-08-11 15:44 UTC, tsaarni commented
Thank you @mposolda and see you again when you'll be back!

2022-08-29 17:48 UTC, stianst commented
@mposolda now that you are back could you take a look at this one again? I'm trying to clean-up the backlog of PRs and this is one of the PRs that have been around the longest.

2022-08-30 14:49 UTC, tsaarni commented
@mposolda I've created a small "demo" that builds on top of this PR: 

I made a small additional change that uses the proposed KeyStore SPI as source also for HTTPS server certificate/key for Quarkus. The advantage is that server certificate can be replaced on disk and Keycloak will pick up the changes without restart (i.e. Keycloak gains certificate hot-reload capability). The demo depends on unreleased Quarkus version that provides customization hook for Vert.X web server. It has a drawbacks currently, for which I posted a question https://github.com/quarkusio/quarkus/issues/27481#issuecomment-1231714170.

The code for the demo is here https://github.com/Nordix/keycloak/commit/717f0d917c47841e5de056830a667f4f10066fb4.

2022-09-07 07:49 UTC, anuragensemble commented
@tsaarni Thank you for working on this. I was pointed to this PR by @trixpan from the issue : https://github.com/keycloak/keycloak/issues/13300.

We were looking for suggestions around  "hot-reload" of LDAP external TLS truststore.
Additionally I was looking for any runtime configuration possibilities of such certs while configuring ldaps; not requiring Keycloak server restarts.

Your inputs around the linked issue would be invaluable. Thank you once again.

2022-10-19 20:12 UTC, pedroigor commented
@tsaarni @mposolda I agree we can split the work. Are you planning to include in the first PR only the changes that introduce the new SPI?

I'm asking because it is probably the baseline to start two initial distinct/parallel tasks: SASL_EXTERNAL and HTTP/TLS.

2022-10-20 04:27 UTC, tsaarni commented
> @tsaarni @mposolda I agree we can split the work. Are you planning to include in the first PR only the changes that introduce the new SPI?
> 
> I'm asking because it is probably the baseline to start two initial distinct/parallel tasks: SASL_EXTERNAL and HTTP/TLS.

Yes, let's do it that way.

2022-10-21 04:42 UTC, mposolda commented
@tsaarni @pedroigor Thanks for this idea and +1 for split the work. I've started to review the PR some time ago, but did not yet finished due the other things. Just some initial feedback from me:
- Among other things, the PR introduces some util methods for working with keys and pems like `PemReader`, `PemCredentialFactory` etc. However Keycloak already has some similar utilities - see for example Keycloak classes `PemUtils`, `KeyUtils`, `CertificateUtils` etc. It will be good if you can either use the existing utils or add more stuff to them (if existing functionality cannot be used for some reason) instead of introducing new set of crypto utilities. It is important also because we're starting to add FIPS support and some crypto functions are implemented in the submodules of `crypto` module to make sure they work in both FIPS and non-FIPS environment.

- Regarding the parameter names, I think it will be nice if new `KeyStoreSPI` is aligned with already existing `TruststoreSPI` and use same names for configuration parameters like existing `FileTruststoreProvider` uses. For example `file`, `password`,`type` instead of `ldapKeystoreFile`, `ldapKeystorePassword`, `ldapKeystoreType`. However I understand that you added the `ldap...` into the name of parameters due the keyStoreIdentifier (namespace) argument. With regards to this, I propose to skip support for namespaces in this PR and just change the method signatures to ommit `keyStoreIdentifier` parameter. So changing provider methods to something like this:
```
    KeyStore loadKeyStore();
    KeyStore.Builder loadKeyStoreBuilder();
```

If we want to support namespaces, it is not sufficient anyway to use something like `ldap-client-keystore` in my opinion for all LDAP related usages of this SPI ,because you may have different LDAP servers in different realms and you may want to use different namespace for each of them. Hence I see the ability of adding namespace support to this SPI rather as a follow-up if really needed. And in this case, we will need to make sure that it can be properly handled (For example it would be possible to configure at LDAP provider level which namespace to use etc).

What do you think guys?

2022-10-21 05:53 UTC, tsaarni commented
@mposolda Thank you for your comments!

I have added motivation why namespacing would be nice to have. It is in the design proposal at https://github.com/keycloak/keycloak-community/pull/345. There I also commented on https://github.com/keycloak/keycloak-community/pull/345#issuecomment-1284969973 that instead of namespacing, we could move LDAP keystore config to be part of other LDAP config, so that connection parameters would not be split between startup time parameters, and realm parameters. I'd appreciate if you could take a look of that discussion, when you have time!

However, if you would still prefer that SPI supports single keystore, then I will do that.

Some reflections:
* I suppose changing the SPI later comes with some backwards incompatibilities, at least the "user interface" i.e. the SPI config would change considerably, so it would be nice to have somewhat firm decision that namespacing would not be added immediately after initial version.
* I would really like to add support for HTTPS server certificate hot-reload as well. That requires me to add support to one more key store [1]. *I think the HTTPS server key store cannot be the same as LDAP client key store*, but what do you think?

[1] HTTP server certificate hot-reload needs to be done via [custom KeyManager](https://www.github.com/quarkusio/quarkus/pull/27682) and I have not managed to convince Vert.x to add [transparent hot-reload support](https://www.github.com/eclipse-vertx/vert.x/pull/4372).

2022-10-21 19:19 UTC, pedroigor commented
@tsaarni I'm really interested in enabling hot-reload to the distribution for HTTPS. It should be possible to do it without relying on the key store, right?

I know not ideal from your perspective, but it would help us to improve this area as well as check most of the code you are planning to contribute.

2022-10-21 19:40 UTC, tsaarni commented
@pedroigor,

> It should be possible to do it without relying on the key store, right?

I'm not sure if I understood what you mean. But since the JDK TLS implementation requires a `KeyManager` which basically requires a `KeyStore` I do not see way around it, unless one is rewriting the KeyManager logic.  I've studied a bit about different approaches in implementing hot-reload and wrote some [notes here](https://github.com/tsaarni/reloading-keystore/blob/main/docs/implementation-description.md) regarding my findings and reasoning for implementation decisions.

I also studied Vert.x which internally loads keys to in-memory `KeyStore` directly from PEM files, which is of course possible and I'd like to support the same, but it does not remove the need for `KeyStore`. My first idea was to try implement hot-reload support in Vert.x, but I failed proceeding on that front and anyway Vert.x already had a capability of taking in `KeyManager` from user, which is often used to implement hot-reload from application side. That I also got working with small Quarkus modification that was merged.

2022-10-21 20:22 UTC, tsaarni commented
I wanted to highlight that I'm not locked to any specific implementation. I've worked with this for a little while and I have some ideas how things could work, but I'd appreciate any input and direction from you. It would be great to have these two use cases (LDAP client cert auth with SASL EXTERNAL and hot-reload for both HTTPS and LDAP) supported by Keycloak :)  I'm also open for a zoom call or something if you have those.

2022-10-24 19:16 UTC, pedroigor commented
@tsaarni Sorry, I meant "without relying on the key store SPI" so that we could leverage your code to enable hot-reload without necessarily discussing the SPI.

2022-10-25 05:29 UTC, tsaarni commented
@pedroigor Yes that is true! We would still need a `KeyStore` but that can of course be instantiated by other means than via KeyStore SPI. While working on this PR, and while experimenting with HTTPS server credential hot-reload, I started to think it may be advantageous to implement the logic (of hot-reloading keystore) only once.  I thought all use cases of `KeyStores` might benefit from default implementation that can hot-reload and also support PEM files besides key store files. That lead me to think about adding namespaces into the KeyStore SPI proposal.

2022-10-27 12:17 UTC, mposolda commented
@tsaarni One question: Do you need namespaces for your own use-cases? If not, I wonder about supporting them later if there is a requirement for them. For this PR, it only uses single namespace for LDAP, so based on that, I assume that you don't need them since it is in fact always the same namespace used when you call it. Is it correct?

Avoiding namespaces can be good as we won't need additional property in the LDAP configuration for the namespace (which is good as LDAP provider already has bunch of properties...:-)

Regarding namespaces, I don't see any issue with adding support for them later. Since Keystore SPI won't be public SPI, adding new methods to it like:
```
    KeyStore loadKeyStore(String namespace);
    KeyStore.Builder loadKeyStoreBuilder(String namespace);
```

is not a problem IMO. and I think it should be possible to do this in a backwards compatible way. For example when we add new property to LDAP provider like `keystore namespace`, it can be empty by default, which means that it will use "global" (default) namespace used when calling non-argument methods like `KeyStore loadKeyStore()` .

So how about milestones like this:
- Milestone 1: Adding Keystore SPI without namespaces
- Milestone 2: Adding support for Keystore SPI into LDAP provider (Note there is also LDAP in the new store, which may be added as a follow-up PR to the default LDAP provider)
- Milestone 3: Consider re-use some parts of the Keystore SPI for hot-reloading at quarkus/vert.x layer for HTTPS. We can possibly extract some parts of the implementation to some "util methods" (or to some common module), which can be consumed by both keystore SPI and by quarkus/vert.x.
- Milestone 4: Adding namespaces support (if there is requirement for that)

There can be other milestones (probably after milestone 2) for leveraging keystore SPI for other things, like for example realm keys (we already have `JavaKeystoreKeyProvider`, which allows this, but we can improve it to use `Keystore SPI` etc)

2022-10-27 13:43 UTC, tsaarni commented
Hi @mposolda!

> One question: Do you need namespaces for your own use-cases? If not, I wonder about supporting them later if there is a requirement for them. 

My use cases needs two key stores: one for implementing **(1)** LDAP SASL EXTERNAL client credentials and second for implementing **(2)** HTTPS server credential hot-reload.  

The question that I had then: how can I configure and instantiate two different key stores?  

Since we had already discussed about introducing KeyStore SPI in this PR previously with motivation of not mixing LDAP key store with the default JDK key store, this rang a bell for me: are we creating the same problem here? Wouldn't it make sense for KeyStore SPI to support many independently configured key stores as well, so that we do not end up with another "default JDK keystore" scenario.

That is the reason for the identifier in the call when fetching key stores.  We can have one global key store for use case (1), which could be identified by `"ldap-client"` and another global keystore identified by `"https-server"` which would be for use case (2).

> Regarding namespaces, I don't see any issue with adding support for them later. Since Keystore SPI won't be public SPI, adding new methods to it like:
> ...
> is not a problem IMO. and I think it should be possible to do this in a backwards compatible way. For example when we add new property to LDAP provider like keystore namespace, it can be empty by default, which means that it will use "global" (default) namespace used when calling non-argument methods like KeyStore loadKeyStore() .

But isn't the global default key store then actually just LDAP key store or who else would default to that?

BTW: The discussion has now unfortunately been split between the [design proposal PR](https://github.com/keycloak/keycloak-community/pull/345) and this PR. I wonder would it be appropriate to move the discussion there? :)

2023-05-14 16:30 UTC, JakubNovak3 commented
I personally will handle mutual auth TLS cert hot reloading by running keycloak in a 'custer' mode and replacing a container. Here is a hack that works for now: https://github.com/keycloak/keycloak/issues/11725#issuecomment-1546937011
But thanks a lot for doing the work properly.

2024-10-09 06:34 UTC, tsaarni commented
> Looks like an interesting feature, is it still in the works?

Not right now, unless we'd come up with an approach that works for Keycloak. I'm still very much interested in working with this feature.

2026-04-29 06:01 UTC, stianst commented
Closing this as it has been open a long time with unresolved decisions on how to resolve; the issue also has very few votes (single thumbs-up).

For anyone interested in this continue the discussion on https://github.com/keycloak/keycloak/issues/11725; or potentially a simpler path forward is https://github.com/keycloak/keycloak/issues/29654 assuming that mTLS is actually what folks are after.

2026-04-29 06:01 UTC, closed without merging

2026-04-29 08:31 UTC, tsaarni commented
> Closing this as it has been open a long time with unresolved decisions on how to resolve

We are interested in this feature, and I am happy to revive this PR and work toward an acceptable solution for the project.

> potentially a simpler path forward is #29654 assuming that mTLS is actually what folks are after.

I am not sure if a simpler path was suggested there? The suggestion I see is _"It would be helpful if Keycloak supported configuring both truststore and keystore for LDAP directly via the SPI (instead of relying on JVM arguments)"_ https://github.com/keycloak/keycloak/issues/29654#issuecomment-3269831928, which is exactly what this PR implemented.

Yes the goal is to use client certificates to authenticate towards the LDAP server. StartTLS with SASL EXTERNAL authentication is an IETF standard, whereas LDAPS was never standardized but would be needed as well.

Cc @pedroigor

2026-04-30 10:41 UTC, pedroigor commented
@stianst The PR is primarily targeting two key capabilities for LDAP:

1. An additional and more secure (connection) authentication method based on mTLS
2. Improve production-ready experience by avoiding downtimes when rotating keys

We all agree that mTLS is a key authentication method.

As for 2), even though there are workarounds (https://github.com/keycloak/keycloak/issues/29654) to enable mTLS, one is forced to restart deployments when rotating keys. By that, we not only impact availability but also make it harder to rotate keys when they are compromised, when they expire, or as a preventive step due to any security policy.

The 2) changes the scope of this PR and goes beyond LDAP because rotating keys is a cross-cutting concern that spans how we configure truststores and keystores in areas other than LDAP. We already allow rotating HTTP TLS keys, but AFAIK, we lack this mechanism when Keycloak is acting as a client, such as an HTTP and LDAP client.

That said, we should probably involve @keycloak/cloud-native-maintainers and @team-production-readiness to sort out 2 as we are going to have changes in the distribution (server config) as well as in the instructions/UX when deploying Keycloak in production.

@tsaarni is interested in moving forward with the contribution and from the LDAP-side of things, @keycloak/core-iam team can help. But we will also need to involve other teams.

Does it make sense to re-open it and move it forward?

2026-04-30 11:33 UTC, trixpan commented
Maybe look into quarkus’ [TLS registry](https://quarkus.io/guides/tls-registry-reference#:~:text=TLS%20Registry%20also%20provides%20automatic%20certificate%20reloading%20%2C%20integration%20with%20Let%E2%80%99s%20Encrypt%20(ACME)%20%2C%20support%20for%20Kubernetes%20Cert%2DManager%2C%20and%20compatibility%20with%20various%20keystore%20formats%2C%20such%20as%20PKCS12%2C%20PEM%2C%20and%20JKS)?

2026-05-08 10:44 UTC, tsaarni commented
Thanks @trixpan for the tip, following that suggestion I took a look and it really would provide the exact same functionality, and more.  I guess the problem is that there is no precedent for Quarkus TLS Registry use either, and it also introduces new API, so I'm not sure if there is way forward with that.

Regardless I created PoC #48832