KEYCLOAK-15252 Allow themes to get info about hidden IdPs
keycloak/keycloak pull request #7369
Opened 2020-08-24 21:01 UTC by lscorcia

Currently IdPs that have the `Hide on Login page` flag enabled are not exposed in the `social.providers` Freemarker data model. 
This makes impossible any kind of theme-based rendering or other processing (like showing them as grayed out, or using their `loginUrl` in javascript, or placing their UI in other pages than the login one, etc.).
This very simple pull request lets the `social.providers` item contain both hidden and visible IdPs and makes the theme take care of the hiding.

2020-09-01 06:14 UTC, stianst requested changes
This change doesn't make any sense. Why select hide on login page for an IdP, if you are going to display it on the login page?

2020-09-01 12:36 UTC, lscorcia commented
Hello @stianst, thanks for taking the time to review this contribution.

The starting point for this PR was a problem I had when designing customizations for my setup: how do I build custom UI events to login to providers that are enabled, but shouldn't be visible in the standard providers link list? Since the freemarker template is rendered on the server side, there is no technical reason why it couldn't get these informations from the providers model.

Now, I agree that most of the time, if you want the provider hidden it's because you don't ever want the user to discover it. Sometimes however you just need to render it in a different way from other providers, without having to hardcode the IdP aliases in the theme.

Let's provide an example. You can see my current theme at https://login.mise.gov.it/auth/realms/spid/account (not a production site yet, feel free to poke around). The big blue button is the law-mandated UI for the Italian IdP federation and if you click on it you will see a bunch of provider logos. We also have a mockup IdP for development (idptest.spid.gov.it), and an implementation validator (ValidatorSpidL2) that we have to publish for the federation coordinator to allow tests on their end before our SP is actually authorized to access the federation.

The deployed Keycloak instance contains this patch. All of the IdPs are configured as Hidden = True, except the two test-related ones. Even though they are marked as hidden, my theme is able to render them with the custom UI because it has access to their alias and login url. As soon as the test period ends, I can just flip the Hidden flag on the test ones and the UI will be immediately updated.

If this behavior is not interesting for the product I totally understand - I can always tweak the login template to obtain the same result. It's just that I want to keep theme changes to a minimum, and by delegating the interpretation of "what hiding means" to the theme I get a lot of additional flexibility.

2020-09-02 12:48 UTC, stianst commented
I appreciate your use-case and I would like to see something out of the box to support it, but this is not the correct approach. "Hide on login page" is just that - it's completely hidden on the login page, so this is very much just a workaround rather than a proper solution.

I have two ideas that we can visit if your are interested in taking this further:

* Support federations - Have built-in support to support federation of IdPs. In essence rather than creating a separate IdP for each external IdP, you'd create a federation, where the list of IdPs and their configuration would often be external URLs, and within KC you'd be able to configure a group in one go (including I presume mappers). I'd imagine on the first login page there would be a button to select a specific federation, that would then list IdPs within this federation (sometimes there's 100s, if not 1000s idps here though, so that's something to consider as well).
* Support some more UI based properties on IdPs.

2020-09-02 20:37 UTC, lscorcia commented
Hello @stianst, thanks for taking the time to consider this, I really appreciate it.

Yes, having federation support out of the box would be great for us. In fact, we are currently evaluating Keycloak because we are trying to move away from OpenAM, which supports this concept by defining one or more "Circle of Trust", which is pretty much a container of SAML IdPs that share a common set of assertions and configurations. Usually federations also expose one single SAML SP endpoint for the entire federation - this makes metadata sharing much easier. The UI improvement would also be nice, but considering that we have actual laws mandating the various widgets' appearances, I don't think we'll ever be able to avoid custom theming.
Anyway considering the amount of work required, implementing this feature would be a major effort and will involve a lot of product planning. For the time being I will close this PR and hardcode the aliases of the test IdPs in my theme.

Thanks again for your collaboration!

2020-09-02 20:37 UTC, closed without merging