KEYCLOAK-15287 Ability to add custom claims to the AccessTokenResponse
keycloak/keycloak pull request #7371
Opened 2020-08-26 17:18 UTC by ibacher

This adds the ability to add custom claims to the OIDC access token response when successful using a similar API to how ProtocolMappers add claims to tokens currently.

2020-08-31 17:59 UTC, ibacher commented
I have seen the test failure, but I can't reproduce it my environment and it seems to be unrelated to any changes introduced by this code.

2020-09-01 10:23 UTC, stianst commented
This has come up once or twice already. I'm not quite convinced that it should be possible to add custom claims to access token response. @mposolda @pedroigor wdyt?

2020-09-01 10:25 UTC, stianst commented
@ibacher can you provide a bit more details on the justification for adding this (assume we don't know details about SMART App Launch Framework, and don't have time to research it ;))?

2020-09-01 13:59 UTC, ibacher commented
@stianst I apologise that this is probably going to be a bit of a response. The TL;DR is that the SMART App Launch Framework is a standard that medical record systems are being required to implement and to implement that standard we need to be able to add claims to the initial access token response.

I completely agree that what this I am asking for is weird. The SMART framework unfortunately chose to design things this way. That said, the "claims" we are trying to pass are not actually security-related data but rather metadata provided from the authorization server to the client. So, we aren't driving any authorization decisions off of these claims. They are simply there to communicate contextual information to the client.

The way this works is something like this: a doctor has an application that implements the SMART framework that they'd like to connect to their electronic health record (EHR). They tell their client the URL of the EHR, which directs them to an authorization server to actually authorize them. As part of this flow, the doctor will chose a particular patient that they want this application to work on. Most current SMART applications do things with individual data like, e.g., calculate stroke risk or highlight missing immunizations, that kind of thing. When the access token is issued, we also want to communicate some metadata to the client that says "you should be working on patient 123". Since this data isn't communicating a *restriction*, i.e., it's not saying "this access token is only for accessing patient 123's data", it doesn't seem to belong in the access token itself, so it wound up in the access token response.

It seems worth mention that, for better or worse, this is not, from the perspective of someone working in the EHR space, a fly-by-night standard. For instance, under the 21st Century Cares Act implementing the SMART App Framework is actually a requirement for EHR implementations in the US. In other parts of the world, while it may not be backed by legislation, it's still a commonly used standard for applications that want to work with EHR data without necessarily being tied to a particular EHR vendor.

It's worth mention that a different group implemented [the SMART App Framework on Keycloak](https://github.com/igia/igia-keycloak) by essentially supplying a custom login protocol that boils down to more or less the same implementation I'm proposing here. Unfortunately, that approach appears to break the Keycloak UI (especially the Mappers part) and fixing those kinds of issues looks to require re-implementing a fair bit of Keycloak's OIDC protocol implementation.

I hope that makes it clear where this is coming from. If you have any suggestions of a better way that we can add some claims to just the initial access token response, I'm very open to that.

2020-09-02 12:58 UTC, stianst commented
Thanks for the great explanation. Since this really is a requirement to be able to integrate with the SMART framework I agree it is something we should add. One thing I wonder if we should at least make the label a bit more clear on recommending avoiding levering this capability unless you need to, and perhaps also the fact that care should be taken in adding sensitive information into the access token response.

We'll also need some tests around this, but that can wait until we get some feedback from @mposolda and @pedroigor to see if they have any objections around this.

2020-09-02 16:56 UTC, ibacher commented
@stianst Thanks for taking a look at this! Do you have a suggestion for how to change the label as you suggest? I'll definitely add some tests to this PR.

2020-09-03 06:08 UTC, stianst commented on themes/src/main/resources/theme/base/admin/messages/admin-messages_en.properties
> +includeInAccessTokenResponse.tooltip=Should the claim be added to the access token response?
```suggestion
includeInAccessTokenResponse.tooltip=Should the claim be added to the access token response? Should only be used for informative and non-sensitive data
```

2020-09-03 06:47 UTC, mposolda commented
@ibacher Thansk for all the info about SMART framework. +1 from me for adding this capability. As pointed already by @stianst, we may need to add tests and we need to have some support in the built-in mappers for adding claims to AccessTokenResponse.

2020-09-08 12:57 UTC, pedroigor reviewed
I have no objection to include a mapper for token responses.

However, I have some questions around the use case:

* Isn't the "you should be working on patient 123" somewhat a condition and a claim that should be associated with the access token itself to indicate that the doctor is only authorized to deal with a particular patient ? I think I understand the reasoning behind your approach if considering the restrictions impose by SMART integration though.

* Isn't UMA (User-Managed Access) a standard that should be addressing such use cases ?

2020-09-08 13:35 UTC, ibacher commented
> Isn't the "you should be working on patient 123" somewhat a condition and a claim that should be associated with the access token itself to indicate that the doctor is only authorized to deal with a particular patient ? I think I understand the reasoning behind your approach if considering the restrictions imposed by SMART integration though.

So I think the angle that SMART is taking here is that they want to provide some metadata to the client without necessarily restricting the access token. E.g., Dr. X was looking at patient 123's record, so that's probably what should be shown. If, during the use of the app, Dr. X decides to compare patient 123 to patient 456, then the same access token should be used, but the backend will use whatever rules it has (including claims associated with the access token) to determine if Dr. X can access patient 456's record.

> Isn't UMA (User-Managed Access) a standard that should be addressing such use cases ?

I would think that ideally, yes. But SMART is designed to be layered on top of an existing EHR (with it's own management of access). Again, however, the data that I'm talking about adding to the response is not intended to be security-relevant.

2020-09-09 17:25 UTC, thomasdarimont commented on services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java
> +    public AccessTokenResponse transformAccessTokenResponse(KeycloakSession session, AccessTokenResponse token,
```suggestion
    public AccessTokenResponse transformAccessTokenResponse(KeycloakSession session, AccessTokenResponse tokenResponse,
```

2020-09-10 15:05 UTC, pedroigor requested changes
@ibacher Despite the comment from @thomasdarimont. I'm keen to move forward with this PR.

The missing bit though is the test. Could you please work on it ?

2020-09-10 15:19 UTC, ibacher commented
@pedroigor Yes, adding tests is on my TODO list for this.

2020-10-27 22:46 UTC, pedroigor commented
@ibacher Your test is failing. See https://travis-ci.com/github/keycloak/keycloak/jobs/407441246.

2020-11-04 21:00 UTC, ibacher commented
All right! I've finally got my IDE to cooperate with Arquillian so I could actually work out what was going on. Hopefully in this latest update, the test should pass.

2020-11-05 00:03 UTC, pedroigor commented
@ibacher Thanks! I'll iterate over the changes again.

2020-11-09 11:37 UTC, pedroigor approved these changes
@ibacher Thanks !

We are having issues with Travis so I can't merge it. But will once we figure out (or finish our move to GA).

@stianst Or we can just have it in ?

2020-12-03 00:19 UTC, pvnmurthy commented
We are very eagerly waiting for this pull request to be merged. Even we need to support SMART ON FHIR (A healthcare spec) authorization extensions to OIDC by adding extra claims to AccessTokenResponse. Thanks in advance for all your help.

2020-12-03 16:28 UTC, merged

2022-07-21 14:16 UTC, XcrigX commented
@ibacher @pedroigor - apologies for resurrecting this old issue. But the commit here seems to only allow mapping a claim into the access token response using the 'User Session Note' mapper. Was there a reason it wasn't allowed on others, like the user attribute mapper? 
What I'm struggling with is (I think) is that in order to use it, I would need to write a custom authenticator which sets the user session note. Is that correct? 
Or to state that another way - Is there any other way to set a user session note or add a custom claim to the token response without writing custom code? 
Thanks!

2022-07-21 14:36 UTC, lmsurpre commented
@XcrigX FWIW I had opened a PR that expands it to the UserAttributeMapper at https://github.com/keycloak/keycloak/pull/7773 but I never got back to it and so it got closed.  Feel free to revive it.