Keycloak 14953
keycloak/keycloak pull request #7375
Opened 2020-08-27 12:18 UTC by darranl

This is the pull request for the changes we have been discussing recently regarding providing a Galleon feature pack from Keycloak to make it possible to install the Keycloak client adapters for OIDC using Galleon, this will also complement the work currently being undertaken to add support for the generation of bootable jars which is based on the provisioning of Galleon feature packs.

https://issues.redhat.com/browse/KEYCLOAK-14953

The following analysis submission contains a number of examples showing how community users can make use of this against WildFly.

https://github.com/wildfly/wildfly-proposals/pull/330

_Note: The Galleon CLI and galleon-maven-plugin mentioned in the analysis are community only features._

Locally I have been testing the use of the Galleon CLI against WildFly 19.0.0.Final, WildFly 20.0.0.Final and WildFly 20.0.1.Final so the feature pack produced by a Keycloak release is not tied to a single WildFly release so this doesn't introduce a need for lock stepping the releases.

**Example Project**

I am just waiting on a tag of the latest version of the wildfly-jar-maven-plugin and I will add a link to a simple maven project that can be used to make use of this feature pack from within a bootable jar, this is the simplest way for you to experiment with this feature pack applied to a WildFly installation.

**Discussion Points**

A few of areas still need consideration but easier to see in the context of this PR.

1. Initially @jfdenise called the new layer "keycloak-elytron-oidc", within Galleon layers we are making Elytron the preferred solution so I don't really want everything to end up with an "elytron" qualifier - I have renamed the layer "keycloak-client-oidc" but "keycloak-adapter-oidc" could make sense.  If anyone feels strongly now is the time to address that.

2. Presently an expression is used to flip the group ID of the feature pack artefact for project vs product releases.  This seems incompatible with the verification of the GitHub actions so probably need to discuss this item with someone more familiar with your release processes.

3. The examples in the analysis are using a fully qualified GAV to reference the feature pack.  There is an option to publish channels by adding a project equivalent to https://github.com/wildfly/wildfly-producers.  The producers project allows channels to be defined with version ranges.  As an example users of WildFly can specify the feature pack "wildfly:current" and they will always get the latest WildFly version.  Where community users use the Galleon CLI they can also use an update command to update their installation and the use of channels allows the versions to be constrained.

The use of producers to define channels is a community only feature and can be added later so I am just mentioning it here in case there is interest.

2020-08-27 14:53 UTC, darranl commented
I see the cause of the build error, just going to fix the pom.  My local maven settings was compensating for this locally.

2020-09-09 09:48 UTC, pskopek requested changes

2020-09-09 09:48 UTC, pskopek commented on distribution/galleon-feature-packs/adapter-galleon-pack/pom.xml
> +                <version.org.wildfly.common>1.5.4.Final</version.org.wildfly.common>
Version properties here should be aligned with already used properties in keycloak-parent pom.xml.
I have sent PR to your product repo fork.

2020-09-09 09:48 UTC, pskopek commented on distribution/galleon-feature-packs/adapter-galleon-pack/pom.xml
> +            </properties>
The same applies here.

2020-09-10 07:12 UTC, pskopek approved these changes
LGTM!

2020-09-11 10:00 UTC, stianst approved these changes
LGTM, but only done a quick review

2020-09-18 06:27 UTC, merged

2020-10-13 20:26 UTC, lscorcia commented
Hi, sorry to revive a merged PR but I'm having issues when building the master branch since these commits have been merged. I have bisected the commits since the last working sources and got to this feature addition.

In my organization, we build and deploy Keycloak from sources using a CI/CD process which ultimately launches `mvn -DskipTests -Pdistribution clean install`. The build is triggered by CI (gitlab-runner) and it runs in an Ubuntu LXC container with JDK v8. Internet access is available to the container via http proxy set as maven option+/etc/environment vars.

CI builds now fail with the following log messages. Weirdly, if I login via SSH to the container as the same CI user and run the same mvn command, the build completes with no errors. The problem shows up only when running via the non-interactive CI shell. I have no idea about how to fix this - actually I have no idea as to what this build step is actually doing, I can see it tries to spin up a Wildfly server, but that's it. The user running the build is pretty low-privileged, maybe special permissions are required?
Any suggestions to get more information about the error?

Thanks in advance for your help!

```
313288 [INFO] -------------< org.keycloak:keycloak-adapter-galleon-pack >-------------
313288 [INFO] Building Keycloak Galleon Feature Pack: Adapter 12.0.0-SNAPSHOT [244/246]
313288 [INFO] --------------------------------[ pom ]---------------------------------
323187 [INFO] 
323187 [INFO] --- maven-clean-plugin:3.1.0:clean (default-clean) @ keycloak-adapter-galleon-pack ---
323189 [INFO] 
323189 [INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-java-version) @ keycloak-adapter-galleon-pack ---
323190 [INFO] 
323190 [INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-maven-version) @ keycloak-adapter-galleon-pack ---
323191 [INFO] 
323191 [INFO] --- buildnumber-maven-plugin:1.4:create (get-scm-revision) @ keycloak-adapter-galleon-pack ---
323192 [INFO] 
323192 [INFO] --- maven-resources-plugin:3.1.0:copy-resources (copy-resources) @ keycloak-adapter-galleon-pack ---
323193 [INFO] Using 'UTF-8' encoding to copy filtered resources.
323194 [INFO] Copying 2 resources
323195 [INFO] 
323196 [INFO] --- maven-resources-plugin:3.1.0:copy-resources (copy-feature-pack-resources) @ keycloak-adapter-galleon-pack ---
323197 [INFO] Using 'UTF-8' encoding to copy filtered resources.
323199 [INFO] Copying 12 resources
323209 [INFO] 
323209 [INFO] --- keycloak-distribution-licenses-maven-plugin:12.0.0-SNAPSHOT:process (process-licenses) @ keycloak-adapter-galleon-pack ---
323221 [INFO] Appending first party dependency license data
323222 [INFO] ==> org.keycloak,keycloak-adapter-core,12.0.0-SNAPSHOT,Apache Software License 2.0.txt
323223 [INFO] ==> org.keycloak,keycloak-adapter-spi,12.0.0-SNAPSHOT,Apache Software License 2.0.txt
323223 [INFO] ==> org.keycloak,keycloak-authz-client,12.0.0-SNAPSHOT,Apache Software License 2.0.txt
323224 [INFO] ==> org.keycloak,keycloak-common,12.0.0-SNAPSHOT,Apache Software License 2.0.txt
323225 [INFO] ==> org.keycloak,keycloak-core,12.0.0-SNAPSHOT,Apache Software License 2.0.txt
323225 [INFO] ==> org.keycloak,keycloak-jboss-adapter-core,12.0.0-SNAPSHOT,Apache Software License 2.0.txt
323226 [INFO] ==> org.keycloak,keycloak-undertow-adapter,12.0.0-SNAPSHOT,Apache Software License 2.0.txt
323227 [INFO] ==> org.keycloak,keycloak-undertow-adapter-spi,12.0.0-SNAPSHOT,Apache Software License 2.0.txt
323227 [INFO] ==> org.keycloak,keycloak-wildfly-adapter,12.0.0-SNAPSHOT,Apache Software License 2.0.txt
323228 [INFO] ==> org.keycloak,keycloak-wildfly-elytron-oidc-adapter,12.0.0-SNAPSHOT,Apache Software License 2.0.txt
323229 [INFO] ==> org.keycloak,keycloak-wildfly-subsystem,12.0.0-SNAPSHOT,Apache Software License 2.0.txt
323229 [INFO] Writing XML to /home/gitlab-runner/builds/irpkAex9/0/DgrobDiv05/keycloak/distribution/galleon-feature-packs/adapter-galleon-pack/target/resources/packages/licenses/content/docs/licenses-keycloak/licenses.xml
323233 [INFO] Writing transformed HTML to /home/gitlab-runner/builds/irpkAex9/0/DgrobDiv05/keycloak/distribution/galleon-feature-packs/adapter-galleon-pack/target/resources/packages/licenses/content/docs/licenses-keycloak/licenses.html
323251 [INFO] 
323252 [INFO] --- wildfly-galleon-maven-plugin:4.2.6.Final:build-feature-pack (keycloak-adapter-galleon-pack-build) @ keycloak-adapter-galleon-pack ---
Oct 13, 2020 8:21:03 PM org.wildfly.core.embedded.LoggerContext$JBossLoggingModuleLogger greeting
INFO: JBoss Modules version 1.10.1.Final
Oct 13, 2020 8:21:03 PM org.jboss.msc.service.ServiceContainerImpl <clinit>
INFO: JBoss MSC version 1.4.11.Final
Oct 13, 2020 8:21:03 PM org.jboss.threads.Version <clinit>
INFO: JBoss Threads version 2.3.3.Final
Oct 13, 2020 8:21:03 PM org.jboss.as.server.ApplicationServerService start
INFO: WFLYSRV0049: WildFly Core 12.0.3.Final starting
Oct 13, 2020 8:21:06 PM org.projectodd.vdx.wildfly.LoggingPrinter println
INFO: OPVDX003: No schemas available from /home/gitlab-runner/builds/irpkAex9/0/DgrobDiv05/keycloak/distribution/galleon-feature-packs/adapter-galleon-pack/target/wildfly/docs/schema - disabling validation error pretty printing
Oct 13, 2020 8:21:06 PM org.jboss.as.server.ServerService boot
ERROR: WFLYSRV0055: Caught exception during boot
org.jboss.as.controller.persistence.ConfigurationPersistenceException: WFLYCTL0085: Failed to parse configuration
	at org.jboss.as.controller.persistence.XmlConfigurationPersister.load(XmlConfigurationPersister.java:143)
	at org.jboss.as.server.ServerService.boot(ServerService.java:395)
	at org.jboss.as.controller.AbstractControllerService$1.run(AbstractControllerService.java:416)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.xml.stream.XMLStreamException: WFLYCTL0083: Failed to load module org.keycloak.keycloak-adapter-subsystem
	at org.jboss.as.controller.parsing.DeferredExtensionContext.load(DeferredExtensionContext.java:100)
	at org.jboss.as.server.parsing.StandaloneXml_6.readServerElement(StandaloneXml_6.java:221)
	at org.jboss.as.server.parsing.StandaloneXml_6.readElement(StandaloneXml_6.java:121)
	at org.jboss.as.server.parsing.StandaloneXml.readElement(StandaloneXml.java:114)
	at org.jboss.as.server.parsing.StandaloneXml.readElement(StandaloneXml.java:52)
	at org.jboss.staxmapper.XMLMapperImpl.processNested(XMLMapperImpl.java:122)
	at org.jboss.staxmapper.XMLMapperImpl.parseDocument(XMLMapperImpl.java:76)
	at org.jboss.as.controller.persistence.XmlConfigurationPersister.load(XmlConfigurationPersister.java:126)
	... 3 more
Caused by: java.util.concurrent.ExecutionException: javax.xml.stream.XMLStreamException: WFLYCTL0083: Failed to load module
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.jboss.as.controller.parsing.DeferredExtensionContext.load(DeferredExtensionContext.java:92)
	... 10 more
Caused by: javax.xml.stream.XMLStreamException: WFLYCTL0083: Failed to load module
	at org.jboss.as.controller.parsing.DeferredExtensionContext.loadModule(DeferredExtensionContext.java:129)
	at org.jboss.as.controller.parsing.DeferredExtensionContext.access$000(DeferredExtensionContext.java:44)
	at org.jboss.as.controller.parsing.DeferredExtensionContext$1.call(DeferredExtensionContext.java:74)
	at org.jboss.as.controller.parsing.DeferredExtensionContext$1.call(DeferredExtensionContext.java:71)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1348)
	at java.lang.Thread.run(Thread.java:748)
	at org.jboss.threads.JBossThread.run(JBossThread.java:485)
Caused by: org.jboss.modules.Mo [...]

2020-10-13 21:37 UTC, lscorcia commented
As you probably imagined, it was my fault: our local maven was configured with -DinstallAtEnd=true . Removing this config switch made the build work again. There goes another day...

Thanks for your patience!