KEYCLOAK-15429 Add CORS origin on permission request with invalid access token
keycloak/keycloak pull request #7412
Opened 2020-09-11 05:48 UTC by FrodeI

This fetches Web Origins setting from the client to set access-control-allow-origin on token endpoint response in the case where grant type is urn:ietf:params:oauth:grant-type:uma-ticket, and the access token is invalid. This can happen if the token is expired, or if the user is disabled.

2020-09-21 15:01 UTC, vmuzikar requested changes
@FrodeI Thank you for your contribution!

2020-09-21 15:10 UTC, pedroigor requested changes
@FrodeI Thanks for this one !

I share the same suggestion from @vmuzikar. Could you please do that change ?

2020-09-22 05:49 UTC, FrodeI commented on services/src/main/java/org/keycloak/protocol/oidc/endpoints/TokenEndpoint.java
> +                    AccessToken invalidToken = verifier.verify().getToken();
Is it just as correct then to allow any origin for the error response, and ignore the client setting completely? I that's what's done for some of the other checks in TokenEndpoint: (checkSsl, checkRealm)
```java
                    cors.allowAllOrigins();
```

2020-09-22 06:27 UTC, vmuzikar commented on services/src/main/java/org/keycloak/protocol/oidc/endpoints/TokenEndpoint.java
> +                    AccessToken invalidToken = verifier.verify().getToken();
I haven't checked what other verifications do, but I see no real reason why we should allow all origins here. Just parse the token, get the client and you're good to go. :)

2020-09-22 11:54 UTC, pedroigor approved these changes
Thanks !

2020-09-22 11:56 UTC, merged