Check FIELD_PASSWORD_CONFIRM only if client submitted FIELD_PASSWORD_…
keycloak/keycloak pull request #7432
Opened 2020-09-21 10:32 UTC by pherman

I have a client that wishes to have a registration form without the password confirmation field. This field is a convenience for the user anyway and is not absolutely necessary.  Thus, I changed the implementation of RegistrationPassword.java to check the FIELD_PASSWORD_CONFIRM only if it was actually passed back in the form.  Otherwise, the check should be ignored.

2020-09-21 11:49 UTC, stianst commented
I'm onboard with the idea that a password confirmation is not strictly needed. However, I don't quite like the approach here by just ignoring the field on the server-side. As this is done now it's completely hidden to anyone other than yourself. No one else will know/understand that this is possible.

Perhaps a different approach would be to add a config option for the action.

Also, please read our contributors guideline with regards to creating a JIRA, and also adding tests.

2020-09-27 21:12 UTC, pherman commented
I've created a Jira ticket: https://issues.redhat.com/browse/KEYCLOAK-15728

2020-10-12 09:59 UTC, mposolda commented
@pherman Thanks for the PR and sorry for the late response.
- As pointed already, it will be good to add this as a configuration option on the Authenticator - looks like RegistrationPassword authenticator would be best way to go. For the backwards compatibility, confirmation field should be enabled by default
- It will be good to add the JIRA to the commit message. See the other commits to the Keycloak repository for the inspiration.
- Finally, will be good to add the test. Probably new test-case to the RegisterTest with the confirmation field disabled will be nice.

2020-10-12 09:59 UTC, mposolda requested changes
@pherman Thanks for the PR and sorry for the late response.

- As pointed already, it will be good to add this as a configuration option on the Authenticator - looks like RegistrationPassword authenticator would be best way to go. For the backwards compatibility, confirmation field should be enabled by default
- It will be good to add the JIRA to the commit message. See the other commits to the Keycloak repository for the inspiration.
- Finally, will be good to add the test. Probably new test-case to the RegisterTest with the confirmation field disabled will be nice.

2021-02-03 13:57 UTC, mposolda commented
@pherman I am closing the PR due the lack of feedback. Feel free to re-open, but please address the comments above

2021-02-03 13:57 UTC, closed without merging

2021-02-03 14:20 UTC, pherman commented
I posted a message here recently: https://issues.redhat.com/browse/KEYCLOAK-15728
and am waiting for feedback.