KEYCLOAK-15836 : Do not override System property mail.smtp.ssl.protoc…
keycloak/keycloak pull request #7472
Opened 2020-10-06 19:47 UTC by tgyKomgo

Proposal of this PR : 

- Each enduser should be able to select allowed protocol to use to connect to an smtp server over ssl.
- To not impact expected behavior of Keycloak (KEYCLOAK-13285), default supported SSL Context protocol still applied but only if jvm parameter mail.smtp.ssl.protocols is not already set (ex JAVA_OPTS= -Dmail.smtp.ssl.protocols=...)

2020-10-13 08:57 UTC, stianst requested changes
This is just a work-around for yourself and not a proper solution for others. We need to find some way of either fixing the issue, or making it possible to configure SSL protocols to be supported in a nice KC friendly way (not by setting low-level java system properties)

2020-10-13 09:14 UTC, tgyKomgo commented
> This is just a work-around for yourself and not a proper solution for others. We need to find some way of either fixing the issue, or making it possible to configure SSL protocols to be supported in a nice KC friendly way (not by setting low-level java system properties)

under javax.mail documentation, it should be done using this low-level property : https://javaee.github.io/javamail/FAQ.html#smtpssl

2020-10-13 09:36 UTC, stianst commented
Folks should not need to be experts in JavaMail to use KC.

2020-10-13 09:46 UTC, tgyKomgo commented
> Folks should not need to be experts in JavaMail to use KC.

Make sense ... in this case we should wait for this one :
https://issues.redhat.com/browse/KEYCLOAK-14907

2020-10-13 09:46 UTC, stianst commented
Let's discuss this on the dev ml. If we can't find a better solution, then I'm okay with merging this, but let's at least see if we can come up with a better way that doesn't require folks to understand javamail docs to resolve an issue after the fact.

2020-10-23 07:22 UTC, stianst commented
I'm going to close this PR as I believe we should do something better. Let's discuss through mailing list, or on this JIRA:
https://issues.redhat.com/browse/KEYCLOAK-16047

2020-10-23 07:22 UTC, closed without merging