KEYCLOAK-15806: Extension to SignatureAlgorithm to support more Algorithms
keycloak/keycloak pull request #7480
Opened 2020-10-08 08:41 UTC by rowe42

Extension to SignatureAlgorithm to support more Algorithms (RSA_SHA256_MGF1, RSA_SHA512_MGF1).
    Also included in realms.js so it can be chosen as signature algorithm when brokering through SAML.

2020-10-09 21:31 UTC, hmlnarik requested changes
Thank you for the PR. Please see inline.

2020-10-09 21:31 UTC, hmlnarik commented on themes/src/main/resources/theme/base/admin/resources/js/controllers/realm.js
> +            "RSA_SHA512_MGF1"
These changes should be done consistently also for SAML clients.

2020-10-12 06:10 UTC, rowe42 commented
fixed. sorry for the stupid copy-paste-error!

2020-10-15 12:34 UTC, hmlnarik commented
Thank you. For some reason setting the client signature algorithm to one of the MGF variants, the client does not display the signature algorithm in client detail. Could you please check?

Also it would be great if the new algorithms were placed next to their non-MGF variant in the combo box, currently they are at the end of the list.

2020-10-15 16:47 UTC, rowe42 commented
@hmlnarik You were right. There was some code missing in clients.js, which takes care of setting the chosen entry to the data model.

I've fixed that now and rearranged the entries as suggested.

2020-10-15 18:55 UTC, hmlnarik approved these changes
Thank you for the contribution!

2020-10-15 18:55 UTC, merged