Update DefaultKeyManager kid is null logging
keycloak/keycloak pull request #7493
Opened 2020-10-13 08:30 UTC by leppaott

Got this "kid is null, can't find public key" without a hint to which realm it's belonging. Not sure if the realm name is dropped because it's null(?), but at least the log message is now explicit. Dropping kid because the text says it's null. Haven't tested whether this breaks tests etc.

2020-10-15 12:15 UTC, hmlnarik requested changes
Thank you for the contribution. Please introduce a JIRA for this issue, and include it both in the commit message and PR title. Then the PR would be ready for merging.

2020-10-22 14:27 UTC, hmlnarik commented
@leppaott Could you please rebase and address the comment above?

2020-10-23 09:35 UTC, leppaott commented
@hmlnarik slightly better?

2020-11-03 19:39 UTC, hmlnarik approved these changes
Thank you!

2020-11-03 19:40 UTC, merged