KEYCLOAK-14201 Client Policy - Executor : Enforce Proof Key for Code Exchange (PKCE)
keycloak/keycloak pull request #7501
Opened 2020-10-15 02:34 UTC by tnorimat

This PR is for [KEYCLOAK-14201 Client Policy - Executor : Enforce Proof Key for Code Exchange (PKCE)](https://issues.redhat.com/browse/KEYCLOAK-14201) in [KEYCLOAK-13933 Client Policies](https://issues.redhat.com/browse/KEYCLOAK-13933), also is the part of the project [Client Policy Official Support](https://github.com/keycloak/kc-sig-fapi/projects) of [FAPI-SIG](https://github.com/keycloak/kc-sig-fapi) activity.

Generally speaking, the aim of this PR is to support policy executors defined in [Client Policy design document](https://github.com/keycloak/keycloak-community/blob/master/design/client-policies.md#which-kind-of-executors-are-provided)

As mentioned in the corresponding [JIRA ticket](https://issues.redhat.com/browse/KEYCLOAK-14201), its details are as follows.

- on the `REGISTER` event (i.e. before registering client by Dynamic Client Registration or Admin REST API)
- on the `UPDATE` event (i.e. before updating client by Dynamic Client Registration or Admin REST API)
  - enforce PKCE setting (`code_challenge_method` = `S256`) depending on this executor's setting.
  - check whether the client's PKCE setting is enabled or not. If not, return the error.
- on the `AUTHORIZATION_REQUEST` event (i.e. receive authz request from client)
  - do PKCE specification defining process the same as what has already been implemented in `AuthorizationEndpoint`.
- on the `TOKEN_REQUEST` event (i.e. receive token request from client)
  - do PKCE specification defining process the same as what has already been implemented in `TokenEndpoint`.

I've recognized that this executor do the same thing done by the existing `AuthorizationEndpoint` and `TokenEndpoint`, namely duplicate PKCE protocol processing.

When working on [KEYCLOAK-14208 Client Policy : Pre-set Policies](https://issues.redhat.com/browse/KEYCLOAK-14208), I'd like to remove PKCE part from `AuthorizationEndpoint` and `TokenEndpoint`.

2020-10-15 03:14 UTC, tnorimat commented
[Travis failure](https://travis-ci.com/github/keycloak/keycloak/jobs/399938204) is irrelevant to this PR.

2020-11-05 19:47 UTC, mposolda requested changes
@tnorimat Thanks and sorry for the late review. The PR looks good to me, but there is conflict with your other PR. Could you please rebase this?

2020-11-06 10:58 UTC, tnorimat commented
@mposolda I've resolved conflicts and rebased.

2020-11-06 19:51 UTC, mposolda commented
@tnorimat Thanks and I am sorry to ask, but could you please rebase again? We are currently doing some changes in the GH actions configuration as Travis doesn't work anymore. And there were some fixes from today, which should (hopefully) help to fix some issues and make the build with GH actions to pass.

I see there is compilation error reported in Keycloak CI github actions build, but I suppose you are not seeing it on your laptop, so it is really just the issue in our GH actions caching configuration. Could you please just doublecheck after rebase? Thanks

2020-11-07 05:49 UTC, tnorimat commented
@mposolda I've rebased again. I've done the following tests on my local environment.
```
mvn clean install -DskipTests -Pdistribution
mvn clean install -Pauth-server-wildfly -DskipTests -f testsuite/pom.xml
mvn clean install -Pauth-server-wildfly -f testsuite/integration-arquillian/tests/base/pom.xml
```

2020-11-09 07:17 UTC, mposolda approved these changes
@tnorimat Thanks! I am merging your PR

2020-11-09 07:18 UTC, merged