[KEYCLOAK-15634] Prevent federated user removal with new account console
keycloak/keycloak pull request #7543
Opened 2020-10-27 23:16 UTC by vanrar68

A quick and dirty fix to trigger a discussion around #KEYCLOAK-15634
The new account console deletes federated user stored in Keycloak local storage by removing system attributes from these users

2020-10-28 12:55 UTC, vanrar68 commented
Another option for a fix:

The new account console code that's handling the user info form in AccountPage.tsx seems to overwrite the 'attributes' node of the submitted JSON in case the user has no locale set:

`private fetchPersonalInfo(): void {
        this.context!.doGet<FormFields>("/")
            .then((response: HttpResponse<FormFields>) => {
                this.setState(this.DEFAULT_STATE);
                const formFields = response.data;
                if (!formFields!.attributes || !formFields!.attributes.locale) {
                    formFields!.attributes = { locale: [locale] };
                }

                this.setState({...{ formFields: formFields as FormFields }});
            });
    }`

I successfuly tested that #KEYCLOAK-15634 doesn't occur if the user located in the local storage has a locale attribute set before accessing the account console and submitting a change

2020-10-28 17:06 UTC, vanrar68 commented
Just updated the PR with a fix that makes more sense (client side fix in the code handling the user info form)

2020-11-25 16:16 UTC, mposolda commented
@abstractj @stianst @vanrar68  I confirm that this is the issue in the UI layer. For more details:
- The GET REST endpoint returns all the attributes of the user (including LDAP_ID)
- The POST request sent from the UI sends just the 5 attributes (firstName, lastname, username, email and locale). This causes the missing attributes to be deleted (including LDAP_ID attribute) which causes this bug

IMO this should be fixed in the UI layer, so that UI sends all the attributes of the user.

The only thing missing in this PR is the test, which may need to be done for the account console UI level. I am not sure if we want to block this PR due the test?

BTV. As the test, this can be simulated without LDAP as well. For example by doing this:
- Create user with the admin REST API and add some attribute "foo" with value "bar" to him. Just make sure that user does not have "locale" attribute (which he does not have by default).
- Login as this user into the account console
- Update user
- Now the attribute "foo" was deleted from the user in latest master (with the fix it should not be deleted).

2020-11-25 22:32 UTC, vanrar68 commented
@mposolda I'll add the test

2020-11-26 09:27 UTC, vanrar68 commented
Added a test. Not working yet. Any clue why @mposolda ?

2020-11-26 19:07 UTC, vanrar68 commented
Ok got it, wrong place to insert the test since ACCOUNT2 feature is disabled on this class.
I guess account2/PersonalInfoTest.java would be a more suitable location, wouldn't it ?

2020-11-26 20:50 UTC, mposolda requested changes
@vanrar68 Thanks for adding the test. This is unfortunately not the correct place for the test :( The AccountFormServiceTest is the test for the old account console.

The correct place for adding the test is this package in the "other" module: https://github.com/keycloak/keycloak/tree/master/testsuite/integration-arquillian/tests/other/base-ui/src/test/java/org/keycloak/testsuite/ui/account2 . Probably the PersonalInfoTest (for the non-LDAP scenario I mentioned) or LDAPAccountTest (for the LDAP scenario) might be the best place to test UI.

Here is the info how to execute the tests. These are UI tests and need to use "Real" web browser. It is sufficient to choose some browser (EG. chrome) and run the tests with them: https://github.com/keycloak/keycloak/blob/master/testsuite/integration-arquillian/HOW-TO-RUN.md#base-ui-tests . You may need to add something like `-Dtest=PersonalInfoTest` to the arguments to make sure that just your test will be executed.

2020-11-26 20:51 UTC, mposolda commented
> Ok got it, wrong place to insert the test since ACCOUNT2 feature is disabled on this class.
> I guess account2/PersonalInfoTest.java would be a more suitable location, wouldn't it ?

Yes, exactly!

2020-11-27 11:37 UTC, vanrar68 commented
@mposolda I moved the test to the right location. It runs well with both Firefox and Chrome drivers.
Thanks for the pointers!

2020-11-27 12:44 UTC, mposolda approved these changes
@vanrar68 Thanks!

2020-11-27 12:44 UTC, merged

2020-11-28 14:20 UTC, vanrar68 commented
@mposolda FWIW I have the LDAP test ready and working with both firefox/chrome drivers. Let me know if it's worth submitting now that the PR has been merged.