KECLOAK-16009 Add a method to check if the token request has duplicat…
keycloak/keycloak pull request #7544
Opened 2020-10-28 04:32 UTC by Yang-Xie-OSS

…e parameters

When receive a request with duplicate parameters, the token endpoint doesn't response an error message defined in the RFC6749.
The details can be found in this JIRA[1].

[1] https://issues.redhat.com/browse/KEYCLOAK-16009.

Because all the grant types supported by the token endpoint should check the duplicate parameters, I added a check method before the grant type check.

Token endpoint is different from authorization endpoint as it don't have a parameter parser. So I can't use the same method which used in fixing KEYCLOAK-11996 [2]. I think that looping over all params is the only way to fix this problem.
[2] https://github.com/keycloak/keycloak/pull/6467

2020-11-11 15:49 UTC, mposolda commented
@Yang-Xie-OSS Thanks for the PR and sorry for the late review.

The fix looks mostly good to me, but there are test failures in the CI. I think that LDAPUserLoginTest is already fixed in latest master (you can eventually rebase this PR to the latest master, so we can confirm this). However the EntitlementAPITest failure is maybe the regression of this PR. Could you please doublecheck?

Will be good to check if EntitlementAPITest is using some duplicate parameters. If yes, it will be good to check the UMA specification and whether our "permission" endpoint is also subject to this check and should not allow duplicated parameters.

2020-11-11 15:50 UTC, mposolda requested changes
Marking as "Request changes" as there is likely regression in the test and we may need to clarify whether this should be for UMA endpoint...

2020-11-11 15:51 UTC, mposolda commented
We have a map AuthzEndpointRequestParser.KNOWN_REQ_PARAMS . It is possible that just the known OIDC/OAuth2 parameters should be subject to this change. But I am not yet 100% sure if this is best to handle this... Just a note...

2020-11-17 07:26 UTC, Yang-Xie-OSS commented
@mposolda 
I rebased this PR to the lastest master and it looks like LDAPUserLoginTest failure was disappeared. Besides, I confirmed that EntitlementAPITest failure is certainly due to this change.
checkParameterDuplicated() works before checkGrantType() so all actions (grant types) are affected by this method. As shown in linked JIRA, the error response of PERMISSION is also defined as RFC6749's 5.2 secion[3]. And it should be responded when a parameter was repeated.
[3] https://tools.ietf.org/html/rfc6749#section-5.2

I found that token endpoint received 2 "permission" parameter and have the same value when run the EntitlementAPITest. The test have 4 errors and 2 of them caused by "permission=#sensors:view,sensors:update" repeated twice, other 1 error caused by "permission=d00e5038-c7db-4ad3-8a83-c000225700b3" repeated twice.

After all, it might be good to fix the EntitlementAPITest. What's your opinion?

2020-11-18 05:36 UTC, Yang-Xie-OSS commented
@mposolda 
I found that in UMA grant request, parameter "permission" can be added multiple times. It can be confirmed at
 org.keycloak.authorization.client.util.HttpMethodAuthenticator.uma() shown as below.
```java
        if (permissions != null) {
            for (Permission permission : permissions.getPermissions()) {
              ...
                method.params("permission", value.toString());
            }
        }
```

And it might be thought like a correct behavior because in TokenEndpoint, permissionGrant() treat permission as a list shown as below. So it can be thought that checkParameterDuplicated() will almost every time respond a error response after received a UMA grant request.
```java
        // permissions have a format like RESOURCE#SCOPE1,SCOPE2
        List<String> permissions = formParams.get("permission");

        if (permissions != null) {
        ...
```

After all, I have two ideas to resolve this problem as shown below.

1. Don't run checkParameterDuplicated() when the parameter's name is "permission" and grant type is uma.
2. To modify the permission parameter's format to some others (e.g.: A list of space-delimited, case-sensitive strings like the scope parameter). But I'm not sure if that is correct because I can't find a clear definition of permission parameter.

What's your opinion?

2020-11-24 07:40 UTC, Yang-Xie-OSS commented
@mposolda
I think the 2nd idea above, to change the permission parameter's format, will cause lots of impacts. People who use keycloak as a uma endpoint are used to configure multiple permission parameters  but they will receive an error response after the change. And they don't know how to deal with it.
So I choose not to run checkParameterDuplicated() when grant type is UMA. I've changed the code already and confirmed it passed the EntitlementAPITest.

2021-02-03 15:10 UTC, mposolda commented
@Yang-Xie-OSS Thanks, I am merging your PR. There is still space for improvement here around the better support for various grant types etc (We plan to introduce SPI for grantTypes of TokenEndpoint). But for now, it is ok.

2021-02-03 15:10 UTC, merged