KEYCLOAK-16627 detach user session on potential refresh token abuse
keycloak/keycloak pull request #7681
Opened 2020-12-15 18:22 UTC by fugu13

JIRA: [KEYCLOAK-16627: Potential abuse of refresh tokens does not invalidate related tokens](https://issues.redhat.com/browse/KEYCLOAK-16627)

Potential abuse of refresh tokens did not invalidate other refresh tokens, violating the OAuth 2.0 BCP and allowing an attacker to take over a session simply by immediately refreshing after illicitly obtaining a refresh token, which would work so long as the real user had not yet used that refresh token.

I've used `detachFromUserSession()` in the existing place where the potential abuse is detected to create this behavior, and updated the related tests to check for it (where previously they'd checked that the refresh tokens were still allowed).

2021-02-03 14:06 UTC, mposolda approved these changes
@fugu13 Thanks

2021-02-03 14:09 UTC, mposolda requested changes
@fugu13 Thanks for the PR, however there are some failing tests. OfflineTokenTest failing is regression of this PR. Maybe also JavascriptAdapterTest, but not 100% sure about that one (maybe it was just random failure in our testsuite).

Could you please check the failing tests?

2021-02-03 16:32 UTC, fugu13 commented
@mposolda I'll try to take a look at the tests and fix the PR this week or early next week, most likely the OfflineTokenTest just needs a slight test modification, not sure what's up with JavascriptAdapterTest (but as you say, it might be unrelated). Thanks for taking a look!

2021-03-02 08:38 UTC, mposolda commented
@fugu13 Thanks for the note. Any update on this PR?

2021-04-29 14:41 UTC, mposolda commented
@fugu13 I am closing this as there is no more feedback on this PR. But feel free to re-open when you have time to work on this and look at failing test.

2021-04-29 14:41 UTC, closed without merging