[KEYCLOAK-16676] - Client attributes should not be stored if null or empty
keycloak/keycloak pull request #7751
Opened 2021-02-02 03:14 UTC by pedroigor

2021-02-03 09:22 UTC, hmlnarik requested changes
Thank you for the PR.

The map storage needs to be updated similarly, this should fix the test failures (`org.keycloak.models.map.client.MapClientAdapter.setAttribute(String, String)`).

2021-02-03 10:36 UTC, pedroigor commented on testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/LogoutTest.java
> +        clients.get(rep.getId()).update(rep);
Now that change has no impact, so the same "status-quo" is kept. Otherwise, that would cause errors.

2021-02-03 11:49 UTC, pedroigor commented
> Thank you for the PR.
> 
> The map storage needs to be updated similarly, this should fix the test failures (`org.keycloak.models.map.client.MapClientAdapter.setAttribute(String, String)`).

I don't know yet why but changing that method does not fix tests. They are: `successfulKLogoutAfterEmptyBackChannelUrl` and `postLogoutExpiredRefreshToken`, and `postLogoutWithRefreshTokenAfterUserSessionLogoutAndLoginAgain`.

Something is happening where tests timeout when waiting for the logout action to be available from the testing application provider.

Is this a blocker for the PR? If so, I need to spend some more time looking at these failures.

In regards to Quarkus clustering failures, I've created https://issues.redhat.com/browse/KEYCLOAK-17031.

2021-02-03 21:14 UTC, hmlnarik commented
> > Thank you for the PR.
> > The map storage needs to be updated similarly, this should fix the test failures (`org.keycloak.models.map.client.MapClientAdapter.setAttribute(String, String)`).
> 
> I don't know yet why but changing that method does not fix tests. They are: `successfulKLogoutAfterEmptyBackChannelUrl` and `postLogoutExpiredRefreshToken`, and `postLogoutWithRefreshTokenAfterUserSessionLogoutAndLoginAgain`.
> 
> Something is happening where tests timeout when waiting for the logout action to be available from the testing application provider.
> 
> Is this a blocker for the PR? If so, I need to spend some more time looking at these failures.

Unfortunately yes. Undertow / map tests are currently stable. Since I'll be away for following days, @mhajas could you please help @pedroigor with the failures?

> In regards to Quarkus clustering failures, I've created https://issues.redhat.com/browse/KEYCLOAK-17031.

Is this related / duplicate of https://issues.redhat.com/browse/KEYCLOAK-16435?

2021-02-05 19:23 UTC, pedroigor commented
> > > Thank you for the PR.
> > > The map storage needs to be updated similarly, this should fix the test failures (`org.keycloak.models.map.client.MapClientAdapter.setAttribute(String, String)`).
> > 
> > 
> > I don't know yet why but changing that method does not fix tests. They are: `successfulKLogoutAfterEmptyBackChannelUrl` and `postLogoutExpiredRefreshToken`, and `postLogoutWithRefreshTokenAfterUserSessionLogoutAndLoginAgain`.
> > Something is happening where tests timeout when waiting for the logout action to be available from the testing application provider.
> > Is this a blocker for the PR? If so, I need to spend some more time looking at these failures.
> 
> Unfortunately yes. Undertow / map tests are currently stable. Since I'll be away for following days, @mhajas could you please help @pedroigor with the failures?
> 
> > In regards to Quarkus clustering failures, I've created https://issues.redhat.com/browse/KEYCLOAK-17031.
> 
> Is this related / duplicate of https://issues.redhat.com/browse/KEYCLOAK-16435?

Sorry, my bad. The suggestion to fix worked fine. I was doing something stupid.

2021-03-03 11:53 UTC, mhajas approved these changes
LGTM. Thanks @pedroigor.

2021-03-03 14:36 UTC, hmlnarik approved these changes
Approving, based on @mhajas's approval

2021-03-03 14:37 UTC, merged