KEYCLOAK-17192 Add jaxb module dependency required by JAXBUtil class
keycloak/keycloak pull request #7798
Opened 2021-02-19 15:07 UTC by lscorcia

The JAXBUtil class requires classes that have been removed from JDK11. These are already imported with the appropriate POMs during compilation, but they aren't declared in the module dependencies and are therefore unavailable at runtime.

This PR adds the appropriate dependency to the module.

2021-03-04 08:57 UTC, hmlnarik requested changes
Thank you for the PR!

Could you please also update `distribution/saml-adapters/wildfly-adapter/wildfly-modules/src/main/resources/modules/org/keycloak/keycloak-saml-core/main/module.xml` and `distribution/saml-adapters/as7-eap6-adapter/as7-modules/src/main/resources/modules/org/keycloak/keycloak-saml-core/main`?

Also I believe that for AS7 / EAP6 we need to have this with `optional="true"`, i.e.
```xml
<module name="javax.xml.bind.api" optional="true" />
```

2021-03-04 13:12 UTC, lscorcia commented
Thanks for the review! I applied the additional edits you requested verbatim - I don't know how to test that they're correct (we don't use the adapters). Let's see what the automated tests have to say :)

2021-03-15 16:33 UTC, martin-kanis approved these changes
@lscorcia Thanks for the PR. Installation of keycloak adapter to Wildfly 23/ EAP 6/7 and deployment of a simple app work well.

2021-03-15 16:40 UTC, hmlnarik approved these changes
Approving, based on @martin-kanis 's review. Thanks for the PR!

2021-03-15 16:41 UTC, merged