Fix new account console tests
keycloak/keycloak pull request #7839
Opened 2021-03-09 12:10 UTC by Aboullos

Fix DeviceActivityTest, SigningInTest and PermissionsTest

PermissionsTest will still fail because there is a bug in the New Account Console, the test failure was covering the bug:
https://issues.redhat.com/browse/KEYCLOAK-17366

2021-03-09 13:58 UTC, mhajas requested changes
Thank you for the PR @Aboullos, the changes look good, however we should cleanup all changes in realm config after test, I commented directly in code. Otherwise it looks good.

2021-03-09 14:47 UTC, Aboullos commented
Thanks, I just applied the changes

2021-03-09 15:31 UTC, mhajas approved these changes
Thanks @Aboullos, LGTM now.

2021-03-10 08:00 UTC, pdrozd approved these changes

2021-03-10 08:00 UTC, merged