KEYCLOAK-17407 - Add Retry
keycloak/keycloak pull request #7843
Opened 2021-03-10 12:38 UTC by Aboullos

Test works fine in local, but in Jenkins it needs a wait of 1 second

2021-03-11 09:47 UTC, hmlnarik commented
Can `Thread.sleep` be avoided and rather done via e.g. Retry - 10 retries in 1 second would do the job without unnecessary waiting.
Also please file a JIRA.

2021-03-11 14:04 UTC, Aboullos commented
The test passed with the changes in this build:
new-jenkins.com/job/universal-test-pipeline-server/152

I applied the retry to the old code too

2021-03-11 17:51 UTC, hmlnarik requested changes
Thank you for the PR. Looks good apart from a minor thing.

2021-03-11 17:51 UTC, hmlnarik commented on testsuite/integration-arquillian/tests/other/console/src/test/java/org/keycloak/testsuite/console/authorization/DisableAuthorizationSettingsTest.java
> +import static org.junit.Assert.*;
Please avoid star imports.

2021-03-24 08:22 UTC, mhajas approved these changes
@Aboullos Looks good to me. Thanks

2021-03-24 14:14 UTC, pdrozd approved these changes

2021-03-24 14:15 UTC, merged