KEYCLOAK-17655 - Can't impersonate with client_crédential flow
keycloak/keycloak pull request #7904
Opened 2021-04-06 07:02 UTC by Spechey

You can no longer impersonate a user with a "client_credential" service account of the same realm.

Indeed this type of account does not have a session in its access token, which causes an exception in the search for the latter to operate a disconnection (services/src/main/java/org/keycloak/services/resources/admin/UserResource.java line 295 to 300)

2021-04-23 12:59 UTC, Spechey commented
Is it possible to take it into the next version ?
@stianst @mposolda

2021-05-11 17:48 UTC, Spechey commented
Don't forget me !

2021-05-12 06:26 UTC, mposolda requested changes
@Spechey Thanks for the PR. Do you please have a chance to add the automated test for this scenario? I think ImpersonationTest is the correct place to add a test

2021-05-12 19:51 UTC, Spechey commented
Ok, i try to do that as soon as posible

2021-05-18 12:15 UTC, mposolda approved these changes
@Spechey Thanks!

2021-05-18 12:16 UTC, merged

2021-06-11 16:23 UTC, Leletir commented
Hi, 
Thank you all for your work on this issue !

Do you know when it will be released ?