KEYCLOAK-16918 Set custom user attribute to Name ID Format for a SAML…
keycloak/keycloak pull request #7913
Opened 2021-04-07 15:25 UTC by i7a7467

https://issues.redhat.com/projects/KEYCLOAK/issues/KEYCLOAK-16918
https://groups.google.com/g/keycloak-dev/c/4ExUdT9rc2g

### SAMLNameIdMapper interface
I created SAMLNameIdMapper interface so that we can add Script mapper etc. in the future.

### SAML Metadata
I do not change NameID Format  in SAML 2.0 Identity Provider Metadata.
I think it is unclear whether NameID will be the expected value.

2021-04-09 12:33 UTC, mhajas requested changes
Thank you very much for PR @i7a7467. It looks good to me, I just found one minor issue in one of the test cases. Otherwise, it looks good to me.

2021-04-09 13:00 UTC, i7a7467 commented on testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/saml/NameIdMapperTest.java
> +                ProtocolMapperUtils.USER_ATTRIBUTE, "username"))
Sorry. Yes, you're right. It's better not to use username.

2021-04-12 08:27 UTC, mhajas approved these changes, later dismissed
Thank you for the fix @i7a7467! The PR LGTM now. @hmlnarik Can you have a look and possibly merge?

2021-04-12 08:28 UTC, mhajas commented
I forgot about one more thing. @i7a7467 Can you squash the commits into one please?

2021-04-12 09:22 UTC, i7a7467 commented
Thanks. @mhajas 
I squashed the commit.

2021-04-12 11:37 UTC, mhajas approved these changes, later dismissed

2021-04-19 10:44 UTC, hmlnarik approved these changes, later dismissed
Approving based on @mhajas's approval

2021-04-19 10:44 UTC, hmlnarik commented
@i7a7467 Since there's a conflict, could you please rebase to current master?

2021-04-20 08:29 UTC, hmlnarik approved these changes
Thank you @i7a7467. Reapproving

2021-04-20 08:29 UTC, merged