KEYCLOAK-15244 Require user to agree to 'terms and conditions' during registration
keycloak/keycloak pull request #7938
Opened 2021-04-15 18:52 UTC by reda-alaoui

2021-04-21 14:23 UTC, thomasdarimont commented
Wouldn't it have been easier to make `RegistrationUserCreation` configurable and add a "requireTerms" config property?

2021-04-21 14:50 UTC, reda-alaoui commented
I followed `Recaptcha` example. The advantage of the separate `FormAction` is greater modularity. Also it may allow to re-use the action in a context different from user registration in the future.

But I would not mind turning this into a `RegistrationUserCreation` configuration option if needed.

2021-11-13 09:52 UTC, agemuend commented
We are very interested in this, is it still being worked on?

2021-11-15 07:34 UTC, stianst submitted a review, later dismissed
Requiring users to accept t&c during registration would be good to have, but please provide a summary of the proposed changes here, and how it should work.

2022-01-19 14:09 UTC, pdomineaux commented
Hello, thanks for the amazing work, any updates on that GDPR compliant feature?

2022-03-24 10:11 UTC, pachisi456 commented
Any updates on this? Would be quite interested in using this soon.

2022-05-10 10:12 UTC, reda-alaoui commented
Ping :pray:

2022-06-15 06:29 UTC, tbdaniel27 commented
:+1: 

This is actually a legal requirement in Germany. Forcing the user to accept the TOS after registration via the required action is too late because the contract was already created. Therefore, please consider accepting this feature :pray:

2022-08-21 22:10 UTC, wojtekkul commented
Any updates?

2022-08-22 07:18 UTC, RANSoftRA commented
Would be nice to have this in the next version.

2022-11-20 19:38 UTC, reda-alaoui commented
Ping :cry:

2023-03-30 16:21 UTC, adamalexandru4 commented
We want this feature!

2023-04-25 12:24 UTC, thuemmler-zeppelin commented
@reda-alaoui I think the feature would be able to be merged if you fulfilled @stianst changes request. It is just to provide a summary and how it works. 
I think this would be a powerful highly needed feature for european needs

2023-04-25 12:55 UTC, reda-alaoui commented
> @reda-alaoui I think the feature would be able to be merged if you fulfilled @stianst changes request. It is just to provide a summary and how it works. I think this would be a powerful highly needed feature for european needs

@thuemmler-zeppelin , the content of https://github.com/keycloak/keycloak/pull/7938#issue-859160934 has already been updated in `January 30 2022`  following https://github.com/keycloak/keycloak/pull/7938#pullrequestreview-805712249 .

2023-04-26 07:37 UTC, thuemmler-zeppelin commented
> > @reda-alaoui I think the feature would be able to be merged if you fulfilled @stianst changes request. It is just to provide a summary and how it works. I think this would be a powerful highly needed feature for european needs
> 
> @thuemmler-zeppelin , the content of [#7938 (comment)](https://github.com/keycloak/keycloak/pull/7938#issue-859160934) has already been updated on `January 30, 2022` following [#7938 (review)](https://github.com/keycloak/keycloak/pull/7938#pullrequestreview-805712249) posted on `November 15, 2021`.
> 
> From my POV, the change request has been fulfilled a long time ago.

@reda-alaoui  Oh sorry i did not see that one. Maybe someone (@stianst ) can resolve this as resolved then? ;-)

2023-05-02 08:38 UTC, mabartos commented
@mposolda @stianst @rmartinc Guys, do you think you have some time, this or next sprint, to review this PR? :))

2023-05-25 16:03 UTC, reda-alaoui commented
:sleeping:

2023-05-26 15:09 UTC, rmartinc requested changes
Thanks @reda-alaoui for the PR and really sorry for the delay!

It LGTM  and I think it's a very good idea. Current terms and conditions need the user created as they are implemented as a user action. But for sure you have to change the import to `jakarta` or it won't compile in main now (it's our fault for not reviewing it sooner).

Please rebase the branch to put PR changes on top of current main and modify the import. Also squash the commits into a singe one once the PR is being reviewed.

I have a doubt about if we usually modify the `registration` flow in upgrades (for existing realms). I have checked a bit and I think the answer is no. The old flows remain as it were before. Nevertheless I will ask to the team and I'll confirm you the next week.

Have a nice weekend!

2023-05-26 17:29 UTC, reda-alaoui commented on themes/src/main/resources/theme/base/login/register-user-profile.ftl
> +			</#if>
It looks like to me that the indentation is already at the same level than the recaptcha  block. And what do you mean by OCD?

2023-05-29 07:07 UTC, rmartinc commented on themes/src/main/resources/theme/base/login/register-user-profile.ftl
> +			</#if>
:smile:  My [ODC](https://en.wikipedia.org/wiki/Obsessive%E2%80%93compulsive_disorder), I think the new part is to the right, isn't it?

```xml
			</#if>
            
            <#if recaptchaRequired??>
```

2023-05-29 10:48 UTC, pedroigor commented on themes/src/main/resources/theme/base/login/register-user-profile.ftl
> +            <#if termsAcceptanceRequired??>
Would make sense to create a macro and import/re-use the template on both registration pages?

2023-05-29 12:43 UTC, rmartinc commented
@reda-alaoui I asked and some other colleagues also think that upgrade modifications are not needed (the registration flow will remain the same in the existing realms). So nothing more needed for that part.

Just one more idea from me. Maybe it's recommendable to add some documentation about this. I think a good point would be after [Enabling user regitration](https://www.keycloak.org/docs/latest/server_admin/#proc-enabling-user-registration_server_administration_guide) in the [admin guide](https://github.com/keycloak/keycloak/tree/main/docs/documentation/server_admin/). Adding one more topic like `Require user to agree to 'terms and conditions' during registration`. And you just comment the same you did here in the issue. WDYT?

2023-05-31 15:51 UTC, rmartinc commented
@reda-alaoui The code is OK to me now, but what do you think about the documentation? Do you want to add the new topic for the doc? We can do it in a follow-up issue if you don't want to be involved with doc changes...

2023-05-31 15:56 UTC, rmartinc commented
@reda-alaoui Thanks! Take all the time you need, I was not rushing you to do it.

2023-06-06 20:53 UTC, reda-alaoui commented
@rmartinc , documentation added :+1:

2023-06-07 12:38 UTC, pedroigor submitted a review, later dismissed
LGTM

2023-06-07 13:19 UTC, rmartinc approved these changes, later dismissed
Thanks @reda-alaoui ! LGTM too! I'm adding @andymunro for the documentation changes.

2023-06-07 14:59 UTC, andymunro commented on docs/documentation/server_admin/topics/users/proc-requiring-tac-agreement-at-registration.adoc
> +You can condition a user registration to his agreement to your terms and conditions.
```suggestion
For a user to register, you can require agreement to your terms and conditions.
```

2023-06-07 14:59 UTC, andymunro commented on docs/documentation/server_admin/topics/users/proc-requiring-tac-agreement-at-registration.adoc
> +* Terms and conditions required action is enabled
```suggestion
* Terms and conditions required action is enabled.
```

2023-06-07 15:01 UTC, andymunro requested changes
Looks good, @pedroigor.  Just one change to suggest.

2023-06-08 09:11 UTC, rmartinc approved these changes
@pedroigor This seems to be ready! Thanks a lot @reda-alaoui!

2023-06-08 13:37 UTC, pedroigor approved these changes

2023-06-08 13:39 UTC, merged

2023-06-08 13:39 UTC, pedroigor commented
@reda-alaoui Thanks. nice addition.

2023-10-02 12:10 UTC, danieliu456 commented
@reda-alaoui 

Is there any possibility to set user attributes when the user accepts terms and conditions with this new flow? 
Or did I misunderstand something? Because I can't see any attributes on the user after testing this functionality?

P.S. @reda-alaoui Thank you for this awesome feature and contribution! <3

Old flow: 
```java
    @Override
    public void processAction(RequiredActionContext context) {
        // Keycloak 21.0.0 changed the user attribute name from lowercase to uppercase
        // this change was reverted, but it is still possible some attributes created
        // in Keycloak 21.0.0 will be present in the database, we need to remove it too.
        // See https://github.com/keycloak/keycloak/issues/17277 for more details
        context.getUser().removeAttribute(USER_ATTRIBUTE.toUpperCase());

        if (context.getHttpRequest().getDecodedFormParameters().containsKey("cancel")) {
            context.getUser().removeAttribute(USER_ATTRIBUTE);
            context.failure();
            return;
        }

        context.getUser().setAttribute(USER_ATTRIBUTE, Arrays.asList(Integer.toString(Time.currentTime())));

        context.success();
    }
```

New:
```java
	@Override
	public void success(FormContext context) {

	}
```