KEYCLOAK-17853 Multiple regular expression password policy support
keycloak/keycloak pull request #7959
Opened 2021-04-23 11:03 UTC by y-tabata

JIRA: https://issues.redhat.com/browse/KEYCLOAK-17853

# Implementation
The regular expression password policy is stored not in the existing policy config Map but in the new Set only for the regular expression password policy.

2023-05-17 17:06 UTC, mposolda commented
@y-tabata Sorry for late review. Your PR looks good.

Are you please able to rebase your PR on top of latest Keycloak main? Also to check if it works as expected with the new admin console and that multiple regexes can be configurable?

2023-05-19 02:38 UTC, y-tabata commented
@mposolda 
Thanks for your review.
I recheck my pull request and we're thinking that it's better to use the isMultiplSupported flag so we reimplement this.

https://github.com/keycloak/keycloak/blob/main/server-spi-private/src/main/java/org/keycloak/policy/RegexPatternsPasswordPolicyProviderFactory.java#L65-L67

2023-05-31 08:50 UTC, jonkoops requested changes
There are some linting errors on the front-end that need to be resolved.

2023-06-12 10:22 UTC, jonkoops commented
@y-tabata are you still interested in landing this?

2023-06-19 09:37 UTC, jonkoops commented
Closing this PR due to lack of response from the author. Feel free to let us know it there is renewed interest in landing this.

2023-06-19 09:37 UTC, closed without merging