KEYCLOAK-12988 Deprecate getUsers methods from UserProvider and UserQueryProvider
keycloak/keycloak pull request #7972
Opened 2021-04-27 07:38 UTC by mhajas

This PR deprecates all methods starting with `getUsers*` in all user interfaces. These methods were used only in a few places, that are replaced by `searchUser*` variants of methods. 

The only difference I found is, that `search` variants of methods in current JPA are using `getUserById` at the end of method so that found users are cached and also import validation is done. While `getUsers` methods didn't do that. This was causing some failures in LDAP tests that are fixed in separate commit. When approved I will squash.

2021-04-30 09:03 UTC, martin-kanis requested changes
@mhajas Thanks for the PR. Please see my comments/questions.

2021-05-12 09:08 UTC, hmlnarik commented on server-spi/src/main/java/org/keycloak/models/UserProvider.java
> -        Stream<UserModel> getUsersStream(RealmModel realm, Integer firstResult, Integer maxResults, boolean includeServiceAccounts);
The last one (`Stream<UserModel> getUsersStream(RealmModel realm, Integer firstResult, Integer maxResults, boolean includeServiceAccounts);`) should remain and become deprecated, others are inherited.

2021-05-12 09:13 UTC, hmlnarik commented on testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/testsuite/federation/BackwardsCompatibilityUserStorage.java
> -
This should remain here.

2021-05-12 11:45 UTC, mhajas commented on server-spi/src/main/java/org/keycloak/models/UserProvider.java
> -        Stream<UserModel> getUsersStream(RealmModel realm, Integer firstResult, Integer maxResults, boolean includeServiceAccounts);
I think we can remove all of them as all of them has a default method in the parent. The Stream interface was there only to switch methods that need to be implemented by implementors. Now after this PR none of these methods need to be implemented as they are replaced by search* methods by default.

2021-05-12 11:47 UTC, mhajas commented on services/src/main/java/org/keycloak/exportimport/util/ExportUtils.java
> +            List<UserRepresentation> users = session.users().searchForUserStream(realm, Collections.emptyMap())
yes, unless we set includeServiceAccount to false, we return all user entities.

2021-06-28 12:15 UTC, martin-kanis submitted a review, later dismissed
Thanks Michal. LGTM

2022-09-06 07:56 UTC, ahus1 approved these changes
I reviewed the code and also the previous comments. Thanks for this PR and cleaning up!

2022-09-06 08:38 UTC, hmlnarik approved these changes
Thanks for the PR!

2022-09-06 08:38 UTC, merged