KEYCLOAK-17887 fix PATCH endpoint for realm localization
keycloak/keycloak pull request #7974
Opened 2021-04-27 15:12 UTC by danielFesenmeyer

UnsupportedOperationException was thrown because RealmAdapter tried to change unmodifiable map. Fixed this by removing unnecessary line of code.

To prevent regression, I added tests for the PATCH endpoint.

2021-06-04 10:39 UTC, stianst requested changes
I appreciate that PATCH should be used in this case, but we don't use it anywhere else in the Admin APIs, so this would be rather inconsistent with other things.

What we do instead is somewhat implement patch as part of the post, which I appreciate is quite broken, but think that's what we should do here as well to make it consistent with other endpoints.

2021-06-14 13:35 UTC, danielFesenmeyer commented
> I appreciate that PATCH should be used in this case, but we don't use it anywhere else in the Admin APIs, so this would be rather inconsistent with other things.
> 
> What we do instead is somewhat implement patch as part of the post, which I appreciate is quite broken, but think that's what we should do here as well to make it consistent with other endpoints.

Ok, I can change the corresponding endpoints to POST. Is it ok that this breaks the API, or should the PATCH endpoints be kept for backwards compatibility?

2021-06-21 09:25 UTC, danielFesenmeyer commented
> > I appreciate that PATCH should be used in this case, but we don't use it anywhere else in the Admin APIs, so this would be rather inconsistent with other things.
> > What we do instead is somewhat implement patch as part of the post, which I appreciate is quite broken, but think that's what we should do here as well to make it consistent with other endpoints.
> 
> Ok, I can change the corresponding endpoints to POST. Is it ok that this breaks the API, or should the PATCH endpoints be kept for backwards compatibility?

@stianst WDYT?

2021-08-02 10:55 UTC, danielFesenmeyer commented
I have changed the implementation to use POST instead of PATCH. I also renamed RealmModel#patchRealmLocalizationTexts to #createOrUpdateRealmLocalizationTexts, in order to avoid confusion.

I didn't add any code for backwards compatibility, because the endpoint was undocumented anyway (not in org.keycloak.admin.client.resource.RealmLocalizationResource). Please let be me know if you think that backwards compatibility is needed.

2021-09-30 06:31 UTC, stianst approved these changes

2021-09-30 06:43 UTC, stianst commented
Rebased here: https://github.com/keycloak/keycloak/pull/8509

2021-09-30 13:08 UTC, stianst commented
Merged in https://github.com/keycloak/keycloak/pull/8509

2021-09-30 13:08 UTC, closed without merging