KEYCLOAK-17995 Add a warning to standalone migration scripts to perfo…
keycloak/keycloak pull request #7997
Opened 2021-05-05 10:31 UTC by mhajas

…rm a manual migration script if needed + fix test failures when migrating from 9.0.3

2021-05-05 14:46 UTC, hmlnarik requested changes

2021-05-05 14:46 UTC, hmlnarik commented on distribution/feature-packs/server-feature-pack/src/main/resources/content/bin/migrate-standalone-ha.cli
> +echo
Please consider a different wording:
```suggestion
echo
echo *** WARNING ***
echo
echo ** If the following embed-server command fails, manual intervention is needed.
echo ** In such case, remove any <extension> and <subsystem> declarations referring
echo ** to the removed smallrye modules from the standalone-ha.xml file and rerun this script.
echo ** For details, see Migration Changes section in the Upgrading guide.
echo ** We apologize for this inconvenience.
echo
```
Same comment (with alteration of the file name) applies to `migrate-standalone.cli` below as well.

2021-05-05 15:33 UTC, mhajas commented
@hmlnarik Thank you, I updated.

2021-05-05 15:55 UTC, hmlnarik commented on distribution/feature-packs/server-feature-pack/src/main/resources/content/bin/migrate-standalone.cli
> +echo ** to the removed smallrye modules from the standalone-ha.xml file and rerun this script.
```suggestion
echo ** to the removed smallrye modules from the standalone.xml file and rerun this script.
```

2021-05-06 06:57 UTC, hmlnarik approved these changes

2021-05-06 09:40 UTC, merged