KEYCLOAK-17936 FAPI-CIBA : support Signed Authentication Request
keycloak/keycloak pull request #8006
Opened 2021-05-06 04:08 UTC by tnorimat

This PR is for [KEYCLOAK-11846 OpenID Connect Financial-grade API: Client Initiated Backchannel Authentication Profile](https://issues.redhat.com/browse/KEYCLOAK-11846), also is the part of the project [FAPI-CIBA(poll mode)](https://github.com/keycloak/kc-sig-fapi/projects) of [FAPI-SIG](https://github.com/keycloak/kc-sig-fapi) activity.

Based on the merged [OIDC CIBA](https://github.com/keycloak/keycloak/pull/7679) feature, this PR provides additional feature to satisfy [FAPI-CIBA(poll mode) security profile](https://bitbucket.org/openid/fapi/src/master/Financial_API_WD_CIBA.md).

2021-05-06 04:11 UTC, tnorimat commented
@mposolda This PR is for supporting FAPI-CIBA security profile support based on the merged OIDC CIBA feature as mentioned in [the 17th FAPI-SIG meeting](https://github.com/keycloak/kc-sig-fapi/blob/master/FAPI-SIG/meetings/17th/presentations/FAPI-SIG_17th_MTG_agenda.pdf). Could you or your team review it?

2021-06-24 16:16 UTC, mposolda requested changes
@tnorimat Thanks for the PR!

I've added one inline comment regarding signature algorithms. Also I have few other comments:

- It will be nice that ClientPolicyExecutor `SecureRequestObjectExecutor` is triggered somehow for the CIBA Authentication  request. Similarly `SecureSigningAlgorithmExecutor` (or other executor) will be probably nice to be triggered to makes sure that for the FAPI, the secured algorithms are used. But I am not sure whether to integrate with client policies here or in separate PR. Maybe it makes sense to rather use separate PR for this? As I suppose it will require to have the CIBA Authorization request event available as the type of `ClientPolicyEvent`, which is not yet available.

2021-06-25 02:00 UTC, tnorimat commented
@mposolda 

As you said in https://github.com/keycloak/keycloak/pull/8006#pullrequestreview-691877966 , I've been preparing the PR extending client policies to treat requests on Backchannel Authentication Endpoint.

Also, I've been preparing the PR extending some existing executors to meet the requirements by [FAPI-CIBA](https://bitbucket.org/openid/fapi/src/master/Financial_API_WD_CIBA.md) .

Therefore, I would like to work as follows.

1. Revising this PR.
2. After (1)'s PR is merged, implementing PR for extending client policies to treat requests on Backchannel Authentication Endpoint based on (1)'s PR.
3. After (2)'s PR is merged, implementing PR for extending some existing executors to meet the requirements by FAPI-CIBA based on (1) and (2)'s PR 

WDYT?

2021-06-25 02:07 UTC, tnorimat commented on testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/OIDCWellKnownProviderTest.java
> +            Assert.assertNames(oidcConfig.getBackchannelAuthenticationRequestSigningAlgValuesSupported(), "none", Algorithm.PS256, Algorithm.PS384, Algorithm.PS512, Algorithm.RS256, Algorithm.RS384,
@mposolda Yes, that's right.
I would like to revise this PR as follows.
- `none` is not allowed. keycloak returns an error if CD(client) sends backchannel authentication requests with not signed authentication request.
- ES*, PS* and RS* are allowed. keycloak returns an error if CD(client) sends backchannel authentication requests with signed authentication request by HS*.
- add arquillian integration tests to check the things just mentioned above.

By the way, [FAPI-CIBA](https://bitbucket.org/openid/fapi/src/master/Financial_API_WD_CIBA.md#markdown-header-710-algorithm-considerations) does not allow RS*. I would like to implement the PR for extending some existing executors to meet the requirements by FAPI-CIBA.

2021-06-25 03:02 UTC, tnorimat commented
@mposolda
Aside from it, how about treating requests on Device Authorization Endpoint? If you agree with it, I would like to implement PR for it.

2021-06-25 07:23 UTC, mposolda commented on testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/OIDCWellKnownProviderTest.java
> +            Assert.assertNames(oidcConfig.getBackchannelAuthenticationRequestSigningAlgValuesSupported(), "none", Algorithm.PS256, Algorithm.PS384, Algorithm.PS512, Algorithm.RS256, Algorithm.RS384,
+1 to everything you mentioned in the last paragraph. We can allow RS* by default, but reject it with the client policy executor similarly like we're doing for other use-cases where RS* is rejected by the executor.

2021-06-25 07:24 UTC, mposolda commented
+1 to the stages you proposed here. Also +1 for the Device Authorization Endpoint

2021-06-28 14:29 UTC, mposolda commented
@tnorimat I've opened the pull request https://github.com/Hitachi/keycloak/pull/3 to update this pull request. I've added method "isAsymmetricAlgorithm" on SignatureProvider class to be able to filter algorithms programatically instead of having hardcoded filtering of concrete provider. Hardcoded filtering may not reliably work for example for the case if someone adds new symmetric algorithm providers in the future etc. If you are fine with this, feel free to merge my PR to your branch (which should effectively update this PR against Keycloak master)

2021-06-28 22:10 UTC, tnorimat commented
@mposolda Thank you. I've merged your PR into this PR. Could you check it?

2021-06-29 06:07 UTC, mposolda approved these changes
@tnorimat Thanks!

2021-06-29 06:07 UTC, merged

2021-06-29 06:12 UTC, mposolda commented
@tnorimat FYI. I've created one minor follow-up JIRA https://issues.redhat.com/browse/KEYCLOAK-18583 . Figured that there is this unused method, which I forgot to remove in my PR...

2021-06-29 06:29 UTC, tnorimat commented
@mposolda I'll work on https://issues.redhat.com/browse/KEYCLOAK-18583 as soon as possible.

2021-06-29 09:10 UTC, mposolda commented
@tnorimat Thanks! FYI. I've also created https://issues.redhat.com/browse/KEYCLOAK-18587 . Please let me know what do you think about it and if my understanding of the specification and description of the JIRA is correct.

2021-06-29 23:15 UTC, tnorimat commented
@mposolda I would like to check and work on https://issues.redhat.com/browse/KEYCLOAK-18587 and https://issues.redhat.com/browse/KEYCLOAK-18588 .