KEYCLOAK-18073 avoid ModelDuplicateException during parallel starup o…
keycloak/keycloak pull request #8088
Opened 2021-05-25 13:07 UTC by vramik

…f servers

2021-05-26 08:59 UTC, hmlnarik requested changes
Thank you @vramik! Oveall looks good, the only requested change is in naming the db lock, as it has nothing to do with map. Have you considered placing this implementation into server-spi-private module?

2021-05-26 08:59 UTC, hmlnarik commented on model/map/src/main/java/org/keycloak/models/map/dblock/NoLockingDBLockProviderFactory.java
> +    public static final String PROVIDER_ID = "map";
```suggestion
    public static final String PROVIDER_ID = "none";
```

2021-05-26 08:59 UTC, hmlnarik commented on testsuite/integration-arquillian/tests/base/pom.xml
> +                                <keycloak.dblock.provider>map</keycloak.dblock.provider>
```suggestion
                                <keycloak.dblock.provider>none</keycloak.dblock.provider>
```

2021-05-26 11:12 UTC, vramik commented
https://master-jenkins/job/universal-test-pipeline-server/443

2021-05-27 05:10 UTC, hmlnarik approved these changes
Thank you for your contribution!

2021-05-27 05:10 UTC, merged