KEYCLOAK-18390 GroupProvider search implementation of JPA and Map del…
keycloak/keycloak pull request #8141
Opened 2021-06-09 12:38 UTC by srose

Group search behaves differently between JPA and Map implementation.

With the change the root nodes are delivered by the Map impl, the same way as it is done on JPA impl.

2021-06-14 11:57 UTC, mhajas requested changes
Thank you for the PR @srose, this is indeed something that needs fixing. I added two comments into the code.

Also, could you please update the JavaDoc of the method in the GroupLookupProvider interface?
https://github.com/keycloak/keycloak/blob/74089a51b3503b8e68a62ff954a68f3499cd44ec/server-spi/src/main/java/org/keycloak/storage/group/GroupLookupProvider.java#L53-L60

2021-06-28 06:42 UTC, hmlnarik commented
@srose Thank you for the PR. Would you have time to address the review comments?

2021-06-28 09:10 UTC, srose commented on testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/group/GroupTest.java
> +        Assert.assertEquals(expectedResult.getName(), groups.get(0).getName());
will do, good catch

2021-06-28 09:11 UTC, srose commented on model/map/src/main/java/org/keycloak/models/map/group/MapGroupProvider.java
> +        return closing(groups.map(id -> {
you are right

2021-06-28 12:14 UTC, mhajas requested changes
@srose Thank you for the changes. The code looks good now. Just please remove the Retry CI commit. There are some failures in the CI that we know about and are unrelated to your changes.

2021-06-28 12:24 UTC, srose commented
> @srose Thank you for the changes. The code looks good now. Just please remove the Retry CI commit. There are some failures in the CI that we know about and are unrelated to your changes.

Thanks for your review, Commit removed

2021-06-29 12:56 UTC, mhajas approved these changes

2021-06-29 12:58 UTC, hmlnarik approved these changes
Approving based on @mhajas's approval

2021-06-29 12:59 UTC, merged