Update messages_cs.properties
keycloak/keycloak pull request #8159
Opened 2021-06-14 13:04 UTC by McLaynV

Czech translations for base login theme

2021-07-25 19:20 UTC, dklika commented on themes/src/main/resources-community/theme/base/login/messages/messages_cs.properties
> +doTryAgain=Zkusti znovu
```suggestion
doTryAgain=Zkusit znovu
```

2021-07-25 19:20 UTC, dklika commented on themes/src/main/resources-community/theme/base/login/messages/messages_cs.properties
>  termsText=<p>Smluvní podmínky, které se mají definovat</p>
```suggestion
termsText=<p>Smluvní podmínky k odsouhlasení</p>
```

2021-07-25 19:20 UTC, dklika commented on themes/src/main/resources-community/theme/base/login/messages/messages_cs.properties
> +termsPlainText=Smluvní podmínky, které se mají definovat.
```suggestion
termsPlainText=Smluvní podmínky k odsouhlasení.
```

2021-07-28 08:20 UTC, McLaynV commented
@hmlnarik you had some commits in this file (czech translation) in the past. Could you please review or merge this?

2021-07-28 08:50 UTC, hmlnarik requested changes
@McLaynV Thank you for the PR.
@dklika Thank you for the review.
Could you please introduce a JIRA, address the inline comments and squash the commits into a single one?

2021-07-28 08:50 UTC, hmlnarik commented on themes/src/main/resources-community/theme/base/login/messages/messages_cs.properties
> +phoneNumberVerified=Telefoní číslo ověřeno
```suggestion
phoneNumber=Telefonní číslo
phoneNumberVerified=Telefonní číslo ověřeno
```

2021-07-28 08:50 UTC, hmlnarik commented on themes/src/main/resources-community/theme/base/login/messages/messages_cs.properties
> +profileScopeConsentText=Úživatelský profil
```suggestion
profileScopeConsentText=Uživatelský profil
```

2021-07-28 08:50 UTC, hmlnarik commented on themes/src/main/resources-community/theme/base/login/messages/messages_cs.properties
> +logoutOtherSessions=Odhlásit se na ostatních zařízeních
```suggestion
logoutOtherSessions=Odhlásit se z ostatních zařízení
```

2021-07-28 08:50 UTC, hmlnarik commented on themes/src/main/resources-community/theme/base/login/messages/messages_cs.properties
> +phoneScopeConsentText=Telefoní číslo
```suggestion
phoneScopeConsentText=Telefonní číslo
```

2021-07-28 08:50 UTC, hmlnarik commented on themes/src/main/resources-community/theme/base/login/messages/messages_cs.properties
> +addressScopeConsentText=Addresa
```suggestion
addressScopeConsentText=Adresa
```

2021-07-28 08:50 UTC, hmlnarik commented on themes/src/main/resources-community/theme/base/login/messages/messages_cs.properties
> +loginTotpIntro=You need to set up a One Time Password generator to access this account
Please translate

2021-07-28 08:50 UTC, hmlnarik commented on themes/src/main/resources-community/theme/base/login/messages/messages_cs.properties
> +emailScopeConsentText=Emailová adresa
```suggestion
emailScopeConsentText=E-mailová adresa
```

2021-07-28 08:50 UTC, hmlnarik commented on themes/src/main/resources-community/theme/base/login/messages/messages_cs.properties
> +client_account-console=Uživatelská Console
```suggestion
client_account-console=Uživatelská konzola
```

2021-07-28 08:50 UTC, hmlnarik commented on themes/src/main/resources-community/theme/base/login/messages/messages_cs.properties
> +delegationCompleteMessage=Můžete zavřít toto okno prohlížeče a vrátit se do konzolové aplikace.
```suggestion
delegationCompleteMessage=Můžete zavřít toto okno prohlížeče a vrátit se do aplikace.
```

2021-07-28 08:50 UTC, hmlnarik commented on themes/src/main/resources-community/theme/base/login/messages/messages_cs.properties
> +delegationFailedMessage=Můžete zavřít toto okno prohlížeče a vrátit se do konzolové aplikace a zkusit se znovu přihlásit.
```suggestion
delegationFailedMessage=Můžete zavřít toto okno prohlížeče a vrátit se do aplikace a zkusit se znovu přihlásit.
```

2021-07-28 08:50 UTC, hmlnarik commented on themes/src/main/resources-community/theme/base/login/messages/messages_cs.properties
> +invalidPasswordNotEmailMessage=Neplatné heslo: nesmí být totožné s emailovou adresou.
```suggestion
invalidPasswordNotEmailMessage=Neplatné heslo: nesmí být totožné s e-mailovou adresou.
```

2021-07-28 08:50 UTC, hmlnarik commented on themes/src/main/resources-community/theme/base/login/messages/messages_cs.properties
> +finalDeletionConfirmation=Pokud svůj účet odstraníte, nemůže být obnoven. Pro zachování účtu klikněte na Storno.
```suggestion
finalDeletionConfirmation=Pokud svůj účet odstraníte, nemůže být obnoven. Pro zachování účtu klikněte na tlačítko Zrušit.
```

2021-07-28 08:50 UTC, hmlnarik commented on themes/src/main/resources-community/theme/base/login/messages/messages_cs.properties
> +webauthn-error-user-not-found=Neznámý uživatel přihlášen pomocí bezpečnostního kíče.
```suggestion
webauthn-error-user-not-found=Neznámý uživatel přihlášen pomocí bezpečnostního klíče.
```

2021-07-28 13:41 UTC, hmlnarik commented
Thank you @McLaynV
One last thing is to prefix the commit message with Keycloak JIRA, i.e. `KEYCLOAK-18913 Update messages_cs.properties`, could you please update it?

2021-07-29 09:24 UTC, McLaynV commented
Hello @hmlnarik 
I changed the commit name as you suggested.

2021-07-29 09:46 UTC, hmlnarik approved these changes

2021-07-29 09:47 UTC, hmlnarik commented
@McLaynV Thank you!

2021-07-29 10:58 UTC, stianst approved these changes

2021-07-29 19:18 UTC, merged