KEYCLOAK-11570 SocketTimeoutException in windows adapter tests
keycloak/keycloak pull request #8175
Opened 2021-06-17 17:09 UTC by mabartos

JIRA: [KEYCLOAK-11570](https://issues.redhat.com/browse/KEYCLOAK-11570)

PR for pipeline: https://KEYCLOAK-GITLAB.com/keycloak/keycloak-pipeline/-/merge_requests/48
Pipeline tests passed: https://master-jenkins.com/job/universal-test-pipeline-adapters/473/

The HTTP client builder is the same for OIDC and SAML adapters, but these modules are separated, therefore the duplicate code is present. It'd be great to find another way, how to do it, but it's out of scope of this PR.

@miquelsi @pdrozd @mhajas  Could you please review it? Thanks.

2021-06-18 06:48 UTC, miquelsi approved these changes

2021-06-21 10:45 UTC, mhajas requested changes
Thank you for the PR @mabartos. Isn't this just another approach to: https://github.com/keycloak/keycloak/pull/8165? Also, what change fixes the SocketTimeoutException? I don't see where we are changing the system properties.

2021-06-22 09:49 UTC, mabartos commented on adapters/oidc/adapter-core/src/main/java/org/keycloak/adapters/HttpClientBuilder.java
> +        log.warnf("Cannot find system property '%s'", propertyName);
Agree

2021-06-22 09:50 UTC, mabartos commented on adapters/oidc/adapter-core/src/main/java/org/keycloak/adapters/HttpClientBuilder.java
> +        String property = System.getProperty(propertyName, "");
+1

2021-06-22 09:50 UTC, mabartos commented on adapters/oidc/adapter-core/src/main/java/org/keycloak/adapters/HttpClientBuilder.java
> +                Long socketTimeoutProperty = getLongSystemProperty(SOCKET_TIMEOUT_PROPERTY);
You're right. Same like [this](https://github.com/keycloak/keycloak/pull/8165#discussion_r655364248).

2021-06-22 10:00 UTC, mabartos commented
@mhajas Thanks for your review.

Yeah, it's quite similar approach, but not so comprehensive as #8165. The best approach how to solve it will be discussed [here](https://groups.google.com/g/keycloak-dev/c/HLLo9wk0dSI).

2021-06-24 07:35 UTC, mabartos commented
I'm closing this PR after discussion [here](https://groups.google.com/g/keycloak-dev/c/HLLo9wk0dSI/m/aVUKlWfOAQAJ?utm_medium=email&utm_source=footer).

2021-06-24 07:35 UTC, closed without merging