KEYCLOAK-18467 support unicode for realm localization texts
keycloak/keycloak pull request #8195
Opened 2021-06-23 08:21 UTC by danielFesenmeyer

This PR adds unicode support for realm localization texts (see KEYCLOAK-18467):
- it changes the datatype of the database column REALM_LOCALIZATIONS.TEXTS to NCLOB (instead of CLOB)
- adds the Hibernate @Nationalized annotation to the corresponding java entity field

2021-06-30 19:58 UTC, vramik requested changes
Thank you @danielFesenmeyer for the PR, I've did just quick look I've 2 things so far. Could you take a look at those? 

First there is missing test, I suggest to add it to https://github.com/keycloak/keycloak/tree/master/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/i18n

Second please see inline.

2021-06-30 19:58 UTC, vramik commented on model/jpa/src/main/resources/META-INF/jpa-changelog-15.0.0.xml
> +        <sql>UPDATE REALM_LOCALIZATIONS SET TEXTS_NEW = TEXTS</sql>
This line doesn't take into account a different than default schema. Can be `<update>` used instead?

2021-07-01 16:22 UTC, danielFesenmeyer commented
@vramik Thanks for the review :) I've adjusted the PR according to your suggestions. (Also rebased on master.)

2021-07-14 22:24 UTC, vramik approved these changes
@danielFesenmeyer thank you!

https://master-jenkins/job/universal-test-pipeline-server/617/

2021-07-15 08:30 UTC, hmlnarik approved these changes
Approving based on @vramik's approval

2021-07-15 08:30 UTC, merged