[KEYCLOAK-18591] - Support a dynamic IDP user review form
keycloak/keycloak pull request #8247
Opened 2021-07-08 11:08 UTC by velias

Few notes:
* new template `idp-review-user-profile.ftl` added
* added calls to UserProfile SPI for profile validation when profile review action is configured to "when missing" (legacy profile validation code removed)
* added calls to UserProfile SPI to create user from IDP data. When profile review is disable then direct user creation is still performed as profile may be invalid so UserProfile SPI can't create user.
* tons of tests added to cover dynamic functionality (some existing tests improved to assert that values entered into review form are really used)

2021-07-08 14:35 UTC, pedroigor requested changes
@velias We should keep here only changes to make idp review dynamic. We should be discussing a separate template for idp review first and probably have a follow up.

It should make this PR much simpler.

2021-07-09 08:14 UTC, velias commented
@pedroigor thanks for the review, separate template removed

2021-07-09 13:01 UTC, pedroigor commented on server-spi-private/src/main/java/org/keycloak/forms/login/LoginFormsPages.java
> +    LOGIN_OAUTH2_DEVICE_VERIFY_USER_CODE, UPDATE_USER_PROFILE, IDP_REVIEW_USER_PROFILE;
Nice, that should help if we decide for an additional template specific for this flow.

2021-07-09 13:05 UTC, pedroigor approved these changes

2021-07-09 13:05 UTC, merged