Update undertow-core
keycloak/keycloak pull request #8259
Opened 2021-07-12 14:34 UTC by abstractj

2021-07-12 15:45 UTC, vmuzikar approved these changes

2021-07-12 19:18 UTC, sguilhen approved these changes

2021-07-13 07:58 UTC, hmlnarik requested changes
@abstractj What is the reason for updating undertow-core component? The undertow-core should be on par with wildfly's version which is currently 2.2.5.Final.

2021-07-13 09:14 UTC, iankko reviewed
@abstractj The change LGTM, but +1 on @hmlnarik 's concern / comment.

Can you possibly explain the motivation behind the bump a bit more further? Is there some change / regression fix [between `2.2.5` and `2.2.8` versions](https://github.com/undertow-io/undertow/compare/2.2.5.Final...2.2.8.Final), that's crucial enough to break the previously used customs?

Thanks,
Jan

2021-07-13 13:44 UTC, abstractj commented
The upgrade should wait for the next WildFly release, I'm closing it for now.

2021-07-13 13:44 UTC, closed without merging