KEYCLOAK-18824 Simplify MapStorageTransaction and move registerEntityForChanges to CHM transaction
keycloak/keycloak pull request #8276
Opened 2021-07-17 14:30 UTC by hmlnarik

This PR contains #8272 to prevent merging conflicts

2021-07-20 12:42 UTC, mhajas reviewed
Thank you for the changes @hmlnarik. The idea of adding registering entity into the transaction totally makes sense! We probably won't be able to have unregistered entity from the JPA anyway, so it doesn't make sense to have this concept in the providers.

I looked much closer on users, groups and authorization than on other areas. I assumed @vramik and @martin-kanis to look at others closer.

I added few comments into the code, but in general it looks good.

2021-07-20 12:42 UTC, mhajas commented on model/map/src/main/java/org/keycloak/models/map/user/MapUserProvider.java
> +        MapUserEntity<K> userEntity = usersWithEmail.get(0);
Please refactor this method to use `entityToAdapterFunc` on line 539.

2021-07-20 12:42 UTC, mhajas commented on model/map/src/main/java/org/keycloak/models/map/user/MapUserProvider.java
> +        tx.create(entity);
It seems that on this line we had `entity =` after the first commit and then the second commit removed it. Should `entity =` remain there?

2021-07-20 12:42 UTC, mhajas commented on model/map/src/main/java/org/keycloak/models/map/authorization/MapPermissionTicketStore.java
> +        tx.create(entity);
the same

2021-07-20 12:42 UTC, mhajas commented on model/map/src/main/java/org/keycloak/models/map/authorization/MapPolicyStore.java
> +        tx.create(entity);
the same

2021-07-20 12:42 UTC, mhajas commented on model/map/src/main/java/org/keycloak/models/map/authorization/MapResourceServerStore.java
> +        tx.create(entity);
the same

2021-07-20 12:42 UTC, mhajas commented on model/map/src/main/java/org/keycloak/models/map/authorization/MapResourceStore.java
> +        tx.create(entity);
the same

2021-07-20 12:42 UTC, mhajas commented on model/map/src/main/java/org/keycloak/models/map/authorization/MapScopeStore.java
> +        tx.create(entity);
the same

2021-07-20 20:06 UTC, hmlnarik commented
@mhajas Thanks for the review. Could you please re-review?

2021-07-21 07:31 UTC, vramik reviewed
Thank you @hmlnarik for the PR, it looks great. I've just two comments regarding javadoc.

2021-07-21 07:31 UTC, vramik commented on model/map/src/main/java/org/keycloak/models/map/storage/chm/ConcurrentHashMapKeycloakTransaction.java
> +     * @param <K>
Parameter K is not used here.

2021-07-21 07:39 UTC, mhajas approved these changes, later dismissed
Thanks for the changes @hmlnarik. Approved

2021-07-21 12:39 UTC, martin-kanis requested changes

2021-07-21 14:46 UTC, vramik approved these changes
Thank you @hmlnarik

2021-07-21 15:11 UTC, martin-kanis approved these changes
Thanks @hmlnarik

2021-07-21 18:58 UTC, merged