KEYCLOAK-18918 - clientSession.setTimesteamp() must NOT be executed during Introspection
keycloak/keycloak pull request #8344
Opened 2021-08-04 12:44 UTC by mterrade

KEYCLOAK-18918 - clientSession.setTimesteamp() must NOT be executed during Introspection. 
**If executed, on the next refresh, the refresh token will appear as 'stale token' and trigger error.**

Bug introduced in 1.13, in this commit : https://github.com/keycloak/keycloak/commit/515bfb5064fc2552e521c302507a29b9962f1d81#diff-fd8b1c47da5ec7ee42d5450d3f7b73cdeef9c08af26b825c9245e3e6052c5cdf

2021-08-04 13:45 UTC, mposolda approved these changes
@mterrade Thanks for the fix

2021-08-04 14:13 UTC, martin-kanis approved these changes

2021-08-05 08:37 UTC, mposolda requested changes
Changing "Approve" to "Request changes" due the regression in the OpenshiftTokenReviewTest for the map storage. See JIRA for more details.

2021-08-05 08:47 UTC, hmlnarik requested changes
Please see JIRA, there are many changes

2021-08-06 07:01 UTC, hmlnarik commented
Thank you for the PR. Specifically this behaviour has been fixed and tested in #8349, hence closing this PR as duplicate.

2021-08-06 07:01 UTC, closed without merging