KEYCLOAK-18873 href attribute of a "Unable to scan?" tag is wrong in …
keycloak/keycloak pull request #8351
Opened 2021-08-06 10:02 UTC by ch219318

href attribute of a "Unable to scan?" tag is wrong in "configure OTP" page.

2021-08-06 10:07 UTC, ch219318 commented
@mabartos 
@stianst 
please review

2021-08-22 20:41 UTC, thomasdarimont commented
@ch219318 this looks good to me, would you mind rebasing this again?

2021-08-23 01:43 UTC, ch219318 commented
@thomasdarimont ok.I will rebase it

2021-08-23 02:44 UTC, ch219318 commented
@thomasdarimont I have rebased.

2021-08-31 09:21 UTC, mabartos requested changes
Thanks @ch219318 for the PR! LGTM, just one nitpick. It won't be hard to edit that.

2021-09-01 02:38 UTC, ch219318 commented on testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/RequiredActionPriorityTest.java
> +import static org.junit.Assert.assertTrue;
ok

2021-09-01 11:10 UTC, mabartos approved these changes
LGTM!

2021-09-20 08:09 UTC, mposolda approved these changes
@ch219318 @thomasdarimont @mabartos Thanks all for this PR and for the review!

2021-09-20 08:09 UTC, merged