Update LDAPOperationManager.java
keycloak/keycloak pull request #8353
Opened 2021-08-06 17:13 UTC by pravsjv

2021-08-09 17:20 UTC, pravsjv commented
Hi Team, Can someone review this.

2021-08-13 17:52 UTC, pravsjv commented
Team, can someone have a look and review the changes.

2021-08-16 13:55 UTC, pravsjv commented
Adding the JIRA for more description of the issue.
https://issues.redhat.com/browse/KEYCLOAK-18942

2021-08-20 20:26 UTC, mvk37 commented
Useful bug fixing. If credential couldn't be validated because of connection problem to a backend  brute-force shouldn't count them.

2021-09-13 16:09 UTC, mvk37 approved these changes, later dismissed

2021-10-04 14:48 UTC, mposolda requested changes
@pravsjv Thanks for the PR! Few points:
- Added one minor inline point for the formatting
- Can you rebase this PR when you address the point? This will allow easier review.
- Can you please add the JIRA number to the commit message? See other messages sent to Keycloak repository for the details.

2021-10-04 14:48 UTC, mposolda commented on federation/ldap/src/main/java/org/keycloak/storage/ldap/idm/store/ldap/LDAPOperationManager.java
> +        } catch(RuntimeException re){
Minor: Is it possible to use spaces in formatting like:
```
} catch (RuntimeException re) {
```
and
```
if (log.isDebugEnabled()) {
```

2021-11-16 14:09 UTC, mposolda commented
@pravsjv The PR looks good, but we will need to run the build and I am not able to re-run the build right now. Is it fine for you to rebase this PR on top of latest master? Hopefully that will help to be able to run the PR.

2021-12-10 14:49 UTC, mposolda commented
@pravsjv Any update to the previous comment?

2022-01-14 03:24 UTC, pravsjv commented
@mposolda Sorry for the delay in responding. Raised the pull request with proper github ID and incorporating the review comments. Here is the pull request for the same - https://github.com/keycloak/keycloak/pull/9561

2022-01-20 16:37 UTC, closed without merging