KEYCLOAK-19037 Problems with validation of Email field that contains uppercase character
keycloak/keycloak pull request #8376
Opened 2021-08-18 12:24 UTC by mabartos

[KEYCLOAK-19037](https://issues.redhat.com/browse/KEYCLOAK-19037) Register user page - problems with validation of Email field that contains uppercase character

@mposolda @pdrozd Could you please take a look at it? Thank you

2021-08-18 13:00 UTC, mposolda approved these changes
@mabartos Thanks for the PR! Approving assuming the tests will pass.

2021-08-18 15:33 UTC, mposolda requested changes
@mabartos The failed test in AccountRestServiceTest looks like a regression of this change :/ Do you have a chance to take a look? Thanks!

2021-08-19 07:49 UTC, mabartos commented on server-spi-private/src/main/java/org/keycloak/userprofile/DefaultAttributes.java
> +                    .filter(Objects::nonNull)
@mposolda I added this filter in order to avoid an unexpected behavior.

2021-08-19 08:26 UTC, mposolda approved these changes
@mabartos Thanks, hopefully GH actions will pass this time.

2021-08-19 09:13 UTC, merged