KEYCLOAK-19388 correct AttributeConsumingService bug in SAML SP metadata
keycloak/keycloak pull request #8471
Opened 2021-09-24 07:53 UTC by cgeorgilakis

2021-10-03 16:05 UTC, vramik requested changes
Thank you @cgeorgilakis for the PR, LGTM ... I just have few suggestions regarding the test. Please see inline, that same applies to the 3rd test as well.

2021-10-03 16:05 UTC, vramik commented on testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcSamlSpDescriptorTest.java
> +            assertThat(spDescriptor.getAttributeConsumingService().get(0).getRequestedAttribute().isEmpty(), is(false));
```suggestion
            assertThat(spDescriptor.getAttributeConsumingService().get(0).getRequestedAttribute(), notNullValue());
            assertThat(spDescriptor.getAttributeConsumingService().get(0).getRequestedAttribute(), not(empty()));
```

2021-10-03 16:05 UTC, vramik commented on testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcSamlSpDescriptorTest.java
> +            Assert.assertTrue(spDescriptor.getAttributeConsumingService().get(0).getServiceName() != null);
```suggestion
            assertThat(spDescriptor.getAttributeConsumingService().get(0).getServiceName(), notNullValue());
```

2021-10-04 08:51 UTC, cgeorgilakis commented
I did the requested changes in tests

2021-10-04 09:27 UTC, vramik approved these changes
Thank you @cgeorgilakis

2021-10-06 08:18 UTC, toby78 commented
Could anyone review this pull request please?

2021-10-21 18:24 UTC, hmlnarik approved these changes
Approving based on @vramik's review

2021-10-21 18:24 UTC, merged

2021-10-21 22:52 UTC, lscorcia commented
Unfortunately this change has introduced hardcoded references to the user attribute mapper `"saml-user-attribute-idp-mapper"` , which broke https://github.com/keycloak/keycloak/pull/8312 .

I will rebase my pull request removing the hardcoded string with the appropriate detection of the `SamlMetadataDescriptorUpdater` interface.