[KEYCLOAK-18255] - Vault Support in Dist.X
keycloak/keycloak pull request #8659
Opened 2021-10-27 23:49 UTC by pedroigor

2021-10-29 15:06 UTC, DGuhr submitted a review, later dismissed

2021-11-01 08:35 UTC, stianst requested changes
The DefaultProvider should be removed as we don't want special cases like these, and should rather handle this with existing logic, and with introducing a better "extensions" support in the future.

We should have two providers for Quarkus; one for files and one for hashicorp. The hashicorp should have higher priority, but only be enabled when hashicorp is configured for Quarkus. That will result in the correct provider being selected.

With an extension type thing in the future we can similarly have extensions that are enabled/disabled at build-time.

2021-11-02 01:06 UTC, pedroigor commented
@stianst @DGuhr Some update:

* There is a UX issue w.r.t. the configuration options available for Hashicorp Vault. We only advertise those we explicitly support, so the other settings inherited from `quarkus-vault` are not available in the help message (e.g.: authentication, etc). I'm not sure if we should add individual properties from Quarkus or if we should just mention in help/docs that more configuration options are available from `quarkus-vault` extension. Or perhaps we only enable the file-based one for now and discuss later how to deal with this particular problem in a more generic way (once we support more extensions from Quarkus, we would probably need the same approach).

2021-11-03 12:20 UTC, stianst approved these changes

2021-11-03 12:23 UTC, DGuhr approved these changes
LGTM

2021-11-03 12:23 UTC, merged