8793 Unable to find default UserProfile provider with multiple implementations
keycloak/keycloak pull request #8794
Opened 2021-11-11 09:05 UTC by mabartos

Recently, there was a PR with a new implementation of UserProfile provider in testsuite and GH actions were executed successfully. However, our remote tests have started to fail. As described in attached GH issue, it was caused by the wrong setting of default provider for UserProfile. We didn't catch the bug in GH actions, because in testsuite, there's a file `keycloak-server.json`, where the default provider is set up. However, for remote auth-server, the file is not provided there and we were not able to execute those tests, because when we called `session.getProvider(UserProfileProvider.class)`, we didn't know about the default provider for UserProfile.

Closes #8793 

@pedroigor Could you please take a look at it? Thank you.
I'll execute the remote tests.

2021-11-11 09:09 UTC, mabartos commented on testsuite/integration-arquillian/tests/base/src/test/resources/META-INF/keycloak-server.json
> +        "provider": "${keycloak.userProfile.provider:}",
When we don't specify the default provider here, we can test the default settings for distribution of Keycloak Server and if the default provider is not set up, the tests will fail, which is expected and will be revealed earlier.

2021-11-11 11:29 UTC, stianst requested changes
It shouldn't be needed to define a default provider in standalone.xml, that can be done by adding priorities to the providers instead.

https://github.com/keycloak/keycloak/blob/36da2d20e97a10821c7305881d3ffa343b5ad001/services/src/main/java/org/keycloak/services/DefaultKeycloakSessionFactory.java#L231-L259

The correct fix here should be to add override order in DeclarativeUserProfileProvider to make it the default.

2021-11-11 14:55 UTC, mabartos commented
@stianst Thanks for your review! You're right. It's better solution for that.

2021-11-11 15:27 UTC, pedroigor submitted a review, later dismissed
@mabartos Thanks !

2021-11-11 15:29 UTC, pedroigor commented
@mabartos Not sure why undertow tests failed. Quarkus and Wildfly are happy. Started a new run.

2021-11-11 15:32 UTC, mabartos commented
@pedroigor Thanks! However, I'll use the approach, what @stianst suggested. I'll update it soon.

2021-11-11 15:40 UTC, pedroigor commented
@mabartos @stianst Sorry, I did not notice the comments here. Proposed changes should work better, yeah.

2021-11-12 07:27 UTC, mabartos commented
@stianst @pedroigor Pipeline tests passed. See https://keycloak-jenkins.com/job/universal-test-pipeline-adapters/740/ and https://keycloak-jenkins.com/job/universal-test-pipeline-server/929/

2021-11-12 10:37 UTC, pedroigor approved these changes

2021-11-12 13:50 UTC, miquelsi approved these changes
Thanks Martin!

2021-11-15 07:46 UTC, stianst approved these changes

2021-11-15 07:46 UTC, merged