[KEYCLOAK-19798] - Filtering options based on the command
keycloak/keycloak pull request #8852
Opened 2021-11-19 00:40 UTC by pedroigor

2021-11-19 09:01 UTC, DGuhr requested changes
- Tried it locally:
- start -h only shows runtime: ✅
- start-dev -h only shows runtime: ❌ - also shows builtime and helpmsg last sentence is then misleading (see images)


![Screenshot 2021-11-19 at 09 53 43](https://user-images.githubusercontent.com/89905860/142595127-54194f89-3a75-4c7d-9d06-2c92d79bd32e.png)
![Screenshot 2021-11-19 at 09 57 19](https://user-images.githubusercontent.com/89905860/142595137-ee37d769-e46a-49a8-aadf-60341acf6677.png)

- start --auto-build -h shows all: ✅
- build -h shows buildtime only: ✅
- build -ha shows all ✅
- start -ha shows same as start -h ✅ (but -ha not mentioned in help msg, which is fine for me as -h and -ha show same output here)

- please check start-dev behaviour. I went through our list to check expected behaviour:

```
# Shows build ops only
kc.sh build --help (Done)
 
# Shows all ops
kc.sh build --help-all (Done)
 
# Shows runtime ops only
kc.sh start --help (Done)
 
# Shows runtime ops only
kc.sh start-dev --help (Done)
 
# Show all ops
kc.sh start-dev --help-all (Done)
 
# Show all ops
kc.sh start --auto-build --help (Done)

```

- some typos, and one suggestion for the Options: heading
- totally fine with `-ha` as abbreviation. I don't think it's commonly used for anything else.

2021-11-19 10:59 UTC, pedroigor commented on quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Help.java
> +    private static final String DEFAULT_OPTION_LIS_HEADING = "Options:";
I'm not sure, that header refers to the "general options" and not the options we are mapping and grouped.

2021-11-19 11:04 UTC, pedroigor commented
@DGuhr Could you please elaborate more why `start-dev` is wrong? It should show only runtime by default and include build ones if using the new help option, no?

2021-11-19 11:21 UTC, pedroigor commented
@DGuhr @stianst It should also be possible to filter options based on their categories too. Something like:

```
kc.sh [-h|-ha] <category>
```

Perhaps we can discuss more about it and work on that in a separate PR.

2021-11-19 13:46 UTC, pedroigor commented
@DGuhr Sorry, i missed the features options excluded properly. It should be fixed now.

2021-11-19 14:01 UTC, DGuhr commented on quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Help.java
> +    private static final String DEFAULT_OPTION_LIS_HEADING = "Options:";
np

2021-11-19 14:03 UTC, DGuhr submitted a review, later dismissed
lgtm now :) nice work!

2021-11-22 12:18 UTC, stianst approved these changes

2021-11-22 12:24 UTC, DGuhr approved these changes

2021-11-22 13:17 UTC, merged