Fix for KEYCLOAK-18914 - Base64 decoding
keycloak/keycloak pull request #9355
Opened 2021-12-28 21:38 UTC by hc42

Fixed https://issues.redhat.com/browse/KEYCLOAK-18914

- Do not try to gzunzip based on input stream content as this may lead to unexpected behaviour in some cases were the data is not gzip encoded (e.g. random input as described in the but ticket). Use option flags instead for explicit control.
- Unify two parallel exiting implementations of the Base64 class (they already started diverging in maintenance).

2022-01-03 10:42 UTC, mposolda requested changes
@hc42 Thanks for the fix! The fix itself looks good to me as long as all the tests will pass.

Just one small thing: We are moving from JIRA to GH issues. Is it possible if you create new GH issue for this (It should be ok to add just small description as "See https://issues.redhat.com/browse/KEYCLOAK-18914 for the details") and change the commit message in this PR to link to this GH issue? See https://github.com/keycloak/keycloak/blob/main/CONTRIBUTING.md for the details.

2022-01-03 14:14 UTC, stianst commented
Java has had Base64 support built-in since 1.8, and we do not support any older versions any longer. So would it not be better to just switch to the built-in support in Java?

https://docs.oracle.com/javase/8/docs/api/java/util/Base64.Decoder.html

2022-01-03 14:40 UTC, hmlnarik commented
Base64 is used in SAML adapters. Have we ceased supporting EAP 6.4 adapters already?

2022-01-03 15:23 UTC, stianst commented
> Base64 is used in SAML adapters. Have we ceased supporting EAP 6.4 adapters already?

No, but EAP 6.4 surely isn't supported on older Java than 1.8?

2022-01-03 19:04 UTC, hmlnarik commented
> > Base64 is used in SAML adapters. Have we ceased supporting EAP 6.4 adapters already?
> 
> No, but EAP 6.4 surely isn't supported on older Java than 1.8?

It is [1] supported until 2025 [2].

I would also prefer removing the need to keep jdk 7 classes as it became a blocker for many features. However for this PR I'd rather keep Base64 implementation in the codebase and treat this issue separately.

[1] https://access.redhat.com/articles/111663
[2] https://access.redhat.com/support/policy/updates/jboss_notes/#p_eap

2022-01-03 20:32 UTC, hc42 commented
Hi,
I updated the commit message with the new Github issue as proposed by @mposolda . I also rebased to the current main branch (commit 208e45c).

2022-01-04 06:14 UTC, stianst commented
> > > Base64 is used in SAML adapters. Have we ceased supporting EAP 6.4 adapters already?
> > 
> > No, but EAP 6.4 surely isn't supported on older Java than 1.8?
> 
> It is [1] supported until 2025 [2].
> 
> I would also prefer removing the need to keep jdk 7 classes as it became a blocker for many features. However for this PR I'd rather keep Base64 implementation in the codebase and treat this issue separately.
> 
> [1] https://access.redhat.com/articles/111663
> [2] https://access.redhat.com/support/policy/updates/jboss_notes/#p_eap
> 
> 

Sure, 6.4 is supported until 2025, but Java 1.7 hasn't been supported for over a year: https://access.redhat.com/articles/1299013

2022-01-06 17:05 UTC, mposolda approved these changes
@stianst @hmlnarik Ok, I am merging this.

@hc42 Thanks for the clarification regarding commit message.

2022-01-06 17:05 UTC, merged

2023-01-19 11:11 UTC, hshort commented on common/src/main/java/org/keycloak/common/util/Base64.java
> +     *     <i>Note: Technically, without line break your encoding may become non-compliant (see rfc2045 and rfc4648).</i>
Unfortunately adding line breaks causes many SAML Service Providers to fail validating signatures. This is a blocking issue for people being able to upgrade Keycloak now.