Check permissions before partially importing
keycloak/keycloak pull request #9404
Opened 2022-01-06 10:30 UTC by UXabre

This does extra checks to see if the user is actually authorized to do the importing of e.g. clients, clientroles, users, ...

This solves issue: https://github.com/keycloak/keycloak/issues/9387

2022-09-19 06:15 UTC, UXabre commented
Could somebody take a look at this PR please? It's been open for quite some time now.

2024-03-15 07:26 UTC, stianst approved these changes

2024-03-15 08:58 UTC, stianst requested changes
The code has changed to introduce running this in a transaction, not sure why and that doesn't make much sense to me, but regardless this PR would need tweaking to accommodate that. It would probably also be good to add some tests for this.

2025-07-21 10:22 UTC, stianst commented
Closing this as it's outdated. It also doesn't make all that much sense as manage-realm is a super admin role that in effect gives the user ability to do anything within the realm.

2025-07-21 10:22 UTC, closed without merging