Closes #9573: Add Github Workflow that follows Build Instructions
keycloak/keycloak pull request #9574
Opened 2022-01-14 15:04 UTC by guusdk

The assert that the build instructions, as documented in `/docs/building.md`, will work, this commit adds a Github Workflow that periodically (once a week) executes the build instructions as documented there.

2022-01-27 14:44 UTC, stianst requested changes
I'm not in favour of adding this. It's pretty much doing what the existing tests are doing, and is not going to catch anything beyond that. This will just end up being a workflow that runs periodically that no-one maintains or checks the output from.

2022-01-27 15:17 UTC, guusdk commented
Although in theory, the existing tests should cover this in theory, that does not seem to be the case in practise.

The existing workflows are very elaborate, and split things out in multiple steps. That's quite different from the very simple build instructions provided in the documentation. Following those (on a machine not used for building Keycloak before), those instructions won't get you a successful build (even if we disregard the test failures that are happening lately).

Verification of that 'basic build' is the added benefit of this workflow, but I agree that it is of limited benefit - especially if results are going to be ignored. On the other hand, for _new_ users, having build instructions that do not work is maddingly frustrating.

2022-01-28 08:45 UTC, stianst commented
Solution to that issue is probably more in terms of clean-up of the modules, as well as update the build instructions. 

I've honestly not done a `mvn clean install` from the root for years due to the time it takes. So, could be better to not include the testsuite by default, and make that an explicit thing that needs to be built/ran separately.

2022-01-28 08:55 UTC, stianst commented
Created a discussion topic on this:
https://github.com/keycloak/keycloak/discussions/9857

For now I'm going to close this, as I think we should rather fix the problem properly and make it easier to build Keycloak for everyone.

2022-01-28 09:07 UTC, closed without merging