Closes #9498 - Fix cases when user is forced to re-authenticate
keycloak/keycloak pull request #9580
Opened 2022-01-14 16:02 UTC by mposolda

2022-01-24 08:39 UTC, mposolda commented
@stianst @pedroigor Does anyone of you has a chance to review this please? See description for more details

2022-01-28 11:15 UTC, stianst commented
Tested this out with the admin console and Chrome developer console by running `auth.authz.login({maxAge: 1})`. It's now not letting me change the username which is nice, but spotted another issue. 

There's the action to `Restart login`, which should let me switch to a different user, but it doesn't as I just get taken straight back to the same screen asking me to re-authenticate.

![image](https://user-images.githubusercontent.com/2271511/151537638-bde43c42-08ca-4184-996c-9a16b79f9891.png)

Clicking on the `Restart login` just takes me back to the same page and doesn't let me actually restart the login to switch to a different user.

2022-01-28 11:18 UTC, stianst commented on services/src/main/java/org/keycloak/authentication/authenticators/browser/AbstractUsernameFormAuthenticator.java
> +    protected static final String USER_SET_BEFORE_USERNAME_PASSWORD_AUTH = "USER_SET_BEFORE_USERNAME_PASSWORD_AUTH";
Maybe rename to `USER_ALREADY_SET`?

2022-01-28 11:28 UTC, stianst requested changes
Looks pretty good, two things perhaps:

* Not able to restart the login to switch to a different user
* Tests don't cover where there are multiple identity providers, and user has link to only one or a few of the registered providers, and only the linked idps are shown when re-auth

2022-01-31 09:56 UTC, mposolda commented
> Looks pretty good, two things perhaps:
> 
>     * Not able to restart the login to switch to a different user

Yes, so far I've did it in a way that click the link will _Restart RE-authentication_ rather than _Restart authentication_ . So user re-authentication starts from the beginning (EG. When he is on the 2nd-factor authentication screen, he will be switched back to the initial screen with 1st-level authentication, but his username is still the same).

Changing it in the way you proposed will likely mean SSO session logout. As we currently does not have support for something like single SSO session for 2 different users. Is it ok to do SSO logout?

One addition to this is, that when user press "Restart link" during re-authentication, there can be another confirmation screen shown like _Restart of the login will logout your current session and you will authenticate from the beginning. Do you really want to logout?_ And SSO logout will be performed just when user confirms this.

> 
>     * Tests don't seem to cover where there are multiple identity providers, and user has link to only one or a few of the registered providers, and only the linked idps are shown when re-auth

I've added the scenario for this in the ReAuthenticationTest. There is added link for github IDP with the admin REST API and then checking that only "github" link is available on the login screen during re-authentication: https://github.com/keycloak/keycloak/blob/ee45e9f47ba3bf303558c1ecdf7b630c0ac16e9a/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/ReAuthenticationTest.java#L252 .

There is similar scenario tested also for identity-first. Isn't this ok as coverage?

2022-01-31 10:04 UTC, stianst commented
If user clicks on "re-auth" option I would simply go ahead and invalidate the current session and start from scratch. Don't think a confirmation is strictly needed?

2022-01-31 10:05 UTC, stianst commented
For checking only idps that should be shown are, it seems that's okay then.

2022-01-31 10:08 UTC, mposolda commented
> If user clicks on "re-auth" option I would simply go ahead and invalidate the current session and start from scratch. Don't think a confirmation is strictly needed?

Yeah, ok. It is easier without confirmation. Eventually we can add it as a follow-up (if someone asks for it). I will update PR for this.

2022-02-02 08:08 UTC, mposolda commented
@stianst I've updated PR as we discussed, so the "Restart flow" will allow to login from the scratch with different username/password. Do you have a chance to re-review please?

2022-02-07 08:01 UTC, stianst approved these changes

2022-02-07 08:02 UTC, merged

2023-02-28 11:07 UTC, aghArdeshir commented
Hello. I know this is not a Q&A, but I ended up here after a lot of investigation. Hoping for an answer.

In my application, sometimes users end up in this page, when their email/username is already filled up in the header (kc-attempted-username) and they are only prompted for password. With a reset-login-link active here.

But, if they try opening my app on another tab, they will be already logged in and everything works; so the re-authentication is actually unnecessary.

I couldn't find anything in the docs, now I'm wondering if there is a way to prevent this page from happening at all. I kinda find the essence of this state happening at all questionable:
![image](https://user-images.githubusercontent.com/5755214/221836280-8b112b7a-fcff-4d01-927c-adda10897e72.png)