9847 Applying editorial changes
keycloak/keycloak pull request #9883
Opened 2022-01-29 00:56 UTC by andymunro

@stianst I made changes along the following lines:
* Change to avoid first person plural (we) which is inconsistent with Keycloak style
* Removed contractions
* Changed task sections to be gerunds and concept sections to nouns.
* Made the text more concise.

2022-01-29 07:07 UTC, DGuhr commented on docs/guides/src/main/server/containers.adoc
> +For the best start up of your Keycloak container, build an optimized container image by running the `build` step immediately before starting.
Process-wise, this doesn't have to happen immediately before starting, it just has to happen any time before you start it. Suggestion: remove "immediately" completely.

2022-01-29 07:27 UTC, DGuhr requested changes

2022-01-29 07:27 UTC, DGuhr commented on docs/guides/src/main/server/containers.adoc
> +This approach significantly increases startup time and creates image that is mutable, which is not the best practice.
```suggestion
This approach significantly increases startup time and creates an image that is mutable, which is not the best practice.
```

2022-01-29 07:27 UTC, DGuhr commented on docs/guides/src/main/server/containers.adoc
> +For the best start up of your Keycloak container, build an optimized container image by running the `build` step immediately before starting.
```suggestion
For the best start up of your Keycloak container, build an optimized container image by running the `build` step before starting.
```

2022-01-29 07:27 UTC, DGuhr commented on docs/guides/src/main/server/containers.adoc
> +Running this command starts a Keycloak server that detects and applies the build configuration first.
```suggestion
Running this command starts a Keycloak server that detects and applies the build options first.
```
See #9709 for details about the general naming. "Build configuration" might be a bit ambiguous here.

2022-01-31 17:35 UTC, DGuhr approved these changes

2022-02-02 07:43 UTC, stianst approved these changes

2022-02-02 07:43 UTC, merged